import { useEffect, useMemo, useState } from 'react'
import type { SymbolLibrary } from '../types'
import { GROSSLUEFTER, GROSSLUEFTER_BODY, GROSSLUEFTER_FAN, LUEFTER_EXTRACT, composeGrossluefterSvg } from './symbolRender'

export interface SymbolsApi {
  ready: boolean
  order: string[]
  symbols: SymbolLibrary['symbols']
  byName: Record<string, string>   // name -> svg markup
}

const EMPTY: SymbolsApi = { ready: false, order: [], symbols: [], byName: {} }

// WebKit/Safari (the iPad target) doesn't reliably honour `dominant-baseline="central"` on inline
// <text>, so a symbol's baked letter falls back to the alphabetic baseline and sits low / off-centre
// in its glyph. Swap it for a font-relative dy that centres uppercase glyphs identically in EVERY
// browser (≈0.35em down from the baseline lands the cap-height midpoint on the anchor point). Any
// intentional per-symbol y-offset is preserved — the dy stacks on top and scales with font-size.
// Applied at load so it normalises whatever dataset version the backend or the bundled copy serve.
const centerSymbolText = (svg: string) => svg.replace(/\s*dominant-baseline="central"/g, ' dy="0.35em"')

export function useSymbols(): SymbolsApi {
  const [lib, setLib] = useState<SymbolLibrary | null>(null)

  useEffect(() => {
    let alive = true
    // The bundled /public copy is the KP-Front-authored FKS pack + order (generated by
    // tools/gen_symbols.py) — it owns which symbols exist and in what category order. The backend
    // reference dataset only supplies updated glyph ARTWORK, overlaid by name; it can't reorder
    // or drop the authored set (that previously masked frontend symbol edits behind a stale backend).
    fetch(`${import.meta.env.BASE_URL}tactical-symbols.json`)
      .then((r) => r.json())
      .then((base: SymbolLibrary) => {
        if (!alive) return
        setLib(base) // show the authored set immediately (works standalone / offline)
        // then try the backend purely for fresher glyph art; ignore its order + extra symbols
        fetch('/api/reference/symbols:tactical')
          .then((r) => (r.ok ? r.json() : null))
          .then((bk: SymbolLibrary | null) => {
            if (!alive || !bk?.symbols?.length) return
            const art: Record<string, string> = {}
            for (const s of bk.symbols) art[s.name] = s.svg
            setLib({ order: base.order, symbols: base.symbols.map((s) => (art[s.name] ? { ...s, svg: art[s.name] } : s)) })
          })
          .catch(() => {}) // backend optional — the bundled art stands
      })
      .catch((e) => console.error('Symbolbibliothek konnte nicht geladen werden', e))
    return () => { alive = false }
  }, [])

  return useMemo<SymbolsApi>(() => {
    if (!lib) return EMPTY
    // normalise every glyph's text-centering once, up front, so both the palette (which renders
    // s.svg directly) and every byName consumer get the cross-browser-centred version.
    const all = lib.symbols.map((s) => ({ ...s, svg: centerSymbolText(s.svg) }))
    const byName: Record<string, string> = {}
    for (const s of all) byName[s.name] = s.svg
    // the Lüfter's extract/Absaugen glyph is a render-only variant reached via the symbol's
    // Luftrichtung toggle — keep it in byName (above) but drop it from the pickable palette.
    const symbols = all.filter((s) => s.name !== LUEFTER_EXTRACT)
    // synthesise the composite Grosslüfter from the two authoritative FireGIS glyphs (vehicle +
    // fan) so it appears in the palette without hand-authoring artwork that could drift from the
    // source. byName carries the static composite (thumbnail/fallback); the map/plan render the
    // two layers separately for independent rotation. Placed in the Fahrzeuge/Mittel category.
    if (byName[GROSSLUEFTER_BODY] && byName[GROSSLUEFTER_FAN] && !byName[GROSSLUEFTER]) {
      const cat = symbols.find((s) => s.name === GROSSLUEFTER_FAN)?.cat ?? 'Fahrzeuge / Mittel'
      const svg = composeGrossluefterSvg(byName[GROSSLUEFTER_BODY], byName[GROSSLUEFTER_FAN])
      symbols.push({ name: GROSSLUEFTER, cat, svg })
      byName[GROSSLUEFTER] = svg
    }
    return { ready: true, order: lib.order, symbols, byName }
  }, [lib])
}
