import { useEffect, useMemo, useState } from 'react'
import type { SymbolLibrary } from '../types'
import { GROSSLUEFTER, GROSSLUEFTER_BODY, GROSSLUEFTER_FAN, HUBRETTER, COMPOSITE_PART_GLYPHS, composeCompositeSvg } from './symbolRender'

export interface SymbolsApi {
  ready: boolean
  order: string[]
  symbols: SymbolLibrary['symbols']
  byName: Record<string, string>   // name -> svg markup
}

const EMPTY: SymbolsApi = { ready: false, order: [], symbols: [], byName: {} }

// WebKit/Safari (the iPad target) doesn't reliably honour `dominant-baseline="central"` on inline
// <text>, so a symbol's baked letter falls back to the alphabetic baseline and sits low / off-centre
// in its glyph. Swap it for a font-relative dy that centres uppercase glyphs identically in EVERY
// browser (≈0.35em down from the baseline lands the cap-height midpoint on the anchor point). Any
// intentional per-symbol y-offset is preserved — the dy stacks on top and scales with font-size.
// Applied at load so it normalises whatever dataset version the backend or the bundled copy serve.
const centerSymbolText = (svg: string) => svg.replace(/\s*dominant-baseline="central"/g, ' dy="0.35em"')

export function useSymbols(): SymbolsApi {
  const [lib, setLib] = useState<SymbolLibrary | null>(null)

  useEffect(() => {
    let alive = true
    // ONE source: the bundled /public pack, KP-Front-authored and generated by
    // tools/gen_symbols.py. It owns which symbols exist, in what category order, AND their art.
    //
    // ⚠️ There used to be a second stage here that overlaid glyph artwork from the backend
    // dataset `symbols:tactical`, «purely for fresher glyph art». It could not be fresher, and
    // that was the bug (found 01.09.): `seed_reference` copies this very file into the database
    // ONCE, on a deployment's first boot, and never touches it again. So the row is frozen at
    // whatever the pack looked like the day that station was set up, and it silently reverted
    // every artwork change we shipped afterwards — for the symbols it already knew.
    //
    // It failed in the most confusing way possible: NEW symbols appeared (no row for that name,
    // so the bundled art stood) while CHANGED ones stayed old, in the same palette. And the
    // printed Kroki was right the whole time, because kroki.py reads the FILE — so the paper and
    // the screen disagreed about what a symbol looks like.
    //
    // A backend copy can only ever be equal to or older than the file the app was built with, so
    // the whole stage could only lose. Restoring some form of per-station artwork means giving
    // the dataset a version the app can compare — not trusting it by default.
    fetch(`${import.meta.env.BASE_URL}tactical-symbols.json`)
      .then((r) => r.json())
      .then((base: SymbolLibrary) => { if (alive) setLib(base) })
      .catch((e) => console.error('Symbolbibliothek konnte nicht geladen werden', e))
    return () => { alive = false }
  }, [])

  return useMemo<SymbolsApi>(() => {
    if (!lib) return EMPTY
    // normalise every glyph's text-centering once, up front, so both the palette (which renders
    // s.svg directly) and every byName consumer get the cross-browser-centred version.
    const all = lib.symbols.map((s) => ({ ...s, svg: centerSymbolText(s.svg) }))
    const byName: Record<string, string> = {}
    for (const s of all) byName[s.name] = s.svg
    // the composite overlay parts (the reversed-airflow Lüfter, the Drehleiter ladder, the Hubretter
    // boom) are render-only glyphs reached only as a composite's overlay — keep them in byName (above)
    // for rendering but drop them from the pickable palette.
    const partGlyphs = new Set(COMPOSITE_PART_GLYPHS)
    const symbols = all.filter((s) => !partGlyphs.has(s.name))
    // synthesise the composite Grosslüfter from the two authoritative FireGIS glyphs (vehicle +
    // fan) so it appears in the palette without hand-authoring artwork that could drift from the
    // source. byName carries the static composite (thumbnail/fallback); the map/plan render the
    // two layers separately for independent rotation. Inserted right AFTER the Hubretter (the
    // crews' Fahrzeuge order: Fahrzeug, Drehleiter, Hubretter, Grosslüfter, Boot, Pumpe, …), with
    // a fall-back to the end if the Hubretter is missing.
    if (byName[GROSSLUEFTER_BODY] && byName[GROSSLUEFTER_FAN] && !byName[GROSSLUEFTER]) {
      const cat = symbols.find((s) => s.name === GROSSLUEFTER_FAN)?.cat ?? 'Fahrzeuge / Mittel'
      const svg = composeCompositeSvg(byName[GROSSLUEFTER_BODY], byName[GROSSLUEFTER_FAN])
      byName[GROSSLUEFTER] = svg
      const at = symbols.findIndex((s) => s.name === HUBRETTER)
      const entry = { name: GROSSLUEFTER, cat, svg }
      if (at >= 0) symbols.splice(at + 1, 0, entry); else symbols.push(entry)
    }
    return { ready: true, order: lib.order, symbols, byName }
  }, [lib])
}
