// English copy · Anwesenheit, Anrückend, Zeitplan and Schichten.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/anwesenheit.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'anwesenheit' | 'anrueckend' | 'zeitplan' | 'schichten'

export const anwesenheitCopy: Localizable<Pick<Copy, Keys>> = {
  anwesenheit: {
    title: 'Attendance',
    // taking on a function also puts you on the attendance list; the remark is filled in only
    // when nobody wrote one by hand
    noteLabel: 'Remark',
    notePlaceholder: 'e.g. driver TLF',
    logNote: '{name} – remark: {note}',
    logPresentAs: '{name} present – {role}',
    logRoleGroup: 'Under {role}: {list}',
    logRoleGroupTrupp: 'In a team: {list}',
    undoTap: 'Undo the last tap',
    redoTap: 'Redo the tap',
    undone: 'Attendance undone: {names}',
    redone: 'Attendance redone: {names}',
    roleEinsatzleiter: 'Incident commander',
    roleEinsatzleiterShort: 'IC',
    roleEinsatzleiterStv: 'Deputy incident commander',
    roleEinsatzleiterStvShort: 'Dep. IC',
    roleFahrer: 'Driver {vehicle}',
    roleBedienung: 'Operator {symbol}',
    roleOffizier: 'Officer {funktion}',
    roleAtemschutz: 'SCBA',
    roleTrupp: 'Team',
    // the Gruppenführer's own Funktion — ONE hyphenated token, so it stays unambiguous inside the
    // comma list a Bemerkung is («SCBA-Lead, Driver TLF»). See the German base for the reasoning.
    roleLeader: '{role}-Lead',
    roleOffizierPlain: 'Officer',
    alreadyBooked: '{role}',
    // hints, never blocks
    conflictUnderPa: '{name} is under SCBA – team {trupp}.',
    conflictInTrupp: '{name} is in team {trupp}.',
    statusUnderPa: 'under SCBA',
    statusInTrupp: 'in a team',
    conflictElInTrupp: '{name} is incident commander and also in team {trupp}.',
    conflictLeft: '{name} is recorded as «left».',
    summary: '{present} present',
    summaryLeft: '{left} left',
    reload: 'Reload crew',
    loading: 'Loading …',
    searchPlaceholder: 'Search …',
    ortScene: 'On scene',
    ortStation: 'Station',
    ortToScene: 'Send {name} to the scene',
    ortToStation: 'Put {name} at the station',
    logOrtScene: '{name} on scene',
    logOrtStation: '{name} at the station',
    summaryOrt: '{scene} on scene · {station} station',
    statusFrei: 'not present',
    filterLabel: 'Filter',
    statusAll: 'All',
    statusFilterLabel: 'Filter by status',
    noteOnly: 'With a note only',
    statusPresent: 'present',
    statusLeft: 'left',
    loadFailedTitle: 'Crew could not be loaded.',
    loadFailedHint: 'Offline or server unreachable. The last loaded list is preserved.',
    emptyTitle: 'No personnel recorded yet.',
    emptyHint: 'Personnel is entered or synced in the admin area.',
    emptyHintSync: 'Sync the crew from {provider}.',
    retry: 'Try again',
    lockedTitle: 'In a team – report the exit with «Report out» first',
    notInDivera: 'No longer on the crew list',
    notInSource: 'No longer in {provider}',
    weg: 'gone',
    rankFilterLabel: 'Filter by rank',
    rankAll: 'All',
    viewList: 'Present',
    viewPlan: 'Schedule',
    viewBands: 'Shifts',
    viewLabel: 'View',
    backAgain: 'Back again',
    von: 'from',
    bis: 'to',
    addBlock: 'New time from now',
    blockSplit: '{name}: new time – the running one was closed',
    blockRemoved: 'Time of {name} deleted',
    blockRemove: 'Delete time',
    blocksTitle: 'Attendance – {name}',
    blocksSection: 'Recorded times',
    blocksNone: 'Has not been present yet.',
    blocksHint: 'Each line is one real turn on site. Correct a time here when a stamp landed wrong.',
    openBlocks: 'Open attendance for {name}',
    openBlocksNote: 'Open attendance for {name} · note recorded',
    statusNote: 'Note',
    stillHere: 'still here',
    running: 'running',
    ended: 'finished',
    flip: 'switch',

    logPresent: '{name} present',
    logPresentAgain: '{name} present again',
    logLeft: '{name} left',
    logGuestAdded: '{name} recorded as an additional person',
    logGuestAddedAs: '{name} recorded as an additional person – {role}',
    addGuest: 'Add «{name}» as a guest',
    guestBadge: 'Guest',
    removeGuest: 'Delete person',
    presentOnlyOn: 'Present only — tap for the whole crew',
    presentOnlyOff: 'Whole crew — tap for present only',
    onlyPresent: 'Present only',
  },
  anrueckend: {
    title: 'On the way',
    sourceBare: 'Divera',
    coming: (n: number) => (n === 1 ? '1 coming' : `${n} coming`),
    notComing: (n: number) => (n === 1 ? '1 not coming' : `${n} not coming`),
    here: (n: number) => `${n} here`,
    notComingGroup: (n: number) => `Not coming (${n})`,
    notComingWord: 'not coming',
    checkIn: 'here',
    checkInLabel: '{name} is here – record as present',
    allHere: 'Everybody who said they would come is recorded.',
    unmapped: (n: number) => (n === 1 ? '1 answer from somebody not on the crew list' : `${n} answers from people not on the crew list`),
    hint: 'A Divera answer is not attendance – only «here» records somebody.',
    collapse: 'Collapse «On the way»',
    expand: 'Expand «On the way»',
  },
  // Shift bands (BandGrid) — the schedule transposed: columns are named windows, not hours.
  schichten: {
    title: 'Shifts',
    who: 'Who',
    addBand: 'Define a shift',
    addBandFirst: 'Define the first shift',
    emptyTitle: 'No shifts yet.',
    emptyHint: 'Set up the windows you want covered — after that each person is a single tap.',
    emptyAxisHint: 'Or draw times per person on the schedule.',
    sheetAddTitle: 'New shift',
    sheetEditTitle: 'Edit shift',
    labelField: 'Name',
    labelPlaceholder: 'Early',
    sheetHint: 'The shift is created for the whole crew. Every cell starts empty.',
    create: 'Create',
    save: 'Save',
    removeBand: 'Delete shift',
    removeBandHint: 'Deleting removes only the column \u2013 the assigned times stay on the schedule as free-hand entries.',
    removedBand: 'Shift \u00ab{label}\u00bb deleted',
    moveTitle: 'Move the assigned times too?',
    moveMsg: '{n} people are assigned to the old times. Should their times move with the shift?',
    moveYes: 'Move them',
    moveNo: 'Shift only',
    countsAria: '{available} available, {planned} assigned',
    available: 'available',
    confirmed: 'assigned',
    ownTimes: 'own times outside every shift: {times}',
    ownTimesMore: '{first} +{n}',
    deviating: '{name}: {from}\u2013{to} instead of {bandFrom}\u2013{bandTo}',
    cellAria: '{name} in {band}',
    cellFrom: 'from {t}',
    cellUntil: 'until {t}',
    partial: 'partly',
    partialHint: 'Not all of them cover the whole shift.',
    resolveTitle: 'Partly available, partly assigned',
    resolveMsg: '{name} is partly assigned and partly only available in {band}. What should hold for this window?',
    resolveGap: 'The rest of the shift is not covered by this person \u2013 that stays.',
    splitTitle: 'Will be split',
    splitChanges: 'changes',
    splitKeeps: 'stays {state}',
    splitNote: 'Only the piece inside the shift changes; everything outside stays as it is.',
    crossTitle: 'Reaches beyond the shift',
    crossMsg: 'This time of {name} runs past {band}. What should hold for this window?',
    resolveAvailable: 'All to available',
    resolveConfirmed: 'All to assigned',
    resolveCancel: 'Cancel',
    conflict: 'Assigned twice \u2013 two shifts at the same time',
    scrollHint: 'Scroll sideways for more shifts',

    editEntry: 'Edit …',
  },
  zeitplan: {
    title: 'Schedule',
    summary: '{planned} scheduled · {present} here now',
    summaryEmpty: 'Nothing scheduled yet',
    add: 'Shift',
    from: 'from',
    to: 'to',
    remove: 'Delete shift',
    removed: 'Shift {name} deleted',
    conflict: 'Overlaps another shift',
    conflictTitleOne: 'One person is assigned twice.',
    conflictTitleMany: '{n} people are assigned twice.',
    conflictWho: '{name} \u00b7 {from}\u2013{to}',
    conflictMore: '\u2026 and {n} more',
    conflictFix: 'Tap one of the two assignments and set it to \u00abavailable\u00bb \u2013 the time itself stays.',
    conflictShort: 'assigned twice',
    now: 'now',
    coverage: 'Cover',
    coverageHint: 'Three lines: grey available, blue assigned, green actually present – where the green line drops is the gap.',
    coverageExpand: 'Show the numbers – how many are available, assigned and present',
    coverageCollapse: 'Hide the numbers',
    planned: 'available',
    actual: 'present',
    emptyTitle: 'No shift scheduled yet.',
    emptyHint: 'Plan per person from when to when they are available. The schedule does not change attendance – that is still ticked in the attendance list.',
    legendHint: 'Outline = available · filled = assigned · green = actually present',
    print: 'Print schedule',
    sheetSchichtplan: 'Shift plan \u2026',
    sheetVerfuegbarkeiten: 'Availability \u2026',
    sheetSchichtplanTitle: 'Shift plan',
    sheetVerfuegbarkeitenTitle: 'Availability',
    peopleCount: (n: number) => (n === 1 ? '1 person' : `${n} people`),
    bandsCount: (n: number) => (n === 1 ? '1 shift' : `${n} shifts`),
    sheetContent: '{people} · as of {t}',
    sheetContentBands: '{people} · {bands} · as of {t}',
    sheetSchichtplanHint: 'Watches across the top, names down the side, ticks in between \u2013 the command form the crew knows.',
    sheetVerfuegbarkeitenHint: 'Who can do what, from when to when, shift or no shift \u2013 including everyone in none.',
    pdf: 'As PDF',
    paperMenu: 'To paper',
    printFailed: 'The schedule could not be printed.',
    who: 'Who',
    editTitle: 'Shifts – {name}',
    plannedSection: 'Availability & assignment',
    actualSection: 'Actually present',
    actualHint: 'Comes from attendance and is recorded there – the schedule does not change it.',
    actualNone: 'Has not been present yet.',
    plannedNone: 'No availability scheduled yet.',
    addShift: 'Add shift',
    stillHere: 'still here',
    done: 'Done',
    fromStart: 'from start',
    sheetHint: 'Adjust the times here · switch the state on the right · deleting only happens here.',
    laneHint: 'Drag to record availability · tap a bar to assign the person · drag to move the bar · press and hold to open the shifts',
    laneHintShow: 'Show controls',
    laneHintHide: 'Hide controls',
    available: 'available',
    confirmed: 'assigned',
    toggleHint: 'Tap to make it «{state}»',
    zoomIn: 'Narrower window',
    zoomOut: 'Wider window',
    horizonUntil: 'until {t}',
    horizon: 'Window',
    openFor: 'Open shifts for {name}',
    planAt: 'Plan a shift for {name}',
    dragFrom: 'Drag start',
    dragTo: 'Drag end',

    added: 'Shift planned for {name}',
    moved: '{name}\'s shift moved',
    brokenShift: 'This shift ends before it starts — tap to correct',
    running: 'running',
    ended: 'ended',
    flip: 'switch',
    editEntry: 'Edit …',
  },
}
