// English copy · the Trupps board (Atemschutz) and line decorations.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/atemschutz.ts.

import type { Copy, Localizable } from '../index'

export const atemschutzCopy: Localizable<Pick<Copy, 'atemschutz' | 'lineDecor'>> = {
  atemschutz: {
    title: 'SCBA monitoring',
    // the board title in the FULL app — it carries both sections since 03.09. (see de/atemschutz.ts)
    boardTitle: 'Teams',
    // the cut-off title is the door to the full incident details (09.09., see de/atemschutz.ts)
    headDetailOpen: 'Show incident details',
    headDetailTitle: 'Incident',
    sectionAtemschutz: 'SCBA',
    sectionAtemschutzEmpty: 'No team is under SCBA right now.',
    sectionPlain: 'Other teams',
    kindLabel: 'Type of team',
    kindAtemschutz: 'Under SCBA',
    kindPlain: 'Without SCBA',
    asMark: 'SCBA',
    empty: 'No team under monitoring yet.',
    emptyHint: 'Create a team to start monitoring.',
    newTrupp: 'Register team',
    shareLink: 'Hand over monitoring',
    shareLinkOn: 'Hand over monitoring – a link is active',
    linkReentryHint: 'The link leads back to this board – if the page is closed by accident, simply open the QR code again.',
    /** the «+ Trupp» tab on the handed-over phone board (AtemschutzView · focusMode) */
    liteNewTab: 'Team',
    /** the three-section stack on ANY phone (TruppForm · stack, 04.09.) – replaces the two-step
     *  wizard. Titles name the FIELDS; a collapsed section reads its own answer out beside the
     *  title, and «Order & line» is one section (see de/atemschutz.ts). */
    stackPressure: '{n} bar',
    // no longer asked in the Trupp form (04.09.) – still offered on the Lage/plan and in admin
    colorAuto: 'Automatic',
    // sync/clock status in the board header (see de/atemschutz.ts)
    syncStand: '{status} · {t}',
    clockSkewChip: 'Device clock is off ({d} min)',
    formCreateTitle: 'Register team',
    formEditTitle: 'Edit team',
    formRedeployTitle: 'Re-deploy',
    sectionTeam: 'Team',
    auftragLabel: 'Task',
    auftragOpen: 'No task yet',
    // DISPLAY labels for the Auftrag types, keyed by the auftrag id (stored value stays the id).
    auftragLabels: {
      retten: 'Rescue',
      loeschen: 'Extinguish',
      absuchen: 'Search',
      sichern: 'Secure',
      erkunden: 'Reconnoitre',
      verkehr: 'Traffic',
      sanitaet: 'Medical',
      wasser: 'Water supply',
      bereitstellung: 'Standby',
      anderes: 'Other',
    },
    equipmentLabels: {
      retthaube: 'Rescue hood',
      wbk: 'WBK',
      multiwarn: 'Multiwarn',
    },
    equipmentLabel: 'Equipment',
    equipmentShort: {
      retthaube: 'RH',
      wbk: 'WBK',
      multiwarn: 'MW',
    },
    zielLabel: 'Target',
    // ONE placeholder for every kind of team and every Auftrag (see de/atemschutz.ts): a storey reference
    // was SCBA vocabulary and read as nonsense under «Traffic».
    zielPlaceholder: 'Where / what …',
    zielClear: 'Clear target',
    leaderLabel: 'Team leader',
    teamSearchPlaceholder: 'Search person …',
    // the phone chip row (05.09.) — see de/atemschutz.ts for why the roster list is gone there
    teamSearchMore: 'Search another person …',
    teamHintChips: 'Tap a name = leader',
    leaderBadge: 'Leader',
    makeLeader: 'Make {name} team leader',
    teamRemove: 'Take {name} off the team',
    teamTaken: 'on a team',
    teamManual: 'guest',
    teamGuestAdd: 'Add «{name}» as a guest',
    lineNoLabel: 'Line',
    lineLegacyNote: 'Previously recorded: “{value}”',
    lineTyped: 'No. …',
    lineTakeTitle: 'Line {n} is taken',
    lineTakeMsg: 'Team {from} is on line {n}. Put team {to} on it instead?',
    lineTakeConfirm: 'Take over',
    lineHeldToast: 'Line is held by team {name}.',

    lineOptTaken: 'Team {name} is on this line',
    lineShow: 'Show line on the map',
    logLineLinked: 'Team {name} on line {n}',
    logLineUnlinked: 'Team {name}: line unlinked',
    lineUnlinkedToast: 'Line unlinked',
    markerLabel: 'SCBA team',
    markerNone: 'No team',
    markerPick: 'Take over a placed team',
    markerOptTaken: 'Belongs to team {name}',
    markerTakeTitle: 'Team {from} stands here',
    markerTakeMsg: 'This placed team belongs to team {from}. Hand it to team {to}?',
    markerTakeConfirm: 'Take over',
    logMarkerUnlinked: 'Team {name} is no longer placed',
    entryAskTitle: 'Send team in?',
    entryAskMsg: 'Team {name} is registered but has not gone in yet. Send them in now? The contact clock starts immediately.',
    entryAskCancel: 'Not yet',
    pressureLabel: 'Entry pressure',
    newPressureLabel: 'New entry pressure',
    funkkanalSection: 'Radio channel',
    funkkanalDown: 'Radio channel down',
    funkkanalUp: 'Radio channel up',
    funkkanalUnit: 'Channel',
    clearName: 'Clear name',
    notPresent: 'not present',
    noRoster: 'No crew available',
    assignedConflict: '{name} is already in another team.',
    // the one grip that resolves it — take them out of the other team and carry on here
    assignedTransfer: 'Move into this team',
    // …and when that grip is withheld: the other team is deployed, its contact clock running
    assignedConflictDeployed: '{name} is in a team that is deployed.',
    saveBlockedTeam: 'Add a team leader first.',
    auftragMissingHint: 'Task is missing – the team registers as «No task yet».',
    saveBlockedAuftrag: '«Other» needs a target.',
    saveBlockedPressure: 'Entry pressure is missing.',
    cancel: 'Cancel',
    save: 'Save',
    start: 'Register',
    reenterSubmit: 'Deploy',
    reenterStandby: 'Put on standby',
    reenterStandbyHint: 'Register the team as reserve – the contact clock only starts on «Deploy».',
    sinceContact: 'Since last contact',
    elapsed: 'Deployment time',
    outFor: 'Out for',
    outForPlain: 'No task for', // ⚠️ app only — see de/atemschutz.ts · outForPlain
    estimated: 'Estimated pressure',
    // the short form for the one line the Sockel leaves standing (09.09., see de/atemschutz.ts)
    estimatedShort: 'Estimate',
    estimatedHint: 'Planning aid – estimated using a {liters} L cylinder and {rate} L/min consumption until enough pressure history exists. Does not replace a pressure report.',
    estimatedHintHistory: 'Planning aid – projected from this team’s confirmed pressure consumption. Does not replace a pressure report.',
    estimatedSourceHistory: 'from {count} pressure values · as of {time}',
    estimatedSourceFallback: '{rate} L/min assumed · as of {time}',
    currentPressure: 'Pressure',
    lowestPressure: 'Lowest',
    alarmNote: 'Alarm pressure {bar} bar reached',
    alarmNoteEst: 'Alarm pressure {bar} bar – reached per estimate',
    lineField: 'Line',
    edit: 'Edit',
    pressureConfirm: 'Confirm',
    pressureConfirmHint: 'Confirm new pressure – counts as contact',
    verlauf: 'Log',
    cardMenu: 'More actions',
    bandPreEntry: 'Not yet deployed',
    bandRegisteredAt: 'registered at',
    zoneTimes: 'Times',
    lastContactAt: 'Last contact',
    nextContactDue: 'Next due',
    contactIntervalLabel: 'Contact interval',
    contactIntervalValue: '{min} min',
    verlaufLatest: 'last: {time} {what}',
    // ⚠️ EVENT words in this column («Art» / kind), never state words: the row says what happened,
    // and «Out» is what the card says about the team afterwards (status · outFor). Same split the
    // German base keeps — see the note there.
    readingKind: { registered: 'Registered', entry: 'Entry', contact: 'Contact', pressure: 'Pressure',
      alarm: 'Alarm pressure',
      rueckzug: 'Withdrawal',
      // ⚠️ the WITHDRAWAL was called off — nobody re-entered anything (see the German base)
      exit: 'Exit', resume: 'Withdrawal called off',
      paOn: 'Under SCBA', paOff: 'SCBA monitoring ended',
      notfall: 'Emergency raised', notfallEnde: 'Emergency ended',
      // a `crew` row prints its names (AtemschutzView · readingLabel); this is the fallback word
      crew: 'Crew',
    },
    readingNoAs: '{what} – without SCBA',
    clockOk: 'Contact ok',
    clockFrozen: 'As at the close',
    clockWarn: 'Contact due',
    clockOverdue: 'Overdue',
    rowDue: 'Due',
    clockAlarmPressure: 'Alarm pressure',
    clockAlarmLimit: 'Limit {bar} bar',
    overdueBadge: (n: number) => `${n} in alarm`,
    overdueBadgeGo: 'Go to team {name} – most urgent alarm',
    collapse: 'To overview',
    actEnter: 'Deploy',
    actContact: 'Contact',
    actRueckzug: 'Report withdrawal',
    actContinue: 'Continue',
    actExit: 'Report out',
    tileRueckzug: 'Withdraw',
    tileExit: 'Out',
    quickTrupp: 'Team {no}',
    kanalSheetHint: 'Tap picks and closes.',
    formPickTake: 'Apply',
    lineNone: 'none',
    lineChip: 'Line {n}',
    auftragAdd: '+ Task',
    actExitPlain: 'Task done', // ⚠️ app only — see de/atemschutz.ts · actExitPlain
    actReenter: 'Re-deploy',
    actNotDeployed: 'Not deployed',
    actNotDeployedHint: 'Close the team without it ever going on air — stays ready for a later deployment',
    statusNotDeployed: 'Not deployed',
    statusRemoved: 'Removed from board',
    logNotDeployed: 'Team {name} not deployed',
    remove: 'Remove',
    removeUnusedTitle: 'Team was never deployed',
    removeUnusedMsg: 'Stand {name} down as “not deployed” instead of removing it? The team stays ready on the board – “Remove” is for erroneous registrations.',
    place: 'Place',
    placeWhere: 'Place where?',
    placeNoTarget: 'No plan available – pick a building via «Building» in the rail first.',
    showOnPlan: 'Show on plan',
    showOnMap: 'Show on map',
    dockedAt: 'at «{host}»',
    dockLabel: '{who} · at «{host}»',
    dockedTeams: 'Docked',
    preEntryHint: 'Not deployed yet – press «Deploy» once the team goes on air.',
    alarmArmed: 'Alarm on – sound and notification · tap to mute',
    alarmMuted: 'Alarm muted – sound and notification, until this incident ends · tap to turn on',
    alarmBlocked: 'Sound not released – the browser refused it · tap, otherwise only the notification alerts',
    alarmBlockedNoFallback: 'Sound not released – tap to enable it. This browser cannot show a notification.',
    alarmDemoNote: 'Demo – sound and notification are disabled on this instance',
    restoreMenu: 'Removed teams',
    // the bell's WORD on a wide head (22.09.2026; the honest state stays in the tooltip/aria)
    alarmWord: 'Alarm sound',
    alarmMutedWord: 'Muted',
    alarmBlockedWord: 'Enable sound',
    restoreItem: 'Restore {name}',
    alarmNotifyTitle: 'SCBA overdue',
    alarmNotifyBody: 'Team {name} overdue – establish contact.',
    status: { angemeldet: 'Registered', aktiv: 'Deployed', rueckzug: 'Withdrawing', ueberfaellig: 'Overdue', raus: 'Out' },
    statusPlainOut: 'No task', // ⚠️ app only — see de/atemschutz.ts · statusPlainOut
    // how a team is NAMED in running text — see the German base for why the word is part of it
    truppTerm: 'Team {name}',
    logRegister: 'Team {name} registered – entry pressure {bar} bar',
    logRegisterPlain: 'Team {name} registered',
    logRenumbered: 'Team {name} is now Team {no}',
    logRenumberedChip: '{from} is now {to}',
    logPlaced: 'Team {name} placed on plan',
    logPlacedMap: 'Team {name} placed on the map',
    placeLage: 'Map',
    logEntry: 'Team {name}: entry',
    // ⚠️ the ENTRY rows say which kind of team went in — see the German base for why
    logEntryNoAs: 'Team {name}: entry – without SCBA',
    logSafetyEntry: 'Team {name}: safety team deployed',
    logContact: 'Team {name}: contact confirmed',
    logPressure: 'Team {name}: pressure {bar} bar',
    // ⚠️ says what HAPPENS instead of asserting a contact nobody confirmed — see the German base
    logRueckzug: 'Team {name} reports withdrawal – contact clock reset',
    // ⚠️ ONE row that takes the withdrawal back and says what holds instead — see the German base
    logContinue: 'Team {name}: withdrawal called off – deployment continued',
    logExit: 'Team {name}: exit',
    logExitBar: 'Team {name}: exit – remaining pressure {bar} bar',
    actPressure: 'Pressure',
    pressureSheetTitle: 'Pressure',
    pressureSheetHint: 'A tap saves it – counts as contact.',
    exitSheetTitle: 'Remaining pressure',
    exitSheetHint: 'A tap reports the team out – lowest value in the crew.',
    exitNoBar: 'Out without pressure',
    phoneSectionIn: 'Inside',
    phoneSectionReady: 'Ready',
    phoneSectionOut: 'Out',
    safetyTitle: 'Safety team',
    safetyPick: 'Designate',
    safetyPickTitle: 'Designate safety team',
    safetyPickNew: 'Register a new team (safety)',
    pinnedLabel: 'Teams due',
    contactEchoTitle: 'Contact already confirmed',
    contactEchoWho: 'Team {n}',
    contactEchoMsg: '{name} · {s} s ago on another device',
    contactEchoAgain: 'Confirm again',
    contactEchoOk: 'OK',
    editConflictOne: '{field} was changed on another device meanwhile: {now} – overwrite anyway?',
    editConflictMany: '{fields} were changed on another device meanwhile – overwrite anyway?',
    editConflictOverwrite: 'Overwrite',
    editConflictBack: 'Back to the form',
    editFieldLabels: { crew: 'Crew', auftrag: 'Task', ziel: 'Target', lineNo: 'Line', funkkanal: 'Radio channel', pressure: 'Entry pressure', kind: 'Team type', equipment: 'Equipment' },
    logFirstPressure: 'Team {name}: contact – first pressure report {bar} bar replaces the entry pressure {from} bar',
    logFirstPressureSame: 'Team {name}: contact – first pressure report {bar} bar (as entry pressure)',
    pressureSheetFirst: 'First pressure report – replaces the entry pressure {bar} bar, counts as contact',
    newTruppShort: 'Team',
    removedToast: 'Team {name} removed',
    notDeployedToast: 'Team {name}: not deployed',
    // Atemschutznotfall (F1, 08.10.2026) — short, neutral wording; see the German base
    notfall: {
      act: 'Emergency',
      actHint: 'Press and hold to raise the emergency',
      end: 'Emergency ended',
      endHint: 'Press and hold to end the emergency',
      holdHint: 'Press and hold',
      title: 'Emergency',
      who: 'Team {name}',
      since: 'since {time}',
      stateWord: 'Emergency since {time}',
      placeMap: 'Map',
      placeMapAt: 'Map · at {host}',
      bar: '{bar} bar',
      barAge: '{age} ago',
      barEntry: 'Entry pressure',
      barWith: '{bar} ({when})',
      kanal: 'Channel {n}',
      contact: 'Contact {time}',
      sitrDeploy: 'Deploy safety team',
      sitrPickTitle: 'Which safety team?',
      sitrNone: 'No safety team ready',
      sitrDefine: 'Assign safety team',
      sitrInside: 'Safety team {name} inside since {time}',
      goTo: 'To the team',
      goToWho: 'To {name}',
      rowTitle: 'Emergency – team {name}',
      rowTitleMany: 'Emergency – {count} teams: {names}',
      logTrigger: 'Team {name}: emergency raised',
      factPlace: 'location {place}',
      factContact: 'last contact {time}',
      factBar: '{bar} bar ({time})',
      factBarEntry: 'entry pressure {bar} bar',
      factKanal: 'channel {n}',
      logEnd: 'Team {name}: emergency ended – duration {dur}',
      logEndOut: 'Team {name}: emergency ended – duration {dur} – team out',
      logSafetyEntry: 'Team {name}: safety team deployed – emergency team {target}, {dur} after it was raised',
      logAtClose: 'Team {name}: emergency not ended at closing',
      toast: 'Emergency raised for team {name}',
      notifyTitle: 'SCBA emergency – {name}',
      notifyBody: 'Emergency since {time} – deploy the safety team.',
      noSafetyHint: 'No safety team ready',
      abschlussTitle: 'Emergency still running',
      abschlussMsg: '{list} – not ended yet.',
      abschlussClose: 'Close anyway',
      // «Entfernen» on a Trupp in a Notfall is refused until it is ended (review of #300)
      removeBlocked: 'Hold «Emergency ended» first – a team in an emergency stays on the board',
    },
    removeInsideTitle: 'Team {name} is inside – report it out first?',
    removeInsideMsg: 'Removing takes the team off the board and out of every alarm. What is usually meant: the team is out.',
    actEnterFirst: 'Deploy',
    contactDone: 'Confirmed',
    pressureLockedLabelPlain: 'Entry pressure',
    pressureLocked: 'Team is out',
    pressureLockedWhyExit: 'Team is out · remaining {bar} bar',
    entryLowTitle: 'Entry pressure low',
    entryLowMsg: '{bar} bar – usually from {min} bar',
    entryLowConfirm: 'Keep {bar} bar',
    entryLowChange: 'Change',
    bottleAsk: 'Out {min} min ago, last {bar} bar. Which cylinder?',
    bottleAskNow: 'Just out, last {bar} bar. Which cylinder?',
    bottleSame: 'Same cylinder',
    bottleNew: 'New cylinder',
    saveBlockedBottle: 'Choose same or new cylinder',
    logReenter: 'Team {name} re-deployed – entry pressure {bar} bar',
    logReenterPlain: 'Team {name} re-deployed',
    logReenterNoAs: 'Team {name} re-deployed – without SCBA',
    logStandby: 'Team {name} on standby – not yet deployed',
    // the deployment clause appended to the three rows that OPEN a deployment (see de/atemschutz.ts):
    // short forms, because they are appended to a sentence that already stands
    logDetailLine: 'Line {n}',
    logDetailFunk: 'Channel {n}',
    logDetailNoAs: 'without SCBA',
    logAlarm: 'SCBA alarm: team {name} – {status}',
    logAlarmCleared: 'SCBA alarm ended: team {name} – {reason}',
    alarmClearedBy: {
      exit: 'exit',
      contact: 'radio contact',
      pressure: 'pressure report',
      rueckzug: 'withdrawal',
      resume: 'deployment resumed',
    } as Record<string, string>,
    alarmClearedOther: 'contact re-established',
    alarmClearedByReopen: 'contact clock restarted (reopened)',

    orderLabel: 'Order',
    orderUrgency: 'Urgency',
    orderManual: 'As placed',
    orderAuftrag: 'Task',
    orderName: 'Name',
    moveBack: 'Move up',
    moveForward: 'Move down',
    truppFallbackName: 'Team',
    editPressureLabel: 'Correct the entry pressure',
    editPressureHint: 'Corrects the recorded entry pressure — does not count as radio contact.',
    officersOnly: 'officers only',
    assignedFallbackName: 'This person',
    pressureRose: 'Higher than last time ({from} bar) — mistyped?',
    chipHint: 'SCBA — tap for monitoring',
    alarmRowOverdue: 'SCBA overdue — {name}',
    alarmRowOverdueSub: 'No radio contact — establish contact now.',
    alarmRowPressure: 'Alarm pressure reached — {name}',
    alarmRowOverdueMany: 'SCBA overdue — {count} teams: {names}',
    alarmRowPressureMany: 'Alarm pressure reached — {count} teams: {names}',
    alarmRowPressureManySub: 'Order withdrawal.',
    alarmRowPressureSub: '{bar} bar, limit {line} bar — order withdrawal.',
    alarmRowGo: 'To the team',
    alarmRowAck: 'Acknowledged',
    alarmRowReadOnly: 'read-only',
    logSafety: 'SCBA safety values changed: {changes}',
    logSafetyInterval: 'Radio contact interval {from} → {to} min',
    logSafetyGrace: 'Grace period {from} → {to} s',
    logSafetyFunkkanal: 'Radio channel {from} → {to}',
    logEditFields: 'Team {name}: {changes}',
    changeLeader: 'Team leader {from} → {to}',
    changeMemberOut: '{names} taken out of the team',
    changeMemberIn: '{names} joined',
    // …and WHO IS IN IT NOW, with the « / » this app writes a crew with everywhere else
    changeCrewNow: 'Now: {crew}',
    crewChange: {
      leader: 'Team leader {from} → {to}',
      movedTo: '{name} → team {to}',
      movedFrom: '{name} from team {from}',
      left: '{name} taken out of the team',
      joined: '{name} joined',
    },
    // the transfer, as ONE row on the team giving the person up — {name} is that team, {to} the
    // one taking them on (the receiving team's own row already names its full crew)
    logMovedOut: 'Team {name}: {person} moved to team {to}',
    logMovedOutPlain: 'Team {name}: {person} moved to another team',
    changeAuftragTo: 'task {auftrag}',
    changeAuftragCleared: 'task removed',
    changeLine: 'Line {n}',
    changeLineCleared: 'Line released',
    // ⚠️ from → to, like the entry pressure — «Radio channel 12» said nothing about whether it
    // was set, changed or merely confirmed
    changeFunkkanal: 'Radio channel {from} → {to}',
    changeFunkkanalSet: 'Radio channel {n} set',
    changeFunkkanalCleared: 'Radio channel removed',
    changeColor: 'Colour changed',
    changeEquipment: 'Equipment: {list}',
    changeEquipmentNone: 'Equipment: none',
    changePressure: 'Entry pressure {from} → {to} bar',
    // a cylinder opened just now has no «from» — and going the other way the fragment is dropped
    // entirely (see the German base)
    changePressureSet: 'Entry pressure {n} bar',
    changeKindPa: 'now under SCBA',
    changeKindPlain: 'no longer under SCBA',
    kindOffTitle: '{name}: end SCBA monitoring?',
    kindOffMsg: 'The team is deployed. Without SCBA the contact clock and the pressure stop, '
      + 'and there is no alarm for it any more. Everything recorded so far stays in the log '
      + 'and on the report.',
    kindOffConfirm: 'End monitoring',
    logPressureAlarm: 'Team {name}: pressure {bar} bar — alarm pressure reached',
    logRemoved: 'Team {name} removed',
    logRestored: 'Team {name} restored',
    logInsideAtClose: 'Team {name} still inside at closing',
    cycleEndAtClose: '{t} (still inside at closing)',
    logClockRestart: 'Team {name}: contact clock restarted – incident reopened',
  },
  lineDecor: {
    W: 'Water',
    S: 'Foam',
    H: 'Water curtain',
    P: 'Powder',
    N: 'Wet holding line',
    T: 'Dry holding line',
    G: 'Backfire',
  } as Record<string, string>,
}
