// English copy · the Gebäude card and floors.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/building.ts.

import type { Copy, Localizable } from '../index'

export const buildingCopy: Localizable<Pick<Copy, 'building'>> = {
  building: {
    title: 'Building',
    hint: 'Register hint',
    hintTitle: 'From the federal registers (GWR, BFE) – may be outdated or incomplete. Check on site.',
    floors: '{n} storeys',
    floorsOne: '1 storey',
    flats: '{n} flats',
    flatsOne: '1 flat',
    year: 'Built {y}',
    period: 'Built {p}',
    shelter: 'Shelter',
    heating: 'Heating {e}',
    hotWater: 'Hot water {e}',
    pv: 'PV {kw}',
    pvBare: 'PV',
    pvTitle: 'Photovoltaics in the BFE register{since} – may be missing even where a system exists',
    pvSince: ', in service since {d}',
    kw: '{n} kW',
    energy: {
      gas: 'gas',
      oil: 'oil',
      wood: 'wood',
      district: 'district heating',
      air: 'heat pump (air)',
      geothermal: 'heat pump (ground)',
      water: 'heat pump (water)',
      electricity: 'electric',
      solar: 'solar',
      waste_heat: 'waste heat',
      other: 'other',
    },
    status: {
      planned: 'planned',
      approved: 'approved',
      under_construction: 'under construction',
      unusable: 'unusable',
      demolished: 'demolished',
      not_built: 'not built',
    },
    srcGwr: 'GWR {a} · as of {d}',
    srcGwrNoAddr: 'GWR as of {d}',
    srcHeating: 'heating recorded {d}',
    srcPv: 'BFE checked {d}',
    srcCached: 'saved {d}',
    measures: 'Immediate measures',
    remarks: 'Remarks',
    objectSource: '{name} · {src}',
    objectNear: '{name} · nearby ({m} m)',
    objectNearNoDist: '{name} · nearby',
    visit: 'Last object visit {d}',
    visitFindings: 'Last object visit {d} · {n} defects',
    visitFindingsOne: 'Last object visit {d} · 1 defect',
    chipTitle: 'Building info',
    chipLabel: 'Open building profile',
    chipLabelHazards: 'Building: {h} – open profile',
    measuresShort: 'Measures',
  },
}
