// English copy · the capture (QR) app.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/capture.ts.

import type { Copy, Localizable } from '../index'

export const captureCopy: Localizable<Pick<Copy, 'capture'>> = {
  capture: {
    title: 'Record incident',
    invalid: 'Link invalid or capture disabled.',
    noIncidents: 'No recordable incident right now.',
    noIncidentsHint: 'Ongoing and not-yet-reported incidents appear here. Yours is missing? Note it on the paper capture sheet or tell incident command – they can add it later.',
    searchName: 'Search name …',
    filterRecorded: 'Recorded {n}',
    back: 'Back',
    alarmedAt: 'Alarm {t}',
    saveFailed: 'Saving failed',
    saveFailedOffline: 'No connection – the last change was not saved.',
    retry: 'Try again',
    savedOk: 'Saved',
    undo: 'Undo',
    mittelSet: '{label}: now {n} {unit}',
    mittelRemoved: '{label} removed',
    mittelExtra: 'Other recorded items',
    gerettete: 'Rescued',
    gerettetePersonen: 'People',
    geretteteTiere: 'Animals',
    rueckmeldung: 'Report back to dispatch',
    rueckName: 'Pick a name …',
    rueckZeit: 'Time',
    jetzt: 'Now',
    kurzberichtHead: 'Summary',
    kurzberichtPlaceholder: 'What happened, what was done?',
    gruppenHead: 'Group alarm times',
    fahrzeugeHead: 'Vehicle turnout times',
    einsatzleiter: 'Incident commander',
    rapportPdf: 'Report PDF',
    pdfFailed: 'PDF failed – try again',
    sectionZeiten: 'Times',
    sectionAngaben: 'Details',
    zeitenFilled: '{n} times recorded',
    abschlussHead: 'Wrap-up',
    missingHead: 'Still open:',
    missingGo: 'Open {step}',
    missingNote: 'Prints as a blank field.',
    ausgerueckt: 'Turned out',
    kontaktperson: 'Contact person',
    kontaktpersonPlaceholder: 'Owner / caller',
    kontaktpersonTelefon: 'Contact person phone',
    kontaktpersonTelefonPlaceholder: 'Phone number',
    kontaktpersonCall: 'Call contact person',
    von: 'from',
    bis: 'to',
    ende: 'Incident end',
    sectionPersonen: 'Attendance',
    presentCount: '{n} present',
    tapHint: 'Tap: absent → station → on scene → left. Time next to it: from = arrival, after leaving to = departure.',
    tapHelp: 'How this works',
    stateLeft: 'left',
    sectionMaterial: 'Material',
    cancel: 'Cancel',
    mittelCount: '{n} items',
    pickMaterial: 'Pick material …',
    add: 'Add',
    notePlaceholder: 'Note for the log …',
    footNote: 'Everything is saved continuously.',
    loadFailedOffline: 'No connection',
    clockSkew: 'This device\'s clock is off by {n} minutes – check recorded times.',
    searchMaterial: 'Search material …',
    kpActive: 'Command tablet active',
    kpActiveHint: 'The command tablet is on this incident – the full report (with sketch) comes from there.',
    kpNormallyHint: 'The full report (with sketch) normally comes from the command tablet.',
    usageChip: 'QR: {n} entries · last {t}',
    usageChipOne: 'QR: 1 entry · last {t}',
    exerciseHint: 'Exercise – does not count towards the incident statistics.',
    groupCurrent: 'Current',
    groupBacklog: 'Still open',

    logAttendancePresent: '{name} present (QR)',
    logAttendanceLeft: '{name} left (QR)',
    logAttendanceCleared: '{name} removed from attendance (QR)',
    logAttendanceRestored: '{name} restored (QR)',
    logTimes: '{name}\'s times corrected (QR)',
    logMittel: '{label}: {menge} {unit} (QR)',
    logAttachmentAdd: 'Report photo added (QR)',
    logAttachmentRemove: 'Report photo removed (QR)',
    logMeta: 'Report details changed (QR): {fields}',
    partnersHead: 'Partner organisations',
    partnerOrg: 'Organisation',
    partnerNote: 'Note',
    partnerAdd: 'Add organisation',
    partnerPlaceholder: 'Organisation …',
    partnerRemove: 'Remove organisation',
    partnerCount: '{n} recorded',
    partnerNone: 'none',
    beilagenHead: 'Photos',
    beilagenAdd: 'Add a photo',
    beilagenBusy: 'Uploading …',
    beilagenCaption: 'Caption',
    beilagenRemove: 'Delete photo',
    beilagenFailed: 'The photo could not be uploaded.',
    beilagenCount: '{n} photo(s)',
    beilagenNone: 'none',
  },
}
