// English copy · measuring, shapes, object Verlauf rows, the tool dock.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/drawing.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'measure' | 'shapes' | 'log' | 'objectDone' | 'addSheet' | 'toolDock'

export const drawingCopy: Localizable<Pick<Copy, Keys>> = {
  measure: {
    modeLine: 'Distance',
    modeArea: 'Area',
    clear: 'Reset',
    insertPoint: 'Insert point',
    extendLine: 'Extend line',
    deleteNode: 'Press and hold to delete · right-click on a computer',
    snapConnect: 'Hold to connect',
    snapRelease: 'Pull away to release',
    distance: 'Distance',
    perimeter: 'Perimeter',
    boxWidth: 'Width',
    boxHeight: 'Height',
    area: 'Area',
    hoses: 'Hoses',
    profile: 'Elevation profile',
    ascent: 'Ascent',
    descent: 'Descent',
    min: 'Lowest',
    max: 'Highest',
    profileLoading: 'Loading elevation profile …',
    profileNone: 'No elevation profile available',
    hintLine: 'At least 2 points for the distance',
    hintArea: 'At least 3 points for the area',
    adoptLine: 'Keep as a line',
    adoptArea: 'Keep as an area',
  },
  shapes: {
    sectionTitle: 'Shapes',
    kindLabel: 'Shape',
    color: 'Color',
    rotate: 'Rotate',
    stopLabel: 'Stop bar',
    carrierLabel: 'Carrier',
    carrierNone: 'None',
    carrierHeli: 'Heli',
    carrierTlf: 'TLF',
    resizeHint: 'Drag the corner to scale',
    heightLabel: 'Height',
    boxWidthHint: 'Drag — width',
    boxHeightHint: 'Drag — height',
    endHint: 'Drag the end — distance and direction',
    strokeLabel: 'Line width',
    cornersLabel: 'Corners',
    cornersRound: 'Rounded',
    cornersSharp: 'Square',
    names: { arrow: 'Arrow', cloud: 'Smoke', square: 'Rectangle', rotation: 'Shuttle run' },

    size: 'Size',
    sizeSmaller: 'Smaller',
    sizeBigger: 'Bigger',
    lengthLabel: 'Length',
    lengthShorter: 'Shorter',
    lengthLonger: 'Longer',
    moveHint: 'Drag the basket — direction and reach',
  },
  log: {
    audioNote: 'Audio note',
    symbolPlaced: 'Symbol "{name}" placed',
    shapePlaced: '{name} placed',
    notePlaced: 'Note placed',
    teamPlaced: '{name} placed on the map',
    shapeDrawn: '{name} drawn',
    objectMoved: '{name} moved',
    placardDocked: '{name} docked to «{host}»',
    placardUndocked: '{name} released from «{host}»',
    teamDocked: '{name} at «{host}»',
    teamUndocked: '{name} released from «{host}»',
    referenceRebaked: 'Reference adjusted – {n} objects relocated',
    referenceRemeasured: 'Sheet shape measured – {n} objects relocated',
    referenceRolledBack: 'Reference change discarded – saving failed',
    referenceDropped: 'Reference removed',
    referenceDroppedKept: 'Reference removed – {n} objects keep their last position',
    referenceLinked: 'Plan linked to the map – {plan}',
    referenceLinkedPlaced: 'Plan linked to the map – {plan} – {n} objects placed',
    objectDeleted: '{name} removed',
    drawingDeleted: 'Drawing removed',
    undo: 'Action undone',
    redo: 'Action redone',
    undoNamed: '{action} undone',
    redoNamed: '{action} redone',
    journalNote: 'Note',

    selectionDeleted: '{n} objects removed',
    duplicated: 'Object duplicated',
    entityEdited: '{name}: {changes}',
    fieldSet: '{field}: {value}',
    fieldChanged: '{field} changed to {value}',
    fieldCleared: '{field} cleared',
    // the same two statements WITHOUT the value — for the one case where naming it would repeat
    // the row's own name («Pfeil: Abschluss: Pfeil», see lib/drawingEdit)
    fieldSetPlain: '{field} set',
    fieldChangedPlain: '{field} changed',
    labelSet: 'Caption «{value}»',
    labelCleared: 'Caption removed',
    floorSet: 'Floor {value}',
    floorCleared: 'Floor removed',
    floorRangeSet: 'Floors {from} – {to}',
    floorRangeCleared: 'Floor range removed',
    countSet: 'Count {n}',
    spreadSet: 'Spread recorded',
    spreadCleared: 'Spread removed',
    noteWritten: 'Note «{value}»',
    notesCleared: 'Note cleared',
    drawingLabelSet: '{kind} «{value}»',
    gpsReverted: '{name}: back to the state at the scene ({time}), released from {vehicle}',
    gpsRevertedBare: '{name}: back to the state at the scene ({time})',
    gpsReleasedOnSite: '{name}: released from {vehicle} at the scene, drive removed',
    gpsReleasedOnSiteBare: '{name}: released at the scene, drive removed',
    drawingLabelCleared: '{kind}: caption removed',
    drawKinds: {
      area: 'Area',
      line: 'Line',
      circle: 'Cordon circle',
    },
  },
  objectDone: {
    word: {
      fire: { title: 'Extinguished', inline: 'extinguished' },
      other: { title: 'Done', inline: 'done' },
    },
    action: 'Done',
    actionHint: 'stays visible in grey',
    state: '{word} {time}',
    reopen: 'Active again',
    removeHint: 'only for a mistake',
    logDone: '{name} {word}',
    logReopened: '{name} active again',
  },
  addSheet: { tile: 'Add', tools: 'Draw & crew' },
  toolDock: {
    colorGroup: 'Colour',
    colorName: '{group} {n}',
    widthName: 'Line width {n} px',
    autoCommitted: '{name} saved',
    autoCommitUndo: 'Undo',
    draftDiscarded: 'Incomplete drawing discarded',
  },
}
