// English copy · the symbol / drawing editors, top bar and small controls.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/editors.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'contextPanel' | 'drawingEditor' | 'topBar' | 'stepper' | 'confirm' | 'combo'

export const editorsCopy: Localizable<Pick<Copy, Keys>> = {
  contextPanel: {
    titlePlaceholder: 'Label ...',
    floor: 'Floor',
    floorFrom: 'From floor',
    floorTo: 'To floor',
    floorNone: '–',
    spread: 'Spread',
    spreadH: 'Horizontal',
    spreadV: 'Vertical',
    spreadBounded: 'Boundary',
    spreadBoundedTitle: 'Spread boundary — spread stopped here',
    spreadDirTitles: { left: 'to the left', right: 'to the right', up: 'Upper floor (↑)', down: 'Lower floor (↓)' } as Record<string, string>,
    count: 'Count',
    rotation: 'Rotation',
    rotationVehicle: 'Vehicle',
    rotationFan: 'Fan',
    rotationLadder: 'Ladder',
    center: 'Center',
    toOriginal: 'Go to the original',
    toProjection: 'Show on the linked surface',
    showOnMap: 'Show on the map',
    showOnPlan: 'Show on {plan}',
    resetGps: 'GPS',
    resetGpsTitle: 'Reset to GPS position and heading',
    pinGps: 'Hold here',
    pinGpsTitle: 'Hold this vehicle here — the symbol stays put even once it drives off',
    logPinned: '{name} held in place',
    driverLabel: 'Driver',
    driverPlaceholder: 'Name',
    rotateHint: 'Drag the handle to align',
    caption: 'Caption',
    captionDefault: 'Default',
    captionOff: 'Off',
    captionAuto: 'Auto',
    captionAll: 'All',
    notes: 'Notes',
    notesPlaceholder: 'General notes …',
    addField: 'Add field',
    addFieldShort: 'Field',
    removeField: 'Delete field',
    fieldKeyPlaceholder: 'Label',
    fieldNamePlaceholder: 'Name …',
    fieldValuePlaceholder: '{label} …',
    duplicateField: '«{key}» already exists – only the last value is kept.',
    // unField/stoffField are intentionally NOT translated — they are the detail-row DATA keys
    // the UN→substance lookup matches against the (language-independent) preset fields
    // ['UN-Nr.','Stoff']; translating them would break the autofill. They fall back to German.
    stoffSearch: 'Search or enter substance …',
    unHazardTitle: 'Dangerous goods (ADR)',
    adrMeanings: {
      '1': 'Explosives',
      '1.4': 'Explosives (minor hazard)',
      '1.5': 'Explosives (very insensitive)',
      '1.6': 'Explosives (extremely insensitive)',
      '2': 'Gases',
      '2.1': 'Flammable gas',
      '2.2': 'Non-flammable, non-toxic gas',
      '2.3': 'Toxic gas',
      '3': 'Flammable liquids',
      '4.1': 'Flammable solids',
      '4.2': 'Spontaneously combustible',
      '4.3': 'Emits flammable gas with water',
      '5.1': 'Oxidizing substances',
      '5.2': 'Organic peroxides',
      '6.1': 'Toxic substances',
      '6.2': 'Infectious substances',
      '7': 'Radioactive material',
      '7E': 'Radioactive material (fissile)',
      '7X': 'Radioactive material',
      '8': 'Corrosive substances',
      '9': 'Miscellaneous dangerous goods',
      '9A': 'Lithium batteries',
    } as Record<string, string>,
    packingGroups: { I: 'high danger', II: 'medium danger', III: 'low danger' } as Record<string, string>,
    unClass: 'Class',
    unKemler: 'Hazard number',
    unLabels: 'Hazard labels',
    unPacking: 'Packing group',
    unNoMatch: 'UN no. not found in the ADR table',
    unWater: 'Reacts dangerously with water – do NOT use water!',
    unLookupLabel: 'ERI card (Cefic)',
    unLookupUrl: 'https://www.ericards.net/psp/ericards.psp_search_result?p_lang=1&lang=1&unnumber={un}',
    kemler: {
      '2': 'Gas (escaping under pressure or by reaction)',
      '3': 'Flammable liquid / gas',
      '4': 'Flammable solid',
      '5': 'Oxidising (fire-intensifying)',
      '6': 'Toxic / risk of infection',
      '7': 'Radioactive',
      '8': 'Corrosive',
      '9': 'Risk of spontaneous violent reaction',
    } as Record<string, string>,
    kemlerDoubled: 'Intensified hazard (doubled digit)',

    labelField: 'Designation',
    countBySymbol: {
      'VKF Patientensammelstelle': 'Number of patients',
      'VKF Sanitaetshilfsstelle': 'Number of patients',
      'FW Verwundetennest': 'Number of casualties',
      'VKF Totensammelstelle': 'Number of deceased',
      'VKF Sammelstelle': 'Number of uninjured',
      'VKF Rettungen': 'Number of people',
    },
    airflow: 'Air direction',
    airflowBlow: 'Blowing in',
    airflowExtract: 'Extracting',
    stopSharing: 'Remove location',
    stopSharingTitle: 'Remove this person\'s self-reported position. They can share again at any time afterwards.',
    stopSharingFailed: 'The location could not be removed.',
    swapEl: 'Hand over command',
    fieldPlaceholders: {
      'Kapazität': 'e.g. 80 m³',
    },
    ergGuide: 'ERG guide',
    ergPolymerization: 'Polymerisation hazard (P) — the container can burst violently',
    ergIsolate: 'Isolation (small quantity)',
    ergProtectDay: 'Protective distance, day',
    ergProtectNight: 'Protective distance, night',
    ergLarge: 'Large quantity',
    ergTable3: 'see ERG table 3 (container/wind)',
    ergDayShort: 'Day',
    ergNightShort: 'Night',
    ergSunrise: 'sunrise {t}',
    ergSunset: 'sunset {t}',
    dockedTo: 'Docked to «{name}»',
    dockedRelease: 'Release',
    ergAdopt: 'Apply as cordon',
    ergRingsLabel: 'Radius on the map',
    ergRingsOff: 'Off',
    ergRingsSmall: 'Small',
    ergRingsLarge: 'Large',
    ergSource: 'Source: {v} (PHMSA) — a planning aid, not validated',
    ergCameoLabel: 'CAMEO Chemicals (ERG details)',
  },
  drawingEditor: {
    area: 'Area',
    drawing: 'Drawing',
    circle: 'Cordon',
    radius: 'Radius',
    fill: 'Fill',
    fillHatch: 'Hatched',
    move: 'Move',
    moveArmed: 'Move armed – drag anywhere',
    rotateArmed: 'Turn armed – drag anywhere',
    selectionBar: 'Selection',
    points: 'Points',
    color: 'Color',
    width: 'Width',
    lineStyle: 'Line',
    lineSolid: 'Solid',
    lineDashed: 'Dashed',
    lineHalteliniUp: 'Holding line – teeth above',
    lineHalteliniDown: 'Holding line – teeth below',
    lineAbwurfzone: 'Water drop zone',
    label: 'Text',
    labelPlaceholder: 'Label …',
    areaLabelPlaceholder: 'e.g. Sector A',
    abschnittLeiter: 'Sector chief',
    abschnittLeiterPlaceholder: 'Choose sector chief …',
    abschnittAuftrag: 'Task',
    abschnittAuftragPlaceholder: 'e.g. Fire attack building B',
    abschnittMaxHint: 'FKS guideline: at most 3–4 sectors.',
    marker: 'Marker',
    markerPlaceholder: 'e.g. R',
    arrow: 'Arrowhead',
    ending: 'Ending',
    endingNone: 'None',
    endingArrow: 'Arrow',
    endingArrowStop: 'Arrow with stop',
    endingTeilstueck: 'Section',
    endingNoneWhat: 'No ending',
    endingArrowWhat: 'Arrowhead',
    endingArrowStopWhat: 'Arrow with stop bar — limit of spread',
    endingTeilstueckWhat: 'Teilstück — fork with three ports',
    reverse: 'Reverse direction',
    content: 'Type',
    contentPlain: 'Water',
    lineNo: 'Line no.',
    lineNoDuplicate: 'Line {n} already exists here',
    trupp: 'Belongs to team',
    truppShow: 'Show team {name}',
    truppNone: 'No team',
    truppOut: 'out',
    floorTag: 'Floor',
    distance: 'Length',
    measurement: 'Measurement',
    showOnMap: 'On map',
    inputMode: 'Input',
    modeFreehand: 'Freehand',
    modeNodes: 'Points',
    on: 'On',
    off: 'Off',
    lock: 'Lock',
    lockHint: 'Locks the shape against accidental moves; press and hold the lock in the center to unlock.',
    unlockHold: 'Hold to unlock',

    connections: 'Connections',
    connectedStart: 'Start',
    connectedEnd: 'End',
    connectedLines: 'Connected lines ({n})',
    line: 'Line',
    lineLabelNo: 'Line {n}',
    route: 'Route',
    routeDirect: 'Direct',
    routeTrace: 'Track',
    detachConnection: 'Release the connection',
    gpsFollowing: 'GPS following actively',
    gpsMovingAway: 'The vehicle is moving away',
    gpsContinue: 'Keep following',
    gpsDetachOnSite: 'Release at the scene',
    gpsDetachHere: 'Release here (keep the trace)',
    gpsDismiss: 'Hide',
    gpsPause: 'Stop following',
    gpsAwayTitle: '{vehicle} is leaving · {distance} from the scene',
    gpsAwayTitleBare: '{vehicle} is leaving',
    gpsAwaySub: '{lines} still ends at the scene.',
    gpsAwaySubMany: '{lines} still end at the scene.',
    gpsKeepOnSite: 'Leave at the scene',
    gpsStoppedTitle: '{vehicle} · {distance} from the scene',
    gpsStoppedTitleBare: '{vehicle} · following stopped',
    gpsStoppedSub: 'Following stopped · {lines} shows the drive.',
    gpsStoppedSubMany: 'Following stopped · {lines} show the drive.',
    gpsBackTitle: '{vehicle} back at the scene',
    gpsBackSub: '{lines} shows the drive since {time}.',
    gpsBackSubMany: '{lines} show the drive since {time}.',
    gpsRevert: 'Back to the state at the scene',
    gpsRevertAt: 'Back to the state at the scene ({time})',
    gpsRevertStep: '{name} back to the state at the scene',
    gpsFollowingHead: '{line} · following {vehicle} since {time}',
    gpsFollowingHeadBare: '{line} · following {vehicle}',
    gpsStoppedHead: '{line} · following stopped · {vehicle}',
    gpsDistanceNow: 'now {distance} away',
    hiddenTarget: 'Target hidden',
    revealTarget: 'Show the layer',
    removeConnectedTitle: 'Remove {name}?',
    removeConnectedMessage: '{n} lines will be released.',
    removeEMessage: 'Delete the segment? {n} attached lines will be released.',
  },
  topBar: {
    offline: 'Offline',
    tiles: 'Tiles',
    recording: 'REC',
    gpsFrozen: 'GPS frozen',
    gpsFrozenHint: 'The live GPS feed is not responding. Vehicles are shown at their last known position.',
  },
  stepper: {
    less: 'less',
    more: 'more',
    reset: 'reset',
    typeToEnter: 'Tap to enter',
  },
  confirm: {
    ok: 'OK',
    cancel: 'Cancel',
  },
  combo: {
    empty: 'No choices',
    searchPlaceholder: 'Search person …',
    searchOrType: 'Search or enter …',
    useTyped: 'Use «{name}»',

    officersOnly: 'officers only',
  },
}
