// English copy · incident switcher, archive, history, Abschluss, data sources, replay.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/incident.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'incidentSwitcher' | 'archived' | 'history' | 'abschluss' | 'datenquellen' | 'personnelSync'
  | 'planPicker' | 'replay'

export const incidentCopy: Localizable<Pick<Copy, Keys>> = {
  incidentSwitcher: {
    noIncident: 'No incident',
    savedAt: 'Saved at {t}',
    startedRow: '{t} · {d}',
    startedFull: 'Started {t} · {d}',
    saved: 'Saved',
    badgePending: 'Not synced – saving',
    badgeOffline: 'Offline – saved locally, syncs as soon as reconnected',
    badgeError: 'Sync failed – saved locally, will retry',
    badgeStorage: 'Storage full – changes are NOT saved locally and will be lost on close',
    offlineShort: 'Offline',
    errorShort: 'Sync error',
    storageShort: 'Storage full',
    syncErrorToast: 'Sync failed – changes are saved locally.',
    syncOfflineToast: 'Still offline – changes are saved locally.',
    clockSkewToast: 'This device\'s clock is off by {n} minutes – check recorded times.',
    bootOffline: 'Offline – showing saved data.',
    bootListFailed: 'Incident list could not be loaded',
    openFailed: 'Incident could not be opened',
    openFailedNoCache: 'This incident is not saved on this device – connection needed',
    syncNow: 'Sync now',
    syncDone: 'Everything synced',
    syncFailedToast: 'Sync failed – changes stay saved locally.',
    incidents: 'Incidents',
    app: 'App',
    allIncidents: 'All incidents',
    editMetaShort: 'Edit',
    archiveShort: 'Complete',
    report: 'Incident report',
    archive: 'Close incident',
    archiveOpen: '{n} open',
    share: 'Share incident',
    shareShort: 'Share',
    noOpenIncidents: 'No open incidents',
    logout: 'Log out',
    logoutTitle: 'Log out?',
    logoutMsg: 'This device will then only open incidents again after a sign-in with PIN.',
    logoutOffline: 'Signing in again needs a network connection – until then this device opens no incident.',
    logoutUnsyncedOne: '1 entry has not been sent yet. It stays on this device and is sent as soon as you sign in again.',
    logoutUnsyncedMany: '{n} entries have not been sent yet. They stay on this device and are sent as soon as you sign in again.',
    logoutUnsyncedChanges: 'Changes have not been sent yet. They stay on this device and are sent as soon as you sign in again.',
    appVersion: 'App version (build)',

    editMeta: 'Edit incident details',
  },
  archived: {
    title: 'Incident closed',
    hint: 'The report stays correctable (addenda) – reopen for everything else.',
    hintViewOnly: 'View only.',
    back: 'Back',
    reactivate: 'Reopen',
    reactivateOffline: 'Needs a connection to the server',
    reactivateNeedsServer: 'Reopening needs a connection to the server – the incident stays closed. Try again once online.',
    closedElsewhere: 'Incident was closed on another device ({t})',
    closedElsewhereSub: 'The report stays correctable (addenda) – reopen for everything else.',
    closedRefusedOne: '1 entry from this device arrived after the close and was not accepted. It stays saved on this device.',
    closedRefused: '{n} entries from this device arrived after the close and were not accepted. They stay saved on this device.',
    closedExport: 'Save entries',
    closedDismiss: 'Hide notice',
    reopenedElsewhere: 'Incident was reopened on another device ({t})',
    rapportClosedHint: 'Incident closed – changes to the report are printed as addenda.',
    linkClosedTitle: 'Incident closed – this board is display only',
    linkRefusedTitle: 'This link is no longer valid – this board is display only',
    reopenedElsewhereSub: 'Editable again – later entries appear as addenda.',
    reopenedParkedOne: 'Editable again. 1 entry from this device that was not accepted after the close is being sent now – as an addendum.',
    reopenedParked: 'Editable again. {n} entries from this device that were not accepted after the close are being sent now – as addenda.',
  },
  history: {
    title: 'Incidents',
    empty: 'No incidents yet.',
    noLocation: 'no location',
    searchPlaceholder: 'Search …',
    groupOpen: 'Open',
    groupToday: 'Today',
    groupWeek: 'Last 7 days',
    offlineNote: 'Offline: viewing works; closing and reopening need a connection to the server.',
    since: 'since {t}',
    reactivate: 'Reopen',
    reactivateConfirmTitle: 'Reopen incident',
    reactivateConfirmMsg: 'The incident is reopened and editable. Later changes appear in the log and report as addenda.',
    reactivateConfirmBtn: 'Reopen',
    statusArchived: 'Closed',
    deleteExercise: 'Delete',
    deleteConfirmTitle: 'Delete exercise',
    deleteConfirmMsg: 'The exercise and all its data (log, photos, report) are deleted permanently. This cannot be undone.',
    deleteConfirmBtn: 'Delete permanently',
    deleted: 'Exercise deleted',
    deleteFailed: 'Delete failed',

    emptySub: 'Opened and closed incidents appear here.',
    archiveConfirmTitle: 'Close the incident',
    archiveConfirmMsg: 'The incident is closed and the end time recorded. Later additions appear in the log and the report as supplements.',
    archiveConfirmBtn: 'Close',
  },
  abschluss: {
    leftEarly: ' · until {t}',
    steps: {
      zeiten: 'Times',
      anwesenheit: 'Attendance',
      mittel: 'Material',
      einsatzleiter: 'Incident commander',
      kontaktperson: 'Contact person',
      kurzbericht: 'Summary',
      rueckmeldung: 'Report back to ELZ',
      abweichungen: 'Divergences',
    },
    ausgerueckt: 'Turned out',
    ende: 'Incident end',
    personen: '{n} present',
    von: 'from',
    bis: 'to',
    mittelCount: '{n} items',
    mittelNone: 'Nothing used',
    complete: 'Close incident',
    backToRapport: 'Back to report',
    confirmTitle: 'Close incident',
    confirmMsg: 'The report is marked complete and the incident closed. Later corrections stay possible and appear as addenda.',
    confirmBtn: 'Complete',
    confirmAnyway: 'Complete anyway',
    registeredOne: '1 team still registered ({list}).',
    registeredMany: '{n} teams still registered ({list}).',
    registeredSafety: '{name}, safety team',
    registeredToBoard: 'To the board',
    registeredTitle: 'Still registered',
    registeredStandDown: 'Close as «not deployed»',
    insideOne: '1 team is still inside: {list}.',
    insideMany: '{n} teams are still inside: {list}.',
    insideTrupp: 'Team {name}',
    insideClose: 'Complete anyway',
    insideTitle: 'Teams still inside',
    confirmBack: 'Back',
    done: 'Report completed',
    doneMediaPending: 'Report completed · {n} photo/audio not uploaded yet – kept and sent the next time it is opened',
    failed: 'Completion failed',
    corrected: 'Hours corrected: {name}',
    attendanceRemoved: '{name} attendance removed',
  },
  datenquellen: {
    title: 'Data sources',
    uploaded: 'Uploaded',
    uploadFailed: 'Upload failed',
    invalidFilename: 'File name yields no valid identifier',
    layerAdded: 'Layer "{name}" added – visible on the next load',
    addLayerFailed: 'Could not add layer',
    layerConflict: 'The map layers were just changed elsewhere. Please press «Add» again.',
    layerNoVersion: 'The configuration could not be read – the layer was not saved. Please check the connection and reload the page.',
    globalDatasets: 'Global datasets',
    objectsCount: 'objects',
    replace: 'Replace',
    adminOnlyNote: 'Replacing a dataset or adding a layer needs /admin unlocked in this browser (ADMIN_SECRET).',
    newGeoLayer: 'New geo layer …',
    chooseGeojson: 'Choose GeoJSON …',
    labelPlaceholder: 'Label (e.g. hydrants)',
    groupPlaceholder: 'Group (e.g. water)',
    defaultGroup: 'Reference',
    kindLines: 'Lines',
    kindPoints: 'Points',
    color: 'Color',
    adding: 'Loading …',
    add: 'Add',
    geojsonNoteBefore: 'GeoJSON in WGS84 [lng, lat]. Stored as a global dataset ',
    geojsonNoteAfter: '.',
    incidentObjects: 'Incident objects',
    plansWord: 'plans',
    nearby: 'Nearby ({n})',
    allOther: 'All other objects',
    allObjects: 'All objects',
  },
  personnelSync: {
    title: 'Sync personnel with {provider}',
    unknownError: 'Unknown error',
    syncFailed: 'Sync failed',
    countNew: 'new',
    countUpdated: 'updated',
    countUnchanged: 'unchanged',
    countStale: 'no longer in {provider}',
    querying: 'Querying {provider} …',
    done: 'Sync complete.',
    resultCreated: '{n} created',
    resultUpdated: '{n} updated',
    resultReactivated: ' ({n} of them reactivated)',
    resultUnchanged: '{n} unchanged',
    resultDeactivated: '{n} deactivated',
    staleHide: 'Hide {n} people no longer present in {provider} (kept for old incidents, not deleted)',
    syncing: 'Syncing …',
    sync: 'Sync',
  },
  planPicker: {
    searchPlaceholder: 'Search name or address …',
    autoNextObject: 'Automatically nearest object',
    loading: 'Loading objects …',
    loadFailed: 'Objects could not be loaded.',
    noObject: 'No object found.',
    planOne: 'plan',
    planMany: 'plans',
    mapNote: 'Coordinates partly imprecise – the list is authoritative.',
    hideMap: 'Hide map',
    showMap: 'Show map',
  },
  replay: {
    region: 'Log replay',
    banner: 'LOG · REPLAY',
    subtitle: 'Read-only view of the past',
    backToLive: 'Back to live',
    loadFailed: 'Log could not be loaded.',
    loading: 'Loading log …',
    transport: 'Playback',
    skipBack: 'Previous event',
    skipFwd: 'Next event',
    skipped: 'skipped {span}',
    gapTitle: '{span} with no events',
    sinceAlarm: '{span} since alarm',
    pause: 'Pause',
    speed: 'Speed',
    timepoint: 'Point in time',
    now: 'Now',
    laneLabel: 'Log',
    captionOpen: 'in the log',
    laneEntries: '{n} entries',
    captionNone: 'No entry at this point in time',
  },
}
