// English copy · the Einsatz wizard (intake).
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/intake.ts.

import type { Copy, Localizable } from '../index'

export const intakeCopy: Localizable<Pick<Copy, 'intake'>> = {
  intake: {
    titleNew: 'Open incident',
    locationHead: 'Location',
    addressLabel: 'Address',
    addressPlaceholder: 'Street no, ZIP city',
    addressSearching: 'Searching …',
    addressNoHits: 'No address found',
    objectButton: 'From plans',
    objectSearchPlaceholder: 'Search object or address …',
    objectNear: 'Nearby',
    objectNoHits: 'No objects found',
    objectPlans: (n: number) => (n === 1 ? '1 plan' : `${n} plans`),
    objectNoPlans: 'no plans',
    mapPickButton: 'On map',
    hereButton: 'Here',
    hereFailed: 'Location unavailable',
    coordSet: 'Coordinate set',
    coordNone: 'No location – will open without a coordinate',
    coordClear: 'Remove location',
    coordFold: 'Coordinates',
    keywordHead: 'Keyword & category',
    titleLabel: 'Keyword / title',
    titlePlaceholder: 'e.g. Building fire, school',
    categoryLabel: 'Category',
    exerciseNo: 'No',
    exerciseYes: 'Yes',
    exerciseLabel: 'Exercise',
    exerciseSub: 'Not counted in incident statistics',
    detailsPlaceholder: 'Additional details for the report',
    open: 'Open incident',
    opening: 'Opening …',
    cancel: 'Cancel',
    errorCreate: 'Creating failed',
    errorTake: 'Take-over failed',
    errorUpdate: 'Update failed',
    editTitle: 'Edit incident data',
    save: 'Save',
    saving: 'Saving …',
    created: 'Incident created',
    taken: 'Alarm taken over',
    updated: 'Incident updated',
    alarmierungHead: 'Dispatch',
    alarmTime: 'Alarm time',
    alarmMessage: 'Alarm message',
    addressUnknown: 'Address unknown',
    alarmOpen: 'Open',
    alarmOpening: 'Opening …',
    dismiss: 'Dismiss',
    manualIncident: 'Manual incident',
    attach: 'Add to existing incident',
    attachShort: 'To incident',
    attachConfirmTitle: 'Add “{alarm}” to this incident?',
    attachHint: 'The dispatch message lands in the log, GPS times follow automatically. The incident\u2019s keyword and location stay unchanged.',
    attachConfirm: 'Add',
    attachDone: 'Alarm added to the incident',
    attachError: 'Adding failed',
    newDiveraAlarm: 'New alarm',
    hide: 'Hide',
    fromDivera: 'Taken from the alarm source',
    reviewTitle: 'Check the incident data',
    locationSet: 'Location set',
    noLocationOnMap: 'No location – set on map',
    ok: 'Looks good',
    // DISPLAY labels for the category select — keyed by the German category value (the submitted
    // value stays German; only the option text is localized).
    kategorienLabels: {
      'Brandbekämpfung': 'Firefighting',
      'Strassenrettung': 'Road rescue',
      'Technische Hilfeleistung': 'Technical assistance',
      'Elementarereignis': 'Natural hazard',
      'Ölwehr': 'Oil response',
      'Chemiewehr': 'Chemical response',
      'Strahlenwehr': 'Radiation response',
      'Einsatz Bahnanlagen': 'Railway operation',
      'BMA / unechte Alarme': 'Fire alarm / false alarms',
      'Gerettete Tiere': 'Animal rescue',
      'Dienstleistungen': 'Services',
      'Diverse Einsätze': 'Other operations',
    },

    moveConfirmTitle: 'Move the incident location?',
    moveConfirmMsg: 'The incident location will be set to your current position — {d} from the previous one. The map, the sketch frame and the nearby object plans follow it.',
    moveConfirmBtn: 'Move',
    alarmTextUnavailable: 'The alarm message could not be loaded — it stays unchanged',
    demoBlocked: 'Disabled in the demo — no new incident can be opened here.',
  },
}
