// English copy · the Verlauf / journal and error sentences.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/journal.ts.

import type { Copy, Localizable } from '../index'

export const journalCopy: Localizable<Pick<Copy, 'journal' | 'errors'>> = {
  journal: {
    delivery: {
      failedTitleOne: '1 entry not uploaded',
      failedTitle: '{n} entries not uploaded',
      storageTitle: 'Entries not safely stored',
      storageBody: 'Keep the app open and save a copy. Closing the app may lose these entries.',
      savedBody: 'Saved on this device. These entries are missing on other devices.',
      offlineBody: 'Saved on this device. Upload retries automatically when a connection is available.',
      retry: 'Retry', retrying: 'Retrying …', export: 'Save entries', short: 'Entries not uploaded',
      refusedTitleOne: '1 audit event not permitted for this role',
      refusedTitle: '{n} audit events not permitted for this role',
      refusedBody: 'The server does not accept these events from this sign-in. They stay on this device and can be saved; the log is not affected.',
      closedTitleOne: '1 entry not accepted after the close',
      closedTitle: '{n} entries not accepted after the close',
      closedBody: 'The incident had already been closed when these entries reached the server. They are not in the log, but stay on this device and can be saved. If the incident is reopened, they are sent.',
      closedShort: 'Entries not accepted after the close – save them',
    },
    open: 'Log',
    add: 'Entry',
    addHint: 'Tap for an entry · hold, then slide onto a voice memo or a photo',
    title: 'Log',
    empty: 'No events recorded yet',
    surfaceMap: 'Map',
    surfacePlan: 'Plan',
    replay: 'Start replay',
    replayHint: 'Replay situation and plan at an earlier point in time',
    composerTitle: 'New entry',
    textPlaceholder: 'What happened? Report, observation, decision …',
    typeLabel: 'Kind',
    entryTypes: { info: 'Info', auftrag: 'Order', sofort: 'Immediate measure' } as Record<string, string>,
    entryTypesWrap: { info: 'Info', auftrag: 'Order', sofort: 'Immediate measure' } as Record<string, string>,
    record: 'Record',
    recordStop: 'Stop recording',
    discardAudio: 'Discard recording',
    attachUpload: 'Upload file',
    attachUploadShort: 'File',
    attachLabel: 'Attachment',
    attachDiscard: 'Remove attachment',
    attachOpen: 'Download attachment',
    attachOffline: 'File upload needs a connection. Select the file again later.',
    attachTooLarge: 'File is too large. Maximum: {max} MB.',
    attachUnsupported: 'This file type is not supported.',
    attachUploadFailed: 'File upload failed. Check the connection and try again.',
    attachDropped: 'Attachment «{name}» discarded – please pick it again.',
    attachPrint: 'Attachment: {names}',
    attachPrintMany: 'Attachments: {names}',
    attachAudioExtra: 'Only one recording per entry – «{names}» not taken.',
    audioClipLabel: 'Voice memo',
    audioImportLabel: 'External audio recording',
    audioStartLabel: 'Recording started',
    audioStartHint: 'Check the start time against the voice memo.',
    audioStartConfirm: 'Confirm start time',
    audioImportedNote: 'External audio recording ({duration})',
    audioDiscardImport: 'Remove audio file',
    audioUploading: 'Uploading …',
    audioOffline: 'Audio upload needs a connection. Select the file again later.',
    audioTooLarge: 'Audio file is too large. Maximum: {max} MB.',
    audioUnsupported: 'This audio format is not supported.',
    audioUploadFailed: 'Upload failed. Check the connection and try again.',
    audioImportDropped: 'External audio recording «{name}» discarded – please pick it again.',
    playerOpen: 'Listen through',
    editEntry: 'Edit text',
    removeEntry: 'Delete entry',
    entryRemoved: 'Entry deleted',
    playerEntryHere: 'Entry at this point',
    playerEntryPlaceholder: 'What was said? Report, decision …',
    playerEntries: 'Entries in this recording',
    playerNoEntries: 'No entries in this time window yet.',
    playerSkipBack: '15 seconds back',
    playerSkipFwd: '15 seconds forward',
    playerSpeed: 'Playback speed',
    playerSeek: 'Playback position',
    playerOffline: 'Playback needs a connection.',
    sttTranscribe: 'Transcribe',
    sttRunning: 'Transcription running … This can take a few minutes.',
    sttFailed: 'Transcription failed: {error}',
    sttRetry: 'Try again',
    sttErrorGeneric: 'server not reachable',
    sttBanner: '{n} drafts detected – review and take over.',
    sttTakeAll: 'Take all',
    sttTake: 'Take',
    sttDismiss: 'Dismiss',
    sttEmpty: 'No speech detected.',
    photo: 'Photo',
    photoNote: 'Photo',
    discardPhoto: 'Discard photo',
    send: 'Record',
    saved: 'Entry recorded',
    transcriptPlaceholder: 'Add transcript',
    transcriptSave: 'Save',
    transcriptEdit: 'Edit transcript',
    transcriptAdd: 'Add transcript',
    nachtrag: 'Addendum',
    corrected: 'corrected {t}',
    // ⚠️ the TOTAL number of occurrences, the same number the Rapport prints as «N×» — see the
    // German base for why «repeated 2×» was two readings of one number
    repeated: 'in total {n}×',
    repeatedTitle: 'How often this message stands in the record in total – every one of them is kept.',
    correctHint: 'The original wording stays in the record.',
    viaAtemschutzLink: 'SCBA link',
    viaAtemschutzLinkTitle: 'Entered on the handed-over SCBA board.',
    detailTime: 'Time',
    detailArea: 'Area',
    detailSource: 'Source',
    detailSourceManual: 'Written by hand',
    detailSourceSystem: 'Logged by the app',
    detailSourceSystemHint: 'System rows cannot be edited',
    detailAttachments: 'Attachments',
    detailAttachmentsN: '{n} pictures',
    detailAttachmentsOne: 'One picture',
    detailCorrected: 'Corrected',
    detailCorrectedFirst: 'first: {text}',
    detailRepeated: 'Repeated',
    detailRepeatedN: 'in total {n}× until {t}',
    detailNachtrag: 'Late entry',
    detailNachtragHint: 'written after the incident closed',
    attendanceConflict: 'Attendance {name}: {what} – please review.',
    // ⚠️ Fragments, never sentences: joined with « · » and dropped into {what} above, which has
    // already said «Attendance {name}: ». Whatever that line says, these must not say again.
    attendanceConflictTwoNotes: 'two roles – «{a}» and «{b}»',
    attendanceConflictOneNote: 'role «{a}» on one device only',
    attendanceConflictStatus: 'status differs',
    attendanceConflictOrt: 'location differs',
    attendanceConflictTimes: 'different times',
    attendanceConflictOther: 'diverging entries merged',
    attendanceConflictResolved: 'Divergence {name} checked – {taken}, {by}',
    attendanceConflictByUnknown: 'no name given',
    attendanceConflictFromKp: 'entry from the command post',
    attendanceConflictFromCapture: 'entry from the capture sheet',
    attendanceConflictKeepBoth: 'both entries stand',
    attendanceConflictOpenEnd: 'open',
    attendanceConflictTake: 'Take {side}',
    attendanceConflictKeep: 'Both are correct',
    attendanceConflictOpenTitle: 'Divergences',
    attendanceConflictOpenCount: '{n} open',
    attendanceConflictNoneOpen: 'None open',
    attendanceConflictCheckedAt: 'checked {t} · {by}',
    truppConflict: 'BA crew {name}: changes from two devices merged – please review.',
    tafelConflict: 'Board «{page}» · {where}: changed on two devices at once – «{kept}» stands (later), «{lost}» overwritten. Please review.',
    tafelRemovedKept: 'Board «{page}»: removed on one device, written on afterwards on another – the page stays. Please review.',
    tafelRemovedLost: 'Board «{page}» removed – written on before that on another device: {cells}. Please review.',
    arrowTitle: 'Insert arrow – who to whom',
    arrowBackTitle: 'Insert arrow – who from whom',
    dueHead: 'Remind',
    dueNone: 'No reminder',
    dueSetTitle: 'Reminds at {t}',
    dueExactTitle: 'Remind at',
    dayToday: 'Today',
    dayTomorrow: 'Tomorrow',
    duePast: 'That moment has already passed',
    reminderExact: 'Time …',
    reminderChipLabel: 'in {n} min',
    reminderTomorrow: ' · tomorrow',
    reminderSaved: 'Reminder set',
    reminderCreated: 'Reminder set for {t}: {text}',
    dueTitle: 'Reminder due',
    dueOne: 'Reminder due',
    dueDone: 'Done',
    dueSnooze: '+10 min',
    dueOpen: 'Open in log',
    openCount: '{n} open',
    doneLog: 'Reminder done: {text}',
    reopenLog: 'Reminder open again: {text}',
    snoozeLog: 'Reminder +{mins} min: {text}',
    dueAtLabel: 'due {t}',
    overdueLabel: 'overdue',
    markDoneTitle: 'Mark as done',
    againChip: '{mins} min',
    againTitle: 'Remind again in {mins} minutes',
    legend: 'Legend',
    legendPendenzOpen: 'Open item',
    legendPendenzUrgent: 'Open item — urgent',
    legendPendenzDone: 'Open item — done',
    search: 'Search the log',
    searchPlaceholder: 'Search …',
    searchClose: 'Close search',
    searchCount: '{n} of {m}',
    searchEmpty: 'Nothing for «{q}»',
    searchEmptyHint: 'Searches the text as well as the names of people and teams. One typo is forgiven.',
    filter: 'Filter the log',
    filterArt: 'Kind of entry',
    filterArea: 'Area',
    filterAll: 'Show all',
    filterActive: 'Filtered:',
    filterEmpty: 'No entries in this selection',
    filterEmptyHint: '«Show all» clears the filter.',

    stripLabel: 'Timeline — tap to jump to the matching place',
    photoOpen: 'View the photo large',
    mediaPending: 'Loading',
    mediaFailed: 'Not loaded',
    quickPhrasesAria: 'Phrase snippets',
    openRemindersHead: 'Open items',
    // the ○ switch beside the Art chips — three states on one control
    openStates: ['Keep open', 'Stays open – listed under open items', 'Urgent – sorted to the top'] as string[],
    pendenzSaved: 'Open item recorded',
    pendenzUrgentSaved: 'Open item recorded – urgent',
    pendenzDoneLog: 'Item done: {text}',
    pendenzReopenLog: 'Item open again: {text}',
    noteOnTitle: 'Update',
    noteOnLabel: 'on ',
    noteOnClear: 'Detach',
    linkPendenzTitle: 'Update on',
    pendenzNew: 'New open item',
    pendenzNewUrgent: 'Urgent open item',
    pendenzNotOpen: 'Do not keep open',
    noteSaved: 'Update recorded',
    noteChip: 'Item',
    noteOpen: 'Add an update',
    ageLabel: '{n}′',
    ageLabelHours: '{n} h',
    ageToggle: 'Switch time / age',
    openState: 'open',
    openReminderGo: 'Jump to the entry',
  },
  errors: {
    updateFailed: 'Update failed',
    serverUnreachable: 'Network error – server unreachable',
    serverTimeout: 'Server not responding – timed out',

    serverUnreachableHint: 'No network, or the server is not there at this address. Saved incidents stay available offline.',
    serverTimeoutHint: 'The connection is up, nothing is coming back — typical of a dying Wi-Fi. Saved incidents stay available offline.',
    httpUnauthorized: 'Sign-in expired',
    httpUnauthorizedHint: 'Please sign in again.',
    httpForbidden: 'Not permitted',
    httpForbiddenHint: 'This account may not do that. Sign in with an account that has editing rights.',
    httpNotFound: 'Not found on the server',
    httpNotFoundHint: 'The server does not know this address. It may be running a different version.',
    httpTooLarge: 'File too large',
    httpTooLargeHint: 'The server does not accept files of this size.',
    httpStale: 'Page out of date',
    httpStaleHint: 'This page knows an older state. Reload and repeat the change.',
    httpTooMany: 'Too many attempts',
    httpTooManyHint: 'Wait a moment, then try again.',
    httpRejected: 'Request rejected',
    httpRejectedHint: 'The server turned the request down.',
    httpGateway: 'Server unreachable',
    httpGatewayHint: 'The server is not answering — it is probably restarting. Try again shortly; saved incidents stay available offline.',
    httpServerError: 'Error on the server',
    httpServerErrorHint: 'The request arrived, the server could not handle it. Try again — if it persists, it is not the device.',
    httpCode: 'Error code {code}',
  },
}
