// English copy · the Lagemeldung and the Führungsrhythmus.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/lagemeldung.ts.

import type { Copy, Localizable } from '../index'

export const lagemeldungCopy: Localizable<Pick<Copy, 'lagemeldung'>> = {
  lagemeldung: {
    title: 'Situation report',
    chip: 'Report',
    chipIn: 'Report · in {m}′',
    chipDue: 'Report due',
    chipOff: 'Report · off',
    chipHint: 'Compose a situation report',
    chipAria: 'Situation report – {state}',
    modeSeit: 'Since {t}',
    modeVoll: 'Complete',
    modeFirst: 'First report',
    modeLabel: 'Scope',
    firstNote: 'No situation report yet · everything is new',
    seitNote: 'Only what changed since {t} · life-safety always',
    vollNote: 'Everything that stands – for a handover, a neighbouring brigade, Rück',
    slots: {
      zuerst: 'First', lage: 'Situation', menschen: 'People', gefahren: 'Hazards', massnahmen: 'Actions',
      mittel: 'Resources', bedarf: 'Needs', naechste: 'Next', zusatz: 'Also',
    } as Record<string, string>,
    tags: {
      neu: 'New', schlechter: 'Worse', besser: 'Better', erledigt: 'Done', gleich: 'still',
    } as Record<string, string>,
    tagSchaetzung: 'Estimate',
    tagSchaetzungTitle: 'Planning aid – estimated from the pressure history, not a measurement',
    tagRegister: 'Register',
    tagRegisterTitle: 'Register hint (GWR, BFE) – may be outdated, check on site',
    tick: 'Include in the report',
    untick: 'Leave out of the report',
    dropT0: 'Life-safety – leave it out anyway?',
    dropT0Yes: 'Leave out',
    editLine: 'Edit line',
    editDone: 'Done',
    addLine: 'Own line',
    addLinePlaceholder: 'What else has to be said',
    hidden: 'Hidden ({n})',
    hiddenNone: 'Nothing hidden',
    hiddenReasons: {
      gleich: 'unchanged since {t}',
      declined: 'left out {t}',
      budget: 'over radio length',
      routine: 'routine',
      offer: 'background',
      superseded: 'replaced by «{by}»',
      dispatch: 'dispatch already knows',
      inLine: 'included in «{slot}»',
    } as Record<string, string>,
    hiddenAdd: 'Add',
    hiddenAddAria: 'Add «{text}» to the report',
    words: '{n} words',
    seconds: '≈ {s} s',
    overBudget: 'Longer than one radio call ({n} words)',
    radio: 'Radio view',
    radioClose: 'Back to the draft',
    share: 'Share',
    shareCopied: 'Situation report copied',
    shareFailed: 'Sharing not possible',
    more: 'More actions',
    send: 'Reported',
    sendHint: 'Writes the report to the log and schedules the next one',
    close: 'Close without saving',
    source: 'Draft from teams, map, log, vehicle times · nothing saved until «Reported»',
    empty: 'Nothing new since {t}.',
    emptyFirst: 'Nothing in the record yet – add situation, people, resources by hand.',
    row: 'Situation report {t}: {text}',
    rowVoll: 'Situation report {t} (complete): {text}',
    sentToast: 'Situation report {t} in the log',
    undoneLog: 'Situation report {t} withdrawn',
    next: 'Next report approx. {t}.',
    nextHandover: 'Next report at handover.',
    nextNone: 'No further report planned.',
    rhythm: 'Rhythm',
    rhythmEvery: '{m}′',
    rhythmHandover: 'Handover',
    rhythmOff: 'Off',
    rhythmOffAction: 'Switch the rhythm off',
    rhythmOffLog: 'Situation report rhythm off',
    rhythmOnLog: 'Situation report rhythm {m}′ · next {t}',
    rhythmWindDown: 'Fire out – stretch the rhythm?',
    nextLog: 'Next situation report at {t}',
    reminderText: 'Situation report',
    dueTitle: 'Situation report due',
    dueLast: 'last {t}',
    dueNone: 'no situation report yet',
    dueChanges: '{n} changes',
    dueChangesOne: '1 change',
    dueUrgent: '{n} urgent',
    dueOpen: 'Report',
    dueSnooze: '+10′',
    phraseOffer: 'Compose situation report',
    truppNo: 'Team {n}',
    truppBare: 'Team',
    truppPressure: '{trupp} alarm pressure {bar} bar, withdrawing{where}.',
    truppContact: '{trupp} overdue, no radio contact for {m}′{where}.',
    truppEnded: '{trupp}: alarm cleared.',
    where: ', {w}',
    vermisstOne: '1 person missing{where}.',
    vermisstMany: '{n} people missing{where}.',
    eingesperrtOne: '1 person trapped{where}.',
    eingesperrtMany: '{n} people trapped{where}.',
    keineVermissten: 'No more missing persons.',
    gerettetOne: '1 person rescued{extra}.',
    gerettetMany: '{n} people rescued{extra}.',
    anSanitaet: ', handed over to EMS',
    geraeumt: 'Building evacuated.',
    keinePersonen: 'Nobody in the building.',
    un: 'Hazardous material UN {un}{stoff}{dist}.',
    unDist: ', cordon {m} m',
    unDone: 'Hazardous material UN {un}: done.',
    hazard: '{label}{where}.',
    hazardDone: '{label}: done.',
    gas: 'Gas heating in the building.',
    oil: 'Oil heating in the building.',
    pv: 'PV system on the roof.',
    gasAb: 'Gas shut off.',
    stromAb: 'Power cut.',
    geschosse: '{n} storeys.',
    wind: 'Wind turned to {dir}.',
    unterKontrolle: 'Fire under control {t}.',
    feuerAus: 'Fire out {t}{extra}.',
    nachloesch: ', overhaul under way',
    lageTitle: '{title}.',
    lageDamage: '{list}.',
    feuerGeloescht: 'Fire extinguished {t}.',
    trupps: '{n} teams deployed: {list}.',
    truppsOne: '1 team deployed: {list}.',
    truppsShort: '{n} teams deployed.',
    truppsShortOne: '1 team deployed.',
    sitr: 'Rapid intervention team ready.',
    asEnded: 'SCBA operations over, all teams out.',
    bereit: 'Ready: {list}.',
    mittelOn: '{list} on scene',
    mittelComing: '{list} en route',
    mittelNew: 'new {list}',
    mittelLeft: '{list} returned',
    mittelShort: '{n} vehicles new',
    mittelShortOn: '{n} vehicles on scene',
    adf: '{n} firefighters.',
    nachalarm: 'Additional alarm {title}.',
    abloesungJetzt: 'SCBA relief now.',
    abloesungBald: 'SCBA relief in approx. {m}′.',
    verstaerkung: 'Reinforcement requested, not yet on scene.',
    bedarfNone: 'none any more.',
    bedarfDone: '{text}: done.',
    reminderSoon: '{text} ({t}).',
    routineSymbolsOne: '1 symbol entry',
    routinePhotosOne: '1 photo',
    routineTeamOne: '1 SCBA entry',
    routineSymbols: '{n} symbol entries',
    routinePhotos: '{n} photos',
    routineTeam: '{n} SCBA entries',
    routineDispatch: 'Dispatch text',
    routineElTaken: '«Command taken over»',
  },
}
