// English copy · incident and standing links, shared positions.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/links.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'incidentLink' | 'standingLink' | 'sharePosition' | 'livePosition'

export const linksCopy: Localizable<Pick<Copy, Keys>> = {
  incidentLink: {
    opening: 'Opening incident …',
    pendingTitle: 'Incident not available yet',
    pendingHint: 'The alert has only just arrived. Trying again automatically …',
    notReadyTitle: 'This incident is not available.',
    notReadyHint: 'The link only works while the incident is running. If the alert just came in, the incident may not be ready yet — otherwise tell the incident commander.',
    invalidTitle: 'This link is no longer valid.',
    invalidHint: 'Open the link straight from the current alert message.',
    disabledTitle: 'Incident links are not enabled for this brigade.',
    disabledHint: 'The incident commander can switch them on in the configuration.',
    offlineTitle: 'No signal',
    offlineHint: 'The incident cannot be opened without a connection.',
    errorTitle: 'The server is not responding.',
    errorHint: 'If it persists, tell the incident commander.',
    retry: 'Try again',
    closedTitle: 'Incident closed',
    closedAt: 'Closed at {time}.',
    closedHint: 'If the incident is reopened, the board comes back here by itself.',
    unavailable: 'This incident is not reachable right now. Reload the page once you have signal again.',
  },
  standingLink: {
    idleTitle: 'No incident running',
    // one sentence per surface (09.09., see de/links.ts) — the terminal switches itself, the
    // laminated QR is read by somebody who has just scanned it
    idleHintTerminal: 'When an alert comes in, this screen switches to the incident by itself.',
    idleHintAs: 'As soon as an incident or an exercise is running, this code opens SCBA monitoring.',
    terminalKicker: 'Station terminal',
    checkedLabel: 'Last checked',
    chooseTitle: 'Several incidents are running',
    chooseHint: 'Pick which incident this display should show.',
    exerciseTag: 'Exercise',
    notEnrolledTitle: 'This device is not set up as a station terminal.',
    notEnrolledHint: 'In Administration under «Links & access», generate the setup link and open it on this device.',
    asInvalidTitle: 'This SCBA code is no longer valid.',
    asInvalidHint: 'The code was renewed. Print the current QR code in Administration and put it up.',
    disabledTitle: 'This feature is not enabled.',
    disabledHint: 'Administration can enable it under «Links & access».',
  },
  sharePosition: {
    askTitle: 'Share your location?',
    askBody: 'The command post then sees on the situation map where you are — so it is clear who is working where (e.g. on the water relay) and who can be reached.',
    askWho: 'Visible only to the command post. Others who have the incident link do not see your location.',
    askHowLong: 'Only while this incident is running. It is deleted when the incident is closed.',
    askBackground: 'If you lock the phone nothing more is transmitted — the last position stays, with its time.',
    askAgain: 'You have to switch sharing on yourself at every incident — it never starts on its own.',
    pickTitle: 'Who are you?',
    pickHint: 'So that your dot on the map has a name.',
    pickAgain: 'New incident — please confirm again who you are. The name you picked last is at the top.',
    pickLast: 'last',
    search: 'Search a name …',
    yes: 'Yes, share my location',
    no: 'No thanks',
    menuOff: 'Share location',
    menuOn: 'Share location — on',
    menuClosed: 'Only while the incident is running',
    menuDemo: 'Demo: simulated — your location is not requested',
    menuOnHint: 'Tap to stop',
    on: 'Location shared',
    starting: 'Looking for your location …',
    paused: 'Location paused',
    pausedHint: 'The phone transmits nothing while the app is in the background or the screen is locked. Open the app again and it continues.',
    denied: 'Location blocked',
    deniedHint: 'Location access is blocked for this site. It can only be allowed again in the browser settings.',
    taken: 'Name already in use',
    takenHint: 'Another device is currently sharing under this name. Pick your name again or wait a moment.',
    failing: 'Location is not getting through',
    failingHint: 'The phone finds your location, but the server is not accepting it — usually poor reception. It keeps trying.',
    impreciseHint: 'Reception is still too imprecise for a dot on the map. Outdoors it usually improves within seconds.',
    lastAt: 'Last {t}',
    stop: 'Stop sharing my location',
    change: 'Change name',
    settingsLabel: 'Use location',
    settingsHint: 'Allows this device to use your location. Nothing is shared until you switch it on from the map.',
    settingsAs: 'As {name}',
    settingsName: 'Name on the map',
    settingsNameSub: 'How the command post sees you – tap to change',
  },
  livePosition: {
    chip: '{d} · {n} min ago',
    chipNow: '{d} · now',
    atScene: 'At the incident',
    tapHint: 'Show on the map',
  },
}
