// English copy · Material (Mittel) and checklists.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/material.ts.

import type { Copy, Localizable } from '../index'

export const materialCopy: Localizable<Pick<Copy, 'mittel' | 'checklists'>> = {
  mittel: {
    title: 'Material',
    summary: '{lines} entries',
    summaryEmpty: 'Nothing recorded yet',
    add: 'Material',
    viewBySource: 'by source',
    // the category filter's WORD on a wide head (22.09.2026)
    categoryFilterWord: 'Filter',
    noSource: 'No source',
    searchPlaceholder: 'Search …',
    addOne: 'Record {label}',
    addPickSource: '{label} – choose the source',
    materialSearchPlaceholder: 'Search material …',
    unitSearchPlaceholder: 'Search unit …',
    sourceSearchPlaceholder: 'Search source …',
    categoryFilterLabel: 'Filter by category',
    categoryAll: 'All',
    categoryOther: 'Other',
    customGroup: 'Additional',
    noch: '{n} left',
    stockAria: '{label}: {remaining} of {total} left',
    emptyTitle: 'No material recorded yet.',
    emptyHint: 'Use «+ Material» to record what was used – for the report and to see whether resupply is needed.',
    emptyReadonly: 'No material recorded yet.',
    composerTitle: 'Record material',
    materialLabel: 'Material',
    materialPlaceholder: 'Choose material',
    customMaterial: 'Other material',
    composerFromQuery: 'Record «{name}»',
    unitLabel: 'Unit',
    unitPlaceholder: 'Unit',
    sourceLabel: 'Source',
    sourcePlaceholder: 'Source (optional)',
    qtyLabel: 'Quantity',
    save: 'Save',
    cancel: 'Cancel',
    removeRow: 'Set to 0',
    removedToast: '«{label}» deleted',
    logSet: '{label}: {menge} {unit}',
    logRemoved: '{label} set to 0',
    logDeleted: '{label} deleted',
    logRestored: '{label} restored',
    logStock: '{label} – stock: {stock}',
    logBefore: '(was {n})',
    editLabel: 'Edit entry',
    stockLabel: 'Stock',
    stockPlaceholder: 'optional',
    deleteLine: 'Delete entry',
    // Symbol→Mittel reconciliation strip above the list
    lageStrip: 'Placed, but not logged: {list}',
    lageStripTake: 'Log them',
    lageStripHide: 'Hide suggestions',
    lageStripCapture: 'Log …',
    lagePickTitle: 'Placed, but not logged',
    lagePickSub: '{n} symbols on the map/plans are not in the material log yet. Which were they?',
    lagePickSubOne: 'One symbol on the map/plans is not in the material log yet. Which was it?',
    lagePickGroupHint: 'Symbol on map/plan',
    lagePickGroupSourceHint: 'Source?',
    lagePickUnambiguous: 'Unambiguous',
    lagePickUnambiguousSub: 'logged without asking',
    lagePickOpen: '{n} questions left',
    lagePickOpenOne: '1 question left',
    lagePickConfirm: 'Log {n} items',
    lagePickConfirmOne: 'Log 1 item',

    logNote: '{label} – note: {note}',
    noteLabel: 'Note',
    notePlaceholder: 'e.g. handed over to the works depot',
  },
  checklists: {
    railLabel: 'Checklists',
    showList: 'Show list',
    groupTasks: 'Tasks',
    searchPlaceholder: 'Search keyword …',
    searchAria: 'Search keyword',
    matching: 'Matching: {title}',
    none: 'No checklists available yet.',
    pickEntry: 'Choose or search a keyword.',
    done: 'done',
    variantLabel: 'Variant',
    pickVariant: 'Choose a variant to see the tasks.',
    milestoneTitle: 'Milestone – appears in the log',
    // the word the flag wears on the row (22.09.2026): the tooltip above is what a mouse
    // reads, and a tablet reads nothing — a lone glyph said «something», not what
    milestoneTag: 'noted in the log',
    milestoneUndone: 'Milestone taken back: {text}',
    actionLabels: { journal: 'Log', plan: 'Plan', draw: 'Draw' },
    hazardLabels: { red: 'Fire', orange: 'Hazards', green: 'Traffic', yellow: 'Technical', blue: 'Water' },
    diagramAlt: 'Diagram page {page}',
    diagramOpen: 'Enlarge diagram',
    groupManuals: 'Manuals',
    manualUpdated: 'As of {date}',
    manualWarning: 'Caution:',
    manualImageAlt: 'Picture for step {n}',
    manualImageOpen: 'Enlarge picture',
    manualSource: 'Source: {source}',
  },
}
