// English copy · Objektbesuche.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/objectVisits.ts.

import type { Copy, Localizable } from '../index'

export const objectVisitsCopy: Localizable<Pick<Copy, 'objectVisits'>> = {

  objectVisits: {
    launcher: 'Object visits',
    title: 'Object visits',
    back: 'Back',
    loading: 'Loading object visits …',
    notPreparedTitle: 'Not prepared for offline use yet',
    notPreparedBody: 'This device has never loaded the object list or the checklists. Open Object visits once with a connection; after that they stay on the device.',
    notPreparedDrafts: 'Drafts on this device remain available even without the object list.',
    retry: 'Try again',
    refusedTitle: 'Object visits not available',
    refusedBody: 'The administration has not switched on object visits for this brigade, or this account may not open them.',
    storageUnreadable: 'The device storage could not be read – visits on this device may be missing from this list.',
    myDrafts: 'My drafts',
    unsent: 'Not saved yet',
    lists: 'Lists',
    listObjectsOne: '1 object',
    listObjectsMany: '{n} objects',
    listOn: "on {date}",
    listArchived: "No longer scheduled",
    schedule: {"today": "Today", "overdue": "Overdue", "upcoming": "Upcoming", "undated": "Undated", "recent": "Recently done"},
    listUntil: 'until {date}',
    searchHead: 'Find an object',
    searchPlaceholder: 'Search objects …',
    nearby: 'Nearby',
    nearbyUse: 'Use my location',
    nearbyLocating: 'Finding your location …',
    nearbyFailed: 'Location not available',
    nearbyNone: 'No object in the catalogue has coordinates.',
    distanceM: '{m} m',
    distanceKm: '{km} km',
    neverVisited: 'never visited',
    lastVisit: 'last {date}',
    intro: 'Pick an object from a list, the search or «Nearby». The visit is saved on this device first and sent as soon as there is a connection.',
    viewerNote: 'With this account you can read visits but not record them.',
    listSub: '{done} of {total} visited',
    listUnresolved: '{n} objects of this list are not known on this device.',
    listUnknown: 'This list is not known on this device.',
    listDoneElsewhere: 'done',
    stateDraft: 'Draft',
    stateDone: '✓ {date}',
    statePhotos: 'Photos pending',
    stateUnsent: 'not sent',
    visitLoading: 'Loading visit …',
    visitMissing: 'This visit is not on this device and could not be loaded.',
    objectUnknown: 'The object «{key}» is not known in this device\'s catalogue.',
    chooseChecklist: 'Which checklist?',
    chooseChecklistLead: 'There are several visit checklists for this object.',
    noChecklist: 'Without a checklist',
    plans: 'Plans',
    changeChecklist: 'Change checklist',
    changeChecklistLead: 'Answers that also exist in the new checklist stay. Photos always stay.',
    checklistCurrent: 'current',
    changeChecklistDropOne: '1 answer does not fit the new checklist and will be removed. Photos stay.',
    changeChecklistDropMany: '{n} answers do not fit the new checklist and will be removed. Photos stay.',
    changeChecklistConfirm: 'Change',
    planLoading: 'Loading plan …',
    suggestedHead: 'In the incident',
    startFailed: 'The visit could not be created',
    menu: 'More actions',
    saveFile: 'Save as file',
    discard: 'Discard draft',
    discardTitle: 'Discard draft?',
    discardMsg: 'The visit is marked as discarded and no longer appears in any list. This cannot be undone.',
    discardBtn: 'Discard',
    details: 'By & date',
    visitedAt: 'Visited on',
    with: 'By',
    withPlaceholder: 'Names, e.g. Max Muster, Nina Frei',
    notChecked: 'not checked',
    photoMissing: 'Photo missing',
    answer: { ok: 'OK', defect: 'Defect', na: 'n/a', yes: 'Yes', no: 'No', photo: 'Photo' },
    defectNote: 'What is the defect?',
    defectNotePlaceholder: 'e.g. lid jams',
    photosAdded: '{n} photos added',
    photosOne: '1 photo',
    photosMany: '{n} photos',
    takePhoto: 'Take photo',
    addPhoto: 'Add photo',
    valuePlaceholder: 'Value',
    notes: 'Remarks',
    notesPlaceholder: 'Anything else you noticed …',
    photos: 'Photos',
    proposals: 'Correction proposals',
    proposalAdd: 'Add proposal',
    proposalRow: 'was: {current} · new: {proposed}',
    proposalRowNew: 'new: {proposed}',
    complete: 'Complete',
    completeOpenOne: '1 item not checked',
    completeOpenMany: '{n} items not checked',
    completeOpenMsg: 'Complete anyway? Unchecked items appear in the report as «not checked».',
    completeRequired: 'Required among them: {items}',
    completeAnyway: 'Complete anyway',
    completed: 'Visit completed',
    correctionNote: 'Correction: the visit stays completed; the change becomes a new revision.',
    correctionDone: 'Done',
    lifecycle: { draft: 'Draft', completed: 'Completed', discarded: 'Discarded' },
    sync: {
      unsaved: 'Not saved',
      conflict: 'Conflict',
      auth: 'Sign-in needed',
      error: 'Not sent',
      sending: 'Sending',
      local: 'Only on this device',
      localAt: 'on device {time}',
      changes: 'Changes on device {time}',
      photos: 'Photos {done}/{total}',
      saved: 'Saved {time}',
      remote: 'Revision {n}',
      offline: 'offline',
    },
    delivery: { waiting: 'Filing pending', delivered: 'filed', failed: 'Filing: error', paused: 'Filing paused' },
    statusTitle: 'State of this visit',
    statusOpen: 'Show state',
    statusLifecycle: 'Visit',
    statusDevice: 'Device → server',
    statusFiling: 'Filing',
    statusSavedAt: 'Saved on this device at {time}.',
    statusRevision: 'Revision {n} on the server.',
    statusNeverSent: 'Never sent to the server yet.',
    statusPending: 'Newer changes are only on this device.',
    statusPhotos: '{done} of {total} photos on the server.',
    statusNoFiling: 'No filing destination set up.',
    destinationSharePoint: 'SharePoint',
    statusFilingRow: '{destination}: {state}',
    conflictTitle: 'Two versions: {what}',
    conflictBody: 'The same item was changed on another device.',
    conflictMine: 'Mine',
    conflictTheirs: 'Other',
    conflictBoth: 'Keep both',
    conflictRemoved: '(removed)',
    conflictWhat: {
      notes: 'Remarks', visitedAt: 'Visit date', with: 'By', checklist: 'Checklist',
      workRef: 'List', object: 'Object', photo: 'Photo', proposal: 'Proposal',
    },
    unsavedTitle: 'Not saved on the device',
    unsavedBody: 'The browser refused to save (storage full?). Whatever is not saved exists only in this window.',
    unsavedRetry: 'Save again',
    authTitle: 'Sign-in expired',
    authBody: 'The visit is safe on this device. Sign in again to send it.',
    authLogin: 'Sign in',
    errorTitle: 'The server did not accept the visit',
    errorAttachment: 'A photo was not accepted',
    errorForbidden: 'This account may not record visits.',
    errorDisabled: 'Object visits are switched off.',
    photoTitle: 'Photo',
    photoCaption: 'Caption',
    photoCaptionPlaceholder: 'e.g. north entrance',
    photoBelongs: 'Belongs to',
    photoGeneral: 'General',
    photoStored: 'Saved on this device · will be sent as soon as there is a connection',
    photoNotStored: 'Not saved on the device – only in this window',
    photoAnother: 'Another one',
    photoDone: 'Done',
    photoRemove: 'Remove photo',
    photoRemoved: 'Photo removed',
    photoPreparing: 'Preparing photo …',
    photoFailed: 'The photo could not be taken over',
    photoPending: 'not sent yet',
    photoOpen: 'Open photo: {caption}',
    proposalTitle: 'Propose a correction',
    proposalField: 'Field',
    proposalOther: 'Other',
    proposalOtherLabel: 'Which field?',
    proposalCurrent: 'Current',
    proposalCurrentHint: 'as in the master data',
    proposalNew: 'New',
    proposalReason: 'Reason',
    proposalReasonPlaceholder: 'e.g. caretaker has changed',
    proposalSave: 'Save proposal',
    proposalRemove: 'Remove proposal',
    proposalRemoved: 'Proposal removed',
    defectsOne: '1 defect',
    defectsMany: '{n} defects',
    countOk: '{n} OK',
    countOpen: '{n} not checked',
    proposalsOne: '1 proposal',
    proposalsMany: '{n} proposals',
    report: 'Report (PDF)',
    reportSub: 'Revision {n}',
    reportFailed: 'The report could not be loaded',
    edit: 'Edit',
    editSub: 'Correction · stays completed, new revision',
    history: 'History',
    historyFailed: 'The history could not be loaded',
    historyRow: 'r{n} · {time}',
    nextInList: 'Next in the list',
    listDone: 'Every object of this list has been visited.',
    by: 'By {name}',
    fileSaved: 'File saved',
    fileSavedMissing: 'File saved – {n} photos were not on this device',
    fileFailed: 'The file could not be created',
    sent: 'Sent',
    sendContended: 'Conflict with another device – will retry shortly',
    conflictTakeOther: 'Take the other',
    conflictKeep: 'Keep this one',
    conflictOther: 'Other version',
    conflictCurrent: 'In the visit',
    storageWait: 'The device storage could not be read. So that no second draft is created, no new visit is started now.',
    sendOffline: 'Offline – will be sent as soon as the server is reachable',
  },
}
