// English copy · photos, weather, PDF, Einstellungen, Feedback, offline and empty states.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/panels.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'photoViewer' | 'photoGeo' | 'einsatzuhr' | 'mapPicker' | 'weather' | 'weatherLayer' | 'pdf' | 'settings'
  | 'feedback' | 'offline' | 'emptyApp' | 'incidentAlert'

export const panelsCopy: Localizable<Pick<Copy, Keys>> = {
  mapPicker: {
    title: 'Set location on map',
    hint: 'Tap the map to set the location',
    confirm: 'Use location',
  },
  weather: {
    label: 'Weather',
    details: 'Weather details',
    unavailable: 'Weather data currently unavailable',
    from: 'from',
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
    cardinalsLong: ['North', 'Northeast', 'East', 'Southeast', 'South', 'Southwest', 'West', 'Northwest'],
    windTitle: 'Wind {dir} ({deg}°)',
    detailsHint: ' – tap for details',
    meteoHint: ' – tap for MeteoSwiss details',
    windDir: 'Wind direction',
    windSpeed: 'Wind speed',
    gust: 'Gusts',
    precip: 'Precipitation',
    station: 'Station',
    source: 'Source',
    meteoRadar: 'MeteoSwiss precipitation radar',
    detailsUrl: 'https://www.meteoswiss.admin.ch/services-and-publications/applications/precipitation.html',
    conditions: {
      clear: 'Clear', fair: 'Fair', partly: 'Partly cloudy', overcast: 'Overcast',
      fog: 'Fog', drizzle: 'Drizzle', rain: 'Rain', snow: 'Snow',
      rainShowers: 'Rain showers', snowShowers: 'Snow showers', thunder: 'Thunderstorm', cloudy: 'Cloudy',
    },
    windShiftOpen: 'Open in log',
    windShiftDismiss: 'Dismiss',
  },
  weatherLayer: {
    group: 'Weather',
    radar: 'Precipitation (radar)',
    radarSub: 'MeteoSwiss · last hour',
    attribution: 'Radar © MeteoSwiss',
    radarTitle: 'Precipitation radar',
    play: 'Play the last hour',
    pause: 'Stop (back to now)',
    frameSlider: 'Choose radar image',
    frameAgo: '{minutes} min ago',
    latest: 'now',
    legendLight: 'light',
    legendUnit: 'mm/h · radar estimate',
    legendHeavy: 'heavy',
    radarPending: 'No radar image yet – loading.',
    radarUnavailable: 'Radar currently unavailable.',
    stale: 'As of {time} – out of date',
  },
  pdf: {
    loading: 'Loading PDF…',
    failed: 'Could not load the PDF.',
    retry: 'Try again',
    reason: {
      stale: 'The app is running an old version – close it and open it again.',
      offline: 'No connection – this PDF is not stored on this device.',
      missing: 'The PDF is no longer on the server.',
      denied: 'Your sign-in is no longer valid – sign in again.',
      timeout: 'The server did not respond.',
      unsupported: 'This browser is too old to display PDFs.',
      unknown: 'Reason unknown.',
    },
  },
  settings: {
    title: 'Settings',
    deviceGroup: 'Device',
    colorScheme: 'Color scheme',
    symbolSizeMap: 'Symbol size – map',
    symbolSizeMapSub: 'Tactical symbols on the situation map and linked module plans',
    symbolSizeBoard: 'Symbol size – modules',
    symbolSizeBoardSub: 'Tactical symbols on unlinked module plans',
    symbolCaptions: 'Captions',
    symbolCaptionsSub: 'Key value under the symbol',
    railLabels: 'Rail labels',
    railLabelsSub: 'A word under every glyph in both rails',
    captionsOff: 'Off',
    captionsAuto: 'Auto',
    captionsAll: 'All',
    offlineRadius: 'Offline radius',
    offlineAuto: 'Offline preparation',
    offlineAutoSub: 'Loads map & plans by itself shortly after opening',
    offlineRadiusSub: 'Map & lines around the incident',
    deviceFoot: 'Applies to this device only. A smaller radius = faster, smaller offline download.',
    incidentGroup: 'Incident',
    contactInterval: 'SCBA radio contact',
    contactIntervalSub: 'Interval until contact is due (amber)',
    contactIntervalAria: 'Radio contact interval',
    grace: 'Grace period',
    graceSub: 'Red alarm after interval + grace',
    funkkanal: 'Radio channel',
    funkkanalSub: 'Default for new SCBA teams',
    syncedFoot: 'Synced with all devices',
    syncedFootViewer: ' · only the incident commander can change them',
    utilityGroup: 'Templates',
    blankSheet: 'Blank capture sheet (PDF)',
    blankSheetSub: 'Paper sheet to fill in by hand',
    blankSheetDownload: 'Download',
    blankSheetFailed: 'PDF failed – try again',

    keepScreenOn: 'Keep the display on',
    keepScreenOnSub: 'Do not dim the screen during an incident',
    feedbackRow: 'Give feedback',
    feedbackRowSub: 'What was awkward or missing',
    feedbackOpen: 'Write',
  },
  offline: {
    title: 'Offline readiness',
    browserTitle: 'Reliably offline as the installed app',
    browserBody: 'Nothing is reliably stored in a browser tab: map tiles, plans and utility layers can be cleared at any time, and the tab has to still be open at the next incident. Installed, KP Front runs with no signal.',
    browserNoInstall: 'This device offers no installation. For use without a signal, install KP Front on the tablet or phone.',
    syncedAgo: 'Incident data synced {ago}',
    offline: 'Offline – saved locally',
    pending: 'Saving …',
    error: 'Sync error – saved locally',
    agoNever: 'not yet',
    agoJustNow: 'just now',
    agoMin: '{n} min ago',
    agoHour: '{n} h ago',
    checking: 'checking …',
    ready: 'ready',
    notLoaded: 'not loaded',
    loading: 'loading …',
    rowSymbols: 'Symbols',
    rowHazmat: 'Dangerous goods (UN/ADR)',
    rowMap: 'Map',
    noLayer: 'no layer',
    rowPlans: 'Plans',
    noObject: 'no object',
    rowLeitung: 'Reference layers',
    geoAllReady: 'all {n} ready',
    geoSome: '{cached}/{total} loaded',
    rowWeather: 'Weather',
    weatherUnreachable: 'unreachable',
    onlineOnly: 'online only',
    rowPersonnel: 'Personnel',
    personnelCount: '{n} people',
    rowObjectSearch: 'Object search',
    rowStorage: 'Device storage',
    storageFree: '{size} free',
    storageUnknown: 'Device reports no storage figure',
    storageFullShort: 'Full – nothing is saved locally',
    storageFull: 'Storage full – changes are not saved locally',
    dlTightTitle: 'Low storage on this device',
    dlTightMsg: 'The download needs ≈ {need}, {free} is free. Reduced, the whole area is loaded but in less detail (about {pct} % of the map tiles). That leaves room for the incident record.',
    dlTightConfirm: 'Load reduced',
    dlNoSpace: 'Not enough storage for the offline set (only {free} free). Please free up space on the device.',
    loadingForOffline: 'Loading for offline …',
    cancel: 'Cancel',
    loadAll: 'Load everything for offline',
    foot: 'Loads map, plans, symbols and utility lines for this incident onto this device. Weather and object search need a connection and are not available offline.',
    wsDropped: 'Skipped {n} corrupted entries while loading',
    wsNewer: 'Incident data was saved by a newer app version – please update the app.',
    dlDone: 'Map ready offline – {n} tiles',
    dlDoneCapped: 'Map ready offline – area limited, {n} tiles',
    dlPartial: 'Partly loaded – {n} of {total}. The map is missing at the edge of the area.',
    dlPartialCapped: 'Partly loaded – {n} of {total}, area limited. The map is missing at the edge.',
    dlNone: 'Nothing loaded – no connection. The map will not be available at the scene.',
    dlNoCoverage: 'Nothing loaded – the map source has no coverage here. Check the map layer or tile URL.',
    dlContinue: 'Keep loading',
    dlRetry: 'Try again',
    dlFailed: 'Offline download failed',
  },
  emptyApp: {
    title: 'No open incident',
    bodyViewer: 'No incident is currently active.',
    bodyEditor: 'Open an incident.',
    bodyEditorAlarm: 'Open an incident or take over a {provider} alarm.',
    history: 'History',
  },
  incidentAlert: {
    kicker: 'New incident',
    switch: 'Switch',
    open: 'Open',
    later: 'Later',
  },
  photoViewer: {
    title: 'Photo',
    download: 'Download',
  },
  photoGeo: {
    place: 'Place on map',
    placeN: 'Place {n} photos on map',
    show: 'Show on map',
    placedStep: 'Photo placed on map',
    logPlaced: 'Photo placed on map',
    logPlacedN: '{n} photos placed on map',
    where: 'Taken at',
    whereN: 'Photo {n} taken at',
    distance: '{d} from the incident',
    facing: 'facing {dir}',
    takenAt: 'taken {t}',
    tooFar: 'Too far away for the map',
    marker: 'Photo from the log',
    markerTaken: 'Photo from the log · taken {t}',
    planMark: 'Photo – move or remove it on the map',
    sourceExif: 'from the photo',
    sourceDevice: 'device location',
    accuracy: '± {m} m',
    askTitle: 'Save a location with photos?',
    askMessage: 'The camera gives KP Front no location. With this device\'s location, a photo can be placed on the map.',
    askNote: 'Only the position is saved, and only near the incident. Change it in Settings.',
    askYes: 'Use location',
    askNo: 'Don\'t use',
    settingsLabel: 'Location for photos',
    settingsHint: 'If a photo has no location of its own, this device\'s location is used – only near the incident',
    locatedLate: 'Photo with location',
  },
  einsatzuhr: {
    title: 'Incident duration — started {t}',
    modeElapsed: 'Incident duration',
    modeNow: 'Time of day',
    modeStart: 'Incident start',
  },
  feedback: {
    title: 'Feedback',
    promptTitle: 'One quick question',
    promptDismiss: 'Not now',
    promptOpen: 'Describe briefly',
    promptFor: {
      crashLoop: 'The app crashed several times during one incident. What were you doing?',
      crash: 'The app crashed once just now. What were you doing?',
      renderStorm: 'The app ran itself hot during an incident – probably sluggish, or the battery drained fast. What was open at the time?',
      storageFull: 'Storage was full on this device. Did anything get lost?',
      syncConflict: 'Two devices had different states. Was anything missing in the end?',
    },
    kinds: {
      crashLoop: 'repeated crash in the same incident',
      crash: 'interface crash',
      renderStorm: 'interface under constant load',
      storageFull: 'device storage full',
      syncConflict: 'sync conflict while merging',
    },
    subject: 'Feedback',
    intro: 'What happened, and what would you have expected? A sentence or two is enough.',
    placeholder: 'e.g. «Set the team to returning, then the screen went white.»',
    techTitle: 'This is sent along',
    techNote: 'Nothing else — no incident data, no addresses, no names. The app never takes a screenshot by itself.',
    routeGithub: 'Report as a GitHub issue',
    routeGithubBadge: 'recommended',
    routeGithubNote: 'Opens a pre-filled form. You can follow the report afterwards and are notified when it is resolved. Needs a GitHub account.',
    routeMail: 'Send by e-mail',
    routeMailBadge: 'no account',
    routeMailNote: 'Always works, GitHub or not. The reply comes straight back by e-mail.',
    next: 'Continue',
    diagNote: 'Either way: the diagnostics file ({n}) is saved when you continue — attach it to the issue or the mail. Without it the actual error message is missing.',
    diagNoteEmpty: 'Either way: no error logs have been recorded at the moment. Just describe what happened.',
    diagCount: '{n} error logs',
    diagCountOne: '1 error log',
    diagLine: 'Errors: ',
    diagSaved: 'Diagnostics file «{name}» saved — please attach it.',
    diagFailed: 'The diagnostics file could not be created — the report still works.',
    privacy: 'Nothing is sent automatically. You decide whether, how and to whom.',
    close: 'Close',
    tech: {
      version: 'Version:',
      locale: 'Language:',
      device: 'Device: ',
      viewport: 'Window: ',
      network: 'Network:',
      event: 'Incident:',
      online: 'online',
      offline: 'offline',
      noDescription: '(no description)',
    },
  },
}
