// English copy · the Rapport: Auswertung, report, preflight.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/report.ts.

import type { Copy, Localizable } from '../index'

export const reportCopy: Localizable<Pick<Copy, 'auswertung' | 'report' | 'wheel' | 'preflight'>> = {
  auswertung: {
    heading: 'Debrief',
    note: 'For the debrief – derived from the incident record, not part of the signed report.',
    missing: '—',
    firstOnScene: 'Alarm to 1st vehicle on scene',
    firstOnSceneDef: 'From the alarm to the earliest «on scene» time of any vehicle (alarm / turnout times).',
    firstAs: 'Alarm to 1st SCBA entry',
    firstAsDef: 'From the alarm to the first entry of a team under SCBA.',
    contacts: 'Radio contacts on time',
    contactsSub: '{n} overdue of {total}',
    contactsDef: 'Share of the SCBA radio-contact intervals that ended before the team was overdue ({n} min + {g}). An interval runs from the entry or a contact to the next contact, pressure, withdrawal or exit; an open one counts only once it became overdue. Time between closing and reopening does not count.',
    contactsDefNoGrace: 'Share of the SCBA radio-contact intervals that ended before the team was overdue ({n} min). An interval runs from the entry or a contact to the next contact, pressure, withdrawal or exit; an open one counts only once it became overdue. Time between closing and reopening does not count.',
    longestAs: 'Longest SCBA deployment',
    longestAsDef: 'Longest completed time of a team under SCBA, entry to exit.',
    total: 'Incident duration',
    totalDef: 'From the alarm to the end of the incident.',
    totalRunning: 'Incident still running',
    truppLane: 'Team {no} · {name}',
    groupPhases: 'Phases (checklist)',
    groupVehicles: 'Vehicles',
    groupTrupps: 'Teams',
    groupMilestones: 'Milestones',
    noTimeline: 'No vehicle, team or checklist times recorded.',
    legendTravel: 'en route',
    legendScene: 'on scene',
    legendReturn: 'returning',
    legendAs: 'under SCBA',
    legendWork: 'deployed without SCBA',
    legendStandby: 'standing by',
    legendContact: 'radio contact',
    legendFaellig: 'contact due',
    legendUeberfaellig: 'overdue',
    legendMilestone: 'milestone',
    legendPhase: 'phase: first to last tick',
    footnotesHead: 'Definitions',
    lehrenSeePage1: 'Lessons / safety: see page 1',
    graceMin: '{n} min',
    graceSec: '{n} s',
  },
  report: {
    erfasser: 'Recorded by',
    gerettete: 'Rescued',
    gerettetePersonen: 'people',
    geretteteTiere: 'animals',
    gerettetePerson: 'person',
    geretteteTier: 'animal',
    rueckmeldungElz: 'Report back to dispatch',
    back: 'Back',
    print: 'Print',
    keyword: 'Keyword',
    einsatzleiter: 'Incident commander',
    // the printed IC succession when command rotated mid-incident (lib/reportPdfDirect)
    einsatzleitungBis: '{name} (until {t})',
    einsatzleitungAb: '{name} (from {t})',
    kontaktperson: 'Contact person',
    alarmierung: 'Alerted',
    ausgerueckt: 'Turned out',
    incidentId: 'Incident ID',
    alarmMessage: 'Alarm message',
    partnerOrgs: 'Partner organisations',
    remarks: 'Remarks',
    kroki: 'Sketch',
    krokiState: '{title} · as of {at}',
    atemschutz: 'SCBA monitoring',
    truppEntry: 'Entry',
    mittel: 'Material (enter quantity)',
    journal: 'Incident journal',
    photo: 'Photo',
    transcript: 'Transcript',
    planFallback: 'Plan',
    proofOffline: 'Verification not possible (offline)',
    proofIntact: 'Hash chain intact',
    proofBroken: 'Hash chain broken',
    proofBrokenAt: 'Hash chain broken at #{seq}',
    areaManual: 'Manual',
    areaAtemschutz: 'Teams',
    areaAnwesenheit: 'Attendance',
    areaMittel: 'Material',
    areaChecklist: 'Checklist',
    areaRapport: 'Report',
    areaSystem: 'System',
    areaLage: 'Situation',
    drawCircle: 'Cordon',
    drawAreaLabeled: 'Section "{label}"',
    drawArea: 'Area',
    drawRescueAxis: 'Rescue axis',
    drawMeasureArrow: 'Measure arrow',
    drawLine: 'Line',

    pdf: 'Download PDF',
    pdfBusy: 'Creating the PDF …',
    pdfFailed: 'The PDF could not be created.',
    lehren: 'Lessons / safety',
  },
  wheel: {
    invalidTime: 'Enter a valid time (00:00–23:59).',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    now: 'Now',
    ok: 'OK',
  },
  preflight: {
    pdfFull: 'Incident report (PDF)',
    pdfBusy: 'Generating PDF …',
    geretteteLabel: 'Rescued',
    geretteteLageStrip: 'On the map: {list}',
    geretteteLagePersonen: '{n} people',
    geretteteLageTiere: '{n} animals',
    geretteteLageTake: 'Apply',
    gerettetePersonen: 'People',
    geretteteTiere: 'Animals',
    geretteteNone: 'None',
    geretteteNoneHint: 'Nothing rescued',
    geretteteNonePrint: 'none',
    gruppenLabel: 'Group alarm times',
    fahrzeugeLabel: 'Vehicle turnout times',
    ausgeruecktDerived: 'derived from the vehicle times',
    vorOrtShort: 'on scene',
    zurueckShort: 'returned',
    gpsTableTitle: 'Vehicles GPS · live',
    gpsTableNote: 'Times from the GPS positions, recorded by the server',
    gpsColFzg: 'Veh.',
    gpsColStatus: 'Status',
    gpsColAn: 'arr.',
    gpsColAb: 'dep.',
    gpsColFahrten: 'Trips',
    gpsColPos: 'Pos.',
    gpsStatusScene: 'on scene',
    gpsStatusAway: 'en route',
    gpsAgeSec: '{n} s ago',
    gpsAgeMin: '{n} min ago',
    gpsAgeHour: '{n} h ago',
    gpsAgeStale: 'Position outdated',
    fahrtenCount: '{n} trips',
    rueckmeldungLabel: 'Report back to dispatch',
    rueckmeldungName: 'Name',
    rueckmeldungZeit: 'Time of report to control room',
    title: 'Incident report',
    headAllRecorded: 'all details recorded',
    headStillOpen: 'open',
    tabsLabel: 'Part of the report',
    tabs: { bericht: 'Report', werwas: 'Personnel & Material', beilagen: 'Attachments' },
    stichwort: 'Keyword',
    einsatzart: 'Type',
    ort: 'Location',
    fromDispatch: 'From the incident data',
    edit: 'Edit',
    alarmMessage: 'Alarm message',
    alarmierung: 'Alerted',
    notRecorded: 'Not recorded',
    summaryLabel: 'Summary',
    summaryPlaceholder: 'What happened / what was found?',
    einsatzleiterLabel: 'Incident commander',
    einsatzleiterPlaceholder: 'Select or type',
    kontaktpersonLabel: 'Contact person',
    kontaktpersonClear: 'Clear contact person',
    kontaktpersonPlaceholder: 'Owner / caller',
    kontaktpersonTelefon: 'Contact person phone',
    kontaktpersonTelefonClear: 'Clear phone',
    kontaktpersonTelefonPlaceholder: 'Phone number',
    kontaktpersonCall: 'Call contact person',
    entfaellt: 'Not applicable',
    entfaelltUndo: 'Change',
    incidentEndLabel: 'Incident end',
    zeitBeforeAlarm: 'Earlier than the alarm ({t})',
    zeitBeforeAusgerueckt: 'Earlier than turnout ({t})',
    zeitFuture: 'In the future',
    madeToast: 'Report created',
    bandDone: 'Report created.',
    bandAsk: 'The incident is still open – close it?',
    bandLater: 'Later',
    exportIncompleteTitle: 'Details still missing',
    exportIncompleteLead: 'Still open:',
    exportIncompleteMsg: 'The report can still be produced — the open fields stay blank and can be filled in by hand.',
    now: 'Now',
    remarksLabel: 'Remarks',
    remarksPlaceholder: 'Optional',
    sectionsHead: 'Sections',
    printMenu: 'More print options',
    toggleKroki: 'Sketch',
    plansAnnotated: 'Annotated plans ({n})',
    toggleGebaeude: 'Building – storeys ({n})',
    plansAll: 'All plans',
    toggleAtemschutz: 'SCBA monitoring ({n})',
    toggleAttendance: 'Attendance ({n})',
    toggleMittel: 'Material ({n})',
    toggleJournal: 'Incident journal',
    togglePendenzen: 'Tasks / open items ({n})',
    toggleAttachments: 'Photos ({n})',
    archiveZip: 'Download attachments (ZIP)',
    krokiAtLabel: 'Kroki as of',
    krokiOrientation: 'Orientation',
    krokiPortrait: 'Portrait',
    krokiLandscape: 'Landscape',
    krokiAtNow: 'Now',
    krokiAtFailed: 'The situation at that moment could not be reconstructed – the current one is printed.',
    partnersLabel: 'Partner organisations',
    partnerOrg: 'Organisation (e.g. police)',
    partnerOrgShort: 'Organisation',
    partnerNote: 'Remark (e.g. taking over traffic)',
    partnerNoteShort: 'Remark',
    partnersNone: 'none recorded',
    partnerAdd: 'Add organisation',
    partnerPlaceholder: 'Organisation …',
    partnerLageStrip: 'On the map: {list}',
    partnerLageTake: 'Apply',
    attachmentsHead: 'Photos',
    attachmentsAdd: 'Add photo',
    attachmentsOpen: 'View the photo',
    attachmentsCount: '{n} photo(s)',
    attachmentsNone: 'none',
    attachmentsCaption: 'Caption (e.g. «Driver\'s licence»)',
    attachmentsPending: 'not uploaded yet',
    attachmentsFailed: 'Photo {name} could not be uploaded – it will not appear in print.',
    attachmentAdded: 'Photo added',
    attachmentCaptioned: 'Caption',
    attachmentRemoved: 'Photo removed',
    linksHead: 'Forms & links',
    shareHead: 'Share',
    shareLede: 'No login · still valid after closing.',
    shareLiveLede: 'No login · still valid after closing.',
    shareCreate: 'Create link',
    shareBusy: 'Creating link …',
    shareLoading: 'Loading link …',
    shareLoadFailed: 'The link could not be loaded.',
    shareRetry: 'Try again',
    shareCreateFailed: 'Creating the link failed',
    shareCopy: 'Copy address',
    shareCopied: 'Copied',
    shareScan: 'Scan with the camera',
    shareSend: 'Send …',
    shareWarn: 'Anyone holding the link sees the whole incident – the names of everyone present, '
      + 'the photos and the full journal.',
    shareRevoke: 'Revoke link',
    shareRevokeTitle: 'Revoke the link to the whole incident?',
    shareRevokeBody: 'The address stops working. Anyone who has it open right now loses access '
      + 'immediately. A new link can be created at any time – it will be a different address.',
    shareRevokeConfirm: 'Yes, revoke',
    shareRevokeFailed: 'Revoking the link failed',
    shareKindLabel: 'What the link opens',
    shareKindFull: 'Incident · read',
    shareKindAtem: 'Teams · operate',
    shareAsLede: 'Whoever opens the link sees only this incident’s team board – the SCBA '
      + 'monitoring – and operates it: register a team, contact, pressure, withdrawal, out. No '
      + 'map, no log. Valid until the incident is closed.',
    shareAsLiveLede: 'Valid until the incident is closed.',
    shareAsWarn: 'Whatever is entered there appears in the report under «SCBA monitoring». Give the link only '
      + 'to the person doing the monitoring.',
    shareAsRevokeTitle: 'Revoke the link to the team board?',
    shareAsRevokeBody: 'The address stops working. Anyone with the board open can no longer enter '
      + 'anything. A new link can be created at any time – it is then a different address.',
    linksCount: '{done} of {n} done',
    linksOpen: 'Open',
    linksMarkDone: 'Mark {title} as done',
    linksMarkOpen: 'Mark {title} as open again',
    linksDoneAt: 'done · {at}',
    linksOpened: '{title} opened.',
    linksOpenedAction: 'Done',
    linksOpenFailed: '{title} could not be opened – the browser blocked the window.',
    toggleDetailedAudit: 'Detailed integrity proof',
    toggleAuswertung: 'Debrief (internal)',
    krokiHead: 'Sketch crop',
    framingHint: 'Pan and zoom the map – exactly this crop is printed.',
    framingFollows: 'Follows the situation',
    framingFollowOn: 'The crop grows with the situation. Panning switches this off.',
    framingOutside: '{n} outside – tap to fit',
    framingLegend: 'Legend',
    framingLegendEmpty: 'nothing labelled inside the crop',
    framingLegendPending: 'updates when you let go …',
    framingLegendMissing: '{n} without a number – the disc does not fully fit on the sheet.',
    framingDiscOut: 'Will not be in the legend – the disc does not fully fit on the sheet.',
    controlHead: 'Checks',
    plansPrintNone: 'Plans are not printed – add them from the ▾ menu if needed.',
    plansPrintAnnotated: '{n} annotated plans will be printed.',
    plansPrintAll: 'All plans will be printed.',
    missingTranscripts: '{n} audio entry/entries without a transcript – add for the record.',
    fixTranscripts: 'Add in the log',
    stateNote: 'As of: whole incident up to report creation ({at}).',

    sectionBericht: 'Report & people involved',
    sectionZeiten: 'Times',
    sectionNachbearbeitung: 'Follow-up',
    vehicleOrder: 'Turnout order',
    einsatzplan: 'Incident plan',
    lehrenLabel: 'Lessons / safety',
    lehrenPlaceholder: 'Findings, safety notes (optional)',
    logMetaChanged: 'Report details: {fields}',
    metaValue: '{label} «{value}»',
    metaWritten: 'written',
    metaRewritten: 'revised',
    metaCleared: 'cleared',
    metaRueckmeldung: 'Report to the control room by {name} at {t}',
    metaRueckmeldungTime: 'Report to the control room at {t}',
    metaRueckmeldungName: 'Report to the control room by {name}',
    metaGeretteteNone: 'Rescued: none',
    metaGeretteteNoneOff: 'Rescued: «none» withdrawn',
    metaGerettete: 'Rescued: {value}',
    metaPartnerAdded: 'Partner organisation {org} added',
    metaPartnerRemoved: 'Partner organisation {org} removed',
    metaPartnerNote: 'Partner organisation {org} – note: {note}',
    metaPartnerNoteCleared: 'Partner organisation {org} – remark removed',
    metaPartnerUnnamed: 'Partner organisation recorded',
    metaGruppe: 'Alarm time {gruppe}: {t}',
    metaGruppeCleared: 'Alarm time {gruppe} cleared',
    metaFahrzeugAus: '{fahrzeug} turned out {t}',
    metaFahrzeugVorOrt: '{fahrzeug} on scene {t}',
    metaFahrzeugZurueck: '{fahrzeug} back {t}',
    metaFahrzeugCleared: '{fahrzeug}: time cleared',
    metaMittelNoneOn: 'Material: «none used» confirmed',
    metaMittelNoneOff: 'Material: «none used» withdrawn',
    metaNoneOn: '{label}: not applicable',
    metaNoneOff: '{label}: «not applicable» withdrawn',
    controlOpen: '{n} open',
    pdfShort: 'PDF',
    controlHint: '1 note',
    controlHints: '{n} notes',
    controlOpenHead: 'Still open',
    unresolvedHours: '{names}: times run backwards or are missing — not in the deployment hours.',
    pendingMedia: '{n} photo/audio not uploaded yet — it will be added once there is a connection; it may not be visible on other devices yet.',
    pendingMediaConfirm: '{n} photo/audio not uploaded yet – kept on this device',
    truppsDeployedConfirm: 'Still deployed: {n} – never reported out',
  },
}
