// English copy · tactical symbol names, search aliases and categories.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/symbols.ts.

import type { Copy, Localizable } from '../index'

export const symbolsCopy: Localizable<Pick<Copy, 'symbolNames' | 'symbolAliases' | 'symbolCategories'>> = {
  // Tactical-symbol display labels, keyed by the RAW FireGIS name. Stored identity stays the raw
  // name; only the label localizes. Missing keys fall back to the German label / displayNames.
  symbolNames: {
    'VKF Feuer': 'Fire',
    'VKF Rettungen': 'Rescue',
    'VKF Unfall': 'Accident',
    'VKF Gefaehrliche Stoffe': 'Hazmat',
    'VKF Wasser': 'Water',
    'FW Gefahr allgemein': 'Hazard',
    'FW Gefahr Tafel': 'Hazard placard',
    'FW Gefahr Radioaktiv': 'Radioactive',
    'FW Gefahr Ex': 'Explosion',
    'FW Gefahr G': 'Gas',
    'FW Gefahr C': 'Chemical',
    'FW Gefahr W': 'Water',
    'FW Elektroanlage': 'Electrical installation',
    'VKF Patientensammelstelle': 'Casualty collection point',
    'VKF Sanitaetshilfsstelle': 'Medical aid post',
    'VKF Totensammelstelle': 'Fatalities collection point',
    'VKF Sammelstelle': 'Uninjured',
    'FW Sammelplatz': 'Assembly point',
    'FW Warteraum': 'Holding area',
    'FW Verwundetennest': 'Casualty nest',
    'VKF Bereich Sanitaet': 'Medical',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Incident commander',
    'FW Offizier': 'Officer',
    'VKF Kontrollposten': 'Checkpoint',
    'VKF Informationszentrum': 'Information centre',
    'VKF Bereich Materialdepot': 'Materials depot',
    'FW Absperrung': 'Cordon',
    'VKF Verkehrssperre ueberwacht': 'Road closure',
    'VKF Drehleiter': 'Turntable ladder',
    'VKF Hubretter': 'Aerial platform',
    'VKF Fahrzeug': 'Vehicle',
    'VKF Pumpe Typ2': 'Pump',
    'VKF Helilandeplatz': 'Helicopter landing site',
    'VKF Luefter mobil': 'Fan',
    'FW Entrauchung': 'Smoke extraction',
    'FW Kleinloeschgeraet': 'Small extinguisher',
    'FW Sprungretter': 'Jump rescue cushion',
    'FW Leiter': 'Ladder',
    'SI Ueberflurhydrant': 'Pillar hydrant',
    'SI Unterflurhydrant': 'Underground hydrant',
    'VKF Innenhydrant': 'Indoor hydrant',
    'SI Wasserloeschposten': 'Hose reel post',
    'WV Loeschweier': 'Fire pond',
    'SI Wasserbezugsort': 'Water draw point',
    'SI Wasserdruckversorgung': 'Pressurised water supply',
    'GB Lift': 'Lift',
    'GB Kamin': 'Chimney',
    'GB Abzug': 'Vent',
    'SI Schieber': 'Valve',
    'GB Elektrotableau': 'Electrical panel',
    'GB Sprinklerzentrale': 'Sprinkler control room',
    'GB Brandmeldezentrale': 'Fire alarm control panel',
    'GB BMA Melder': 'Fire detector',
    'GB BMA-Z': 'Fire alarm placard (BMA-Z)',
    'GB RWA-BS': 'Smoke vent placard (RWA-BS)',
    'FW AED': 'AED / Defibrillator',
    'GB Fernsignaltableau': 'Remote signal panel',
    'GB Schluesseldepot': 'Key depot',
    'GB BA Wand F30': 'Wall F30',
    'GB BA Wand F60': 'Wall F60',
    'GB BA Wand F180': 'Wall F180',
    'GB Ture BS R30': 'Door R30',
    'GB Ture Durchgang': 'Passage',
    'GB Treppe 8': 'Stairs',
    'SI Nordpfeil': 'North arrow',
    'FKS Schluesselstelle': 'Key point',
    'FKS Beobachtungsposten': 'Observation post',
    'FKS Helikopter': 'Helicopter',
    'FKS Drohnenlandeplatz': 'Drone landing site',
    'FKS Forst': 'Forestry',
    'ZS Fahrzeugplatz': 'Vehicle park',
    'ZS Angehoerigensammelstelle': 'Relatives assembly point',
    'ZS Verpflegungsabgabestelle': 'Catering',
    'ZS Betriebsstoffabgabestelle': 'Fuel point',
    'ZS Dekontaminationsstelle': 'Decontamination point',
    'SI Windrichtung': 'Wind direction',
    'VKF Bereich Polizei': 'Police',
    'VKF Bereich Chemiewehr': 'Chemical response',
    'VKF Bereich Zivilschutz': 'Civil protection',
    'VKF Bereich Feuerwehr': 'Fire service',

    'VKF Rauch': 'Smoke',
    'FW Boot': 'Boat',
    'FW Tauchpumpe': 'Submersible pump',
    'FW Wassersauger': 'Wet vacuum',
  },
  // Symbol-palette category headings, keyed by the German category key.
  symbolCategories: {
    'Schadenlage': 'Damage situation',
    'Gefahren': 'Hazards',
    'Gebäude': 'Building',
    'Wasser': 'Water',
    'Führung': 'Command',
    'Personen / Sanität': 'People / Medical',
    'Partner': 'Partners',
  },
  symbolAliases: {
    'VKF Feuer': ['fire', 'blaze', 'flames', 'seat of fire', 'Brand', 'Brandherd', 'Flammen'],
    'VKF Rettungen': ['rescue', 'casualty rescue', 'evacuation', 'Personenrettung', 'Menschenrettung', 'Evakuierung'],
    'VKF Unfall': ['accident', 'road accident', 'collision', 'RTC', 'Verkehrsunfall', 'Kollision'],
    'VKF Gefaehrliche Stoffe': ['hazmat', 'dangerous goods', 'chemical', 'oil', 'spill', 'CBRN', 'Gefahrgut', 'ABC', 'Chemie', 'Öl', 'Oel', 'Austritt', 'Hazmat'],
    'VKF Wasser': ['water damage', 'flood', 'leak', 'Wasserschaden', 'Hochwasser', 'Leck'],
    'FW Gefahr Ex': ['explosion risk', 'detonation', 'Explosionsgefahr', 'Detonation'],
    'FW Beschaedigung': ['damage', 'damaged', 'Schaden', 'beschädigt'],
    'FW Teilzerstoerung': ['partial collapse', 'rubble', 'destruction', 'Zerstörung', 'Trümmer'],
    'FW Totalzerstoerung': ['collapse', 'total destruction', 'rubble', 'Zerstörung', 'Einsturz', 'Trümmer'],
    'FW Ueberschwemmung': ['flood', 'flooding', 'water damage', 'Hochwasser', 'Flut', 'Wasserschaden'],
    'FW Gefahr Tafel': ['UN number', 'ADR', 'hazard plate', 'Kemler', 'orange plate', 'hazmat', 'UN', 'UN-Nummer', 'ADR', 'Gefahrgut', 'Kemler', 'orange Tafel', 'Warntafel', 'Hazmat'],
    'FW Gefahr allgemein': ['caution', 'warning', 'hazard', 'Achtung', 'Warnung', 'Gefahrenstelle'],
    'FW Gefahr G': ['gas', 'gas main', 'natural gas', 'propane', 'Gasleitung', 'Erdgas', 'Propan', 'Explosionsgefahr'],
    'FW Gefahr C': ['chemicals', 'acid', 'alkali', 'hazardous substance', 'Chemikalien', 'Säure', 'Lauge', 'Gefahrstoff'],
    'FW Gefahr Radioaktiv': ['radiation', 'radioactive', 'nuclear', 'Strahlung', 'atomar', 'nuklear', 'A-Gefahr'],
    'FW Gefahr W': ['water hazard', 'watercourse', 'water protection', 'Wassergefahr', 'Gewässer', 'Gewässerschutz'],
    'FW Elektroanlage': ['electricity', 'power', 'voltage', 'high voltage', 'Strom', 'Spannung', 'Hochspannung', 'Elektrizität'],
    'VKF KP Front': ['command post', 'incident command', 'CP', 'Kommandoposten', 'Einsatzleitung', 'Führungsstandort'],
    'VKF Einsatzleiter': ['incident commander', 'IC', 'Einsatzleitung', 'EL'],
    'FW Offizier': ['officer', 'command', 'Kader', 'Führung'],
    'FW Sammelplatz': ['assembly point', 'muster point', 'rendezvous', 'Treffpunkt', 'Besammlung'],
    'FW Warteraum': ['staging area', 'holding area', 'Bereitstellungsraum', 'Bereitstellung'],
    'VKF Kontrollposten': ['checkpoint', 'control point', 'gate', 'Checkpoint', 'Kontrolle', 'Verkehrsposten', 'Pforte'],
    'VKF Informationszentrum': ['information', 'media', 'press', 'Info', 'Medien', 'Auskunft', 'Mediensammelstelle'],
    'VKF Bereich Materialdepot': ['equipment', 'depot', 'store', 'materials', 'Material', 'Depot', 'Lager'],
    'FW Absperrung': ['cordon', 'barrier', 'tape', 'exclusion zone', 'Sperre', 'Barriere', 'Absperrband', 'Sperrzone'],
    'VKF Verkehrssperre ueberwacht': ['road closure', 'roadblock', 'manned', 'guarded', 'Strassensperre', 'Absperrung', 'Sperre', 'bewacht', 'Bewachung', 'Überwachung'],
    'VKF Fahrzeug': ['vehicle', 'appliance', 'engine', 'truck', 'pump', 'Auto', 'TLF', 'Tanklöschfahrzeug', 'Einsatzfahrzeug', 'Lastwagen'],
    'VKF Drehleiter': ['turntable ladder', 'aerial ladder', 'TL', 'ADL', 'Autodrehleiter', 'Leiterfahrzeug'],
    'VKF Luefter mobil': ['fan', 'ventilator', 'PPV', 'ventilation', 'Ventilator', 'Belüftung', 'Druckbelüfter'],
    'FW Kleinloeschgeraet': ['extinguisher', 'fire extinguisher', 'fire blanket', 'Feuerlöscher', 'Handfeuerlöscher', 'Löschdecke'],
    'VKF Hubretter': ['aerial platform', 'hydraulic platform', 'telescopic mast', 'Hebebühne', 'Teleskopmast'],
    'VKF Pumpe Typ2': ['motor pump', 'portable pump', 'water relay', 'Motorspritze', 'Wassertransport', 'MS'],
    'FW Tauchpumpe': ['submersible pump', 'pump', 'cellar', 'water', 'Pumpe', 'Keller', 'Wasser', 'TP', 'Lenzpumpe'],
    'FW Wassersauger': ['wet vacuum', 'water vacuum', 'suction', 'Sauger', 'Nasssauger', 'Wasser', 'WS'],
    'VKF Helilandeplatz': ['helicopter', 'helipad', 'landing site', 'Rega', 'Helikopter', 'Heli', 'Rega', 'Landeplatz'],
    'VKF Drohne': ['drone', 'UAV', 'multicopter', 'aerial recon', 'thermal', 'Drone', 'UAV', 'Multicopter', 'Quadrocopter', 'Luftaufklärung', 'Wärmebild'],
    'FW Entrauchung': ['smoke extraction', 'smoke venting', 'exhaust', 'Rauchabzug', 'Belüftung', 'Abluft'],
    'FW Sprungretter': ['jump cushion', 'rescue cushion', 'air bag', 'Sprungkissen', 'Sprungpolster', 'Rettungskissen'],
    'FW Leiter': ['ladder', 'extension ladder', 'sectional ladder', 'Anstellleiter', 'Schiebleiter', 'Steckleiter'],
    'VKF Sammelstelle': ['assembly point', 'uninjured', 'evacuees', 'care', 'Unverletztensammelstelle', 'Betreuung', 'Evakuierte'],
    'VKF Patientensammelstelle': ['casualty collection point', 'triage', 'patients', 'CCP', 'Verletzte', 'Triage', 'Patienten'],
    'VKF Sanitaetshilfsstelle': ['medical post', 'aid post', 'treatment area', 'Verbandplatz', 'Sanposten', 'Sanhist'],
    'VKF Totensammelstelle': ['mortuary', 'deceased', 'fatalities', 'Tote', 'Verstorbene'],
    'FW Verwundetennest': ['casualty nest', 'injured', 'wounded', 'Verletzte', 'Verwundete'],
    'VKF Bereich Sanitaet': ['ambulance', 'EMS', 'medical', '144', 'Ambulanz', 'Rettungsdienst', '144'],
    'VKF Bereich Feuerwehr': ['fire service', 'fire brigade', '118', '118'],
    'VKF Bereich Polizei': ['police', '117', '117', 'Kantonspolizei'],
    'VKF Bereich Chemiewehr': ['hazmat team', 'chemical response', 'ABC-Wehr', 'Chemikalien'],
    'VKF Bereich Zivilschutz': ['civil protection', 'civil defence', 'ZS', 'Bevölkerungsschutz'],
    'SI Ueberflurhydrant': ['hydrant', 'pillar hydrant', 'water supply', 'Wasserbezug'],
    'SI Unterflurhydrant': ['hydrant', 'underground hydrant', 'water supply', 'Wasserbezug'],
    'VKF Innenhydrant': ['indoor hydrant', 'wall hydrant', 'riser', 'standpipe', 'Steigleitung', 'Wandhydrant'],
    'SI Wasserloeschposten': ['hose reel', 'internal attack', 'fire point', 'Innenangriff'],
    'WV Loeschweier': ['fire pond', 'pond', 'reservoir', 'water reserve', 'Weiher', 'Teich', 'Reservoir', 'Löschwasserreserve'],
    'SI Wasserbezugsort': ['water source', 'draft point', 'river', 'lake', 'Saugstelle', 'Fluss', 'Bach', 'See'],
    'SI Wasserdruckversorgung': ['pressurised supply', 'pressure main', 'reservoir', 'Druckleitung', 'Reservoir'],
    'GB BA Wand F30': ['fire compartment', 'fire wall', 'compartment wall', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F60': ['fire compartment', 'fire wall', 'compartment wall', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F180': ['fire compartment', 'fire wall', 'compartment wall', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB Ture BS R30': ['fire door', 'door', 'Brandschutztüre', 'Brandschutztür', 'Tür'],
    'GB Ture Durchgang': ['door', 'entrance', 'access', 'Tür', 'Eingang', 'Zugang'],
    'GB Lift': ['lift', 'elevator', 'goods lift', 'Aufzug', 'Fahrstuhl', 'Warenlift'],
    'GB Kamin': ['chimney', 'flue', 'stack', 'Cheminée', 'Schornstein', 'Abgas'],
    'GB Abzug': ['extract', 'ventilation', 'exhaust duct', 'Lüftung', 'Ventilation', 'Abluft'],
    'SI Schieber': ['valve', 'shut-off valve', 'gas valve', 'stopcock', 'Absperrschieber', 'Ventil', 'Gasschieber'],
    'GB Elektrotableau': ['distribution board', 'fuse box', 'main switch', 'power', 'Sicherungskasten', 'Verteiler', 'Strom', 'Hauptschalter'],
    'GB Sprinklerzentrale': ['sprinkler', 'sprinkler control', 'suppression system', 'Sprinkler', 'Löschanlage'],
    'GB Brandmeldezentrale': ['fire alarm panel', 'FACP', 'detection panel', 'BMA', 'BMZ', 'Brandmeldeanlage', 'Alarmzentrale'],
    'GB BMA Melder': ['detector', 'smoke detector', 'call point', 'zone', 'Melder', 'Brandmelder', 'Rauchmelder', 'Meldergruppe', 'Handfeuermelder'],
    'GB BMA-Z': ['fire alarm placard', 'BMA', 'BMZ', 'sign', 'placard', 'Brandmeldezentrale', 'Brandmeldeanlage'],
    'GB RWA-BS': ['smoke vent control', 'RWA', 'smoke and heat vent', 'placard', 'Rauch- und Wärmeabzug', 'Bedienstelle'],
    'FW AED': ['defibrillator', 'defib', 'AED', 'CPR', 'cardiac arrest'],
    'GB Fernsignaltableau': ['remote indicator panel', 'repeater panel', 'Brandmeldeanlage', 'Signaltableau'],
    'GB Schluesseldepot': ['key box', 'key safe', 'fire service key box', 'Schlüsselrohr', 'Feuerwehrschlüsseldepot'],
    'GB Treppe 8': ['stairs', 'staircase', 'stairwell', 'Treppenhaus', 'Stiege', 'Aufgang'],
    'SI Windrichtung': ['wind', 'wind direction', 'windsock', 'weather', 'Wind', 'Windsack', 'Wetter'],
    'SI Nordpfeil': ['north', 'compass', 'orientation', 'Norden', 'Kompass', 'Orientierung'],
    'FKS Schluesselstelle': ['key point', 'choke point', 'Schlüsselstelle'],
    'FKS Beobachtungsposten': ['observation', 'lookout', 'Beobachtungsposten'],
    'FKS Helikopter': ['helicopter', 'heli', 'Helikopter'],
    'FKS Drohnenlandeplatz': ['drone', 'landing', 'Drohne', 'Landeplatz'],
    'FKS Forst': ['forestry', 'ranger', 'Forst', 'Waldbrand'],
    'ZS Fahrzeugplatz': ['vehicle park', 'staging', 'Fahrzeugplatz', 'Bereitstellungsraum'],
    'ZS Angehoerigensammelstelle': ['relatives', 'family', 'Angehörige'],
    'ZS Verpflegungsabgabestelle': ['catering', 'food', 'Verpflegung'],
    'ZS Betriebsstoffabgabestelle': ['fuel', 'refuelling', 'Tankstelle', 'Treibstoff'],
    'ZS Dekontaminationsstelle': ['decontamination', 'decon', 'Dekontamination'],
  },
}
