// English copy · the Plan whiteboard, notes and entities.
// One slice of the `en` overlay, assembled in ../en.ts; the German base is ../de/whiteboard.ts.

import type { Copy, Localizable } from '../index'

export const whiteboardCopy: Localizable<Pick<Copy, 'incidents' | 'entities' | 'notes' | 'whiteboard' | 'tafel'>> = {
  incidents: {
    migratedTitle: 'Migrated working state',
    geojsonNotJson: 'Not a valid JSON file.',
    geojsonNotFc: 'Not a GeoJSON FeatureCollection.',
    geojsonNotWgs84: 'Coordinates look like LV95, not WGS84 [lng, lat]. Reproject to EPSG:4326 first.',
  },
  entities: {
    noteSubtitle: 'Note',
    fallbackObjectName: 'Object',
  },
  notes: {
    deleteTitle: 'Remove note?',
    deleteMsg: 'This note contains text. Really remove it?',
    section: 'Note',
    content: 'Text',
    size: 'Size',
    sizeS: 'Small',
    sizeM: 'Normal',
    sizeL: 'Large',
    look: 'Appearance',
    lookPill: 'Sticky note',
    lookPlain: 'Plain text',
    color: 'Colour',
    done: 'Done',
  },
  whiteboard: {
    fit: 'Fit',
    pan: 'Select',
    team: 'Team',
    draw: 'Draw',
    text: 'Note',
    symbol: 'Symbol',
    line: 'Line',
    area: 'Area',
    dockHints: {
      draw: 'Drag on the plan to draw freely. Pick colour, width and style afterwards in the editor.',
      line: 'Tap corner points. Double-tap or "Done" closes the line. Pick colour, width and style afterwards in the editor.',
      lineFreeShort: 'Drag your finger across the plan',
      lineNodesShort: 'Tap points – ✓ finishes the line',
      areaFreeShort: 'Drag the outline with your finger',
      areaNodesShort: 'Tap at least 3 corners – ✓ finishes',
      area: 'Tap corner points (at least 3). Double-tap or "Done" closes the area.',
      circle: 'Drag from the centre outward to set the radius. Adjust radius, colour and fill afterwards in the editor – in real metres once the scale is calibrated.',
      text: 'Tap the plan to drop a note.',
      resource: 'Tap the plan to place a team. Drag to move it.',
      scale: 'Tap the two endpoints of the printed scale bar, then enter the real length. Lines with "Length" then show real metres.',
      measure: 'Tap points on the plan. "Distance" shows the length, "Area" the surface + perimeter – in real metres once the scale is calibrated. Drag points to move, press and hold one to remove it.',
    },
    scale: {
      tool: 'Scale',
      promptTitle: 'Set scale',
      promptBody: 'Real length of the captured distance (e.g. the scale bar):',
      unit: 'm',
      confirm: 'Apply',
      cancel: 'Cancel',
      chipCalibrated: 'ref. {m} m',
      chipAuto: 'ref. auto',
      chipAutoHint: 'ref. automatic – scale derived from the map link',
      chipAutoStackHint: 'ref. automatic – scale derived from the building footprint',
      chipUncalibrated: 'not calibrated',
      recalibrate: 'Recalibrate',
      calibrate: 'Calibrate scale',
      calibrateHint: 'Tap two points of the scale bar',
      stale: 'recheck the scale',
      saved: 'Scale calibrated ({m} m reference)',
      needsCalibration: 'Set scale: tap the two ends of the scale bar',
      needsCalibrationViewer: 'Measuring needs a calibrated scale first',

      persistTitle: 'Remember the scale?',
      saveAll: 'For all plans',
      saveThis: 'This plan only',
      savedAll: 'Saved as the default scale',
      savedThis: 'Scale saved for this plan',
      saveFailed: 'Saving the scale failed',
    },
    georef: {
      chipUnlinked: 'Link to map',
      chipLinked: 'linked',
      chipTwoPoints: 'from 2 points',
      chipResidual: '⌀ {m} m',
      linkTitle: 'Link this plan to the map',
      openQuality: 'Review and correct the reference',
      freeOrderTap: 'Tap the same spot on module and map',
      freeOrderTip: 'Unmistakable points work best – building corner, hydrant, path junction. The order is free: placed halves find their counterpart by themselves.',
      freeOrderPlace: 'Acts on the visible surface – map or module, any order',
      moveMap: 'Move point {n} – tap the new spot on the map, the old one disappears.',
      movePlan: 'Move point {n} – tap the new spot on the module, the old one disappears.',
      title: 'Link to map',
      barOpen: '{n} open',
      sideProgress: 'Map {map} · Module {plan}',
      statusOpenMap: 'Point {n} is still missing on the map.',
      statusOpenPlan: 'Point {n} is still missing on the module.',
      statusOpenMapMany: '{k} points are still missing on the map.',
      statusOpenPlanMany: '{k} points are still missing on the module.',
      statusOpenBoth: 'Open points on map and module – matching spots pair up automatically.',
      statusSelected: 'Point {n} selected – tap elsewhere to deselect.',
      cancel: 'Cancel',
      closeMode: 'Close',
      done: 'Done',
      placePoint: 'Set point',
      targetOutside: 'Move the crosshair onto the visible surface first',
      checkFit: 'Check the fit',
      checkOpacity: 'Module overlay visibility',
      checkMap: 'Map',
      checkPlan: 'Module',
      autoStart: 'Align automatically',
      autoStartSub: 'Review the suggestion on the map, then accept',
      autoManual: 'Set points yourself',
      autoManualSub: 'Tap the same spot on the module and the map – any order',
      autoBusy: 'Automatic alignment running…',
      autoStepRender: 'Rendering the plan',
      autoStepOsm: 'Loading building data',
      autoStepMatch: 'Matching buildings',
      autoNone: 'No confident suggestion found – set points yourself',
      autoNoScale: 'The plan’s scale was not recognised – calibrate first or set points yourself',
      autoFailed: 'Automatic alignment failed',
      autoUnavailable: 'Automatic alignment is not set up on this server',
      proposalHead: 'Aligned automatically',
      proposalSub: 'Compare the building edges, then accept',
      proposalCheckHead: 'Check the overlay',
      proposalCheckSub: 'The buildings only partly agree – compare closely, adjust if needed',
      proposalAdjustHead: 'Adjust the plan',
      proposalAdjustSub: 'Move or turn until the building edges match.',
      adjust: 'Adjust',
      accept: 'Accept',
      discard: 'Discard',
      restore: 'Restore suggestion',
      planSize: 'Plan size',
      sizeSmaller: 'Shrink the plan by 1 percent',
      sizeBigger: 'Grow the plan by 1 percent',
      undoNudge: 'Undo the last adjustment',
      rotateGrip: 'Turn',
      hintMove: 'Dragging moves the plan',
      hintRotate: 'Dragging turns the plan around its centre',
      acceptedToast: 'Alignment accepted',
      crossTitle: 'Point {n} – drag to move, tap for options',
      pendingCrossTitle: 'Point {n} open – drag to move, tap for options',
      pointN: 'Point {n}',
      popMove: 'Move',
      popKeep: 'Keep',
      popResidual: 'off by {m} m',
      popOpen: 'open',
      popPairHint: 'To match, tap the open point on the other surface',
      detailsTitle: 'Fit details',
      saveFailed: 'Saving the link failed',
      qualityTitle: 'Fit',
      pairs: 'Pairs',
      qualityDeviation: 'Deviation ⌀ {m} m',
      warnTwoPoints: 'Two pairs solve exactly – only a third point shows how good the fit really is.',
      warnCollinear: 'Set the next point off the line – the current ones sit almost on one line, and across it the position is undetermined.',
      warnBaseline: 'Set the next point further away – the points are only {m} m apart, larger spacing makes the fit more stable.',
      lampNoneHead: 'No link yet',
      lampNoneBody: 'Two points put the plan on the map.',
      lampOneHead: '1 point set',
      lampOneBody: 'The second one puts the plan on the map.',
      lampTwoHead: '2 points – exact, but unchecked',
      lampGoodHead: '{n} points · ⌀ {m} m',
      lampGoodBody: 'Accurate enough to mirror symbols between plan and map.',
      addThird: 'Set a third point',
      lampAutoHead: 'Aligned automatically',
      lampApprovedHead: 'Approved by the station',
      lampApprovedBody: 'The station checked the overlay and published this fit.',
      chipAuto: 'unmeasured',
      warnAuto: 'Set reference points to measure the fit – so far only the visual overlay check stands.',
      autoAddPoints: 'Set reference points',
      autoOneHead: 'Aligned automatically · 1 point',
      autoOneBody: 'A second point replaces the automatic alignment with real references.',
      autoOnePoint: '1 point',
      openDroppedOne: 'Open point discarded – a reference point needs both surfaces',
      openDroppedMany: '{k} open points discarded – a reference point needs both surfaces',
      addMore: 'Add points',
      transfer: 'Transfer',
      transferTitle: 'Copy the fit',
      transferBody: 'The reference points from {source} are copied. Each module can then be adjusted separately.',
      transferLinked: 'already linked',
      transferCompleted: 'copied',
      transferReplaceTitle: 'Replace the fit for {target}?',
      transferReplaceBody: 'The existing reference points for {target} are replaced by the fit from {source}.',
      transferDone: 'Fit copied to {target} – check the overlap there',
      reset: 'Reset',
      resetTitle: 'Reset the reference?',
      resetBody: 'The link between this plan and the map is deleted. The points have to be set again afterwards.',
      resetDone: 'Reference reset',
      clearPoints: 'Reset',
      clearTitle: 'Reset all points?',
      clearBody: 'The points set so far are deleted, and with them the link between this plan and the map. Setting them starts over.',
      removePoint: 'Delete point',
      layerGroupPlans: 'Plans',
      layerPlanImage: 'Plan ({plan})',
      twinFromMap: '{name} – mirrored from the map. Tap for its details, drag to move the original.',
      twinUnnamed: 'Symbol',
    },
    finishShape: 'Done',
    cancelShape: 'Cancel',
    insertVertex: 'Insert point',
    dragVertex: 'Drag corner · press and hold to delete',
    dragRadius: 'Drag radius',
    groupDeleteTitle: 'Remove selection',
    groupDeleted: 'Selection removed',
    placeText: 'Note placed on plan',
    placeSymbol: 'Symbol "{name}" placed on plan',
    placeLine: 'Line drawn on plan',
    placeArea: 'Area drawn on plan',
    placeCircle: 'Cordon drawn on plan',
    placeTeam: '{name} placed on plan',
    selectTrupp: 'Which team?',
    newTeam: 'New team',
    truppPlacedHere: 'already here',
    showTrupp: 'Show in Teams',
    markPosition: 'Mark position',
    positionMarked: '{name}: position marked',
    removeMarker: 'Remove marker',
    removeMarkerTrail: 'Remove marker and trail',
    clearTrail: 'Remove trail',
    clearTrailConfirm: 'Remove all {n} marked positions of {name}? The trail disappears from map and plan.',
    trailCleared: '{name}: trail removed',
    trails: 'Trails',
    trailsOn: 'Show trails',
    trailsOff: 'Hide trails',
    ghostTrail: 'Trail {name}',
    ghostTrailHint: 'Trail of {name} – the team marker was removed',
    ghostTrailTitle: 'Trail of {name}',
    ghostTrailAsk: 'The team marker was removed and its trail stayed. Place the team back at the end of the trail – or remove the trail?',
    ghostTrailRestore: 'Place team again',
    ghostTrailRestored: '{name} placed again – trail carried over',
    teamNameTaken: '{name} is already taken – the name stays',
    textPlaceholder: 'Note ...',
    blankHint: 'Blank sheet – annotate with line, area, note, symbol or team',
    osmLoading: 'Loading building outlines …',
    osmError: 'Building outlines (OSM) unreachable',
    osmEmpty: 'No buildings in this area',
    osmRetry: 'Try again',
    osmPickHint: 'Tap a building, then apply',
    osmPickHintReplace: 'Tap a building, then apply – this replaces the existing building',
    osmPickHintAmend: 'The existing building is highlighted – tap more to add them, then apply',
    osmPickHintHere: 'The building at the incident location is marked – check it, then apply.',
    osmPickMissing: 'Outlines of the existing building are missing here ({n}) – they are lost when you apply.',
    osmTransfer: 'Apply ({n})',
    osmClear: 'Clear selection',
    addFloorUp: 'Add upper floor',
    noFloorPlan: 'No floor plan',
    stairTo: 'On to {floor}',
    stairFrom: 'From {floor}',
    climbUp: 'Continue one floor up',
    climbDown: 'Continue one floor down',
    climbBack: 'Back to {floor}',
    addFloorDown: 'Add lower floor',
    floorAddedToast: '{floor} added',
    floorHide: 'Hide floor',
    floorHideShort: 'Hide',
    floorMenu: '{name}: hide or remove',
    floorShow: 'show',
    floorHidden: 'hidden',
    removeFloor: 'Remove floor',
    removeFloorConfirm: '{floor}: {n} markings on this floor will be removed or shortened. Remove the floor anyway?',
    removeFloorConfirmOne: '{floor}: 1 marking on this floor will be removed or shortened. Remove the floor anyway?',
    floorRemoved: 'Floor removed',
    floorRemovedLog: 'Floor {floor} removed',
    floorRemovedLogMarks: 'Floor {floor} removed – {n} markings removed or shortened',
    floorRestoredLog: 'Floor {floor} restored',
    floorAddedLog: 'Floor {floor} added',
    floorAdded: 'Floor added',
    buildingReplaced: 'Building replaced',
    buildingReplacedMarks: 'Building replaced – {n} markings removed',
    buildingReplacedKept: 'Building changed – storeys kept',
    buildingReplacedCarried: 'Building changed – {n} markings carried over',
    buildingReplacedCarriedDropped: 'Building changed – {n} carried over, {d} dropped',
    buildingTaken: 'Building adopted',
    replaceBuilding: 'Choose another building',
    replaceBuildingConfirm: 'The existing floor stack is discarded and replaced by the new outline.',
    replaceBuildingConfirmMarks: 'The floors carry {n} markings. They are anchored to the current outline and cannot be carried over to another one – they will be removed. «Undo» in the notice brings them back.',
    replaceBuildingConfirmKeep: 'The new outline takes the place of the current one. The storeys are kept.',
    replaceBuildingConfirmCarry: 'The new outline takes the place of the current one. The storeys are kept, and {n} markings come along – they keep their place on the ground.',
    replaceBuildingConfirmCarryDrop: '{n} markings are carried over to the new outline and keep their place on the ground. {d} no longer lie on it and are dropped. «Undo» in the notice brings everything back.',
    backToBuilding: 'Back to the building',
    railBuilding: 'Building',
    otherObject: 'Other object',
    objectLabel: 'Object',
    objectNone: 'No object',
    objectIs: 'Object: {name}',
    objectSwitch: 'Object: {name} – choose another object',
    objectSwitchShort: 'Choose another object',
    objectNearby: '{name} · {distance} away',
    objectNearbyLabel: 'Nearest object, {distance} away – not the incident address',
    nearbyBannerTitle: 'Nearest object, not the incident address.',
    nearbyBannerBody: 'Incident: {incident} · plan: {object} ({distance}).',
    nearbyBannerNoAddress: 'no address',
    objectActive: 'Plans of "{name}"',
    objectReset: 'Reset to the next object',
    objectSwitchConfirmTitle: 'Load another object',
    objectSwitchConfirm: 'The plans of every module switch to "{name}". Change the current object?',
    objectSwitchConfirmCta: 'Load object',
    northLabel: 'N',
    northTitle: 'North direction – building rotated to its long axis',
    orientAsDrawn: 'As drawn',
    northUnknownTitle: 'North unknown – plan not linked to the map',
    orientNorthUp: 'North up',
    orientLongAxis: 'Rotate to long axis',
    orientMenuTitle: 'Rotate building',
    orientSliderLabel: 'Rotation',

    groupDeletedN: '{n} objects removed from the plan',
  },
  tafel: {
    strip: 'Board pages',
    skizze: 'Sketch',
    addPage: 'Page',
    addPageTitle: 'Add a page',
    alreadyThere: 'already here',
    pageAdded: 'Page «{page}» added',
    pageEdited: '{page} changed',
    pageRemoved: 'Page «{page}» removed',
    removePage: 'Remove page',
    removeTitle: 'Remove page?',
    removeMsg: 'Everything written on «{page}» goes with it. Undo (↶) brings it back.',
    template: 'Template {title}, version {v}',
    mapLabel: 'Situation map – tap to open the map',
    mapOpen: 'Open map',
    mapPrint: 'In the report: the map at the moment of printing',
    head: { title: 'Incident', address: 'Address', alarm: 'Alarm', el: 'Incident commander' },
    tag: 'Keyword',
    done: 'Done',
    trendNone: 'Trend open',
    trendUp: 'getting worse',
    trendSame: 'unchanged',
    trendDown: 'easing',
    trendTitle: 'Trend: {trend} – tap to change',
    keysHint: 'Enter: next row · Tab: next column · Shift+Enter: line break',
  },
}
