// German copy · the Lagemeldung and the Führungsrhythmus.
// One slice of the canonical `de` catalogue, assembled in ../de.ts — read the rules at the
// top of that file before adding or renaming a key here.

export const lagemeldungCopy = {
  // Lagemeldung auf Knopfdruck (F3): the composer sheet, its radio view, the TopBar chip, the due
  // row — and the sentence parts the deterministic engine (lib/lagemeldung) assembles. Every line
  // template ends with its own full stop; the engine joins them per slot.
  lagemeldung: {
    title: 'Lagemeldung',
    chip: 'Lage',
    chipIn: 'Lage · in {m}′',
    chipDue: 'Lage fällig',
    chipOff: 'Lage · aus',
    chipHint: 'Lagemeldung zusammenstellen',
    chipAria: 'Lagemeldung – {state}',
    modeSeit: 'Seit {t}',
    modeVoll: 'Vollständig',
    modeFirst: 'Erstmeldung',
    modeLabel: 'Umfang',
    firstNote: 'Noch keine Lagemeldung · alles neu',
    seitNote: 'Nur was sich seit {t} geändert hat · Lebenswichtiges immer',
    vollNote: 'Alles, was gilt – für Übergabe, Nachbarwehr, Rück',
    slots: {
      zuerst: 'Zuerst', lage: 'Lage', menschen: 'Menschen', gefahren: 'Gefahren', massnahmen: 'Massnahmen',
      mittel: 'Mittel', bedarf: 'Bedarf', naechste: 'Nächste', zusatz: 'Zusatz',
    } as Record<string, string>,
    tags: {
      neu: 'Neu', schlechter: 'Schlechter', besser: 'Besser', erledigt: 'Erledigt', gleich: 'weiterhin',
    } as Record<string, string>,
    tagSchaetzung: 'Schätzung',
    tagSchaetzungTitle: 'Planungshilfe – aus dem Druckverlauf geschätzt, kein Messwert',
    tagRegister: 'Register',
    tagRegisterTitle: 'Register-Hinweis (GWR, BFE) – kann veraltet sein, vor Ort prüfen',
    tick: 'In die Meldung',
    untick: 'Aus der Meldung nehmen',
    dropT0: 'Lebenswichtig – trotzdem weglassen?',
    dropT0Yes: 'Weglassen',
    editLine: 'Zeile bearbeiten',
    editDone: 'Fertig',
    addLine: 'Eigene Zeile',
    addLinePlaceholder: 'Was noch gesagt werden muss',
    hidden: 'Ausgeblendet ({n})',
    hiddenNone: 'Nichts ausgeblendet',
    hiddenReasons: {
      gleich: 'unverändert seit {t}',
      declined: 'weggelassen {t}',
      budget: 'über Funklänge',
      routine: 'Routine',
      offer: 'Hintergrund',
      superseded: 'ersetzt durch «{by}»',
      dispatch: 'kennt die ELZ',
      inLine: 'in «{slot}» enthalten',
    } as Record<string, string>,
    hiddenAdd: 'Hinzufügen',
    hiddenAddAria: '«{text}» in die Meldung nehmen',
    words: '{n} Wörter',
    seconds: '≈ {s} s',
    overBudget: 'Länger als ein Funkspruch ({n} Wörter)',
    radio: 'Funkansicht',
    radioClose: 'Zurück zum Entwurf',
    share: 'Teilen',
    shareCopied: 'Lagemeldung kopiert',
    shareFailed: 'Teilen nicht möglich',
    more: 'Weitere Aktionen',
    send: 'Gemeldet',
    sendHint: 'Schreibt die Meldung in den Verlauf und plant die nächste',
    close: 'Schliessen ohne Speichern',
    source: 'Entwurf aus Trupps, Karte, Verlauf, Fahrzeugzeiten · nichts gespeichert bis «Gemeldet»',
    empty: 'Nichts Neues seit {t}.',
    emptyFirst: 'Noch nichts im Record – Lage, Menschen, Mittel von Hand ergänzen.',
    // the record
    row: 'Lagemeldung {t}: {text}',
    rowVoll: 'Lagemeldung {t} (vollständig): {text}',
    sentToast: 'Lagemeldung {t} im Verlauf',
    undoneLog: 'Lagemeldung {t} zurückgenommen',
    // «Nächste Meldung» (K5) and the Führungsrhythmus
    next: 'Nächste Meldung ca. {t}.',
    nextHandover: 'Nächste Meldung bei Übergabe.',
    nextNone: 'Keine weitere Lagemeldung geplant.',
    rhythm: 'Rhythmus',
    rhythmEvery: '{m}′',
    rhythmHandover: 'Übergabe',
    rhythmOff: 'Aus',
    rhythmOffAction: 'Rhythmus ausschalten',
    rhythmOffLog: 'Lagemeldung-Rhythmus aus',
    rhythmOnLog: 'Lagemeldung-Rhythmus {m}′ · nächste {t}',
    rhythmWindDown: 'Feuer aus – Rhythmus strecken?',
    nextLog: 'Nächste Lagemeldung um {t}',
    reminderText: 'Lagemeldung',
    // the due row in the Meldeleiste (an ordinary Wiedervorlage with purpose «lagemeldung»)
    dueTitle: 'Lagemeldung fällig',
    dueLast: 'letzte {t}',
    dueNone: 'noch keine Lagemeldung',
    dueChanges: '{n} Änderungen',
    dueChangesOne: '1 Änderung',
    dueUrgent: '{n} dringend',
    dueOpen: 'Lagemeldung',
    dueSnooze: '+10′',
    // the quick phrase «Lagemeldung an Einsatzzentrale» in the composer
    phraseOffer: 'Lagemeldung zusammenstellen',
    // line templates (the engine)
    truppNo: 'Trupp {n}',
    truppBare: 'Trupp',
    truppPressure: '{trupp} Alarmdruck {bar} bar, Rückzug{where}.',
    truppContact: '{trupp} überfällig, kein Funkkontakt seit {m}′{where}.',
    truppEnded: '{trupp}: Alarm aufgehoben.',
    where: ', {w}',
    vermisstOne: '1 Person vermisst{where}.',
    vermisstMany: '{n} Personen vermisst{where}.',
    eingesperrtOne: '1 Person eingeschlossen{where}.',
    eingesperrtMany: '{n} Personen eingeschlossen{where}.',
    keineVermissten: 'Keine weiteren Vermissten.',
    gerettetOne: '1 Person gerettet{extra}.',
    gerettetMany: '{n} Personen gerettet{extra}.',
    anSanitaet: ', an Sanität übergeben',
    geraeumt: 'Gebäude geräumt.',
    keinePersonen: 'Keine Personen im Gebäude.',
    un: 'Gefahrstoff UN {un}{stoff}{dist}.',
    unDist: ', Absperrung {m} m',
    unDone: 'Gefahrstoff UN {un}: erledigt.',
    hazard: '{label}{where}.',
    hazardDone: '{label}: erledigt.',
    gas: 'Gasheizung im Gebäude.',
    oil: 'Ölheizung im Gebäude.',
    pv: 'PV-Anlage auf dem Dach.',
    gasAb: 'Gas abgestellt.',
    stromAb: 'Strom abgeschaltet.',
    geschosse: '{n} Geschosse.',
    wind: 'Wind gedreht auf {dir}.',
    unterKontrolle: 'Brand unter Kontrolle {t}.',
    feuerAus: 'Feuer aus {t}{extra}.',
    nachloesch: ', Nachlöscharbeiten laufen',
    lageTitle: '{title}.',
    lageDamage: '{list}.',
    feuerGeloescht: 'Feuer gelöscht {t}.',
    trupps: '{n} Trupps im Einsatz: {list}.',
    truppsOne: '1 Trupp im Einsatz: {list}.',
    truppsShort: '{n} Trupps im Einsatz.',
    truppsShortOne: '1 Trupp im Einsatz.',
    sitr: 'Sicherheitstrupp bereit.',
    asEnded: 'Atemschutz beendet, alle Trupps draussen.',
    bereit: 'Bereit: {list}.',
    mittelOn: '{list} vor Ort',
    mittelComing: '{list} anrückend',
    mittelNew: 'neu {list}',
    mittelLeft: '{list} eingerückt',
    mittelShort: '{n} Fahrzeuge neu',
    mittelShortOn: '{n} Fahrzeuge vor Ort',
    adf: '{n} AdF.',
    nachalarm: 'Nachalarm {title}.',
    abloesungJetzt: 'Atemschutz-Ablösung jetzt.',
    abloesungBald: 'Atemschutz-Ablösung in ca. {m}′.',
    verstaerkung: 'Verstärkung angefordert, noch nicht vor Ort.',
    bedarfNone: 'keiner mehr.',
    bedarfDone: '{text}: erledigt.',
    reminderSoon: '{text} ({t}).',
    // routine counts in «Ausgeblendet»
    routineSymbolsOne: '1 Symbol-Eintrag',
    routinePhotosOne: '1 Foto',
    routineTeamOne: '1 Atemschutz-Eintrag',
    routineSymbols: '{n} Symbol-Einträge',
    routinePhotos: '{n} Fotos',
    routineTeam: '{n} Atemschutz-Einträge',
    routineDispatch: 'Alarmtext',
    routineElTaken: '«Einsatzleitung übernommen»',
  },
} as const
