// German copy · Objektbesuche.
// One slice of the canonical `de` catalogue, assembled in ../de.ts — read the rules at the
// top of that file before adding or renaming a key here.

export const objectVisitsCopy = {

  // ── Admin / Verwaltung surface (the /admin back-office) ───────────────────────
  // ── Objektbesuche (docs/object-visits.md) — launcher entry, Übersicht, Liste, Besuch ──
  objectVisits: {
    launcher: 'Objektbesuche',
    title: 'Objektbesuche',
    back: 'Zurück',
    loading: 'Objektbesuche werden geladen …',
    notPreparedTitle: 'Noch nicht offline vorbereitet',
    notPreparedBody: 'Dieses Gerät hat die Objektliste und die Checklisten noch nie geladen. Öffne Objektbesuche einmal mit Verbindung, danach bleiben sie auf dem Gerät.',
    notPreparedDrafts: 'Entwürfe auf diesem Gerät bleiben auch ohne Objektliste verfügbar.',
    retry: 'Erneut versuchen',
    refusedTitle: 'Objektbesuche nicht verfügbar',
    refusedBody: 'Die Verwaltung hat Objektbesuche für diese Wehr nicht eingeschaltet, oder dieses Konto darf sie nicht öffnen.',
    storageUnreadable: 'Der Gerätespeicher konnte nicht gelesen werden – Besuche auf diesem Gerät fehlen vielleicht in dieser Liste.',
    myDrafts: 'Meine Entwürfe',
    unsent: 'Noch nicht gespeichert',
    lists: 'Listen',
    listObjectsOne: '1 Objekt',
    listObjectsMany: '{n} Objekte',
    listOn: "am {date}",
    listArchived: "Nicht mehr eingeplant",
    schedule: {"today": "Heute", "overdue": "Noch offen", "upcoming": "Nächste Termine", "undated": "Ohne Termin", "recent": "Kürzlich erledigt"},
    listUntil: 'bis {date}',
    searchHead: 'Objekt suchen',
    searchPlaceholder: 'Objekt suchen …',
    nearby: 'In der Nähe',
    nearbyUse: 'Standort verwenden',
    nearbyLocating: 'Standort wird bestimmt …',
    nearbyFailed: 'Standort nicht verfügbar',
    nearbyNone: 'Kein Objekt im Katalog hat Koordinaten.',
    distanceM: '{m} m',
    distanceKm: '{km} km',
    neverVisited: 'noch nie besucht',
    lastVisit: 'zuletzt {date}',
    intro: 'Wähle ein Objekt aus einer Liste, über die Suche oder «In der Nähe». Der Besuch wird zuerst auf diesem Gerät gespeichert und gesendet, sobald Netz da ist.',
    viewerNote: 'Mit diesem Konto kannst du Besuche lesen, aber nicht erfassen.',
    listSub: '{done} von {total} besucht',
    listUnresolved: '{n} Objekte dieser Liste sind auf diesem Gerät nicht bekannt.',
    listUnknown: 'Diese Liste ist auf diesem Gerät nicht bekannt.',
    listDoneElsewhere: 'erledigt',
    stateDraft: 'Entwurf',
    stateDone: '✓ {date}',
    statePhotos: 'Fotos ausstehend',
    stateUnsent: 'nicht gesendet',
    visitLoading: 'Besuch wird geladen …',
    visitMissing: 'Dieser Besuch ist nicht auf diesem Gerät und konnte nicht geladen werden.',
    objectUnknown: 'Das Objekt «{key}» ist im Katalog dieses Geräts nicht bekannt.',
    chooseChecklist: 'Welche Checkliste?',
    chooseChecklistLead: 'Für dieses Objekt gibt es mehrere Besuchs-Checklisten.',
    noChecklist: 'Ohne Checkliste',
    plans: 'Pläne',
    changeChecklist: 'Checkliste wechseln',
    changeChecklistLead: 'Antworten, die auch in der neuen Checkliste vorkommen, bleiben. Fotos bleiben immer.',
    checklistCurrent: 'aktuell',
    changeChecklistDropOne: '1 Antwort passt nicht zur neuen Checkliste und wird entfernt. Fotos bleiben.',
    changeChecklistDropMany: '{n} Antworten passen nicht zur neuen Checkliste und werden entfernt. Fotos bleiben.',
    changeChecklistConfirm: 'Wechseln',
    planLoading: 'Plan wird geladen …',
    suggestedHead: 'Im Einsatz',
    startFailed: 'Besuch konnte nicht angelegt werden',
    menu: 'Weitere Aktionen',
    saveFile: 'Als Datei sichern',
    discard: 'Entwurf verwerfen',
    discardTitle: 'Entwurf verwerfen?',
    discardMsg: 'Der Besuch wird als verworfen markiert und erscheint in keiner Liste mehr. Das lässt sich nicht rückgängig machen.',
    discardBtn: 'Verwerfen',
    details: 'Von & Datum',
    visitedAt: 'Besucht am',
    with: 'Von',
    withPlaceholder: 'Namen, z. B. Muster Max, Frei Nina',
    notChecked: 'nicht geprüft',
    photoMissing: 'Foto fehlt',
    answer: { ok: 'OK', defect: 'Mangel', na: 'n. a.', yes: 'Ja', no: 'Nein', photo: 'Foto' },
    defectNote: 'Was ist der Mangel?',
    defectNotePlaceholder: 'z. B. Deckel klemmt',
    photosAdded: '{n} Fotos hinzugefügt',
    photosOne: '1 Foto',
    photosMany: '{n} Fotos',
    takePhoto: 'Foto aufnehmen',
    addPhoto: 'Foto hinzufügen',
    valuePlaceholder: 'Wert',
    notes: 'Bemerkungen',
    notesPlaceholder: 'Was sonst auffiel …',
    photos: 'Fotos',
    proposals: 'Korrekturvorschläge',
    proposalAdd: 'Vorschlag hinzufügen',
    proposalRow: 'bisher: {current} · neu: {proposed}',
    proposalRowNew: 'neu: {proposed}',
    complete: 'Abschliessen',
    completeOpenOne: '1 Punkt nicht geprüft',
    completeOpenMany: '{n} Punkte nicht geprüft',
    completeOpenMsg: 'Trotzdem abschliessen? Nicht geprüfte Punkte stehen im Bericht als «nicht geprüft».',
    completeRequired: 'Darunter verlangt: {items}',
    completeAnyway: 'Trotzdem abschliessen',
    completed: 'Besuch abgeschlossen',
    correctionNote: 'Korrektur: Der Besuch bleibt abgeschlossen, die Änderung wird eine neue Revision.',
    correctionDone: 'Fertig',
    lifecycle: { draft: 'Entwurf', completed: 'Abgeschlossen', discarded: 'Verworfen' },
    sync: {
      unsaved: 'Nicht gespeichert',
      conflict: 'Konflikt',
      auth: 'Anmeldung nötig',
      error: 'Nicht gesendet',
      sending: 'Wird gesendet',
      local: 'Nur auf diesem Gerät',
      localAt: 'auf Gerät {time}',
      changes: 'Änderungen auf Gerät {time}',
      photos: 'Fotos {done}/{total}',
      saved: 'Gespeichert {time}',
      remote: 'Revision {n}',
      offline: 'offline',
    },
    delivery: { waiting: 'Ablage wartet', delivered: 'abgelegt', failed: 'Ablage: Fehler', paused: 'Ablage pausiert' },
    statusTitle: 'Stand dieses Besuchs',
    statusOpen: 'Stand anzeigen',
    statusLifecycle: 'Besuch',
    statusDevice: 'Gerät → Server',
    statusFiling: 'Ablage',
    statusSavedAt: 'Auf diesem Gerät gespeichert um {time}.',
    statusRevision: 'Revision {n} auf dem Server.',
    statusNeverSent: 'Noch nie an den Server gesendet.',
    statusPending: 'Neuere Änderungen sind nur auf diesem Gerät.',
    statusPhotos: '{done} von {total} Fotos auf dem Server.',
    statusNoFiling: 'Keine Ablage eingerichtet.',
    destinationSharePoint: 'SharePoint',
    statusFilingRow: '{destination}: {state}',
    conflictTitle: 'Zwei Fassungen: {what}',
    conflictBody: 'Auf einem anderen Gerät wurde derselbe Punkt geändert.',
    conflictMine: 'Meine',
    conflictTheirs: 'Andere',
    conflictBoth: 'Beide behalten',
    conflictRemoved: '(entfernt)',
    conflictWhat: {
      notes: 'Bemerkungen', visitedAt: 'Besuchsdatum', with: 'Von', checklist: 'Checkliste',
      workRef: 'Liste', object: 'Objekt', photo: 'Foto', proposal: 'Vorschlag',
    },
    unsavedTitle: 'Nicht auf dem Gerät gespeichert',
    unsavedBody: 'Der Browser hat das Speichern abgelehnt (Speicher voll?). Was nicht gespeichert ist, gibt es nur in diesem Fenster.',
    unsavedRetry: 'Erneut speichern',
    authTitle: 'Anmeldung abgelaufen',
    authBody: 'Der Besuch ist auf diesem Gerät sicher. Melde dich wieder an, um ihn zu senden.',
    authLogin: 'Anmelden',
    errorTitle: 'Der Server hat den Besuch nicht angenommen',
    errorAttachment: 'Ein Foto wurde nicht angenommen',
    errorForbidden: 'Dieses Konto darf keine Besuche erfassen.',
    errorDisabled: 'Objektbesuche sind ausgeschaltet.',
    photoTitle: 'Foto',
    photoCaption: 'Beschriftung',
    photoCaptionPlaceholder: 'z. B. Zugang Nord',
    photoBelongs: 'Gehört zu',
    photoGeneral: 'Allgemein',
    photoStored: 'Auf diesem Gerät gespeichert · wird gesendet, sobald Netz da ist',
    photoNotStored: 'Nicht auf dem Gerät gespeichert – nur in diesem Fenster',
    photoAnother: 'Noch eins',
    photoDone: 'Fertig',
    photoRemove: 'Foto entfernen',
    photoRemoved: 'Foto entfernt',
    photoPreparing: 'Foto wird vorbereitet …',
    photoFailed: 'Foto konnte nicht übernommen werden',
    photoPending: 'noch nicht gesendet',
    photoOpen: 'Foto öffnen: {caption}',
    proposalTitle: 'Korrektur vorschlagen',
    proposalField: 'Feld',
    proposalOther: 'Anderes',
    proposalOtherLabel: 'Welches Feld?',
    proposalCurrent: 'Bisher',
    proposalCurrentHint: 'wie in den Stammdaten',
    proposalNew: 'Neu',
    proposalReason: 'Begründung',
    proposalReasonPlaceholder: 'z. B. Hauswart hat gewechselt',
    proposalSave: 'Vorschlag speichern',
    proposalRemove: 'Vorschlag entfernen',
    proposalRemoved: 'Vorschlag entfernt',
    defectsOne: '1 Mangel',
    defectsMany: '{n} Mängel',
    countOk: '{n} OK',
    countOpen: '{n} nicht geprüft',
    proposalsOne: '1 Vorschlag',
    proposalsMany: '{n} Vorschläge',
    report: 'Bericht (PDF)',
    reportSub: 'Revision {n}',
    reportFailed: 'Bericht konnte nicht geladen werden',
    edit: 'Bearbeiten',
    editSub: 'Korrektur · bleibt abgeschlossen, neue Revision',
    history: 'Verlauf',
    historyFailed: 'Verlauf konnte nicht geladen werden',
    historyRow: 'r{n} · {time}',
    nextInList: 'Nächstes in der Liste',
    listDone: 'Alle Objekte dieser Liste sind besucht.',
    by: 'Von {name}',
    fileSaved: 'Datei gesichert',
    fileSavedMissing: 'Datei gesichert – {n} Fotos waren nicht auf diesem Gerät',
    fileFailed: 'Datei konnte nicht erstellt werden',
    sent: 'Gesendet',
    sendContended: 'Konflikt mit einem anderen Gerät – wird gleich erneut versucht',
    conflictTakeOther: 'Andere übernehmen',
    conflictKeep: 'Diese behalten',
    conflictOther: 'Andere Fassung',
    conflictCurrent: 'Im Besuch',
    storageWait: 'Der Gerätespeicher konnte nicht gelesen werden. Damit kein zweiter Entwurf entsteht, wird jetzt kein neuer Besuch angelegt.',
    sendOffline: 'Offline – wird gesendet, sobald der Server erreichbar ist',
  },
} as const
