// German copy · tactical symbol names, search aliases and categories.
// One slice of the canonical `de` catalogue, assembled in ../de.ts — read the rules at the
// top of that file before adding or renaming a key here.

export const symbolsCopy = {
  // Tactical-symbol DISPLAY labels, keyed by the RAW FireGIS name (same keys as
  // appConfig.symbols.displayNames). de = the current German short labels; en/fr/it translate
  // them. The stored/looked-up symbol identity is always the raw name — only the label localizes.
  // formatSymbolName falls back to appConfig.symbols.displayNames (per-deployment override) then
  // to the prefix-strip/umlaut-restore, so missing keys keep working.
  symbolNames: {
    'VKF Feuer': 'Feuer',
    'VKF Rettungen': 'Rettung',
    'VKF Unfall': 'Unfall',
    'VKF Gefaehrliche Stoffe': 'Gefahrstoffe',
    'VKF Wasser': 'Wasser',
    'FW Gefahr allgemein': 'Gefahr',
    'FW Gefahr Tafel': 'Gefahrentafel',
    'FW Gefahr Radioaktiv': 'Radioaktiv',
    'FW Gefahr Ex': 'Explosion',
    'FW Gefahr G': 'Gas',
    'FW Gefahr C': 'Chemie',
    'FW Gefahr W': 'Wasser',
    'FW Elektroanlage': 'Elektroanlage',
    'VKF Patientensammelstelle': 'Patientensammelstelle',
    'VKF Sanitaetshilfsstelle': 'Sanitätshilfsstelle',
    'VKF Totensammelstelle': 'Totensammelstelle',
    'VKF Sammelstelle': 'Unverletzte',
    'FW Sammelplatz': 'Sammelplatz',
    'FW Warteraum': 'Warteraum',
    'FW Verwundetennest': 'Verwundetennest',
    'VKF Bereich Sanitaet': 'Sanität',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Einsatzleiter',
    'FW Offizier': 'Offizier',
    'VKF Kontrollposten': 'Kontrollposten',
    'VKF Informationszentrum': 'Informationszentrum',
    'VKF Bereich Materialdepot': 'Materialdepot',
    'FW Absperrung': 'Absperrung',
    'VKF Verkehrssperre ueberwacht': 'Verkehrssperre',
    'VKF Drehleiter': 'Drehleiter',
    'VKF Hubretter': 'Hubretter',
    'VKF Fahrzeug': 'Fahrzeug',
    'VKF Pumpe Typ2': 'Pumpe',
    // ⚠️ These two had NO entry and fell through to formatSymbolName(), which strips the
    // pack prefix — «VKF Rauch» → «Rauch» happened to be right, and would have stopped being
    // right the moment either name changed. Every other placeable symbol is named here.
    'VKF Rauch': 'Rauch',
    'FW Boot': 'Boot',
    'FW Tauchpumpe': 'Tauchpumpe',
    'FW Wassersauger': 'Wassersauger',
    'VKF Helilandeplatz': 'Helilandeplatz',
    'VKF Luefter mobil': 'Lüfter',
    'FW Entrauchung': 'Entrauchung',
    'FW Kleinloeschgeraet': 'Kleinlöschgerät',
    'FW Sprungretter': 'Sprungretter',
    'FW Leiter': 'Leiter',
    'SI Ueberflurhydrant': 'Überflurhydrant',
    'SI Unterflurhydrant': 'Unterflurhydrant',
    'VKF Innenhydrant': 'Innenhydrant',
    'SI Wasserloeschposten': 'Wasserlöschposten',
    'WV Loeschweier': 'Löschweiher',
    'SI Wasserbezugsort': 'Wasserbezugsort',
    'SI Wasserdruckversorgung': 'Wasserdruckversorgung',
    'GB Lift': 'Lift',
    'GB Kamin': 'Kamin',
    'GB Abzug': 'Abzug',
    'SI Schieber': 'Schieber',
    'GB Elektrotableau': 'Elektrotableau',
    'GB Sprinklerzentrale': 'Sprinklerzentrale',
    'GB Brandmeldezentrale': 'Brandmeldezentrale',
    'GB BMA Melder': 'BMA Melder',
    'GB BMA-Z': 'BMA-Z',
    'GB RWA-BS': 'RWA-BS',
    'FW AED': 'AED',
    'GB Fernsignaltableau': 'Fernsignaltableau',
    'GB Schluesseldepot': 'Schlüsseldepot',
    'GB BA Wand F30': 'Wand F30',
    'GB BA Wand F60': 'Wand F60',
    'GB BA Wand F180': 'Wand F180',
    'GB Ture BS R30': 'Türe R30',
    'GB Ture Durchgang': 'Durchgang',
    'GB Treppe 8': 'Treppe',
    'SI Nordpfeil': 'Nordpfeil',
    'SI Windrichtung': 'Windrichtung',
    // ── FKS Vegetationsbrand-Handbuch S. 52 und Zivile Signaturen S. 7 (01.09.) ──
    // Namen explizit statt über den Prefix-Fallback: «ZS» ist kein bekanntes Präfix, und
    // «Verpflegungsabgabestelle» ist der amtliche Name, nicht der, den man auf einer Palette
    // lesen will.
    'FKS Schluesselstelle': 'Schlüsselstelle',
    'FKS Beobachtungsposten': 'Beobachtungsposten',
    'FKS Helikopter': 'Helikopter',
    'FKS Drohnenlandeplatz': 'Drohnenlandeplatz',
    'FKS Forst': 'Forst',
    'ZS Fahrzeugplatz': 'Fahrzeugplatz',
    'ZS Angehoerigensammelstelle': 'Angehörigensammelstelle',
    'ZS Verpflegungsabgabestelle': 'Verpflegung',
    'ZS Betriebsstoffabgabestelle': 'Tankstelle',
    'ZS Dekontaminationsstelle': 'Dekontaminationsstelle',
    'VKF Bereich Polizei': 'Polizei',
    'VKF Bereich Chemiewehr': 'Chemiewehr',
    'VKF Bereich Zivilschutz': 'Zivilschutz',
    'VKF Bereich Feuerwehr': 'Feuerwehr',
  } as Record<string, string>,
  // Palette-search synonyms, keyed by the RAW FireGIS name. Matched (substring, case/umlaut
  // tolerant) IN ADDITION to the raw key + display label + category heading — so "wasser"
  // finds the Hydranten and "UN"/"ADR" find the Gefahrentafel. Recognition over recall: the
  // operator types whatever the thing is called in their head, not our label. Locale overlays
  // may translate; missing keys fall back to these German lists.
  symbolAliases: {
    'VKF Feuer': ['Brand', 'Brandherd', 'Flammen'],
    'VKF Rettungen': ['Personenrettung', 'Menschenrettung', 'Evakuierung'],
    'VKF Unfall': ['Verkehrsunfall', 'Kollision'],
    'VKF Gefaehrliche Stoffe': ['Gefahrgut', 'ABC', 'Chemie', 'Öl', 'Oel', 'Austritt', 'Hazmat'],
    'VKF Wasser': ['Wasserschaden', 'Hochwasser', 'Leck'],
    'FW Gefahr Ex': ['Explosionsgefahr', 'Detonation'],
    'FW Beschaedigung': ['Schaden', 'beschädigt'],
    'FW Teilzerstoerung': ['Zerstörung', 'Trümmer'],
    'FW Totalzerstoerung': ['Zerstörung', 'Einsturz', 'Trümmer'],
    'FW Ueberschwemmung': ['Hochwasser', 'Flut', 'Wasserschaden'],
    'FW Gefahr Tafel': ['UN', 'UN-Nummer', 'ADR', 'Gefahrgut', 'Kemler', 'orange Tafel', 'Warntafel', 'Hazmat'],
    'FW Gefahr allgemein': ['Achtung', 'Warnung', 'Gefahrenstelle'],
    'FW Gefahr G': ['Gasleitung', 'Erdgas', 'Propan', 'Explosionsgefahr'],
    'FW Gefahr C': ['Chemikalien', 'Säure', 'Lauge', 'Gefahrstoff'],
    'FW Gefahr Radioaktiv': ['Strahlung', 'atomar', 'nuklear', 'A-Gefahr'],
    'FW Gefahr W': ['Wassergefahr', 'Gewässer', 'Gewässerschutz'],
    'FW Elektroanlage': ['Strom', 'Spannung', 'Hochspannung', 'Elektrizität'],
    'VKF KP Front': ['Kommandoposten', 'Einsatzleitung', 'Führungsstandort'],
    'VKF Einsatzleiter': ['Einsatzleitung', 'EL'],
    'FW Offizier': ['Kader', 'Führung'],
    'FW Sammelplatz': ['Treffpunkt', 'Besammlung'],
    'FW Warteraum': ['Bereitstellungsraum', 'Bereitstellung'],
    'VKF Kontrollposten': ['Checkpoint', 'Kontrolle', 'Verkehrsposten', 'Pforte'],
    'VKF Informationszentrum': ['Info', 'Medien', 'Auskunft', 'Mediensammelstelle'],
    'VKF Bereich Materialdepot': ['Material', 'Depot', 'Lager'],
    'FW Absperrung': ['Sperre', 'Barriere', 'Absperrband', 'Sperrzone'],
    'VKF Verkehrssperre ueberwacht': ['Strassensperre', 'Absperrung', 'Sperre', 'bewacht', 'Bewachung', 'Überwachung'],
    'VKF Fahrzeug': ['Auto', 'TLF', 'Tanklöschfahrzeug', 'Einsatzfahrzeug', 'Lastwagen'],
    'VKF Drehleiter': ['ADL', 'Autodrehleiter', 'Leiterfahrzeug'],
    'VKF Luefter mobil': ['Ventilator', 'Belüftung', 'Druckbelüfter'],
    'FW Kleinloeschgeraet': ['Feuerlöscher', 'Handfeuerlöscher', 'Löschdecke'],
    'VKF Hubretter': ['Hebebühne', 'Teleskopmast'],
    'VKF Pumpe Typ2': ['Motorspritze', 'Wassertransport', 'MS'],
    'FW Tauchpumpe': ['Pumpe', 'Keller', 'Wasser', 'TP', 'Lenzpumpe'],
    'FW Wassersauger': ['Sauger', 'Nasssauger', 'Wasser', 'WS'],
    'VKF Helilandeplatz': ['Helikopter', 'Heli', 'Rega', 'Landeplatz'],
    'VKF Drohne': ['Drone', 'UAV', 'Multicopter', 'Quadrocopter', 'Luftaufklärung', 'Wärmebild'],
    'FW Entrauchung': ['Rauchabzug', 'Belüftung', 'Abluft'],
    'FW Sprungretter': ['Sprungkissen', 'Sprungpolster', 'Rettungskissen'],
    'FW Leiter': ['Anstellleiter', 'Schiebleiter', 'Steckleiter'],
    'VKF Sammelstelle': ['Unverletztensammelstelle', 'Betreuung', 'Evakuierte'],
    'VKF Patientensammelstelle': ['Verletzte', 'Triage', 'Patienten'],
    'VKF Sanitaetshilfsstelle': ['Verbandplatz', 'Sanposten', 'Sanhist'],
    'VKF Totensammelstelle': ['Tote', 'Verstorbene'],
    'FW Verwundetennest': ['Verletzte', 'Verwundete'],
    'FW AED': ['Defibrillator', 'Defi', 'Herzdruckmassage', 'Reanimation', 'Herzstillstand'],
    'VKF Bereich Sanitaet': ['Ambulanz', 'Rettungsdienst', '144'],
    'VKF Bereich Feuerwehr': ['118'],
    'VKF Bereich Polizei': ['117', 'Kantonspolizei'],
    'VKF Bereich Chemiewehr': ['ABC-Wehr', 'Chemikalien'],
    'VKF Bereich Zivilschutz': ['ZS', 'Bevölkerungsschutz'],
    'SI Ueberflurhydrant': ['Wasserbezug'],
    'SI Unterflurhydrant': ['Wasserbezug'],
    'VKF Innenhydrant': ['Steigleitung', 'Wandhydrant'],
    'SI Wasserloeschposten': ['Innenangriff'],
    'WV Loeschweier': ['Weiher', 'Teich', 'Reservoir', 'Löschwasserreserve'],
    'SI Wasserbezugsort': ['Saugstelle', 'Fluss', 'Bach', 'See'],
    'SI Wasserdruckversorgung': ['Druckleitung', 'Reservoir'],
    'GB BA Wand F30': ['Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F60': ['Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F180': ['Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB Ture BS R30': ['Brandschutztüre', 'Brandschutztür', 'Tür'],
    'GB Ture Durchgang': ['Tür', 'Eingang', 'Zugang'],
    'GB Lift': ['Aufzug', 'Fahrstuhl', 'Warenlift'],
    'GB Kamin': ['Cheminée', 'Schornstein', 'Abgas'],
    'GB Abzug': ['Lüftung', 'Ventilation', 'Abluft'],
    'SI Schieber': ['Absperrschieber', 'Ventil', 'Gasschieber'],
    'GB Elektrotableau': ['Sicherungskasten', 'Verteiler', 'Strom', 'Hauptschalter'],
    'GB Sprinklerzentrale': ['Sprinkler', 'Löschanlage'],
    'GB Brandmeldezentrale': ['BMA', 'BMZ', 'Brandmeldeanlage', 'Alarmzentrale'],
    'GB BMA Melder': ['Melder', 'Brandmelder', 'Rauchmelder', 'Meldergruppe', 'Handfeuermelder'],
    'GB BMA-Z': ['BMA', 'BMZ', 'Brandmeldezentrale', 'Brandmeldeanlage', 'Piktogramm', 'Wandschild'],
    'GB RWA-BS': ['RWA', 'Rauch- und Wärmeabzug', 'Rauchabzug', 'Wärmeabzug', 'Bedienstelle', 'RWA-Zentrale'],
    'GB Fernsignaltableau': ['Brandmeldeanlage', 'Signaltableau'],
    'GB Schluesseldepot': ['Schlüsselrohr', 'Feuerwehrschlüsseldepot'],
    'GB Treppe 8': ['Treppenhaus', 'Stiege', 'Aufgang'],
    'SI Windrichtung': ['Wind', 'Windsack', 'Wetter'],
    'SI Nordpfeil': ['Norden', 'Kompass', 'Orientierung'],
    'FKS Schluesselstelle': ['Schlüsselstelle', 'Engstelle', 'Vegetationsbrand'],
    'FKS Beobachtungsposten': ['Beobachtung', 'Sicherungsposten', 'Posten', 'Wache'],
    'FKS Helikopter': ['Heli', 'Helikopter', 'Luftfahrzeug'],
    'FKS Drohnenlandeplatz': ['Drohne', 'Landeplatz', 'UAV'],
    'FKS Forst': ['Förster', 'Forstdienst', 'Waldbrand'],
    'ZS Fahrzeugplatz': ['Fahrzeuge', 'Abstellplatz', 'Bereitstellungsraum', 'Fz'],
    'ZS Angehoerigensammelstelle': ['Angehörige', 'Betreuung', 'Care'],
    'ZS Verpflegungsabgabestelle': ['Verpflegung', 'Essen', 'Kantine', 'Getränke'],
    'ZS Betriebsstoffabgabestelle': ['Tanken', 'Treibstoff', 'Benzin', 'Diesel'],
    'ZS Dekontaminationsstelle': ['Deko', 'Dekon', 'Dekontamination', 'Chemiewehr'],
  } as Record<string, string[]>,
  // Symbol-palette category headings, keyed by the German category (the keys of
  // appConfig.symbols.presets.byCat). de = identity; en/fr/it translate. The German key is the
  // canonical category — only the heading localizes. Palette falls back to the raw key.
  symbolCategories: {
    'Schadenlage': 'Schadenlage',
    'Gefahren': 'Gefahren',
    'Gebäude': 'Gebäude',
    'Wasser': 'Wasser',
    'Führung': 'Führung',
    'Personen / Sanität': 'Personen / Sanität',
    'Partner': 'Partner',
  } as Record<string, string>,
} as const
