// French copy · Anwesenheit, Anrückend, Zeitplan and Schichten.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/anwesenheit.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'anwesenheit' | 'anrueckend' | 'zeitplan' | 'schichten'

export const anwesenheitCopy: Localizable<Pick<Copy, Keys>> = {
  anwesenheit: {
    title: 'Présence',
    summary: '{present} présents',
    summaryLeft: '{left} partis',
    reload: 'Recharger l’effectif',
    loading: 'Chargement …',
    searchPlaceholder: 'Rechercher …',
    ortScene: 'Sur place',
    ortStation: 'Caserne',
    ortToScene: 'Envoyer {name} sur place',
    ortToStation: 'Placer {name} à la caserne',
    logOrtScene: '{name} sur place',
    logOrtStation: '{name} à la caserne',
    summaryOrt: '{scene} sur place · {station} caserne',
    statusFrei: 'non présent',
    filterLabel: 'Filtrer',
    statusAll: 'Tous',
    statusFilterLabel: 'Filtrer par statut',
    noteOnly: 'Avec remarque seulement',
    statusPresent: 'présent',
    statusLeft: 'parti',
    loadFailedTitle: 'L’effectif n’a pas pu être chargé.',
    loadFailedHint: 'Hors ligne ou serveur injoignable. La dernière liste chargée est conservée.',
    emptyTitle: 'Aucun effectif enregistré.',
    emptyHint: 'L’effectif se saisit ou se synchronise dans l’administration.',
    emptyHintSync: 'Synchronisez l’effectif depuis {provider}.',
    retry: 'Réessayer',
    lockedTitle: 'Dans un binôme – annoncer d’abord la sortie avec « Annoncer sorti »',
    notInDivera: 'Ne figure plus sur la liste',
    notInSource: 'Plus dans {provider}',
    weg: 'parti',

    noteLabel: 'Remarque',
    notePlaceholder: 'p. ex. chauffeur TP',
    logNote: '{name} – remarque : {note}',
    logPresent: '{name} présent',
    logPresentAgain: '{name} de nouveau présent',
    logLeft: '{name} parti',
    logGuestAdded: '{name} saisi comme personne supplémentaire',
    logGuestAddedAs: '{name} saisi comme personne supplémentaire – {role}',
    addGuest: 'Ajouter «{name}» comme invité',
    guestBadge: 'Invité',
    removeGuest: 'Supprimer la personne',
    logPresentAs: '{name} présent – {role}',
    logRoleGroup: 'Sous {role} : {list}',
    logRoleGroupTrupp: 'Dans un binôme : {list}',
    undoTap: 'Annuler la dernière saisie',
    redoTap: 'Rétablir la saisie',
    undone: 'Présence annulée : {names}',
    redone: 'Présence rétablie : {names}',
    roleEinsatzleiter: 'Chef d\'intervention',
    roleEinsatzleiterShort: 'CI',
    roleEinsatzleiterStv: 'Remplaçant du chef d\'intervention',
    roleEinsatzleiterStvShort: 'Rempl. CI',
    roleFahrer: 'Chauffeur {vehicle}',
    roleBedienung: 'Opérateur {symbol}',
    roleOffizier: 'Officier {funktion}',
    roleAtemschutz: 'ARI',
    roleTrupp: 'Binôme',
    // la fonction du chef de binôme — UN seul jeton avec trait d’union, pour rester lisible dans la
    // liste de fonctions séparée par des virgules (« ARI-CG, Chauffeur TLF »).
    roleLeader: '{role}-CG',
    roleOffizierPlain: 'Officier',
    alreadyBooked: '{role}',
    conflictUnderPa: '{name} est sous ARI – binôme {trupp}.',
    conflictInTrupp: '{name} est dans le binôme {trupp}.',
    statusUnderPa: 'sous ARI',
    statusInTrupp: 'dans un binôme',
    conflictElInTrupp: '{name} est chef d\'intervention et en même temps dans le binôme {trupp}.',
    conflictLeft: '{name} est enregistré comme «parti».',
    presentOnlyOn: 'Présents seulement – toucher pour toute la troupe',
    presentOnlyOff: 'Toute la troupe – toucher pour les présents seulement',
    onlyPresent: 'Présents seulement',
    rankFilterLabel: 'Filtrer par grade',
    rankAll: 'Tous',
    backAgain: 'De retour',
    von: 'de',
    bis: 'à',
    addBlock: 'Nouvelle plage dès maintenant',
    blockSplit: '{name} : nouvelle plage – celle en cours a été close',
    blockRemoved: 'Plage de {name} supprimée',
    blockRemove: 'Supprimer la plage',
    blocksTitle: 'Présence – {name}',
    blocksSection: 'Plages saisies',
    blocksNone: 'Pas encore été présent.',
    blocksHint: 'Chaque ligne est une présence réelle de cette personne. Corrige ici si un pointage est à côté.',
    openBlocks: 'Ouvrir la présence de {name}',
    openBlocksNote: 'Ouvrir la présence de {name} · remarque saisie',
    statusNote: 'Remarque',
    stillHere: 'encore là',
    running: 'en cours',
    ended: 'terminé',
    flip: 'basculer',
    viewList: 'Présence',
    viewPlan: 'Planning',
    viewBands: 'Tours',
    viewLabel: 'Vue',
  },
  anrueckend: {
    title: 'En route',
    sourceBare: 'Divera',
    coming: (n: number) => (n === 1 ? '1 vient' : `${n} viennent`),
    notComing: (n: number) => (n === 1 ? '1 ne vient pas' : `${n} ne viennent pas`),
    here: (n: number) => (n === 1 ? '1 présent' : `${n} présents`),
    notComingGroup: (n: number) => `Ne vient pas (${n})`,
    notComingWord: 'ne vient pas',
    checkIn: 'présent',
    checkInLabel: '{name} est là – enregistrer comme présent',
    allHere: 'Tous ceux qui ont annoncé venir sont enregistrés.',
    unmapped: (n: number) => (n === 1 ? '1 réponse sans entrée dans l’effectif' : `${n} réponses sans entrée dans l’effectif`),
    hint: 'Une réponse Divera n’est pas une présence – seul «présent» enregistre quelqu’un.',
    collapse: 'Replier «En route»',
    expand: 'Déplier «En route»',
  },
  zeitplan: {
    title: 'Planning',
    summary: '{planned} planifiés · {present} présents',
    summaryEmpty: 'Rien de planifié',
    add: 'Tour',
    from: 'de',
    to: 'à',
    remove: 'Supprimer le tour',
    removed: 'Tour de {name} supprimé',
    added: 'Tour planifié pour {name}',
    moved: 'Tour de {name} déplacé',
    conflict: 'Double affectation – deux tours au même moment',
    conflictTitleOne: 'Une personne est affectée deux fois.',
    conflictTitleMany: '{n} personnes sont affectées deux fois.',
    conflictWho: '{name} · {from}–{to}',
    conflictMore: '… et {n} autres',
    conflictFix: 'Touche l\'une des deux affectations et mets-la sur «disponible» – l\'horaire lui-même reste.',
    conflictShort: 'double affectation',
    brokenShift: 'Ce tour se termine avant de commencer – touche pour corriger',
    now: 'maintenant',
    coverage: 'Couverture',
    coverageHint: 'Trois lignes : gris disponible, bleu affecté, vert réellement présent – là où la ligne verte s\'effondre se trouve le trou.',
    coverageExpand: 'Afficher les chiffres – combien sont disponibles, affectés et présents',
    coverageCollapse: 'Masquer les chiffres',
    planned: 'disponible',
    actual: 'présent',
    emptyTitle: 'Aucun tour planifié.',
    emptyHint: 'Planifie par personne de quand à quand elle est disponible. Le planning ne modifie pas la présence – celle-ci se coche toujours dans la liste de présence.',
    legendHint: 'Creux = disponible · plein = affecté · vert = réellement présent',
    print: 'Imprimer le planning',
    sheetSchichtplan: 'Plan des tours …',
    sheetVerfuegbarkeiten: 'Disponibilités …',
    sheetSchichtplanTitle: 'Plan des tours',
    sheetVerfuegbarkeitenTitle: 'Disponibilités',
    peopleCount: (n: number) => (n === 1 ? '1 personne' : `${n} personnes`),
    bandsCount: (n: number) => (n === 1 ? '1 tour' : `${n} tours`),
    sheetContent: '{people} · état {t}',
    sheetContentBands: '{people} · {bands} · état {t}',
    sheetSchichtplanHint: 'Les tours en colonnes, les noms en lignes, des coches entre les deux – le formulaire de conduite tel que la troupe le connaît.',
    sheetVerfuegbarkeitenHint: 'Qui peut de quand à quand, indépendamment de tout tour – y compris tous ceux qui n\'en ont aucun.',
    pdf: 'En PDF',
    paperMenu: 'Sur papier',
    printFailed: 'Le planning n\'a pas pu être imprimé.',
    who: 'Qui',
    editTitle: 'Tours – {name}',
    plannedSection: 'Disponibilité et affectation',
    actualSection: 'Réellement présent',
    actualHint: 'Provient de la présence et s\'y saisit – le planning ne la modifie pas.',
    actualNone: 'Pas encore été présent.',
    plannedNone: 'Aucune disponibilité saisie.',
    addShift: 'Ajouter un tour',
    stillHere: 'encore là',
    running: 'en cours',
    ended: 'terminé',
    flip: 'basculer',
    done: 'Terminé',
    fromStart: 'dès le début',
    sheetHint: 'Ajuster les heures ici · basculer l\'état à droite · la suppression ne se fait qu\'ici.',
    laneHint: 'Glisser enregistre la disponibilité · toucher une barre affecte la personne · glisser déplace la barre · maintenir ouvre les tours',
    laneHintShow: 'Afficher les commandes',
    laneHintHide: 'Masquer les commandes',
    available: 'disponible',
    confirmed: 'affecté',
    toggleHint: 'Toucher en fait «{state}»',
    zoomIn: 'Période plus courte',
    zoomOut: 'Période plus longue',
    horizonUntil: 'jusqu\'à {t}',
    horizon: 'Période',
    openFor: 'Ouvrir les tours de {name}',
    planAt: 'Planifier un tour pour {name}',
    dragFrom: 'Tirer le début',
    editEntry: 'Modifier …',
    dragTo: 'Tirer la fin',
  },
  schichten: {
    title: 'Tours',
    who: 'Qui',
    addBand: 'Définir un tour',
    addBandFirst: 'Définir le premier tour',
    emptyTitle: 'Aucun tour.',
    emptyHint: 'Crée les créneaux que tu veux couvrir – ensuite il suffit de toucher par personne.',
    emptyAxisHint: 'Ou dessiner librement par personne dans le planning.',
    sheetAddTitle: 'Créer un tour',
    sheetEditTitle: 'Modifier le tour',
    labelField: 'Nom',
    labelPlaceholder: 'Matin',
    sheetHint: 'Le tour est créé pour toute la troupe. Chaque case commence vide.',
    create: 'Créer',
    save: 'Enregistrer',
    removeBand: 'Supprimer le tour',
    removeBandHint: 'La suppression n\'enlève que la colonne – les heures affectées restent dans le planning comme heures libres.',
    removedBand: 'Tour «{label}» supprimé',
    moveTitle: 'Déplacer aussi les heures ?',
    moveMsg: '{n} personnes sont affectées aux anciennes heures. Leurs heures doivent-elles suivre ?',
    moveYes: 'Faire suivre',
    moveNo: 'Le tour seulement',
    countsAria: '{available} disponibles, {planned} planifiés',
    available: 'disponible',
    confirmed: 'planifié',
    ownTimes: 'heures propres hors de tout tour : {times}',
    ownTimesMore: '{first} +{n}',
    deviating: '{name} : {from}–{to} au lieu de {bandFrom}–{bandTo}',
    cellAria: '{name} dans {band}',
    cellFrom: 'dès {t}',
    cellUntil: 'jusqu\'à {t}',
    partial: 'partiellement',
    partialHint: 'Tous ne couvrent pas l\'ensemble du tour.',
    resolveTitle: 'En partie disponible, en partie planifié',
    resolveMsg: '{name} est en partie affecté à {band} et en partie seulement disponible. Que doit valoir pour ce créneau ?',
    resolveGap: 'Le reste du tour n\'est pas couvert par cette personne – cela ne change pas.',
    splitTitle: 'Sera divisé',
    splitChanges: 'change',
    splitKeeps: 'reste {state}',
    splitNote: 'Seule la partie à l\'intérieur du tour change ; en dehors, tout reste tel quel.',
    crossTitle: 'Dépasse le tour',
    crossMsg: 'Cette plage de {name} dépasse {band}. Que doit valoir pour ce créneau ?',
    resolveAvailable: 'Tout sur disponible',
    resolveConfirmed: 'Tout sur planifié',
    resolveCancel: 'Annuler',
    conflict: 'Double affectation – deux tours au même moment',
    editEntry: 'Modifier …',
    scrollHint: 'Faire défiler horizontalement pour voir d\'autres tours',
  },
}
