// French copy · the Trupps board (Atemschutz) and line decorations.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/atemschutz.ts.

import type { Copy, Localizable } from '../index'

export const atemschutzCopy: Localizable<Pick<Copy, 'atemschutz' | 'lineDecor'>> = {
  atemschutz: {
    title: 'Surveillance ARI',
    // titre du tableau dans l'application complète — il porte les deux sections (voir de/atemschutz.ts)
    boardTitle: 'Binômes',
    // le titre tronqué ouvre les indications de l'intervention (09.09., voir de/atemschutz.ts)
    headDetailOpen: 'Afficher les indications',
    headDetailTitle: 'Intervention',
    sectionAtemschutz: 'ARI',
    sectionAtemschutzEmpty: 'Aucun binôme sous ARI actuellement.',
    sectionPlain: 'Autres binômes',
    kindLabel: 'Type de binôme',
    kindAtemschutz: 'Sous ARI',
    kindPlain: 'Sans ARI',
    asMark: 'ARI',
    empty: 'Aucun binôme en surveillance.',
    emptyHint: 'Créez un binôme pour démarrer la surveillance.',
    newTrupp: 'Annoncer le binôme',
    shareLink: 'Transmettre la surveillance',
    shareLinkOn: 'Transmettre la surveillance – un lien est actif',
    linkReentryHint: 'Le lien ramène à ce tableau – si la page est fermée par mégarde, il suffit d’ouvrir à nouveau le code QR.',
    /** the «+ Trupp» tab on the handed-over phone board (AtemschutzView · focusMode) */
    liteNewTab: 'Binôme',
    /** the three-section stack on ANY phone (TruppForm · stack, 04.09.) – replaces the two-step
     *  wizard; «Mission et ligne» is one section (see de/atemschutz.ts). */
    stackPressure: '{n} bar',
    // no longer asked in the Trupp form (04.09.) – still offered on the Lage/plan and in admin
    colorAuto: 'Automatique',
    // état sync/horloge dans l'en-tête du tableau (voir de/atemschutz.ts)
    syncStand: '{status} · {t}',
    clockSkewChip: 'Horloge de l\'appareil décalée ({d} min)',
    formCreateTitle: 'Annoncer le binôme',
    formEditTitle: 'Modifier le binôme',
    formRedeployTitle: 'Réengager',
    sectionTeam: 'Binôme',
    auftragLabel: 'Mission',
    auftragOpen: 'Mission ouverte',
    // Libellés d'AFFICHAGE des types de mission, indexés par l'id (la valeur stockée reste l'id).
    auftragLabels: {
      retten: 'Sauver',
      loeschen: 'Éteindre',
      absuchen: 'Fouiller',
      sichern: 'Sécuriser',
      erkunden: 'Reconnaître',
      verkehr: 'Circulation',
      sanitaet: 'Sanitaire',
      wasser: 'Alimentation en eau',
      bereitstellung: 'Mise à disposition',
      anderes: 'Autre',
    },
    equipmentLabels: {
      retthaube: 'Cagoule de sauvetage',
      wbk: 'WBK',
      multiwarn: 'Multiwarn',
    },
    equipmentLabel: 'Équipement',
    equipmentShort: {
      retthaube: 'RH',
      wbk: 'WBK',
      multiwarn: 'MW',
    },
    zielLabel: 'Objectif',
    // UN seul placeholder pour les deux types de binôme et chaque mission (voir de/atemschutz.ts).
    zielPlaceholder: 'Où / quoi …',
    zielClear: 'Vider l’objectif',
    leaderLabel: 'Chef de groupe',
    teamSearchPlaceholder: 'Rechercher une personne …',
    // the phone chip row (05.09.) — see de/atemschutz.ts for why the roster list is gone there
    teamSearchMore: 'Rechercher une autre personne …',
    teamHintChips: 'Toucher un nom = chef de groupe',
    leaderBadge: 'CG',
    makeLeader: 'Désigner {name} chef de groupe',
    teamRemove: 'Retirer {name} de l’équipe',
    teamTaken: 'dans une équipe',
    teamManual: 'invité',
    teamGuestAdd: 'Ajouter «{name}» comme invité',
    lineNoLabel: 'Conduite',
    lineLegacyNote: 'Saisie précédente : « {value} »',
    lineTyped: 'N° …',
    lineTakeTitle: 'La conduite {n} est occupée',
    lineTakeMsg: 'L’équipe {from} est sur la conduite {n}. Y mettre l’équipe {to} ?',
    lineTakeConfirm: 'Reprendre',
    lineHeldToast: 'La conduite est occupée par le binôme {name}.',

    lineOptTaken: 'L’équipe {name} est sur cette conduite',
    lineShow: 'Montrer la conduite sur la carte',
    logLineLinked: 'Équipe {name} sur la conduite {n}',
    logLineUnlinked: 'Équipe {name} : conduite détachée',
    lineUnlinkedToast: 'Conduite détachée',
    markerLabel: 'Équipe PR',
    markerNone: 'Aucune équipe',
    markerPick: 'Reprendre une équipe placée',
    markerOptTaken: 'Appartient à l’équipe {name}',
    markerTakeTitle: 'L’équipe {from} est ici',
    markerTakeMsg: 'Cette équipe placée appartient à l’équipe {from}. La donner à l’équipe {to} ?',
    markerTakeConfirm: 'Reprendre',
    logMarkerUnlinked: 'L’équipe {name} n’est plus placée',
    entryAskTitle: 'Engager l’équipe ?',
    entryAskMsg: 'L’équipe {name} est annoncée mais pas encore engagée. L’engager maintenant ? Le chrono de contact démarre immédiatement.',
    entryAskCancel: 'Pas encore',
    pressureLabel: 'Pression d’entrée',
    newPressureLabel: 'Nouvelle pression d’entrée',
    funkkanalSection: 'Canal radio',
    funkkanalDown: 'Canal radio bas',
    funkkanalUp: 'Canal radio haut',
    funkkanalUnit: 'Canal',
    clearName: 'Effacer le nom',
    notPresent: 'absent',
    noRoster: 'Aucun effectif disponible',
    assignedConflict: '{name} est déjà dans un autre binôme.',
    // la seule manœuvre qui dénoue la situation — la retirer de l’autre binôme et continuer ici
    assignedTransfer: 'Déplacer dans ce binôme',
    // …et quand elle n’est pas offerte : l’autre binôme est engagé, sa montre de contact tourne
    assignedConflictDeployed: '{name} est dans un binôme qui est engagé.',
    saveBlockedTeam: 'Indiquer d’abord un chef de binôme.',
    auftragMissingHint: 'Mission manquante – le binôme est engagé avec «mission ouverte».',
    saveBlockedAuftrag: '«Autre» a besoin d’un objectif.',
    saveBlockedPressure: 'Pression d’entrée manquante.',
    cancel: 'Annuler',
    save: 'Enregistrer',
    start: 'Annoncer',
    reenterSubmit: 'Engager',
    reenterStandby: 'Mettre en réserve',
    reenterStandbyHint: 'Annoncer le binôme comme réserve – le compteur de contact ne démarre qu\'à «Engager».',
    sinceContact: 'Depuis le dernier contact',
    elapsed: 'Temps d’intervention',
    outFor: 'Sorti depuis',
    outForPlain: 'Sans mission depuis', // ⚠️ app only — see de/atemschutz.ts · outForPlain
    currentPressure: 'Pression',
    lowestPressure: 'Le plus bas',
    lineField: 'Conduite',
    edit: 'Modifier',
    pressureConfirm: 'Confirmer',
    pressureConfirmHint: 'Confirmer la nouvelle pression – compte comme contact',
    verlauf: 'Journal',
    cardMenu: 'Autres actions',
    bandPreEntry: 'Pas encore engagée',
    bandRegisteredAt: 'annoncée à',
    zoneTimes: 'Heures',
    lastContactAt: 'Dernier contact',
    nextContactDue: 'Prochain contact',
    contactIntervalLabel: 'Intervalle de contact',
    contactIntervalValue: '{min} min',
    verlaufLatest: 'dernier : {time} {what}',
    // ⚠️ Des mots d’ÉVÉNEMENT dans cette colonne (« Art »), jamais des mots d’état : la ligne dit
    // ce qui s’est passé, « Sorti » est ce que la carte dit du binôme ensuite (status · outFor).
    readingKind: { registered: 'Annoncée', entry: 'Entrée', contact: 'Contact', pressure: 'Pression',
      alarm: 'Pression d\'alarme',
      rueckzug: 'Repli',
      // ⚠️ le repli a été annulé — personne n’est rentré (voir la base allemande)
      exit: 'Sortie', resume: 'Repli annulé',
      paOn: 'Sous ARI', paOff: 'Surveillance ARI terminée',
      // a `crew` row prints its names (AtemschutzView · readingLabel); this is the fallback word
      crew: 'Équipe',
    },
    readingNoAs: '{what} – sans ARI',
    clockOk: 'Contact ok',
    clockFrozen: 'État à la clôture',
    clockWarn: 'Contact à faire',
    clockOverdue: 'En retard',
    clockAlarmPressure: 'Pression d’alarme',
    clockAlarmLimit: 'Limite {bar} bar',
    overdueBadge: (n: number) => `${n} en alarme`,
    overdueBadgeGo: 'Vers l’équipe {name} – alarme la plus urgente',
    collapse: 'Vue d’ensemble',
    actEnter: 'Engager',
    actContact: 'Contact',
    actRueckzug: 'Annoncer le repli',
    actContinue: 'Poursuivre',
    actExit: 'Annoncer sorti',
    tileRueckzug: 'Repli',
    tileExit: 'Sorti',
    quickTrupp: 'Binôme {no}',
    kanalSheetHint: 'Toucher choisit et ferme.',
    formPickTake: 'Appliquer',
    lineNone: 'aucune',
    lineChip: 'Cond. {n}',
    auftragAdd: '+ Mission',
    actExitPlain: 'Mission terminée', // ⚠️ app only — see de/atemschutz.ts · actExitPlain
    actReenter: 'Réengager',
    actNotDeployed: 'Non engagée',
    actNotDeployedHint: 'Clore l’équipe sans qu’elle soit passée sous ARI – reste prête pour un engagement ultérieur',
    statusNotDeployed: 'Non engagée',
    statusRemoved: 'Retiré du tableau',
    logNotDeployed: 'Équipe {name} non engagée',
    remove: 'Retirer',
    removeUnusedTitle: 'L’équipe n’est pas intervenue',
    removeUnusedMsg: 'Clore {name} comme «non engagée» plutôt que la retirer ? L’équipe reste prête au tableau – «Retirer» sert aux annonces erronées.',
    place: 'Placer',
    placeWhere: 'Placer où ?',
    placeNoTarget: 'Aucun plan disponible – choisissez d’abord un bâtiment via « Bâtiment » dans la barre.',
    showOnPlan: 'Montrer sur le plan',
    showOnMap: 'Montrer sur la carte',
    dockedAt: 'près de «{host}»',
    dockLabel: '{who} · près de «{host}»',
    dockedTeams: 'Amarré',
    preEntryHint: 'Pas encore engagé – appuyez sur « Engager » dès que le binôme passe sous ARI.',
    alarmArmed: 'Alarme active – son et notification · toucher pour couper',
    alarmMuted: 'Alarme coupée – son et notification, jusqu’à la fin de cette intervention · toucher pour activer',
    alarmBlocked: 'Son non autorisé – le navigateur l’a refusé · toucher, sinon seule la notification alerte',
    alarmBlockedNoFallback: 'Son non autorisé – toucher pour l’activer. Ce navigateur ne peut afficher aucune notification.',
    alarmDemoNote: 'Démo – le son et la notification sont désactivés sur cette instance',
    restoreMenu: 'Groupes retirés',
    // the bell's WORD on a wide head (22.09.2026; the honest state stays in the tooltip/aria)
    alarmWord: 'Sonnerie',
    alarmMutedWord: 'Muet',
    alarmBlockedWord: 'Activer le son',
    restoreItem: 'Rétablir {name}',
    alarmNotifyTitle: 'ARI en retard',
    alarmNotifyBody: 'Binôme {name} en retard – établir le contact.',
    status: { angemeldet: 'Annoncé', aktiv: 'En intervention', rueckzug: 'Repli', ueberfaellig: 'En retard', raus: 'Sorti' },
    statusPlainOut: 'Sans mission', // ⚠️ app only — see de/atemschutz.ts · statusPlainOut
    // comment un binôme est NOMMÉ dans le texte courant — voir la base allemande
    truppTerm: 'Binôme {name}',
    logRegister: 'Binôme {name} annoncé – pression d’entrée {bar} bar',
    logRegisterPlain: 'Binôme {name} annoncé',
    logRenumbered: 'Binôme {name} devient Binôme {no}',
    logRenumberedChip: '{from} devient {to}',
    logPlaced: 'Binôme {name} placé sur le plan',
    logPlacedMap: 'Binôme {name} placé sur la carte',
    placeLage: 'Carte',
    logEntry: 'Binôme {name} : entrée',
    // ⚠️ les lignes d’ENTRÉE disent avec quoi le binôme est entré — voir la base allemande
    logEntryNoAs: 'Binôme {name} : entrée – sans ARI',
    logSafetyEntry: 'Binôme {name} : équipe de sécurité engagée',
    logContact: 'Binôme {name} : contact confirmé',
    logPressure: 'Binôme {name} : pression {bar} bar',
    // ⚠️ dit ce qui SE PASSE au lieu d’affirmer un contact que personne n’a confirmé
    logRueckzug: 'Binôme {name} annonce le repli – horloge de contact remise à zéro',
    // ⚠️ UNE ligne qui annule le repli et dit ce qui vaut à la place — voir la base allemande
    logContinue: 'Binôme {name} : repli annulé – intervention poursuivie',
    logExit: 'Binôme {name} : sortie',
    logExitBar: 'Binôme {name} : sortie – pression restante {bar} bar',
    actPressure: 'Pression',
    pressureSheetTitle: 'Pression',
    pressureSheetHint: 'Un appui enregistre – compte comme contact.',
    exitSheetTitle: 'Pression restante',
    exitSheetHint: 'Un appui annonce la sortie – valeur la plus basse de l’équipe.',
    exitNoBar: 'Sorti sans pression',
    phoneSectionIn: 'Engagés',
    phoneSectionReady: 'Prêts',
    phoneSectionOut: 'Sortis',
    safetyTitle: 'Équipe de sécurité',
    safetyPick: 'Désigner',
    safetyPickTitle: 'Désigner l’équipe de sécurité',
    safetyPickNew: 'Annoncer un nouveau binôme (sécurité)',
    pinnedLabel: 'Binômes à contacter',
    contactEchoTitle: 'Contact déjà confirmé',
    contactEchoWho: 'Binôme {n}',
    contactEchoMsg: '{name} · il y a {s} s sur un autre appareil',
    contactEchoAgain: 'Confirmer encore',
    contactEchoOk: 'OK',
    editConflictOne: '{field} a été modifié entre-temps sur un autre appareil : {now} – écraser quand même ?',
    editConflictMany: '{fields} ont été modifiés entre-temps sur un autre appareil – écraser quand même ?',
    editConflictOverwrite: 'Écraser',
    editConflictBack: 'Retour au formulaire',
    editFieldLabels: { crew: 'Équipe', auftrag: 'Mission', ziel: 'Objectif', lineNo: 'Conduite', funkkanal: 'Canal radio', pressure: 'Pression d’entrée', kind: 'Type de binôme', equipment: 'Équipement' },
    logFirstPressure: 'Binôme {name} : contact – première pression {bar} bar remplace la pression d’entrée {from} bar',
    logFirstPressureSame: 'Binôme {name} : contact – première pression {bar} bar (comme la pression d’entrée)',
    pressureSheetFirst: 'Première pression – remplace la pression d’entrée {bar} bar, compte comme contact',
    newTruppShort: 'Binôme',
    removedToast: 'Binôme {name} retiré',
    notDeployedToast: 'Binôme {name} : pas engagé',
    removeInsideTitle: 'Le binôme {name} est engagé – l’annoncer sorti d’abord ?',
    removeInsideMsg: 'Retirer enlève le binôme du tableau et de toute alarme. En général, on veut dire : le binôme est sorti.',
    actEnterFirst: 'Engager',
    contactDone: 'Confirmé',
    pressureLockedLabelPlain: 'Pression d’entrée',
    pressureLocked: 'Binôme sorti',
    pressureLockedWhyExit: 'Binôme sorti · pression restante {bar} bar',
    entryLowTitle: 'Pression d’entrée basse',
    entryLowMsg: '{bar} bar – d’habitude dès {min} bar',
    entryLowConfirm: 'Garder {bar} bar',
    entryLowChange: 'Modifier',
    bottleAsk: 'Sorti il y a {min} min, dernière {bar} bar. Quelle bouteille ?',
    bottleAskNow: 'Tout juste sorti, dernière {bar} bar. Quelle bouteille ?',
    bottleSame: 'Même bouteille',
    bottleNew: 'Nouvelle bouteille',
    saveBlockedBottle: 'Choisir même ou nouvelle bouteille',
    logReenter: 'Binôme {name} réengagé – pression d’entrée {bar} bar',
    logReenterPlain: 'Binôme {name} réengagé',
    logReenterNoAs: 'Binôme {name} réengagé – sans ARI',
    logStandby: 'Binôme {name} en réserve – pas encore engagé',
    // le complément d’engagement ajouté aux trois lignes qui OUVRENT un engagement (voir de/atemschutz.ts) :
    // formes courtes, elles se greffent sur une phrase déjà complète
    logDetailLine: 'Ligne {n}',
    logDetailFunk: 'Canal {n}',
    logDetailNoAs: 'sans ARI',
    logAlarm: 'Alarme ARI : binôme {name} – {status}',
    logAlarmCleared: 'Alarme ARI terminée : binôme {name} – {reason}',
    alarmClearedBy: {
      exit: 'sortie',
      contact: 'contact radio',
      pressure: 'relevé de pression',
      rueckzug: 'repli',
      resume: 'engagement repris',
    } as Record<string, string>,
    alarmClearedOther: 'contact rétabli',
    alarmClearedByReopen: 'horloge de contact redémarrée (rouverte)',

    orderLabel: 'Ordre',
    orderUrgency: 'Urgence',
    orderManual: 'Tel que placé',
    orderAuftrag: 'Mission',
    orderName: 'Nom',
    moveBack: 'Monter',
    moveForward: 'Descendre',
    truppFallbackName: 'Binôme',
    editPressureLabel: 'Corriger la pression d\'entrée',
    editPressureHint: 'Corrige la pression d\'entrée saisie – ne compte pas comme contact radio.',
    officersOnly: 'officiers seulement',
    assignedFallbackName: 'Cette personne',
    estimated: 'Pression estimée',
    // la forme courte pour la ligne qui reste du socle (09.09., voir de/atemschutz.ts)
    estimatedShort: 'Estimation',
    estimatedHint: 'Aide à la planification – tant qu\'il n\'y a pas assez d\'historique de pression, estimé avec une bouteille de {liters} L et une consommation de {rate} L/min. Ne remplace pas l\'annonce de pression.',
    estimatedHintHistory: 'Aide à la planification – extrapolé de la consommation de pression confirmée de ce binôme. Ne remplace pas l\'annonce de pression.',
    estimatedSourceHistory: 'sur {count} relevés de pression · état {time}',
    estimatedSourceFallback: '{rate} L/min supposés · état {time}',
    alarmNote: 'Pression d\'alarme de {bar} bar atteinte',
    alarmNoteEst: 'Pression d\'alarme de {bar} bar – atteinte selon l\'estimation',
    pressureRose: 'Plus élevé que la dernière fois ({from} bar) – faute de frappe ?',
    chipHint: 'ARI – toucher pour la surveillance',
    alarmRowOverdue: 'ARI en retard – {name}',
    alarmRowOverdueSub: 'Aucun contact radio – établir le contact immédiatement.',
    alarmRowPressure: 'Pression d\'alarme atteinte – {name}',
    alarmRowOverdueMany: 'Protection respiratoire en retard – {count} équipes : {names}',
    alarmRowPressureMany: 'Pression d\'alarme atteinte – {count} équipes : {names}',
    alarmRowPressureManySub: 'Ordonner le repli.',
    alarmRowPressureSub: '{bar} bar, limite {line} bar – ordonner le repli.',
    alarmRowGo: 'Vers le binôme',
    alarmRowAck: 'Pris connaissance',
    alarmRowReadOnly: 'lecture seule',
    logSafety: 'Valeurs de sécurité ARI modifiées : {changes}',
    logSafetyInterval: 'Intervalle de contact radio {from} → {to} min',
    logSafetyGrace: 'Délai de grâce {from} → {to} s',
    logSafetyFunkkanal: 'Canal radio {from} → {to}',
    logEditFields: 'Binôme {name} : {changes}',
    changeLeader: 'Chef de binôme {from} → {to}',
    changeMemberOut: '{names} retirés du binôme',
    changeMemberIn: '{names} ont rejoint',
    // …et QUI EN FAIT PARTIE MAINTENANT, avec le « / » que cette app utilise pour un binôme
    changeCrewNow: 'Nouveau : {crew}',
    crewChange: {
      leader: 'Chef de binôme {from} → {to}',
      movedTo: '{name} → binôme {to}',
      movedFrom: '{name} du binôme {from}',
      left: '{name} retiré du binôme',
      joined: '{name} ajouté',
    },
    // le changement, en UNE ligne chez le binôme qui cède la personne — {name} ce binôme-là,
    // {to} celui qui la reprend (dont la propre ligne nomme déjà tout son effectif)
    logMovedOut: 'Binôme {name} : {person} passé au binôme {to}',
    logMovedOutPlain: 'Binôme {name} : {person} passé à un autre binôme',
    changeAuftragTo: 'mission {auftrag}',
    changeAuftragCleared: 'mission retirée',
    changeLine: 'Ligne {n}',
    changeLineCleared: 'Ligne libérée',
    // ⚠️ de → à, comme la pression d’entrée — « Canal radio 12 » ne disait pas s’il avait été
    // défini, changé ou simplement confirmé
    changeFunkkanal: 'Canal radio {from} → {to}',
    changeFunkkanalSet: 'Canal radio {n} défini',
    changeFunkkanalCleared: 'Canal radio retiré',
    changeColor: 'Couleur modifiée',
    changeEquipment: 'Équipement : {list}',
    changeEquipmentNone: 'Équipement : aucun',
    changePressure: 'Pression d\'entrée {from} → {to} bar',
    // une bouteille ouverte à l’instant n’a pas de « avant » — voir la base allemande
    changePressureSet: 'Pression d\'entrée {n} bar',
    changeKindPa: 'désormais sous ARI',
    changeKindPlain: 'plus sous ARI',
    kindOffTitle: '{name} : terminer la surveillance ARI ?',
    kindOffMsg: 'Le binôme est engagé. Sans ARI, l’horloge de contact et la pression '
      + 's’arrêtent, et il n’y a plus d’alarme pour lui. Tout ce qui a été saisi reste dans le '
      + 'journal et sur le rapport.',
    kindOffConfirm: 'Terminer la surveillance',
    logPressureAlarm: 'Binôme {name} : pression {bar} bar – pression d\'alarme atteinte',
    logRemoved: 'Binôme {name} retiré',
    logRestored: 'Binôme {name} rétabli',
    logInsideAtClose: 'Binôme {name} encore engagé à la clôture',
    cycleEndAtClose: '{t} (encore engagé à la clôture)',
    logClockRestart: 'Binôme {name} : horloge de contact redémarrée – intervention rouverte',
  },
  lineDecor: {
    W: 'Eau',
    S: 'Mousse',
    H: 'Rideau d’eau',
    P: 'Poudre',
    N: 'Ligne d’arrêt humide',
    T: 'Ligne d’arrêt sèche',
    G: 'Contre-feu',
  } as Record<string, string>,
}
