// French copy · the Gebäude card and floors.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/building.ts.

import type { Copy, Localizable } from '../index'

export const buildingCopy: Localizable<Pick<Copy, 'building'>> = {
  building: {
    title: 'Bâtiment',
    hint: 'Indication du registre',
    hintTitle: 'Tiré des registres fédéraux (RegBL, OFEN) – peut être obsolète ou incomplet. À vérifier sur place.',
    floors: '{n} niveaux',
    floorsOne: '1 niveau',
    flats: '{n} logements',
    flatsOne: '1 logement',
    year: 'Construit en {y}',
    period: 'Construit {p}',
    shelter: 'Abri',
    heating: 'Chauffage {e}',
    hotWater: 'Eau chaude {e}',
    pv: 'PV {kw}',
    pvBare: 'PV',
    pvTitle: 'Photovoltaïque au registre OFEN{since} – peut manquer même si une installation existe',
    pvSince: ', en service depuis le {d}',
    kw: '{n} kW',
    energy: {
      gas: 'gaz',
      oil: 'mazout',
      wood: 'bois',
      district: 'chauffage à distance',
      air: 'pompe à chaleur (air)',
      geothermal: 'pompe à chaleur (sol)',
      water: 'pompe à chaleur (eau)',
      electricity: 'électrique',
      solar: 'solaire',
      waste_heat: 'rejets de chaleur',
      other: 'autre',
    },
    status: {
      planned: 'projeté',
      approved: 'autorisé',
      under_construction: 'en construction',
      unusable: 'inutilisable',
      demolished: 'démoli',
      not_built: 'non réalisé',
    },
    srcGwr: 'RegBL {a} · état {d}',
    srcGwrNoAddr: 'RegBL état {d}',
    srcHeating: 'chauffage saisi {d}',
    srcPv: 'OFEN consulté {d}',
    srcCached: 'enregistré {d}',
    measures: 'Mesures immédiates',
    remarks: 'Remarques',
    objectSource: '{name} · {src}',
    objectNear: '{name} · à proximité ({m} m)',
    objectNearNoDist: '{name} · à proximité',
    visit: 'Dernière visite d’objet {d}',
    visitFindings: 'Dernière visite d’objet {d} · {n} défauts',
    visitFindingsOne: 'Dernière visite d’objet {d} · 1 défaut',
    chipTitle: 'Info bâtiment',
    chipLabel: 'Ouvrir la fiche du bâtiment',
    chipLabelHazards: 'Bâtiment : {h} – ouvrir la fiche',
    measuresShort: 'Mesures',
  },
}
