// French copy · the capture (QR) app.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/capture.ts.

import type { Copy, Localizable } from '../index'

export const captureCopy: Localizable<Pick<Copy, 'capture'>> = {
  capture: {
    title: 'Saisir l’intervention',
    invalid: 'Lien invalide ou saisie désactivée.',
    noIncidents: 'Aucune intervention saisissable pour le moment.',
    noIncidentsHint: 'Les interventions en cours et pas encore rapportées apparaissent ici. La vôtre manque ? Notez-la sur la feuille de saisie papier ou informez la conduite – elle peut la saisir plus tard.',
    searchName: 'Chercher un nom …',
    filterRecorded: 'Saisis {n}',
    back: 'Retour',
    alarmedAt: 'Alarme {t}',
    saveFailed: 'Échec de l’enregistrement',
    saveFailedOffline: 'Pas de réseau – la dernière modification n’a pas été enregistrée.',
    retry: 'Réessayer',
    savedOk: 'Enregistré',
    undo: 'Annuler',
    mittelSet: '{label} : désormais {n} {unit}',
    mittelRemoved: '{label} retiré',
    mittelExtra: 'Autres positions saisies',
    gerettete: 'Sauvés',
    gerettetePersonen: 'Personnes',
    geretteteTiere: 'Animaux',
    rueckmeldung: 'Retour à la centrale',
    rueckName: 'Choisir un nom …',
    rueckZeit: 'Heure',
    jetzt: 'Maintenant',
    kurzberichtHead: 'Rapport succinct',
    kurzberichtPlaceholder: 'Que s’est-il passé, qu’a-t-on fait ?',
    gruppenHead: 'Alarme des groupes',
    fahrzeugeHead: 'Départs des véhicules',
    einsatzleiter: 'Chef d’intervention',
    rapportPdf: 'Rapport PDF',
    pdfFailed: 'Échec du PDF – réessayer',
    sectionZeiten: 'Horaires',
    sectionAngaben: 'Indications',
    zeitenFilled: '{n} heures saisies',
    abschlussHead: 'Clôture',
    missingHead: 'Encore ouvert :',
    missingGo: 'Ouvrir {step}',
    missingNote: 'Imprimé comme champ à remplir.',
    ausgerueckt: 'Départ',
    kontaktperson: 'Personne de contact',
    kontaktpersonPlaceholder: 'Propriétaire / requérant',
    kontaktpersonTelefon: 'Téléphone personne de contact',
    kontaktpersonTelefonPlaceholder: 'Numéro de téléphone',
    kontaktpersonCall: 'Appeler la personne de contact',
    von: 'de',
    bis: 'à',
    ende: 'Fin d’intervention',
    sectionPersonen: 'Présences',
    presentCount: '{n} présents',
    tapHint: 'Toucher : absent → caserne → sur place → parti. Heure à côté : de = arrivée, après le départ à = départ.',
    stateLeft: 'parti',
    sectionMaterial: 'Matériel',
    cancel: 'Annuler',
    mittelCount: '{n} positions',
    pickMaterial: 'Choisir le matériel …',
    add: 'Ajouter',
    notePlaceholder: 'Note pour le journal …',
    footNote: 'Tout est enregistré en continu.',
    tapHelp: 'Aide à l\'utilisation',

    logAttendancePresent: '{name} présent (QR)',
    logAttendanceLeft: '{name} parti (QR)',
    logAttendanceCleared: '{name} retiré de la présence (QR)',
    logAttendanceRestored: '{name} rétabli (QR)',
    logTimes: 'Heures de {name} corrigées (QR)',
    logMittel: '{label} : {menge} {unit} (QR)',
    logAttachmentAdd: 'Photo du rapport ajoutée (QR)',
    logAttachmentRemove: 'Photo du rapport retirée (QR)',
    logMeta: 'Données du rapport modifiées (QR) : {fields}',
    partnersHead: 'Organisations partenaires',
    partnerOrg: 'Organisation',
    partnerNote: 'Remarque',
    partnerAdd: 'Ajouter une organisation',
    partnerPlaceholder: 'Organisation …',
    partnerRemove: 'Retirer l\'organisation',
    partnerCount: '{n} saisies',
    partnerNone: 'aucune',
    beilagenHead: 'Photos',
    beilagenAdd: 'Ajouter une photo',
    beilagenBusy: 'Téléversement …',
    beilagenCaption: 'Légende',
    beilagenRemove: 'Supprimer la photo',
    beilagenFailed: 'La photo n\'a pas pu être téléversée.',
    beilagenCount: '{n} photo(s)',
    beilagenNone: 'aucune',
    loadFailedOffline: 'Pas de réseau',
    clockSkew: 'L\'horloge de cet appareil dévie de {n} minutes – vérifie les heures saisies.',
    searchMaterial: 'Rechercher du matériel …',
    kpActive: 'Tablette PC active',
    kpActiveHint: 'La tablette du PC est en service – le rapport complet (avec le croquis) vient de là.',
    kpNormallyHint: 'Le rapport complet (avec le croquis) vient normalement de la tablette du PC.',
    usageChip: 'QR : {n} saisies · dernière {t}',
    usageChipOne: 'QR : 1 saisie · dernière {t}',
    exerciseHint: 'Exercice – ne compte pas dans la statistique d\'intervention.',
    groupCurrent: 'Actuel',
    groupBacklog: 'Encore ouvert',
  },
}
