// French copy · measuring, shapes, object Verlauf rows, the tool dock.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/drawing.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'measure' | 'shapes' | 'log' | 'objectDone' | 'addSheet' | 'toolDock'

export const drawingCopy: Localizable<Pick<Copy, Keys>> = {
  measure: {
    modeLine: 'Distance',
    modeArea: 'Surface',
    clear: 'Réinitialiser',
    insertPoint: 'Insérer un point',
    extendLine: 'Prolonger la ligne',
    deleteNode: 'Maintenir pour supprimer · clic droit sur ordinateur',
    snapConnect: 'Maintenir pour relier',
    snapRelease: 'Tirer pour détacher',
    distance: 'Distance',
    perimeter: 'Périmètre',
    boxWidth: 'Largeur',
    boxHeight: 'Hauteur',
    area: 'Surface',
    hoses: 'Tuyaux',
    profile: 'Profil altimétrique',
    ascent: 'Montée',
    descent: 'Descente',
    min: 'Le plus bas',
    max: 'Le plus haut',
    profileLoading: 'Chargement du profil altimétrique …',
    profileNone: 'Aucun profil altimétrique disponible',
    hintLine: 'Au moins 2 points pour la distance',
    hintArea: 'Au moins 3 points pour la surface',
    adoptLine: 'Reprendre comme ligne',
    adoptArea: 'Reprendre comme surface',
  },
  shapes: {
    sectionTitle: 'Formes',
    kindLabel: 'Forme',
    color: 'Couleur',
    rotate: 'Pivoter',
    stopLabel: 'Barre d’arrêt',
    carrierLabel: 'Vecteur',
    carrierNone: 'Aucun',
    carrierHeli: 'Héli',
    carrierTlf: 'TLF',
    resizeHint: 'Tirer le coin pour redimensionner',
    heightLabel: 'Hauteur',
    boxWidthHint: 'Tirer — largeur',
    boxHeightHint: 'Tirer — hauteur',
    endHint: 'Tirer l’extrémité — distance et direction',
    strokeLabel: 'Épaisseur du trait',
    cornersLabel: 'Angles',
    cornersRound: 'Arrondis',
    cornersSharp: 'Droits',
    names: { arrow: 'Flèche', cloud: 'Fumée', square: 'Rectangle', rotation: 'Rotation' },

    size: 'Taille',
    sizeSmaller: 'Plus petit',
    sizeBigger: 'Plus grand',
    lengthLabel: 'Longueur',
    lengthShorter: 'Plus court',
    lengthLonger: 'Plus long',
    moveHint: 'Glisse la nacelle – direction et portée',
  },
  log: {
    audioNote: 'Note audio',
    symbolPlaced: 'Symbole « {name} » posé',
    shapePlaced: '{name} placé',
    notePlaced: 'Note posée',
    shapeDrawn: '{name} dessiné',
    objectMoved: '{name} déplacé',
    placardDocked: '{name} amarré à «{host}»',
    placardUndocked: '{name} détaché de «{host}»',
    teamDocked: '{name} près de «{host}»',
    teamUndocked: '{name} détaché de «{host}»',
    referenceRebaked: 'Référence ajustée – {n} objets replacés',
    referenceRemeasured: 'Forme de la feuille mesurée – {n} objets replacés',
    referenceRolledBack: 'Modification de la référence abandonnée – échec de l’enregistrement',
    referenceDropped: 'Référence supprimée',
    referenceDroppedKept: 'Référence supprimée – {n} objets conservent leur dernière position',
    referenceLinked: 'Plan lié à la carte – {plan}',
    referenceLinkedPlaced: 'Plan lié à la carte – {plan} – {n} objets placés',
    objectDeleted: '{name} retiré',
    drawingDeleted: 'Dessin retiré',
    undo: 'Action annulée',
    redo: 'Action rétablie',
    undoNamed: '{action} annulé',
    redoNamed: '{action} rétabli',
    journalNote: 'Note',

    teamPlaced: '{name} placé sur la carte',
    selectionDeleted: '{n} objets retirés',
    duplicated: 'Objet dupliqué',
    entityEdited: '{name} : {changes}',
    fieldSet: '{field} : {value}',
    fieldChanged: '{field} passé à {value}',
    fieldCleared: '{field} vidé',
    // les deux mêmes énoncés SANS la valeur — pour le seul cas où la nommer répéterait le nom de
    // la ligne elle-même (« Pfeil : Abschluss : Pfeil », voir lib/drawingEdit)
    fieldSetPlain: '{field} défini',
    fieldChangedPlain: '{field} modifié',
    labelSet: 'Étiquette «{value}»',
    labelCleared: 'Étiquette retirée',
    floorSet: 'Étage {value}',
    floorCleared: 'Étage retiré',
    floorRangeSet: 'Étages {from} – {to}',
    floorRangeCleared: 'Plage d\'étages retirée',
    countSet: 'Nombre {n}',
    spreadSet: 'Propagation saisie',
    spreadCleared: 'Propagation retirée',
    noteWritten: 'Note «{value}»',
    notesCleared: 'Note vidée',
    drawingLabelSet: '{kind} «{value}»',
    gpsReverted: '{name} : revenu à l\'état sur place ({time}), libéré de {vehicle}',
    gpsRevertedBare: '{name} : revenu à l\'état sur place ({time})',
    gpsReleasedOnSite: '{name} : libéré de {vehicle} sur place, trajet supprimé',
    gpsReleasedOnSiteBare: '{name} : libéré sur place, trajet supprimé',
    drawingLabelCleared: '{kind} : étiquette retirée',
    drawKinds: {
      area: 'Surface',
      line: 'Ligne',
      circle: 'Cercle de barrage',
    },
  },
  objectDone: {
    word: {
      fire: { title: 'Éteint', inline: 'éteint' },
      other: { title: 'Terminé', inline: 'terminé' },
    },
    action: 'Terminé',
    actionHint: 'reste visible en gris',
    state: '{word} {time}',
    reopen: 'De nouveau actif',
    removeHint: 'seulement en cas d’erreur',
    logDone: '{name} : état {word}',
    logReopened: '{name} : état actif',
  },
  addSheet: { tile: 'Ajouter', tools: 'Dessin & équipe' },
  toolDock: {
    colorGroup: 'Couleur',
    colorName: '{group} {n}',
    widthName: 'Épaisseur {n} px',
    autoCommitted: '{name} enregistré',
    autoCommitUndo: 'Annuler',
    draftDiscarded: 'Dessin incomplet abandonné',
  },
}
