// French copy · the symbol / drawing editors, top bar and small controls.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/editors.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'contextPanel' | 'drawingEditor' | 'topBar' | 'stepper' | 'confirm' | 'combo'

export const editorsCopy: Localizable<Pick<Copy, Keys>> = {
  contextPanel: {
    titlePlaceholder: 'Désignation ...',
    floor: 'Étage',
    floorFrom: 'De l’étage',
    floorTo: 'À l’étage',
    floorNone: '–',
    spread: 'Propagation',
    spreadH: 'Horizontale',
    spreadV: 'Verticale',
    spreadBounded: 'Limite',
    spreadBoundedTitle: 'Limite de propagation — propagation stoppée ici',
    spreadDirTitles: { left: 'vers la gauche', right: 'vers la droite', up: 'Étage supérieur (↑)', down: 'Sous-sol (↓)' } as Record<string, string>,
    count: 'Nombre',
    rotation: 'Rotation',
    rotationVehicle: 'Véhicule',
    rotationFan: 'Ventilateur',
    rotationLadder: 'Échelle',
    center: 'Centrer',
    toOriginal: 'Vers l\'original',
    toProjection: 'Afficher sur la surface liée',
    showOnMap: 'Afficher sur la carte',
    showOnPlan: 'Afficher sur {plan}',
    resetGps: 'GPS',
    resetGpsTitle: 'Réinitialiser sur la position et le cap GPS',
    pinGps: 'Fixer ici',
    pinGpsTitle: 'Fixer le véhicule ici – le symbole reste en place même s’il repart',
    logPinned: '{name} fixé',
    driverLabel: 'Conducteur',
    driverPlaceholder: 'Nom',
    rotateHint: 'Tirer la poignée pour orienter',
    notes: 'Notes',
    notesPlaceholder: 'Notes générales …',
    addField: 'Ajouter un champ',
    addFieldShort: 'Champ',
    removeField: 'Supprimer le champ',
    fieldKeyPlaceholder: 'Désignation',
    fieldNamePlaceholder: 'Nom …',
    fieldValuePlaceholder: '{label} …',
    duplicateField: '«{key}» existe déjà – seule la dernière valeur est conservée.',
    stoffSearch: 'Rechercher ou saisir une substance …',
    unHazardTitle: 'Matières dangereuses (ADR)',
    adrMeanings: {
      '1': 'Matières explosibles',
      '1.4': 'Matières explosibles (danger mineur)',
      '1.5': 'Matières explosibles (très peu sensibles)',
      '1.6': 'Matières explosibles (extrêmement peu sensibles)',
      '2': 'Gaz',
      '2.1': 'Gaz inflammable',
      '2.2': 'Gaz ininflammable, non toxique',
      '2.3': 'Gaz toxique',
      '3': 'Liquides inflammables',
      '4.1': 'Matières solides inflammables',
      '4.2': 'Matières sujettes à l’inflammation spontanée',
      '4.3': 'Dégage des gaz inflammables au contact de l’eau',
      '5.1': 'Matières comburantes',
      '5.2': 'Peroxydes organiques',
      '6.1': 'Matières toxiques',
      '6.2': 'Matières infectieuses',
      '7': 'Matières radioactives',
      '7E': 'Matières radioactives (fissiles)',
      '7X': 'Matières radioactives',
      '8': 'Matières corrosives',
      '9': 'Marchandises dangereuses diverses',
      '9A': 'Piles au lithium',
    } as Record<string, string>,
    packingGroups: { I: 'danger élevé', II: 'danger moyen', III: 'danger faible' } as Record<string, string>,
    unClass: 'Classe',
    unKemler: 'Numéro de danger',
    unLabels: 'Étiquettes de danger',
    unPacking: 'Groupe d’emballage',
    unNoMatch: 'N° ONU introuvable dans la table ADR',
    unWater: 'Réagit dangereusement avec l’eau – NE PAS utiliser d’eau !',
    unLookupLabel: 'Fiche ERI (Cefic)',
    unLookupUrl: 'https://www.ericards.net/psp/ericards.psp_search_result?p_lang=2&lang=2&unnumber={un}',
    kemler: {
      '2': 'Gaz (fuite sous pression ou par réaction)',
      '3': 'Liquide / gaz inflammable',
      '4': 'Solide inflammable',
      '5': 'Comburant (intensifie le feu)',
      '6': 'Toxique / risque d’infection',
      '7': 'Radioactif',
      '8': 'Corrosif',
      '9': 'Risque de réaction violente spontanée',
    } as Record<string, string>,
    kemlerDoubled: 'Danger renforcé (chiffre doublé)',

    labelField: 'Désignation',
    countBySymbol: {
      'VKF Patientensammelstelle': 'Nombre de patients',
      'VKF Sanitaetshilfsstelle': 'Nombre de patients',
      'FW Verwundetennest': 'Nombre de blessés',
      'VKF Totensammelstelle': 'Nombre de décédés',
      'VKF Sammelstelle': 'Nombre d\'indemnes',
      'VKF Rettungen': 'Nombre de personnes',
    },
    airflow: 'Sens de l\'air',
    airflowBlow: 'Soufflage',
    airflowExtract: 'Aspiration',
    stopSharing: 'Retirer la position',
    stopSharingTitle: 'Retirer la position auto-déclarée de cette personne. Elle peut la repartager à tout moment ensuite.',
    stopSharingFailed: 'La position n\'a pas pu être retirée.',
    caption: 'Étiquette',
    captionDefault: 'Standard',
    captionOff: 'Aucune',
    captionAuto: 'Auto',
    captionAll: 'Toutes',
    swapEl: 'Transmettre la conduite',
    fieldPlaceholders: {
      'Kapazität': 'p. ex. 80 m³',
    },
    ergGuide: 'Guide ERG',
    ergPolymerization: 'Risque de polymérisation (P) – le récipient peut éclater violemment',
    ergIsolate: 'Isolement (petite quantité)',
    ergProtectDay: 'Distance de protection, jour',
    ergProtectNight: 'Distance de protection, nuit',
    ergLarge: 'Grande quantité',
    ergTable3: 'voir ERG tableau 3 (récipient/vent)',
    ergDayShort: 'Jour',
    ergNightShort: 'Nuit',
    ergSunrise: 'lever du soleil {t}',
    ergSunset: 'coucher du soleil {t}',
    dockedTo: 'Amarré à «{name}»',
    dockedRelease: 'Détacher',
    ergAdopt: 'Reprendre comme périmètre',
    ergRingsLabel: 'Rayon sur la carte',
    ergRingsOff: 'Non',
    ergRingsSmall: 'Petit',
    ergRingsLarge: 'Grand',
    ergSource: 'Source : {v} (PHMSA) – aide à la planification, non validée',
    ergCameoLabel: 'CAMEO Chemicals (détails ERG)',
  },
  drawingEditor: {
    area: 'Surface',
    drawing: 'Dessin',
    circle: 'Périmètre de sécurité',
    radius: 'Rayon',
    fill: 'Remplissage',
    fillHatch: 'Hachuré',
    move: 'Déplacer',
    moveArmed: 'Déplacement actif – glisser n’importe où',
    rotateArmed: 'Rotation active – glisser n’importe où',
    selectionBar: 'Sélection',
    points: 'Points',
    color: 'Couleur',
    width: 'Épaisseur',
    lineStyle: 'Ligne',
    lineSolid: 'Continue',
    lineDashed: 'Pointillée',
    lineHalteliniUp: 'Ligne d’arrêt – dents au-dessus',
    lineHalteliniDown: 'Ligne d’arrêt – dents en dessous',
    lineAbwurfzone: 'Zone de largage',
    label: 'Texte',
    labelPlaceholder: 'Libellé …',
    areaLabelPlaceholder: 'p. ex. Secteur A',
    abschnittLeiter: 'Chef de secteur',
    abschnittLeiterPlaceholder: 'Choisir le chef de secteur …',
    abschnittAuftrag: 'Mission',
    abschnittAuftragPlaceholder: 'p. ex. Lutte contre le feu bâtiment B',
    abschnittMaxHint: 'Directive CSP : au plus 3–4 secteurs.',
    marker: 'Marqueur',
    markerPlaceholder: 'p. ex. R',
    arrow: 'Pointe de flèche',
    ending: 'Terminaison',
    endingNone: 'Aucune',
    endingArrow: 'Flèche',
    endingArrowStop: 'Flèche avec arrêt',
    endingTeilstueck: 'Tronçon',
    endingNoneWhat: 'Sans terminaison',
    endingArrowWhat: 'Pointe de flèche',
    endingArrowStopWhat: 'Flèche avec barre d’arrêt — limite de propagation',
    endingTeilstueckWhat: 'Teilstück — fourche à trois raccords',
    reverse: 'Inverser le sens',
    content: 'Type',
    contentPlain: 'Eau',
    lineNo: 'Conduite n°',
    lineNoDuplicate: 'La conduite {n} existe déjà ici',
    trupp: 'Appartient à l’équipe',
    truppShow: 'Montrer l’équipe {name}',
    truppNone: 'Aucune équipe',
    truppOut: 'sortie',
    floorTag: 'Étage',
    distance: 'Longueur',
    measurement: 'Mesure',
    showOnMap: 'Sur la carte',
    inputMode: 'Saisie',
    modeFreehand: 'Main levée',
    modeNodes: 'Points',
    on: 'Activé',
    off: 'Désactivé',
    lock: 'Verrouiller',
    lockHint: 'Verrouille la forme contre les déplacements accidentels ; maintenez le verrou au centre pour déverrouiller.',
    unlockHold: 'Maintenir pour déverrouiller',

    connections: 'Connexions',
    connectedStart: 'Début',
    connectedEnd: 'Fin',
    connectedLines: 'Lignes connectées ({n})',
    line: 'Ligne',
    lineLabelNo: 'Ligne {n}',
    route: 'Tracé',
    routeDirect: 'Direct',
    routeTrace: 'Trace',
    detachConnection: 'Libérer la connexion',
    gpsFollowing: 'Le GPS suit activement',
    gpsMovingAway: 'Le véhicule s\'éloigne',
    gpsContinue: 'Continuer à suivre',
    gpsDetachOnSite: 'Libérer sur le lieu d\'intervention',
    gpsDetachHere: 'Libérer ici (garder le tracé)',
    gpsDismiss: 'Masquer',
    gpsPause: 'Arrêter le suivi',
    gpsAwayTitle: '{vehicle} s\'éloigne · {distance} du lieu d\'intervention',
    gpsAwayTitleBare: '{vehicle} s\'éloigne',
    gpsAwaySub: '{lines} se termine encore sur le lieu d\'intervention.',
    gpsAwaySubMany: '{lines} se terminent encore sur le lieu d\'intervention.',
    gpsKeepOnSite: 'Laisser sur place',
    gpsStoppedTitle: '{vehicle} · {distance} du lieu d\'intervention',
    gpsStoppedTitleBare: '{vehicle} · suivi arrêté',
    gpsStoppedSub: 'Suivi arrêté · {lines} montre le trajet.',
    gpsStoppedSubMany: 'Suivi arrêté · {lines} montrent le trajet.',
    gpsBackTitle: '{vehicle} de retour sur le lieu d\'intervention',
    gpsBackSub: '{lines} montre le trajet depuis {time}.',
    gpsBackSubMany: '{lines} montrent le trajet depuis {time}.',
    gpsRevert: 'Revenir à l\'état sur place',
    gpsRevertAt: 'Revenir à l\'état sur place ({time})',
    gpsRevertStep: '{name} revenu à l\'état sur place',
    gpsFollowingHead: '{line} · suit {vehicle} depuis {time}',
    gpsFollowingHeadBare: '{line} · suit {vehicle}',
    gpsStoppedHead: '{line} · suivi arrêté · {vehicle}',
    gpsDistanceNow: 'actuellement à {distance}',
    hiddenTarget: 'Cible masquée',
    revealTarget: 'Afficher la couche',
    removeConnectedTitle: 'Retirer {name} ?',
    removeConnectedMessage: '{n} lignes seront libérées.',
    removeEMessage: 'Supprimer le tronçon ? {n} lignes raccordées seront libérées.',
  },
  topBar: {
    offline: 'Hors ligne',
    tiles: 'Tuiles',
    recording: 'REC',
    gpsFrozen: 'GPS figé',
    gpsFrozenHint: 'Le flux GPS en direct ne répond plus. Les véhicules restent à leur dernière position connue.',
  },
  stepper: {
    less: 'moins',
    more: 'plus',
    reset: 'réinitialiser',
    typeToEnter: 'Toucher pour saisir',
  },
  confirm: {
    ok: 'OK',
    cancel: 'Annuler',
  },
  combo: {
    empty: 'Aucun choix',
    searchPlaceholder: 'Rechercher une personne …',
    searchOrType: 'Rechercher ou saisir …',
    useTyped: 'Utiliser «{name}»',

    officersOnly: 'officiers seulement',
  },
}
