// French copy · incident switcher, archive, history, Abschluss, data sources, replay.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/incident.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'incidentSwitcher' | 'archived' | 'history' | 'abschluss' | 'datenquellen' | 'personnelSync'
  | 'planPicker' | 'replay'

export const incidentCopy: Localizable<Pick<Copy, Keys>> = {
  incidentSwitcher: {
    noIncident: 'Aucune intervention',
    savedAt: 'Enregistré à {t}',
    saved: 'Enregistré',
    badgePending: 'Non synchronisé – enregistrement en cours',
    badgeOffline: 'Hors ligne – enregistré localement, se synchronise dès la reconnexion',
    badgeError: 'Échec de la synchro – enregistré localement, nouvel essai',
    badgeStorage: 'Stockage plein – les modifications ne sont PAS enregistrées localement et seront perdues à la fermeture',
    storageShort: 'Stockage plein',
    syncNow: 'Synchroniser maintenant',
    incidents: 'Interventions',
    app: 'Application',
    allIncidents: 'Toutes les interventions',
    editMetaShort: 'Modifier',
    archiveShort: 'Clore',
    archive: 'Clore l\u2019intervention',
    archiveOpen: '{n} en suspens',
    share: 'Partager l’intervention',
    shareShort: 'Transmettre',
    report: 'Rapport d’intervention',
    noOpenIncidents: 'Aucune intervention ouverte',
    logout: 'Déconnexion',
    logoutTitle: 'Se déconnecter ?',
    logoutMsg: 'Cet appareil n’ouvrira ensuite des interventions qu’après une connexion avec PIN.',
    logoutOffline: 'Une nouvelle connexion n’est possible qu’avec le réseau – d’ici là, cet appareil n’ouvre aucune intervention.',
    logoutUnsyncedOne: '1 entrée n’a pas encore été transmise. Elle reste sur cet appareil et sera envoyée dès ta prochaine connexion.',
    logoutUnsyncedMany: '{n} entrées n’ont pas encore été transmises. Elles restent sur cet appareil et seront envoyées dès ta prochaine connexion.',
    logoutUnsyncedChanges: 'Des modifications n’ont pas encore été transmises. Elles restent sur cet appareil et seront envoyées dès ta prochaine connexion.',
    appVersion: 'Version de l’app (build)',

    startedRow: '{t} · {d}',
    startedFull: 'Début de l\'intervention {t} · {d}',
    offlineShort: 'Hors ligne',
    errorShort: 'Erreur de sync',
    syncErrorToast: 'Échec de la synchronisation – les modifications sont enregistrées localement.',
    syncOfflineToast: 'Toujours hors ligne – les modifications sont enregistrées localement.',
    clockSkewToast: 'L\'horloge de cet appareil dévie de {n} minutes – vérifie les heures saisies.',
    bootOffline: 'Hors ligne – les données enregistrées sont affichées.',
    bootListFailed: 'La liste des interventions n\'a pas pu être chargée',
    openFailed: 'L\'intervention n\'a pas pu être ouverte',
    openFailedNoCache: 'Cette intervention n\'est pas enregistrée sur cet appareil – connexion nécessaire',
    syncDone: 'Tout est synchronisé',
    syncFailedToast: 'Échec de la synchronisation – les modifications restent enregistrées localement.',
    editMeta: 'Modifier les données de l\'intervention',
  },
  archived: {
    title: 'Intervention close',
    hint: 'Le rapport reste corrigeable (ajouts) – rouvrir pour tout le reste.',
    hintViewOnly: 'Consultation seule.',
    reactivate: 'Rouvrir',
    reactivateOffline: 'Nécessite une connexion au serveur',
    reactivateNeedsServer: 'La réouverture nécessite une connexion au serveur – l’intervention reste close. Réessayer une fois en ligne.',

    back: 'Retour',
    closedElsewhere: 'L’intervention a été close sur un autre appareil ({t})',
    closedElsewhereSub: 'Le rapport reste corrigeable (ajouts) – rouvrir pour tout le reste.',
    closedRefusedOne: '1 entrée de cet appareil est arrivée après la clôture et n’a pas été reprise. Elle reste enregistrée sur cet appareil.',
    closedRefused: '{n} entrées de cet appareil sont arrivées après la clôture et n’ont pas été reprises. Elles restent enregistrées sur cet appareil.',
    closedExport: 'Exporter les entrées',
    closedDismiss: 'Masquer l’avis',
    reopenedElsewhere: 'L’intervention a été rouverte sur un autre appareil ({t})',
    rapportClosedHint: 'Intervention close – les modifications du rapport apparaissent comme ajouts.',
    linkClosedTitle: 'Intervention close – ce tableau ne fait plus qu’afficher',
    linkRefusedTitle: 'Ce lien n’est plus valable – ce tableau ne fait plus qu’afficher',
    reopenedElsewhereSub: 'De nouveau modifiable – les entrées ultérieures apparaissent comme ajouts.',
    reopenedParkedOne: 'De nouveau modifiable. 1 entrée de cet appareil non reprise après la clôture est envoyée maintenant – comme ajout.',
    reopenedParked: 'De nouveau modifiable. {n} entrées de cet appareil non reprises après la clôture sont envoyées maintenant – comme ajouts.',
  },
  history: {
    title: 'Interventions',
    empty: 'Aucune intervention pour le moment.',
    noLocation: 'sans lieu',
    searchPlaceholder: 'Rechercher une intervention …',
    groupOpen: 'Ouvertes',
    groupToday: 'Aujourd\u2019hui',
    groupWeek: '7 derniers jours',
    offlineNote: 'Hors ligne : la consultation fonctionne ; clore et rouvrir nécessitent une connexion au serveur.',
    since: 'depuis {t}',
    reactivate: 'Rouvrir',
    reactivateConfirmTitle: 'Rouvrir l\u2019intervention',
    reactivateConfirmMsg: 'L’intervention est rouverte et modifiable. Les modifications ultérieures apparaissent dans le journal et le rapport comme compléments.',
    reactivateConfirmBtn: 'Rouvrir',
    statusArchived: 'Close',

    emptySub: 'Les interventions ouvertes et closes apparaissent ici.',
    archiveConfirmTitle: 'Clôturer l\'intervention',
    archiveConfirmMsg: 'L\'intervention est close et l\'heure de fin enregistrée. Les ajouts ultérieurs apparaissent dans le journal et le rapport comme compléments.',
    archiveConfirmBtn: 'Clôturer',
    deleteExercise: 'Supprimer',
    deleteConfirmTitle: 'Supprimer l\'exercice',
    deleteConfirmMsg: 'L\'exercice et toutes ses données (journal, photos, rapport) sont définitivement supprimés. Cela ne peut pas être annulé.',
    deleteConfirmBtn: 'Supprimer définitivement',
    deleted: 'Exercice supprimé',
    deleteFailed: 'Échec de la suppression',
  },
  abschluss: {
    leftEarly: ' · jusqu’à {t}',
    steps: {
      zeiten: 'Horaires',
      anwesenheit: 'Présences',
      mittel: 'Matériel',
      einsatzleiter: 'Chef d’intervention',
      kurzbericht: 'Rapport succinct',
      rueckmeldung: 'Retour à la CET',
      abweichungen: 'Divergences',

      kontaktperson: 'Personne de contact',
    },
    ausgerueckt: 'Départ',
    ende: 'Fin d’intervention',
    personen: '{n} présents',
    von: 'de',
    bis: 'à',
    mittelCount: '{n} positions',
    mittelNone: 'Rien utilisé',
    complete: 'Clore l’intervention',
    backToRapport: 'Retour au rapport',
    confirmTitle: 'Clore l’intervention',
    confirmMsg: 'Le rapport est marqué comme clos et l’intervention close. Les corrections restent possibles et apparaissent comme addenda.',
    confirmBtn: 'Clore',
    confirmAnyway: 'Clore quand même',
    registeredOne: '1 binôme encore annoncé ({list}).',
    registeredMany: '{n} binômes encore annoncés ({list}).',
    registeredSafety: '{name}, équipe de sécurité',
    registeredToBoard: 'Vers le tableau',
    registeredTitle: 'Encore annoncé',
    registeredStandDown: 'Clore comme « pas engagé »',
    insideOne: '1 binôme est encore engagé : {list}.',
    insideMany: '{n} binômes sont encore engagés : {list}.',
    insideTrupp: 'Binôme {name}',
    insideClose: 'Clore quand même',
    insideTitle: 'Binômes encore engagés',
    confirmBack: 'Retour',
    done: 'Rapport clos',
    doneMediaPending: 'Rapport clôturé · {n} photo/audio pas encore envoyé – conservé et transmis à la prochaine ouverture',
    failed: 'Échec de la clôture',
    corrected: 'Heures corrigées : {name}',
    attendanceRemoved: 'Présence de {name} retirée',
  },
  datenquellen: {
    title: 'Sources de données',
    uploaded: 'Téléversé',
    uploadFailed: 'Échec du téléversement',
    invalidFilename: 'Le nom de fichier ne donne pas d’identifiant valide',
    layerAdded: 'Couche « {name} » ajoutée – visible au prochain chargement',
    addLayerFailed: 'Impossible d’ajouter la couche',
    layerConflict: 'Les couches cartographiques viennent d’être modifiées ailleurs. Appuyer à nouveau sur « Ajouter ».',
    layerNoVersion: 'La configuration n’a pas pu être lue – la couche n’a pas été enregistrée. Merci de vérifier la connexion et de recharger la page.',
    globalDatasets: 'Jeux de données globaux',
    objectsCount: 'objets',
    replace: 'Remplacer',
    adminOnlyNote: 'Remplacer un jeu de données ou ajouter une couche exige que /admin soit déverrouillé dans ce navigateur (ADMIN_SECRET).',
    newGeoLayer: 'Nouvelle couche géo …',
    chooseGeojson: 'Choisir un GeoJSON …',
    labelPlaceholder: 'Désignation (p. ex. hydrantes)',
    groupPlaceholder: 'Groupe (p. ex. eau)',
    defaultGroup: 'Référence',
    kindLines: 'Lignes',
    kindPoints: 'Points',
    color: 'Couleur',
    adding: 'Chargement …',
    add: 'Ajouter',
    geojsonNoteBefore: 'GeoJSON en WGS84 [lng, lat]. Enregistré comme jeu de données global ',
    geojsonNoteAfter: '.',
    incidentObjects: 'Objets d’intervention',
    plansWord: 'plans',
    nearby: 'À proximité ({n})',
    allOther: 'Tous les autres objets',
    allObjects: 'Tous les objets',
  },
  personnelSync: {
    title: 'Synchroniser l’effectif avec {provider}',
    unknownError: 'Erreur inconnue',
    syncFailed: 'Échec de la synchronisation',
    countNew: 'nouveau(x)',
    countUpdated: 'mis à jour',
    countUnchanged: 'inchangé(s)',
    countStale: 'plus chez {provider}',
    querying: 'Interrogation de {provider} …',
    done: 'Synchronisation terminée.',
    resultCreated: '{n} créé(s)',
    resultUpdated: '{n} mis à jour',
    resultReactivated: ' (dont {n} réactivé(s))',
    resultUnchanged: '{n} inchangé(s)',
    resultDeactivated: '{n} désactivé(s)',
    staleHide: 'Masquer {n} personnes qui ne sont plus présentes chez {provider} (conservées pour les anciennes interventions, non supprimées)',
    syncing: 'Synchronisation …',
    sync: 'Synchroniser',
  },
  planPicker: {
    searchPlaceholder: 'Rechercher un nom ou une adresse …',
    autoNextObject: 'Objet le plus proche automatiquement',
    loading: 'Chargement des objets …',
    loadFailed: 'Les objets n’ont pas pu être chargés.',
    noObject: 'Aucun objet trouvé.',
    planOne: 'plan',
    planMany: 'plans',
    mapNote: 'Coordonnées parfois imprécises – la liste fait foi.',
    hideMap: 'Masquer la carte',
    showMap: 'Afficher la carte',
  },
  replay: {
    region: 'Relecture du journal',
    banner: 'JOURNAL · RELECTURE',
    subtitle: 'Vue du passé en lecture seule',
    backToLive: 'Retour au direct',
    loadFailed: 'Le journal n’a pas pu être chargé.',
    loading: 'Chargement du journal …',
    transport: 'Lecture',
    skipBack: 'Événement précédent',
    skipFwd: 'Événement suivant',
    skipped: '{span} ignorées',
    gapTitle: '{span} sans événement',
    sinceAlarm: '{span} depuis l’alarme',
    pause: 'Pause',
    speed: 'Vitesse',
    timepoint: 'Instant',
    now: 'Maintenant',
    laneLabel: 'Journal',
    captionOpen: 'dans le journal',
    laneEntries: '{n} entrées',
    captionNone: 'Aucune entrée à cet instant',
  },
}
