// French copy · the Einsatz wizard (intake).
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/intake.ts.

import type { Copy, Localizable } from '../index'

export const intakeCopy: Localizable<Pick<Copy, 'intake'>> = {
  intake: {
    titleNew: 'Ouvrir une intervention',
    locationHead: 'Lieu',
    addressLabel: 'Adresse',
    addressPlaceholder: 'Rue n°, NPA localité',
    addressSearching: 'Recherche …',
    addressNoHits: 'Aucune adresse trouvée',
    objectButton: 'Des plans',
    objectSearchPlaceholder: 'Rechercher un objet ou une adresse …',
    objectNear: 'À proximité',
    objectNoHits: 'Aucun objet trouvé',
    objectPlans: (n: number) => (n === 1 ? '1 plan' : `${n} plans`),
    objectNoPlans: 'aucun plan',
    mapPickButton: 'Sur la carte',
    coordSet: 'Coordonnée définie',
    coordNone: 'Aucun lieu – sera ouverte sans coordonnée',
    coordClear: 'Retirer le lieu',
    coordFold: 'Coordonnées',
    keywordHead: 'Mot-clé et catégorie',
    titleLabel: 'Mot-clé / titre',
    titlePlaceholder: 'p. ex. Incendie de bâtiment, école',
    categoryLabel: 'Catégorie',
    detailsPlaceholder: 'Indications supplémentaires sur le message',
    open: 'Ouvrir l’intervention',
    opening: 'Ouverture …',
    cancel: 'Annuler',
    errorCreate: 'Échec de la création',
    errorTake: 'Échec de la reprise',
    errorUpdate: 'Échec de la mise à jour',
    editTitle: 'Modifier les données d’intervention',
    save: 'Enregistrer',
    saving: 'Enregistrement …',
    created: 'Intervention créée',
    taken: 'Alarme reprise',
    updated: 'Intervention mise à jour',
    alarmierungHead: 'Alarme',
    alarmTime: 'Heure d’alarme',
    alarmMessage: 'Message d’alarme',
    addressUnknown: 'Adresse inconnue',
    alarmOpen: 'Ouvrir',
    alarmOpening: 'Ouverture …',
    dismiss: 'Écarter',
    manualIncident: 'Intervention manuelle',
    attach: 'Ajouter \u00e0 une intervention existante',
    attachShort: '\u00c0 l\u2019intervention',
    attachConfirmTitle: 'Ajouter « {alarm} » à cette intervention ?',
    attachHint: 'Le message d\u2019alarme est consign\u00e9 dans le journal, les temps GPS suivent automatiquement. Le mot-cl\u00e9 et le lieu de l\u2019intervention restent inchang\u00e9s.',
    attachConfirm: 'Ajouter',
    attachDone: 'Alarme ajout\u00e9e \u00e0 l\u2019intervention',
    attachError: '\u00c9chec de l\u2019ajout',
    newDiveraAlarm: 'Nouvelle alarme',
    hide: 'Masquer',
    fromDivera: 'Repris depuis la source d’alarme',
    reviewTitle: 'Vérifier les données de l’intervention',
    locationSet: 'Lieu défini',
    noLocationOnMap: 'Aucun lieu – placer sur la carte',
    ok: 'Ça convient',
    // Libellés d'AFFICHAGE de la liste des catégories — la valeur soumise reste l'allemand.
    kategorienLabels: {
      'Brandbekämpfung': 'Lutte contre l\'incendie',
      'Strassenrettung': 'Désincarcération',
      'Technische Hilfeleistung': 'Aide technique',
      'Elementarereignis': 'Intempéries',
      'Ölwehr': 'Lutte antipollution (hydrocarbures)',
      'Chemiewehr': 'Intervention chimique',
      'Strahlenwehr': 'Intervention radiologique',
      'Einsatz Bahnanlagen': 'Intervention ferroviaire',
      'BMA / unechte Alarme': 'DAI / fausses alarmes',
      'Gerettete Tiere': 'Sauvetage d\'animaux',
      'Dienstleistungen': 'Prestations de service',
      'Diverse Einsätze': 'Interventions diverses',
    },

    hereButton: 'Ici',
    hereFailed: 'Position indisponible',
    exerciseNo: 'Non',
    exerciseYes: 'Oui',
    exerciseLabel: 'Exercice',
    exerciseSub: 'Ne compte pas dans la statistique d\'intervention',
    moveConfirmTitle: 'Déplacer le lieu d\'intervention ?',
    moveConfirmMsg: 'Le lieu d\'intervention sera placé sur ta position actuelle – à {d} de l\'ancienne. La carte, le cadrage du croquis et les plans d\'objet à proximité s\'y adaptent.',
    moveConfirmBtn: 'Déplacer',
    alarmTextUnavailable: 'Le message d\'alarme n\'a pas pu être chargé – il reste inchangé',
    demoBlocked: 'Désactivé dans la démo – impossible d\'ouvrir une nouvelle intervention ici.',
  },
}
