// French copy · the Verlauf / journal and error sentences.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/journal.ts.

import type { Copy, Localizable } from '../index'

export const journalCopy: Localizable<Pick<Copy, 'journal' | 'errors'>> = {
  journal: {
    delivery: {
      failedTitleOne: '1 entrée non transmise',
      failedTitle: '{n} entrées non transmises',
      storageTitle: 'Entrées non enregistrées de manière sûre',
      storageBody: 'Gardez l’application ouverte et enregistrez une copie. Fermer l’application peut entraîner la perte de ces entrées.',
      savedBody: 'Enregistrées sur cet appareil. Ces entrées manquent sur les autres appareils.',
      offlineBody: 'Enregistrées sur cet appareil. La transmission reprend automatiquement dès qu’une connexion est disponible.',
      retry: 'Réessayer', retrying: 'Nouvelle tentative …', export: 'Exporter les entrées', short: 'Entrées non transmises',
      refusedTitleOne: '1 événement de protocole non prévu pour ce rôle',
      refusedTitle: '{n} événements de protocole non prévus pour ce rôle',
      refusedBody: 'Le serveur n’accepte pas ces événements de cette connexion. Ils restent sur cet appareil et peuvent être exportés ; le journal n’est pas concerné.',
      closedTitleOne: '1 entrée non reprise après la clôture',
      closedTitle: '{n} entrées non reprises après la clôture',
      closedBody: 'L’intervention était déjà close lorsque ces entrées ont atteint le serveur. Elles ne figurent pas dans le journal, mais restent sur cet appareil et peuvent être exportées. Si l’intervention est rouverte, elles sont envoyées.',
      closedShort: 'Entrées non reprises après la clôture – les exporter',
    },
    open: 'Journal',
    add: 'Entrée',
    addHint: 'Toucher pour une entrée · maintenir, puis glisser sur mémo vocal ou photo',
    title: 'Journal',
    empty: 'Aucun événement enregistré',
    surfaceMap: 'Carte',
    surfacePlan: 'Plan',
    replay: 'Démarrer la relecture',
    replayHint: 'Rejouer situation et plan à un instant antérieur',
    composerTitle: 'Nouvelle entrée',
    textPlaceholder: 'Que s’est-il passé ? Message, observation, décision …',
    typeLabel: 'Type',
    entryTypes: { info: 'Info', auftrag: 'Ordre', sofort: 'Mesure immédiate' } as Record<string, string>,
    entryTypesWrap: { info: 'Info', auftrag: 'Ordre', sofort: 'Mesure immédiate' } as Record<string, string>,
    record: 'Enregistrer',
    recordStop: 'Arrêter l’enregistrement',
    discardAudio: 'Abandonner l’enregistrement',
    attachUpload: 'Téléverser un fichier',
    attachUploadShort: 'Fichier',
    attachLabel: 'Annexe',
    attachDiscard: 'Retirer l’annexe',
    attachOpen: 'Télécharger l’annexe',
    attachOffline: 'Le téléversement nécessite une connexion. Resélectionner le fichier plus tard.',
    attachTooLarge: 'Fichier trop volumineux. Maximum : {max} MB.',
    attachUnsupported: 'Ce type de fichier n’est pas pris en charge.',
    attachUploadFailed: 'Échec du téléversement du fichier. Vérifier la connexion et réessayer.',
    attachDropped: 'Annexe «{name}» abandonnée – à sélectionner de nouveau.',
    attachPrint: 'Annexe : {names}',
    attachPrintMany: 'Annexes : {names}',
    attachAudioExtra: 'Un seul enregistrement par entrée – «{names}» non repris.',
    audioClipLabel: 'Note vocale',
    audioImportLabel: 'Enregistrement audio externe',
    audioStartLabel: 'Début de l’enregistrement',
    audioStartHint: 'Vérifier l’heure de début à l’aide du mémo vocal.',
    audioStartConfirm: 'Confirmer l’heure de début',
    audioImportedNote: 'Enregistrement audio externe ({duration})',
    audioDiscardImport: 'Supprimer le fichier audio',
    audioUploading: 'Téléversement …',
    audioOffline: 'Le téléversement audio nécessite une connexion. Resélectionner le fichier plus tard.',
    audioTooLarge: 'Fichier audio trop volumineux. Maximum : {max} MB.',
    audioUnsupported: 'Ce format audio n’est pas pris en charge.',
    audioUploadFailed: 'Échec du téléversement. Vérifier la connexion et réessayer.',
    audioImportDropped: 'Enregistrement audio externe «{name}» abandonné – à sélectionner de nouveau.',
    playerOpen: 'Réécouter',
    editEntry: 'Modifier le texte',
    removeEntry: 'Supprimer l’entrée',
    entryRemoved: 'Entrée supprimée',
    playerEntryHere: 'Entrée à cet endroit',
    playerEntryPlaceholder: 'Qu’a-t-on entendu ? Message, décision …',
    playerEntries: 'Entrées dans cet enregistrement',
    playerNoEntries: 'Aucune entrée dans cette fenêtre pour l’instant.',
    playerSkipBack: '15 secondes en arrière',
    playerSkipFwd: '15 secondes en avant',
    playerSpeed: 'Vitesse de lecture',
    playerSeek: 'Position de lecture',
    playerOffline: 'La lecture nécessite une connexion.',
    sttTranscribe: 'Transcrire',
    sttRunning: 'Transcription en cours … Cela peut prendre quelques minutes.',
    sttFailed: 'Échec de la transcription : {error}',
    sttRetry: 'Réessayer',
    sttErrorGeneric: 'serveur injoignable',
    sttBanner: '{n} ébauches détectées – vérifier et reprendre.',
    sttTakeAll: 'Tout reprendre',
    sttTake: 'Reprendre',
    sttDismiss: 'Rejeter',
    sttEmpty: 'Aucune parole détectée.',
    photo: 'Photo',
    photoNote: 'Photo',
    discardPhoto: 'Abandonner la photo',
    send: 'Consigner',
    saved: 'Entrée consignée',
    transcriptPlaceholder: 'Compléter la transcription',
    transcriptSave: 'Enregistrer',
    transcriptEdit: 'Modifier la transcription',
    transcriptAdd: 'Compléter la transcription',
    nachtrag: 'Complément',
    corrected: 'corrigé {t}',
    // ⚠️ le nombre TOTAL d’occurrences, celui que le rapport imprime en « N× » — voir la base allemande
    repeated: 'au total {n}×',
    repeatedTitle: 'Nombre total d’occurrences de ce message au procès-verbal – chacune est conservée.',
    correctHint: 'La formulation initiale reste au procès-verbal.',
    viaAtemschutzLink: 'Lien ARI',
    viaAtemschutzLinkTitle: 'Saisi sur le tableau ARI transmis.',
    detailTime: 'Heure',
    detailArea: 'Domaine',
    detailSource: 'Source',
    detailSourceManual: 'Saisi à la main',
    detailSourceSystem: 'Enregistré par l’application',
    detailSourceSystemHint: 'Les lignes système ne sont pas modifiables',
    detailAttachments: 'Annexes',
    detailAttachmentsN: '{n} images',
    detailAttachmentsOne: 'Une image',
    detailCorrected: 'Corrigé',
    detailCorrectedFirst: 'd’abord : {text}',
    detailRepeated: 'Répété',
    detailRepeatedN: 'au total {n}× jusqu’à {t}',
    detailNachtrag: 'Ajout',
    detailNachtragHint: 'saisi après la fin de l’intervention',
    arrowTitle: 'Insérer la flèche – qui à qui',
    arrowBackTitle: 'Insérer la flèche – qui de qui',
    dueHead: 'Rappeler',
    dueNone: 'Sans rappel',
    dueSetTitle: 'Rappel à {t}',
    dueExactTitle: 'Rappeler à',
    dayToday: 'Aujourd’hui',
    dayTomorrow: 'Demain',
    duePast: 'Ce moment est déjà passé',
    reminderExact: 'Heure …',
    reminderChipLabel: 'dans {n} min',
    reminderTomorrow: ' · demain',
    reminderSaved: 'Rappel défini',
    reminderCreated: 'Rappel fixé pour {t} : {text}',
    dueTitle: 'Rappel échu',
    dueOne: 'Rappel échu',
    dueDone: 'Fait',
    dueSnooze: '+10 min',
    dueOpen: 'Ouvrir dans le journal',
    openCount: '{n} ouvert(s)',
    doneLog: 'Rappel fait : {text}',
    reopenLog: 'Rappel rouvert : {text}',
    snoozeLog: 'Rappel +{mins} min : {text}',
    dueAtLabel: 'échéance {t}',
    overdueLabel: 'en retard',
    markDoneTitle: 'Marquer comme fait',
    againChip: '{mins} min',
    againTitle: 'Rappeler dans {mins} minutes',
    legend: 'Légende',
    legendPendenzOpen: 'Point ouvert',
    legendPendenzUrgent: 'Point ouvert – urgent',
    legendPendenzDone: 'Point ouvert – fait',
    search: 'Rechercher dans le journal',
    searchPlaceholder: 'Rechercher …',
    searchClose: 'Fermer la recherche',
    searchCount: '{n} sur {m}',
    searchEmpty: 'Rien pour «{q}»',
    searchEmptyHint: 'La recherche porte sur le texte ainsi que sur les noms des personnes et des binômes. Une faute de frappe est tolérée.',
    filter: 'Filtrer le journal',
    filterArt: 'Type d’entrée',
    filterArea: 'Domaine',
    filterAll: 'Tout afficher',
    filterActive: 'Filtré :',
    filterEmpty: 'Aucune entrée dans cette sélection',
    filterEmptyHint: '«Tout afficher» lève le filtre.',

    stripLabel: 'Frise chronologique – toucher pour sauter à l\'endroit correspondant',
    photoOpen: 'Voir la photo en grand',
    mediaPending: 'Chargement',
    mediaFailed: 'Non chargé',
    attendanceConflict: 'Présence {name} : {what} – merci de vérifier.',
    // ⚠️ Des fragments, pas des phrases : reliés par « · » et insérés dans {what} ci-dessus, qui a
    // déjà écrit « Présence {name} : ». Ce que cette ligne dit déjà ne se répète pas ici.
    attendanceConflictTwoNotes: 'deux fonctions – «{a}» et «{b}»',
    attendanceConflictOneNote: 'fonction «{a}» sur un seul appareil',
    attendanceConflictStatus: 'statut divergent',
    attendanceConflictOrt: 'emplacement divergent',
    attendanceConflictTimes: 'heures divergentes',
    truppConflict: 'Protection respiratoire {name} : modifications de deux appareils fusionnées – merci de vérifier.',
    tafelConflict: 'Tableau «{page}» · {where} : modifié sur deux appareils en même temps – «{kept}» est retenu (plus récent), «{lost}» écrasé. Merci de vérifier.',
    tafelRemovedKept: 'Tableau «{page}» : retiré sur un appareil, puis encore rempli sur un autre – la page reste. Merci de vérifier.',
    tafelRemovedLost: 'Tableau «{page}» retiré – rempli auparavant sur un autre appareil : {cells}. Merci de vérifier.',
    attendanceConflictOther: 'saisies divergentes fusionnées',
    attendanceConflictResolved: 'Divergence {name} vérifiée – {taken}, {by}',
    attendanceConflictByUnknown: 'sans nom',
    attendanceConflictFromKp: 'saisie du poste de commandement',
    attendanceConflictFromCapture: 'saisie de la feuille de présence',
    attendanceConflictKeepBoth: 'les deux saisies sont correctes',
    attendanceConflictOpenEnd: 'ouvert',
    attendanceConflictTake: 'Reprendre {side}',
    attendanceConflictKeep: 'Les deux sont correctes',
    attendanceConflictOpenTitle: 'Divergences',
    attendanceConflictOpenCount: '{n} ouvertes',
    attendanceConflictNoneOpen: 'Aucune ouverte',
    attendanceConflictCheckedAt: 'vérifiée {t} · {by}',
    quickPhrasesAria: 'Formules types',
    openRemindersHead: 'En suspens',
    // le commutateur ○ à côté des chips Art — trois états sur une seule commande
    openStates: ['Garder ouvert', 'Reste ouvert – figure dans les en-suspens', 'Urgent – placé en tête'] as string[],
    pendenzSaved: 'En-suspens enregistré',
    pendenzUrgentSaved: 'En-suspens enregistré – urgent',
    pendenzDoneLog: 'En-suspens terminé : {text}',
    pendenzReopenLog: 'En-suspens rouvert : {text}',
    noteOnTitle: 'Message',
    noteOnLabel: 'sur ',
    noteOnClear: 'Détacher',
    linkPendenzTitle: 'Message sur',
    pendenzNew: 'Nouvel en-suspens',
    pendenzNewUrgent: 'En-suspens urgent',
    pendenzNotOpen: 'Ne pas garder ouvert',
    noteSaved: 'Message enregistré',
    noteChip: 'En suspens',
    noteOpen: 'Saisir un message',
    ageLabel: '{n}′',
    ageLabelHours: '{n} h',
    ageToggle: 'Basculer heure / ancienneté',
    openState: 'ouvert',
    openReminderGo: 'Aller à l\'entrée',
  },
  errors: {
    serverUnreachable: 'Erreur réseau – serveur inaccessible',
    serverTimeout: 'Le serveur ne répond pas – délai dépassé',

    updateFailed: 'Échec de la mise à jour',
    serverUnreachableHint: 'Pas de réseau, ou le serveur n\'est pas à cette adresse. Les interventions enregistrées restent disponibles hors ligne.',
    serverTimeoutHint: 'La connexion tient, mais rien ne revient – typique d\'un Wi-Fi qui s\'éteint. Les interventions enregistrées restent disponibles hors ligne.',
    httpUnauthorized: 'Session expirée',
    httpUnauthorizedHint: 'Merci de te reconnecter.',
    httpForbidden: 'Pas autorisé',
    httpForbiddenHint: 'Ce compte n\'a pas le droit. Connecte-toi avec un compte disposant du droit de modification.',
    httpNotFound: 'Introuvable sur le serveur',
    httpNotFoundHint: 'Le serveur ne connaît pas cette adresse. Il fait peut-être tourner une autre version.',
    httpTooLarge: 'Fichier trop volumineux',
    httpTooLargeHint: 'Le serveur n\'accepte pas de fichiers de cette taille.',
    httpStale: 'Page obsolète',
    httpStaleHint: 'Cette page connaît un état plus ancien. Recharge et refais la modification.',
    httpTooMany: 'Trop de tentatives',
    httpTooManyHint: 'Attends un instant, puis réessaie.',
    httpRejected: 'Requête refusée',
    httpRejectedHint: 'Le serveur a refusé la requête.',
    httpGateway: 'Serveur injoignable',
    httpGatewayHint: 'Le serveur ne répond pas – il redémarre probablement. Réessaie dans un instant ; les interventions enregistrées restent disponibles hors ligne.',
    httpServerError: 'Erreur sur le serveur',
    httpServerErrorHint: 'La requête est arrivée, le serveur n\'a pas su la traiter. Réessaie – si cela persiste, cela ne vient pas de l\'appareil.',
    httpCode: 'Code d\'erreur {code}',
  },
}
