// French copy · the Lagemeldung and the Führungsrhythmus.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/lagemeldung.ts.

import type { Copy, Localizable } from '../index'

export const lagemeldungCopy: Localizable<Pick<Copy, 'lagemeldung'>> = {
  lagemeldung: {
    title: 'Message de situation',
    chip: 'Situation',
    chipIn: 'Situation · dans {m}′',
    chipDue: 'Situation due',
    chipOff: 'Situation · arrêt',
    chipHint: 'Composer un message de situation',
    chipAria: 'Message de situation – {state}',
    modeSeit: 'Depuis {t}',
    modeVoll: 'Complet',
    modeFirst: 'Premier message',
    modeLabel: 'Étendue',
    firstNote: 'Pas encore de message de situation · tout est nouveau',
    seitNote: 'Seulement ce qui a changé depuis {t} · le vital toujours',
    vollNote: 'Tout ce qui vaut – remise, corps voisin, Rück',
    slots: {
      zuerst: 'D\'abord', lage: 'Situation', menschen: 'Personnes', gefahren: 'Dangers', massnahmen: 'Mesures',
      mittel: 'Moyens', bedarf: 'Besoins', naechste: 'Suivant', zusatz: 'En plus',
    } as Record<string, string>,
    tags: {
      neu: 'Nouveau', schlechter: 'Pire', besser: 'Mieux', erledigt: 'Réglé', gleich: 'toujours',
    } as Record<string, string>,
    tagSchaetzung: 'Estimation',
    tagSchaetzungTitle: 'Aide à la planification – estimée d\'après l\'évolution de la pression, pas une mesure',
    tagRegister: 'Registre',
    tagRegisterTitle: 'Indication du registre (RegBL, OFEN) – peut être obsolète, à vérifier sur place',
    tick: 'Inclure dans le message',
    untick: 'Retirer du message',
    dropT0: 'Vital – le retirer quand même ?',
    dropT0Yes: 'Retirer',
    editLine: 'Modifier la ligne',
    editDone: 'Terminé',
    addLine: 'Ligne propre',
    addLinePlaceholder: 'Ce qui doit encore être dit',
    hidden: 'Masqué ({n})',
    hiddenNone: 'Rien de masqué',
    hiddenReasons: {
      gleich: 'inchangé depuis {t}',
      declined: 'omis {t}',
      budget: 'dépasse la durée radio',
      routine: 'routine',
      offer: 'arrière-plan',
      superseded: 'remplacé par «{by}»',
      dispatch: 'la centrale le sait',
      inLine: 'compris dans «{slot}»',
    } as Record<string, string>,
    hiddenAdd: 'Ajouter',
    hiddenAddAria: 'Ajouter «{text}» au message',
    words: '{n} mots',
    seconds: '≈ {s} s',
    overBudget: 'Plus long qu\'un message radio ({n} mots)',
    radio: 'Vue radio',
    radioClose: 'Retour au brouillon',
    share: 'Partager',
    shareCopied: 'Message de situation copié',
    shareFailed: 'Partage impossible',
    more: 'Autres actions',
    send: 'Transmis',
    sendHint: 'Inscrit le message dans le journal et planifie le suivant',
    close: 'Fermer sans enregistrer',
    source: 'Brouillon tiré des groupes, de la carte, du journal, des heures des véhicules · rien n\'est enregistré avant «Transmis»',
    empty: 'Rien de nouveau depuis {t}.',
    emptyFirst: 'Rien encore dans le dossier – compléter situation, personnes, moyens à la main.',
    row: 'Message de situation {t} : {text}',
    rowVoll: 'Message de situation {t} (complet) : {text}',
    sentToast: 'Message de situation {t} au journal',
    undoneLog: 'Message de situation {t} retiré',
    next: 'Prochain message vers {t}.',
    nextHandover: 'Prochain message à la remise.',
    nextNone: 'Pas d\'autre message prévu.',
    rhythm: 'Rythme',
    rhythmEvery: '{m}′',
    rhythmHandover: 'Remise',
    rhythmOff: 'Arrêt',
    rhythmOffAction: 'Arrêter le rythme',
    rhythmOffLog: 'Rythme des messages de situation arrêté',
    rhythmOnLog: 'Rythme des messages de situation {m}′ · prochain {t}',
    rhythmWindDown: 'Feu éteint – espacer le rythme ?',
    nextLog: 'Prochain message de situation à {t}',
    reminderText: 'Message de situation',
    dueTitle: 'Message de situation dû',
    dueLast: 'dernier {t}',
    dueNone: 'pas encore de message de situation',
    dueChanges: '{n} changements',
    dueChangesOne: '1 changement',
    dueUrgent: '{n} urgent(s)',
    dueOpen: 'Message',
    dueSnooze: '+10′',
    phraseOffer: 'Composer le message de situation',
    truppNo: 'Groupe {n}',
    truppBare: 'Groupe',
    truppPressure: '{trupp} pression d\'alarme {bar} bar, retrait{where}.',
    truppContact: '{trupp} en retard, pas de contact radio depuis {m}′{where}.',
    truppEnded: '{trupp} : alarme levée.',
    where: ', {w}',
    vermisstOne: '1 personne disparue{where}.',
    vermisstMany: '{n} personnes disparues{where}.',
    eingesperrtOne: '1 personne bloquée{where}.',
    eingesperrtMany: '{n} personnes bloquées{where}.',
    keineVermissten: 'Plus de personnes disparues.',
    gerettetOne: '1 personne sauvée{extra}.',
    gerettetMany: '{n} personnes sauvées{extra}.',
    anSanitaet: ', remise au service sanitaire',
    geraeumt: 'Bâtiment évacué.',
    keinePersonen: 'Personne dans le bâtiment.',
    un: 'Matière dangereuse ONU {un}{stoff}{dist}.',
    unDist: ', périmètre {m} m',
    unDone: 'Matière dangereuse ONU {un} : réglé.',
    hazard: '{label}{where}.',
    hazardDone: '{label} : réglé.',
    gas: 'Chauffage au gaz dans le bâtiment.',
    oil: 'Chauffage au mazout dans le bâtiment.',
    pv: 'Installation PV sur le toit.',
    gasAb: 'Gaz coupé.',
    stromAb: 'Courant coupé.',
    geschosse: '{n} étages.',
    wind: 'Vent tourné au {dir}.',
    unterKontrolle: 'Feu maîtrisé {t}.',
    feuerAus: 'Feu éteint {t}{extra}.',
    nachloesch: ', déblai en cours',
    lageTitle: '{title}.',
    lageDamage: '{list}.',
    feuerGeloescht: 'Feu éteint {t}.',
    trupps: '{n} groupes engagés : {list}.',
    truppsOne: '1 groupe engagé : {list}.',
    truppsShort: '{n} groupes engagés.',
    truppsShortOne: '1 groupe engagé.',
    sitr: 'Groupe de sécurité prêt.',
    asEnded: 'Protection respiratoire terminée, tous les groupes dehors.',
    bereit: 'Prêt : {list}.',
    mittelOn: '{list} sur place',
    mittelComing: '{list} en route',
    mittelNew: 'nouveau {list}',
    mittelLeft: '{list} rentré',
    mittelShort: '{n} véhicules nouveaux',
    mittelShortOn: '{n} véhicules sur place',
    adf: '{n} sapeurs-pompiers.',
    nachalarm: 'Alarme complémentaire {title}.',
    abloesungJetzt: 'Relève protection respiratoire maintenant.',
    abloesungBald: 'Relève protection respiratoire dans env. {m}′.',
    verstaerkung: 'Renfort demandé, pas encore sur place.',
    bedarfNone: 'plus aucun.',
    bedarfDone: '{text} : réglé.',
    reminderSoon: '{text} ({t}).',
    routineSymbolsOne: '1 entrée de symbole',
    routinePhotosOne: '1 photo',
    routineTeamOne: '1 entrée protection respiratoire',
    routineSymbols: '{n} entrées de symboles',
    routinePhotos: '{n} photos',
    routineTeam: '{n} entrées protection respiratoire',
    routineDispatch: 'Texte d\'alarme',
    routineElTaken: '«Direction d\'intervention reprise»',
  },
}
