// French copy · incident and standing links, shared positions.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/links.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'incidentLink' | 'standingLink' | 'sharePosition' | 'livePosition'

export const linksCopy: Localizable<Pick<Copy, Keys>> = {
  incidentLink: {
    opening: 'Ouverture de l\'intervention …',
    pendingTitle: 'Intervention pas encore disponible',
    pendingHint: 'L\'alarme vient d\'arriver. Nouvelle tentative automatique …',
    notReadyTitle: 'Cette intervention n\'est pas disponible.',
    notReadyHint: 'Le lien n\'est valable que pendant l\'intervention. Si l\'alarme vient d\'arriver, l\'intervention n\'est peut-être pas encore prête – sinon, avertir le commandant d\'intervention.',
    invalidTitle: 'Ce lien n\'est plus valable.',
    invalidHint: 'Ouvre le lien directement depuis le message d\'alarme actuel.',
    disabledTitle: 'Les liens d\'intervention ne sont pas activés dans ce corps de sapeurs-pompiers.',
    disabledHint: 'Le commandant d\'intervention peut les activer dans la configuration.',
    offlineTitle: 'Pas de réseau',
    offlineHint: 'Impossible d\'ouvrir l\'intervention sans connexion.',
    errorTitle: 'Le serveur ne répond pas.',
    errorHint: 'Si cela persiste, avertir le commandant d\'intervention.',
    retry: 'Réessayer',
    closedTitle: 'Intervention clôturée',
    closedAt: 'Clôturée à {time}.',
    closedHint: 'Si l’intervention est rouverte, le tableau réapparaît ici tout seul.',
    unavailable: 'Cette intervention n\'est pas accessible pour le moment. Recharge la page dès que tu as du réseau.',
  },
  standingLink: {
    idleTitle: 'Aucune intervention en cours',
    // une phrase par surface (09.09., voir de/links.ts)
    idleHintTerminal: 'Dès qu\'une alarme arrive, cet écran bascule tout seul sur l\'intervention.',
    idleHintAs: 'Dès qu\'une intervention ou un exercice est en cours, ce code ouvre la surveillance ARI.',
    terminalKicker: 'Terminal de caserne',
    checkedLabel: 'Dernière vérification',
    chooseTitle: 'Plusieurs interventions en cours',
    chooseHint: 'Choisis quelle intervention cet écran doit afficher.',
    exerciseTag: 'Exercice',
    notEnrolledTitle: 'Cet appareil n\'est pas configuré comme terminal de caserne.',
    notEnrolledHint: 'Dans l\'administration, sous « Liens et accès », générer le lien de configuration et l\'ouvrir sur cet appareil.',
    asInvalidTitle: 'Ce code de protection respiratoire n\'est plus valable.',
    asInvalidHint: 'Le code a été renouvelé. Imprimer le code QR actuel dans l\'administration et l\'afficher.',
    disabledTitle: 'Cette fonction n\'est pas activée.',
    disabledHint: 'L\'administration peut l\'activer sous « Liens et accès ».',
  },
  sharePosition: {
    askTitle: 'Partager ta position ?',
    askBody: 'Le poste de commandement voit alors sur la carte de situation où tu es – pour savoir qui travaille où (p. ex. au transport d\'eau) et qui est joignable.',
    askWho: 'Visible uniquement par le poste de commandement. Les autres qui ont le lien d\'intervention ne voient pas ta position.',
    askHowLong: 'Seulement tant que cette intervention est en cours. La position est supprimée à la clôture.',
    askBackground: 'Si tu verrouilles le téléphone, plus rien n\'est transmis – la dernière position reste, avec son heure.',
    askAgain: 'Tu dois activer le partage toi-même à chaque intervention – il ne démarre jamais tout seul.',
    pickTitle: 'Qui es-tu ?',
    pickHint: 'Pour que ton point sur la carte ait un nom.',
    pickAgain: 'Nouvelle intervention – confirme à nouveau qui tu es. Le dernier nom choisi est en haut.',
    pickLast: 'dernier',
    search: 'Rechercher un nom …',
    yes: 'Oui, partager ma position',
    no: 'Non merci',
    menuOff: 'Partager la position',
    menuOn: 'Partage de la position – activé',
    menuClosed: 'Seulement tant que l\'intervention est en cours',
    menuDemo: 'Démo : simulé – ta position n\'est pas demandée',
    menuOnHint: 'Toucher pour arrêter',
    on: 'Position partagée',
    starting: 'Recherche de la position …',
    paused: 'Position en pause',
    pausedHint: 'Le téléphone ne transmet rien tant que l\'application est en arrière-plan ou l\'écran verrouillé. Rouvre l\'application et cela reprend.',
    denied: 'Position bloquée',
    deniedHint: 'L\'accès à la position est bloqué pour ce site. Cela ne peut être réautorisé que dans les réglages du navigateur.',
    taken: 'Nom déjà pris',
    takenHint: 'Un autre appareil partage actuellement sous ce nom. Choisis à nouveau ton nom ou attends un instant.',
    failing: 'La position n\'arrive pas',
    failingHint: 'Le téléphone trouve ta position, mais le serveur ne l\'accepte pas – généralement un manque de réseau. Les tentatives continuent.',
    impreciseHint: 'La réception est encore trop imprécise pour un point sur la carte. Dehors, cela s\'améliore généralement en quelques secondes.',
    lastAt: 'Dernière {t}',
    stop: 'Ne plus partager ma position',
    change: 'Changer de nom',
    settingsLabel: 'Utiliser la position',
    settingsHint: 'Autorise cet appareil à utiliser ta position. Rien n\'est partagé tant que tu ne l\'actives pas depuis la carte.',
    settingsAs: 'En tant que {name}',
    settingsName: 'Nom sur la carte',
    settingsNameSub: 'Ainsi te voit le poste de commandement – toucher pour changer',
  },
  livePosition: {
    chip: '{d} · il y a {n} min',
    chipNow: '{d} · maintenant',
    atScene: 'Sur les lieux',
    tapHint: 'Afficher sur la carte',
  },
}
