// French copy · Material (Mittel) and checklists.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/material.ts.

import type { Copy, Localizable } from '../index'

export const materialCopy: Localizable<Pick<Copy, 'mittel' | 'checklists'>> = {
  checklists: {
    railLabel: 'Checklists',
    showList: 'Afficher la liste',
    groupTasks: 'Tâches',
    searchPlaceholder: 'Rechercher un mot-clé …',
    searchAria: 'Rechercher un mot-clé',
    matching: 'Correspond : {title}',
    none: 'Aucune checklist disponible pour le moment.',
    pickEntry: 'Choisir ou rechercher un mot-clé.',
    done: 'fait',
    variantLabel: 'Variante',
    pickVariant: 'Choisir une variante pour voir les tâches.',
    milestoneTitle: 'Jalon – apparaît dans le journal',
    // the word the flag wears on the row (22.09.2026): the tooltip above is what a mouse
    // reads, and a tablet reads nothing — a lone glyph said «something», not what
    milestoneTag: 'noté dans le journal',
    milestoneUndone: 'Jalon annulé : {text}',
    actionLabels: { journal: 'Journal', plan: 'Plan', draw: 'Dessiner' },
    hazardLabels: { red: 'Incendie', orange: 'Dangers', green: 'Circulation', yellow: 'Technique', blue: 'Eau' },
    diagramAlt: 'Diagramme page {page}',
    diagramOpen: 'Agrandir le schéma',
    groupManuals: 'Modes d’emploi',
    manualUpdated: 'État au {date}',
    manualWarning: 'Attention :',
    manualImageAlt: 'Image de l’étape {n}',
    manualImageOpen: 'Agrandir l’image',
    manualSource: 'Source : {source}',
  },
  mittel: {
    title: 'Matériel',
    summary: '{lines} positions',
    summaryEmpty: 'Rien de saisi',
    add: 'Matériel',
    viewBySource: 'En service',
    // the category filter's WORD on a wide head (22.09.2026)
    categoryFilterWord: 'Filtrer',
    noSource: 'Sans affectation',
    searchPlaceholder: 'Rechercher …',
    addOne: 'Saisir {label}',
    addPickSource: '{label} – choisir la provenance',
    materialSearchPlaceholder: 'Rechercher du matériel …',
    unitSearchPlaceholder: 'Rechercher une unité …',
    sourceSearchPlaceholder: 'Rechercher une provenance …',
    categoryFilterLabel: 'Filtrer par catégorie',
    categoryAll: 'Toutes',
    categoryOther: 'Divers',
    customGroup: 'Autres',
    noch: 'reste {n}',
    stockAria: '{label} : reste {remaining} sur {total}',
    emptyTitle: 'Aucun matériel saisi.',
    emptyHint: 'Saisis avec «+ Matériel» ce qui a été consommé – pour le rapport et pour voir s\'il faut du réapprovisionnement.',
    emptyReadonly: 'Aucun matériel saisi.',
    composerTitle: 'Saisir du matériel',
    materialLabel: 'Matériel',
    materialPlaceholder: 'Choisir du matériel',
    customMaterial: 'Autre matériel',
    composerFromQuery: 'Saisir «{name}»',
    unitLabel: 'Unité',
    unitPlaceholder: 'Unité',
    sourceLabel: 'Provenance',
    sourcePlaceholder: 'Provenance (facultatif)',
    qtyLabel: 'Quantité',
    save: 'Enregistrer',
    cancel: 'Annuler',
    removeRow: 'Mettre à 0',
    removedToast: '«{label}» supprimé',
    logSet: '{label} : {menge} {unit}',
    logRemoved: '{label} mis à 0',
    logDeleted: '{label} supprimé',
    logRestored: '{label} rétabli',
    logNote: '{label} – remarque : {note}',
    logStock: '{label} – stock : {stock}',
    logBefore: '(avant {n})',
    noteLabel: 'Remarque',
    notePlaceholder: 'p. ex. remis au service de voirie',
    editLabel: 'Modifier l\'entrée',
    stockLabel: 'Stock',
    stockPlaceholder: 'facultatif',
    deleteLine: 'Supprimer l\'entrée',
    lageStrip: 'Posé, mais pas saisi : {list}',
    lageStripTake: 'Reprendre',
    lageStripHide: 'Masquer les suggestions',
    lageStripCapture: 'Saisir …',
    lagePickTitle: 'Posé, mais pas saisi',
    lagePickSub: '{n} symboles sur la carte/les plans ne figurent pas encore dans le matériel. Lesquels étaient-ce ?',
    lagePickSubOne: 'Un symbole sur la carte/les plans ne figure pas encore dans le matériel. Lequel était-ce ?',
    lagePickGroupHint: 'Symbole sur la carte/le plan',
    lagePickGroupSourceHint: 'Source ?',
    lagePickUnambiguous: 'Univoque',
    lagePickUnambiguousSub: 'saisi sans question',
    lagePickOpen: 'Encore {n} questions ouvertes',
    lagePickOpenOne: 'Encore 1 question ouverte',
    lagePickConfirm: 'Saisir {n} positions',
    lagePickConfirmOne: 'Saisir 1 position',
  },
}
