// French copy · Objektbesuche.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/objectVisits.ts.

import type { Copy, Localizable } from '../index'

export const objectVisitsCopy: Localizable<Pick<Copy, 'objectVisits'>> = {

  objectVisits: {
    launcher: 'Visites d’objets',
    title: 'Visites d’objets',
    back: 'Retour',
    loading: 'Chargement des visites d’objets …',
    notPreparedTitle: 'Pas encore préparé hors ligne',
    notPreparedBody: 'Cet appareil n’a jamais chargé la liste des objets ni les listes de contrôle. Ouvrez une fois les visites d’objets avec une connexion ; elles restent ensuite sur l’appareil.',
    notPreparedDrafts: 'Les brouillons de cet appareil restent disponibles même sans la liste des objets.',
    retry: 'Réessayer',
    refusedTitle: 'Visites d’objets indisponibles',
    refusedBody: 'L’administration n’a pas activé les visites d’objets pour ce corps, ou ce compte n’a pas le droit de les ouvrir.',
    storageUnreadable: 'La mémoire de l’appareil n’a pas pu être lue – des visites de cet appareil manquent peut-être dans cette liste.',
    myDrafts: 'Mes brouillons',
    unsent: 'Pas encore enregistré',
    lists: 'Listes',
    listObjectsOne: '1 objet',
    listObjectsMany: '{n} objets',
    listOn: "le {date}",
    listArchived: "Plus au programme",
    schedule: {"today": "Aujourd’hui", "overdue": "En retard", "upcoming": "À venir", "undated": "Sans date", "recent": "Terminées récemment"},
    listUntil: 'jusqu’au {date}',
    searchHead: 'Chercher un objet',
    searchPlaceholder: 'Chercher un objet …',
    nearby: 'À proximité',
    nearbyUse: 'Utiliser ma position',
    nearbyLocating: 'Localisation en cours …',
    nearbyFailed: 'Position indisponible',
    nearbyNone: 'Aucun objet du catalogue n’a de coordonnées.',
    distanceM: '{m} m',
    distanceKm: '{km} km',
    neverVisited: 'jamais visité',
    lastVisit: 'dernière fois le {date}',
    intro: 'Choisissez un objet dans une liste, par la recherche ou « À proximité ». La visite est d’abord enregistrée sur cet appareil, puis envoyée dès qu’il y a du réseau.',
    viewerNote: 'Avec ce compte, vous pouvez lire les visites mais pas les saisir.',
    listSub: '{done} sur {total} visités',
    listUnresolved: '{n} objets de cette liste ne sont pas connus sur cet appareil.',
    listUnknown: 'Cette liste n’est pas connue sur cet appareil.',
    listDoneElsewhere: 'fait',
    stateDraft: 'Brouillon',
    stateDone: '✓ {date}',
    statePhotos: 'Photos en attente',
    stateUnsent: 'non envoyé',
    visitLoading: 'Chargement de la visite …',
    visitMissing: 'Cette visite n’est pas sur cet appareil et n’a pas pu être chargée.',
    objectUnknown: 'L’objet « {key} » n’est pas connu dans le catalogue de cet appareil.',
    chooseChecklist: 'Quelle liste de contrôle ?',
    chooseChecklistLead: 'Il existe plusieurs listes de contrôle de visite pour cet objet.',
    noChecklist: 'Sans liste de contrôle',
    plans: 'Plans',
    changeChecklist: 'Changer de liste de contrôle',
    changeChecklistLead: 'Les réponses qui existent aussi dans la nouvelle liste sont conservées. Les photos restent toujours.',
    checklistCurrent: 'actuelle',
    changeChecklistDropOne: '1 réponse ne correspond pas à la nouvelle liste et sera supprimée. Les photos restent.',
    changeChecklistDropMany: '{n} réponses ne correspondent pas à la nouvelle liste et seront supprimées. Les photos restent.',
    changeChecklistConfirm: 'Changer',
    planLoading: 'Chargement du plan …',
    suggestedHead: 'En intervention',
    startFailed: 'La visite n’a pas pu être créée',
    menu: 'Autres actions',
    saveFile: 'Enregistrer comme fichier',
    discard: 'Abandonner le brouillon',
    discardTitle: 'Abandonner le brouillon ?',
    discardMsg: 'La visite est marquée comme abandonnée et n’apparaît plus dans aucune liste. Cela ne peut pas être annulé.',
    discardBtn: 'Abandonner',
    details: 'Par et date',
    visitedAt: 'Visité le',
    with: 'Par',
    withPlaceholder: 'Noms, p. ex. Max Muster, Nina Frei',
    notChecked: 'non contrôlé',
    photoMissing: 'Photo manquante',
    answer: { ok: 'OK', defect: 'Défaut', na: 'n. a.', yes: 'Oui', no: 'Non', photo: 'Photo' },
    defectNote: 'Quel est le défaut ?',
    defectNotePlaceholder: 'p. ex. le couvercle coince',
    photosAdded: '{n} photos ajoutées',
    photosOne: '1 photo',
    photosMany: '{n} photos',
    takePhoto: 'Prendre une photo',
    addPhoto: 'Ajouter une photo',
    valuePlaceholder: 'Valeur',
    notes: 'Remarques',
    notesPlaceholder: 'Autre chose remarquée …',
    photos: 'Photos',
    proposals: 'Propositions de correction',
    proposalAdd: 'Ajouter une proposition',
    proposalRow: 'avant : {current} · nouveau : {proposed}',
    proposalRowNew: 'nouveau : {proposed}',
    complete: 'Terminer',
    completeOpenOne: '1 point non contrôlé',
    completeOpenMany: '{n} points non contrôlés',
    completeOpenMsg: 'Terminer quand même ? Les points non contrôlés figurent dans le rapport comme « non contrôlé ».',
    completeRequired: 'Dont exigés : {items}',
    completeAnyway: 'Terminer quand même',
    completed: 'Visite terminée',
    correctionNote: 'Correction : la visite reste terminée, la modification devient une nouvelle révision.',
    correctionDone: 'Terminé',
    lifecycle: { draft: 'Brouillon', completed: 'Terminée', discarded: 'Abandonnée' },
    sync: {
      unsaved: 'Non enregistré',
      conflict: 'Conflit',
      auth: 'Connexion requise',
      error: 'Non envoyé',
      sending: 'Envoi en cours',
      local: 'Uniquement sur cet appareil',
      localAt: 'sur l’appareil {time}',
      changes: 'Modifications sur l’appareil {time}',
      photos: 'Photos {done}/{total}',
      saved: 'Enregistré {time}',
      remote: 'Révision {n}',
      offline: 'hors ligne',
    },
    delivery: { waiting: 'Classement en attente', delivered: 'classé', failed: 'Classement : erreur', paused: 'Classement en pause' },
    statusTitle: 'État de cette visite',
    statusOpen: 'Afficher l’état',
    statusLifecycle: 'Visite',
    statusDevice: 'Appareil → serveur',
    statusFiling: 'Classement',
    statusSavedAt: 'Enregistré sur cet appareil à {time}.',
    statusRevision: 'Révision {n} sur le serveur.',
    statusNeverSent: 'Jamais envoyé au serveur.',
    statusPending: 'Des modifications plus récentes ne sont que sur cet appareil.',
    statusPhotos: '{done} photos sur {total} sur le serveur.',
    statusNoFiling: 'Aucune destination de classement configurée.',
    destinationSharePoint: 'SharePoint',
    statusFilingRow: '{destination} : {state}',
    conflictTitle: 'Deux versions : {what}',
    conflictBody: 'Le même point a été modifié sur un autre appareil.',
    conflictMine: 'La mienne',
    conflictTheirs: 'L’autre',
    conflictBoth: 'Garder les deux',
    conflictRemoved: '(supprimé)',
    conflictWhat: {
      notes: 'Remarques', visitedAt: 'Date de visite', with: 'Par', checklist: 'Liste de contrôle',
      workRef: 'Liste', object: 'Objet', photo: 'Photo', proposal: 'Proposition',
    },
    unsavedTitle: 'Non enregistré sur l’appareil',
    unsavedBody: 'Le navigateur a refusé l’enregistrement (mémoire pleine ?). Ce qui n’est pas enregistré n’existe que dans cette fenêtre.',
    unsavedRetry: 'Enregistrer à nouveau',
    authTitle: 'Connexion expirée',
    authBody: 'La visite est en sécurité sur cet appareil. Reconnectez-vous pour l’envoyer.',
    authLogin: 'Se connecter',
    errorTitle: 'Le serveur n’a pas accepté la visite',
    errorAttachment: 'Une photo n’a pas été acceptée',
    errorForbidden: 'Ce compte ne peut pas saisir de visites.',
    errorDisabled: 'Les visites d’objets sont désactivées.',
    photoTitle: 'Photo',
    photoCaption: 'Légende',
    photoCaptionPlaceholder: 'p. ex. accès nord',
    photoBelongs: 'Appartient à',
    photoGeneral: 'Général',
    photoStored: 'Enregistrée sur cet appareil · envoyée dès qu’il y a du réseau',
    photoNotStored: 'Non enregistrée sur l’appareil – uniquement dans cette fenêtre',
    photoAnother: 'Encore une',
    photoDone: 'Terminé',
    photoRemove: 'Retirer la photo',
    photoRemoved: 'Photo retirée',
    photoPreparing: 'Préparation de la photo …',
    photoFailed: 'La photo n’a pas pu être reprise',
    photoPending: 'pas encore envoyée',
    photoOpen: 'Ouvrir la photo : {caption}',
    proposalTitle: 'Proposer une correction',
    proposalField: 'Champ',
    proposalOther: 'Autre',
    proposalOtherLabel: 'Quel champ ?',
    proposalCurrent: 'Avant',
    proposalCurrentHint: 'selon les données de base',
    proposalNew: 'Nouveau',
    proposalReason: 'Motif',
    proposalReasonPlaceholder: 'p. ex. le concierge a changé',
    proposalSave: 'Enregistrer la proposition',
    proposalRemove: 'Retirer la proposition',
    proposalRemoved: 'Proposition retirée',
    defectsOne: '1 défaut',
    defectsMany: '{n} défauts',
    countOk: '{n} OK',
    countOpen: '{n} non contrôlés',
    proposalsOne: '1 proposition',
    proposalsMany: '{n} propositions',
    report: 'Rapport (PDF)',
    reportSub: 'Révision {n}',
    reportFailed: 'Le rapport n’a pas pu être chargé',
    edit: 'Modifier',
    editSub: 'Correction · reste terminée, nouvelle révision',
    history: 'Historique',
    historyFailed: 'L’historique n’a pas pu être chargé',
    historyRow: 'r{n} · {time}',
    nextInList: 'Suivant dans la liste',
    listDone: 'Tous les objets de cette liste ont été visités.',
    by: 'Par {name}',
    fileSaved: 'Fichier enregistré',
    fileSavedMissing: 'Fichier enregistré – {n} photos n’étaient pas sur cet appareil',
    fileFailed: 'Le fichier n’a pas pu être créé',
    sent: 'Envoyé',
    sendContended: 'Conflit avec un autre appareil – nouvel essai sous peu',
    conflictTakeOther: 'Reprendre l’autre',
    conflictKeep: 'Garder celle-ci',
    conflictOther: 'Autre version',
    conflictCurrent: 'Dans la visite',
    storageWait: 'La mémoire de l’appareil n’a pas pu être lue. Pour éviter un second brouillon, aucune nouvelle visite n’est créée maintenant.',
    sendOffline: 'Hors ligne – sera envoyé dès que le serveur est joignable',
  },
}
