// French copy · photos, weather, PDF, Einstellungen, Feedback, offline and empty states.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/panels.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'photoViewer' | 'photoGeo' | 'einsatzuhr' | 'mapPicker' | 'weather' | 'weatherLayer' | 'pdf'
  | 'settings' | 'feedback' | 'offline' | 'emptyApp' | 'incidentAlert'

export const panelsCopy: Localizable<Pick<Copy, Keys>> = {
  mapPicker: {
    title: 'Placer le lieu sur la carte',
    hint: 'Touchez la carte pour définir le lieu',
    confirm: 'Utiliser ce lieu',
  },
  weather: {
    label: 'Météo',
    details: 'Détails météo',
    from: 'de',
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    cardinalsLong: ['Nord', 'Nord-est', 'Est', 'Sud-est', 'Sud', 'Sud-ouest', 'Ouest', 'Nord-ouest'],
    windTitle: 'Vent {dir} ({deg}°)',
    detailsHint: ' – toucher pour les détails',
    meteoHint: ' – toucher pour les détails MétéoSuisse',
    windDir: 'Direction du vent',
    windSpeed: 'Force du vent',
    gust: 'Rafales',
    precip: 'Précipitations',
    station: 'Station',
    source: 'Source',
    meteoRadar: 'Radar de précipitations MétéoSuisse',
    detailsUrl: 'https://www.meteosuisse.admin.ch/services-et-publications/applications/precipitations.html',
    conditions: {
      clear: 'Clair', fair: 'Beau', partly: 'Partiellement nuageux', overcast: 'Couvert',
      fog: 'Brouillard', drizzle: 'Bruine', rain: 'Pluie', snow: 'Neige',
      rainShowers: 'Averses de pluie', snowShowers: 'Averses de neige', thunder: 'Orage', cloudy: 'Nuageux',
    },
    windShiftOpen: 'Ouvrir dans le journal',
    windShiftDismiss: 'Masquer',

    unavailable: 'Données météo actuellement indisponibles',
  },
  weatherLayer: {
    group: 'Météo',
    radar: 'Précipitations (radar)',
    radarSub: 'MétéoSuisse · dernière heure',
    attribution: 'Radar © MétéoSuisse',
    radarTitle: 'Radar des précipitations',
    play: 'Lire la dernière heure',
    pause: "Arrêter (retour à l'image actuelle)",
    frameSlider: "Choisir l'image radar",
    frameAgo: 'il y a {minutes} min',
    latest: 'actuel',
    legendLight: 'faible',
    legendUnit: 'mm/h · estimation radar',
    legendHeavy: 'fort',
    radarPending: "Pas encore d'image radar – chargement.",
    radarUnavailable: 'Radar actuellement indisponible.',
    stale: 'État {time} – obsolète',
    chipAria: 'Alertes météo ({count}) : {summary}',
    more: '+{count}',
    from: 'dès {time}',
    until: "jusqu'à {time}",
    untilRevoked: "jusqu'à révocation",
    validity: 'Validité',
    source: 'Source',
    sourceMeteoswiss: 'MétéoSuisse (via MeteoAlarm)',
    sourceAlertswiss: '{publisher} (via Alertswiss)',
    moreInfo: "Plus d'informations à la source",
    warningStale: 'État {time} – source actuellement injoignable',
    verbatimNote: 'Texte original de la source, non modifié.',
    level1: 'Information',
    level2: 'Jaune – potentiellement dangereux',
    level3: 'Orange – dangereux',
    level4: 'Rouge – très dangereux',
    authorityNotice: 'Communication des autorités',
  },
  pdf: {
    loading: 'Chargement du PDF…',
    failed: 'Le PDF n’a pas pu être chargé.',
    retry: 'Réessayer',
    reason: {
      stale: 'L’application fonctionne sur une ancienne version – fermez-la et rouvrez-la.',
      offline: 'Aucune connexion – ce PDF n’est pas enregistré sur cet appareil.',
      missing: 'Le PDF ne se trouve plus sur le serveur.',
      denied: 'La connexion n’est plus valable – reconnectez-vous.',
      timeout: 'Le serveur n’a pas répondu.',
      unsupported: 'Ce navigateur est trop ancien pour afficher des PDF.',
      unknown: 'Raison inconnue.',
    },
  },
  settings: {
    title: 'Réglages',
    deviceGroup: 'Appareil',
    colorScheme: 'Schéma de couleurs',
    symbolSizeMap: 'Taille des symboles – carte',
    symbolSizeMapSub: 'Symboles tactiques sur la carte de situation et les plans de module liés',
    symbolSizeBoard: 'Taille des symboles – modules',
    symbolSizeBoardSub: 'Symboles tactiques sur les plans de module non liés',
    offlineRadius: 'Rayon hors ligne',
    offlineAuto: 'Préparation hors ligne',
    offlineAutoSub: 'Charge carte et plans de lui-même peu après l\'ouverture',
    offlineRadiusSub: 'Carte et conduites autour de l’intervention',
    deviceFoot: 'S’applique uniquement à cet appareil. Un rayon plus petit = téléchargement hors ligne plus rapide et plus léger.',
    incidentGroup: 'Intervention',
    contactInterval: 'Contact radio ARI',
    contactIntervalSub: 'Intervalle jusqu’au contact dû (orange)',
    contactIntervalAria: 'Intervalle de contact radio',
    grace: 'Délai de grâce',
    graceSub: 'Alarme rouge après intervalle + délai',
    funkkanal: 'Canal radio',
    funkkanalSub: 'Par défaut pour les nouveaux binômes ARI',
    syncedFoot: 'Synchronisé avec tous les appareils',
    syncedFootViewer: ' · seul le chef d’intervention peut les modifier',

    symbolCaptions: 'Étiquettes',
    symbolCaptionsSub: 'La valeur clé sous le symbole',
    railLabels: 'Étiquettes des barres',
    railLabelsSub: 'Un mot sous chaque symbole des deux barres',
    captionsOff: 'Aucune',
    captionsAuto: 'Auto',
    captionsAll: 'Toutes',
    keepScreenOn: 'Garder l\'écran allumé',
    keepScreenOnSub: 'Ne pas assombrir l\'écran pendant l\'intervention',
    utilityGroup: 'Modèles',
    blankSheet: 'Feuille de saisie vierge (PDF)',
    blankSheetSub: 'Une feuille papier à remplir à la main',
    blankSheetDownload: 'Télécharger',
    blankSheetFailed: 'Échec du PDF – réessayer',
    feedbackRow: 'Donner un retour',
    feedbackRowSub: 'Ce qui était compliqué ou manquait',
    feedbackOpen: 'Écrire',
  },
  offline: {
    title: 'Préparation hors ligne',
    syncedAgo: 'Données d’intervention synchronisées {ago}',
    offline: 'Hors ligne – enregistré localement',
    pending: 'Enregistrement …',
    error: 'Erreur de synchro – enregistré localement',
    agoNever: 'pas encore',
    agoJustNow: 'à l’instant',
    agoMin: 'il y a {n} min',
    agoHour: 'il y a {n} h',
    checking: 'vérification …',
    ready: 'prêt',
    notLoaded: 'non chargé',
    loading: 'chargement …',
    rowSymbols: 'Symboles',
    rowHazmat: 'Matières dangereuses (ONU/ADR)',
    rowMap: 'Carte',
    noLayer: 'aucune couche',
    rowPlans: 'Plans',
    noObject: 'aucun objet',
    rowLeitung: 'Couches de référence',
    geoAllReady: 'les {n} prêts',
    geoSome: '{cached}/{total} chargés',
    rowWeather: 'Météo',
    weatherUnreachable: 'injoignable',
    onlineOnly: 'en ligne uniquement',
    rowPersonnel: 'Effectif',
    personnelCount: '{n} personnes',
    rowObjectSearch: 'Recherche d’objet',
    rowStorage: 'Stockage de l’appareil',
    storageFree: '{size} libres',
    storageUnknown: 'L’appareil n’indique aucun niveau de stockage',
    storageFullShort: 'Plein – rien n’est enregistré localement',
    storageFull: 'Stockage plein – les modifications ne sont pas enregistrées localement',
    dlTightTitle: 'Stockage faible sur cet appareil',
    dlTightMsg: 'Le téléchargement nécessite ≈ {need}, il reste {free}. En version réduite, toute la zone est chargée mais moins détaillée (environ {pct} % des tuiles). Cela laisse de la place au rapport d’intervention.',
    dlTightConfirm: 'Charger en réduit',
    dlNoSpace: 'Stockage insuffisant pour le jeu hors ligne (seulement {free} libres). Libérez de l’espace sur l’appareil.',
    loadingForOffline: 'Chargement pour le hors ligne …',
    cancel: 'Annuler',
    loadAll: 'Tout charger pour le hors ligne',
    foot: 'Charge la carte, les plans, les symboles et les conduites de cette intervention sur cet appareil. La météo et la recherche d’objet nécessitent une connexion et ne sont pas disponibles hors ligne.',
    dlDone: 'Carte prête hors ligne – {n} tuiles',
    dlDoneCapped: 'Carte prête hors ligne – étendue limitée, {n} tuiles',
    dlPartial: 'Chargement partiel – {n} sur {total}. La carte manque en bordure de la zone.',
    dlPartialCapped: 'Chargement partiel – {n} sur {total}, étendue limitée. La carte manque en bordure.',
    dlNone: 'Rien chargé – pas de réseau. La carte ne sera pas disponible sur les lieux.',
    dlNoCoverage: 'Rien chargé – la source cartographique ne couvre pas cette zone. Vérifier la couche de carte ou l’URL des tuiles.',
    dlContinue: 'Poursuivre',
    dlRetry: 'Réessayer',
    dlFailed: 'Échec du téléchargement hors ligne',

    browserTitle: 'Hors ligne fiable en application installée',
    browserBody: 'Dans un onglet de navigateur, rien n\'est stocké de façon fiable : cartes, plans et lignes peuvent être supprimés à tout moment, et l\'onglet doit encore être ouvert à la prochaine intervention. Installée, PC Front fonctionne aussi hors ligne.',
    browserNoInstall: 'Cet appareil ne propose pas l\'installation. Pour être hors ligne en intervention, installe PC Front sur la tablette ou le téléphone.',
    wsDropped: '{n} entrées endommagées ignorées au chargement',
    wsNewer: 'Les données d\'intervention proviennent d\'une version plus récente de l\'application – merci de mettre l\'application à jour.',
  },
  emptyApp: {
    title: 'Aucune intervention ouverte',
    bodyViewer: 'Aucune intervention n’est actuellement active.',
    bodyEditor: 'Ouvrez une intervention.',
    bodyEditorAlarm: 'Ouvrez une intervention ou reprenez une alarme {provider}.',
    history: 'Historique',
  },
  incidentAlert: {
    kicker: 'Nouvelle intervention',
    switch: 'Basculer',
    open: 'Ouvrir',
    later: 'Plus tard',
  },
  photoViewer: {
    title: 'Photo',
    download: 'Télécharger',
  },
  photoGeo: {
    place: 'Placer sur la carte',
    placeN: 'Placer {n} photos sur la carte',
    show: 'Afficher sur la carte',
    placedStep: 'Photo placée sur la carte',
    logPlaced: 'Photo placée sur la carte',
    logPlacedN: '{n} photos placées sur la carte',
    where: 'Lieu de prise de vue',
    whereN: 'Lieu de prise de vue photo {n}',
    distance: 'à {d} du lieu d\'intervention',
    facing: 'vue vers {dir}',
    takenAt: 'prise à {t}',
    tooFar: 'Trop loin pour la carte',
    marker: 'Photo du journal',
    markerTaken: 'Photo du journal · prise à {t}',
    planMark: 'Photo – à déplacer ou supprimer sur la carte',
    sourceExif: 'lieu tiré de la photo',
    sourceDevice: 'position de l\'appareil',
    accuracy: '± {m} m',
    askTitle: 'Enregistrer la position avec les photos ?',
    askMessage: 'L\'appareil photo ne transmet aucun lieu à KP Front. Avec la position de cet appareil, une photo peut être placée sur la carte.',
    askNote: 'Seule la position est enregistrée, et seulement près de l\'intervention. Modifiable dans les réglages.',
    askYes: 'Utiliser la position',
    askNo: 'Ne pas utiliser',
    settingsLabel: 'Position pour les photos',
    settingsHint: 'Si une photo n\'a pas de lieu, la position de cet appareil est utilisée – seulement près de l\'intervention',
    locatedLate: 'Photo avec position',
  },
  einsatzuhr: {
    title: 'Durée de l\'intervention – début {t}',
    modeElapsed: 'Durée de l\'intervention',
    modeNow: 'Heure',
    modeStart: 'Début de l\'intervention',
  },
  feedback: {
    title: 'Retour',
    promptTitle: 'Une petite question',
    promptDismiss: 'Pas maintenant',
    promptOpen: 'Décrire brièvement',
    promptFor: {
      crashLoop: 'L\'application a planté plusieurs fois pendant une intervention. Que faisais-tu ?',
      crash: 'L\'application a planté une fois à l\'instant. Que faisais-tu ?',
      renderStorm: 'L\'application a tourné à plein régime pendant une intervention – sans doute lente, ou la batterie vidée rapidement. Qu\'est-ce qui était ouvert ?',
      storageFull: 'La mémoire de cet appareil était pleine. Quelque chose a-t-il été perdu ?',
      syncConflict: 'Deux appareils avaient des états différents. Manquait-il quelque chose au final ?',
    },
    kinds: {
      crashLoop: 'plantage répété dans la même intervention',
      crash: 'plantage de l\'interface',
      renderStorm: 'interface en charge permanente',
      storageFull: 'mémoire de l\'appareil pleine',
      syncConflict: 'conflit de synchronisation lors de la fusion',
    },
    subject: 'Retour',
    intro: 'Que s\'est-il passé, et à quoi t\'attendais-tu ? Une ou deux phrases suffisent.',
    placeholder: 'p. ex. «J\'ai mis le binôme sur retour, puis l\'écran est devenu blanc.»',
    techTitle: 'Ceci est joint à l\'envoi',
    techNote: 'Rien d\'autre – aucune donnée d\'intervention, aucune adresse, aucun nom. L\'application ne fait jamais de capture d\'écran d\'elle-même.',
    routeGithub: 'Signaler comme issue GitHub',
    routeGithubBadge: 'recommandé',
    routeGithubNote: 'Ouvre un formulaire pré-rempli. Tu peux suivre le signalement et tu es averti dès qu\'il est traité. Nécessite un compte GitHub.',
    routeMail: 'Envoyer par e-mail',
    routeMailBadge: 'sans compte',
    routeMailNote: 'Fonctionne toujours, même sans GitHub. La réponse revient directement par e-mail.',
    next: 'Continuer',
    diagNote: 'Dans les deux cas : le fichier de diagnostic ({n}) est enregistré au moment de continuer – joins-le à l\'issue ou à l\'e-mail. Sans lui, le message d\'erreur réel manque.',
    diagNoteEmpty: 'Dans les deux cas : aucun journal d\'erreurs n\'est enregistré pour l\'instant. Décris simplement ce qui s\'est passé.',
    diagCount: '{n} journaux d\'erreurs',
    diagCountOne: '1 journal d\'erreurs',
    diagLine: 'Erreurs : ',
    diagSaved: 'Fichier de diagnostic «{name}» enregistré – merci de le joindre.',
    diagFailed: 'Le fichier de diagnostic n\'a pas pu être créé – le signalement fonctionne quand même.',
    privacy: 'Rien n\'est envoyé automatiquement. Tu décides si, comment et à qui.',
    close: 'Fermer',
    tech: {
      version: 'Version :',
      locale: 'Langue :',
      device: 'Appareil :',
      viewport: 'Fenêtre :',
      network: 'Réseau : ',
      event: 'Incident :',
      online: 'en ligne',
      offline: 'hors ligne',
      noDescription: '(aucune description)',
    },
  },
}
