// French copy · the Rapport: Auswertung, report, preflight.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/report.ts.

import type { Copy, Localizable } from '../index'

export const reportCopy: Localizable<Pick<Copy, 'auswertung' | 'report' | 'wheel' | 'preflight'>> = {
  auswertung: {
    heading: 'Analyse',
    note: 'Pour le débriefing – dérivé des données de l’intervention, ne fait pas partie du rapport signé.',
    missing: '—',
    firstOnScene: 'Alarme jusqu’au 1er véhicule sur place',
    firstOnSceneDef: 'De l’alarme à l’heure «sur place» la plus précoce d’un véhicule (heures d’alarme / de départ).',
    firstAs: 'Alarme jusqu’au 1er engagement ARI',
    firstAsDef: 'De l’alarme à la première entrée d’un groupe sous ARI.',
    contacts: 'Contacts radio respectés',
    contactsSub: '{n} en retard sur {total}',
    contactsDef: 'Part des intervalles de contact radio sous ARI terminés avant que le groupe ne soit en retard ({n} min + {g}). Un intervalle va de l’entrée ou d’un contact au contact, à la pression, au repli ou à la sortie suivants ; un intervalle ouvert ne compte qu’une fois en retard. Le temps entre la clôture et la réouverture ne compte pas.',
    contactsDefNoGrace: 'Part des intervalles de contact radio sous ARI terminés avant que le groupe ne soit en retard ({n} min). Un intervalle va de l’entrée ou d’un contact au contact, à la pression, au repli ou à la sortie suivants ; un intervalle ouvert ne compte qu’une fois en retard. Le temps entre la clôture et la réouverture ne compte pas.',
    longestAs: 'Plus long engagement ARI',
    longestAsDef: 'Plus longue durée terminée d’un groupe sous ARI, de l’entrée à la sortie.',
    total: 'Durée de l’intervention',
    totalDef: 'De l’alarme à la fin de l’intervention.',
    totalRunning: 'Intervention en cours',
    truppLane: 'Groupe {no} · {name}',
    groupPhases: 'Phases (check-list)',
    groupVehicles: 'Véhicules',
    groupTrupps: 'Groupes',
    groupMilestones: 'Jalons',
    noTimeline: 'Aucune heure de véhicule, de groupe ou de check-list saisie.',
    legendTravel: 'trajet',
    legendScene: 'sur place',
    legendReturn: 'retour',
    legendAs: 'sous ARI',
    legendWork: 'engagé sans ARI',
    legendStandby: 'prêt',
    legendContact: 'contact radio',
    legendFaellig: 'contact dû',
    legendUeberfaellig: 'en retard',
    legendMilestone: 'jalon',
    legendPhase: 'phase : première à dernière coche',
    footnotesHead: 'Définitions',
    lehrenSeePage1: 'Enseignements / sécurité : voir page 1',
    graceMin: '{n} min',
    graceSec: '{n} s',
  },
  report: {
    erfasser: 'Saisi par',
    gerettete: 'Sauvés',
    gerettetePersonen: 'personnes',
    geretteteTiere: 'animaux',
    gerettetePerson: 'personne',
    geretteteTier: 'animal',
    rueckmeldungElz: 'Retour à la centrale',
    back: 'Retour',
    print: 'Imprimer',
    keyword: 'Mot-clé',
    einsatzleiter: 'Chef d’intervention',
    // la succession imprimée quand la conduite a changé en cours d’intervention (lib/reportPdfDirect)
    einsatzleitungBis: '{name} (jusqu’à {t})',
    einsatzleitungAb: '{name} (dès {t})',
    kontaktperson: 'Personne de contact',
    alarmierung: 'Alarme',
    ausgerueckt: 'Départ',
    incidentId: 'ID d’intervention',
    alarmMessage: 'Message d’alarme',
    partnerOrgs: 'Organisations partenaires',
    remarks: 'Remarques',
    kroki: 'Croquis',
    krokiState: '{title} · état {at}',
    atemschutz: 'Surveillance ARI',
    truppEntry: 'Entrée',
    mittel: 'Matériel (indiquer la quantité)',
    journal: 'Journal d’intervention',
    photo: 'Photo',
    transcript: 'Transcription',
    planFallback: 'Plan',
    proofOffline: 'Vérification impossible (hors ligne)',
    proofIntact: 'Chaîne de hash intacte',
    proofBroken: 'Chaîne de hash rompue',
    proofBrokenAt: 'Chaîne de hash rompue à #{seq}',
    areaManual: 'Manuel',
    areaAtemschutz: 'Binômes',
    areaAnwesenheit: 'Présences',
    areaMittel: 'Matériel',
    areaChecklist: 'Checklist',
    areaRapport: 'Rapport',
    areaSystem: 'Système',
    areaLage: 'Situation',
    drawCircle: 'Périmètre de sécurité',
    drawAreaLabeled: 'Section « {label} »',
    drawArea: 'Surface',
    drawRescueAxis: 'Axe de sauvetage',
    drawMeasureArrow: 'Flèche de mesure',
    drawLine: 'Ligne',

    pdf: 'Télécharger le PDF',
    pdfBusy: 'Création du PDF …',
    pdfFailed: 'Le PDF n\'a pas pu être créé.',
    lehren: 'Enseignements / sécurité',
  },
  wheel: {
    invalidTime: 'Saisir une heure valide (00:00–23:59).',
    day: 'Jour',
    hour: 'Heure',
    minute: 'Minute',
    now: 'Maintenant',
    ok: 'OK',
  },
  preflight: {
    pdfFull: 'Rapport d’intervention (PDF)',
    pdfBusy: 'Création du PDF …',
    geretteteLabel: 'Sauvés',
    geretteteLageStrip: 'Sur la carte : {list}',
    geretteteLagePersonen: '{n} personnes',
    geretteteLageTiere: '{n} animaux',
    geretteteLageTake: 'Reprendre',
    gerettetePersonen: 'Personnes',
    geretteteTiere: 'Animaux',
    geretteteNone: 'Aucun',
    geretteteNoneHint: 'Rien de sauvé',
    geretteteNonePrint: 'aucun',
    gruppenLabel: 'Alarme des groupes',
    fahrzeugeLabel: 'Départs des véhicules',
    ausgeruecktDerived: 'repris des heures des véhicules',
    vorOrtShort: 'sur place',
    zurueckShort: 'retour',
    gpsTableTitle: 'Véhicules GPS · en direct',
    gpsTableNote: 'Heures tirées des positions GPS, relevées par le serveur',
    gpsColFzg: 'Véh.',
    gpsColStatus: 'Statut',
    gpsColAn: 'arr.',
    gpsColAb: 'dép.',
    gpsColFahrten: 'Trajets',
    gpsColPos: 'Pos.',
    gpsStatusScene: 'sur place',
    gpsStatusAway: 'en route',
    gpsAgeSec: 'il y a {n} s',
    gpsAgeMin: 'il y a {n} min',
    gpsAgeHour: 'il y a {n} h',
    gpsAgeStale: 'Position périmée',
    fahrtenCount: '{n} trajets',
    rueckmeldungLabel: 'Retour à la centrale',
    rueckmeldungName: 'Nom',
    rueckmeldungZeit: 'Heure du retour à la centrale',
    title: 'Rapport d’intervention',
    headAllRecorded: 'toutes les données saisies',
    headStillOpen: 'ouvert',
    tabsLabel: 'Partie du rapport',
    tabs: { bericht: 'Rapport', werwas: 'Personnel & Matériel', beilagen: 'Annexes' },
    stichwort: 'Mot-clé',
    einsatzart: 'Type',
    ort: 'Lieu',
    fromDispatch: 'D’après les données d’intervention',
    edit: 'Modifier',
    alarmMessage: 'Message d’alarme',
    alarmierung: 'Alarme',
    notRecorded: 'Non saisi',
    summaryLabel: 'Rapport succinct',
    summaryPlaceholder: 'Que s’est-il passé / qu’a-t-on trouvé ?',
    einsatzleiterLabel: 'Chef d’intervention',
    einsatzleiterPlaceholder: 'Sélectionner ou saisir',
    kontaktpersonLabel: 'Personne de contact',
    kontaktpersonClear: 'Vider la personne de contact',
    kontaktpersonPlaceholder: 'Propriétaire / requérant',
    kontaktpersonTelefon: 'Téléphone personne de contact',
    kontaktpersonTelefonClear: 'Vider le téléphone',
    kontaktpersonTelefonPlaceholder: 'Numéro de téléphone',
    kontaktpersonCall: 'Appeler la personne de contact',
    entfaellt: 'Sans objet',
    entfaelltUndo: 'Modifier',
    incidentEndLabel: 'Fin d’intervention',
    zeitBeforeAlarm: 'Antérieur à l’alarme ({t})',
    zeitBeforeAusgerueckt: 'Antérieur au départ ({t})',
    zeitFuture: 'Dans le futur',
    madeToast: 'Rapport établi',
    bandDone: 'Rapport établi.',
    bandAsk: "L'intervention est encore ouverte – la clôturer ?",
    bandLater: 'Plus tard',
    exportIncompleteTitle: 'Des indications manquent',
    exportIncompleteLead: 'Encore ouvert :',
    exportIncompleteMsg: 'Le rapport peut tout de même être établi – les champs ouverts restent vides et peuvent être complétés à la main.',
    now: 'Maintenant',
    remarksLabel: 'Remarques',
    remarksPlaceholder: 'Optionnel',
    sectionsHead: 'Sections',
    printMenu: 'Autres options d’impression',
    toggleKroki: 'Croquis',
    plansAnnotated: 'Plans annotés ({n})',
    toggleGebaeude: 'Bâtiment – étages ({n})',
    toggleTafel: 'Tableau – pages ({n})',
    plansAll: 'Tous les plans',
    toggleAtemschutz: 'Surveillance ARI ({n})',
    toggleAttendance: 'Présence ({n})',
    toggleJournal: 'Journal d’intervention',
    togglePendenzen: 'Ordres / en-suspens ({n})',
    toggleAttachments: 'Photos ({n})',
    archiveZip: 'Télécharger les annexes (ZIP)',
    krokiAtLabel: 'Kroki à',
    krokiOrientation: 'Orientation',
    krokiPortrait: 'Portrait',
    krokiLandscape: 'Paysage',
    krokiAtNow: 'Maintenant',
    krokiAtFailed: 'La situation à ce moment n’a pas pu être reconstituée – la situation actuelle est imprimée.',
    partnersLabel: 'Organisations partenaires',
    partnerOrg: 'Organisation (p. ex. police)',
    partnerOrgShort: 'Organisation',
    partnerNote: 'Remarque (p. ex. reprend le trafic)',
    partnerNoteShort: 'Remarque',
    partnersNone: 'aucune saisie',
    partnerAdd: 'Ajouter une organisation',
    partnerPlaceholder: 'Organisation …',
    partnerLageStrip: 'Sur la carte : {list}',
    partnerLageTake: 'Reprendre',
    attachmentsHead: 'Photos',
    attachmentsAdd: 'Ajouter une photo',
    attachmentsOpen: 'Voir la photo',
    attachmentsCount: '{n} photo(s)',
    attachmentsNone: 'aucune',
    attachmentsCaption: 'Légende (p. ex. «Permis du conducteur»)',
    attachmentsPending: 'pas encore téléversée',
    attachmentsFailed: 'La photo {name} n’a pas pu être téléversée – elle ne figurera pas à l’impression.',
    attachmentAdded: 'Photo ajoutée',
    attachmentCaptioned: 'Légende',
    attachmentRemoved: 'Photo supprimée',
    linksHead: 'Formulaires & liens',
    shareHead: 'Transmettre',
    shareLede: 'Sans connexion · reste valable après la clôture.',
    shareLiveLede: 'Sans connexion · reste valable après la clôture.',
    shareCreate: 'Créer le lien',
    shareBusy: 'Création du lien …',
    shareLoading: 'Chargement du lien …',
    shareLoadFailed: 'Le lien n’a pas pu être chargé.',
    shareRetry: 'Réessayer',
    shareCreateFailed: 'La création du lien a échoué.',
    shareCopy: 'Copier l’adresse',
    shareCopied: 'Copié',
    shareScan: 'Scanner avec l’appareil photo',
    shareSend: 'Envoyer …',
    shareWarn: 'Toute personne disposant du lien voit l’intervention entière – les noms des '
      + 'présents, les photos et le journal complet.',
    shareRevoke: 'Révoquer le lien',
    shareRevokeTitle: 'Révoquer le lien vers toute l’intervention ?',
    shareRevokeBody: 'L’adresse cessera de fonctionner. Qui l’a ouverte perd l’accès '
      + 'immédiatement. Un nouveau lien peut être créé à tout moment – ce sera une autre adresse.',
    shareRevokeConfirm: 'Oui, révoquer',
    shareRevokeFailed: 'La révocation du lien a échoué.',
    shareKindLabel: 'Ce que le lien donne',
    shareKindFull: 'Intervention · lire',
    shareKindAtem: 'Binômes · utiliser',
    shareAsLede: 'Qui ouvre le lien ne voit que le tableau des binômes de cette intervention – la '
      + 'surveillance ARI – et l’utilise : annoncer un binôme, contact, pression, repli, sorti. '
      + 'Pas de carte, pas de journal. Valable jusqu’à la clôture de l’intervention.',
    shareAsLiveLede: 'Valable jusqu’à la clôture.',
    shareAsWarn: 'Ce qui y est saisi figure au rapport sous «Surveillance ARI». Ne donnez le lien qu’à la '
      + 'personne qui surveille.',
    shareAsRevokeTitle: 'Révoquer le lien vers le tableau des binômes ?',
    shareAsRevokeBody: 'L’adresse cessera de fonctionner. Qui a le tableau ouvert ne peut plus '
      + 'rien saisir. Un nouveau lien peut être créé à tout moment – ce sera alors une autre '
      + 'adresse.',
    linksCount: '{done} sur {n} faits',
    linksOpen: 'Ouvrir',
    linksMarkDone: 'Marquer {title} comme fait',
    linksMarkOpen: 'Marquer {title} comme à faire',
    linksDoneAt: 'fait · {at}',
    linksOpened: '{title} ouvert.',
    linksOpenedAction: 'Fait',
    linksOpenFailed: '{title} n’a pas pu être ouvert – le navigateur a bloqué la fenêtre.',
    toggleDetailedAudit: 'Preuve d’intégrité détaillée',
    toggleAuswertung: 'Analyse (interne)',
    krokiHead: 'Cadrage du croquis',
    framingHint: 'Déplacez et zoomez la carte – exactement ce cadrage sera imprimé.',
    framingFollows: 'Suit la situation',
    framingFollowOn: 'Le cadrage grandit avec la situation. Un déplacement le désactive.',
    framingOutside: '{n} en dehors – toucher pour ajuster',
    framingLegend: 'Légende',
    framingLegendEmpty: 'rien d’étiqueté dans le cadrage',
    framingLegendPending: 'mis à jour au relâchement …',
    framingLegendMissing: '{n} sans numéro – la pastille ne tient pas entièrement sur la feuille.',
    framingDiscOut: 'N’apparaîtra pas dans la légende – la pastille ne tient pas entièrement sur la feuille.',
    controlHead: 'Contrôle',
    controlOpen: '{n} en suspens',
    pdfShort: 'PDF',
    controlHint: '1 remarque',
    controlHints: '{n} remarques',
    controlOpenHead: 'En suspens',
    plansPrintNone: 'Les plans ne sont pas imprimés – à ajouter au besoin dans le menu ▾.',
    plansPrintAnnotated: '{n} plans annotés seront imprimés.',
    plansPrintAll: 'Tous les plans seront imprimés.',
    missingTranscripts: '{n} entrée(s) audio sans transcription – à compléter pour le procès-verbal.',
    fixTranscripts: 'Compléter dans le journal',
    stateNote: 'État : toute l’intervention jusqu’à la création du rapport ({at}).',

    sectionBericht: 'Rapport et personnes impliquées',
    sectionZeiten: 'Heures',
    sectionNachbearbeitung: 'Suivi',
    vehicleOrder: 'Ordre de départ',
    einsatzplan: 'Plan d\'intervention',
    lehrenLabel: 'Enseignements / sécurité',
    lehrenPlaceholder: 'Constats, consignes de sécurité (facultatif)',
    toggleMittel: 'Matériel ({n})',
    logMetaChanged: 'Données du rapport : {fields}',
    metaValue: '{label} «{value}»',
    metaWritten: 'rédigé',
    metaRewritten: 'retravaillé',
    metaCleared: 'vidé',
    metaRueckmeldung: 'Retour à la centrale par {name} à {t}',
    metaRueckmeldungTime: 'Retour à la centrale à {t}',
    metaRueckmeldungName: 'Retour à la centrale par {name}',
    metaGeretteteNone: 'Sauvés : aucun',
    metaGeretteteNoneOff: 'Sauvés : « aucun » annulé',
    metaGerettete: 'Sauvés : {value}',
    metaPartnerAdded: 'Organisation partenaire {org} ajoutée',
    metaPartnerRemoved: 'Organisation partenaire {org} retirée',
    metaPartnerNote: 'Organisation partenaire {org} – remarque : {note}',
    metaPartnerNoteCleared: 'Organisation partenaire {org} – remarque retirée',
    metaPartnerUnnamed: 'Organisation partenaire saisie',
    metaGruppe: 'Heure d\'alarme {gruppe} : {t}',
    metaGruppeCleared: 'Heure d\'alarme {gruppe} vidée',
    metaFahrzeugAus: '{fahrzeug} parti {t}',
    metaFahrzeugVorOrt: '{fahrzeug} sur place {t}',
    metaFahrzeugZurueck: '{fahrzeug} rentré {t}',
    metaFahrzeugCleared: '{fahrzeug} : heure vidée',
    metaMittelNoneOn: 'Matériel : «aucun utilisé» confirmé',
    metaMittelNoneOff: 'Matériel : «aucun utilisé» retiré',
    metaNoneOn: '{label} : sans objet',
    metaNoneOff: '{label} : «sans objet» retiré',
    unresolvedHours: '{names} : les heures sont inversées ou manquent – pas comptées dans les heures d\'intervention.',
    pendingMedia: '{n} photo/audio pas encore téléversés – seront complétés dès qu\'une connexion existe ; peut-être pas encore visibles sur d\'autres appareils.',
    pendingMediaConfirm: '{n} photo/audio pas encore envoyé – conservé sur cet appareil',
    truppsDeployedConfirm: 'Encore engagés : {n} – jamais annoncés sortis',
  },
}
