// French copy · tactical symbol names, search aliases and categories.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/symbols.ts.

import type { Copy, Localizable } from '../index'

export const symbolsCopy: Localizable<Pick<Copy, 'symbolNames' | 'symbolAliases' | 'symbolCategories'>> = {
  // Libellés d'AFFICHAGE des symboles tactiques, indexés par le nom FireGIS brut. L'identité
  // stockée reste le nom brut ; seul le libellé est traduit.
  symbolNames: {
    'VKF Feuer': 'Feu',
    'VKF Rettungen': 'Sauvetage',
    'VKF Unfall': 'Accident',
    'VKF Gefaehrliche Stoffe': 'Matières dangereuses',
    'VKF Wasser': 'Eau',
    'FW Gefahr allgemein': 'Danger',
    'FW Gefahr Tafel': 'Plaque de danger',
    'FW Gefahr Radioaktiv': 'Radioactif',
    'FW Gefahr Ex': 'Explosion',
    'FW Gefahr G': 'Gaz',
    'FW Gefahr C': 'Chimique',
    'FW Gefahr W': 'Eau',
    'FW Elektroanlage': 'Installation électrique',
    'VKF Patientensammelstelle': 'Poste de rassemblement des blessés',
    'VKF Sanitaetshilfsstelle': 'Poste de secours',
    'VKF Totensammelstelle': 'Poste de rassemblement des décédés',
    'VKF Sammelstelle': 'Indemnes',
    'FW Sammelplatz': 'Point de rassemblement',
    'FW Warteraum': 'Zone d\'attente',
    'FW Verwundetennest': 'Nid de blessés',
    'VKF Bereich Sanitaet': 'Sanitaire',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Chef d\'intervention',
    'FW Offizier': 'Officier',
    'VKF Kontrollposten': 'Poste de contrôle',
    'VKF Informationszentrum': 'Centre d\'information',
    'VKF Bereich Materialdepot': 'Dépôt de matériel',
    'FW Absperrung': 'Barrage',
    'VKF Verkehrssperre ueberwacht': 'Barrage routier',
    'VKF Drehleiter': 'Échelle pivotante',
    'VKF Hubretter': 'Bras élévateur',
    'VKF Fahrzeug': 'Véhicule',
    'VKF Pumpe Typ2': 'Pompe',
    'VKF Helilandeplatz': 'Aire d\'atterrissage hélico',
    'VKF Luefter mobil': 'Ventilateur',
    'FW Entrauchung': 'Désenfumage',
    'FW Kleinloeschgeraet': 'Petit extincteur',
    'FW Sprungretter': 'Coussin de sauvetage',
    'FW Leiter': 'Échelle',
    'SI Ueberflurhydrant': 'Hydrant aérien',
    'SI Unterflurhydrant': 'Hydrant souterrain',
    'VKF Innenhydrant': 'Hydrant intérieur',
    'SI Wasserloeschposten': 'Poste d\'extinction',
    'WV Loeschweier': 'Étang d\'extinction',
    'SI Wasserbezugsort': 'Point de puisage',
    'SI Wasserdruckversorgung': 'Alimentation en eau sous pression',
    'GB Lift': 'Ascenseur',
    'GB Kamin': 'Cheminée',
    'GB Abzug': 'Évacuation',
    'SI Schieber': 'Vanne',
    'GB Elektrotableau': 'Tableau électrique',
    'GB Sprinklerzentrale': 'Centrale sprinkler',
    'GB Brandmeldezentrale': 'Centrale de détection incendie',
    'GB BMA Melder': 'Détecteur d’incendie',
    'GB BMA-Z': 'Pictogramme centrale incendie (BMA-Z)',
    'GB RWA-BS': 'Pictogramme exutoire de fumée (RWA-BS)',
    'FW AED': 'DAE / Défibrillateur',
    'GB Fernsignaltableau': 'Tableau de signalisation à distance',
    'GB Schluesseldepot': 'Dépôt de clés',
    'GB BA Wand F30': 'Paroi F30',
    'GB BA Wand F60': 'Paroi F60',
    'GB BA Wand F180': 'Paroi F180',
    'GB Ture BS R30': 'Porte R30',
    'GB Ture Durchgang': 'Passage',
    'GB Treppe 8': 'Escalier',
    'SI Nordpfeil': 'Flèche du nord',
    'FKS Schluesselstelle': 'Point clé',
    'FKS Beobachtungsposten': 'Poste d’observation',
    'FKS Helikopter': 'Hélicoptère',
    'FKS Drohnenlandeplatz': 'Aire d’atterrissage drone',
    'FKS Forst': 'Service forestier',
    'ZS Fahrzeugplatz': 'Parc de véhicules',
    'ZS Angehoerigensammelstelle': 'Rassemblement des proches',
    'ZS Verpflegungsabgabestelle': 'Ravitaillement',
    'ZS Betriebsstoffabgabestelle': 'Station-service',
    'ZS Dekontaminationsstelle': 'Poste de décontamination',
    'SI Windrichtung': 'Direction du vent',
    'VKF Bereich Polizei': 'Police',
    'VKF Bereich Chemiewehr': 'Intervention chimique',
    'VKF Bereich Zivilschutz': 'Protection civile',
    'VKF Bereich Feuerwehr': 'Sapeurs-pompiers',

    'VKF Rauch': 'Fumée',
    'FW Boot': 'Bateau',
    'FW Tauchpumpe': 'Pompe immergée',
    'FW Wassersauger': 'Aspirateur à eau',
  },
  // En-têtes de catégories de la palette, indexés par la clé de catégorie allemande.
  symbolCategories: {
    'Schadenlage': 'Situation des dégâts',
    'Gefahren': 'Dangers',
    'Gebäude': 'Bâtiment',
    'Wasser': 'Eau',
    'Führung': 'Conduite',
    'Personen / Sanität': 'Personnes / Sanitaire',
    'Partner': 'Partenaires',
  },
  symbolAliases: {
    'VKF Feuer': ['incendie', 'feu', 'foyer', 'flammes', 'Brand', 'Brandherd', 'Flammen'],
    'VKF Rettungen': ['sauvetage', 'évacuation', 'personnes', 'Personenrettung', 'Menschenrettung', 'Evakuierung'],
    'VKF Unfall': ['accident', 'accident de circulation', 'collision', 'Verkehrsunfall', 'Kollision'],
    'VKF Gefaehrliche Stoffe': ['matières dangereuses', 'hydrocarbures', 'chimique', 'huile', 'fuite', 'NRBC', 'Gefahrgut', 'ABC', 'Chemie', 'Öl', 'Oel', 'Austritt', 'Hazmat'],
    'VKF Wasser': ['dégât d’eau', 'inondation', 'fuite', 'Wasserschaden', 'Hochwasser', 'Leck'],
    'FW Gefahr Ex': ['risque d’explosion', 'détonation', 'Explosionsgefahr', 'Detonation'],
    'FW Beschaedigung': ['dégât', 'endommagé', 'Schaden', 'beschädigt'],
    'FW Teilzerstoerung': ['destruction partielle', 'décombres', 'Zerstörung', 'Trümmer'],
    'FW Totalzerstoerung': ['destruction totale', 'effondrement', 'décombres', 'Zerstörung', 'Einsturz', 'Trümmer'],
    'FW Ueberschwemmung': ['inondation', 'crue', 'dégât d’eau', 'Hochwasser', 'Flut', 'Wasserschaden'],
    'FW Gefahr Tafel': ['numéro ONU', 'ADR', 'plaque orange', 'Kemler', 'panneau de danger', 'UN', 'UN-Nummer', 'ADR', 'Gefahrgut', 'Kemler', 'orange Tafel', 'Warntafel', 'Hazmat'],
    'FW Gefahr allgemein': ['attention', 'avertissement', 'zone de danger', 'Achtung', 'Warnung', 'Gefahrenstelle'],
    'FW Gefahr G': ['gaz', 'conduite de gaz', 'gaz naturel', 'propane', 'Gasleitung', 'Erdgas', 'Propan', 'Explosionsgefahr'],
    'FW Gefahr C': ['produits chimiques', 'acide', 'base', 'substance dangereuse', 'Chemikalien', 'Säure', 'Lauge', 'Gefahrstoff'],
    'FW Gefahr Radioaktiv': ['radiation', 'radioactif', 'nucléaire', 'Strahlung', 'atomar', 'nuklear', 'A-Gefahr'],
    'FW Gefahr W': ['danger pour les eaux', 'cours d’eau', 'protection des eaux', 'Wassergefahr', 'Gewässer', 'Gewässerschutz'],
    'FW Elektroanlage': ['électricité', 'courant', 'tension', 'haute tension', 'Strom', 'Spannung', 'Hochspannung', 'Elektrizität'],
    'VKF KP Front': ['poste de commandement', 'PC front', 'conduite', 'Kommandoposten', 'Einsatzleitung', 'Führungsstandort'],
    'VKF Einsatzleiter': ['chef d’intervention', 'CI', 'Einsatzleitung', 'EL'],
    'FW Offizier': ['officier', 'cadre', 'Kader', 'Führung'],
    'FW Sammelplatz': ['point de rassemblement', 'rendez-vous', 'Treffpunkt', 'Besammlung'],
    'FW Warteraum': ['zone d’attente', 'zone de mise à disposition', 'Bereitstellungsraum', 'Bereitstellung'],
    'VKF Kontrollposten': ['poste de contrôle', 'contrôle', 'barrage', 'Checkpoint', 'Kontrolle', 'Verkehrsposten', 'Pforte'],
    'VKF Informationszentrum': ['information', 'médias', 'presse', 'Info', 'Medien', 'Auskunft', 'Mediensammelstelle'],
    'VKF Bereich Materialdepot': ['matériel', 'dépôt', 'stock', 'Material', 'Depot', 'Lager'],
    'FW Absperrung': ['barrage', 'barrière', 'ruban', 'zone interdite', 'Sperre', 'Barriere', 'Absperrband', 'Sperrzone'],
    'VKF Verkehrssperre ueberwacht': ['fermeture de route', 'barrage routier', 'gardé', 'surveillé', 'Strassensperre', 'Absperrung', 'Sperre', 'bewacht', 'Bewachung', 'Überwachung'],
    'VKF Fahrzeug': ['véhicule', 'camion', 'tonne-pompe', 'TP', 'Auto', 'TLF', 'Tanklöschfahrzeug', 'Einsatzfahrzeug', 'Lastwagen'],
    'VKF Drehleiter': ['échelle automobile', 'grande échelle', 'EA', 'ADL', 'Autodrehleiter', 'Leiterfahrzeug'],
    'VKF Luefter mobil': ['ventilateur', 'ventilation', 'VPP', 'Ventilator', 'Belüftung', 'Druckbelüfter'],
    'FW Kleinloeschgeraet': ['extincteur', 'couverture anti-feu', 'Feuerlöscher', 'Handfeuerlöscher', 'Löschdecke'],
    'VKF Hubretter': ['bras élévateur', 'plate-forme élévatrice', 'mât télescopique', 'Hebebühne', 'Teleskopmast'],
    'VKF Pumpe Typ2': ['motopompe', 'pompe', 'transport d’eau', 'Motorspritze', 'Wassertransport', 'MS'],
    'FW Tauchpumpe': ['pompe immergée', 'pompe vide-cave', 'cave', 'eau', 'Pumpe', 'Keller', 'Wasser', 'TP', 'Lenzpumpe'],
    'FW Wassersauger': ['aspirateur à eau', 'aspiration', 'Sauger', 'Nasssauger', 'Wasser', 'WS'],
    'VKF Helilandeplatz': ['hélicoptère', 'place d’atterrissage', 'DZ', 'Rega', 'Helikopter', 'Heli', 'Rega', 'Landeplatz'],
    'VKF Drohne': ['drone', 'UAV', 'reconnaissance aérienne', 'thermique', 'Drone', 'UAV', 'Multicopter', 'Quadrocopter', 'Luftaufklärung', 'Wärmebild'],
    'FW Entrauchung': ['désenfumage', 'extraction de fumée', 'Rauchabzug', 'Belüftung', 'Abluft'],
    'FW Sprungretter': ['coussin de sauvetage', 'matelas de sauvetage', 'Sprungkissen', 'Sprungpolster', 'Rettungskissen'],
    'FW Leiter': ['échelle', 'échelle à coulisse', 'échelle à crochets', 'Anstellleiter', 'Schiebleiter', 'Steckleiter'],
    'VKF Sammelstelle': ['point de rassemblement', 'indemnes', 'évacués', 'prise en charge', 'Unverletztensammelstelle', 'Betreuung', 'Evakuierte'],
    'VKF Patientensammelstelle': ['nid de blessés', 'triage', 'patients', 'Verletzte', 'Triage', 'Patienten'],
    'VKF Sanitaetshilfsstelle': ['poste sanitaire', 'poste de secours', 'Verbandplatz', 'Sanposten', 'Sanhist'],
    'VKF Totensammelstelle': ['dépôt mortuaire', 'décédés', 'Tote', 'Verstorbene'],
    'FW Verwundetennest': ['nid de blessés', 'blessés', 'Verletzte', 'Verwundete'],
    'VKF Bereich Sanitaet': ['ambulance', 'secours sanitaire', 'sanitaire', '144', 'Ambulanz', 'Rettungsdienst', '144'],
    'VKF Bereich Feuerwehr': ['sapeurs-pompiers', 'pompiers', '118', '118'],
    'VKF Bereich Polizei': ['police', 'gendarmerie', '117', '117', 'Kantonspolizei'],
    'VKF Bereich Chemiewehr': ['défense chimique', 'NRBC', 'ABC-Wehr', 'Chemikalien'],
    'VKF Bereich Zivilschutz': ['protection civile', 'PCi', 'ZS', 'Bevölkerungsschutz'],
    'SI Ueberflurhydrant': ['hydrante', 'borne hydrante', 'prise d’eau', 'Wasserbezug'],
    'SI Unterflurhydrant': ['hydrante souterraine', 'prise d’eau', 'Wasserbezug'],
    'VKF Innenhydrant': ['hydrante intérieure', 'colonne montante', 'Steigleitung', 'Wandhydrant'],
    'SI Wasserloeschposten': ['poste incendie', 'attaque intérieure', 'Innenangriff'],
    'WV Loeschweier': ['étang', 'bassin', 'réserve d’eau', 'Weiher', 'Teich', 'Reservoir', 'Löschwasserreserve'],
    'SI Wasserbezugsort': ['point d’eau', 'aspiration', 'rivière', 'lac', 'Saugstelle', 'Fluss', 'Bach', 'See'],
    'SI Wasserdruckversorgung': ['alimentation sous pression', 'conduite sous pression', 'réservoir', 'Druckleitung', 'Reservoir'],
    'GB BA Wand F30': ['compartiment coupe-feu', 'mur coupe-feu', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F60': ['compartiment coupe-feu', 'mur coupe-feu', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F180': ['compartiment coupe-feu', 'mur coupe-feu', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB Ture BS R30': ['porte coupe-feu', 'porte', 'Brandschutztüre', 'Brandschutztür', 'Tür'],
    'GB Ture Durchgang': ['porte', 'entrée', 'accès', 'Tür', 'Eingang', 'Zugang'],
    'GB Lift': ['ascenseur', 'monte-charge', 'Aufzug', 'Fahrstuhl', 'Warenlift'],
    'GB Kamin': ['cheminée', 'conduit de fumée', 'Cheminée', 'Schornstein', 'Abgas'],
    'GB Abzug': ['extraction', 'ventilation', 'gaine', 'Lüftung', 'Ventilation', 'Abluft'],
    'SI Schieber': ['vanne', 'vanne d’arrêt', 'vanne de gaz', 'Absperrschieber', 'Ventil', 'Gasschieber'],
    'GB Elektrotableau': ['tableau électrique', 'coffret de fusibles', 'interrupteur principal', 'Sicherungskasten', 'Verteiler', 'Strom', 'Hauptschalter'],
    'GB Sprinklerzentrale': ['sprinkler', 'centrale sprinkler', 'installation d’extinction', 'Sprinkler', 'Löschanlage'],
    'GB Brandmeldezentrale': ['centrale de détection incendie', 'tableau de signalisation', 'BMA', 'BMZ', 'Brandmeldeanlage', 'Alarmzentrale'],
    'GB BMA Melder': ['détecteur', 'détecteur de fumée', 'déclencheur manuel', 'zone', 'Melder', 'Brandmelder', 'Rauchmelder', 'Meldergruppe', 'Handfeuermelder'],
    'GB BMA-Z': ['pictogramme centrale incendie', 'BMA', 'BMZ', 'plaquette', 'Brandmeldezentrale', 'Brandmeldeanlage'],
    'GB RWA-BS': ['exutoire de fumée', 'RWA', 'commande exutoire', 'plaquette', 'Rauch- und Wärmeabzug', 'Bedienstelle'],
    'FW AED': ['défibrillateur', 'DAE', 'réanimation', 'arrêt cardiaque'],
    'GB Fernsignaltableau': ['tableau de report', 'report d’alarme', 'Brandmeldeanlage', 'Signaltableau'],
    'GB Schluesseldepot': ['dépôt de clés', 'boîte à clés pompiers', 'Schlüsselrohr', 'Feuerwehrschlüsseldepot'],
    'GB Treppe 8': ['escalier', 'cage d’escalier', 'Treppenhaus', 'Stiege', 'Aufgang'],
    'SI Windrichtung': ['vent', 'direction du vent', 'manche à air', 'météo', 'Wind', 'Windsack', 'Wetter'],
    'SI Nordpfeil': ['nord', 'boussole', 'orientation', 'Norden', 'Kompass', 'Orientierung'],
    'FKS Schluesselstelle': ['point clé', 'passage', 'Schlüsselstelle'],
    'FKS Beobachtungsposten': ['observation', 'guet', 'Beobachtungsposten'],
    'FKS Helikopter': ['hélicoptère', 'héli', 'Helikopter'],
    'FKS Drohnenlandeplatz': ['drone', 'atterrissage', 'Drohne', 'Landeplatz'],
    'FKS Forst': ['forestier', 'forêt', 'Forst', 'Waldbrand'],
    'ZS Fahrzeugplatz': ['véhicules', 'parc', 'Fahrzeugplatz'],
    'ZS Angehoerigensammelstelle': ['proches', 'famille', 'Angehörige'],
    'ZS Verpflegungsabgabestelle': ['ravitaillement', 'repas', 'Verpflegung'],
    'ZS Betriebsstoffabgabestelle': ['carburant', 'essence', 'Tankstelle', 'Treibstoff'],
    'ZS Dekontaminationsstelle': ['décontamination', 'décon', 'Dekontamination'],
  },
}
