// French copy · the Plan whiteboard, notes and entities.
// One slice of the `fr` overlay, assembled in ../fr.ts; the German base is ../de/whiteboard.ts.

import type { Copy, Localizable } from '../index'

export const whiteboardCopy: Localizable<Pick<Copy, 'incidents' | 'entities' | 'notes' | 'whiteboard' | 'tafel'>> = {
  incidents: {
    migratedTitle: 'État de travail migré',
    geojsonNotJson: 'Fichier JSON non valide.',
    geojsonNotFc: 'Pas une FeatureCollection GeoJSON.',
    geojsonNotWgs84: 'Les coordonnées ressemblent à du LV95, pas du WGS84 [lng, lat]. Reprojeter d’abord en EPSG:4326.',
  },
  entities: {
    noteSubtitle: 'Note',
    fallbackObjectName: 'Objet',
  },
  notes: {
    section: 'Note',
    content: 'Texte',
    size: 'Taille',
    sizeS: 'Petit',
    sizeM: 'Normal',
    sizeL: 'Grand',
    look: 'Apparence',
    lookPill: 'Étiquette',
    lookPlain: 'Texte simple',
    color: 'Couleur',
    done: 'Terminé',
    deleteTitle: 'Retirer la note ?',
    deleteMsg: 'Cette note contient du texte. Vraiment la retirer ?',
  },
  whiteboard: {
    fit: 'Ajuster',
    pan: 'Sélection',
    team: 'Équipe',
    draw: 'Dessiner',
    text: 'Note',
    symbol: 'Symbole',
    line: 'Ligne',
    area: 'Surface',
    dockHints: {
      draw: 'Glissez sur le plan pour dessiner à main levée. Couleur, épaisseur et style se choisissent ensuite dans l’éditeur.',
      line: 'Touchez les sommets. Un double appui ou « Terminé » ferme la ligne. Couleur, épaisseur et style se choisissent ensuite dans l’éditeur.',
      lineFreeShort: 'Glissez le doigt sur le plan',
      lineNodesShort: 'Touchez des points – ✓ termine la ligne',
      areaFreeShort: 'Tracez le contour du doigt',
      areaNodesShort: 'Touchez au moins 3 sommets – ✓ termine',
      area: 'Touchez les sommets (au moins 3). Un double appui ou « Terminé » ferme la surface.',
      circle: 'Glissez du centre vers l’extérieur pour fixer le rayon. Ajustez ensuite le rayon, la couleur et le remplissage dans l’éditeur – en mètres réels une fois l’échelle calibrée.',
      text: 'Touchez le plan pour poser une note.',
      resource: 'Touchez le plan pour placer une équipe. Tirez pour la déplacer.',
      scale: 'Touchez les deux extrémités de l’échelle imprimée, puis saisissez la longueur réelle. Ensuite, les lignes avec « Longueur » affichent des mètres réels.',
      measure: 'Touchez des points sur le plan. « Distance » affiche la longueur, « Surface » l’aire + le périmètre – en mètres réels une fois l’échelle calibrée. Tirez les points pour déplacer, maintenez un point pour le supprimer.',
    },
    scale: {
      tool: 'Échelle',
      promptTitle: 'Définir l’échelle',
      promptBody: 'Longueur réelle de la distance relevée (p. ex. la barre d’échelle) :',
      unit: 'm',
      confirm: 'Appliquer',
      cancel: 'Annuler',
      chipCalibrated: 'réf. {m} m',
      chipAuto: 'réf. auto',
      chipAutoHint: 'réf. automatique – échelle issue du lien avec la carte',
      chipAutoStackHint: 'réf. automatique – échelle issue de l’emprise du bâtiment',
      chipUncalibrated: 'non calibrée',
      recalibrate: 'Recalibrer',
      calibrate: 'Calibrer l’échelle',
      calibrateHint: 'Touchez deux points de la barre d’échelle',
      stale: 'revérifier l’échelle',
      saved: 'Échelle calibrée (référence {m} m)',
      needsCalibration: 'Définir l’échelle : touchez les deux extrémités de la barre d’échelle',
      needsCalibrationViewer: 'La mesure exige d’abord une échelle calibrée',

      persistTitle: 'Mémoriser l\'échelle ?',
      saveAll: 'Pour tous les plans',
      saveThis: 'Ce plan seulement',
      savedAll: 'Enregistrée comme échelle par défaut',
      savedThis: 'Échelle enregistrée pour ce plan',
      saveFailed: 'Échec de l’enregistrement de l’échelle',
    },
    georef: {
      chipUnlinked: 'Lier à la carte',
      chipLinked: 'lié',
      chipTwoPoints: 'à partir de 2 points',
      chipResidual: '⌀ {m} m',
      linkTitle: 'Lier ce plan à la carte',
      openQuality: 'Vérifier et corriger la référence',
      freeOrderTap: 'Touchez le même endroit sur le module et la carte',
      freeOrderTip: 'Les points sans ambiguïté sont les meilleurs – angle de bâtiment, hydrant, croisement. L’ordre est libre : les moitiés posées trouvent leur homologue toutes seules.',
      freeOrderPlace: 'Agit sur la surface visible – carte ou module, ordre libre',
      moveMap: 'Déplacer le point {n} – touchez le nouvel endroit sur la carte, l’ancien disparaît.',
      movePlan: 'Déplacer le point {n} – touchez le nouvel endroit sur le module, l’ancien disparaît.',
      title: 'Lier à la carte',
      barOpen: '{n} en attente',
      sideProgress: 'Carte {map} · Module {plan}',
      statusOpenMap: 'Le point {n} manque encore sur la carte.',
      statusOpenPlan: 'Le point {n} manque encore sur le module.',
      statusOpenMapMany: '{k} points manquent encore sur la carte.',
      statusOpenPlanMany: '{k} points manquent encore sur le module.',
      statusOpenBoth: 'Points ouverts sur la carte et le module – les endroits identiques s’associent automatiquement.',
      statusSelected: 'Point {n} sélectionné – toucher à côté désélectionne.',
      cancel: 'Annuler',
      closeMode: 'Fermer',
      done: 'Terminé',
      placePoint: 'Placer le point',
      targetOutside: 'Placez d’abord le réticule sur la surface visible',
      checkFit: 'Vérifier la superposition',
      checkOpacity: 'Visibilité de la superposition du module',
      checkMap: 'Carte',
      checkPlan: 'Module',
      autoStart: 'Aligner automatiquement',
      autoStartSub: 'Vérifier la proposition sur la carte, puis valider',
      autoManual: 'Placer les points soi-même',
      autoManualSub: 'Toucher le même endroit sur le module et la carte – ordre libre',
      autoBusy: 'Alignement automatique en cours…',
      autoStepRender: 'Rendu du plan',
      autoStepOsm: 'Chargement des bâtiments',
      autoStepMatch: 'Comparaison des bâtiments',
      autoNone: 'Aucune proposition fiable trouvée – placer les points soi-même',
      autoNoScale: 'Échelle du plan non reconnue – calibrer d’abord ou placer les points soi-même',
      autoFailed: 'L’alignement automatique a échoué.',
      autoUnavailable: 'L’alignement automatique n’est pas configuré sur ce serveur',
      proposalHead: 'Aligné automatiquement',
      proposalSub: 'Comparer les arêtes des bâtiments, puis valider',
      proposalCheckHead: 'Vérifier la superposition',
      proposalCheckSub: 'Les bâtiments ne concordent que partiellement – comparer attentivement, ajuster au besoin',
      proposalAdjustHead: 'Ajuster le plan',
      proposalAdjustSub: 'Déplacer ou tourner jusqu’à ce que les arêtes coïncident.',
      adjust: 'Ajuster',
      accept: 'Valider',
      discard: 'Abandonner',
      restore: 'Rétablir la proposition',
      planSize: 'Taille du plan',
      sizeSmaller: 'Réduire le plan de 1 pour cent',
      sizeBigger: 'Agrandir le plan de 1 pour cent',
      undoNudge: 'Annuler le dernier ajustement',
      rotateGrip: 'Tourner',
      hintMove: 'Glisser déplace le plan',
      hintRotate: 'Glisser tourne le plan autour du centre',
      acceptedToast: 'Alignement validé',
      crossTitle: 'Point {n} – glisser déplace, toucher affiche les options',
      pendingCrossTitle: 'Point {n} ouvert – glisser déplace, toucher affiche les options',
      pointN: 'Point {n}',
      popMove: 'Déplacer',
      popKeep: 'Garder',
      popResidual: 'écart {m} m',
      popOpen: 'ouvert',
      popPairHint: 'Pour associer, touchez le point ouvert sur l’autre surface',
      detailsTitle: 'Détails de l’ajustement',
      saveFailed: 'Échec de l\'enregistrement du lien',
      qualityTitle: 'Ajustement',
      pairs: 'Paires',
      qualityDeviation: 'Écart ⌀ {m} m',
      warnTwoPoints: 'Deux paires se résolvent exactement – seul un troisième point montre la qualité réelle de l\'ajustement.',
      warnCollinear: 'Posez le point suivant à l’écart de la ligne – les points actuels sont presque alignés, et perpendiculairement la position est indéterminée.',
      warnBaseline: 'Posez le point suivant plus loin – les points ne sont distants que de {m} m, un plus grand écart stabilise l’ajustement.',
      lampNoneHead: 'Pas encore de lien',
      lampNoneBody: 'Deux points posent le plan sur la carte.',
      lampOneHead: '1 point posé',
      lampOneBody: 'Le deuxième pose le plan sur la carte.',
      lampTwoHead: '2 points – exact, mais non vérifié',
      lampGoodHead: '{n} points · ⌀ {m} m',
      lampGoodBody: 'Assez précis pour refléter les symboles entre le plan et la carte.',
      addThird: 'Poser un troisième point',
      lampAutoHead: 'Aligné automatiquement',
      lampApprovedHead: 'Validé par la station',
      lampApprovedBody: 'La station a vérifié la superposition et validé cet ajustement.',
      chipAuto: 'non mesuré',
      warnAuto: 'Placer des points de référence pour mesurer l’ajustement – seule la vérification visuelle a eu lieu.',
      autoAddPoints: 'Placer des points de référence',
      autoOneHead: 'Aligné automatiquement · 1 point',
      autoOneBody: 'Un deuxième point remplace l’alignement automatique par de vraies références.',
      autoOnePoint: '1 point',
      openDroppedOne: 'Point ouvert abandonné – un point de référence exige les deux surfaces',
      openDroppedMany: '{k} points ouverts abandonnés – un point de référence exige les deux surfaces',
      addMore: 'Ajouter des points',
      transfer: 'Transférer',
      transferTitle: 'Copier l’ajustement',
      transferBody: 'Les points de référence de {source} sont copiés. Chaque module peut ensuite être ajusté séparément.',
      transferLinked: 'déjà lié',
      transferCompleted: 'copié',
      transferReplaceTitle: 'Remplacer l’ajustement de {target} ?',
      transferReplaceBody: 'Les points de référence existants de {target} sont remplacés par l’ajustement de {source}.',
      transferDone: 'Ajustement copié vers {target} – vérifiez-y la superposition',
      reset: 'Réinitialiser',
      resetTitle: 'Réinitialiser la référence ?',
      resetBody: 'Le lien entre ce plan et la carte est supprimé. Les points devront être posés à nouveau.',
      resetDone: 'Référence réinitialisée',
      clearPoints: 'Réinitialiser',
      clearTitle: 'Réinitialiser tous les points ?',
      clearBody: 'Les points posés sont supprimés, et avec eux le lien entre ce plan et la carte. Tout est à reposer.',
      removePoint: 'Supprimer le point',
      layerGroupPlans: 'Plans',
      layerPlanImage: 'Plan ({plan})',
      twinFromMap: '{name} – reflété depuis la carte. Toucher pour les indications, glisser déplace l’original.',
      twinUnnamed: 'Symbole',
    },
    finishShape: 'Terminé',
    cancelShape: 'Annuler',
    insertVertex: 'Insérer un point',
    dragVertex: 'Tirer le sommet · maintenir pour supprimer',
    dragRadius: 'Faire glisser le rayon',
    groupDeleteTitle: 'Retirer la sélection',
    groupDeleted: 'Sélection retirée',
    placeText: 'Note posée sur le plan',
    placeSymbol: 'Symbole « {name} » posé sur le plan',
    placeLine: 'Ligne tracée sur le plan',
    placeArea: 'Surface dessinée sur le plan',
    placeCircle: 'Périmètre de sécurité tracé sur le plan',
    placeTeam: '{name} placé sur le plan',
    selectTrupp: 'Quel binôme ?',
    newTeam: 'Nouvelle équipe',
    showTrupp: 'Montrer dans Binômes',
    markPosition: 'Marquer la position',
    positionMarked: '{name} : position marquée',
    removeMarker: 'Retirer le marqueur',
    removeMarkerTrail: 'Retirer le marqueur et la trace',
    clearTrail: 'Retirer la trace',
    clearTrailConfirm: 'Retirer les {n} positions marquées de {name} ? La trace disparaît de la carte et du plan.',
    trailCleared: '{name} : trace retirée',
    trails: 'Traces',
    trailsOn: 'Afficher les traces',
    trailsOff: 'Masquer les traces',
    ghostTrail: 'Trace {name}',
    ghostTrailHint: 'Trace de {name} – le marqueur a été supprimé',
    ghostTrailTitle: "Trace de {name}",
    ghostTrailAsk: "Le marqueur a été supprimé, sa trace est restée. Replacer l’équipe à la fin de la trace – ou retirer la trace ?",
    ghostTrailRestore: "Replacer l’équipe",
    ghostTrailRestored: '{name} replacée – trace reprise',
    teamNameTaken: '{name} est déjà attribué – le nom reste',
    textPlaceholder: 'Note ...',
    blankHint: 'Feuille vierge – annotez avec ligne, surface, note, symbole ou binôme',
    osmLoading: 'Chargement des contours de bâtiment …',
    osmError: 'Contours de bâtiment (OSM) injoignables',
    osmEmpty: 'Aucun bâtiment dans cette zone',
    osmRetry: 'Réessayer',
    osmPickHint: 'Touchez un bâtiment, puis appliquez',
    osmPickHintReplace: 'Touchez un bâtiment, puis appliquez – cela remplace le bâtiment existant',
    osmPickHintAmend: 'Le bâtiment existant est en surbrillance – touchez-en d’autres pour les ajouter, puis appliquez',
    osmPickHintHere: 'Le bâtiment du lieu d’intervention est marqué – vérifiez, puis appliquez.',
    osmPickMissing: 'Des contours du bâtiment existant manquent ici ({n}) – ils seront perdus à l’application.',
    osmTransfer: 'Appliquer ({n})',
    osmClear: 'Effacer la sélection',
    addFloorUp: 'Ajouter un étage supérieur',
    noFloorPlan: 'Pas de plan d’étage',
    stairTo: 'Continue vers {floor}',
    stairFrom: 'Depuis {floor}',
    climbUp: 'Continuer un étage plus haut',
    climbDown: 'Continuer un étage plus bas',
    climbBack: 'Retour à {floor}',
    addFloorDown: 'Ajouter un sous-sol',
    floorAddedToast: '{floor} ajouté',
    floorHide: 'Masquer l’étage',
    floorHideShort: 'Masquer',
    floorMenu: '{name} : masquer ou retirer',
    floorShow: 'afficher',
    floorHidden: 'masqué',
    removeFloor: 'Retirer l’étage',
    removeFloorConfirm: '{floor} : {n} marquages de cet étage seront retirés ou raccourcis. Retirer l’étage quand même ?',
    removeFloorConfirmOne: '{floor} : 1 marquage de cet étage sera retiré ou raccourci. Retirer l’étage quand même ?',
    floorRemoved: 'Étage retiré',
    floorRemovedLog: 'Étage {floor} retiré',
    floorRemovedLogMarks: 'Étage {floor} retiré – {n} marquages retirés ou raccourcis',
    floorRestoredLog: 'Étage {floor} rétabli',
    floorAddedLog: 'Étage {floor} ajouté',
    floorAdded: 'Étage ajouté',
    buildingReplaced: 'Bâtiment remplacé',
    buildingReplacedMarks: 'Bâtiment remplacé – {n} marquages retirés',
    buildingReplacedKept: 'Bâtiment changé – étages conservés',
    buildingReplacedCarried: 'Bâtiment changé – {n} marquages repris',
    buildingReplacedCarriedDropped: 'Bâtiment changé – {n} repris, {d} supprimés',
    buildingTaken: 'Bâtiment repris',
    replaceBuilding: 'Choisir un autre bâtiment',
    replaceBuildingConfirm: 'La pile d’étages actuelle est abandonnée et remplacée par le nouveau contour.',
    replaceBuildingConfirmMarks: 'Les étages portent {n} marquages. Ils sont liés au contour actuel et ne peuvent pas être reportés sur un autre – ils seront supprimés. « Annuler » dans l’avis les rétablit.',
    replaceBuildingConfirmKeep: 'Le nouveau contour prend la place de l’actuel. Les étages sont conservés.',
    replaceBuildingConfirmCarry: 'Le nouveau contour prend la place de l’actuel. Les étages sont conservés et {n} marquages sont repris – ils gardent leur position au sol.',
    replaceBuildingConfirmCarryDrop: '{n} marquages sont reportés sur le nouveau contour et gardent leur position au sol. {d} n’y figurent plus et sont supprimés. « Annuler » dans l’avis rétablit le tout.',
    backToBuilding: 'Retour au bâtiment',
    railBuilding: 'Bâtiment',
    otherObject: 'Autre objet',
    objectLabel: 'Objet',
    objectNone: 'Aucun objet',
    objectIs: 'Objet : {name}',
    objectSwitch: 'Objet : {name} – choisir un autre objet',
    objectSwitchShort: 'Choisir un autre objet',
    objectNearby: '{name} · à {distance}',
    objectNearbyLabel: 'Objet le plus proche à {distance} – pas l’adresse de l’intervention',
    nearbyBannerTitle: 'Objet le plus proche, pas l’adresse de l’intervention.',
    nearbyBannerBody: 'Intervention : {incident} · plan : {object} ({distance}).',
    nearbyBannerNoAddress: 'sans adresse',
    objectActive: 'Plans de « {name} »',
    objectReset: 'Réinitialiser sur l’objet suivant',
    objectSwitchConfirmTitle: 'Charger un autre objet',
    objectSwitchConfirm: 'Les plans de tous les modules basculent sur « {name} ». Changer l’objet actuel ?',
    objectSwitchConfirmCta: 'Charger l’objet',
    northLabel: 'N',
    northTitle: 'Direction du nord – bâtiment pivoté sur son grand axe',
    orientAsDrawn: 'Tel que dessiné',
    northUnknownTitle: 'Nord inconnu – plan non lié à la carte',
    orientNorthUp: 'Nord en haut',
    orientLongAxis: 'Pivoter sur le grand axe',
    orientMenuTitle: 'Pivoter le bâtiment',
    orientSliderLabel: 'Rotation',

    groupDeletedN: '{n} objets retirés du plan',
    truppPlacedHere: 'déjà ici',
  },
  tafel: {
    templateTitle: 'Modèle',
    plakatName: 'Première affiche (CSSP)',
    plakat: {
      heading: 'Première conduite',
      prefilled: 'prérempli depuis l’intervention',
      title: 'Intervention',
      address: 'Adresse',
      alarm: 'Alarme',
      el: 'Chef d’intervention',
      problems: 'Saisie des problèmes',
      front: 'Front',
      ordnung: 'Ordre',
      sanitaet: 'Sanitaire',
      spezial: 'Problèmes spéciaux',
      massnahmen: 'Mesures',
      mittel: 'Moyens',
      verbindungen: 'Liaisons',
      absprachen: 'Points à convenir',
      was: 'Quoi / où',
      wer: 'Qui',
      wann: 'Quand',
      formation: 'Formation',
      pers: 'Pers.',
      wo: 'Où',
      funktion: 'Fonction / emplacement',
      kanal: 'Canal',
      ruf: 'Indicatif / tél.',
      newProblem: 'Problème …',
      newRow: 'Nouvelle ligne …',
      note: 'Mot-clé',
      trendNone: 'Tendance ouverte',
      trendUp: 's’aggrave',
      trendSame: 'stable',
      trendDown: 's’améliore',
      trendTitle: 'Tendance : {trend} – toucher pour changer',
      done: 'Fait',
      weatherTag: 'Météo',
      wind: 'Vent {dir} {speed} km/h',
      absprachenDefaults: ['Emplacement de la direction d’intervention', 'Accès / axe de sauvetage', 'Zone d’attente', 'Point de rassemblement des patients', 'Alimentation en eau', 'Bouclage'],
      inserted: 'Première affiche insérée',
      edited: 'Affiche modifiée',
      remove: 'Retirer l’affiche',
      removeTitle: 'Retirer l’affiche ?',
      removeMsg: 'Tout ce qui est inscrit sur l’affiche part avec. Annuler la ramène.',
      removed: 'Affiche retirée',
      reportTitle: 'Première conduite (affiche)',
    },
  },
}
