// English (en) — a full translation overlay deep-merged over German (./de).
//
// Fire-service domain terms are kept recognizable to an English-speaking commander; where a
// Swiss term has no clean English equivalent the established translation is used (Lage →
// "Situation", Atemschutz → "SCBA", Trupp → "team/crew", Verlauf → "Log").
//
// Two groups are deliberately NOT translated and fall back to German on purpose:
//   • intake.kategorien / intake.kategorieGuess — these mirror the backend's VKF
//     Schadenkategorien (app/divera.py TYPE_LABELS) and match against German Divera keyword
//     text; translating them would desync category derivation.
// Everything omitted here renders the German base string (deepMerge fallback).

import type { Copy, Localizable } from './index'

export const en: Localizable<Copy> = {
  loadingSubtitle: 'Loading map & symbol library …',
  modes: { map: 'Situation', plans: 'Plan', checklists: 'Checklist', atemschutz: 'SCBA', anwesenheit: 'Attendance', mittel: 'Resources' },
  navRail: { map: 'Map', plansGroup: 'Plans', objectSwitch: 'Choose object', assign: 'Assign plan', expand: 'Expand', collapse: 'Collapse', resize: 'Resize bar' },
  panels: { layers: 'Layers', history: 'Log' },
  layerPanel: {
    stateVisible: 'visible, hide',
    stateHidden: 'hidden, show',
  },
  help: {
    menu: 'Features & help',
    title: 'What can KP Front do?',
    subtitle: 'Every feature at a glance — built to be usable at 3am without practice.',
    contents: 'Contents',
    close: 'Close',
    introFallback: 'KP Front is your brigade’s digital situation and incident command: a tactical situation map, object plans, SCBA monitoring and a shared log — all live across multiple devices at once.',
    sections: [
      {
        id: 'ueberblick', title: 'Overview', icon: 'info',
        blocks: [
          { kind: 'intro' },
          { kind: 'sub', text: 'The four work areas (left rail)' },
          { kind: 'list', items: [
            '**Situation** — the tactical map with symbols, lines, areas and the utility layers.',
            '**Plan** — the object plans (Modules 1–6, building outlines) as a whiteboard, storey by storey.',
            '**Checklist** — runnable incident checklists.',
            '**SCBA** — monitoring of deployed teams with time and pressure.',
          ] },
          { kind: 'note', text: 'Guiding principle: usable at 3am, after six months without practice. Recognition over recall, usable with gloves and offline.' },
        ],
      },
      {
        id: 'navigation', title: 'Navigation & interface', icon: 'cursor',
        blocks: [
          { kind: 'lead', text: 'Three fixed zones: the area rail on the left, the incident bar on top, the tool rail on the right.' },
          { kind: 'sub', text: 'Left rail' },
          { kind: 'list', items: [
            'Switches the work area: **Map** (Situation), the **Plans** (Modules/buildings), **Checklist**, **SCBA**.',
            'At the bottom, **Choose object** swaps the building/object of the plans.',
            'In Situation mode, **Layers** and the **Map** toggle are pinned at the bottom — always visible.',
            'Dragging the right edge of the rail expands it with labels, or collapses it again.',
          ] },
          { kind: 'sub', text: 'Top incident bar' },
          { kind: 'list', items: [
            'On the left, the incident name with the **Menu** (switch incident, day/night, this help …) and the clock.',
            'On the right, **Undo/Redo**, **Log** and **+ Entry**.',
          ] },
          { kind: 'sub', text: 'Right tool rail' },
          { kind: 'list', items: [
            'The drawing and placement tools; pinned at the bottom, map navigation (zoom, fit, coordinates).',
          ] },
        ],
      },
      {
        id: 'lage', title: 'Situation — map', icon: 'map',
        blocks: [
          { kind: 'lead', text: 'The tactical map over the real map background (operational area and surroundings).' },
          { kind: 'list', items: [
            '**Base map** (top of the layers panel) switches the background: Carto, OpenStreetMap or satellite.',
            '**Zoom in/out**, **Fit** and **Capture coordinates** at the bottom of the right rail. When capturing, tap the map to fix a point (LV95 + WGS84); the compass re-aligns to north.',
            '**Wind** is shown continuously (direction + temperature) so the spread direction is immediately clear.',
            '**Vehicles/resources** appear live via GPS (name + heading), your own position as a calm blue dot.',
          ] },
        ],
      },
      {
        id: 'ebenen', title: 'Layers & data', icon: 'layers',
        blocks: [
          { kind: 'lead', text: 'Via **Layers** you show the utility and hazard data — ordered by type.' },
          { kind: 'list', items: [
            '**Situation** — tactical symbols, vehicles, sketches & notes.',
            '**Water** — hydrants, mains, valves, sources.',
            '**Sewer** — foul/combined, storm/clean, manholes / gullies.',
            '**Gas** — mains.',
            '**Power** — lines, PV systems.',
            '**Hazards** — flooding, inundation depth.',
          ] },
          { kind: 'lead', text: 'Every layer can be shown/hidden and its opacity adjusted.' },
          { kind: 'list', items: [
            '**Download map for offline** (in the Layers area) pre-loads map tiles, plans, symbols and geodata for the incident location.',
          ] },
          { kind: 'note', text: 'The utility data covers the configured operational area and is available locally — it works offline too.' },
        ],
      },
      {
        id: 'zeichnen', title: 'Drawing & symbols', icon: 'pen',
        blocks: [
          { kind: 'lead', text: 'Tools in the right rail in Situation mode.' },
          { kind: 'list', items: [
            '**Symbol** — the tactical symbol (FKS/VKF). Quick-pick of the most common symbols or search the whole library. Tap to place; use the lock to set several in a row.',
            '**Select** — tap objects, move them, adjust in the editor.',
            '**Multi** — lasso: select several symbols/drawings at once.',
            '**Line** — drag or tap points; the style is chosen afterwards in the editor: **Freehand**, **Arrow** or **Rescue axis**.',
            '**Area** — tap corner points (area shown from 3 points); drag/insert/delete corners.',
            '**Cordon** — drag from the centre to the edge to set the radius in metres (fill adjustable).',
            '**Note** — free text directly on the map.',
            '**Measure** — distance (length + elevation profile) or area (area + perimeter). Drag points to move, tap the line to insert intermediate points, right-click to remove a point.',
          ] },
          { kind: 'sub', text: 'Symbol presets' },
          { kind: 'lead', text: 'Each symbol brings only the controls that make sense: **Rotation** for directional symbols (arrows, ladders, walls), **Count** where several matter, **Storey** or a **storey range** (e.g. stairs/lift), **Spread** for damage situations — plus matching input fields (e.g. name, substance, status).' },
        ],
      },
      {
        id: 'plan', title: 'Plan — modules & buildings', icon: 'doc',
        blocks: [
          { kind: 'lead', text: 'One whiteboard per object over the module/building plans. Storey by storey, with its own tools.' },
          { kind: 'list', items: [
            '**Symbol**, **Select**, **Draw** (colour/width/line style), **Note** (text), **Team**.',
            '**Storeys** as a stack: use the **UF/BF** buttons on the plan to add a floor above/below.',
            '**Zoom/Fit** at the bottom of the tool rail, just like on the map.',
            '**Teams** (crews) as coloured markers; toggling **Trails** shows their path. Team chips whose crew is "out" are greyed out/struck through.',
          ] },
        ],
      },
      {
        id: 'atemschutz', title: 'SCBA monitoring', icon: 'gauge',
        blocks: [
          { kind: 'lead', text: 'Gap-free monitoring of every SCBA team per FKS — the safety signal is the **time since last radio contact**, not an estimated remaining time.' },
          { kind: 'sub', text: 'Create a team' },
          { kind: 'list', items: [
            '**Assignment** first: pick the type (Rescue · Extinguish · Search · Secure · Recon · Other), the **target / location** in plain text (e.g. "2nd floor, flat on the left") and optionally the line/hose no.',
            '**Team & pressure**: record the team leader and member (already deployed names as quick-pick) and set the entry pressure (bar).',
          ] },
          { kind: 'sub', text: 'Monitoring per team' },
          { kind: 'list', items: [
            'Large: the clock **Since last contact**: green **Contact ok** → amber **Contact due** → red **Overdue** (no contact within ~5 min) with an alarm.',
            '**Contact** (large button) confirms radio contact and resets the clock.',
            '**Pressure** adjusted directly with ± and applied with **Confirm** — that counts as contact and is logged; a misclick without confirming changes nothing. Low pressure turns red.',
            'Status **Registered → Deployed → Withdrawing → Out**. **Withdraw** can be reverted with **Continue**; an out team returns to monitoring with **Re-deploy** (new cylinder).',
            '**Log** per team (expandable) shows every contact with time and pressure.',
            '**Edit** (pencil) adjusts assignment, target/storey or team mid-incident.',
            'Overdue teams move to the top and a counter appears; the **alarm sound** can be muted per device (bell). Everything lands in the log.',
            'Each team can be placed on the plan (the "show on plan" button).',
          ] },
        ],
      },
      {
        id: 'checkliste', title: 'Checklist', icon: 'check',
        blocks: [
          { kind: 'lead', text: 'Two columns: runnable tasks and a searchable tactics reference.' },
          { kind: 'list', items: [
            '**Tasks** — incident checklists (e.g. command support, situation report) with progress; tick items off, branches follow multi-step procedures.',
            '**Tactics · keywords** — search a keyword and open the matching entry (with hazard colour code and sketches).',
            'When a Divera alarm is taken over, a matching keyword is suggested automatically.',
          ] },
          { kind: 'lead', text: 'The state is preserved and synced to all devices.' },
        ],
      },
      {
        id: 'verlauf', title: 'Log & entry', icon: 'history',
        blocks: [
          { kind: 'lead', text: 'A shared, running log across Situation and Plan — the incident chronicle.' },
          { kind: 'list', items: [
            '**+ Entry** (top right): a short tap opens text input; **press and hold** records a **voice note**. Photos can be attached too.',
            'Significant actions (symbol placed, drawing created/removed …) land in the log automatically.',
            '**Undo/Redo** applies to Situation and Plan.',
            'A log entry with a location jumps back to the spot in map or plan when tapped; photos and voice notes can be opened/played directly in the log.',
            '**Start replay** plays Situation and Plan back to an earlier point in time (time slider; editing is locked while doing so).',
          ] },
        ],
      },
      {
        id: 'einsatz', title: 'Manage incidents', icon: 'swap',
        blocks: [
          { kind: 'lead', text: 'Everything in the incident menu (name top left).' },
          { kind: 'list', items: [
            '**Switch incident** between open incidents; **New incident** (location selectable on the map).',
            '**Divera pool** — take over incoming alarms.',
            '**Incidents** — open the archive / earlier incidents.',
            '**Archive current** closes out the running incident.',
          ] },
        ],
      },
      {
        id: 'sync', title: 'Multi-device & offline', icon: 'check',
        blocks: [
          { kind: 'lead', text: 'All devices see the same incident live.' },
          { kind: 'list', items: [
            'Changes are shared automatically; the sync badge on top shows the state (saved/pending).',
            'Concurrent editing is merged per object (latest change wins).',
            '**Read-only**: viewers and phones see the situation live, without the tactical tools.',
          ] },
        ],
      },
      {
        id: 'bedienung', title: 'Operation & day/night', icon: 'move',
        blocks: [
          { kind: 'sub', text: 'Tap & drag (touch/iPad)' },
          { kind: 'list', items: [
            'One finger pans the map/plan; two fingers zoom (pinch).',
            'Dragging a lasso with **Multi** selects several objects; selected objects are moved by dragging.',
          ] },
          { kind: 'sub', text: 'Mouse' },
          { kind: 'list', items: [
            'Scroll to zoom; **right-click** (or long press) on a measure/line point removes it, clicking a line inserts an intermediate point.',
          ] },
          { kind: 'sub', text: 'Keys' },
          { kind: 'list', items: [
            '[[Esc]] cancels the active tool or clears the selection.',
            '[[Del]] / [[Backspace]] deletes the selection (not while typing in a field).',
          ] },
          { kind: 'sub', text: 'Day / night' },
          { kind: 'list', items: [
            'Toggled in the incident menu — night mode dims the map and interface for the dark.',
          ] },
        ],
      },
    ],
  },
  baseMap: 'Map',
  floor: { eg: 'GF', og: '{n}F', ug: 'B{n}' },
  hoseHint: '~{n} hose lengths',
  noHistoryRows: 'No events recorded yet',
  symbolSearchPlaceholder: 'Search tactical symbol …',
  noSymbolMatches: 'No matches',
  close: 'Close',
  closeDialog: 'Close',
  sheetGrip: 'Adjust detail height',
  edit: 'Edit',
  primarySymbol: { label: 'Symbol' },
  done: 'Done',
  cancel: 'Cancel',
  exerciseBadge: 'Exercise',
  keepPlacing: 'Place several',
  delete: 'Remove',
  undo: 'Undo',
  redo: 'Redo',
  play: 'Play',
  clear: 'Clear',
  mapTools: [
    { id: 'select', icon: 'select', label: 'Select', kind: 'tool' },
    { id: 'lasso', icon: 'marquee', label: 'Multi', kind: 'tool' },
    { id: 'sep-symbol', sep: true, icon: '', label: '' },
    { id: 'symbol-slot', slot: true, icon: '', label: '' },
    { id: 'line', icon: 'pen', label: 'Line', kind: 'tool' },
    { id: 'area', icon: 'area', label: 'Area', kind: 'tool' },
    { id: 'circle', icon: 'circle', label: 'Cordon', kind: 'tool' },
    { id: 'sep-anno', sep: true, icon: '', label: '' },
    { id: 'note', icon: 'type', label: 'Note', kind: 'tool' },
    { id: 'team', icon: 'flag', label: 'Team', kind: 'tool' },
    { id: 'measure', icon: 'measure', label: 'Measure', kind: 'tool' },
  ],
  planTools: [
    { id: 'pan', icon: 'select', label: 'Select' },
    { id: 'lasso', icon: 'marquee', label: 'Multi' },
    { id: 'sep-symbol', sep: true, icon: '', label: '' },
    { id: 'symbol-slot', slot: true, icon: '', label: '' },
    { id: 'line', icon: 'pen', label: 'Line' },
    { id: 'area', icon: 'area', label: 'Area' },
    { id: 'text', icon: 'type', label: 'Note' },
    { id: 'resource', icon: 'flag', label: 'Team' },
    { id: 'sep-measure', sep: true, icon: '', label: '' },
    { id: 'measure', icon: 'measure', label: 'Measure' },
  ],
  nav: {
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit',
    resetNorth: 'Align north',
    centerIncident: 'Center on incident',
    coords: 'Pick coordinates',
    coordsHint: 'Tap the map to capture',
    coordsLocked: 'Captured — tap the button for a new point',
    themeLabel: 'Appearance',
    autoMode: 'Automatic',
    dayMode: 'Day',
    nightMode: 'Night',
  },
  toast: {
    recordingStarted: 'Recording audio …',
    audioSaved: 'Audio note saved ({secs}s)',
    micDenied: 'No microphone access – noted as placeholder',
    merged: 'Changes merged',
  },
  mapHints: {
    placeSymbol: 'Tap the map to place "{name}"',
    areaDraft: 'Tap the area corners on the map',
    placeNote: 'Tap the map to drop a note',
    placeShape: 'Tap the map to place {name}',
  },
  dockHints: {
    symbol: 'Tap the map to place the symbol. Enable the lock to place several in a row.',
    lasso: 'Drag a frame around several objects with one finger. Two fingers still pan the map.',
    line: 'Drag on the map or tap points to draw a line. Choose the style (Freehand · Arrow · Rescue axis) afterwards in the editor.',
    area: 'Tap at least three corners on the map, then finish with the checkmark.',
    circle: 'Drag from the center outward to set the radius in metres. Adjust radius and fill afterwards in the editor.',
    note: 'Tap the map to drop a note.',
    team: 'Tap the map and pick the crew from the list. Drag to move it.',
    shape: 'Tap the map to place the shape. Enable the lock to place several in a row.',
    measure: 'Tap points on the map. Distance shows length and elevation profile, area shows surface and perimeter. Drag points to move, tap a line for an intermediate point, right-click a point to remove it.',
  },
  map: {
    incidentHere: 'Incident',
    youHere: 'My location',
  },
  intake: {
    titleNew: 'Open incident',
    titleDivera: 'Take over alarm',
    diveraHint: 'Imported from the alarm source — review and correct if needed.',
    locationHead: 'Location',
    addressLabel: 'Address',
    addressPlaceholder: 'Street no, ZIP city',
    addressSearching: 'Searching …',
    addressNoHits: 'No address found',
    objectButton: 'Object from fire plans',
    objectSearchPlaceholder: 'Search object or address …',
    objectNear: 'Nearby',
    objectNoHits: 'No objects found',
    objectPlans: (n: number) => (n === 1 ? '1 plan' : `${n} plans`),
    objectNoPlans: 'no plans',
    mapPickButton: 'Set on map',
    hereButton: 'Here',
    hereFailed: 'Location unavailable',
    coordSet: 'Coordinate set',
    coordNone: 'No location — will open without a coordinate',
    coordClear: 'Remove location',
    keywordHead: 'Keyword & category',
    titleLabel: 'Keyword / title',
    titlePlaceholder: 'e.g. Building fire, school',
    categoryLabel: 'Category',
    exerciseToggle: 'Exercise — not counted in incident statistics',
    detailsLabel: 'Message text (optional)',
    detailsPlaceholder: 'Additional details for the report',
    open: 'Open incident',
    opening: 'Opening …',
    cancel: 'Cancel',
    errorCreate: 'Error while creating',
    errorTake: 'Take-over failed',
    errorUpdate: 'Update failed',
    editTitle: 'Edit incident data',
    back: '← Back',
    save: 'Save',
    saving: 'Saving …',
    created: 'Incident created',
    taken: 'Alarm taken over',
    updated: 'Incident updated',
    alarmierungHead: 'Dispatch',
    alarmTime: 'Alarm time',
    alarmMessage: 'Alarm message',
    addressUnknown: 'Address unknown',
    alarmOpen: 'Open',
    alarmOpening: 'Opening …',
    dismiss: 'Dismiss',
    manualIncident: 'Manual incident',
    attach: 'Add to existing incident',
    attachShort: 'To incident',
    attachConfirmTitle: 'Add “{alarm}” to this incident?',
    attachHint: 'The dispatch message lands in the log, GPS times follow automatically. The incident\u2019s keyword and location stay unchanged.',
    attachConfirm: 'Add',
    attachDone: 'Alarm added to the incident',
    attachError: 'Adding failed',
    newDiveraAlarm: 'New alarm',
    hide: 'Hide',
    fromDivera: 'Taken from the alarm source',
    locationSet: 'Location set',
    noLocationOnMap: 'No location — set on map',
    ok: 'Looks good',
    // DISPLAY labels for the category select — keyed by the German category value (the submitted
    // value stays German; only the option text is localized).
    kategorienLabels: {
      'Brandbekämpfung': 'Firefighting',
      'Strassenrettung': 'Road rescue',
      'Technische Hilfeleistung': 'Technical assistance',
      'Elementarereignis': 'Natural hazard',
      'Ölwehr': 'Oil response',
      'Chemiewehr': 'Chemical response',
      'Strahlenwehr': 'Radiation response',
      'Einsatz Bahnanlagen': 'Railway operation',
      'BMA / unechte Alarme': 'Fire alarm / false alarms',
      'Gerettete Tiere': 'Animal rescue',
      'Dienstleistungen': 'Services',
      'Diverse Einsätze': 'Other operations',
    },
  },
  // Tactical-symbol display labels, keyed by the RAW FireGIS name. Stored identity stays the raw
  // name; only the label localizes. Missing keys fall back to the German label / displayNames.
  symbolNames: {
    'VKF Feuer': 'Fire',
    'VKF Rettungen': 'Rescue',
    'VKF Unfall': 'Accident',
    'VKF Gefaehrliche Stoffe': 'Hazmat',
    'VKF Wasser': 'Water',
    'FW Gefahr allgemein': 'Hazard',
    'FW Gefahr Tafel': 'Hazard placard',
    'FW Gefahr Radioaktiv': 'Radioactive',
    'FW Gefahr Ex': 'Explosion',
    'FW Gefahr G': 'Gas',
    'FW Gefahr C': 'Chemical',
    'FW Gefahr W': 'Water',
    'FW Elektroanlage': 'Electrical installation',
    'VKF Patientensammelstelle': 'Casualty collection point',
    'VKF Sanitaetshilfsstelle': 'Medical aid post',
    'VKF Totensammelstelle': 'Fatalities collection point',
    'VKF Sammelstelle': 'Uninjured',
    'FW Sammelplatz': 'Assembly point',
    'FW Warteraum': 'Holding area',
    'FW Verwundetennest': 'Casualty nest',
    'VKF Bereich Sanitaet': 'Medical',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Incident commander',
    'FW Offizier': 'Officer',
    'VKF Kontrollposten': 'Checkpoint',
    'VKF Informationszentrum': 'Information centre',
    'VKF Bereich Materialdepot': 'Materials depot',
    'FW Absperrung': 'Cordon',
    'VKF Verkehrssperre ueberwacht': 'Road closure',
    'VKF Drehleiter': 'Turntable ladder',
    'VKF Hubretter': 'Aerial platform',
    'VKF Fahrzeug': 'Vehicle',
    'VKF Pumpe Typ2': 'Pump',
    'VKF Helilandeplatz': 'Helicopter landing site',
    'VKF Luefter mobil': 'Fan',
    'FW Entrauchung': 'Smoke extraction',
    'FW Kleinloeschgeraet': 'Small extinguisher',
    'FW Sprungretter': 'Jump rescue cushion',
    'FW Leiter': 'Ladder',
    'SI Ueberflurhydrant': 'Pillar hydrant',
    'SI Unterflurhydrant': 'Underground hydrant',
    'VKF Innenhydrant': 'Indoor hydrant',
    'SI Wasserloeschposten': 'Hose reel post',
    'WV Loeschweier': 'Fire pond',
    'SI Wasserbezugsort': 'Water draw point',
    'SI Wasserdruckversorgung': 'Pressurised water supply',
    'GB Lift': 'Lift',
    'GB Kamin': 'Chimney',
    'GB Abzug': 'Vent',
    'SI Schieber': 'Valve',
    'GB Elektrotableau': 'Electrical panel',
    'GB Sprinklerzentrale': 'Sprinkler control room',
    'GB Brandmeldezentrale': 'Fire alarm control panel',
    'GB BMA Melder': 'Fire detector',
    'GB Fernsignaltableau': 'Remote signal panel',
    'GB Schluesseldepot': 'Key depot',
    'GB BA Wand F30': 'Wall F30',
    'GB BA Wand F60': 'Wall F60',
    'GB BA Wand F180': 'Wall F180',
    'GB Ture BS R30': 'Door R30',
    'GB Ture Durchgang': 'Passage',
    'GB Treppe 8': 'Stairs',
    'SI Nordpfeil': 'North arrow',
    'SI Windrichtung': 'Wind direction',
    'VKF Bereich Polizei': 'Police',
    'VKF Bereich Chemiewehr': 'Chemical response',
    'VKF Bereich Zivilschutz': 'Civil protection',
    'VKF Bereich Feuerwehr': 'Fire service',
  },
  // Symbol-palette category headings, keyed by the German category key.
  symbolCategories: {
    'Schadenlage': 'Damage situation',
    'Gefahren': 'Hazards',
    'Gebäude': 'Building',
    'Wasser': 'Water',
    'Führung': 'Command',
    'Personen / Sanität': 'People / Medical',
    'Partner': 'Partners',
  },
  measure: {
    modeLine: 'Distance',
    modeArea: 'Area',
    clear: 'Reset',
    deleteNode: 'Right-click to remove',
    distance: 'Distance',
    perimeter: 'Perimeter',
    area: 'Area',
    hoses: 'Hoses',
    profile: 'Elevation profile',
    ascent: 'Ascent',
    descent: 'Descent',
    min: 'Lowest',
    max: 'Highest',
    profileLoading: 'Loading elevation profile …',
    profileNone: 'No elevation profile available',
    hintLine: 'At least 2 points for the distance',
    hintArea: 'At least 3 points for the area',
  },
  shapes: {
    sectionTitle: 'Shapes',
    kindLabel: 'Shape',
    color: 'Color',
    rotateHint: 'Drag the handle to rotate',
    resizeHint: 'Drag the corner to scale',
    names: { arrow: 'Arrow', cloud: 'Smoke', square: 'Rectangle' },
  },
  log: {
    noMicrophone: 'Audio note (no microphone access)',
    audioNote: 'Audio note',
    symbolPlaced: 'Symbol "{name}" placed',
    shapePlaced: '{name} placed',
    notePlaced: 'Note placed',
    teamPlaced: '{name} placed on the map',
    areaDrawn: 'Area drawn',
    circleDrawn: 'Cordon drawn',
    drawingCreated: 'Drawing created',
    objectMoved: '{name} moved',
    objectDeleted: '{name} removed',
    drawingDeleted: 'Drawing removed',
    undo: 'Action undone',
    redo: 'Action redone',
    journalNote: 'Note',
  },
  journal: {
    open: 'Log',
    add: 'Entry',
    addHint: 'Tap for an entry · hold for a voice message',
    title: 'Log',
    empty: 'No events recorded yet',
    surfaceMap: 'Situation',
    surfacePlan: 'Plan',
    replay: 'Start replay',
    replayHint: 'Replay situation and plan at an earlier point in time',
    composerTitle: 'Log entry',
    textPlaceholder: 'What happened? Report, observation, decision …',
    record: 'Record',
    recordStop: 'Stop recording',
    dictate: 'Dictate',
    dictateStop: 'Stop dictation',
    dictateListening: 'Listening …',
    discardAudio: 'Discard recording',
    audioUpload: 'Upload audio',
    audioImportLabel: 'External audio recording',
    audioStartLabel: 'Recording started',
    audioStartHint: 'Check the start time against the voice memo.',
    audioStartConfirm: 'Confirm start time',
    audioImportedNote: 'External audio recording ({duration})',
    audioDiscardImport: 'Remove audio file',
    audioUploading: 'Uploading …',
    audioOffline: 'Audio upload needs a connection. Select the file again later.',
    audioTooLarge: 'Audio file is too large. Maximum: {max} MB.',
    audioUnsupported: 'This audio format is not supported.',
    audioUploadFailed: 'Upload failed. Check the connection and try again.',
    playerOpen: 'Listen through',
    editEntry: 'Edit text',
    removeEntry: 'Remove entry',
    entryRemoved: 'Entry removed',
    playerEntryHere: 'Entry at this point',
    playerEntryPlaceholder: 'What was said? Report, decision …',
    playerEntries: 'Entries in this recording',
    playerNoEntries: 'No entries in this time window yet.',
    playerSkipBack: '15 seconds back',
    playerSkipFwd: '15 seconds forward',
    playerSpeed: 'Playback speed',
    playerSeek: 'Playback position',
    playerOffline: 'Playback needs a connection.',
    sttTranscribe: 'Transcribe',
    sttRunning: 'Transcription running … This can take a few minutes.',
    sttFailed: 'Transcription failed: {error}',
    sttRetry: 'Try again',
    sttErrorGeneric: 'server not reachable',
    sttBanner: '{n} drafts detected — review and take over.',
    sttTakeAll: 'Take all',
    sttTake: 'Take',
    sttDismiss: 'Dismiss',
    sttEmpty: 'No speech detected.',
    sttTaken: 'Entry added',
    photo: 'Photo',
    photoNote: 'Photo',
    discardPhoto: 'Discard photo',
    pinMap: 'Pin to current map center',
    pinPlan: 'Pin to current plan center',
    send: 'Record',
    saved: 'Log entry recorded',
    transcriptPlaceholder: 'Add transcript',
    transcriptSave: 'Save',
    transcriptEdit: 'Edit transcript',
    transcriptAdd: 'Add transcript',
    nachtrag: 'Addendum',
    attendanceConflict: 'Attendance for {name}: diverging entries from QR capture and command post were merged — please review.',
    modeEntry: 'Entry',
    modeReminder: 'Reminder',
    reminderTextPlaceholder: 'Remind about what? e.g. check fan, feedback to command …',
    reminderWhen: 'Due in',
    reminderExact: 'Time',
    reminderChipLabel: '+{n} min',
    reminderTomorrow: ' · tomorrow',
    hourUp: 'Hour +', hourDown: 'Hour −', minUp: 'Minute +', minDown: 'Minute −',
    reminderSend: 'Set reminder',
    reminderSaved: 'Reminder set',
    reminderNeedsDue: 'Choose a due time',
    reminderCreated: 'Reminder: {text}',
    dueTitle: 'Reminder due',
    dueOne: 'Reminder due',
    dueMany: '{n} reminders due',
    dueDone: 'Done',
    dueSnooze: '+10 min',
    dueOpen: 'Open in log',
    openCount: '{n} open',
    doneLog: 'Reminder done: {text}',
    snoozeLog: 'Reminder +{mins} min: {text}',
    dueAtLabel: 'due {t}',
    overdueLabel: 'overdue',
    doneState: 'done',
    markDoneTitle: 'Mark as done',
  },
  errors: {
    noMicrophone: 'No microphone access. Audio note recorded as a placeholder.',
    updateFailed: 'Update failed',
  },
  atemschutz: {
    title: 'SCBA monitoring',
    subtitle: 'Gap-free monitoring of every SCBA team',
    empty: 'No team under monitoring yet.',
    emptyHint: 'Create a team to start monitoring.',
    newTrupp: 'Create team',
    formCreateTitle: 'Create team',
    formEditTitle: 'Edit team',
    formRedeployTitle: 'Re-deploy',
    sectionAuftrag: 'Assignment',
    sectionTeam: 'Team',
    auftragLabel: 'Type',
    // DISPLAY labels for the Auftrag types, keyed by the auftrag id (stored value stays the id).
    auftragLabels: {
      retten: 'Rescue',
      loeschen: 'Extinguish',
      absuchen: 'Search',
      sichern: 'Secure',
      erkunden: 'Reconnoitre',
      anderes: 'Other',
    },
    zielLabel: 'Assignment / target',
    zielPlaceholder: 'e.g. 2nd floor, flat on the left, person missing',
    zielOtherPlaceholder: 'Describe the assignment',
    leaderLabel: 'Team leader',
    leaderPlaceholder: 'Team leader name',
    memberLabel: 'Member',
    memberPlaceholder: 'Name (optional)',
    addMember: 'Add member',
    lineNumberLabel: 'Line / hose no.',
    lineNumberPlaceholder: 'e.g. 1',
    pressureLabel: 'Entry pressure (bar)',
    newPressureLabel: 'New entry pressure (bar)',
    funkkanalSection: 'Radio channel',
    funkkanalDown: 'Radio channel down',
    funkkanalUp: 'Radio channel up',
    funkkanalUnit: 'Channel',
    clearName: 'Clear name',
    notPresent: 'not present',
    noRoster: 'No crew available',
    typeName: 'Type a name …',
    assignedConflict: '{name} is already in another team.',
    cancel: 'Cancel',
    save: 'Save',
    start: 'Register team',
    reenterSubmit: 'Deploy',
    sinceContact: 'Since last contact',
    elapsed: 'Deployment time',
    estimated: 'Expected (estimate)',
    estimatedHint: 'Planning aid — estimated using a {liters} L cylinder and {rate} L/min consumption until enough pressure history exists. Does not replace a pressure report.',
    estimatedHintHistory: 'Planning aid — projected from this team’s confirmed pressure consumption. Does not replace a pressure report.',
    estimatedSourceHistory: 'from {count} pressure values · as of {time}',
    estimatedSourceFallback: '{rate} L/min assumed · as of {time}',
    currentPressure: 'Pressure',
    lowestPressure: 'Lowest',
    lineField: 'Line',
    edit: 'Edit',
    pressureDown: '10 bar less',
    pressureUp: '10 bar more',
    pressureConfirm: 'Confirm',
    pressureConfirmHint: 'Confirm new pressure — counts as contact',
    verlauf: 'Log',
    readingKind: { entry: 'Deployed', contact: 'Contact', pressure: 'Pressure' },
    clockOk: 'Contact ok',
    clockWarn: 'Contact due',
    clockOverdue: 'Overdue',
    overdueBadge: '{n} overdue',
    actEnter: 'Deployed',
    actContact: 'Contact',
    actRueckzug: 'Withdraw',
    actContinue: 'Continue',
    actExit: 'Out',
    actReenter: 'Re-deploy',
    exitConfirmTitle: 'Team out?',
    exitConfirmMsg: 'Mark the team as out and end monitoring?',
    remove: 'Remove',
    removedToast: 'Team {name} removed',
    place: 'Place',
    placeWhere: 'Place where?',
    placeNoTarget: 'No plan available — create a building from the outlines first.',
    showOnPlan: 'Show on plan',
    showOnMap: 'Show on map',
    rosterLabel: 'Already recorded',
    preEntryHint: 'Not deployed yet — press "Deployed" once the team goes on air.',
    alarmOn: 'Alarm sound on',
    alarmOff: 'Alarm sound off',
    alarmNotifyTitle: 'SCBA overdue',
    alarmNotifyBody: 'Team {name} overdue — establish contact.',
    status: { angemeldet: 'Registered', aktiv: 'Deployed', rueckzug: 'Withdrawing', ueberfaellig: 'Overdue', raus: 'Out' },
    logRegister: 'Team {name} registered',
    logPlaced: 'Team {name} placed on plan',
    logPlacedMap: 'Team {name} placed on the map',
    placeLage: 'Situation map',
    logEntry: 'Team {name} deployed',
    logContact: 'Team {name}: contact confirmed',
    logPressure: 'Team {name}: pressure {bar} bar',
    logRueckzug: 'Team {name}: withdrawing',
    logContinue: 'Team {name}: deployment continued',
    logEdit: 'Team {name}: assignment updated',
    logExit: 'Team {name} out',
    logReenter: 'Team {name} re-deployed',
    logAlarm: 'SCBA alarm: team {name} – {status}',
  },
  lineDecor: {
    S: 'Foam branch',
    W: 'Water monitor',
    H: 'Water curtain',
    P: 'Powder gun',
  } as Record<string, string>,
  incidents: {
    migratedTitle: 'Migrated working state',
    geojsonNotJson: 'Not a valid JSON file.',
    geojsonNotFc: 'Not a GeoJSON FeatureCollection.',
    geojsonNotWgs84: 'Coordinates look like LV95, not WGS84 [lng, lat]. Reproject to EPSG:4326 first.',
  },
  entities: {
    photoLabel: 'Photo',
    photoSubtitle: 'Photo pin',
    noteSubtitle: 'Note',
    fallbackObjectName: 'Object',
  },
  notes: {
    deleteTitle: 'Remove note?',
    deleteMsg: 'This note contains text. Really remove it?',
  },
  whiteboard: {
    documentListTitle: 'Plan documents',
    fit: 'Fit',
    pan: 'Select',
    team: 'Team',
    draw: 'Draw',
    text: 'Note',
    symbol: 'Symbol',
    line: 'Line',
    area: 'Area',
    dockHints: {
      draw: 'Drag on the plan to draw freely. Choose color, width and line style below.',
      line: 'Tap corner points. Double-tap or "Done" closes the line. Choose the style below.',
      area: 'Tap corner points (at least 3). Double-tap or "Done" closes the area.',
      text: 'Tap the plan to drop a note.',
      resource: 'Tap the plan to place a team. Drag to move it.',
      scale: 'Tap the two endpoints of the printed scale bar, then enter the real length. Lines with "Length" then show real metres.',
      measure: 'Tap points on the plan. "Distance" shows the length, "Area" the surface + perimeter — in real metres once the scale is calibrated. Drag points to move, double-tap to remove one.',
    },
    scale: {
      tool: 'Scale',
      promptTitle: 'Set scale',
      promptBody: 'Real length of the captured distance (e.g. the scale bar):',
      unit: 'm',
      confirm: 'Apply',
      cancel: 'Cancel',
      chipCalibrated: 'Scale: ref. {m} m',
      chipUncalibrated: 'Scale not calibrated',
      recalibrate: 'Recalibrate',
      calibrate: 'Calibrate scale',
      calibrateHint: 'Tap two points of the scale bar',
      stale: 'Plan changed — recheck the scale',
      saved: 'Scale calibrated ({m} m reference)',
      needsCalibration: 'Set scale: tap the two ends of the scale bar',
    },
    finishShape: 'Done',
    cancelShape: 'Cancel',
    insertVertex: 'Insert point',
    dragVertex: 'Drag corner · double-tap to delete',
    groupDeleted: 'Selection removed',
    placeText: 'Note placed on plan',
    placeSymbol: 'Symbol "{name}" placed on plan',
    placeLine: 'Line drawn on plan',
    placeArea: 'Area drawn on plan',
    placeTeam: '{name} placed on plan',
    selectTrupp: 'Which team?',
    newTeam: 'New team',
    showTrupp: 'Show in SCBA',
    markPosition: 'Mark position',
    positionMarked: '{name}: position marked',
    clearTrail: 'Clear trail',
    clearTrailConfirm: 'Delete all {n} marked positions of {name}? The trail disappears from map and plan.',
    trailCleared: '{name}: trail cleared',
    teamColor: 'Color',
    trails: 'Trails',
    trailsOn: 'Show trails',
    trailsOff: 'Hide trails',
    deleteLocked: 'Team with recorded history — clear the trail first',
    drawCreated: 'Drawing created on plan',
    placeSymbolHint: 'Tap the plan to place "{name}"',
    textHint: 'Tap the plan to place text',
    teamHint: 'Tap the plan to place a team',
    textPlaceholder: 'Note ...',
    blankHint: 'Blank sheet — annotate with draw, text, symbol or team',
    osmLoading: 'Loading building outlines …',
    osmError: 'Building outlines (OSM) unreachable',
    osmEmpty: 'No buildings in this area',
    osmRetry: 'Reload',
    osmPickHint: 'Tap a building, then apply',
    osmTransfer: 'Apply ({n})',
    osmClear: 'Clear selection',
    addFloorUp: 'Add upper floor',
    addFloorDown: 'Add lower floor',
    removeFloor: 'Remove floor',
    removeFloorConfirm: '{floor} contains sketches or markers. Remove the floor anyway?',
    floorRemoved: 'Floor removed',
    floorAdded: 'Floor added',
    buildingReplaced: 'Building replaced',
    replaceBuilding: 'Choose another building',
    replaceBuildingConfirm: 'There are sketches on the floors. Choose another building and discard the existing floors?',
    otherObject: 'Other object',
    objectActive: 'Plans of "{name}"',
    objectReset: 'Reset to the next object',
    objectSwitchConfirmTitle: 'Load another object',
    objectSwitchConfirm: 'The plans of every module switch to "{name}". Change the current object?',
    objectSwitchConfirmCta: 'Load object',
    northLabel: 'N',
    northTitle: 'North direction — building rotated to its long axis',
    orientNorthUp: 'North up',
    orientLongAxis: 'Rotate to long axis',
  },
  contextPanel: {
    titlePlaceholder: 'Label ...',
    titleTypePick: 'Choose type …',
    floor: 'Floor',
    floorFrom: 'From floor',
    floorTo: 'To floor',
    floorNone: '–',
    floorClear: 'Reset',
    spread: 'Spread',
    spreadH: 'Horizontal',
    spreadV: 'Vertical',
    spreadBounded: 'Boundary',
    spreadBoundedTitle: 'Spread boundary (spread stopped)',
    spreadLeft: 'to the left',
    spreadRight: 'to the right',
    spreadUp: 'Upper floor (↑)',
    spreadDown: 'Lower floor (↓)',
    count: 'Count',
    rotation: 'Rotation',
    rotationVehicle: 'Vehicle',
    rotationFan: 'Fan',
    rotationLadder: 'Ladder',
    center: 'Center',
    resetGps: 'GPS',
    resetGpsTitle: 'Reset to GPS position and heading',
    rotateHint: 'Drag the handle to align',
    detailsTitle: 'Details',
    caption: 'Caption',
    captionDefault: 'Default',
    captionOff: 'Off',
    captionAuto: 'Auto',
    captionAll: 'All',
    notes: 'Notes',
    notesPlaceholder: 'General notes …',
    addField: 'Add field',
    removeField: 'Remove field',
    fieldKeyPlaceholder: 'Label',
    fieldValuePlaceholder: 'Value',
    // unField/stoffField are intentionally NOT translated — they are the detail-row DATA keys
    // the UN→substance lookup matches against the (language-independent) preset fields
    // ['UN-Nr','Stoff']; translating them would break the autofill. They fall back to German.
    unHazardTitle: 'Dangerous goods (ADR)',
    unClass: 'Class',
    unKemler: 'Hazard number',
    unLabels: 'Hazard labels',
    unPacking: 'Packing group',
    unNoMatch: 'UN no. not found in the ADR table',
    unWater: 'Reacts dangerously with water – do NOT use water!',
    unLookupLabel: 'Safety data sheet (GESTIS)',
    kemler: {
      '2': 'Gas (escaping under pressure or by reaction)',
      '3': 'Flammable liquid / gas',
      '4': 'Flammable solid',
      '5': 'Oxidising (fire-intensifying)',
      '6': 'Toxic / risk of infection',
      '7': 'Radioactive',
      '8': 'Corrosive',
      '9': 'Risk of spontaneous violent reaction',
    } as Record<string, string>,
    kemlerDoubled: 'Intensified hazard (doubled digit)',
  },
  drawingEditor: {
    area: 'Area',
    drawing: 'Drawing',
    circle: 'Cordon',
    radius: 'Radius',
    fill: 'Fill',
    move: 'Move',
    points: 'Points',
    preset: 'Style',
    color: 'Color',
    width: 'Width',
    lineStyle: 'Line',
    lineSolid: 'Solid',
    lineDashed: 'Dashed',
    label: 'Text',
    labelPlaceholder: 'Label …',
    areaLabelPlaceholder: 'e.g. Sector A / East section',
    marker: 'Marker',
    markerPlaceholder: 'e.g. R',
    arrow: 'Arrowhead',
    ending: 'Ending',
    endingNone: 'None',
    endingArrow: 'Arrow',
    endingTeilstueck: 'Section',
    content: 'Content',
    contentPlain: 'Water',
    lineNo: 'Line no.',
    floorTag: 'Floor',
    distance: 'Length',
    inputMode: 'Input',
    modeFreehand: 'Freehand',
    modeNodes: 'Points',
    on: 'On',
    off: 'Off',
    lock: 'Lock',
    lockHint: 'Locks the shape against accidental moves; tap the lock in the center to unlock.',
    unlockHold: 'Hold to unlock',
    unlocking: 'Unlocking …',
  },
  topBar: {
    offline: 'Offline',
    tiles: 'Tiles',
    recording: 'REC',
  },
  stepper: {
    less: 'less',
    more: 'more',
    reset: 'reset',
    typeToEnter: 'Tap to enter',
  },
  confirm: {
    ok: 'OK',
    cancel: 'Cancel',
  },
  combo: {
    customDefault: 'Enter …',
    empty: 'No choices',
  },
  login: {
    subtitle: 'Command support',
    pinEnter: 'Enter PIN',
    connectionFailed: 'Connection to the server failed',
    loadingRoster: 'Loading roster…',
    noUsers: 'No users configured',
    whoAreYou: 'Who are you?',
    loginFailed: 'Login failed',
    pleaseWait: 'Please wait a moment…',
    clearDigit: 'Delete',
  },
  errorBoundary: {
    title: 'Something went wrong',
    body: 'The view could not be loaded. Your local changes are saved and stay intact.',
    reload: 'Reload',
  },
  tabLock: {
    title: 'Open in another tab',
    hint: 'This tab is read-only — editing is active in the other tab.',
    takeOver: 'Edit here',
  },
  mapPicker: {
    title: 'Set location on map',
    hint: 'Tap the map to set the location',
    confirm: 'Use location',
  },
  weather: {
    label: 'Weather',
    details: 'Weather details',
    unavailable: 'Weather data currently unavailable',
    from: 'from',
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
    cardinalsLong: ['North', 'Northeast', 'East', 'Southeast', 'South', 'Southwest', 'West', 'Northwest'],
    windTitle: 'Wind {dir} ({deg}°)',
    detailsHint: ' — tap for details',
    meteoHint: ' — tap for MeteoSwiss details',
    windDir: 'Wind direction',
    windSpeed: 'Wind speed',
    gust: 'Gusts',
    precip: 'Precipitation',
    station: 'Station',
    source: 'Source',
    meteoRadar: 'MeteoSwiss precipitation radar',
    detailsUrl: 'https://www.meteoswiss.admin.ch/services-and-publications/applications/precipitation.html',
    conditions: {
      clear: 'Clear', fair: 'Fair', partly: 'Partly cloudy', overcast: 'Overcast',
      fog: 'Fog', drizzle: 'Drizzle', rain: 'Rain', snow: 'Snow',
      rainShowers: 'Rain showers', snowShowers: 'Snow showers', thunder: 'Thunderstorm', cloudy: 'Cloudy',
    },
  },
  pdf: {
    loading: 'Loading PDF…',
    failed: 'Could not load the PDF.',
    retry: 'Reload',
  },
  settings: {
    title: 'Settings',
    deviceGroup: 'Device',
    colorScheme: 'Color scheme',
    symbolSize: 'Symbol size',
    symbolCaptions: 'Captions',
    symbolCaptionsSub: 'Key value under the symbol',
    captionsOff: 'Off',
    captionsAuto: 'Auto',
    captionsAll: 'All',
    offlineRadius: 'Offline radius',
    offlineRadiusSub: 'Map & lines around the incident',
    elView: 'Incident-commander view',
    elViewSub: 'View only – journal & symbol details stay live',
    elViewOn: 'On',
    elViewOff: 'Off',
    deviceFoot: 'Applies to this device only. A smaller radius = faster, smaller offline download.',
    incidentGroup: 'Incident',
    contactInterval: 'SCBA radio contact',
    contactIntervalSub: 'Interval until contact is due (amber)',
    contactIntervalAria: 'Radio contact interval',
    grace: 'Grace period',
    graceSub: 'Red alarm after interval + grace',
    funkkanal: 'Radio channel',
    funkkanalSub: 'Default for new SCBA teams',
    syncedFoot: 'Synced with all devices',
    syncedFootViewer: ' · only the incident commander can change them',
    utilityGroup: 'Templates',
    blankSheet: 'Blank capture sheet (PDF)',
    blankSheetSub: 'Paper sheet to fill in by hand',
    blankSheetDownload: 'Download',
    blankSheetFailed: 'PDF failed — try again.',
  },
  offline: {
    title: 'Offline readiness',
    syncNow: 'Sync now',
    syncedAgo: 'Incident data synced {ago}',
    offline: 'Offline – saved locally',
    pending: 'Saving …',
    error: 'Sync error – saved locally',
    agoNever: 'not yet',
    agoJustNow: 'just now',
    agoMin: '{n} min ago',
    agoHour: '{n} h ago',
    checking: 'checking …',
    ready: 'ready',
    notLoaded: 'not loaded',
    loading: 'loading …',
    rowSymbols: 'Symbols',
    rowHazmat: 'Dangerous goods (UN/ADR)',
    rowMap: 'Map',
    noLayer: 'no layer',
    rowPlans: 'Plans',
    noObject: 'no object',
    rowLeitung: 'Utility cadastre',
    geoAllReady: 'all {n} ready',
    geoSome: '{cached}/{total} loaded',
    rowWeather: 'Weather',
    weatherUnreachable: 'unreachable',
    onlineOnly: 'online only',
    rowPersonnel: 'Personnel',
    personnelCount: '{n} people',
    rowObjectSearch: 'Object search',
    loadingForOffline: 'Loading for offline …',
    loadAll: 'Load everything for offline',
    foot: 'Loads map, plans, symbols and utility lines for this incident onto this device. Weather and object search need a connection and are not available offline.',
    wsDropped: 'Skipped {n} corrupted entries while loading',
    wsNewer: 'Incident data was saved by a newer app version – please update the app.',
    layerGroup: 'Offline',
    loadMap: 'Load map for offline',
    loadingShort: 'Loading … {done}/{total}',
    dlDone: 'Map available offline ({n} tiles)',
    dlDoneCapped: 'Map available offline (area limited, {n} tiles)',
    dlFailed: 'Offline download failed',
  },
  emptyApp: {
    title: 'No open incident',
    bodyViewer: 'No incident is currently active.',
    bodyPoolOne: '1 Divera alarm in the pool — open it and review on the map.',
    bodyPoolMany: '{n} Divera alarms in the pool — open one and review on the map.',
    bodyEditor: 'Open an incident or take over a Divera alarm.',
    history: 'History',
  },
  incidentAlert: {
    kicker: 'New incident',
    switch: 'Switch',
    open: 'Open',
    later: 'Later',
  },
  capture: {
    title: 'Record incident',
    invalid: 'Link invalid or capture disabled.',
    noIncidents: 'No recordable incident right now.',
    noIncidentsHint: 'Ongoing and not-yet-reported incidents appear here. Yours is missing? Note it on the paper capture sheet or tell incident command — they can add it later.',
    whoTitle: 'Who is recording?',
    searchName: 'Search name …',
    back: 'Back',
    alarmedAt: 'Alarm {t}',
    saveFailed: 'Saving failed — try again.',
    saveFailedOffline: 'No connection — the last change was not saved.',
    retry: 'Try again',
    savedOk: 'Saved',
    undo: 'Undo',
    removedEntry: '{name} removed (incl. times)',
    mittelSet: '{label}: now {n} {unit}',
    mittelRemoved: '{label} removed',
    stepLess: 'One less',
    stepMore: 'One more',
    mittelExtra: 'Other recorded items',
    gerettete: 'Rescued',
    gerettetePersonen: 'People',
    geretteteTiere: 'Animals',
    rueckmeldung: 'Report back to dispatch',
    rueckName: 'Pick a name …',
    rueckZeit: 'Time',
    jetzt: 'Now',
    kurzberichtHead: 'Summary',
    kurzberichtPlaceholder: 'What happened, what was done?',
    zeitenHead: 'Times',
    gruppenHead: 'Group alarm times',
    fahrzeugeHead: 'Vehicle turnout times',
    angabenHead: 'Details',
    einsatzleiter: 'Incident commander',
    rueckName2: 'Name',
    rapportPdf: 'Report PDF',
    pdfFailed: 'PDF failed — try again.',
    sectionZeiten: 'Times',
    sectionAngaben: 'Details',
    zeitenFilled: '{n} times recorded',
    abschlussHead: 'Wrap-up',
    pdfMissing: 'Still empty (prints as a blank field): {fields}',
    ausgerueckt: 'Turned out',
    kontaktperson: 'Contact person',
    kontaktpersonPlaceholder: 'Owner / caller / responsible person',
    von: 'from',
    bis: 'to',
    ende: 'Incident end',
    endeNow: 'Set to now',
    sectionPersonen: 'Attendance',
    presentCount: '{n} present',
    tapHint: 'Tap: absent → present → left. Time next to it: from = arrival, after leaving to = departure.',
    tapHelp: 'How this works',
    statePresent: 'present',
    stateLeft: 'left',
    sectionMaterial: 'Materials',
    sectionAllgemein: 'General',
    selectPerson: 'Pick a name …',
    whoHint: 'Recorded on the report as "entered by".',
    cancel: 'Cancel',
    mittelCount: '{n} items',
    pickMaterial: 'Pick material …',
    add: 'Add',
    sectionNotizen: 'Notes',
    notePlaceholder: 'Note for the log …',
    footNote: 'Everything is saved continuously.',
    loadFailedOffline: 'No connection — please try again.',
    clockSkew: 'This device\'s clock is off by {n} minutes — check recorded times.',
    searchMaterial: 'Search material …',
    kpActive: 'Command tablet active',
    kpActiveHint: 'The command tablet is on this incident — the full report (with sketch) comes from there.',
    usageChip: 'QR: {n} entries · last {t}',
    usageChipOne: 'QR: 1 entry · last {t}',
  },
  incidentSwitcher: {
    noIncident: 'No incident',
    savedAt: 'Saved at {t}',
    startedRow: 'Started {t} · {d}',
    saved: 'Saved',
    badgePending: 'Not synced – saving',
    badgeOffline: 'Offline – saved locally, syncs as soon as reconnected',
    badgeError: 'Sync failed – saved locally, will retry',
    offlineShort: 'Offline',
    errorShort: 'Sync error',
    syncErrorToast: 'Sync failed – changes are saved locally.',
    syncOfflineToast: 'Still offline – changes are saved locally.',
    bootOffline: 'Offline – showing saved data.',
    syncNow: 'Sync now',
    objectRow: 'Object: {name}',
    incidents: 'Incidents',
    allIncidents: 'All incidents',
    report: 'Incident report',
    archive: 'Close incident',
    noOpenIncidents: 'No open incidents',
    logout: 'Log out',
    appVersion: 'App version (build)',
  },
  update: {
    available: 'Update ready',
    hint: 'Becomes active on the next start — fully close and reopen the app.',
    dismiss: 'OK',
    updated: 'Updated – {v}',
  },
  install: {
    menu: 'Install as app',
    bannerTitle: 'Install KP Front as an app',
    bannerHint: 'Works offline, full screen, own icon.',
    bannerAction: 'How to',
    dismiss: 'Later',
    title: 'Install as app',
    why: 'Installed, KP Front runs like an app: available offline at the scene, full screen without the browser bar, with its own icon on the home screen.',
    nativeButton: 'Install now',
    nativeHint: 'The browser will ask briefly — confirm with “Install”.',
    manualIntro: 'Or manually:',
    installed: 'Installed! From now on, launch KP Front from the app icon.',
    alreadyStandalone: 'KP Front is already running as an installed app.',
    ios: {
      intro: 'On iPad/iPhone:',
      steps: [
        'Tap the share icon {share} in the toolbar',
        'Choose “Add to Home Screen”',
        'Confirm with “Add”',
      ],
      note: 'If “Add to Home Screen” is missing: open the page in Safari.',
    },
    android: {
      intro: 'In Chrome on Android:',
      steps: [
        'Tap the ⋮ menu in the top right',
        'Choose “Install app”',
        'Confirm',
      ],
      note: 'In other browsers: menu → “Add to Home screen”.',
    },
    desktop: {
      intro: 'In Chrome or Edge:',
      steps: [
        'Click the install icon at the right of the address bar',
        'Confirm with “Install”',
      ],
      note: 'Alternatively: browser menu ⋮ → “Install KP Front”.',
    },
    macSafari: {
      intro: 'In Safari on the Mac:',
      steps: [
        'Open the “File” menu',
        'Choose “Add to Dock”',
        'Confirm with “Add”',
      ],
      note: '',
    },
    unsupported: 'This browser does not support installation. Best open the page in Chrome, Edge or Safari and install there.',
  },
  archived: {
    title: 'Incident archived',
    hint: 'View only — reactivate to edit.',
    back: 'Back',
    reactivate: 'Reactivate',
  },
  history: {
    title: 'Incidents',
    empty: 'No incidents yet.',
    noLocation: 'no location',
    searchPlaceholder: 'Search incidents …',
    noMatches: 'No matches.',
    groupOpen: 'Open',
    groupToday: 'Today',
    groupWeek: 'Last 7 days',
    reactivate: 'Reactivate',
    reactivateConfirmTitle: 'Reactivate incident',
    reactivateConfirmMsg: 'The incident is reopened and editable. Later changes appear in the log and report as addenda.',
    reactivateConfirmBtn: 'Reactivate',
    statusArchived: 'Archived',
    statusOpen: 'Open',
    statusInProgress: 'In progress',
    deleteExercise: 'Delete',
    deleteConfirmTitle: 'Delete exercise',
    deleteConfirmMsg: 'The exercise and all its data (log, photos, report) are deleted permanently. This cannot be undone.',
    deleteConfirmBtn: 'Delete permanently',
    deleted: 'Exercise deleted',
    deleteFailed: 'Delete failed',
  },
  abschluss: {
    leftEarly: ' · until {t}',
    steps: {
      zeiten: 'Times',
      anwesenheit: 'Attendance',
      mittel: 'Materials',
      abschluss: 'Wrap-up',
    },
    ausgerueckt: 'Turned out',
    ende: 'Incident end',
    personen: '{n} recorded',
    stunden: 'Hours',
    von: 'from',
    bis: 'to',
    mittelCount: '{n} items',
    mittelNone: 'Nothing used',
    mittelNoneOn: 'Nothing used ✓',
    complete: 'Close incident',
    backToRapport: 'Back to report',
    confirmTitle: 'Close incident',
    confirmMsg: 'The report is marked complete and the incident archived. Later corrections stay possible and appear as addenda.',
    confirmMissing: 'Still open: {steps}. Complete anyway?',
    confirmBtn: 'Complete',
    done: 'Report completed',
    failed: 'Completion failed',
    corrected: 'Hours corrected: {name}',
    attendanceRemoved: '{name} attendance removed',
  },
  datenquellen: {
    title: 'Data sources',
    uploaded: 'Uploaded',
    uploadFailed: 'Upload failed',
    invalidFilename: 'File name yields no valid identifier',
    layerAdded: 'Layer "{name}" added — visible on the next load',
    addLayerFailed: 'Could not add layer',
    globalDatasets: 'Global datasets',
    objectsCount: 'objects',
    replace: 'Replace',
    newGeoLayer: 'New geo layer …',
    chooseGeojson: 'Choose GeoJSON …',
    labelPlaceholder: 'Label (e.g. hydrants)',
    groupPlaceholder: 'Group (e.g. water)',
    defaultGroup: 'Reference',
    kindLines: 'Lines',
    kindPoints: 'Points',
    color: 'Color',
    adding: 'Loading …',
    add: 'Add',
    geojsonNoteBefore: 'GeoJSON in WGS84 [lng, lat]. Stored as a global dataset ',
    geojsonNoteAfter: '.',
    incidentObjects: 'Incident objects',
    plansWord: 'plans',
    nearby: 'Nearby ({n})',
    allOther: 'All other objects',
    allObjects: 'All objects',
  },
  personnelSync: {
    title: 'Sync personnel with {provider}',
    unknownError: 'Unknown error',
    syncFailed: 'Sync failed',
    countNew: 'new',
    countUpdated: 'updated',
    countUnchanged: 'unchanged',
    countStale: 'no longer in {provider}',
    querying: 'Querying {provider} …',
    done: 'Sync complete.',
    resultCreated: '{n} created',
    resultUpdated: '{n} updated',
    resultReactivated: ' ({n} of them reactivated)',
    resultUnchanged: '{n} unchanged',
    resultDeactivated: '{n} deactivated',
    staleHide: 'Hide {n} people no longer present in {provider} (kept for old incidents, not deleted)',
    syncing: 'Syncing …',
    sync: 'Sync',
  },
  planPicker: {
    searchPlaceholder: 'Search name or address …',
    autoNextObject: 'Automatically nearest object',
    loading: 'Loading objects …',
    loadFailed: 'Objects could not be loaded.',
    noObject: 'No object found.',
    planOne: 'plan',
    planMany: 'plans',
    mapNote: 'Coordinates partly imprecise — the list is authoritative.',
    hideMap: 'Hide map',
    showMap: 'Show map',
  },
  replay: {
    region: 'Log replay',
    banner: 'LOG · REPLAY',
    subtitle: 'Read-only view of the past',
    backToLive: 'Back to live',
    loadFailed: 'Log could not be loaded.',
    loading: 'Loading log …',
    transport: 'Playback',
    skipBack: '10 seconds back',
    skipFwd: '30 seconds forward',
    pause: 'Pause',
    speed: 'Speed',
    timepoint: 'Point in time',
    now: 'Now',
    noVehicleData: 'no vehicle data · tactical situation + status are replayed',
    noVehicleTitle: 'The Traccar→sample capture is not yet wired up',
    markerSymbol: 'Symbol placed',
    markerDraw: 'Drawing',
    markerStatus: 'Status',
    markerDivera: 'Divera',
    markerIncidentOpen: 'Incident opened',
    markerSave: 'Save point',
  },
  report: {
    erfasser: 'Recorded by',
    gerettete: 'Rescued',
    gerettetePersonen: 'people',
    geretteteTiere: 'animals',
    rueckmeldungElz: 'Report back to dispatch',
    zeitenHead: 'Alarm / turnout times',
    back: 'Back',
    print: 'Print',
    coverEyebrow: 'Incident report',
    blankPlan: 'Blank plan',
    keyword: 'Keyword',
    addressObject: 'Address / object',
    einsatzleiter: 'Incident commander',
    kontaktperson: 'Contact person',
    alarmierung: 'Alerted',
    ausgerueckt: 'Turned out',
    incidentEnd: 'Incident end',
    incidentId: 'Incident ID',
    alarmMessage: 'Alarm message',
    summaryHead: 'Brief description / work carried out',
    partnerOrgs: 'Partner organisations',
    remarks: 'Remarks',
    sigKommandant: 'Commander',
    kroki: 'Sketch',
    krokiState: '{title} · as of {at}',
    atemschutz: 'SCBA monitoring',
    truppMembers: 'Members',
    truppAuftrag: 'Assignment / target',
    truppLine: 'Line',
    truppEntry: 'Entry',
    truppExit: 'Exit',
    colTime: 'Time',
    colKind: 'Type',
    colPressure: 'Pressure bar',
    noPressureLog: 'No pressure log recorded.',
    mittel: 'Materials (enter quantity)',
    personalHead: 'Personnel / attendance',
    personalHint: 'Tick off, add from–to if applicable',
    partnerOther: 'Other',
    journal: 'Incident journal',
    colArea: 'Area',
    colEntry: 'Entry',
    audioPresent: 'Audio present',
    audioNotTranscribed: ', not transcribed',
    photo: 'Photo',
    transcript: 'Transcript',
    noEntries: 'No entries.',
    nachtraege: 'Addenda after incident end',
    planFallback: 'Plan',
    proofOffline: 'Verification not possible (offline)',
    proofIntact: 'Hash chain intact',
    proofBroken: 'Hash chain broken',
    proofBrokenAt: 'Hash chain broken at #{seq}',
    areaManual: 'Manual',
    areaAtemschutz: 'SCBA',
    drawCircle: 'Cordon',
    drawAreaLabeled: 'Section "{label}"',
    drawArea: 'Area',
    drawRescueAxis: 'Rescue axis',
    drawMeasureArrow: 'Measure arrow',
    drawLine: 'Line',
  },
  wheel: {
    day: 'Day',
    month: 'Month',
    year: 'Year',
    hour: 'Hour',
    minute: 'Minute',
    now: 'Now',
    ok: 'OK',
    clear: 'Clear',
  },
  preflight: {
    pdfFull: 'Incident report (PDF)',
    pdfBusy: 'Generating PDF …',
    geretteteLabel: 'Rescued',
    gerettetePersonen: 'People',
    geretteteTiere: 'Animals',
    gruppenLabel: 'Group alarm times',
    fahrzeugeLabel: 'Vehicle turnout times',
    ausgeruecktDerived: 'derived from the vehicle times',
    vorOrtShort: 'on scene',
    zurueckShort: 'returned',
    rueckmeldungLabel: 'Report back to dispatch',
    rueckmeldungName: 'Name',
    rueckmeldungZeit: 'Time',
    title: 'Print incident report',
    rapportHead: 'Report details',
    fromDispatch: 'From the incident data',
    edit: 'Edit',
    alarmMessage: 'Alarm message',
    alarmierung: 'Alerted',
    notRecorded: 'Not recorded',
    summaryLabel: 'Brief description',
    summaryPlaceholder: 'What happened / what was found?',
    einsatzleiterLabel: 'Incident commander',
    einsatzleiterPlaceholder: 'Select or type',
    kontaktpersonLabel: 'Contact person',
    kontaktpersonPlaceholder: 'Owner / reporter / person in charge',
    incidentEndLabel: 'Incident end',
    now: 'Now',
    remarksLabel: 'Remarks',
    remarksPlaceholder: 'Optional',
    sectionsHead: 'Sections',
    groupMap: 'Map & plans',
    groupContents: 'Contents',
    groupAdvanced: 'Advanced',
    toggleKroki: 'Sketch',
    plansLabel: 'Plans',
    plansAnnotated: 'Annotated ({n})',
    plansAll: 'All',
    plansNone: 'None',
    toggleAtemschutz: 'SCBA monitoring ({n})',
    toggleAttendance: 'Attendance ({n})',
    toggleMittel: 'Resources ({n})',
    toggleJournal: 'Incident journal',
    toggleDetailedAudit: 'Detailed integrity proof',
    framingTitle: 'Choose sketch crop',
    framingHint: 'Pan and zoom the map — exactly this crop is printed.',
    framingFit: 'Zoom to incident',
    framingConfirm: 'Use this crop',
    controlHead: 'Checks',
    proofChecking: 'Verifying integrity proof …',
    annotatedDefault: '{n} annotated plans are printed by default.',
    missingTranscripts: '{n} audio entry/entries without a transcript — add for the record.',
    fixTranscripts: 'Add in the log',
    stateNote: 'As of: whole incident up to report creation ({at}).',
    cancel: 'Cancel',
    openPrint: 'Open print view',
  },
  printRelay: {
    send: 'Print',
    sending: 'Sending …',
    queued: 'Sent to station printer',
    printing: 'Printing …',
    printed: 'Printed',
    printFailed: 'Printing failed – check the printer',
    confirmTitle: 'Print',
    confirmMsg: 'Send the incident report to the station printer?',
    confirmBtn: 'Print',
    undo: 'Undo',
    cancelled: 'Print job cancelled',
    undoTooLate: 'Too late — the job is already at the printer',
    failed: 'Sending to station printer failed',
    online: 'Station printer reachable',
    offline: 'Station printer offline',
    offlineConfirmTitle: 'Station printer offline',
    offlineConfirmMsg: 'The print relay is not reporting in right now. The job will print once it is reachable again. Send anyway?',
    offlineConfirmBtn: 'Send anyway',
  },
  anwesenheit: {
    title: 'Attendance',
    summary: '{present} present · {left} left · {total} crew',
    reload: 'Reload crew',
    loading: 'Loading …',
    refresh: 'Refresh',
    searchPlaceholder: 'Search name',
    clearSearch: 'Clear search',
    legendFrei: 'not present',
    legendPresent: 'present',
    legendLeft: 'left',
    loadFailedTitle: 'Crew could not be loaded.',
    loadFailedHint: 'Offline or server unreachable. The last loaded list is preserved.',
    emptyTitle: 'No crew available.',
    emptyHint: 'Sync the crew from Divera.',
    retry: 'Try again',
    noMatches: 'No matches.',
    lockedTitle: 'In an SCBA team — mark the team out first',
    notInDivera: 'No longer in Divera',
    weg: 'gone',
    editTime: 'Adjust time',
  },
  mittel: {
    title: 'Resources',
    summary: '{lines} entries',
    summaryEmpty: 'Nothing recorded yet',
    add: 'Resource',
    viewLabel: 'View',
    viewList: 'Resources',
    viewBySource: 'by source',
    noSource: 'No source',
    categoryOther: 'Other',
    customGroup: 'Additional',
    noch: '{n} left',
    stockAria: '{label}: {remaining} of {total} left',
    emptyTitle: 'No resources recorded yet.',
    emptyHint: 'Use «+ Resource» to record what was used — for the report and to see whether resupply is needed.',
    emptyReadonly: 'No resources recorded.',
    composerTitle: 'Record resource',
    materialLabel: 'Resource',
    materialPlaceholder: 'Choose resource',
    customMaterial: 'Other resource',
    customMaterialPlaceholder: 'Name',
    unitLabel: 'Unit',
    unitPlaceholder: 'Unit',
    sourceLabel: 'Source',
    sourcePlaceholder: 'Source (optional)',
    qtyLabel: 'Quantity',
    save: 'Save',
    cancel: 'Cancel',
    removeRow: 'Set to 0 (remove)',
    removedToast: '«{label}» removed',
    logSet: '{label}: {menge} {unit}',
    logRemoved: '{label} removed',
    // Symbol→Mittel capture offer + Retablierung
    captureOffer: 'Log {label} as materiel?',
    captureAction: 'Log it',
    captured: '{label}: {menge} {unit} logged',
  },
  checklists: {
    railLabel: 'Checklists',
    showList: 'Show list',
    groupTasks: 'Tasks',
    groupTactics: 'Tactics · keywords',
    searchPlaceholder: 'Search keyword ...',
    searchAria: 'Search keyword',
    matching: 'Matching: {title}',
    noMatches: 'No matches.',
    none: 'No checklists available yet.',
    pickEntry: 'Choose or search a keyword.',
    done: 'done',
    variantLabel: 'Variant',
    pickVariant: 'Choose a variant to see the tasks.',
    milestoneTitle: 'Milestone — appears in the log',
    actionLabels: { journal: 'Journal', plan: 'Plan', draw: 'Draw' },
    hazardLabels: { red: 'Fire', orange: 'Hazards', green: 'Traffic', yellow: 'Technical', blue: 'Water' },
    diagramAlt: 'Diagram page {page}',
  },

  admin: {
    common: {
      configLoading: 'Loading configuration…',
      copy: 'Copy',
      copied: 'Copied',
      confirmYes: 'Yes, do it',
      confirmNo: 'Cancel',
    },
    shell: {
      verwaltung: 'Administration',
      toLageMap: '← To situation map',
      logout: 'Sign out',
      openSections: 'Open sections',
      closeSections: 'Close sections',
      navAria: 'Administration sections',
    },
    denied: {
      title: 'No access',
      body: 'Administration is reserved for editors. You are signed in as {name}.',
    },
    nav: {
      groupStation: 'Station',
      groupPersonen: 'People',
      groupDaten: 'Data',
      groupSystem: 'System',
      identitaet: { label: 'Station & map', title: 'Station & map', lede: 'Name, language, brand colour, logos and the situation map’s default view for this installation.' },
      karte: { label: 'Map', title: 'Map', lede: 'Initial situation-map view (centre + zoom) before an incident is selected.' },
      doktrin: { label: 'Doctrine', title: 'Doctrine', lede: 'FKS settings for this brigade: default radio channel, SCBA contact interval and warning lead.' },
      fahrzeuge: {
        label: 'Symbols',
        title: 'Symbols',
        lede: 'Pick lists for situation entry. Suggestions — free typing stays possible.',
        tip: 'Each list attaches pick suggestions to a symbol field — e.g. vehicle types to «VKF vehicle · title». Suggestions only; free typing always stays possible in the situation map.',
      },
      ebenen: { label: 'Map layers', title: 'Map layers', lede: 'Reference / utility layers for this brigade (hydrants, utility cadastre, canton WMS …). Base maps are national / shipped.' },
      objektplaene: {
        label: 'Object plans',
        title: 'Object plans (modules)',
        lede: 'Module catalogue for this brigade: which modules exist, their labels (M1, 2/3 …), order and the import detection rules. Empty = shipped default modules.',
        tip: 'One configuration for both: the plan tiles in the app and the file parsing of import_einsatzplaene (the importer fetches this list via /api/config). «Family» derives sub-modules from the file name (Modul 5 - Wasser → modul5-wasser); «Combined with» fills several slots from one combined sheet (Modul 2-3 → modul2, modul3).',
      },
      mitglieder: { label: 'Members & access', title: 'Members & access', lede: 'Who may sign in, with which role and PIN.' },
      mannschaft: { label: 'Roster', title: 'Roster', lede: 'Canonical local personnel roster: manual entry and CSV always work; an optional personnel provider can synchronize records.' },
      erfassung: { label: 'Capture', title: 'Capture (poster)', lede: 'The station capture poster: a QR code through which attendance, materials and notes for a recent incident are recorded without a login.' },
      einsaetze: { label: 'Incident history', title: 'Incident history', lede: 'All current and historical incidents with start time, status, source, report state and last update.' },
      divera: {
        label: 'Alarm intake',
        title: 'Alarm intake',
        lede: 'Configured alarm-provider status, unassigned incoming alarms, refresh and connection test.',
        tip: 'The «pool» are the alarms imported from Divera that are not yet assigned. «Refresh» fetches them again from the server.',
      },
      traccar: {
        label: 'Vehicle tracking',
        title: 'Vehicle tracking',
        lede: 'Configured tracking-provider status, transmitting vehicles, freshest signal and connection test.',
        tip: 'Live GPS of the vehicles via Traccar. «connected» = link active; «online» = vehicles currently transmitting.',
      },
      statistik: {
        label: 'Statistics export',
        title: 'Statistics export',
        lede: 'Read-only data feed of all incidents for external analytics (e.g. yearly statistics).',
      },
      objekte: {
        label: 'Objects & plans',
        title: 'Objects & plans',
        lede: 'Stored objects and their plans (module, version, status). View only.',
        tip: 'Plans are PDF sheets per object, ordered by FKS module: Modul 1 overview, 2 access, 3 interior, 2-3 combined, 6 building plans.',
      },
      geodaten: {
        label: 'Geodata',
        title: 'Geodata & symbols',
        lede: 'Imported reference data: GeoJSON layers, symbol sets and PDFs. View only.',
        tip: 'Station-owned reference data (hydrants, utilities …). «Dataset» = one layer, «Features» = contained objects, «Source» = where it comes from.',
      },
      system: { label: 'System & maintenance', title: 'System & maintenance', lede: 'Status & maintenance: version, database, inventory, storage and this device’s offline cache.' },
      sicherung: { label: 'Backup', title: 'Backup', lede: 'Back up the configuration to a file or restore a saved file.' },
    },
    erfassung: {
      cardTitle: 'Capture poster',
      body: 'Whoever scans the poster in the station can record attendance, materials and notes for a recent incident — no login, no training. Trust model: access to the station = permission (like the clipboard before).',
      stateLabel: 'Capture',
      stateOn: 'active',
      stateOff: 'disabled',
      enableBtn: 'Enable & generate token',
      rotateBtn: 'Rotate token',
      rotateMsg: 'Generate a new token? Every printed poster becomes invalid immediately.',
      rotated: 'New token generated — print a fresh poster.',
      disableBtn: 'Disable',
      disableMsg: 'Disable capture? The QR code on all posters stops working.',
      disabled: 'Capture disabled.',
      printBtn: 'Poster as PDF (A4)',
      posterHead: 'Record incident',
      posterStep1: 'Scan the QR code with your phone',
      posterStep2: 'Tap the incident and pick your name',
      posterStep3: 'Tick off who is present, add materials and notes',
      failed: 'Action failed',
      sheetBtn: 'Capture sheet as PDF (A4)',
      sheetCardTitle: 'Capture sheet (paper)',
      sheetCardBody: 'The paper twin of the digital report: same fields, same order — for the fully analog incident. Generated from the current roster, materials and config; photograph filled sheets (Verlauf/attachment) and transfer them in the app.',
      sheetHead: 'Incident capture sheet',
      sheetIncident: 'Incident',
      sheetAdresse: 'Address / object',
      sheetEigentuemer: 'Owner / responsible party',
      sheetGerettete: 'Rescued (people / animals)',
      sheetZeiten: 'Alarm / turnout times',
      sheetPartner: 'Partner organisations',
      sheetPartnerOther: 'Other',
      sheetRueckmeldung: 'Report back to dispatch',
      sheetZeit: 'Time',
      sheetDate: 'Date',
      sheetAlarm: 'Alarmed',
      sheetEnde: 'Incident end',
      sheetKontakt: 'Contact person',
      sheetSignatures: 'Sign-off',
      sheetName: 'Name',
      sheetEl: 'Incident commander',
      sheetKdt: 'Commander',
      sheetPersonen: 'Attendance (tick, from–to if needed)',
      sheetMaterial: 'Materials (enter amounts)',
      sheetNotizen: 'Brief report / work carried out',
      hint: 'The link covers ongoing and not-yet-reported incidents; reported ones disappear after a few hours (default 12 h, alarms.captureWindowHours). No access to the map, administration, or archived incidents.',
    },
    statistik: {
      body: 'Read-only export of all incidents as flat JSON records (metadata, times, attendance from–to, materials, report status) — for external analytics such as the yearly statistics. No write access, no access to the map or administration.',
      stateLabel: 'Export',
      stateOn: 'active',
      stateOff: 'disabled',
      enableBtn: 'Enable & generate token',
      rotateBtn: 'Rotate token',
      rotateMsg: 'Generate a new token? Every connected analytics tool must be reconfigured afterwards.',
      rotated: 'New token generated.',
      disableBtn: 'Disable',
      disableMsg: 'Disable the statistics export? Connected analytics tools will stop receiving data.',
      disabled: 'Export disabled.',
      failed: 'Action failed',
      exampleLabel: 'Example request',
      tokenLabel: 'Token',
      hint: 'Keep the token secret — it grants read access to all incident data incl. names. Pass it to the analytics tool as the X-Stats-Token header (or ?t=).',
    },
    incidentHistory: {
      loading: 'Loading incidents…', error: 'Could not load incidents.', search: 'Search title, address or source…',
      none: 'No incidents available.', noMatches: 'No incidents match the search.', started: 'Started', incident: 'Incident', status: 'Status',
      source: 'Source', report: 'Report', updated: 'Updated', open: 'open', closed: 'closed', complete: 'complete', incomplete: 'pending',
    },
    autosave: {
      retry: 'Try again',
      saving: 'Saving…',
      pending: 'Saving changes…',
      saved: 'Saved',
      sessionExpired: 'Session expired — please sign in again.',
      saveFailed: 'Save failed',
      loadFailed: 'Could not load configuration',
    },
    usageBar: { aria: '{pct}% used' },
    identity: {
      appName: 'App name',
      appNameTip: 'Shown in the title bar, login and help. Empty = «KP Front».',
      accentColor: 'Accent colour',
      accentColorHint: 'Brand colour (login / splash)',
      accentColorTip: 'The brigade’s brand colour; flows through the entire --accent colour system (login, splash, accents).',
      pickAccentColor: 'Choose accent colour',
      language: 'Language',
      languageHint: 'UI language for the whole brigade',
      languageTip: 'Language of all interface text. Applies to the whole brigade (one deployment = one language); applied when the app loads. fr/it are only partly translated and otherwise fall back to German.',
      pickLanguage: 'Choose language',
      kommandant: 'Commander',
      kommandantTip: 'Name of the brigade commander — pre-printed next to the «Kommandant» signature line on the incident report. Empty = label only.',
    },
    map: {
      centerLon: 'Centre — longitude (lon)',
      centerLonTip: 'Longitude (WGS84) of the map start, before an incident is selected.',
      centerLat: 'Centre — latitude (lat)',
      centerLatTip: 'Latitude (WGS84) of the map start, before an incident is selected.',
      zoom: 'Zoom',
      zoomTip: 'Initial zoom level of the map (higher = closer; ~16 shows a neighbourhood extent).',
    },
    doctrine: {
      defaultFunkkanal: 'Radio channel (default)',
      defaultFunkkanalTip: 'Preset radio channel of a new incident.',
      contactInterval: 'Contact interval (min)',
      contactIntervalTip: 'SCBA contact interval; once elapsed, contact is due (amber).',
      contactGrace: 'Grace (s)',
      contactGraceTip: 'Seconds after contact is due until the overdue alarm fires.',
      mindestBar: 'Minimum pressure (bar)',
      mindestBarTip: 'Critical minimum pressure; at or below it the pressure readout on the team card highlights red.',
      defaultPressure: 'Entry pressure (bar)',
      defaultPressureTip: 'Fill pressure the team wizard starts with (e.g. a 300 bar cylinder in service).',
      pressureStep: 'Pressure step (bar)',
      pressureStepTip: 'Step of the ± pressure controls; inputs snap to this grid.',
      pressureMax: 'Pressure maximum (bar)',
      pressureMaxTip: 'Upper bound of pressure input (320 allows an overfull cylinder).',
      funkkanalMin: 'Radio channel min',
      funkkanalMinTip: 'Lower bound of the radio-channel stepper.',
      funkkanalMax: 'Radio channel max',
      funkkanalMaxTip: 'Upper bound of the radio-channel stepper.',
    },
    backup: {
      title: 'Backup',
      caption: 'Back up the configuration to a file or restore a saved file. Import replaces it entirely (without env integrations).',
      export: 'Export configuration',
      import: 'Import configuration',
      lastChangedBy: 'Last changed by {name} on {date}',
      lastChanged: 'Last changed on {date}',
      notJson: 'File is not valid JSON.',
      notConfig: 'File does not contain a valid configuration.',
      replaceConfirm: 'This file fully replaces the current configuration. The previous one is downloaded as a backup first. Continue?',
      imported: 'Configuration imported.',
      invalidSchema: 'Configuration invalid (422) — file does not match the schema.',
      importFailed: 'Import failed.',
    },
    common2: {
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving…',
      create: 'Create',
      edit: 'Edit',
      remove: 'Remove',
      notAvailable: 'not available',
      unknownError: 'Unknown error',
    },
    infoTip: { prefix: 'Info: {label}' },
    stringList: {
      addPlaceholder: 'Add…',
      removeItem: 'Remove {item}',
    },
    fleet: {
      filterPlaceholder: 'Search symbol …',
      loading: 'Loading symbol library …',
      noMatches: 'No symbol matches the search.',
      noAttributes: 'No fields.',
      fieldTitle: 'Title',
      fieldMeaningTitle: 'Special fields',
      guideTitle: 'Fields and properties explained',
      fieldGlossary: {
        Titel: 'Visible vehicle label, e.g. Engine 1.', Status: 'Context-specific state, e.g. rescued or valve open/closed.',
        Stoff: 'Hazardous substance name.', 'UN-Nr': 'Four-digit UN dangerous-goods number.', Einheit: 'Organisation or deployed unit.',
        Name: 'Person from the roster.', Funktion: 'Command assignment, e.g. sector or safety.', Fahrer: 'Driver from the roster.', Typ: 'Equipment or configuration type.',
      },
      propsLabel: 'Properties',
      controls: {
        rotation: 'Rotatable',
        rotation2: 'Second rotation',
        count: 'Count',
        floor: 'Floor',
        floorRange: 'Floor range',
        spread: 'Spread',
      },
      propertiesMeaningTitle: 'Properties',
      controlGlossary: {
        rotation: 'The symbol can be rotated after placement.', rotation2: 'A second independent direction angle is available.',
        count: 'Several identical elements are tracked as a count.', floor: 'The symbol can be assigned to a floor.',
        floorRange: 'The symbol can cover a range of floors.', spread: 'Direction and extent of spread can be shown.',
      },
      listsMeaningTitle: 'Source & options.',
      noConfiguredLists: 'This station has no custom option lists. Name and driver come from the roster; all other fields remain freely editable.',
      configuredLists: '“Configured” shows station suggestions and “From roster” uses personnel. Suggestions speed up entry; free text remains possible.',
      rosterField: 'From roster',
      rosterBadgeHint: 'filled from the roster',
      configuredBadge: 'Configured',
      configuredBadgeHint: 'set in the station configuration',
      freitextBadge: 'Free text',
      freitextBadgeHint: 'no list — operator types freely',
      freitextValue: 'free entry',
    },
    members: {
      add: 'Add member',
      addCaption: 'Username for signing in, display name on the login tiles. PIN: exactly {n} digits.',
      username: 'Username',
      usernamePlaceholder: 'e.g. fu',
      displayName: 'Display name',
      displayNamePlaceholder: 'e.g. Felix Muster',
      role: 'Role',
      roleViewer: 'Viewer',
      roleEditor: 'Editor',
      elViewDefault: 'Starts in incident-commander view',
      elViewDefaultHint: 'tactics locked, journal & details live – switchable on the device',
      colorLabel: 'Colour',
      colorOptional: 'optional',
      pickColor: 'Choose colour',
      pinLabel: 'PIN',
      pinDigits: '{n} digits',
      title: 'Members',
      caption: 'Who may sign in and with which role. Members are deactivated, never deleted (the history is preserved).',
      loading: 'Loading members…',
      none: 'No members.',
      colName: 'Name',
      colUsername: 'Username',
      colRole: 'Role',
      colStatus: 'Status',
      colLastLogin: 'Last login',
      colActions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      toViewer: '→ Viewer',
      toEditor: '→ Editor',
      deactivate: 'Deactivate',
      reactivate: 'Reactivate',
      resetPin: 'Reset PIN',
      guardSelf: 'You cannot change or deactivate your own account.',
      guardLastCmd: 'The last active editor account cannot be deactivated or demoted.',
      guardSelfRole: 'You cannot change your own role.',
      guardLastCmdRole: 'The last active editor account cannot be demoted.',
      guardSelfDeactivate: 'You cannot deactivate your own account.',
      guardLastCmdDeactivate: 'The last active editor account cannot be deactivated.',
      guardLabel: 'Protected actions for {name}',
      newPinPrompt: 'New PIN for {name} ({n} digits):',
      pinInvalid: 'PIN must have exactly {n} digits.',
    },
    roster: {
      sourceHint: 'Columns: name (required), rank (optional). UTF-8, comma-separated, with a header row. Provider identities are managed by synchronization.',
      addPerson: 'Add person',
      addPersonCaption: 'Enter the person’s name.',
      name: 'Name',
      namePlaceholder: 'e.g. Meier Hans',
      csvImport: 'Import CSV',
      csvTemplate: 'Download example CSV',
      importing: 'Importing…',
      imported: '{n} imported',
      skipped: '{n} skipped',
      syncDivera: 'Sync roster with Divera',
      diveraNotConfigured: 'Divera not configured',
      syncProvider: 'Synchronize with {provider}',
      providerNotConfigured: 'No personnel provider configured · CSV and manual entry available',
      title: 'Recorded persons',
      caption: 'Personnel roster of the brigade. Persons are deactivated, never deleted (the history is preserved).',
      showInactive: 'Show inactive',
      loading: 'Loading roster…',
      none: 'No persons recorded.',
      colName: 'Name',
      colSource: 'Source',
      colStatus: 'Status',
      colActions: 'Actions',
      sourceDivera: 'Divera',
      sourceManual: 'manual',
      active: 'Active',
      inactive: 'Inactive',
      deactivate: 'Deactivate',
      reactivate: 'Reactivate',
    },
    data: {
      testConnection: 'Test connection',
      testing: 'Testing…',
      testOk: 'OK',
      testOff: 'not configured',
      testErr: 'Error',
      genericError: 'Error',
      stateConnected: 'connected',
      stateUnavailable: 'not available',
      stateNotConfigured: 'not configured',
      poolLoading: 'Loading pool…',
      poolCount: '{n} alarm in the pool',
      poolCountPlural: '{n} alarms in the pool',
      poolUnavailable: 'Pool not available',
      refresh: 'Refresh',
      refreshing: 'Refreshing…',
      lastAlarm: 'Last alarm',
      alarmFallback: 'Alarm {id}',
      noneInPool: 'none in the pool',
      address: 'Address',
      vehiclesLoading: 'Loading vehicles…',
      vehicleCount: '{n} vehicle',
      vehicleCountPlural: '{n} vehicles',
      onlineCount: '{n} online',
      positionsUnavailable: 'Positions not available',
      server: 'Server',
      freshestSignal: 'Latest signal',
      colDevice: 'Device',
      colStatus: 'Status',
      colLastSignal: 'Last signal',
      colSpeed: 'Speed',
      online: 'online',
      offline: 'offline',
      unknown: 'unknown',
      noPlans: 'no plans',
      objectsLoading: 'Loading objects…',
      objectsUnavailable: 'Objects not available.',
      objectsError: 'Could not load objects.',
      objectsNone: 'No objects stored.',
      objectsHintBefore: 'Objects and their plans are imported server-side — via ',
      objectsHintAfter: ' from the private data repository. They then appear here for viewing.',
      mapLoading: 'Loading map…',
      noLocation: 'no location',
      geodataLoading: 'Loading data…',
      geodataUnavailable: 'Data not available.',
      geodataError: 'Could not load data.',
      geodataNone: 'No reference data imported.',
      geodataHintBefore: 'Hydrants, utility cadastre and further layers are loaded server-side — via ',
      geodataHintAfter: ' from the private data repository. GeoJSON must be WGS84.',
      colDataset: 'Dataset',
      colType: 'Type',
      colVersion: 'Version',
      colUpdated: 'Updated',
      colFeatures: 'Features',
      colSource: 'Source',
      justNow: 'just now',
      relMin: '{n} min ago',
      relHour: '{n} h ago',
    },
    objectsMap: {
      showAll: 'Show all',
      showAllTitle: 'Show all objects',
    },
    modules: {
      empty: 'No modules configured — the bundled standard modules apply.',
      summary: '{modules} modules · {objects} objects · {plans} plans',
      coverage: '{covered}/{total} objects',
      code: 'Code',
      title: 'Title',
      order: 'Order',
      orientation: 'Orientation',
      orientationPortrait: 'Portrait',
      orientationLandscape: 'Landscape',
      detection: 'Match rule',
      detectionNone: 'no rule',
      combinedWith: 'Combined with',
      familyBadge: 'Family',
      familyHint: 'generates sub-modules from the filename',
      viewerBadge: 'View only',
      viewerHint: 'PDF without drawing',
      objectsTitle: 'Objects & plans',
    },
    layers: {
      filterPlaceholder: 'Search layer …',
      loading: 'Loading …',
      empty: 'No reference layers configured.',
      noMatches: 'No layer matches the search.',
      summary: '{total} layers · {loaded} loaded · {missing} missing · {external} external',
      statusLoaded: 'Loaded',
      statusMissing: 'Not loaded',
      statusExternal: 'External source',
      features: '{n} features',
      updated: 'Updated {date}',
      group: 'Group',
      opacity: 'Opacity',
      colorDay: 'Day color',
      colorNight: 'Night color',
      symbol: 'Symbol',
      geometry: 'Geometry',
      geometryPoint: 'Points',
      geometryLine: 'Lines',
      maxZoom: 'Max zoom',
      attribution: 'Source',
      source: 'Source',
      datasetsTitle: 'Loaded datasets',
    },
    branding: {
      logo: 'Logo',
      logoHint: 'Login screen',
      favicon: 'Favicon',
      faviconHint: 'Browser tab',
      upload: 'Choose image',
      uploading: 'Uploading…',
      remove: 'Remove',
      removeConfirm: 'Remove this image?',
      uploadFailed: 'Upload failed',
      removeFailed: 'Removal failed',
      iconsNote: 'App / home-screen icons are set at build time (separately).',
    },
    system: {
      loading: 'Loading system data…',
      refresh: 'Refresh',
      liveSnapshot: 'Live system status',
      updatedAt: 'Updated {time}',
      healthSummary: 'System health',
      server: 'Server',
      reachable: 'reachable',
      error: 'Could not load system data.',
      notAvailable: 'not available',
      version: 'Version',
      versionTip: 'Build status of this installation. «Commit» = the server’s Git state, «Environment» = production or development mode.',
      commit: 'Commit',
      branch: 'Branch',
      environment: 'Environment',
      production: 'Production',
      development: 'Development',
      database: 'Database',
      databaseTip: 'Liveness of the database: a simple test query. «OK» = the server reaches the database.',
      ok: 'OK',
      error2: 'Error',
      inventory: 'Inventory',
      inventoryTip: 'Records in the database of this installation.',
      incidentsTotal: 'Incidents (total)',
      incidentsOpen: 'Incidents (open)',
      personnelActive: 'Roster (active)',
      users: 'Users',
      referenceData: 'Reference data',
      domain: 'Domain',
      status: 'Status',
      active: 'active',
      personnelProvider: 'Personnel provider',
      alarmProvider: 'Alarm provider',
      vehicleProvider: 'Tracking provider',
      configured: 'configured',
      notConfigured: 'not configured',
      connectors: 'Connections',
      connectorsTip: 'Everything this installation talks to — providers (Divera/Traccar) and all consumers/producers — read-only. Configured via environment variables or the admin area (capture, statistics).',
      connection: 'Connection',
      directionIn: 'inbound',
      directionOut: 'outbound',
      connOnline: 'online',
      connOffline: 'offline',
      connLastSeen: 'Last seen: {time}',
      connPrintRelay: 'Station printer (print agent)',
      connCapture: 'Capture poster (QR)',
      connStats: 'Statistics export',
      connDiveraWebhook: 'Divera webhook',
      connAlarmWebhook: 'Generic alarm intake',
      connPush: 'Web push (alerting)',
      connStt: 'Speech-to-text',
      storage: 'Storage',
      storageTip: 'The server’s object storage (photos, plans, reference files) and the utilisation of the underlying disk.',
      mediaUsed: 'Used (media)',
      files: 'Files',
      directory: 'Directory',
      diskUsed: 'Disk used',
      diskUnavailable: 'Disk utilisation not available.',
      free: 'Free: {size}',
      offlineCache: 'Offline cache (this device)',
      offlineCacheTip: 'The offline cache (service worker) of this device: stored maps, plans and app files for use without reception. Numbers apply only to THIS device, not the server.',
      cacheReading: 'Reading cache…',
      cacheUnavailable: 'Not available in this browser.',
      usedQuota: 'Used / quota',
      storageEstimateUnavailable: 'Storage estimate not available.',
      cacheStorage: 'Cache storage',
      cacheSummary: '{caches} · {entries} entries',
      cache: 'Cache',
      entries: 'Entries',
      clearCaches: 'Clear caches',
      clearing: 'Clearing…',
      cleared: 'cleared',
      clearConfirm: 'Clear the offline cache on THIS device?\n\nThe stored maps, plans and app files will be deleted. On the next load they are fetched again from the server (internet required). Sign-in and server data remain untouched.',
      offlineCacheCaption: 'Local maintenance: clears only the offline cache on THIS device. On the next load the files are fetched again. Sign-in and server remain untouched.',
    },
  },
}
