// French (fr, Suisse romande) — a full translation overlay deep-merged over German (./de).
//
// Fire-service domain terms follow Swiss «sapeurs-pompiers» usage: Lage → «Situation»,
// Atemschutz → «protection respiratoire» / ARI (appareil respiratoire isolant),
// Trupp → «binôme», Einsatzleiter → «chef d'intervention», Verlauf → «journal»,
// KP Front → «PC Front».
//
// Two groups are deliberately NOT translated and fall back to German on purpose:
//   • intake.kategorien / intake.kategorieGuess — these mirror the backend's VKF
//     Schadenkategorien (app/divera.py TYPE_LABELS) and match against German Divera keyword
//     text; translating them would desync category derivation.
//   • contextPanel.unField / contextPanel.stoffField — detail-row DATA keys the UN→substance
//     lookup matches against the (language-independent) preset fields; translating them would
//     break the autofill.
// Everything omitted here renders the German base string (deepMerge fallback).

import type { Copy, Localizable } from './index'

export const fr: Localizable<Copy> = {
  loadingSubtitle: 'Chargement de la carte et de la bibliothèque de symboles …',
  modes: { map: 'Situation', plans: 'Plan', checklists: 'Checklist', atemschutz: 'ARI', anwesenheit: 'Présence' },
  navRail: { map: 'Carte', plansGroup: 'Plans', objectSwitch: 'Choisir l’objet', assign: 'Attribuer le plan', expand: 'Déplier', collapse: 'Replier', resize: 'Ajuster la barre' },
  panels: { layers: 'Couches', history: 'Journal' },
  layerPanel: {
    stateVisible: 'visible, masquer',
    stateHidden: 'masqué, afficher',
  },
  help: {
    menu: 'Fonctions et aide',
    title: 'Que fait PC Front ?',
    subtitle: 'Toutes les fonctions en un coup d’œil — conçu pour être utilisable à 3 h du matin sans entraînement.',
    contents: 'Sommaire',
    close: 'Fermer',
    introFallback: 'PC Front est la conduite d’intervention numérique de votre corps de sapeurs-pompiers : carte de situation tactique, plans d’objet, surveillance de la protection respiratoire et un journal partagé — le tout en direct sur plusieurs appareils à la fois.',
    sections: [
      {
        id: 'ueberblick', title: 'Aperçu', icon: 'info',
        blocks: [
          { kind: 'intro' },
          { kind: 'sub', text: 'Les quatre espaces de travail (barre de gauche)' },
          { kind: 'list', items: [
            '**Situation** — la carte tactique avec symboles, lignes, surfaces et les couches des réseaux.',
            '**Plan** — les plans d’objet (modules 1–6, contours de bâtiment) sous forme de tableau blanc, étage par étage.',
            '**Checklist** — listes de contrôle d’intervention à dérouler.',
            '**ARI** — surveillance des binômes engagés avec temps et pression.',
          ] },
          { kind: 'note', text: 'Principe directeur : utilisable à 3 h du matin, après six mois sans entraînement. Reconnaître plutôt que retenir, utilisable avec des gants et hors ligne.' },
        ],
      },
      {
        id: 'navigation', title: 'Navigation et interface', icon: 'cursor',
        blocks: [
          { kind: 'lead', text: 'Trois zones fixes : la barre des espaces à gauche, la barre d’intervention en haut, la barre d’outils à droite.' },
          { kind: 'sub', text: 'Barre de gauche' },
          { kind: 'list', items: [
            'Change d’espace de travail : **Carte** (Situation), les **Plans** (modules/bâtiments), **Checklist**, **ARI**.',
            'En bas, **Choisir l’objet** permute le bâtiment/objet des plans.',
            'En mode Situation, **Couches** et le sélecteur de **Carte** sont épinglés en bas — toujours visibles.',
            'Tirer le bord droit de la barre la déplie avec les libellés ou la replie.',
          ] },
          { kind: 'sub', text: 'Barre d’intervention (haut)' },
          { kind: 'list', items: [
            'À gauche, le nom de l’intervention avec le **Menu** (changer d’intervention, jour/nuit, cette aide …) et l’horloge.',
            'À droite, **Annuler/Rétablir**, **Journal** et **+ Entrée**.',
          ] },
          { kind: 'sub', text: 'Barre d’outils (droite)' },
          { kind: 'list', items: [
            'Les outils de dessin et de placement ; épinglée en bas, la navigation de carte (zoom, ajuster, coordonnées).',
          ] },
        ],
      },
      {
        id: 'lage', title: 'Situation — carte', icon: 'map',
        blocks: [
          { kind: 'lead', text: 'La carte tactique par-dessus le fond de carte réel (zone d’intervention et environs).' },
          { kind: 'list', items: [
            '**Fond de carte** (en haut du panneau des couches) change le fond : Carto, OpenStreetMap ou satellite.',
            '**Agrandir/Réduire**, **Ajuster** et **Relever les coordonnées** en bas de la barre de droite. Lors du relevé, toucher la carte pour fixer un point (LV95 + WGS84) ; la boussole se réoriente au nord.',
            '**Vent** affiché en continu (direction + température) pour que la direction de propagation soit immédiatement visible.',
            '**Véhicules/moyens** apparaissent en direct par GPS (nom + orientation), votre propre position sous forme de point bleu discret.',
          ] },
        ],
      },
      {
        id: 'ebenen', title: 'Couches et données', icon: 'layers',
        blocks: [
          { kind: 'lead', text: 'Via **Couches**, vous affichez les données des réseaux et des dangers — classées par type.' },
          { kind: 'list', items: [
            '**Situation** — symboles tactiques, véhicules, croquis et notes.',
            '**Eau** — hydrantes, conduites, vannes, sources.',
            '**Eaux usées** — eaux sales/mixtes, eaux pluviales/propres, regards / grilles.',
            '**Gaz** — conduites.',
            '**Électricité** — lignes, installations PV.',
            '**Dangers** — crues, profondeur d’inondation.',
          ] },
          { kind: 'lead', text: 'Chaque couche peut être affichée/masquée et son opacité réglée.' },
          { kind: 'list', items: [
            '**Charger la carte hors ligne** (dans l’espace Couches) précharge les tuiles de carte, plans, symboles et géodonnées du lieu d’intervention.',
          ] },
          { kind: 'note', text: 'Les données des réseaux couvrent la zone d’intervention configurée et sont disponibles localement — elles fonctionnent aussi hors ligne.' },
        ],
      },
      {
        id: 'zeichnen', title: 'Dessin et symboles', icon: 'pen',
        blocks: [
          { kind: 'lead', text: 'Outils de la barre de droite en mode Situation.' },
          { kind: 'list', items: [
            '**Symbole** — le symbole tactique (FKS/VKF). Sélection rapide des symboles les plus courants ou recherche dans toute la bibliothèque. Toucher pour placer ; avec le verrou, en poser plusieurs à la suite.',
            '**Sélection** — toucher des objets, les déplacer, les ajuster dans l’éditeur.',
            '**Multiple** — lasso : sélectionner plusieurs symboles/dessins à la fois.',
            '**Ligne** — glisser ou toucher des points ; le style se choisit ensuite dans l’éditeur : **Main levée**, **Flèche** ou **Axe de sauvetage**.',
            '**Surface** — toucher les sommets (surface affichée dès 3 points) ; tirer/insérer/supprimer des sommets.',
            '**Périmètre de sécurité** — glisser du centre vers le bord fixe le rayon en mètres (remplissage réglable).',
            '**Note** — texte libre directement sur la carte.',
            '**Mesurer** — distance (longueur + profil altimétrique) ou surface (aire + périmètre). Tirer les points pour déplacer, toucher la ligne pour insérer des points intermédiaires, clic droit pour supprimer un point.',
          ] },
          { kind: 'sub', text: 'Préréglages des symboles' },
          { kind: 'lead', text: 'Chaque symbole n’apporte que les réglages utiles : **Rotation** pour les symboles orientés (flèches, échelles, parois), **Nombre** quand plusieurs comptent, **Étage** ou une **plage d’étages** (p. ex. escalier/ascenseur), **Propagation** pour les sinistres — plus les champs de saisie adaptés (p. ex. nom, substance, statut).' },
        ],
      },
      {
        id: 'plan', title: 'Plan — modules et bâtiments', icon: 'doc',
        blocks: [
          { kind: 'lead', text: 'Un tableau blanc par objet par-dessus les plans de module/bâtiment. Étage par étage, avec ses propres outils.' },
          { kind: 'list', items: [
            '**Symbole**, **Sélection**, **Dessiner** (couleur/épaisseur/type de ligne), **Note** (texte), **Équipe**.',
            '**Étages** en pile : avec les boutons **étage sup./sous-sol** sur le plan, ajouter un niveau au-dessus/en dessous.',
            '**Zoom/Ajuster** en bas de la barre d’outils, comme sur la carte.',
            '**Équipes** (binômes) sous forme de marqueurs colorés ; afficher/masquer les **Traces** montre leur trajet. Les pastilles d’équipe dont le binôme est « sorti » sont grisées/barrées.',
          ] },
        ],
      },
      {
        id: 'atemschutz', title: 'Surveillance ARI', icon: 'gauge',
        blocks: [
          { kind: 'lead', text: 'Surveillance sans faille de chaque binôme ARI selon FKS — le signal de sécurité est le **temps depuis le dernier contact radio**, et non une autonomie restante estimée.' },
          { kind: 'sub', text: 'Créer un binôme' },
          { kind: 'list', items: [
            '**Mission** d’abord : choisir le type (Sauver · Éteindre · Fouiller · Sécuriser · Reconnaître · Autre), le **but / lieu** en clair (p. ex. « 1er étage, appartement de gauche ») et, en option, le n° de conduite/tuyau.',
            '**Binôme et pression** : saisir le chef de groupe et le sapeur-pompier (noms déjà engagés en sélection rapide) et régler la pression d’entrée (bar).',
          ] },
          { kind: 'sub', text: 'Surveillance par binôme' },
          { kind: 'list', items: [
            'En grand, l’horloge **Depuis le dernier contact** : vert **Contact ok** → orange **Contact à faire** → rouge **En retard** (pas de contact en ~5 min) avec alarme.',
            '**Contact** (grand bouton) confirme le contact radio et réinitialise l’horloge.',
            '**Pression** réglée directement avec ± puis appliquée avec **Confirmer** — cela compte comme un contact et est journalisé ; une fausse manœuvre sans confirmer ne change rien. Une pression basse passe au rouge.',
            'Statut **Annoncé → En intervention → Repli → Sorti**. **Repli** peut être annulé avec **Poursuivre** ; un binôme sorti revient à la surveillance avec **Réengager** (nouvelle bouteille).',
            '**Journal** par binôme (dépliable) montre chaque contact avec l’heure et la pression.',
            '**Modifier** (crayon) ajuste la mission, le but/étage ou l’équipe en cours d’intervention.',
            'Les binômes en retard remontent en haut, un compteur apparaît ; le **son d’alarme** peut être coupé par appareil (cloche). Tout est consigné au journal.',
            'Chaque binôme peut être placé sur le plan (bouton « montrer sur le plan »).',
          ] },
        ],
      },
      {
        id: 'checkliste', title: 'Checklist', icon: 'check',
        blocks: [
          { kind: 'lead', text: 'Deux colonnes : des tâches à dérouler et un référentiel tactique consultable.' },
          { kind: 'list', items: [
            '**Tâches** — listes de contrôle d’intervention (p. ex. conduite, rapport de situation) avec barre de progression ; cocher les points, les embranchements suivent des procédures à plusieurs étapes.',
            '**Tactique · mots-clés** — rechercher un mot-clé et ouvrir l’entrée correspondante (avec code couleur des dangers et croquis).',
            'Lors de la reprise d’une alarme Divera, un mot-clé adapté est proposé automatiquement.',
          ] },
          { kind: 'lead', text: 'L’état est conservé et synchronisé sur tous les appareils.' },
        ],
      },
      {
        id: 'verlauf', title: 'Journal et entrée', icon: 'history',
        blocks: [
          { kind: 'lead', text: 'Un journal partagé et continu à travers Situation et Plan — la chronique de l’intervention.' },
          { kind: 'list', items: [
            '**+ Entrée** (en haut à droite) : un appui court ouvre la saisie de texte ; **maintenir appuyé** enregistre une **note vocale**. Des photos peuvent aussi être jointes.',
            'Les actions importantes (symbole posé, dessin créé/supprimé …) sont consignées automatiquement au journal.',
            '**Annuler/Rétablir** s’applique à Situation et Plan.',
            'Une entrée de journal avec un lieu ramène à l’endroit dans la carte ou le plan quand on la touche ; photos et notes vocales s’ouvrent/se lisent directement dans le journal.',
            '**Démarrer la relecture** rejoue Situation et Plan à un instant antérieur (curseur temporel ; l’édition est bloquée pendant ce temps).',
          ] },
        ],
      },
      {
        id: 'einsatz', title: 'Gérer les interventions', icon: 'swap',
        blocks: [
          { kind: 'lead', text: 'Tout dans le menu d’intervention (nom en haut à gauche).' },
          { kind: 'list', items: [
            '**Changer d’intervention** parmi les interventions ouvertes ; **Nouvelle intervention** (lieu choisissable sur la carte).',
            '**Pool Divera** — reprendre les alarmes entrantes.',
            '**Interventions** — ouvrir l’archive / les interventions antérieures.',
            '**Archiver l’actuelle** clôture l’intervention en cours.',
          ] },
        ],
      },
      {
        id: 'sync', title: 'Multi-appareils et hors ligne', icon: 'check',
        blocks: [
          { kind: 'lead', text: 'Tous les appareils voient la même intervention en direct.' },
          { kind: 'list', items: [
            'Les modifications sont partagées automatiquement ; le badge de synchro en haut indique l’état (enregistré/en attente).',
            'Les éditions simultanées sont fusionnées par objet (la modification la plus récente l’emporte).',
            '**Lecture seule** : les observateurs et les téléphones voient la situation en direct, sans les outils tactiques.',
          ] },
        ],
      },
      {
        id: 'bedienung', title: 'Utilisation et jour/nuit', icon: 'move',
        blocks: [
          { kind: 'sub', text: 'Toucher et glisser (tactile/iPad)' },
          { kind: 'list', items: [
            'Un doigt déplace la carte/le plan ; deux doigts zooment (pincer).',
            'Tirer un lasso avec **Multiple** sélectionne plusieurs objets ; les objets sélectionnés se déplacent en les tirant.',
          ] },
          { kind: 'sub', text: 'Souris' },
          { kind: 'list', items: [
            'La molette zoome ; **clic droit** (ou appui long) sur un point de mesure/de ligne le supprime, un clic sur une ligne insère un point intermédiaire.',
          ] },
          { kind: 'sub', text: 'Touches' },
          { kind: 'list', items: [
            '[[Échap]] annule l’outil actif ou désélectionne.',
            '[[Suppr]] / [[Retour arrière]] supprime la sélection (pas pendant la saisie dans un champ).',
          ] },
          { kind: 'sub', text: 'Jour / nuit' },
          { kind: 'list', items: [
            'Commutable dans le menu d’intervention — le mode nuit atténue la carte et l’interface pour l’obscurité.',
          ] },
        ],
      },
    ],
  },
  baseMap: 'Carte',
  floor: { eg: 'RDC', og: '+{n}', ug: '-{n}' },
  hoseHint: '~{n} tuyaux',
  noHistoryRows: 'Aucun événement enregistré',
  symbolSearchPlaceholder: 'Rechercher un symbole tactique …',
  noSymbolMatches: 'Aucun résultat',
  close: 'Fermer',
  closeDialog: 'Fermer',
  edit: 'Modifier',
  primarySymbol: { label: 'Symbole' },
  done: 'Terminé',
  cancel: 'Annuler',
  keepPlacing: 'Placer plusieurs',
  delete: 'Supprimer',
  undo: 'Annuler',
  redo: 'Rétablir',
  play: 'Lire',
  clear: 'Vider',
  mapTools: [
    { id: 'select', icon: 'select', label: 'Sélection', kind: 'tool' },
    { id: 'lasso', icon: 'marquee', label: 'Multiple', kind: 'tool' },
    { id: 'sep-symbol', sep: true, icon: '', label: '' },
    { id: 'symbol-slot', slot: true, icon: '', label: '' },
    { id: 'line', icon: 'pen', label: 'Ligne', kind: 'tool' },
    { id: 'area', icon: 'area', label: 'Surface', kind: 'tool' },
    { id: 'circle', icon: 'circle', label: 'Périmètre de sécurité', kind: 'tool' },
    { id: 'sep-anno', sep: true, icon: '', label: '' },
    { id: 'note', icon: 'type', label: 'Note', kind: 'tool' },
    { id: 'team', icon: 'flag', label: 'Équipe', kind: 'tool' },
    { id: 'measure', icon: 'measure', label: 'Mesurer', kind: 'tool' },
  ],
  planTools: [
    { id: 'pan', icon: 'select', label: 'Sélection' },
    { id: 'lasso', icon: 'marquee', label: 'Multiple' },
    { id: 'sep-symbol', sep: true, icon: '', label: '' },
    { id: 'symbol-slot', slot: true, icon: '', label: '' },
    { id: 'line', icon: 'pen', label: 'Ligne' },
    { id: 'area', icon: 'area', label: 'Surface' },
    { id: 'text', icon: 'type', label: 'Note' },
    { id: 'resource', icon: 'flag', label: 'Équipe' },
    { id: 'sep-measure', sep: true, icon: '', label: '' },
    { id: 'measure', icon: 'measure', label: 'Mesurer' },
  ],
  nav: {
    zoomIn: 'Agrandir',
    zoomOut: 'Réduire',
    fit: 'Ajuster',
    resetNorth: 'Orienter au nord',
    centerIncident: 'Centrer sur l’intervention',
    coords: 'Relever les coordonnées',
    coordsHint: 'Toucher la carte pour fixer',
    coordsLocked: 'Fixé — bouton pour un nouveau point',
    themeLabel: 'Affichage',
    autoMode: 'Automatique',
    dayMode: 'Jour',
    nightMode: 'Nuit',
  },
  toast: {
    recordingStarted: 'Enregistrement audio en cours …',
    audioSaved: 'Note audio enregistrée ({secs}s)',
    micDenied: 'Pas d’accès au micro – noté comme marqueur',
    merged: 'Modifications fusionnées',
  },
  mapHints: {
    placeSymbol: 'Touchez la carte pour placer « {name} »',
    areaDraft: 'Touchez les sommets de la surface sur la carte',
    placeNote: 'Touchez la carte pour poser une note',
    placeShape: 'Touchez la carte pour placer {name}',
  },
  dockHints: {
    symbol: 'Touchez la carte pour placer le symbole. Activez le verrou pour en poser plusieurs à la suite.',
    lasso: 'Tirez un cadre autour de plusieurs objets avec un doigt. Deux doigts déplacent toujours la carte.',
    line: 'Glissez sur la carte ou touchez des points pour tracer une ligne. Choisissez le style (Main levée · Flèche · Axe de sauvetage) ensuite dans l’éditeur.',
    area: 'Touchez au moins trois sommets sur la carte, puis terminez avec la coche.',
    circle: 'Glissez du centre vers l’extérieur pour fixer le rayon en mètres. Ajustez ensuite le rayon et le remplissage dans l’éditeur.',
    note: 'Touchez la carte pour poser une note.',
    shape: 'Touchez la carte pour placer la forme. Activez le verrou pour en poser plusieurs à la suite.',
    measure: 'Touchez des points sur la carte. La distance affiche la longueur et le profil altimétrique, la surface affiche l’aire et le périmètre. Tirez les points pour déplacer, touchez une ligne pour un point intermédiaire, clic droit sur un point pour le supprimer.',
  },
  map: {
    incidentHere: 'Lieu d’intervention',
    youHere: 'Ma position',
  },
  intake: {
    titleNew: 'Ouvrir une intervention',
    titleDivera: 'Reprendre l’alarme',
    diveraHint: 'Reprise depuis la source d’alarme — vérifier et corriger si nécessaire.',
    locationHead: 'Lieu',
    addressLabel: 'Adresse',
    addressPlaceholder: 'Rue n°, NPA localité',
    addressSearching: 'Recherche …',
    addressNoHits: 'Aucune adresse trouvée',
    objectButton: 'Objet des plans d’intervention',
    objectSearchPlaceholder: 'Rechercher un objet ou une adresse …',
    objectNear: 'À proximité',
    objectNoHits: 'Aucun objet trouvé',
    objectPlans: (n: number) => (n === 1 ? '1 plan' : `${n} plans`),
    objectNoPlans: 'aucun plan',
    mapPickButton: 'Placer sur la carte',
    coordSet: 'Coordonnée définie',
    coordNone: 'Aucun lieu — sera ouverte sans coordonnée',
    coordClear: 'Supprimer le lieu',
    keywordHead: 'Mot-clé et catégorie',
    titleLabel: 'Mot-clé / titre',
    titlePlaceholder: 'p. ex. Incendie de bâtiment, école',
    categoryLabel: 'Catégorie',
    detailsLabel: 'Texte du message (optionnel)',
    detailsPlaceholder: 'Indications supplémentaires sur le message',
    open: 'Ouvrir l’intervention',
    opening: 'Ouverture …',
    cancel: 'Annuler',
    errorCreate: 'Erreur lors de la création',
    errorTake: 'Échec de la reprise',
    errorUpdate: 'Échec de la mise à jour',
    editTitle: 'Modifier les données d’intervention',
    back: '← Retour',
    save: 'Enregistrer',
    saving: 'Enregistrement …',
    created: 'Intervention créée',
    taken: 'Alarme reprise',
    updated: 'Intervention mise à jour',
    alarmierungHead: 'Alarme',
    alarmTime: 'Heure d’alarme',
    alarmMessage: 'Message d’alarme',
    addressUnknown: 'Adresse inconnue',
    alarmOpen: 'Ouvrir',
    alarmOpening: 'Ouverture …',
    dismiss: 'Écarter',
    manualIncident: 'Intervention manuelle',
    attach: 'Ajouter \u00e0 une intervention existante',
    attachShort: '\u00c0 l\u2019intervention',
    attachConfirmTitle: 'Ajouter « {alarm} » à cette intervention ?',
    attachHint: 'Le message d\u2019alarme est consign\u00e9 dans le journal, les temps GPS suivent automatiquement. Le mot-cl\u00e9 et le lieu de l\u2019intervention restent inchang\u00e9s.',
    attachConfirm: 'Ajouter',
    attachDone: 'Alarme ajout\u00e9e \u00e0 l\u2019intervention',
    attachError: '\u00c9chec de l\u2019ajout',
    newDiveraAlarm: 'Nouvelle alarme',
    hide: 'Masquer',
    fromDivera: 'Repris depuis la source d’alarme',
    locationSet: 'Lieu défini',
    noLocationOnMap: 'Aucun lieu — placer sur la carte',
    ok: 'Ça convient',
    // Libellés d'AFFICHAGE de la liste des catégories — la valeur soumise reste l'allemand.
    kategorienLabels: {
      'Brandbekämpfung': 'Lutte contre l\'incendie',
      'Strassenrettung': 'Désincarcération',
      'Technische Hilfeleistung': 'Aide technique',
      'Elementarereignis': 'Intempéries',
      'Ölwehr': 'Lutte antipollution (hydrocarbures)',
      'Chemiewehr': 'Intervention chimique',
      'Strahlenwehr': 'Intervention radiologique',
      'Einsatz Bahnanlagen': 'Intervention ferroviaire',
      'BMA / unechte Alarme': 'DAI / fausses alarmes',
      'Gerettete Tiere': 'Sauvetage d\'animaux',
      'Dienstleistungen': 'Prestations de service',
      'Diverse Einsätze': 'Interventions diverses',
    },
  },
  // Libellés d'AFFICHAGE des symboles tactiques, indexés par le nom FireGIS brut. L'identité
  // stockée reste le nom brut ; seul le libellé est traduit.
  symbolNames: {
    'VKF Feuer': 'Feu',
    'VKF Rettungen': 'Sauvetage',
    'VKF Unfall': 'Accident',
    'VKF Gefaehrliche Stoffe': 'Matières dangereuses',
    'VKF Wasser': 'Eau',
    'FW Gefahr allgemein': 'Danger',
    'FW Gefahr Tafel': 'Plaque de danger',
    'FW Gefahr Radioaktiv': 'Radioactif',
    'FW Gefahr Ex': 'Explosion',
    'FW Gefahr G': 'Gaz',
    'FW Gefahr C': 'Chimique',
    'FW Gefahr W': 'Eau',
    'FW Elektroanlage': 'Installation électrique',
    'VKF Patientensammelstelle': 'Poste de rassemblement des blessés',
    'VKF Sanitaetshilfsstelle': 'Poste de secours',
    'VKF Totensammelstelle': 'Poste de rassemblement des décédés',
    'VKF Sammelstelle': 'Indemnes',
    'FW Sammelplatz': 'Point de rassemblement',
    'FW Warteraum': 'Zone d\'attente',
    'FW Verwundetennest': 'Nid de blessés',
    'VKF Bereich Sanitaet': 'Sanitaire',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Chef d\'intervention',
    'FW Offizier': 'Officier',
    'VKF Kontrollposten': 'Poste de contrôle',
    'VKF Informationszentrum': 'Centre d\'information',
    'VKF Bereich Materialdepot': 'Dépôt de matériel',
    'FW Absperrung': 'Barrage',
    'VKF Verkehrssperre ueberwacht': 'Barrage routier',
    'VKF Drehleiter': 'Échelle pivotante',
    'VKF Hubretter': 'Bras élévateur',
    'VKF Fahrzeug': 'Véhicule',
    'VKF Pumpe Typ2': 'Pompe',
    'VKF Helilandeplatz': 'Aire d\'atterrissage hélico',
    'VKF Luefter mobil': 'Ventilateur',
    'FW Entrauchung': 'Désenfumage',
    'FW Kleinloeschgeraet': 'Petit extincteur',
    'FW Sprungretter': 'Coussin de sauvetage',
    'FW Leiter': 'Échelle',
    'SI Ueberflurhydrant': 'Hydrant aérien',
    'SI Unterflurhydrant': 'Hydrant souterrain',
    'VKF Innenhydrant': 'Hydrant intérieur',
    'SI Wasserloeschposten': 'Poste d\'extinction',
    'WV Loeschweier': 'Étang d\'extinction',
    'SI Wasserbezugsort': 'Point de puisage',
    'SI Wasserdruckversorgung': 'Alimentation en eau sous pression',
    'GB Lift': 'Ascenseur',
    'GB Kamin': 'Cheminée',
    'GB Abzug': 'Évacuation',
    'SI Schieber': 'Vanne',
    'GB Elektrotableau': 'Tableau électrique',
    'GB Sprinklerzentrale': 'Centrale sprinkler',
    'GB Brandmeldezentrale': 'Centrale de détection incendie',
    'GB BMA Melder': 'Détecteur d’incendie',
    'GB Fernsignaltableau': 'Tableau de signalisation à distance',
    'GB Schluesseldepot': 'Dépôt de clés',
    'GB BA Wand F30': 'Paroi F30',
    'GB BA Wand F60': 'Paroi F60',
    'GB BA Wand F180': 'Paroi F180',
    'GB Ture BS R30': 'Porte R30',
    'GB Ture Durchgang': 'Passage',
    'GB Treppe 8': 'Escalier',
    'SI Nordpfeil': 'Flèche du nord',
    'SI Windrichtung': 'Direction du vent',
    'VKF Bereich Polizei': 'Police',
    'VKF Bereich Chemiewehr': 'Intervention chimique',
    'VKF Bereich Zivilschutz': 'Protection civile',
    'VKF Bereich Feuerwehr': 'Sapeurs-pompiers',
  },
  // En-têtes de catégories de la palette, indexés par la clé de catégorie allemande.
  symbolCategories: {
    'Schadenlage': 'Situation des dégâts',
    'Gefahren': 'Dangers',
    'Gebäude': 'Bâtiment',
    'Wasser': 'Eau',
    'Führung': 'Conduite',
    'Personen / Sanität': 'Personnes / Sanitaire',
    'Partner': 'Partenaires',
  },
  measure: {
    modeLine: 'Distance',
    modeArea: 'Surface',
    clear: 'Réinitialiser',
    deleteNode: 'Clic droit pour supprimer',
    distance: 'Distance',
    perimeter: 'Périmètre',
    area: 'Surface',
    hoses: 'Tuyaux',
    profile: 'Profil altimétrique',
    ascent: 'Montée',
    descent: 'Descente',
    min: 'Le plus bas',
    max: 'Le plus haut',
    profileLoading: 'Chargement du profil altimétrique …',
    profileNone: 'Aucun profil altimétrique disponible',
    hintLine: 'Au moins 2 points pour la distance',
    hintArea: 'Au moins 3 points pour la surface',
  },
  shapes: {
    sectionTitle: 'Formes',
    kindLabel: 'Forme',
    color: 'Couleur',
    rotateHint: 'Tirer la poignée pour pivoter',
    resizeHint: 'Tirer le coin pour redimensionner',
    names: { arrow: 'Flèche', cloud: 'Fumée', square: 'Rectangle' },
  },
  log: {
    noMicrophone: 'Note audio (pas d’accès au micro)',
    audioNote: 'Note audio',
    symbolPlaced: 'Symbole « {name} » posé',
    shapePlaced: '{name} placé',
    notePlaced: 'Note posée',
    areaDrawn: 'Surface dessinée',
    circleDrawn: 'Périmètre de sécurité dessiné',
    drawingCreated: 'Dessin créé',
    objectMoved: '{name} déplacé',
    objectDeleted: '{name} supprimé',
    drawingDeleted: 'Dessin supprimé',
    undo: 'Action annulée',
    redo: 'Action rétablie',
    journalNote: 'Note',
  },
  journal: {
    open: 'Journal',
    add: 'Entrée',
    addHint: 'Toucher pour une entrée · maintenir pour un message vocal',
    title: 'Journal',
    empty: 'Aucun événement enregistré',
    surfaceMap: 'Situation',
    surfacePlan: 'Plan',
    replay: 'Démarrer la relecture',
    replayHint: 'Rejouer situation et plan à un instant antérieur',
    composerTitle: 'Entrée de journal',
    textPlaceholder: 'Que s’est-il passé ? Message, observation, décision …',
    record: 'Enregistrer',
    recordStop: 'Arrêter l’enregistrement',
    dictate: 'Dicter',
    dictateStop: 'Arrêter la dictée',
    dictateListening: 'À l’écoute …',
    discardAudio: 'Abandonner l’enregistrement',
    audioUpload: 'Téléverser un audio',
    audioImportLabel: 'Enregistrement audio externe',
    audioStartLabel: 'Début de l’enregistrement',
    audioStartHint: 'Vérifier l’heure de début à l’aide du mémo vocal.',
    audioStartConfirm: 'Confirmer l’heure de début',
    audioImportedNote: 'Enregistrement audio externe ({duration})',
    audioDiscardImport: 'Supprimer le fichier audio',
    audioUploading: 'Téléversement …',
    audioOffline: 'Le téléversement audio nécessite une connexion. Resélectionner le fichier plus tard.',
    audioTooLarge: 'Fichier audio trop volumineux. Maximum : {max} MB.',
    audioUnsupported: 'Ce format audio n’est pas pris en charge.',
    audioUploadFailed: 'Échec du téléversement. Vérifier la connexion et réessayer.',
    playerOpen: 'Réécouter',
    editEntry: 'Modifier le texte',
    removeEntry: 'Supprimer l’entrée',
    entryRemoved: 'Entrée supprimée',
    playerEntryHere: 'Entrée à cet endroit',
    playerEntryPlaceholder: 'Qu’a-t-on entendu ? Message, décision …',
    playerEntries: 'Entrées dans cet enregistrement',
    playerNoEntries: 'Aucune entrée dans cette fenêtre pour l’instant.',
    playerSkipBack: '15 secondes en arrière',
    playerSkipFwd: '15 secondes en avant',
    playerSpeed: 'Vitesse de lecture',
    playerSeek: 'Position de lecture',
    playerOffline: 'La lecture nécessite une connexion.',
    sttTranscribe: 'Transcrire',
    sttRunning: 'Transcription en cours … Cela peut prendre quelques minutes.',
    sttFailed: 'Échec de la transcription : {error}',
    sttRetry: 'Réessayer',
    sttErrorGeneric: 'serveur injoignable',
    sttBanner: '{n} ébauches détectées — vérifier et reprendre.',
    sttTakeAll: 'Tout reprendre',
    sttTake: 'Reprendre',
    sttDismiss: 'Rejeter',
    sttEmpty: 'Aucune parole détectée.',
    sttTaken: 'Entrée ajoutée',
    photo: 'Photo',
    photoNote: 'Photo',
    discardPhoto: 'Abandonner la photo',
    pinMap: 'Épingler au centre actuel de la carte',
    pinPlan: 'Épingler au centre actuel du plan',
    send: 'Consigner',
    saved: 'Entrée de journal consignée',
    transcriptPlaceholder: 'Compléter la transcription',
    transcriptSave: 'Enregistrer',
    transcriptEdit: 'Modifier la transcription',
    transcriptAdd: 'Compléter la transcription',
    nachtrag: 'Complément',
    modeEntry: 'Entrée',
    modeReminder: 'Rappel',
    reminderTextPlaceholder: 'Rappeler quoi ? p. ex. vérifier le ventilateur, retour à la conduite …',
    reminderWhen: 'Échéance dans',
    reminderExact: 'Heure',
    reminderChipLabel: '+{n} min',
    reminderTomorrow: ' · demain',
    hourUp: 'Heure +', hourDown: 'Heure −', minUp: 'Minute +', minDown: 'Minute −',
    reminderSend: 'Définir le rappel',
    reminderSaved: 'Rappel défini',
    reminderNeedsDue: 'Choisir une échéance',
    reminderCreated: 'Rappel : {text}',
    dueTitle: 'Rappel échu',
    dueOne: 'Rappel échu',
    dueMany: '{n} rappels échus',
    dueDone: 'Fait',
    dueSnooze: '+10 min',
    dueOpen: 'Ouvrir dans le journal',
    openCount: '{n} ouvert(s)',
    doneLog: 'Rappel fait : {text}',
    snoozeLog: 'Rappel +{mins} min : {text}',
    dueAtLabel: 'échéance {t}',
    overdueLabel: 'en retard',
    doneState: 'fait',
    markDoneTitle: 'Marquer comme fait',
  },
  errors: {
    noMicrophone: 'Pas d’accès au micro. Note audio enregistrée comme marqueur.',
  },
  atemschutz: {
    title: 'Surveillance ARI',
    subtitle: 'Surveillance sans faille de chaque binôme ARI',
    empty: 'Aucun binôme en surveillance.',
    emptyHint: 'Créez un binôme pour démarrer la surveillance.',
    newTrupp: 'Créer un binôme',
    formCreateTitle: 'Créer un binôme',
    formEditTitle: 'Modifier le binôme',
    formRedeployTitle: 'Réengager',
    sectionAuftrag: 'Mission',
    sectionTeam: 'Binôme',
    auftragLabel: 'Type',
    // Libellés d'AFFICHAGE des types de mission, indexés par l'id (la valeur stockée reste l'id).
    auftragLabels: {
      retten: 'Sauver',
      loeschen: 'Éteindre',
      absuchen: 'Fouiller',
      sichern: 'Sécuriser',
      erkunden: 'Reconnaître',
      anderes: 'Autre',
    },
    zielLabel: 'Mission / but',
    zielPlaceholder: 'p. ex. 1er étage, appartement de gauche, personne disparue',
    zielOtherPlaceholder: 'Décrire la mission',
    leaderLabel: 'Chef de groupe',
    leaderPlaceholder: 'Nom du chef de groupe',
    memberLabel: 'Sapeur-pompier',
    memberPlaceholder: 'Nom (optionnel)',
    addMember: 'Ajouter un sapeur-pompier',
    lineNumberLabel: 'N° de conduite / tuyau',
    lineNumberPlaceholder: 'p. ex. 1',
    pressureLabel: 'Pression d’entrée (bar)',
    newPressureLabel: 'Nouvelle pression d’entrée (bar)',
    funkkanalSection: 'Canal radio',
    funkkanalDown: 'Canal radio bas',
    funkkanalUp: 'Canal radio haut',
    funkkanalUnit: 'Canal',
    clearName: 'Effacer le nom',
    notPresent: 'absent',
    noRoster: 'Aucun effectif disponible',
    typeName: 'Saisir un nom …',
    assignedConflict: '{name} est déjà dans un autre binôme.',
    cancel: 'Annuler',
    save: 'Enregistrer',
    start: 'Annoncer le binôme',
    reenterSubmit: 'Engager',
    sinceContact: 'Depuis le dernier contact',
    elapsed: 'Temps d’intervention',
    currentPressure: 'Pression',
    lowestPressure: 'Le plus bas',
    lineField: 'Conduite',
    edit: 'Modifier',
    pressureDown: '10 bar de moins',
    pressureUp: '10 bar de plus',
    pressureConfirm: 'Confirmer',
    pressureConfirmHint: 'Confirmer la nouvelle pression — compte comme contact',
    verlauf: 'Journal',
    readingKind: { entry: 'Engagé', contact: 'Contact', pressure: 'Pression' },
    clockOk: 'Contact ok',
    clockWarn: 'Contact à faire',
    clockOverdue: 'En retard',
    overdueBadge: '{n} en retard',
    actEnter: 'Engagé',
    actContact: 'Contact',
    actRueckzug: 'Repli',
    actContinue: 'Poursuivre',
    actExit: 'Sorti',
    actReenter: 'Réengager',
    exitConfirmTitle: 'Binôme sorti ?',
    exitConfirmMsg: 'Marquer le binôme comme sorti et terminer la surveillance ?',
    remove: 'Supprimer',
    removedToast: 'Binôme {name} supprimé',
    place: 'Placer',
    placeWhere: 'Placer où ?',
    placeNoTarget: 'Aucun plan disponible — créez d’abord un bâtiment depuis les contours.',
    showOnPlan: 'Montrer sur le plan',
    showOnMap: 'Montrer sur la carte',
    rosterLabel: 'Déjà saisis',
    preEntryHint: 'Pas encore engagé — appuyez sur « Engagé » dès que le binôme passe sous ARI.',
    alarmOn: 'Son d’alarme activé',
    alarmOff: 'Son d’alarme coupé',
    alarmNotifyTitle: 'ARI en retard',
    alarmNotifyBody: 'Binôme {name} en retard — établir le contact.',
    status: { angemeldet: 'Annoncé', aktiv: 'En intervention', rueckzug: 'Repli', ueberfaellig: 'En retard', raus: 'Sorti' },
    logRegister: 'Binôme {name} annoncé',
    logPlaced: 'Binôme {name} placé sur le plan',
    logPlacedMap: 'Binôme {name} placé sur la carte',
    placeLage: 'Carte de situation',
    logEntry: 'Binôme {name} engagé',
    logContact: 'Binôme {name} : contact confirmé',
    logPressure: 'Binôme {name} : pression {bar} bar',
    logRueckzug: 'Binôme {name} : repli',
    logContinue: 'Binôme {name} : intervention poursuivie',
    logEdit: 'Binôme {name} : mission ajustée',
    logExit: 'Binôme {name} sorti',
    logReenter: 'Binôme {name} réengagé',
    logAlarm: 'Alarme ARI : binôme {name} – {status}',
  },
  lineDecor: {
    S: 'Lance à mousse',
    W: 'Canon à eau',
    H: 'Rideau d’eau',
    P: 'Lance à poudre',
  } as Record<string, string>,
  incidents: {
    migratedTitle: 'État de travail migré',
    geojsonNotJson: 'Fichier JSON non valide.',
    geojsonNotFc: 'Pas une FeatureCollection GeoJSON.',
    geojsonNotWgs84: 'Les coordonnées ressemblent à du LV95, pas du WGS84 [lng, lat]. Reprojeter d’abord en EPSG:4326.',
  },
  entities: {
    photoLabel: 'Photo',
    photoSubtitle: 'Repère photo',
    noteSubtitle: 'Note',
    fallbackObjectName: 'Objet',
  },
  notes: {
    deleteTitle: 'Supprimer la note ?',
    deleteMsg: 'Cette note contient du texte. Vraiment la supprimer ?',
  },
  whiteboard: {
    documentListTitle: 'Documents de plan',
    fit: 'Ajuster',
    pan: 'Sélection',
    team: 'Équipe',
    draw: 'Dessiner',
    text: 'Note',
    symbol: 'Symbole',
    line: 'Ligne',
    area: 'Surface',
    dockHints: {
      draw: 'Glissez sur le plan pour dessiner à main levée. Choisissez la couleur, l’épaisseur et le type de ligne ci-dessous.',
      line: 'Touchez les sommets. Un double appui ou « Terminé » ferme la ligne. Choisissez le style ci-dessous.',
      area: 'Touchez les sommets (au moins 3). Un double appui ou « Terminé » ferme la surface.',
      text: 'Touchez le plan pour poser une note.',
      resource: 'Touchez le plan pour placer une équipe. Tirez pour la déplacer.',
      scale: 'Touchez les deux extrémités de l’échelle imprimée, puis saisissez la longueur réelle. Ensuite, les lignes avec « Longueur » affichent des mètres réels.',
      measure: 'Touchez des points sur le plan. « Distance » affiche la longueur, « Surface » l’aire + le périmètre — en mètres réels une fois l’échelle calibrée. Tirez les points pour déplacer, double appui pour en supprimer un.',
    },
    scale: {
      tool: 'Échelle',
      promptTitle: 'Définir l’échelle',
      promptBody: 'Longueur réelle de la distance relevée (p. ex. la barre d’échelle) :',
      unit: 'm',
      confirm: 'Appliquer',
      cancel: 'Annuler',
      chipCalibrated: 'Échelle : réf. {m} m',
      chipUncalibrated: 'Échelle non calibrée',
      recalibrate: 'Recalibrer',
      calibrate: 'Calibrer l’échelle',
      calibrateHint: 'Touchez deux points de la barre d’échelle',
      stale: 'Plan modifié — revérifier l’échelle',
      saved: 'Échelle calibrée (référence {m} m)',
      needsCalibration: 'Définir l’échelle : touchez les deux extrémités de la barre d’échelle',
    },
    finishShape: 'Terminé',
    cancelShape: 'Annuler',
    insertVertex: 'Insérer un point',
    dragVertex: 'Tirer le sommet · double appui pour supprimer',
    groupDeleted: 'Sélection supprimée',
    placeText: 'Note posée sur le plan',
    placeSymbol: 'Symbole « {name} » posé sur le plan',
    placeLine: 'Ligne tracée sur le plan',
    placeArea: 'Surface dessinée sur le plan',
    placeTeam: '{name} placé sur le plan',
    selectTrupp: 'Quel binôme ?',
    newTeam: 'Nouvelle équipe',
    showTrupp: 'Montrer dans ARI',
    markPosition: 'Marquer la position',
    positionMarked: '{name} : position marquée',
    clearTrail: 'Effacer la trace',
    clearTrailConfirm: 'Supprimer les {n} positions marquées de {name} ? La trace disparaît de la carte et du plan.',
    trailCleared: '{name} : trace effacée',
    teamColor: 'Couleur',
    trails: 'Traces',
    trailsOn: 'Afficher les traces',
    trailsOff: 'Masquer les traces',
    deleteLocked: 'Équipe avec historique enregistré — effacez d’abord la trace',
    drawCreated: 'Dessin créé sur le plan',
    placeSymbolHint: 'Touchez le plan pour placer « {name} »',
    textHint: 'Touchez le plan pour poser du texte',
    teamHint: 'Touchez le plan pour placer une équipe',
    textPlaceholder: 'Note ...',
    blankHint: 'Feuille vierge — annotez avec dessin, texte, symbole ou équipe',
    osmLoading: 'Chargement des contours de bâtiment …',
    osmError: 'Contours de bâtiment (OSM) injoignables',
    osmEmpty: 'Aucun bâtiment dans cette zone',
    osmPickHint: 'Touchez un bâtiment, puis appliquez',
    osmTransfer: 'Appliquer ({n})',
    osmClear: 'Effacer la sélection',
    addFloorUp: 'Ajouter un étage supérieur',
    addFloorDown: 'Ajouter un sous-sol',
    removeFloor: 'Supprimer l’étage',
    removeFloorConfirm: '{floor} contient des croquis ou des marqueurs. Supprimer l’étage quand même ?',
    floorRemoved: 'Étage supprimé',
    floorAdded: 'Étage ajouté',
    buildingReplaced: 'Bâtiment remplacé',
    replaceBuilding: 'Choisir un autre bâtiment',
    replaceBuildingConfirm: 'Des croquis existent sur les étages. Choisir un autre bâtiment et abandonner les étages actuels ?',
    otherObject: 'Autre objet',
    objectActive: 'Plans de « {name} »',
    objectReset: 'Réinitialiser sur l’objet suivant',
    objectSwitchConfirmTitle: 'Charger un autre objet',
    objectSwitchConfirm: 'Les plans de tous les modules basculent sur « {name} ». Changer l’objet actuel ?',
    objectSwitchConfirmCta: 'Charger l’objet',
    northLabel: 'N',
    northTitle: 'Direction du nord — bâtiment pivoté sur son grand axe',
    orientNorthUp: 'Nord en haut',
    orientLongAxis: 'Pivoter sur le grand axe',
  },
  contextPanel: {
    titlePlaceholder: 'Désignation ...',
    titleTypePick: 'Choisir le type …',
    floor: 'Étage',
    floorFrom: 'De l’étage',
    floorTo: 'À l’étage',
    floorNone: '–',
    floorClear: 'Réinitialiser',
    spread: 'Propagation',
    spreadH: 'Horizontale',
    spreadV: 'Verticale',
    spreadBounded: 'Limite',
    spreadBoundedTitle: 'Limite de propagation (propagation stoppée)',
    spreadLeft: 'vers la gauche',
    spreadRight: 'vers la droite',
    spreadUp: 'Étage supérieur (↑)',
    spreadDown: 'Sous-sol (↓)',
    count: 'Nombre',
    rotation: 'Rotation',
    rotationVehicle: 'Véhicule',
    rotationFan: 'Ventilateur',
    center: 'Centrer',
    resetGps: 'GPS',
    resetGpsTitle: 'Réinitialiser sur la position et le cap GPS',
    rotateHint: 'Tirer la poignée pour orienter',
    detailsTitle: 'Détails',
    notes: 'Notes',
    notesPlaceholder: 'Notes générales …',
    addField: 'Ajouter un champ',
    removeField: 'Supprimer le champ',
    fieldKeyPlaceholder: 'Désignation',
    fieldValuePlaceholder: 'Valeur',
    unHazardTitle: 'Matières dangereuses (ADR)',
    unClass: 'Classe',
    unKemler: 'Numéro de danger',
    unLabels: 'Étiquettes de danger',
    unPacking: 'Groupe d’emballage',
    unNoMatch: 'N° ONU introuvable dans la table ADR',
    unWater: 'Réagit dangereusement avec l’eau – NE PAS utiliser d’eau !',
    unLookupLabel: 'Fiche de données de sécurité (GESTIS)',
    kemler: {
      '2': 'Gaz (fuite sous pression ou par réaction)',
      '3': 'Liquide / gaz inflammable',
      '4': 'Solide inflammable',
      '5': 'Comburant (intensifie le feu)',
      '6': 'Toxique / risque d’infection',
      '7': 'Radioactif',
      '8': 'Corrosif',
      '9': 'Risque de réaction violente spontanée',
    } as Record<string, string>,
    kemlerDoubled: 'Danger renforcé (chiffre doublé)',
  },
  drawingEditor: {
    area: 'Surface',
    drawing: 'Dessin',
    circle: 'Périmètre de sécurité',
    radius: 'Rayon',
    fill: 'Remplissage',
    move: 'Déplacer',
    points: 'Points',
    preset: 'Style',
    color: 'Couleur',
    width: 'Épaisseur',
    lineStyle: 'Ligne',
    lineSolid: 'Continue',
    lineDashed: 'Pointillée',
    label: 'Texte',
    labelPlaceholder: 'Libellé …',
    areaLabelPlaceholder: 'p. ex. Secteur A / Section Est',
    marker: 'Marqueur',
    markerPlaceholder: 'p. ex. R',
    arrow: 'Pointe de flèche',
    ending: 'Terminaison',
    endingNone: 'Aucune',
    endingArrow: 'Flèche',
    endingTeilstueck: 'Tronçon',
    content: 'Contenu',
    contentPlain: 'Eau',
    lineNo: 'Conduite n°',
    floorTag: 'Étage',
    distance: 'Longueur',
    inputMode: 'Saisie',
    modeFreehand: 'Main levée',
    modeNodes: 'Points',
    on: 'Activé',
    off: 'Désactivé',
    lock: 'Verrouiller',
    lockHint: 'Verrouille la forme contre les déplacements accidentels ; touchez le verrou au centre pour déverrouiller.',
    unlockHold: 'Maintenir pour déverrouiller',
    unlocking: 'Déverrouillage …',
  },
  topBar: {
    offline: 'Hors ligne',
    tiles: 'Tuiles',
    recording: 'REC',
  },
  stepper: {
    less: 'moins',
    more: 'plus',
    reset: 'réinitialiser',
    typeToEnter: 'Toucher pour saisir',
  },
  confirm: {
    ok: 'OK',
    cancel: 'Annuler',
  },
  combo: {
    customDefault: 'Saisir …',
    empty: 'Aucun choix',
  },
  login: {
    subtitle: 'Aide à la conduite',
    pinEnter: 'Saisir le NIP',
    connectionFailed: 'Échec de la connexion au serveur',
    loadingRoster: 'Chargement de l’effectif…',
    noUsers: 'Aucun utilisateur enregistré',
    whoAreYou: 'Qui es-tu ?',
    loginFailed: 'Échec de la connexion',
    pleaseWait: 'Un instant, s’il te plaît…',
    clearDigit: 'Effacer',
  },
  errorBoundary: {
    title: 'Une erreur est survenue',
    body: 'La vue n’a pas pu être chargée. Vos modifications locales sont enregistrées et conservées.',
    reload: 'Recharger',
  },
  tabLock: {
    title: 'Ouvert dans un autre onglet',
    hint: 'Cet onglet est en lecture seule — l’édition est active dans l’autre onglet.',
    takeOver: 'Éditer ici',
  },
  mapPicker: {
    title: 'Placer le lieu sur la carte',
    hint: 'Touchez la carte pour définir le lieu',
    confirm: 'Utiliser ce lieu',
  },
  weather: {
    label: 'Météo',
    details: 'Détails météo',
    from: 'de',
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    cardinalsLong: ['Nord', 'Nord-est', 'Est', 'Sud-est', 'Sud', 'Sud-ouest', 'Ouest', 'Nord-ouest'],
    windTitle: 'Vent {dir} ({deg}°)',
    detailsHint: ' — toucher pour les détails',
    meteoHint: ' — toucher pour les détails MétéoSuisse',
    windDir: 'Direction du vent',
    windSpeed: 'Force du vent',
    gust: 'Rafales',
    precip: 'Précipitations',
    station: 'Station',
    source: 'Source',
    meteoRadar: 'Radar de précipitations MétéoSuisse',
    detailsUrl: 'https://www.meteosuisse.admin.ch/services-et-publications/applications/precipitations.html',
    conditions: {
      clear: 'Clair', fair: 'Beau', partly: 'Partiellement nuageux', overcast: 'Couvert',
      fog: 'Brouillard', drizzle: 'Bruine', rain: 'Pluie', snow: 'Neige',
      rainShowers: 'Averses de pluie', snowShowers: 'Averses de neige', thunder: 'Orage', cloudy: 'Nuageux',
    },
  },
  settings: {
    title: 'Réglages',
    deviceGroup: 'Appareil',
    colorScheme: 'Schéma de couleurs',
    symbolSize: 'Taille des symboles',
    offlineRadius: 'Rayon hors ligne',
    offlineRadiusSub: 'Carte et conduites autour de l’intervention',
    deviceFoot: 'S’applique uniquement à cet appareil. Un rayon plus petit = téléchargement hors ligne plus rapide et plus léger.',
    incidentGroup: 'Intervention',
    contactInterval: 'Contact radio ARI',
    contactIntervalSub: 'Intervalle jusqu’au contact dû (orange)',
    contactIntervalAria: 'Intervalle de contact radio',
    grace: 'Délai de grâce',
    graceSub: 'Alarme rouge après intervalle + délai',
    funkkanal: 'Canal radio',
    funkkanalSub: 'Par défaut pour les nouveaux binômes ARI',
    syncedFoot: 'Synchronisé avec tous les appareils',
    syncedFootViewer: ' · seul le chef d’intervention peut les modifier',
  },
  offline: {
    title: 'Préparation hors ligne',
    syncNow: 'Synchroniser maintenant',
    syncedAgo: 'Données d’intervention synchronisées {ago}',
    offline: 'Hors ligne – enregistré localement',
    pending: 'Enregistrement …',
    error: 'Erreur de synchro – enregistré localement',
    agoNever: 'pas encore',
    agoJustNow: 'à l’instant',
    agoMin: 'il y a {n} min',
    agoHour: 'il y a {n} h',
    checking: 'vérification …',
    ready: 'prêt',
    notLoaded: 'non chargé',
    loading: 'chargement …',
    rowSymbols: 'Symboles',
    rowHazmat: 'Matières dangereuses (ONU/ADR)',
    rowMap: 'Carte',
    noLayer: 'aucune couche',
    rowPlans: 'Plans',
    noObject: 'aucun objet',
    rowLeitung: 'Cadastre des conduites',
    geoAllReady: 'les {n} prêts',
    geoSome: '{cached}/{total} chargés',
    rowWeather: 'Météo',
    weatherUnreachable: 'injoignable',
    onlineOnly: 'en ligne uniquement',
    rowPersonnel: 'Effectif',
    personnelCount: '{n} personnes',
    rowObjectSearch: 'Recherche d’objet',
    loadingForOffline: 'Chargement pour le hors ligne …',
    loadAll: 'Tout charger pour le hors ligne',
    foot: 'Charge la carte, les plans, les symboles et les conduites de cette intervention sur cet appareil. La météo et la recherche d’objet nécessitent une connexion et ne sont pas disponibles hors ligne.',
    layerGroup: 'Hors ligne',
    loadMap: 'Charger la carte hors ligne',
    loadingShort: 'Chargement … {done}/{total}',
    dlDone: 'Carte disponible hors ligne ({n} tuiles)',
    dlDoneCapped: 'Carte disponible hors ligne (étendue limitée, {n} tuiles)',
    dlFailed: 'Échec du téléchargement hors ligne',
  },
  emptyApp: {
    title: 'Aucune intervention ouverte',
    bodyViewer: 'Aucune intervention n’est actuellement active.',
    bodyPoolOne: '1 alarme Divera dans le pool — ouvrez-la et vérifiez sur la carte.',
    bodyPoolMany: '{n} alarmes Divera dans le pool — ouvrez-en une et vérifiez sur la carte.',
    bodyEditor: 'Ouvrez une intervention ou reprenez une alarme Divera.',
    history: 'Historique',
  },
  incidentAlert: {
    kicker: 'Nouvelle intervention',
    switch: 'Basculer',
    open: 'Ouvrir',
    later: 'Plus tard',
  },
  capture: {
    title: 'Saisir l’intervention',
    invalid: 'Lien invalide ou saisie désactivée.',
    noIncidents: 'Aucune intervention saisissable pour le moment.',
    noIncidentsHint: 'Les interventions en cours et pas encore rapportées apparaissent ici. La vôtre manque ? Notez-la sur la feuille de saisie papier ou informez la conduite — elle peut la saisir plus tard.',
    whoTitle: 'Qui saisit ?',
    searchName: 'Chercher un nom …',
    back: 'Retour',
    alarmedAt: 'Alarme {t}',
    saveFailed: 'Échec de l’enregistrement — réessayer.',
    saveFailedOffline: 'Pas de réseau — la dernière modification n’a pas été enregistrée.',
    retry: 'Réessayer',
    savedOk: 'Enregistré',
    undo: 'Annuler',
    removedEntry: '{name} retiré (heures comprises)',
    mittelSet: '{label} : désormais {n} {unit}',
    mittelRemoved: '{label} retiré',
    stepLess: 'Un de moins',
    stepMore: 'Un de plus',
    mittelExtra: 'Autres positions saisies',
    gerettete: 'Sauvés',
    gerettetePersonen: 'Personnes',
    geretteteTiere: 'Animaux',
    rueckmeldung: 'Retour à la centrale',
    rueckName: 'Choisir un nom …',
    rueckZeit: 'Heure',
    jetzt: 'Maintenant',
    kurzberichtHead: 'Rapport succinct',
    kurzberichtPlaceholder: 'Que s’est-il passé, qu’a-t-on fait ?',
    zeitenHead: 'Horaires',
    gruppenHead: 'Alarme des groupes',
    fahrzeugeHead: 'Départs des véhicules',
    angabenHead: 'Indications',
    einsatzleiter: 'Chef d’intervention',
    rueckName2: 'Nom',
    rapportPdf: 'Rapport PDF',
    pdfFailed: 'Échec du PDF — réessayer.',
    sectionZeiten: 'Horaires',
    sectionAngaben: 'Indications',
    zeitenFilled: '{n} heures saisies',
    abschlussHead: 'Clôture',
    pdfMissing: 'Encore vide (imprimé comme champ à remplir) : {fields}',
    ausgerueckt: 'Départ',
    kontaktperson: 'Personne de contact',
    kontaktpersonPlaceholder: 'Propriétaire / requérant / responsable',
    von: 'de',
    bis: 'à',
    ende: 'Fin d’intervention',
    endeNow: 'Maintenant',
    sectionPersonen: 'Présences',
    presentCount: '{n} présents',
    tapHint: 'Toucher : absent → présent → parti. Heure à côté : de = arrivée, après le départ à = départ.',
    statePresent: 'présent',
    stateLeft: 'parti',
    sectionMaterial: 'Matériel',
    sectionAllgemein: 'Général',
    selectPerson: 'Choisir un nom …',
    whoHint: 'Figure dans le rapport comme « saisi par ».',
    cancel: 'Annuler',
    mittelCount: '{n} positions',
    pickMaterial: 'Choisir le matériel …',
    add: 'Ajouter',
    sectionNotizen: 'Notes',
    notePlaceholder: 'Note pour le journal …',
    footNote: 'Tout est enregistré en continu.',
    tapHelp: 'Aide à l\'utilisation',
  },
  incidentSwitcher: {
    noIncident: 'Aucune intervention',
    savedAt: 'Enregistré à {t}',
    saved: 'Enregistré',
    badgePending: 'Non synchronisé – enregistrement en cours',
    badgeOffline: 'Hors ligne – enregistré localement, se synchronise dès la reconnexion',
    badgeError: 'Échec de la synchro – enregistré localement, nouvel essai',
    syncNow: 'Synchroniser maintenant',
    incidents: 'Interventions',
    allIncidents: 'Toutes les interventions',
    archive: 'Clore l\u2019intervention',
    report: 'Rapport d’intervention',
    noOpenIncidents: 'Aucune intervention ouverte',
    logout: 'Déconnexion',
    appVersion: 'Version de l’app (build)',
  },
  update: {
    available: 'Mise à jour prête',
    hint: 'Active au prochain démarrage — fermer complètement l’app et la rouvrir.',
    dismiss: 'OK',
    updated: 'Mise à jour effectuée – {v}',
  },
  install: {
    menu: 'Installer comme app',
    bannerTitle: 'Installer KP Front comme app',
    bannerHint: 'Hors ligne, plein écran, icône propre.',
    bannerAction: 'Guide',
    dismiss: 'Plus tard',
    title: 'Installer comme app',
    why: 'Installé, KP Front fonctionne comme une app : disponible hors ligne sur place, en plein écran sans barre du navigateur, avec sa propre icône sur l’écran d’accueil.',
    nativeButton: 'Installer maintenant',
    nativeHint: 'Le navigateur demandera une confirmation — valider avec « Installer ».',
    manualIntro: 'Ou manuellement :',
    installed: 'Installé ! Lancer désormais KP Front depuis l’icône de l’app.',
    alreadyStandalone: 'KP Front fonctionne déjà comme app installée.',
    ios: {
      intro: 'Sur iPad/iPhone :',
      steps: [
        'Toucher le symbole de partage {share} dans la barre d’outils',
        'Choisir « Sur l’écran d’accueil »',
        'Confirmer avec « Ajouter »',
      ],
      note: 'Si « Sur l’écran d’accueil » manque : ouvrir la page dans Safari.',
    },
    android: {
      intro: 'Dans Chrome sur Android :',
      steps: [
        'Toucher le menu ⋮ en haut à droite',
        'Choisir « Installer l’application »',
        'Confirmer',
      ],
      note: 'Dans d’autres navigateurs : menu → « Ajouter à l’écran d’accueil ».',
    },
    desktop: {
      intro: 'Dans Chrome ou Edge :',
      steps: [
        'Cliquer sur l’icône d’installation à droite de la barre d’adresse',
        'Confirmer avec « Installer »',
      ],
      note: 'Sinon : menu du navigateur ⋮ → « Installer KP Front ».',
    },
    macSafari: {
      intro: 'Dans Safari sur Mac :',
      steps: [
        'Ouvrir le menu « Fichier »',
        'Choisir « Ajouter au Dock »',
        'Confirmer avec « Ajouter »',
      ],
      note: '',
    },
    unsupported: 'Ce navigateur ne permet pas l’installation. Ouvrir de préférence la page dans Chrome, Edge ou Safari et installer là.',
  },
  archived: {
    title: 'Intervention archivée',
    hint: 'Consultation seule — réactiver pour modifier.',
    reactivate: 'Réactiver',
  },
  history: {
    title: 'Interventions',
    empty: 'Aucune intervention pour le moment.',
    noLocation: 'sans lieu',
    searchPlaceholder: 'Rechercher une intervention …',
    noMatches: 'Aucun résultat.',
    groupOpen: 'Ouvertes',
    groupToday: 'Aujourd\u2019hui',
    groupWeek: '7 derniers jours',
    reactivate: 'Réactiver',
    reactivateConfirmTitle: 'Réactiver l\u2019intervention',
    reactivateConfirmMsg: 'L’intervention est rouverte et modifiable. Les modifications ultérieures apparaissent dans le journal et le rapport comme compléments.',
    reactivateConfirmBtn: 'Réactiver',
    statusArchived: 'Archivée',
    statusOpen: 'Ouverte',
    statusInProgress: 'En cours',
  },
  abschluss: {
    leftEarly: ' · jusqu’à {t}',
    steps: {
      zeiten: 'Horaires',
      anwesenheit: 'Présences',
      mittel: 'Moyens',
      abschluss: 'Clôture',
    },
    ausgerueckt: 'Départ',
    ende: 'Fin d’intervention',
    personen: '{n} saisis',
    stunden: 'Heures',
    von: 'de',
    bis: 'à',
    mittelCount: '{n} positions',
    mittelNone: 'Rien utilisé',
    mittelNoneOn: 'Rien utilisé ✓',
    complete: 'Clore l’intervention',
    backToRapport: 'Retour au rapport',
    confirmTitle: 'Clore l’intervention',
    confirmMsg: 'Le rapport est marqué comme clos et l’intervention archivée. Les corrections restent possibles et apparaissent comme addenda.',
    confirmMissing: 'Encore ouvert : {steps}. Clore quand même ?',
    confirmBtn: 'Clore',
    done: 'Rapport clos',
    failed: 'Échec de la clôture',
    corrected: 'Heures corrigées : {name}',
    attendanceRemoved: 'Présence de {name} supprimée',
  },
  datenquellen: {
    title: 'Sources de données',
    uploaded: 'Téléversé',
    uploadFailed: 'Échec du téléversement',
    invalidFilename: 'Le nom de fichier ne donne pas d’identifiant valide',
    layerAdded: 'Couche « {name} » ajoutée — visible au prochain chargement',
    addLayerFailed: 'Impossible d’ajouter la couche',
    globalDatasets: 'Jeux de données globaux',
    objectsCount: 'objets',
    replace: 'Remplacer',
    newGeoLayer: 'Nouvelle couche géo …',
    chooseGeojson: 'Choisir un GeoJSON …',
    labelPlaceholder: 'Désignation (p. ex. hydrantes)',
    groupPlaceholder: 'Groupe (p. ex. eau)',
    defaultGroup: 'Référence',
    kindLines: 'Lignes',
    kindPoints: 'Points',
    color: 'Couleur',
    adding: 'Chargement …',
    add: 'Ajouter',
    geojsonNoteBefore: 'GeoJSON en WGS84 [lng, lat]. Enregistré comme jeu de données global ',
    geojsonNoteAfter: '.',
    incidentObjects: 'Objets d’intervention',
    plansWord: 'plans',
    nearby: 'À proximité ({n})',
    allOther: 'Tous les autres objets',
    allObjects: 'Tous les objets',
  },
  personnelSync: {
    title: 'Synchroniser l’effectif avec {provider}',
    unknownError: 'Erreur inconnue',
    syncFailed: 'Échec de la synchronisation',
    countNew: 'nouveau(x)',
    countUpdated: 'mis à jour',
    countUnchanged: 'inchangé(s)',
    countStale: 'plus chez {provider}',
    querying: 'Interrogation de {provider} …',
    done: 'Synchronisation terminée.',
    resultCreated: '{n} créé(s)',
    resultUpdated: '{n} mis à jour',
    resultReactivated: ' (dont {n} réactivé(s))',
    resultUnchanged: '{n} inchangé(s)',
    resultDeactivated: '{n} désactivé(s)',
    staleHide: 'Masquer {n} personnes qui ne sont plus présentes chez {provider} (conservées pour les anciennes interventions, non supprimées)',
    syncing: 'Synchronisation …',
    sync: 'Synchroniser',
  },
  planPicker: {
    searchPlaceholder: 'Rechercher un nom ou une adresse …',
    autoNextObject: 'Objet le plus proche automatiquement',
    loading: 'Chargement des objets …',
    loadFailed: 'Les objets n’ont pas pu être chargés.',
    noObject: 'Aucun objet trouvé.',
    planOne: 'plan',
    planMany: 'plans',
    mapNote: 'Coordonnées parfois imprécises — la liste fait foi.',
    hideMap: 'Masquer la carte',
    showMap: 'Afficher la carte',
  },
  replay: {
    region: 'Relecture du journal',
    banner: 'JOURNAL · RELECTURE',
    subtitle: 'Vue du passé en lecture seule',
    backToLive: 'Retour au direct',
    loadFailed: 'Le journal n’a pas pu être chargé.',
    loading: 'Chargement du journal …',
    transport: 'Lecture',
    skipBack: '10 secondes en arrière',
    skipFwd: '30 secondes en avant',
    pause: 'Pause',
    speed: 'Vitesse',
    timepoint: 'Instant',
    now: 'Maintenant',
    noVehicleData: 'aucune donnée de véhicule · la situation tactique + le statut sont rejoués',
    noVehicleTitle: 'La capture Traccar→échantillon n’est pas encore branchée',
    markerSymbol: 'Symbole posé',
    markerDraw: 'Dessin',
    markerStatus: 'Statut',
    markerDivera: 'Divera',
    markerIncidentOpen: 'Intervention ouverte',
    markerSave: 'Point de sauvegarde',
  },
  report: {
    erfasser: 'Saisi par',
    gerettete: 'Sauvés',
    gerettetePersonen: 'personnes',
    geretteteTiere: 'animaux',
    rueckmeldungElz: 'Retour à la centrale',
    zeitenHead: 'Heures d’alarme / de départ',
    back: 'Retour',
    print: 'Imprimer',
    coverEyebrow: 'Rapport d’intervention',
    blankPlan: 'Plan vierge',
    keyword: 'Mot-clé',
    addressObject: 'Adresse / objet',
    einsatzleiter: 'Chef d’intervention',
    kontaktperson: 'Personne de contact',
    alarmierung: 'Alarme',
    ausgerueckt: 'Départ',
    incidentEnd: 'Fin d’intervention',
    incidentId: 'ID d’intervention',
    alarmMessage: 'Message d’alarme',
    summaryHead: 'Description brève / travaux effectués',
    partnerOrgs: 'Organisations partenaires',
    remarks: 'Remarques',
    sigKommandant: 'Commandant',
    kroki: 'Croquis',
    krokiState: '{title} · état {at}',
    atemschutz: 'Surveillance ARI',
    truppMembers: 'Membres',
    truppAuftrag: 'Mission / but',
    truppLine: 'Conduite',
    truppEntry: 'Entrée',
    truppExit: 'Sortie',
    colTime: 'Heure',
    colKind: 'Type',
    colPressure: 'Pression bar',
    noPressureLog: 'Aucun relevé de pression enregistré.',
    mittel: 'Matériel (indiquer la quantité)',
    personalHead: 'Personnel / présence',
    personalHint: 'Cocher, compléter de–à si nécessaire',
    partnerOther: 'Autres',
    journal: 'Journal d’intervention',
    colArea: 'Domaine',
    colEntry: 'Entrée',
    audioPresent: 'Audio présent',
    audioNotTranscribed: ', non transcrit',
    photo: 'Photo',
    transcript: 'Transcription',
    noEntries: 'Aucune entrée.',
    nachtraege: 'Compléments après la fin de l’intervention',
    planFallback: 'Plan',
    proofOffline: 'Vérification impossible (hors ligne)',
    proofIntact: 'Chaîne de hash intacte',
    proofBroken: 'Chaîne de hash rompue',
    proofBrokenAt: 'Chaîne de hash rompue à #{seq}',
    areaManual: 'Manuel',
    areaAtemschutz: 'ARI',
    drawCircle: 'Périmètre de sécurité',
    drawAreaLabeled: 'Section « {label} »',
    drawArea: 'Surface',
    drawRescueAxis: 'Axe de sauvetage',
    drawMeasureArrow: 'Flèche de mesure',
    drawLine: 'Ligne',
  },
  wheel: {
    day: 'Jour',
    month: 'Mois',
    year: 'Année',
    hour: 'Heure',
    minute: 'Minute',
    now: 'Maintenant',
    ok: 'OK',
    clear: 'Effacer',
  },
  preflight: {
    pdfFull: 'Rapport d’intervention (PDF)',
    pdfBusy: 'Création du PDF …',
    geretteteLabel: 'Sauvés',
    gerettetePersonen: 'Personnes',
    geretteteTiere: 'Animaux',
    gruppenLabel: 'Alarme des groupes',
    fahrzeugeLabel: 'Départs des véhicules',
    ausgeruecktDerived: 'repris des heures des véhicules',
    vorOrtShort: 'sur place',
    zurueckShort: 'retour',
    rueckmeldungLabel: 'Retour à la centrale',
    rueckmeldungName: 'Nom',
    rueckmeldungZeit: 'Heure',
    title: 'Imprimer le rapport d’intervention',
    rapportHead: 'Données du rapport',
    fromDispatch: 'D’après les données d’intervention',
    edit: 'Modifier',
    alarmMessage: 'Message d’alarme',
    alarmierung: 'Alarme',
    notRecorded: 'Non saisi',
    summaryLabel: 'Description brève',
    summaryPlaceholder: 'Que s’est-il passé / qu’a-t-on trouvé ?',
    einsatzleiterLabel: 'Chef d’intervention',
    einsatzleiterPlaceholder: 'Sélectionner ou saisir',
    kontaktpersonLabel: 'Personne de contact',
    kontaktpersonPlaceholder: 'Propriétaire / annonceur / responsable',
    incidentEndLabel: 'Fin d’intervention',
    now: 'Maintenant',
    remarksLabel: 'Remarques',
    remarksPlaceholder: 'Optionnel',
    sectionsHead: 'Sections',
    groupMap: 'Carte & plans',
    groupContents: 'Contenus',
    groupAdvanced: 'Avancé',
    toggleKroki: 'Croquis',
    plansLabel: 'Plans',
    plansAnnotated: 'Annotés ({n})',
    plansAll: 'Tous',
    plansNone: 'Aucun',
    toggleAtemschutz: 'Surveillance ARI ({n})',
    toggleAttendance: 'Présence ({n})',
    toggleJournal: 'Journal d’intervention',
    toggleDetailedAudit: 'Preuve d’intégrité détaillée',
    framingTitle: 'Choisir le cadrage du croquis',
    framingHint: 'Déplacez et zoomez la carte — exactement ce cadrage sera imprimé.',
    framingFit: 'Zoomer sur l’intervention',
    framingConfirm: 'Utiliser ce cadrage',
    controlHead: 'Contrôle',
    proofChecking: 'Vérification de la preuve d’intégrité …',
    annotatedDefault: '{n} plans annotés sont imprimés par défaut.',
    missingTranscripts: '{n} entrée(s) audio sans transcription — à compléter pour le procès-verbal.',
    fixTranscripts: 'Compléter dans le journal',
    stateNote: 'État : toute l’intervention jusqu’à la création du rapport ({at}).',
    cancel: 'Annuler',
    openPrint: 'Ouvrir l’aperçu d’impression',
  },
  printRelay: {
    send: 'Imprimer',
    sending: 'Envoi en cours …',
    queued: 'Envoyé à l’imprimante de caserne',
    confirmTitle: 'Imprimer',
    confirmMsg: 'Envoyer le rapport d’intervention à l’imprimante de caserne ?',
    confirmBtn: 'Imprimer',
    undo: 'Annuler',
    cancelled: 'Impression annulée',
    undoTooLate: 'Trop tard — le document est déjà à l’imprimante',
    failed: 'Échec de l’envoi à l’imprimante de caserne',
    online: 'Imprimante de caserne joignable',
    offline: 'Imprimante de caserne hors ligne',
    offlineConfirmTitle: 'Imprimante de caserne hors ligne',
    offlineConfirmMsg: 'Le relais d’impression ne répond pas pour le moment. Le document sera imprimé dès qu’il sera à nouveau joignable. Envoyer quand même ?',
    offlineConfirmBtn: 'Envoyer quand même',
  },
  anwesenheit: {
    title: 'Présence',
    summary: '{present} présents · {left} partis · {total} effectif',
    reload: 'Recharger l’effectif',
    loading: 'Chargement …',
    refresh: 'Actualiser',
    searchPlaceholder: 'Rechercher un nom',
    clearSearch: 'Effacer la recherche',
    legendFrei: 'non présent',
    legendPresent: 'présent',
    legendLeft: 'parti',
    loadFailedTitle: 'L’effectif n’a pas pu être chargé.',
    loadFailedHint: 'Hors ligne ou serveur injoignable. La dernière liste chargée est conservée.',
    emptyTitle: 'Aucun effectif disponible.',
    emptyHint: 'Synchronisez l’effectif depuis Divera.',
    retry: 'Réessayer',
    noMatches: 'Aucun résultat.',
    lockedTitle: 'Dans un binôme ARI — annoncez d’abord le binôme sorti',
    notInDivera: 'Plus dans Divera',
    weg: 'parti',
    editTime: 'Ajuster l’heure',
  },
  checklists: {
    railLabel: 'Checklists',
    showList: 'Afficher la liste',
    groupTasks: 'Tâches',
    groupTactics: 'Tactique · mots-clés',
    searchPlaceholder: 'Rechercher un mot-clé ...',
    searchAria: 'Rechercher un mot-clé',
    matching: 'Correspond : {title}',
    noMatches: 'Aucun résultat.',
    none: 'Aucune checklist disponible pour le moment.',
    pickEntry: 'Choisir ou rechercher un mot-clé.',
    done: 'fait',
    variantLabel: 'Variante',
    pickVariant: 'Choisir une variante pour voir les tâches.',
    milestoneTitle: 'Jalon — apparaît dans le journal',
    actionLabels: { journal: 'Journal', plan: 'Plan', draw: 'Dessiner' },
    hazardLabels: { red: 'Incendie', orange: 'Dangers', green: 'Circulation', yellow: 'Technique', blue: 'Eau' },
    diagramAlt: 'Diagramme page {page}',
  },

  admin: {
    common: {
      configLoading: 'Chargement de la configuration…',
      copy: 'Copier',
      copied: 'Copié',
      confirmYes: 'Oui, exécuter',
      confirmNo: 'Annuler',
    },
    shell: {
      verwaltung: 'Administration',
      toLageMap: '← Vers la carte de situation',
      logout: 'Déconnexion',
      openSections: 'Ouvrir les sections',
      closeSections: 'Fermer les sections',
      navAria: 'Sections d’administration',
    },
    denied: {
      title: 'Aucun accès',
      body: 'L’administration est réservée aux éditeurs. Vous êtes connecté en tant que {name}.',
    },
    nav: {
      groupStation: 'Station',
      groupPersonen: 'Personnes',
      groupDaten: 'Données',
      groupSystem: 'Système',
      identitaet: { label: 'Caserne et carte', title: 'Caserne et carte', lede: 'Nom, langue, couleur de marque, logos et vue initiale de la carte pour cette installation.' },
      karte: { label: 'Carte', title: 'Carte', lede: 'Vue initiale de la carte de situation (centre + zoom), avant qu’une intervention soit choisie.' },
      doktrin: { label: 'Doctrine', title: 'Doctrine', lede: 'Paramètres FKS de ce corps : canal radio par défaut, intervalle de contact ARI et pré-alerte.' },
      fahrzeuge: {
        label: 'Symboles',
        title: 'Symboles',
        lede: 'Listes de choix pour la saisie en Situation. Suggestions — la saisie libre reste possible.',
        tip: 'Chaque liste rattache des suggestions de choix à un champ de symbole — p. ex. les types de véhicule à « VKF véhicule · titre ». Suggestions uniquement ; la saisie libre reste toujours possible en Situation.',
      },
      ebenen: { label: 'Couches de carte', title: 'Couches de carte', lede: 'Couches de référence / de réseaux de ce corps (hydrantes, cadastre des conduites, WMS cantonal …). Les fonds de carte sont nationaux / livrés.' },
      objektplaene: {
        label: 'Plans d’objet',
        title: 'Plans d’objet (modules)',
        lede: 'Catalogue de modules de ce corps : quels modules existent, leur libellé (M1, 2/3 …), l’ordre et les règles de détection pour l’import. Vide = modules standard livrés.',
        tip: 'Une seule configuration pour deux usages : les tuiles de plan dans l’app et l’analyse de fichiers de import_einsatzplaene (l’importeur récupère cette liste via /api/config). « Famille » génère des sous-modules à partir du nom de fichier (Modul 5 - Wasser → modul5-wasser) ; « Combiné avec » remplit plusieurs emplacements depuis une feuille combinée (Modul 2-3 → modul2, modul3).',
      },
      mitglieder: { label: 'Membres et accès', title: 'Membres et accès', lede: 'Qui peut se connecter, avec quel rôle et quel NIP.' },
      mannschaft: { label: 'Effectif', title: 'Effectif', lede: 'Effectif local canonique : saisie manuelle et CSV toujours disponibles ; une source de personnel peut synchroniser les données.' },
      erfassung: { label: 'Saisie', title: 'Saisie (affiche)', lede: 'L’affiche de saisie pour le local : un code QR permettant d’enregistrer présences, matériel et notes d’une intervention récente sans connexion.' },
      einsaetze: { label: 'Historique', title: 'Historique des interventions', lede: 'Toutes les interventions actuelles et historiques avec heure de début, statut, source, état du rapport et dernière modification.' },
      divera: {
        label: 'Alarmes',
        title: 'Réception des alarmes',
        lede: 'État de la source d’alarme configurée, alarmes entrantes non attribuées, actualisation et test de connexion.',
        tip: 'Le « pool » sont les alarmes reprises de Divera, pas encore attribuées. « Actualiser » les récupère à nouveau depuis le serveur.',
      },
      traccar: {
        label: 'Suivi des véhicules',
        title: 'Suivi des véhicules',
        lede: 'État de la source de suivi configurée, véhicules émetteurs, signal le plus récent et test de connexion.',
        tip: 'GPS en direct des véhicules via Traccar. « connecté » = liaison active ; « en ligne » = véhicules qui émettent actuellement.',
      },
      statistik: {
        label: 'Export statistiques',
        title: 'Export statistiques',
        lede: 'Flux de données en lecture seule de toutes les interventions pour des analyses externes (p. ex. statistique annuelle).',
      },
      objekte: {
        label: 'Objets et plans',
        title: 'Objets et plans',
        lede: 'Objets enregistrés et leurs plans (module, version, état). En consultation uniquement.',
        tip: 'Les plans sont des feuilles PDF par objet, classées par module FKS : module 1 vue d’ensemble, 2 accès, 3 intérieur, 2-3 combiné, 6 plans de bâtiment.',
      },
      geodaten: {
        label: 'Géodonnées',
        title: 'Géodonnées et symboles',
        lede: 'Données de référence importées : couches GeoJSON, jeux de symboles et PDF. En consultation uniquement.',
        tip: 'Données de référence propres à la station (hydrantes, conduites …). « Jeu de données » = une couche, « Features » = objets contenus, « Source » = sa provenance.',
      },
      system: { label: 'Système et maintenance', title: 'Système et maintenance', lede: 'État et maintenance : version, base de données, inventaire, stockage et le cache hors ligne de cet appareil.' },
      sicherung: { label: 'Sauvegarde', title: 'Sauvegarde', lede: 'Sauvegarder la configuration dans un fichier ou restaurer un fichier sauvegardé.' },
    },
    erfassung: {
      cardTitle: 'Affiche de saisie',
      body: 'Quiconque scanne l’affiche au local peut enregistrer présences, matériel et notes d’une intervention récente — sans connexion, sans formation.',
      stateLabel: 'Saisie',
      stateOn: 'active',
      stateOff: 'désactivée',
      enableBtn: 'Activer & générer le jeton',
      rotateBtn: 'Renouveler le jeton',
      rotateMsg: 'Générer un nouveau jeton ? Toutes les affiches imprimées deviennent immédiatement invalides.',
      rotated: 'Nouveau jeton généré — réimprimer l’affiche.',
      disableBtn: 'Désactiver',
      disableMsg: 'Désactiver la saisie ? Le code QR de toutes les affiches cessera de fonctionner.',
      disabled: 'Saisie désactivée.',
      printBtn: 'Affiche en PDF (A4)',
      posterHead: 'Saisir l’intervention',
      posterStep1: 'Scanner le code QR avec le téléphone',
      posterStep2: 'Toucher l’intervention et choisir son nom',
      posterStep3: 'Cocher les présents, saisir matériel et notes',
      failed: 'Échec de l’action',
      sheetBtn: 'Feuille de saisie en PDF (A4)',
      sheetCardTitle: 'Feuille de saisie (papier)',
      sheetCardBody: 'Le jumeau papier du rapport numérique : mêmes champs, même ordre — pour l’intervention entièrement analogique. Générée à partir de l’effectif, du matériel et de la configuration actuels ; photographier les feuilles remplies (journal/annexe) et les reporter dans l’app.',
      sheetHead: 'Feuille de saisie d’intervention',
      sheetIncident: 'Intervention',
      sheetAdresse: 'Adresse / objet',
      sheetEigentuemer: 'Propriétaire / responsable',
      sheetGerettete: 'Sauvés (personnes / animaux)',
      sheetZeiten: 'Heures d’alarme / de départ',
      sheetPartner: 'Organisations partenaires',
      sheetPartnerOther: 'Autres',
      sheetRueckmeldung: 'Retour à la centrale',
      sheetZeit: 'Heure',
      sheetDate: 'Date',
      sheetAlarm: 'Alarme',
      sheetEnde: 'Fin d’intervention',
      sheetKontakt: 'Personne de contact',
      sheetSignatures: 'Visa',
      sheetName: 'Nom',
      sheetEl: 'Chef d’intervention',
      sheetKdt: 'Commandant',
      sheetPersonen: 'Présences (cocher, de–à si besoin)',
      sheetMaterial: 'Matériel (indiquer les quantités)',
      sheetNotizen: 'Description brève / travaux effectués',
      hint: 'Le lien couvre les interventions en cours et pas encore rapportées ; les rapportées disparaissent après quelques heures (12 h par défaut, alarms.captureWindowHours).',
    },
    statistik: {
      body: 'Export en lecture seule de toutes les interventions sous forme d’enregistrements JSON plats (métadonnées, horaires, présences de–à, matériel, statut du rapport) — pour des analyses externes comme la statistique annuelle. Aucun droit d’écriture, pas d’accès à la carte ni à l’administration.',
      stateLabel: 'Export',
      stateOn: 'actif',
      stateOff: 'désactivé',
      enableBtn: 'Activer et générer un jeton',
      rotateBtn: 'Renouveler le jeton',
      rotateMsg: 'Générer un nouveau jeton ? Tous les outils d’analyse connectés devront être reconfigurés.',
      rotated: 'Nouveau jeton généré.',
      disableBtn: 'Désactiver',
      disableMsg: 'Désactiver l’export statistiques ? Les outils connectés ne recevront plus de données.',
      disabled: 'Export désactivé.',
      failed: 'Échec de l’action',
      exampleLabel: 'Exemple de requête',
      tokenLabel: 'Jeton',
      hint: 'Garder le jeton secret — il donne un accès en lecture à toutes les données d’intervention, noms compris. À transmettre à l’outil d’analyse via l’en-tête X-Stats-Token (ou ?t=).',
    },
    incidentHistory: {
      loading: 'Chargement des interventions…', error: 'Impossible de charger les interventions.', search: 'Rechercher titre, adresse ou source…',
      none: 'Aucune intervention.', noMatches: 'Aucune intervention ne correspond.', started: 'Début', incident: 'Intervention', status: 'Statut',
      source: 'Source', report: 'Rapport', updated: 'Modifié', open: 'ouverte', closed: 'terminée', complete: 'complet', incomplete: 'en attente',
    },
    autosave: {
      retry: 'Réessayer',
      saving: 'Enregistrement…',
      pending: 'Enregistrement des modifications…',
      saved: 'Enregistré',
      sessionExpired: 'Session expirée — veuillez vous reconnecter.',
      saveFailed: 'Échec de l’enregistrement',
      loadFailed: 'La configuration n’a pas pu être chargée',
    },
    usageBar: { aria: '{pct}% occupé' },
    identity: {
      appName: 'Nom de l’app',
      appNameTip: 'Affiché dans la barre de titre, le login et l’aide. Vide = « KP Front ».',
      accentColor: 'Couleur d’accent',
      accentColorHint: 'Couleur de marque (login / splash)',
      accentColorTip: 'Couleur de marque du corps ; se propage dans tout le système de couleurs --accent (login, splash, accents).',
      pickAccentColor: 'Choisir la couleur d’accent',
      language: 'Langue',
      languageHint: 'Langue de l’interface pour tout le corps',
      languageTip: 'Langue de tous les textes de l’interface. S’applique à tout le corps (un déploiement = une langue) ; appliquée au chargement de l’app. fr/it ne sont que partiellement traduits et reviennent sinon à l’allemand.',
      pickLanguage: 'Choisir la langue',
      kommandant: 'Commandant',
      kommandantTip: 'Nom du commandant — préimprimé à côté de la ligne de signature « Kommandant » sur le rapport d’intervention. Vide = libellé seul.',
    },
    map: {
      centerLon: 'Centre — longitude (lon)',
      centerLonTip: 'Longitude (WGS84) du démarrage de la carte, avant qu’une intervention soit choisie.',
      centerLat: 'Centre — latitude (lat)',
      centerLatTip: 'Latitude (WGS84) du démarrage de la carte, avant qu’une intervention soit choisie.',
      zoom: 'Zoom',
      zoomTip: 'Niveau de zoom initial de la carte (plus élevé = plus proche ; ~16 montre l’étendue d’un quartier).',
    },
    doctrine: {
      defaultFunkkanal: 'Canal radio (par défaut)',
      defaultFunkkanalTip: 'Canal radio préréglé d’une nouvelle intervention.',
      contactInterval: 'Intervalle de contact (min)',
      contactIntervalTip: 'Intervalle de contact ARI ; une fois écoulé, le contact est dû (orange).',
      contactGrace: 'Délai de grâce (s)',
      contactGraceTip: 'Secondes après le contact dû avant l’alarme « en retard ».',
    },
    backup: {
      title: 'Sauvegarde',
      caption: 'Sauvegarder la configuration dans un fichier ou restaurer un fichier sauvegardé. L’import la remplace entièrement (sans les intégrations env).',
      export: 'Exporter la configuration',
      import: 'Importer la configuration',
      lastChangedBy: 'Dernière modification par {name} le {date}',
      lastChanged: 'Dernière modification le {date}',
      notJson: 'Le fichier n’est pas un JSON valide.',
      notConfig: 'Le fichier ne contient pas de configuration valide.',
      replaceConfirm: 'Ce fichier remplace entièrement la configuration actuelle. La précédente est d’abord téléchargée comme sauvegarde. Continuer ?',
      imported: 'Configuration importée.',
      invalidSchema: 'Configuration invalide (422) — le fichier ne correspond pas au schéma.',
      importFailed: 'Échec de l’import.',
    },
    common2: {
      cancel: 'Annuler',
      save: 'Enregistrer',
      saving: 'Enregistrement…',
      create: 'Créer',
      edit: 'Modifier',
      remove: 'Supprimer',
      notAvailable: 'non disponible',
      unknownError: 'Erreur inconnue',
    },
    infoTip: { prefix: 'Info : {label}' },
    stringList: {
      addPlaceholder: 'Ajouter…',
      removeItem: 'Supprimer {item}',
    },
    fleet: {
      filterPlaceholder: 'Rechercher un symbole …',
      loading: 'Chargement de la bibliothèque de symboles …',
      noMatches: 'Aucun symbole ne correspond à la recherche.',
      noAttributes: 'Aucun champ.',
      fieldTitle: 'Titre',
      fieldMeaningTitle: 'Champs spéciaux',
      guideTitle: 'Explication des champs et propriétés',
      fieldGlossary: {
        Titel: 'Désignation visible du véhicule.', Status: 'État selon le contexte, p. ex. sauvé ou vanne ouverte/fermée.',
        Stoff: 'Nom de la matière dangereuse.', 'UN-Nr': 'Numéro ONU à quatre chiffres.', Einheit: 'Organisation ou unité engagée.',
        Name: 'Personne issue de l’effectif.', Funktion: 'Fonction de commandement.', Fahrer: 'Conducteur issu de l’effectif.', Typ: 'Type d’appareil ou d’exécution.',
      },
      propsLabel: 'Propriétés',
      controls: {
        rotation: 'Pivotable',
        rotation2: 'Deuxième rotation',
        count: 'Nombre',
        floor: 'Étage',
        floorRange: 'Plage d’étages',
        spread: 'Propagation',
      },
      propertiesMeaningTitle: 'Propriétés',
      controlGlossary: {
        rotation: 'Le symbole peut être tourné après son placement.', rotation2: 'Un deuxième angle de direction indépendant est disponible.',
        count: 'Plusieurs éléments identiques sont gérés par un nombre.', floor: 'Le symbole peut être affecté à un étage.',
        floorRange: 'Le symbole peut couvrir une plage d’étages.', spread: 'La direction et l’étendue d’une propagation peuvent être représentées.',
      },
      listsMeaningTitle: 'Source et liste de choix.',
      noConfiguredLists: 'Aucune liste propre n’est configurée pour cette caserne. Nom et conducteur proviennent de l’effectif ; les autres champs restent libres.',
      configuredLists: '« Configuré » affiche les suggestions de la caserne et « Depuis l’effectif » utilise les personnes. Le texte libre reste possible.',
      rosterField: 'Depuis l’effectif',
      rosterBadgeHint: 'rempli depuis l’effectif',
      configuredBadge: 'Configuré',
      configuredBadgeHint: 'défini dans la configuration de la station',
      freitextBadge: 'Texte libre',
      freitextBadgeHint: 'aucune liste — l’opérateur saisit librement',
      freitextValue: 'saisie libre',
    },
    members: {
      add: 'Ajouter un membre',
      addCaption: 'Nom d’utilisateur pour se connecter, nom affiché sur les tuiles de login. NIP : exactement {n} chiffres.',
      username: 'Nom d’utilisateur',
      usernamePlaceholder: 'p. ex. fu',
      displayName: 'Nom affiché',
      displayNamePlaceholder: 'p. ex. Felix Muster',
      role: 'Rôle',
      roleViewer: 'Observateur',
      roleEditor: 'Éditeur',
      colorLabel: 'Couleur',
      colorOptional: 'optionnel',
      pickColor: 'Choisir la couleur',
      pinLabel: 'NIP',
      pinDigits: '{n} chiffres',
      title: 'Membres',
      caption: 'Qui peut se connecter et avec quel rôle. Les membres sont désactivés, jamais supprimés (l’historique est conservé).',
      loading: 'Chargement des membres…',
      none: 'Aucun membre.',
      colName: 'Nom',
      colUsername: 'Nom d’utilisateur',
      colRole: 'Rôle',
      colStatus: 'Statut',
      colLastLogin: 'Dernière connexion',
      colActions: 'Actions',
      active: 'Actif',
      inactive: 'Inactif',
      toViewer: '→ Observateur',
      toEditor: '→ Éditeur',
      deactivate: 'Désactiver',
      reactivate: 'Réactiver',
      resetPin: 'Réinitialiser le NIP',
      guardSelf: 'Vous ne pouvez pas modifier ni désactiver votre propre compte.',
      guardLastCmd: 'Le dernier compte éditeur actif ne peut être ni désactivé ni rétrogradé.',
      guardSelfRole: 'Vous ne pouvez pas modifier votre propre rôle.',
      guardLastCmdRole: 'Le dernier compte éditeur actif ne peut pas être rétrogradé.',
      guardSelfDeactivate: 'Vous ne pouvez pas désactiver votre propre compte.',
      guardLastCmdDeactivate: 'Le dernier compte éditeur actif ne peut pas être désactivé.',
      guardLabel: 'Actions protégées pour {name}',
      newPinPrompt: 'Nouveau NIP pour {name} ({n} chiffres) :',
      pinInvalid: 'Le NIP doit comporter exactement {n} chiffres.',
    },
    roster: {
      sourceHint: 'Colonnes : name (obligatoire), rank (optionnel). UTF-8, séparé par des virgules, avec en-tête. Les identités fournisseur sont gérées par synchronisation.',
      addPerson: 'Ajouter une personne',
      addPersonCaption: 'Saisir le nom de la personne.',
      name: 'Nom',
      namePlaceholder: 'p. ex. Meier Hans',
      csvImport: 'Importer un CSV',
      csvTemplate: 'Télécharger un CSV exemple',
      importing: 'Import…',
      imported: '{n} importé(s)',
      skipped: '{n} ignoré(s)',
      syncDivera: 'Synchroniser l’effectif avec Divera',
      diveraNotConfigured: 'Divera non configuré',
      syncProvider: 'Synchroniser avec {provider}',
      providerNotConfigured: 'Aucune source de personnel configurée · CSV et saisie manuelle disponibles',
      title: 'Personnes saisies',
      caption: 'Fichier du personnel du corps. Les personnes sont désactivées, jamais supprimées (l’historique est conservé).',
      showInactive: 'Afficher les inactifs',
      loading: 'Chargement de l’effectif…',
      none: 'Aucune personne saisie.',
      colName: 'Nom',
      colSource: 'Source',
      colStatus: 'Statut',
      colActions: 'Actions',
      sourceDivera: 'Divera',
      sourceManual: 'manuel',
      active: 'Actif',
      inactive: 'Inactif',
      deactivate: 'Désactiver',
      reactivate: 'Réactiver',
    },
    data: {
      testConnection: 'Tester la connexion',
      testing: 'Test…',
      testOk: 'OK',
      testOff: 'non configuré',
      testErr: 'Erreur',
      genericError: 'Erreur',
      stateConnected: 'connecté',
      stateUnavailable: 'non disponible',
      stateNotConfigured: 'non configuré',
      poolLoading: 'Chargement du pool…',
      poolCount: '{n} alarme dans le pool',
      poolCountPlural: '{n} alarmes dans le pool',
      poolUnavailable: 'Pool non disponible',
      refresh: 'Actualiser',
      refreshing: 'Actualisation…',
      lastAlarm: 'Dernière alarme',
      alarmFallback: 'Alarme {id}',
      noneInPool: 'aucune dans le pool',
      address: 'Adresse',
      vehiclesLoading: 'Chargement des véhicules…',
      vehicleCount: '{n} véhicule',
      vehicleCountPlural: '{n} véhicules',
      onlineCount: '{n} en ligne',
      positionsUnavailable: 'Positions non disponibles',
      server: 'Serveur',
      freshestSignal: 'Signal le plus récent',
      colDevice: 'Appareil',
      colStatus: 'Statut',
      colLastSignal: 'Dernier signal',
      colSpeed: 'Vitesse',
      online: 'en ligne',
      offline: 'hors ligne',
      unknown: 'inconnu',
      noPlans: 'aucun plan',
      objectsLoading: 'Chargement des objets…',
      objectsUnavailable: 'Objets non disponibles.',
      objectsError: 'Impossible de charger les objets.',
      objectsNone: 'Aucun objet enregistré.',
      objectsHintBefore: 'Les objets et leurs plans sont importés côté serveur — via ',
      objectsHintAfter: ' depuis le dépôt de données privé. Ils apparaissent ensuite ici en consultation.',
      mapLoading: 'Chargement de la carte…',
      noLocation: 'aucun lieu',
      geodataLoading: 'Chargement des données…',
      geodataUnavailable: 'Données non disponibles.',
      geodataError: 'Impossible de charger les données.',
      geodataNone: 'Aucune donnée de référence importée.',
      geodataHintBefore: 'Hydrantes, cadastre des conduites et d’autres couches sont chargés côté serveur — via ',
      geodataHintAfter: ' depuis le dépôt de données privé. Le GeoJSON doit être en WGS84.',
      colDataset: 'Jeu de données',
      colType: 'Type',
      colVersion: 'Version',
      colUpdated: 'État',
      colFeatures: 'Features',
      colSource: 'Source',
      justNow: 'à l’instant',
      relMin: 'il y a {n} min.',
      relHour: 'il y a {n} h.',
    },
    objectsMap: {
      showAll: 'Tout afficher',
      showAllTitle: 'Afficher tous les objets',
    },
    modules: {
      empty: 'Aucun module configuré — les modules standard fournis s’appliquent.',
      summary: '{modules} modules · {objects} objets · {plans} plans',
      coverage: '{covered}/{total} objets',
      code: 'Code',
      title: 'Titre',
      order: 'Ordre',
      orientation: 'Orientation',
      orientationPortrait: 'Portrait',
      orientationLandscape: 'Paysage',
      detection: 'Règle de reconnaissance',
      detectionNone: 'aucune règle',
      combinedWith: 'Combiné avec',
      familyBadge: 'Famille',
      familyHint: 'génère des sous-modules à partir du nom de fichier',
      viewerBadge: 'Lecture seule',
      viewerHint: 'PDF sans dessin',
      objectsTitle: 'Objets & plans',
    },
    layers: {
      filterPlaceholder: 'Rechercher une couche …',
      loading: 'Chargement …',
      empty: 'Aucune couche de référence configurée.',
      noMatches: 'Aucune couche ne correspond à la recherche.',
      summary: '{total} couches · {loaded} chargées · {missing} manquantes · {external} externes',
      statusLoaded: 'Chargée',
      statusMissing: 'Non chargée',
      statusExternal: 'Source externe',
      features: '{n} entités',
      updated: 'Mis à jour {date}',
      group: 'Groupe',
      opacity: 'Opacité',
      colorDay: 'Couleur jour',
      colorNight: 'Couleur nuit',
      symbol: 'Symbole',
      geometry: 'Géométrie',
      geometryPoint: 'Points',
      geometryLine: 'Lignes',
      maxZoom: 'Zoom max',
      attribution: 'Source',
      source: 'Source',
      datasetsTitle: 'Jeux de données chargés',
    },
    branding: {
      logo: 'Logo',
      logoHint: 'Écran de connexion',
      favicon: 'Favicon',
      faviconHint: 'Onglet du navigateur',
      upload: 'Choisir une image',
      uploading: 'Téléversement…',
      remove: 'Supprimer',
      removeConfirm: 'Supprimer cette image ?',
      uploadFailed: 'Échec du téléversement',
      removeFailed: 'Échec de la suppression',
      iconsNote: 'Les icônes d’app / d’écran d’accueil sont définies au build (séparément).',
    },
    system: {
      loading: 'Chargement des données système…',
      refresh: 'Actualiser',
      liveSnapshot: 'État système en direct',
      updatedAt: 'Mis à jour à {time}',
      healthSummary: 'État du système',
      server: 'Serveur',
      reachable: 'accessible',
      error: 'Impossible de charger les données système.',
      notAvailable: 'non disponible',
      version: 'Version',
      versionTip: 'État de build de cette installation. « Commit » = l’état Git du serveur, « Environnement » = mode production ou développement.',
      commit: 'Commit',
      branch: 'Branche',
      environment: 'Environnement',
      production: 'Production',
      development: 'Développement',
      database: 'Base de données',
      databaseTip: 'Signe de vie de la base de données : une simple requête de test. « OK » = le serveur atteint la base de données.',
      ok: 'OK',
      error2: 'Erreur',
      inventory: 'Inventaire',
      inventoryTip: 'Enregistrements dans la base de données de cette installation.',
      incidentsTotal: 'Interventions (total)',
      incidentsOpen: 'Interventions (ouvertes)',
      personnelActive: 'Effectif (actif)',
      users: 'Utilisateurs',
      referenceData: 'Données de référence',
      domain: 'Domaine',
      status: 'Statut',
      active: 'actif',
      personnelProvider: 'Source du personnel',
      alarmProvider: 'Source des alarmes',
      vehicleProvider: 'Source de suivi',
      configured: 'configuré',
      notConfigured: 'non configuré',
      connectors: 'Connexions',
      connectorsTip: 'Tout ce à quoi cette installation est reliée — fournisseurs (Divera/Traccar) et tous les consommateurs/producteurs — lecture seule. Configuration via variables d’environnement ou l’espace admin (saisie, statistiques).',
      connection: 'Connexion',
      directionIn: 'entrant',
      directionOut: 'sortant',
      connOnline: 'en ligne',
      connOffline: 'hors ligne',
      connLastSeen: 'Dernier signal : {time}',
      connPrintRelay: 'Imprimante de caserne (agent d’impression)',
      connCapture: 'Affiche de saisie (QR)',
      connStats: 'Export statistiques',
      connDiveraWebhook: 'Webhook Divera',
      connAlarmWebhook: 'Entrée d’alarme générique',
      connPush: 'Web push (alerte)',
      connStt: 'Reconnaissance vocale',
      storage: 'Stockage',
      storageTip: 'Le stockage d’objets du serveur (photos, plans, fichiers de référence) et l’occupation du disque sous-jacent.',
      mediaUsed: 'Occupé (médias)',
      files: 'Fichiers',
      directory: 'Répertoire',
      diskUsed: 'Disque occupé',
      diskUnavailable: 'Occupation du disque non disponible.',
      free: 'Libre : {size}',
      offlineCache: 'Cache hors ligne (cet appareil)',
      offlineCacheTip: 'Le cache hors ligne (service worker) de cet appareil : cartes, plans et fichiers d’app stockés pour l’intervention sans réseau. Les chiffres ne valent que pour CET appareil, pas pour le serveur.',
      cacheReading: 'Lecture du cache…',
      cacheUnavailable: 'Non disponible dans ce navigateur.',
      usedQuota: 'Occupé / quota',
      storageEstimateUnavailable: 'Estimation du stockage non disponible.',
      cacheStorage: 'Stockage cache',
      cacheSummary: '{caches} · {entries} entrées',
      cache: 'Cache',
      entries: 'Entrées',
      clearCaches: 'Vider les caches',
      clearing: 'Vidage…',
      cleared: 'vidé',
      clearConfirm: 'Vider le cache hors ligne sur CET appareil ?\n\nLes cartes, plans et fichiers d’app stockés seront supprimés. Au prochain chargement, ils seront récupérés à nouveau depuis le serveur (Internet requis). La connexion et les données du serveur restent intactes.',
      offlineCacheCaption: 'Maintenance locale : vide uniquement le cache hors ligne sur CET appareil. Au prochain chargement, les fichiers sont récupérés à nouveau. La connexion et le serveur restent intacts.',
    },
  },
}
