// Italian (it) — a full translation overlay deep-merged over German (./de).
//
// Swiss-Italian (Ticino) for the pompieri ticinesi. Fire-service domain terms follow Ticino
// conventions: Lage → «Situazione», Atemschutz → «autoprotezione» / ARA (autorespiratore),
// Trupp → «squadra», Einsatz → «intervento», Verlauf → «diario», Einsatzleiter → «capo
// intervento». Acronyms kept natural (ARA, PC, ADR).
//
// Two groups are deliberately NOT translated and fall back to German on purpose:
//   • intake.kategorien / intake.kategorieGuess — these mirror the backend's VKF
//     Schadenkategorien (app/divera.py TYPE_LABELS) and match against German Divera keyword
//     text; translating them would desync category derivation.
//   • contextPanel.unField / contextPanel.stoffField — the UN→substance lookup matches against
//     the language-independent preset fields; translating them would break the autofill.
// Everything omitted here renders the German base string (deepMerge fallback).

import type { Copy, Localizable } from './index'

export const it: Localizable<Copy> = {
  loadingSubtitle: 'Caricamento mappa e libreria simboli …',
  modes: { map: 'Situazione', plans: 'Piano', checklists: 'Checklist', atemschutz: 'Autoprotezione', anwesenheit: 'Presenza' },
  navRail: { map: 'Mappa', plansGroup: 'Piani', objectSwitch: 'Scegli oggetto', assign: 'Assegna piano', expand: 'Espandi', collapse: 'Comprimi', resize: 'Adatta barra' },
  panels: { layers: 'Livelli', history: 'Diario' },
  layerPanel: {
    stateVisible: 'visibile, nascondi',
    stateHidden: 'nascosto, mostra',
  },
  help: {
    menu: 'Funzioni e aiuto',
    title: 'Cosa può fare KP Front?',
    subtitle: 'Tutte le funzioni a colpo d’occhio — pensato per essere usato alle 3 di notte senza pratica.',
    contents: 'Indice',
    close: 'Chiudi',
    introFallback: 'KP Front è la conduzione digitale della situazione e dell’intervento dei tuoi pompieri: carta della situazione tattica, piani degli oggetti, sorveglianza dell’autoprotezione e un diario condiviso — tutto in tempo reale su più dispositivi contemporaneamente.',
    sections: [
      {
        id: 'ueberblick', title: 'Panoramica', icon: 'info',
        blocks: [
          { kind: 'intro' },
          { kind: 'sub', text: 'Le quattro aree di lavoro (barra sinistra)' },
          { kind: 'list', items: [
            '**Situazione** — la carta tattica con simboli, linee, superfici e i livelli delle condotte.',
            '**Piano** — i piani degli oggetti (Moduli 1–6, sagome degli edifici) come lavagna, piano per piano.',
            '**Checklist** — checklist d’intervento eseguibili.',
            '**Autoprotezione** — sorveglianza delle squadre impiegate con tempo e pressione.',
          ] },
          { kind: 'note', text: 'Principio guida: utilizzabile alle 3 di notte, dopo sei mesi senza pratica. Riconoscere invece di ricordare, usabile con i guanti e offline.' },
        ],
      },
      {
        id: 'navigation', title: 'Navigazione e interfaccia', icon: 'cursor',
        blocks: [
          { kind: 'lead', text: 'Tre zone fisse: la barra delle aree a sinistra, la barra dell’intervento in alto, la barra degli strumenti a destra.' },
          { kind: 'sub', text: 'Barra sinistra' },
          { kind: 'list', items: [
            'Cambia area di lavoro: **Mappa** (Situazione), i **Piani** (Moduli/edifici), **Checklist**, **Autoprotezione**.',
            'In basso **Scegli oggetto** cambia l’edificio/oggetto dei piani.',
            'In modalità Situazione, **Livelli** e il selettore della **Mappa** sono fissati in basso — sempre visibili.',
            'Trascinando il bordo destro della barra la si espande con le etichette o la si richiude.',
          ] },
          { kind: 'sub', text: 'Barra dell’intervento in alto' },
          { kind: 'list', items: [
            'A sinistra il nome dell’intervento con il **Menu** (cambia intervento, giorno/notte, questo aiuto …) e l’orologio.',
            'A destra **Annulla/Ripeti**, **Diario** e **+ Voce**.',
          ] },
          { kind: 'sub', text: 'Barra degli strumenti a destra' },
          { kind: 'list', items: [
            'Gli strumenti di disegno e posizionamento; in basso, fissata, la navigazione della carta (zoom, adatta, coordinate).',
          ] },
        ],
      },
      {
        id: 'lage', title: 'Situazione — carta', icon: 'map',
        blocks: [
          { kind: 'lead', text: 'La carta tattica sopra lo sfondo cartografico reale (area d’intervento e dintorni).' },
          { kind: 'list', items: [
            '**Mappa di base** (in alto nel pannello livelli) cambia lo sfondo: Carto, OpenStreetMap o satellite.',
            '**Ingrandisci/Riduci**, **Adatta** e **Rileva coordinate** in basso nella barra destra. Durante il rilevamento, tocca la carta per fissare un punto (LV95 + WGS84); la bussola si riorienta a nord.',
            '**Vento** mostrato in continuo (direzione + temperatura), così la direzione di propagazione è subito chiara.',
            '**Veicoli/mezzi** appaiono in tempo reale via GPS (nome + orientamento), la propria posizione come punto blu fisso.',
          ] },
        ],
      },
      {
        id: 'ebenen', title: 'Livelli e dati', icon: 'layers',
        blocks: [
          { kind: 'lead', text: 'Tramite **Livelli** mostri i dati delle condotte e dei pericoli — ordinati per tipo.' },
          { kind: 'list', items: [
            '**Situazione** — simboli tattici, veicoli, schizzi e note.',
            '**Acqua** — idranti, condotte, saracinesche, sorgenti.',
            '**Acque reflue** — acque nere/miste, acque chiare/meteoriche, pozzetti / caditoie.',
            '**Gas** — condotte.',
            '**Elettricità** — linee, impianti FV.',
            '**Pericoli** — piene, profondità di allagamento.',
          ] },
          { kind: 'lead', text: 'Ogni livello può essere mostrato/nascosto e regolato nell’opacità.' },
          { kind: 'list', items: [
            '**Scarica la carta per l’offline** (nell’area Livelli) precarica i tasselli della carta, i piani, i simboli e i geodati per il luogo d’intervento.',
          ] },
          { kind: 'note', text: 'I dati delle condotte coprono l’area d’intervento configurata e sono disponibili localmente — funzionano anche offline.' },
        ],
      },
      {
        id: 'zeichnen', title: 'Disegno e simboli', icon: 'pen',
        blocks: [
          { kind: 'lead', text: 'Strumenti della barra destra in modalità Situazione.' },
          { kind: 'list', items: [
            '**Simbolo** — il segno tattico (FKS/VKF). Selezione rapida dei segni più comuni o ricerca in tutta la libreria. Tocca per posizionare; con il lucchetto ne metti più di seguito.',
            '**Selezione** — tocca gli oggetti, spostali, modificali nell’editor.',
            '**Multiplo** — lazo: seleziona più simboli/disegni in una volta.',
            '**Linea** — trascina o tocca i punti; lo stile si sceglie poi nell’editor: **Mano libera**, **Freccia** o **Asse di salvataggio**.',
            '**Superficie** — tocca i vertici (area indicata da 3 punti in poi); trascina/inserisci/elimina i vertici.',
            '**Perimetro di sicurezza** — trascina dal centro al bordo per impostare il raggio in metri (riempimento regolabile).',
            '**Nota** — testo libero direttamente sulla carta.',
            '**Misura** — distanza (distanza + profilo altimetrico) o superficie (area + perimetro). Trascina i punti per spostarli, tocca la linea per inserire punti intermedi, clic destro per rimuovere un punto.',
          ] },
          { kind: 'sub', text: 'Preimpostazioni dei simboli' },
          { kind: 'lead', text: 'Ogni simbolo porta solo i comandi sensati: **Rotazione** per i segni orientati (frecce, scale, pareti), **Quantità** dove più elementi contano, **Piano** o un **intervallo di piani** (es. scala/ascensore), **Propagazione** per le situazioni di danno — più i campi di immissione adatti (es. nome, sostanza, stato).' },
        ],
      },
      {
        id: 'plan', title: 'Piano — moduli ed edifici', icon: 'doc',
        blocks: [
          { kind: 'lead', text: 'Una lavagna per oggetto sopra i piani dei moduli/edifici. Piano per piano, con strumenti propri.' },
          { kind: 'list', items: [
            '**Simbolo**, **Selezione**, **Disegna** (colore/spessore/tipo di linea), **Nota** (testo), **Squadra**.',
            '**Piani** come pila: con i pulsanti **PS/PI** sul piano aggiungi un livello sopra/sotto.',
            '**Zoom/Adatta** in basso nella barra degli strumenti, come sulla carta.',
            '**Squadre** (squadre) come marcatori colorati; mostrare/nascondere le **Tracce** ne rivela il percorso. I tag delle squadre la cui squadra è «uscita» vengono attenuati/barrati.',
          ] },
        ],
      },
      {
        id: 'atemschutz', title: 'Sorveglianza autoprotezione', icon: 'gauge',
        blocks: [
          { kind: 'lead', text: 'Sorveglianza senza lacune di ogni squadra ARA secondo FKS — il segnale di sicurezza è il **tempo dall’ultimo contatto radio**, non un tempo residuo stimato.' },
          { kind: 'sub', text: 'Creare una squadra' },
          { kind: 'list', items: [
            '**Compito** prima: scegli il tipo (Salvare · Spegnere · Perlustrare · Mettere in sicurezza · Ricognizione · Altro), l’**obiettivo / luogo** in chiaro (es. «2° piano, appartamento a sinistra») e, facoltativo, il n. della linea/tubo.',
            '**Squadra e pressione**: registra il capogruppo e il milito (i nomi già impiegati come selezione rapida) e imposta la pressione d’ingresso (bar).',
          ] },
          { kind: 'sub', text: 'Sorveglianza per squadra' },
          { kind: 'list', items: [
            'In grande l’orologio **Dall’ultimo contatto**: verde **Contatto ok** → giallo **Contatto in scadenza** → rosso **In ritardo** (nessun contatto entro ~5 min) con allarme.',
            '**Contatto** (pulsante grande) conferma il contatto radio e azzera l’orologio.',
            '**Pressione** regolala direttamente con ± e applicala con **Conferma** — vale come contatto e viene registrata; un clic errato senza conferma non cambia nulla. La pressione bassa diventa rossa.',
            'Stato **Annunciata → In intervento → Ritiro → Fuori**. Il **Ritiro** si può revocare con **Continua**; una squadra fuori rientra in sorveglianza con **Rientrare** (nuova bombola).',
            '**Diario** per squadra (espandibile) mostra ogni contatto con ora e pressione.',
            '**Modifica** (matita) adatta compito, obiettivo/piano o squadra durante l’intervento.',
            'Le squadre in ritardo salgono in alto, in cima appare un contatore; il **suono d’allarme** si può silenziare per dispositivo (campanella). Tutto finisce nel diario.',
            'Ogni squadra si può posizionare sul piano (pulsante «mostra sul piano»).',
          ] },
        ],
      },
      {
        id: 'checkliste', title: 'Checklist', icon: 'check',
        blocks: [
          { kind: 'lead', text: 'Due colonne: compiti eseguibili e un prontuario tattico ricercabile.' },
          { kind: 'list', items: [
            '**Compiti** — checklist d’intervento (es. supporto alla conduzione, rapporto di situazione) con indicatore di avanzamento; spunta le voci, le diramazioni seguono procedure a più livelli.',
            '**Tattica · parole chiave** — cerca una parola chiave e apri la voce corrispondente (con codice colore dei pericoli e schizzi).',
            'Quando si rileva un allarme Divera, una parola chiave adatta viene proposta automaticamente.',
          ] },
          { kind: 'lead', text: 'Lo stato viene conservato e sincronizzato su tutti i dispositivi.' },
        ],
      },
      {
        id: 'verlauf', title: 'Diario e voce', icon: 'history',
        blocks: [
          { kind: 'lead', text: 'Un diario condiviso e continuo tra Situazione e Piano — la cronaca dell’intervento.' },
          { kind: 'list', items: [
            '**+ Voce** (in alto a destra): un tocco breve apre l’immissione testo; **tieni premuto** per registrare una **nota vocale**. Si possono allegare anche foto.',
            'Le azioni rilevanti (simbolo posizionato, disegno creato/rimosso …) finiscono automaticamente nel diario.',
            '**Annulla/Ripeti** vale per Situazione e Piano.',
            'Una voce del diario con un luogo, se toccata, riporta al punto sulla carta o sul piano; foto e note vocali si aprono/riproducono direttamente nel diario.',
            '**Avvia riproduzione** riproduce Situazione e Piano a un momento precedente (cursore temporale; durante la riproduzione la modifica è bloccata).',
          ] },
        ],
      },
      {
        id: 'einsatz', title: 'Gestire gli interventi', icon: 'swap',
        blocks: [
          { kind: 'lead', text: 'Tutto nel menu dell’intervento (nome in alto a sinistra).' },
          { kind: 'list', items: [
            '**Cambia intervento** tra gli interventi aperti; **Nuovo intervento** (luogo selezionabile sulla carta).',
            '**Pool Divera** — rileva gli allarmi in arrivo.',
            '**Interventi** — apri l’archivio / interventi precedenti.',
            '**Archivia l’attuale** chiude l’intervento in corso.',
          ] },
        ],
      },
      {
        id: 'sync', title: 'Multi-dispositivo e offline', icon: 'check',
        blocks: [
          { kind: 'lead', text: 'Tutti i dispositivi vedono lo stesso intervento in tempo reale.' },
          { kind: 'list', items: [
            'Le modifiche vengono condivise automaticamente; il distintivo di sincronizzazione in alto mostra lo stato (salvato/in attesa).',
            'La modifica simultanea viene unita per oggetto (vince la modifica più recente).',
            '**Sola lettura**: osservatori e telefoni vedono la situazione in tempo reale, senza gli strumenti tattici.',
          ] },
        ],
      },
      {
        id: 'bedienung', title: 'Uso e giorno/notte', icon: 'move',
        blocks: [
          { kind: 'sub', text: 'Tocca e trascina (touch/iPad)' },
          { kind: 'list', items: [
            'Un dito sposta la carta/il piano; due dita zoomano (pinch).',
            'Trascinando un lazo con **Multiplo** selezioni più oggetti; gli oggetti selezionati si spostano trascinando.',
          ] },
          { kind: 'sub', text: 'Mouse' },
          { kind: 'list', items: [
            'Lo scorrimento zooma; il **clic destro** (o tocco prolungato) su un punto di misura/linea lo rimuove, un clic su una linea inserisce un punto intermedio.',
          ] },
          { kind: 'sub', text: 'Tasti' },
          { kind: 'list', items: [
            '[[Esc]] annulla lo strumento attivo o deseleziona.',
            '[[Canc]] / [[Backspace]] elimina la selezione (non mentre si scrive in un campo).',
          ] },
          { kind: 'sub', text: 'Giorno / notte' },
          { kind: 'list', items: [
            'Commutabile nel menu dell’intervento — la modalità notte attenua carta e interfaccia per il buio.',
          ] },
        ],
      },
    ],
  },
  baseMap: 'Mappa',
  floor: { eg: 'PT', og: '{n}° PS', ug: '{n}° PI' },
  hoseHint: '~{n} tubi',
  noHistoryRows: 'Nessun evento registrato',
  symbolSearchPlaceholder: 'Cerca simbolo tattico …',
  noSymbolMatches: 'Nessun risultato',
  close: 'Chiudi',
  closeDialog: 'Chiudi',
  edit: 'Modifica',
  primarySymbol: { label: 'Simbolo' },
  done: 'Fatto',
  cancel: 'Annulla',
  keepPlacing: 'Posiziona più',
  delete: 'Rimuovi',
  undo: 'Annulla',
  redo: 'Ripeti',
  play: 'Riproduci',
  clear: 'Svuota',
  mapTools: [
    { id: 'select', icon: 'select', label: 'Selezione', kind: 'tool' },
    { id: 'lasso', icon: 'marquee', label: 'Multiplo', kind: 'tool' },
    { id: 'sep-symbol', sep: true, icon: '', label: '' },
    { id: 'symbol-slot', slot: true, icon: '', label: '' },
    { id: 'line', icon: 'pen', label: 'Linea', kind: 'tool' },
    { id: 'area', icon: 'area', label: 'Superficie', kind: 'tool' },
    { id: 'circle', icon: 'circle', label: 'Perimetro di sicurezza', kind: 'tool' },
    { id: 'sep-anno', sep: true, icon: '', label: '' },
    { id: 'note', icon: 'type', label: 'Nota', kind: 'tool' },
    { id: 'team', icon: 'flag', label: 'Squadra', kind: 'tool' },
    { id: 'measure', icon: 'measure', label: 'Misura', kind: 'tool' },
  ],
  planTools: [
    { id: 'pan', icon: 'select', label: 'Selezione' },
    { id: 'lasso', icon: 'marquee', label: 'Multiplo' },
    { id: 'sep-symbol', sep: true, icon: '', label: '' },
    { id: 'symbol-slot', slot: true, icon: '', label: '' },
    { id: 'line', icon: 'pen', label: 'Linea' },
    { id: 'area', icon: 'area', label: 'Superficie' },
    { id: 'text', icon: 'type', label: 'Nota' },
    { id: 'resource', icon: 'flag', label: 'Squadra' },
    { id: 'sep-measure', sep: true, icon: '', label: '' },
    { id: 'measure', icon: 'measure', label: 'Misura' },
  ],
  nav: {
    zoomIn: 'Ingrandisci',
    zoomOut: 'Riduci',
    fit: 'Adatta',
    resetNorth: 'Orienta a nord',
    centerIncident: 'Centra sull’intervento',
    coords: 'Rileva coordinate',
    coordsHint: 'Tocca la carta per fissare',
    coordsLocked: 'Fissato — pulsante per un nuovo punto',
    themeLabel: 'Visualizzazione',
    autoMode: 'Automatico',
    dayMode: 'Giorno',
    nightMode: 'Notte',
  },
  toast: {
    recordingStarted: 'Registrazione audio in corso …',
    audioSaved: 'Nota audio salvata ({secs}s)',
    micDenied: 'Nessun accesso al microfono – annotato come segnaposto',
    merged: 'Modifiche unite',
  },
  mapHints: {
    placeSymbol: 'Tocca la carta per posizionare «{name}»',
    areaDraft: 'Tocca i vertici della superficie sulla carta',
    placeNote: 'Tocca la carta per inserire una nota',
    placeShape: 'Tocca la carta per posizionare {name}',
  },
  dockHints: {
    symbol: 'Tocca la carta per posizionare il segno. Attiva il lucchetto per metterne più di seguito.',
    lasso: 'Trascina con un dito un riquadro attorno a più oggetti. Con due dita la carta continua a spostarsi.',
    line: 'Trascina sulla carta o tocca i punti per disegnare una linea. Lo stile (Mano libera · Freccia · Asse di salvataggio) si sceglie poi nell’editor.',
    area: 'Tocca almeno tre vertici sulla carta, poi concludi con il segno di spunta.',
    circle: 'Trascina dal centro verso il bordo per impostare il raggio in metri. Raggio e riempimento si regolano poi nell’editor.',
    note: 'Tocca la carta per inserire una nota.',
    shape: 'Tocca la carta per posizionare la forma. Attiva il lucchetto per metterne più di seguito.',
    measure: 'Tocca i punti sulla carta. La distanza mostra lunghezza e profilo altimetrico, la superficie mostra area e perimetro. Trascina i punti per spostarli, tocca una linea per un punto intermedio, clic destro su un punto per rimuoverlo.',
  },
  map: {
    incidentHere: 'Luogo d’intervento',
    youHere: 'La mia posizione',
  },
  intake: {
    titleNew: 'Apri intervento',
    titleDivera: 'Rileva allarme',
    diveraHint: 'Importato dalla fonte di allarme — verifica e correggi se necessario.',
    locationHead: 'Posizione',
    addressLabel: 'Indirizzo',
    addressPlaceholder: 'Via n., NPA località',
    addressSearching: 'Ricerca …',
    addressNoHits: 'Nessun indirizzo trovato',
    objectButton: 'Oggetto dai piani d’intervento',
    objectSearchPlaceholder: 'Cerca oggetto o indirizzo …',
    objectNear: 'Nelle vicinanze',
    objectNoHits: 'Nessun oggetto trovato',
    objectPlans: (n: number) => (n === 1 ? '1 piano' : `${n} piani`),
    objectNoPlans: 'nessun piano',
    mapPickButton: 'Imposta sulla carta',
    coordSet: 'Coordinata impostata',
    coordNone: 'Nessuna posizione — verrà aperto senza coordinata',
    coordClear: 'Rimuovi posizione',
    keywordHead: 'Parola chiave e categoria',
    titleLabel: 'Parola chiave / titolo',
    titlePlaceholder: 'es. Incendio edificio scuola',
    categoryLabel: 'Categoria',
    detailsLabel: 'Testo della segnalazione (facoltativo)',
    detailsPlaceholder: 'Indicazioni aggiuntive sulla segnalazione',
    open: 'Apri intervento',
    opening: 'Apertura …',
    cancel: 'Annulla',
    errorCreate: 'Errore durante la creazione',
    errorTake: 'Rilevamento fallito',
    errorUpdate: 'Aggiornamento fallito',
    editTitle: 'Modifica dati intervento',
    back: '← Indietro',
    save: 'Salva',
    saving: 'Salvataggio …',
    created: 'Intervento creato',
    taken: 'Allarme rilevato',
    updated: 'Intervento aggiornato',
    alarmierungHead: 'Allarme',
    alarmTime: 'Ora dell’allarme',
    alarmMessage: 'Messaggio d’allarme',
    addressUnknown: 'Indirizzo sconosciuto',
    alarmOpen: 'Apri',
    alarmOpening: 'Apertura …',
    dismiss: 'Scarta',
    manualIncident: 'Intervento manuale',
    attach: 'Aggiungi a un intervento esistente',
    attachShort: 'A intervento',
    attachConfirmTitle: 'Aggiungere «{alarm}» a questo intervento?',
    attachHint: 'Il messaggio d\u2019allarme finisce nel giornale, i tempi GPS seguono automaticamente. Parola chiave e luogo dell\u2019intervento restano invariati.',
    attachConfirm: 'Aggiungi',
    attachDone: 'Allarme aggiunto all\u2019intervento',
    attachError: 'Aggiunta non riuscita',
    newDiveraAlarm: 'Nuovo allarme',
    hide: 'Nascondi',
    fromDivera: 'Rilevato dalla fonte di allarme',
    locationSet: 'Posizione impostata',
    noLocationOnMap: 'Nessuna posizione — imposta sulla carta',
    ok: 'Va bene',
    // Etichette di VISUALIZZAZIONE per l'elenco categorie — il valore inviato resta in tedesco.
    kategorienLabels: {
      'Brandbekämpfung': 'Lotta antincendio',
      'Strassenrettung': 'Soccorso stradale',
      'Technische Hilfeleistung': 'Aiuto tecnico',
      'Elementarereignis': 'Eventi naturali',
      'Ölwehr': 'Intervento antinquinamento (idrocarburi)',
      'Chemiewehr': 'Intervento chimico',
      'Strahlenwehr': 'Intervento radiologico',
      'Einsatz Bahnanlagen': 'Intervento ferroviario',
      'BMA / unechte Alarme': 'RAI / falsi allarmi',
      'Gerettete Tiere': 'Salvataggio animali',
      'Dienstleistungen': 'Prestazioni di servizio',
      'Diverse Einsätze': 'Interventi diversi',
    },
  },
  // Etichette di VISUALIZZAZIONE dei simboli tattici, indicizzate per nome FireGIS grezzo.
  // L'identità memorizzata resta il nome grezzo; solo l'etichetta viene tradotta.
  symbolNames: {
    'VKF Feuer': 'Incendio',
    'VKF Rettungen': 'Salvataggio',
    'VKF Unfall': 'Incidente',
    'VKF Gefaehrliche Stoffe': 'Sostanze pericolose',
    'VKF Wasser': 'Acqua',
    'FW Gefahr allgemein': 'Pericolo',
    'FW Gefahr Tafel': 'Targa di pericolo',
    'FW Gefahr Radioaktiv': 'Radioattivo',
    'FW Gefahr Ex': 'Esplosione',
    'FW Gefahr G': 'Gas',
    'FW Gefahr C': 'Chimico',
    'FW Gefahr W': 'Acqua',
    'FW Elektroanlage': 'Impianto elettrico',
    'VKF Patientensammelstelle': 'Punto di raccolta feriti',
    'VKF Sanitaetshilfsstelle': 'Posto di soccorso sanitario',
    'VKF Totensammelstelle': 'Punto di raccolta deceduti',
    'VKF Sammelstelle': 'Illesi',
    'FW Sammelplatz': 'Punto di raccolta',
    'FW Warteraum': 'Area di attesa',
    'FW Verwundetennest': 'Nido feriti',
    'VKF Bereich Sanitaet': 'Sanitario',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Capo intervento',
    'FW Offizier': 'Ufficiale',
    'VKF Kontrollposten': 'Posto di controllo',
    'VKF Informationszentrum': 'Centro informazioni',
    'VKF Bereich Materialdepot': 'Deposito materiale',
    'FW Absperrung': 'Sbarramento',
    'VKF Verkehrssperre ueberwacht': 'Blocco stradale',
    'VKF Drehleiter': 'Autoscala',
    'VKF Hubretter': 'Autopiattaforma',
    'VKF Fahrzeug': 'Veicolo',
    'VKF Pumpe Typ2': 'Pompa',
    'VKF Helilandeplatz': 'Area atterraggio elicottero',
    'VKF Luefter mobil': 'Ventilatore',
    'FW Entrauchung': 'Evacuazione fumi',
    'FW Kleinloeschgeraet': 'Piccolo estintore',
    'FW Sprungretter': 'Cuscino di salvataggio',
    'FW Leiter': 'Scala',
    'SI Ueberflurhydrant': 'Idrante soprasuolo',
    'SI Unterflurhydrant': 'Idrante sottosuolo',
    'VKF Innenhydrant': 'Idrante interno',
    'SI Wasserloeschposten': 'Posto di estinzione',
    'WV Loeschweier': 'Vasca antincendio',
    'SI Wasserbezugsort': 'Punto di prelievo acqua',
    'SI Wasserdruckversorgung': 'Alimentazione idrica in pressione',
    'GB Lift': 'Ascensore',
    'GB Kamin': 'Camino',
    'GB Abzug': 'Sfiato',
    'SI Schieber': 'Saracinesca',
    'GB Elektrotableau': 'Quadro elettrico',
    'GB Sprinklerzentrale': 'Centrale sprinkler',
    'GB Brandmeldezentrale': 'Centrale rilevazione incendi',
    'GB BMA Melder': 'Rivelatore d’incendio',
    'GB Fernsignaltableau': 'Quadro segnalazione a distanza',
    'GB Schluesseldepot': 'Deposito chiavi',
    'GB BA Wand F30': 'Parete F30',
    'GB BA Wand F60': 'Parete F60',
    'GB BA Wand F180': 'Parete F180',
    'GB Ture BS R30': 'Porta R30',
    'GB Ture Durchgang': 'Passaggio',
    'GB Treppe 8': 'Scala',
    'SI Nordpfeil': 'Freccia nord',
    'SI Windrichtung': 'Direzione del vento',
    'VKF Bereich Polizei': 'Polizia',
    'VKF Bereich Chemiewehr': 'Intervento chimico',
    'VKF Bereich Zivilschutz': 'Protezione civile',
    'VKF Bereich Feuerwehr': 'Pompieri',
  },
  // Intestazioni di categoria della palette, indicizzate per chiave di categoria tedesca.
  symbolCategories: {
    'Schadenlage': 'Situazione danni',
    'Gefahren': 'Pericoli',
    'Gebäude': 'Edificio',
    'Wasser': 'Acqua',
    'Führung': 'Comando',
    'Personen / Sanität': 'Persone / Sanitario',
    'Partner': 'Partner',
  },
  measure: {
    modeLine: 'Distanza',
    modeArea: 'Superficie',
    clear: 'Reimposta',
    deleteNode: 'Clic destro per rimuovere',
    distance: 'Distanza',
    perimeter: 'Perimetro',
    area: 'Superficie',
    hoses: 'Tubi',
    profile: 'Profilo altimetrico',
    ascent: 'Salita',
    descent: 'Discesa',
    min: 'Più basso',
    max: 'Più alto',
    profileLoading: 'Caricamento profilo altimetrico …',
    profileNone: 'Nessun profilo altimetrico disponibile',
    hintLine: 'Almeno 2 punti per la distanza',
    hintArea: 'Almeno 3 punti per l’area',
  },
  shapes: {
    sectionTitle: 'Forme',
    kindLabel: 'Forma',
    color: 'Colore',
    rotateHint: 'Trascina la maniglia per ruotare',
    resizeHint: 'Trascina l’angolo per ridimensionare',
    names: { arrow: 'Freccia', cloud: 'Fumo', square: 'Rettangolo' },
  },
  log: {
    noMicrophone: 'Nota audio (nessun accesso al microfono)',
    audioNote: 'Nota audio',
    symbolPlaced: 'Simbolo «{name}» posizionato',
    shapePlaced: '{name} posizionato',
    notePlaced: 'Nota posizionata',
    areaDrawn: 'Superficie disegnata',
    circleDrawn: 'Perimetro di sicurezza disegnato',
    drawingCreated: 'Disegno creato',
    objectMoved: '{name} spostato',
    objectDeleted: '{name} rimosso',
    drawingDeleted: 'Disegno rimosso',
    undo: 'Azione annullata',
    redo: 'Azione ripetuta',
    journalNote: 'Nota',
  },
  journal: {
    open: 'Diario',
    add: 'Voce',
    addHint: 'Tocca per una voce · tieni premuto per un messaggio vocale',
    title: 'Diario',
    empty: 'Nessun evento registrato',
    surfaceMap: 'Situazione',
    surfacePlan: 'Piano',
    replay: 'Avvia riproduzione',
    replayHint: 'Riproduci situazione e piano a un momento precedente',
    composerTitle: 'Voce di diario',
    textPlaceholder: 'Cosa è successo? Segnalazione, osservazione, decisione …',
    record: 'Registra',
    recordStop: 'Ferma registrazione',
    dictate: 'Detta',
    dictateStop: 'Ferma dettatura',
    dictateListening: 'In ascolto …',
    discardAudio: 'Scarta registrazione',
    audioUpload: 'Carica audio',
    audioImportLabel: 'Registrazione audio esterna',
    audioStartLabel: 'Inizio registrazione',
    audioStartHint: 'Verificare l’ora di inizio con il memo vocale.',
    audioStartConfirm: 'Confermare l’ora di inizio',
    audioImportedNote: 'Registrazione audio esterna ({duration})',
    audioDiscardImport: 'Rimuovi file audio',
    audioUploading: 'Caricamento …',
    audioOffline: 'Il caricamento audio richiede una connessione. Riselezionare il file più tardi.',
    audioTooLarge: 'File audio troppo grande. Massimo: {max} MB.',
    audioUnsupported: 'Questo formato audio non è supportato.',
    audioUploadFailed: 'Caricamento non riuscito. Verificare la connessione e riprovare.',
    playerOpen: 'Riascolta',
    editEntry: 'Modifica testo',
    removeEntry: 'Rimuovi voce',
    entryRemoved: 'Voce rimossa',
    playerEntryHere: 'Voce in questo punto',
    playerEntryPlaceholder: 'Cosa si è sentito? Messaggio, decisione …',
    playerEntries: 'Voci in questa registrazione',
    playerNoEntries: 'Ancora nessuna voce in questa finestra.',
    playerSkipBack: '15 secondi indietro',
    playerSkipFwd: '15 secondi avanti',
    playerSpeed: 'Velocità di riproduzione',
    playerSeek: 'Posizione di riproduzione',
    playerOffline: 'La riproduzione richiede una connessione.',
    sttTranscribe: 'Trascrivi',
    sttRunning: 'Trascrizione in corso … Può richiedere alcuni minuti.',
    sttFailed: 'Trascrizione non riuscita: {error}',
    sttRetry: 'Riprova',
    sttErrorGeneric: 'server non raggiungibile',
    sttBanner: '{n} bozze rilevate — verificare e acquisire.',
    sttTakeAll: 'Acquisisci tutte',
    sttTake: 'Acquisisci',
    sttDismiss: 'Scarta',
    sttEmpty: 'Nessun parlato rilevato.',
    sttTaken: 'Voce aggiunta',
    photo: 'Foto',
    photoNote: 'Foto',
    discardPhoto: 'Scarta foto',
    pinMap: 'Fissa al centro attuale della carta',
    pinPlan: 'Fissa al centro attuale del piano',
    send: 'Registra',
    saved: 'Voce di diario registrata',
    transcriptPlaceholder: 'Aggiungi trascrizione',
    transcriptSave: 'Salva',
    transcriptEdit: 'Modifica trascrizione',
    transcriptAdd: 'Aggiungi trascrizione',
    nachtrag: 'Aggiunta',
    modeEntry: 'Voce',
    modeReminder: 'Promemoria',
    reminderTextPlaceholder: 'Ricordare cosa? es. controllare il ventilatore, riscontro alla conduzione …',
    reminderWhen: 'Scade tra',
    reminderExact: 'Ora',
    reminderChipLabel: '+{n} min',
    reminderTomorrow: ' · domani',
    hourUp: 'Ora +', hourDown: 'Ora −', minUp: 'Minuto +', minDown: 'Minuto −',
    reminderSend: 'Imposta promemoria',
    reminderSaved: 'Promemoria impostato',
    reminderNeedsDue: 'Scegli la scadenza',
    reminderCreated: 'Promemoria: {text}',
    dueTitle: 'Promemoria in scadenza',
    dueOne: 'Promemoria in scadenza',
    dueMany: '{n} promemoria in scadenza',
    dueDone: 'Fatto',
    dueSnooze: '+10 min',
    dueOpen: 'Apri nel diario',
    openCount: '{n} aperti',
    doneLog: 'Promemoria completato: {text}',
    snoozeLog: 'Promemoria +{mins} min: {text}',
    dueAtLabel: 'scade {t}',
    overdueLabel: 'scaduto',
    doneState: 'fatto',
    markDoneTitle: 'Segna come fatto',
  },
  errors: {
    noMicrophone: 'Nessun accesso al microfono. Nota audio registrata come segnaposto.',
  },
  atemschutz: {
    title: 'Sorveglianza autoprotezione',
    subtitle: 'Sorveglianza senza lacune di ogni squadra ARA',
    empty: 'Ancora nessuna squadra in sorveglianza.',
    emptyHint: 'Crea una squadra per avviare la sorveglianza.',
    newTrupp: 'Crea squadra',
    formCreateTitle: 'Crea squadra',
    formEditTitle: 'Modifica squadra',
    formRedeployTitle: 'Rientrare',
    sectionAuftrag: 'Compito',
    sectionTeam: 'Squadra',
    auftragLabel: 'Tipo',
    // Etichette di VISUALIZZAZIONE dei tipi di mandato, indicizzate per id (il valore resta l'id).
    auftragLabels: {
      retten: 'Salvare',
      loeschen: 'Spegnere',
      absuchen: 'Perlustrare',
      sichern: 'Mettere in sicurezza',
      erkunden: 'Esplorare',
      anderes: 'Altro',
    },
    zielLabel: 'Compito / obiettivo',
    zielPlaceholder: 'es. 2° piano, appartamento a sinistra, persona dispersa',
    zielOtherPlaceholder: 'Descrivi il compito',
    leaderLabel: 'Capogruppo',
    leaderPlaceholder: 'Nome del capogruppo',
    memberLabel: 'Milito',
    memberPlaceholder: 'Nome (facoltativo)',
    addMember: 'Aggiungi milito',
    lineNumberLabel: 'N. linea / tubo',
    lineNumberPlaceholder: 'es. 1',
    pressureLabel: 'Pressione d’ingresso (bar)',
    newPressureLabel: 'Nuova pressione d’ingresso (bar)',
    funkkanalSection: 'Canale radio',
    funkkanalDown: 'Canale radio giù',
    funkkanalUp: 'Canale radio su',
    funkkanalUnit: 'Canale',
    clearName: 'Svuota nome',
    notPresent: 'non presente',
    noRoster: 'Nessun effettivo disponibile',
    typeName: 'Inserisci un nome …',
    assignedConflict: '{name} è già in un’altra squadra.',
    cancel: 'Annulla',
    save: 'Salva',
    start: 'Annuncia squadra',
    reenterSubmit: 'Entrare',
    sinceContact: 'Dall’ultimo contatto',
    elapsed: 'Tempo d’intervento',
    currentPressure: 'Pressione',
    lowestPressure: 'Più bassa',
    lineField: 'Linea',
    edit: 'Modifica',
    pressureDown: '10 bar in meno',
    pressureUp: '10 bar in più',
    pressureConfirm: 'Conferma',
    pressureConfirmHint: 'Conferma la nuova pressione — vale come contatto',
    verlauf: 'Diario',
    readingKind: { entry: 'Entrata', contact: 'Contatto', pressure: 'Pressione' },
    clockOk: 'Contatto ok',
    clockWarn: 'Contatto in scadenza',
    clockOverdue: 'In ritardo',
    overdueBadge: '{n} in ritardo',
    actEnter: 'Entrata',
    actContact: 'Contatto',
    actRueckzug: 'Ritiro',
    actContinue: 'Continua',
    actExit: 'Fuori',
    actReenter: 'Rientrare',
    exitConfirmTitle: 'Squadra fuori?',
    exitConfirmMsg: 'Segnare la squadra come fuori e terminare la sorveglianza?',
    remove: 'Rimuovi',
    removedToast: 'Squadra {name} rimossa',
    place: 'Posiziona',
    placeWhere: 'Dove posizionare?',
    placeNoTarget: 'Nessun piano disponibile — crea prima un edificio dalle sagome.',
    showOnPlan: 'Mostra sul piano',
    showOnMap: 'Mostra sulla carta',
    rosterLabel: 'Già registrati',
    preEntryHint: 'Non ancora entrata — premi «Entrata» appena la squadra va sotto ARA.',
    alarmOn: 'Suono d’allarme attivo',
    alarmOff: 'Suono d’allarme disattivato',
    alarmNotifyTitle: 'Autoprotezione in ritardo',
    alarmNotifyBody: 'Squadra {name} in ritardo — stabilire il contatto.',
    status: { angemeldet: 'Annunciata', aktiv: 'In intervento', rueckzug: 'Ritiro', ueberfaellig: 'In ritardo', raus: 'Fuori' },
    logRegister: 'Squadra {name} annunciata',
    logPlaced: 'Squadra {name} posizionata sul piano',
    logPlacedMap: 'Squadra {name} posizionata sulla carta',
    placeLage: 'Carta della situazione',
    logEntry: 'Squadra {name} entrata',
    logContact: 'Squadra {name}: contatto confermato',
    logPressure: 'Squadra {name}: pressione {bar} bar',
    logRueckzug: 'Squadra {name}: ritiro',
    logContinue: 'Squadra {name}: intervento ripreso',
    logEdit: 'Squadra {name}: compito modificato',
    logExit: 'Squadra {name} fuori',
    logReenter: 'Squadra {name} rientrata',
    logAlarm: 'Allarme autoprotezione: squadra {name} – {status}',
  },
  lineDecor: {
    S: 'Lancia da schiuma',
    W: 'Monitore idrico',
    H: 'Cortina d’acqua',
    P: 'Lancia a polvere',
  } as Record<string, string>,
  incidents: {
    migratedTitle: 'Stato di lavoro migrato',
    geojsonNotJson: 'File JSON non valido.',
    geojsonNotFc: 'Non è una FeatureCollection GeoJSON.',
    geojsonNotWgs84: 'Le coordinate sembrano LV95, non WGS84 [lng, lat]. Riproiettare prima in EPSG:4326.',
  },
  entities: {
    photoLabel: 'Foto',
    photoSubtitle: 'Segnaposto foto',
    noteSubtitle: 'Nota',
    fallbackObjectName: 'Oggetto',
  },
  notes: {
    deleteTitle: 'Rimuovere la nota?',
    deleteMsg: 'Questa nota contiene del testo. Rimuoverla davvero?',
  },
  whiteboard: {
    documentListTitle: 'Documenti del piano',
    fit: 'Adatta',
    pan: 'Selezione',
    team: 'Squadra',
    draw: 'Disegna',
    text: 'Nota',
    symbol: 'Simbolo',
    line: 'Linea',
    area: 'Superficie',
    dockHints: {
      draw: 'Trascina sul piano per disegnare liberamente. Colore, spessore e tipo di linea si scelgono sotto.',
      line: 'Tocca i vertici. Doppio tocco o «Fatto» chiude la linea. Lo stile si sceglie sotto.',
      area: 'Tocca i vertici (almeno 3). Doppio tocco o «Fatto» chiude la superficie.',
      text: 'Tocca il piano per inserire una nota.',
      resource: 'Tocca il piano per posizionare una squadra. Trascina per spostarla.',
      scale: 'Tocca i due estremi della scala stampata, poi inserisci la lunghezza reale. Dopodiché le linee con «Lunghezza» mostrano metri reali.',
      measure: 'Tocca i punti sul piano. «Distanza» mostra la distanza, «Superficie» l’area + perimetro — in metri reali una volta calibrata la scala. Trascina i punti per spostarli, doppio tocco per rimuoverne uno.',
    },
    scale: {
      tool: 'Scala',
      promptTitle: 'Imposta la scala',
      promptBody: 'Lunghezza reale della distanza rilevata (es. la barra di scala):',
      unit: 'm',
      confirm: 'Applica',
      cancel: 'Annulla',
      chipCalibrated: 'Scala: rif. {m} m',
      chipUncalibrated: 'Scala non calibrata',
      recalibrate: 'Ricalibra',
      calibrate: 'Calibra la scala',
      calibrateHint: 'Tocca due punti della barra di scala',
      stale: 'Piano modificato — ricontrolla la scala',
      saved: 'Scala calibrata ({m} m di riferimento)',
      needsCalibration: 'Imposta la scala: tocca i due estremi della barra di scala',
    },
    finishShape: 'Fatto',
    cancelShape: 'Annulla',
    insertVertex: 'Inserisci punto',
    dragVertex: 'Trascina il vertice · doppio tocco per eliminare',
    groupDeleted: 'Selezione rimossa',
    placeText: 'Nota posizionata sul piano',
    placeSymbol: 'Simbolo «{name}» posizionato sul piano',
    placeLine: 'Linea disegnata sul piano',
    placeArea: 'Superficie disegnata sul piano',
    placeTeam: '{name} posizionato sul piano',
    selectTrupp: 'Quale squadra?',
    newTeam: 'Nuova squadra',
    showTrupp: 'Mostra in autoprotezione',
    markPosition: 'Segna posizione',
    positionMarked: '{name}: posizione segnata',
    clearTrail: 'Cancella traccia',
    clearTrailConfirm: 'Eliminare tutte le {n} posizioni segnate di {name}? La traccia sparisce da carta e piano.',
    trailCleared: '{name}: traccia cancellata',
    teamColor: 'Colore',
    trails: 'Tracce',
    trailsOn: 'Mostra tracce',
    trailsOff: 'Nascondi tracce',
    deleteLocked: 'Squadra con cronologia registrata — cancella prima la traccia',
    drawCreated: 'Disegno creato sul piano',
    placeSymbolHint: 'Tocca il piano per posizionare «{name}»',
    textHint: 'Tocca il piano per inserire del testo',
    teamHint: 'Tocca il piano per posizionare una squadra',
    textPlaceholder: 'Nota ...',
    blankHint: 'Foglio bianco — annota con disegno, testo, simbolo o squadra',
    osmLoading: 'Caricamento sagome degli edifici …',
    osmError: 'Sagome degli edifici (OSM) non raggiungibili',
    osmEmpty: 'Nessun edificio in questa zona',
    osmPickHint: 'Tocca un edificio, poi applica',
    osmTransfer: 'Applica ({n})',
    osmClear: 'Cancella selezione',
    addFloorUp: 'Aggiungi piano superiore',
    addFloorDown: 'Aggiungi piano inferiore',
    removeFloor: 'Rimuovi piano',
    removeFloorConfirm: '{floor} contiene schizzi o marcatori. Rimuovere comunque il piano?',
    floorRemoved: 'Piano rimosso',
    floorAdded: 'Piano aggiunto',
    buildingReplaced: 'Edificio sostituito',
    replaceBuilding: 'Scegli un altro edificio',
    replaceBuildingConfirm: 'Ci sono schizzi sui piani. Scegliere un altro edificio e scartare i piani esistenti?',
    otherObject: 'Altro oggetto',
    objectActive: 'Piani di «{name}»',
    objectReset: 'Reimposta al prossimo oggetto',
    objectSwitchConfirmTitle: 'Carica un altro oggetto',
    objectSwitchConfirm: 'I piani di tutti i moduli passeranno a «{name}». Cambiare l’oggetto attuale?',
    objectSwitchConfirmCta: 'Carica oggetto',
    northLabel: 'N',
    northTitle: 'Direzione nord — edificio ruotato sull’asse maggiore',
    orientNorthUp: 'Nord in alto',
    orientLongAxis: 'Ruota sull’asse maggiore',
  },
  contextPanel: {
    titlePlaceholder: 'Denominazione ...',
    titleTypePick: 'Scegli il tipo …',
    floor: 'Piano',
    floorFrom: 'Dal piano',
    floorTo: 'Al piano',
    floorNone: '–',
    floorClear: 'Reimposta',
    spread: 'Propagazione',
    spreadH: 'Orizzontale',
    spreadV: 'Verticale',
    spreadBounded: 'Limite',
    spreadBoundedTitle: 'Limite di propagazione (propagazione fermata)',
    spreadLeft: 'a sinistra',
    spreadRight: 'a destra',
    spreadUp: 'Piano superiore (↑)',
    spreadDown: 'Piano inferiore (↓)',
    count: 'Quantità',
    rotation: 'Rotazione',
    rotationVehicle: 'Veicolo',
    rotationFan: 'Ventilatore',
    rotationLadder: 'Scala',
    center: 'Centra',
    resetGps: 'GPS',
    resetGpsTitle: 'Reimposta su posizione e rotta GPS',
    rotateHint: 'Trascina la maniglia per orientare',
    detailsTitle: 'Dettagli',
    notes: 'Note',
    notesPlaceholder: 'Note generali …',
    addField: 'Aggiungi campo',
    removeField: 'Rimuovi campo',
    fieldKeyPlaceholder: 'Denominazione',
    fieldValuePlaceholder: 'Valore',
    unHazardTitle: 'Merci pericolose (ADR)',
    unClass: 'Classe',
    unKemler: 'Numero di pericolo',
    unLabels: 'Etichette di pericolo',
    unPacking: 'Gruppo di imballaggio',
    unNoMatch: 'N. ONU non trovato nella tabella ADR',
    unWater: 'Reagisce pericolosamente con l’acqua – NON usare acqua!',
    unLookupLabel: 'Scheda di sicurezza (GESTIS)',
    kemler: {
      '2': 'Gas (fuoriuscita sotto pressione o per reazione)',
      '3': 'Liquido / gas infiammabile',
      '4': 'Solido infiammabile',
      '5': 'Comburente (ossidante)',
      '6': 'Tossico / rischio di infezione',
      '7': 'Radioattivo',
      '8': 'Corrosivo',
      '9': 'Rischio di reazione spontanea violenta',
    } as Record<string, string>,
    kemlerDoubled: 'Pericolo intensificato (cifra raddoppiata)',
  },
  drawingEditor: {
    area: 'Superficie',
    drawing: 'Disegno',
    circle: 'Perimetro di sicurezza',
    radius: 'Raggio',
    fill: 'Riempimento',
    move: 'Sposta',
    points: 'Punti',
    preset: 'Stile',
    color: 'Colore',
    width: 'Spessore',
    lineStyle: 'Linea',
    lineSolid: 'Continua',
    lineDashed: 'Tratteggiata',
    label: 'Testo',
    labelPlaceholder: 'Etichetta …',
    areaLabelPlaceholder: 'es. Settore A / Sezione est',
    marker: 'Marcatore',
    markerPlaceholder: 'es. R',
    arrow: 'Punta della freccia',
    ending: 'Terminazione',
    endingNone: 'Nessuna',
    endingArrow: 'Freccia',
    endingTeilstueck: 'Tratto',
    content: 'Contenuto',
    contentPlain: 'Acqua',
    lineNo: 'Linea n.',
    floorTag: 'Piano',
    distance: 'Lunghezza',
    inputMode: 'Immissione',
    modeFreehand: 'Mano libera',
    modeNodes: 'Punti',
    on: 'Attivo',
    off: 'Spento',
    lock: 'Blocca',
    lockHint: 'Blocca la forma contro spostamenti accidentali; tocca il lucchetto al centro per sbloccare.',
    unlockHold: 'Tieni premuto per sbloccare',
    unlocking: 'Sblocco …',
  },
  topBar: {
    offline: 'Offline',
    tiles: 'Tasselli',
    recording: 'REC',
  },
  stepper: {
    less: 'meno',
    more: 'più',
    reset: 'reimposta',
    typeToEnter: 'Tocca per inserire',
  },
  confirm: {
    ok: 'OK',
    cancel: 'Annulla',
  },
  combo: {
    customDefault: 'Inserisci …',
    empty: 'Nessuna scelta',
  },
  login: {
    subtitle: 'Supporto alla conduzione',
    pinEnter: 'Inserisci PIN',
    connectionFailed: 'Connessione al server fallita',
    loadingRoster: 'Caricamento effettivo…',
    noUsers: 'Nessun utente registrato',
    whoAreYou: 'Chi sei?',
    loginFailed: 'Accesso fallito',
    pleaseWait: 'Attendi un momento…',
    clearDigit: 'Cancella',
  },
  errorBoundary: {
    title: 'Si è verificato un errore',
    body: 'Impossibile caricare la vista. Le tue modifiche locali sono salvate e restano intatte.',
    reload: 'Ricarica',
  },
  update: {
    available: 'Aggiornamento pronto',
    hint: 'Attivo al prossimo avvio — chiudere completamente l’app e riaprirla.',
    dismiss: 'OK',
    updated: 'Aggiornato – {v}',
  },
  install: {
    menu: 'Installa come app',
    bannerTitle: 'Installa KP Front come app',
    bannerHint: 'Offline, schermo intero, icona propria.',
    bannerAction: 'Guida',
    dismiss: 'Più tardi',
    title: 'Installa come app',
    why: 'Installata, KP Front funziona come un’app: disponibile offline sul posto, a schermo intero senza barra del browser, con la propria icona nella schermata Home.',
    nativeButton: 'Installa ora',
    nativeHint: 'Il browser chiederà conferma — confermare con «Installa».',
    manualIntro: 'Oppure manualmente:',
    installed: 'Installata! D’ora in poi avviare KP Front dall’icona dell’app.',
    alreadyStandalone: 'KP Front è già in esecuzione come app installata.',
    ios: {
      intro: 'Su iPad/iPhone:',
      steps: [
        'Toccare il simbolo di condivisione {share} nella barra degli strumenti',
        'Scegliere «Aggiungi alla schermata Home»',
        'Confermare con «Aggiungi»',
      ],
      note: 'Se «Aggiungi alla schermata Home» manca: aprire la pagina in Safari.',
    },
    android: {
      intro: 'In Chrome su Android:',
      steps: [
        'Toccare il menu ⋮ in alto a destra',
        'Scegliere «Installa app»',
        'Confermare',
      ],
      note: 'In altri browser: menu → «Aggiungi a schermata Home».',
    },
    desktop: {
      intro: 'In Chrome o Edge:',
      steps: [
        'Cliccare sull’icona di installazione a destra nella barra degli indirizzi',
        'Confermare con «Installa»',
      ],
      note: 'In alternativa: menu del browser ⋮ → «Installa KP Front».',
    },
    macSafari: {
      intro: 'In Safari su Mac:',
      steps: [
        'Aprire il menu «File»',
        'Scegliere «Aggiungi al Dock»',
        'Confermare con «Aggiungi»',
      ],
      note: '',
    },
    unsupported: 'Questo browser non supporta l’installazione. Meglio aprire la pagina in Chrome, Edge o Safari e installare lì.',
  },
  tabLock: {
    title: 'Aperto in un’altra scheda',
    hint: 'Questa scheda è in sola lettura — la modifica è attiva nell’altra scheda.',
    takeOver: 'Modifica qui',
  },
  mapPicker: {
    title: 'Imposta la posizione sulla carta',
    hint: 'Tocca la carta per impostare la posizione',
    confirm: 'Usa la posizione',
  },
  weather: {
    label: 'Meteo',
    details: 'Dettagli meteo',
    from: 'da',
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    cardinalsLong: ['Nord', 'Nordest', 'Est', 'Sudest', 'Sud', 'Sudovest', 'Ovest', 'Nordovest'],
    windTitle: 'Vento {dir} ({deg}°)',
    detailsHint: ' — tocca per i dettagli',
    meteoHint: ' — tocca per i dettagli MeteoSvizzera',
    windDir: 'Direzione del vento',
    windSpeed: 'Velocità del vento',
    gust: 'Raffiche',
    precip: 'Precipitazioni',
    station: 'Stazione',
    source: 'Fonte',
    meteoRadar: 'Radar delle precipitazioni MeteoSvizzera',
    detailsUrl: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/precipitazioni.html',
    conditions: {
      clear: 'Sereno', fair: 'Poco nuvoloso', partly: 'Parzialmente nuvoloso', overcast: 'Coperto',
      fog: 'Nebbia', drizzle: 'Pioviggine', rain: 'Pioggia', snow: 'Neve',
      rainShowers: 'Rovesci di pioggia', snowShowers: 'Rovesci di neve', thunder: 'Temporale', cloudy: 'Nuvoloso',
    },
  },
  settings: {
    title: 'Impostazioni',
    deviceGroup: 'Dispositivo',
    colorScheme: 'Schema colori',
    symbolSize: 'Dimensione simboli',
    offlineRadius: 'Raggio offline',
    offlineRadiusSub: 'Carta e condotte attorno all’intervento',
    deviceFoot: 'Vale solo su questo dispositivo. Raggio più piccolo = download offline più veloce e più piccolo.',
    incidentGroup: 'Intervento',
    contactInterval: 'Contatto radio autoprotezione',
    contactIntervalSub: 'Intervallo fino al contatto dovuto (ambra)',
    contactIntervalAria: 'Intervallo del contatto radio',
    grace: 'Tempo di tolleranza',
    graceSub: 'Allarme rosso dopo intervallo + tolleranza',
    funkkanal: 'Canale radio',
    funkkanalSub: 'Predefinito per le nuove squadre ARA',
    syncedFoot: 'Sincronizzato con tutti i dispositivi',
    syncedFootViewer: ' · solo il capo intervento può modificarle',
  },
  offline: {
    title: 'Prontezza offline',
    syncNow: 'Sincronizza ora',
    syncedAgo: 'Dati dell’intervento sincronizzati {ago}',
    offline: 'Offline – salvato localmente',
    pending: 'Salvataggio …',
    error: 'Errore di sincronizzazione – salvato localmente',
    agoNever: 'non ancora',
    agoJustNow: 'proprio ora',
    agoMin: '{n} min fa',
    agoHour: '{n} h fa',
    checking: 'verifica in corso …',
    ready: 'pronto',
    notLoaded: 'non caricato',
    loading: 'caricamento …',
    rowSymbols: 'Simboli',
    rowHazmat: 'Merci pericolose (ONU/ADR)',
    rowMap: 'Carta',
    noLayer: 'nessun livello',
    rowPlans: 'Piani',
    noObject: 'nessun oggetto',
    rowLeitung: 'Catasto delle condotte',
    geoAllReady: 'tutti i {n} pronti',
    geoSome: '{cached}/{total} caricati',
    rowWeather: 'Meteo',
    weatherUnreachable: 'non raggiungibile',
    onlineOnly: 'solo online',
    rowPersonnel: 'Effettivo',
    personnelCount: '{n} persone',
    rowObjectSearch: 'Ricerca oggetti',
    loadingForOffline: 'Caricamento per l’offline …',
    loadAll: 'Carica tutto per l’offline',
    foot: 'Carica carta, piani, simboli e condotte di questo intervento su questo dispositivo. Meteo e ricerca oggetti richiedono una connessione e non sono disponibili offline.',
    layerGroup: 'Offline',
    loadMap: 'Scarica la carta per l’offline',
    loadingShort: 'Caricamento … {done}/{total}',
    dlDone: 'Carta disponibile offline ({n} tasselli)',
    dlDoneCapped: 'Carta disponibile offline (area limitata, {n} tasselli)',
    dlFailed: 'Download offline fallito',
  },
  emptyApp: {
    title: 'Nessun intervento aperto',
    bodyViewer: 'Al momento nessun intervento è attivo.',
    bodyPoolOne: '1 allarme Divera nel pool — aprilo e verifica sulla carta.',
    bodyPoolMany: '{n} allarmi Divera nel pool — aprine uno e verifica sulla carta.',
    bodyEditor: 'Apri un intervento o rileva un allarme Divera.',
    history: 'Cronologia',
  },
  incidentAlert: {
    kicker: 'Nuovo intervento',
    switch: 'Cambia',
    open: 'Apri',
    later: 'Più tardi',
  },
  capture: {
    title: 'Registrare l’intervento',
    invalid: 'Link non valido o rilevamento disattivato.',
    noIncidents: 'Al momento nessun intervento registrabile.',
    noIncidentsHint: 'Qui appaiono gli interventi in corso e non ancora rapportati. Manca il vostro? Annotatelo sul foglio cartaceo o segnalatelo alla condotta — potrà aggiungerlo in seguito.',
    whoTitle: 'Chi registra?',
    searchName: 'Cerca nome …',
    back: 'Indietro',
    alarmedAt: 'Allarme {t}',
    saveFailed: 'Salvataggio non riuscito — riprovare.',
    saveFailedOffline: 'Nessuna connessione — l’ultima modifica non è stata salvata.',
    retry: 'Riprovare',
    savedOk: 'Salvato',
    undo: 'Annulla',
    removedEntry: '{name} rimosso (orari inclusi)',
    mittelSet: '{label}: ora {n} {unit}',
    mittelRemoved: '{label} rimosso',
    stepLess: 'Uno in meno',
    stepMore: 'Uno in più',
    mittelExtra: 'Altre posizioni registrate',
    gerettete: 'Salvati',
    gerettetePersonen: 'Persone',
    geretteteTiere: 'Animali',
    rueckmeldung: 'Rapporto alla centrale',
    rueckName: 'Scegliere un nome …',
    rueckZeit: 'Ora',
    jetzt: 'Adesso',
    kurzberichtHead: 'Rapporto breve',
    kurzberichtPlaceholder: 'Cosa è successo, cosa è stato fatto?',
    zeitenHead: 'Orari',
    gruppenHead: 'Allarme dei gruppi',
    fahrzeugeHead: 'Partenze dei veicoli',
    angabenHead: 'Indicazioni',
    einsatzleiter: 'Capo intervento',
    rueckName2: 'Nome',
    rapportPdf: 'Rapporto PDF',
    pdfFailed: 'PDF non riuscito — riprovare.',
    sectionZeiten: 'Orari',
    sectionAngaben: 'Indicazioni',
    zeitenFilled: '{n} orari registrati',
    abschlussHead: 'Chiusura',
    pdfMissing: 'Ancora vuoto (stampato come campo da compilare): {fields}',
    ausgerueckt: 'Partenza',
    kontaktperson: 'Persona di contatto',
    kontaktpersonPlaceholder: 'Proprietario / segnalante / responsabile',
    von: 'da',
    bis: 'a',
    ende: 'Fine intervento',
    endeNow: 'Adesso',
    sectionPersonen: 'Presenze',
    presentCount: '{n} presenti',
    tapHint: 'Toccare: assente → presente → andato. Ora accanto: da = arrivo, dopo l\'uscita a = uscita.',
    statePresent: 'presente',
    stateLeft: 'partito',
    sectionMaterial: 'Materiale',
    sectionAllgemein: 'Generale',
    selectPerson: 'Scegli un nome …',
    whoHint: 'Riportato nel rapporto come «registrato da».',
    cancel: 'Annulla',
    mittelCount: '{n} posizioni',
    pickMaterial: 'Scegliere il materiale …',
    add: 'Aggiungere',
    sectionNotizen: 'Note',
    notePlaceholder: 'Nota per il diario …',
    footNote: 'Tutto viene salvato continuamente.',
    tapHelp: 'Guida all\'uso',
  },
  incidentSwitcher: {
    noIncident: 'Nessun intervento',
    savedAt: 'Salvato alle {t}',
    saved: 'Salvato',
    badgePending: 'Non sincronizzato – salvataggio in corso',
    badgeOffline: 'Offline – salvato localmente, si sincronizza non appena riconnesso',
    badgeError: 'Sincronizzazione fallita – salvato localmente, si riproverà',
    syncNow: 'Sincronizza ora',
    incidents: 'Interventi',
    allIncidents: 'Tutti gli interventi',
    archive: 'Chiudi intervento',
    report: 'Rapporto d’intervento',
    noOpenIncidents: 'Nessun intervento aperto',
    logout: 'Disconnetti',
    appVersion: 'Versione app (build)',
  },
  archived: {
    title: 'Intervento archiviato',
    hint: 'Sola visualizzazione — riattivare per modificare.',
    reactivate: 'Riattiva',
  },
  history: {
    title: 'Interventi',
    empty: 'Ancora nessun intervento.',
    noLocation: 'senza luogo',
    searchPlaceholder: 'Cerca intervento …',
    noMatches: 'Nessun risultato.',
    groupOpen: 'Aperti',
    groupToday: 'Oggi',
    groupWeek: 'Ultimi 7 giorni',
    reactivate: 'Riattiva',
    reactivateConfirmTitle: 'Riattiva intervento',
    reactivateConfirmMsg: 'L\u2019intervento viene riaperto ed è modificabile. Le modifiche successive appaiono nel diario e nel rapporto come aggiunte.',
    reactivateConfirmBtn: 'Riattiva',
    statusArchived: 'Archiviato',
    statusOpen: 'Aperto',
    statusInProgress: 'In corso',
  },
  abschluss: {
    leftEarly: ' · fino alle {t}',
    steps: {
      zeiten: 'Orari',
      anwesenheit: 'Presenze',
      mittel: 'Mezzi',
      abschluss: 'Chiusura',
    },
    ausgerueckt: 'Partenza',
    ende: 'Fine intervento',
    personen: '{n} registrati',
    stunden: 'Ore',
    von: 'da',
    bis: 'a',
    mittelCount: '{n} posizioni',
    mittelNone: 'Niente usato',
    mittelNoneOn: 'Niente usato ✓',
    complete: 'Chiudere l’intervento',
    backToRapport: 'Torna al rapporto',
    confirmTitle: 'Chiudere l’intervento',
    confirmMsg: 'Il rapporto viene contrassegnato come chiuso e l’intervento archiviato. Le correzioni restano possibili e appaiono come aggiunte.',
    confirmMissing: 'Ancora aperto: {steps}. Chiudere comunque?',
    confirmBtn: 'Chiudere',
    done: 'Rapporto chiuso',
    failed: 'Chiusura non riuscita',
    corrected: 'Ore corrette: {name}',
    attendanceRemoved: 'Presenza di {name} rimossa',
  },
  datenquellen: {
    title: 'Fonti dati',
    uploaded: 'Caricato',
    uploadFailed: 'Caricamento fallito',
    invalidFilename: 'Il nome del file non produce un identificativo valido',
    layerAdded: 'Livello «{name}» aggiunto — visibile al prossimo caricamento',
    addLayerFailed: 'Impossibile aggiungere il livello',
    globalDatasets: 'Set di dati globali',
    objectsCount: 'oggetti',
    replace: 'Sostituisci',
    newGeoLayer: 'Nuovo livello geo …',
    chooseGeojson: 'Scegli GeoJSON …',
    labelPlaceholder: 'Denominazione (es. idranti)',
    groupPlaceholder: 'Gruppo (es. acqua)',
    defaultGroup: 'Riferimento',
    kindLines: 'Linee',
    kindPoints: 'Punti',
    color: 'Colore',
    adding: 'Caricamento …',
    add: 'Aggiungi',
    geojsonNoteBefore: 'GeoJSON in WGS84 [lng, lat]. Salvato come set di dati globale ',
    geojsonNoteAfter: '.',
    incidentObjects: 'Oggetti dell’intervento',
    plansWord: 'piani',
    nearby: 'Nelle vicinanze ({n})',
    allOther: 'Tutti gli altri oggetti',
    allObjects: 'Tutti gli oggetti',
  },
  personnelSync: {
    title: 'Sincronizza effettivo con {provider}',
    unknownError: 'Errore sconosciuto',
    syncFailed: 'Sincronizzazione fallita',
    countNew: 'nuovi',
    countUpdated: 'aggiornati',
    countUnchanged: 'invariati',
    countStale: 'non più in {provider}',
    querying: 'Interrogazione di {provider} …',
    done: 'Sincronizzazione completata.',
    resultCreated: '{n} creati',
    resultUpdated: '{n} aggiornati',
    resultReactivated: ' (di cui {n} riattivati)',
    resultUnchanged: '{n} invariati',
    resultDeactivated: '{n} disattivati',
    staleHide: 'Nascondi {n} persone non più presenti in {provider} (mantenute per i vecchi interventi, non eliminate)',
    syncing: 'Sincronizzazione …',
    sync: 'Sincronizza',
  },
  planPicker: {
    searchPlaceholder: 'Cerca nome o indirizzo …',
    autoNextObject: 'Oggetto più vicino automaticamente',
    loading: 'Caricamento oggetti …',
    loadFailed: 'Impossibile caricare gli oggetti.',
    noObject: 'Nessun oggetto trovato.',
    planOne: 'piano',
    planMany: 'piani',
    mapNote: 'Coordinate in parte imprecise — fa fede l’elenco.',
    hideMap: 'Nascondi carta',
    showMap: 'Mostra carta',
  },
  replay: {
    region: 'Riproduzione diario',
    banner: 'DIARIO · RIPRODUZIONE',
    subtitle: 'Vista in sola lettura del passato',
    backToLive: 'Torna in diretta',
    loadFailed: 'Impossibile caricare il diario.',
    loading: 'Caricamento diario …',
    transport: 'Riproduzione',
    skipBack: '10 secondi indietro',
    skipFwd: '30 secondi avanti',
    pause: 'Pausa',
    speed: 'Velocità',
    timepoint: 'Momento',
    now: 'Ora',
    noVehicleData: 'nessun dato dei veicoli · vengono riprodotti la situazione tattica + lo stato',
    noVehicleTitle: 'L’acquisizione Traccar→campione non è ancora collegata',
    markerSymbol: 'Simbolo posizionato',
    markerDraw: 'Disegno',
    markerStatus: 'Stato',
    markerDivera: 'Divera',
    markerIncidentOpen: 'Intervento aperto',
    markerSave: 'Punto di salvataggio',
  },
  report: {
    erfasser: 'Registrato da',
    gerettete: 'Salvati',
    gerettetePersonen: 'persone',
    geretteteTiere: 'animali',
    rueckmeldungElz: 'Rapporto alla centrale',
    zeitenHead: 'Orari di allarme / partenza',
    back: 'Indietro',
    print: 'Stampa',
    coverEyebrow: 'Rapporto d’intervento',
    blankPlan: 'Piano vuoto',
    keyword: 'Parola chiave',
    addressObject: 'Indirizzo / oggetto',
    einsatzleiter: 'Capo intervento',
    kontaktperson: 'Persona di contatto',
    alarmierung: 'Allarme',
    ausgerueckt: 'Partenza',
    incidentEnd: 'Fine intervento',
    incidentId: 'ID intervento',
    alarmMessage: 'Messaggio d’allarme',
    summaryHead: 'Breve descrizione / lavori eseguiti',
    partnerOrgs: 'Organizzazioni partner',
    remarks: 'Osservazioni',
    sigKommandant: 'Comandante',
    kroki: 'Schizzo',
    krokiState: '{title} · stato {at}',
    atemschutz: 'Sorveglianza autoprotezione',
    truppMembers: 'Membri',
    truppAuftrag: 'Compito / obiettivo',
    truppLine: 'Linea',
    truppEntry: 'Entrata',
    truppExit: 'Uscita',
    colTime: 'Ora',
    colKind: 'Tipo',
    colPressure: 'Pressione bar',
    noPressureLog: 'Nessun registro pressioni acquisito.',
    mittel: 'Materiale (indicare la quantità)',
    personalHead: 'Personale / presenza',
    personalHint: 'Spuntare, completare da–a se necessario',
    partnerOther: 'Altre',
    journal: 'Diario d’intervento',
    colArea: 'Area',
    colEntry: 'Voce',
    audioPresent: 'Audio presente',
    audioNotTranscribed: ', non trascritto',
    photo: 'Foto',
    transcript: 'Trascrizione',
    noEntries: 'Nessuna voce.',
    nachtraege: 'Aggiunte dopo la fine dell’intervento',
    planFallback: 'Piano',
    proofOffline: 'Verifica non possibile (offline)',
    proofIntact: 'Catena di hash intatta',
    proofBroken: 'Catena di hash interrotta',
    proofBrokenAt: 'Catena di hash interrotta al #{seq}',
    areaManual: 'Manuale',
    areaAtemschutz: 'Autoprotezione',
    drawCircle: 'Perimetro di sicurezza',
    drawAreaLabeled: 'Sezione «{label}»',
    drawArea: 'Superficie',
    drawRescueAxis: 'Asse di salvataggio',
    drawMeasureArrow: 'Freccia di misura',
    drawLine: 'Linea',
  },
  wheel: {
    day: 'Giorno',
    month: 'Mese',
    year: 'Anno',
    hour: 'Ora',
    minute: 'Minuto',
    now: 'Adesso',
    ok: 'OK',
    clear: 'Cancellare',
  },
  preflight: {
    pdfFull: 'Rapporto d’intervento (PDF)',
    pdfBusy: 'Creazione del PDF …',
    geretteteLabel: 'Salvati',
    gerettetePersonen: 'Persone',
    geretteteTiere: 'Animali',
    gruppenLabel: 'Allarme dei gruppi',
    fahrzeugeLabel: 'Partenze dei veicoli',
    ausgeruecktDerived: 'ripreso dagli orari dei veicoli',
    vorOrtShort: 'sul posto',
    zurueckShort: 'rientro',
    rueckmeldungLabel: 'Rapporto alla centrale',
    rueckmeldungName: 'Nome',
    rueckmeldungZeit: 'Ora',
    title: 'Stampa rapporto d’intervento',
    rapportHead: 'Dati del rapporto',
    fromDispatch: 'Dai dati dell’intervento',
    edit: 'Modifica',
    alarmMessage: 'Messaggio d’allarme',
    alarmierung: 'Allarme',
    notRecorded: 'Non registrato',
    summaryLabel: 'Breve descrizione',
    summaryPlaceholder: 'Cosa è successo / cosa è stato trovato?',
    einsatzleiterLabel: 'Capo intervento',
    einsatzleiterPlaceholder: 'Scegli o inserisci',
    kontaktpersonLabel: 'Persona di contatto',
    kontaktpersonPlaceholder: 'Proprietario / segnalante / responsabile',
    incidentEndLabel: 'Fine intervento',
    now: 'Ora',
    remarksLabel: 'Osservazioni',
    remarksPlaceholder: 'Facoltativo',
    sectionsHead: 'Sezioni',
    groupMap: 'Mappa & piani',
    groupContents: 'Contenuti',
    groupAdvanced: 'Avanzate',
    toggleKroki: 'Schizzo',
    plansLabel: 'Piani',
    plansAnnotated: 'Annotati ({n})',
    plansAll: 'Tutti',
    plansNone: 'Nessuno',
    toggleAtemschutz: 'Sorveglianza autoprotezione ({n})',
    toggleAttendance: 'Presenza ({n})',
    toggleJournal: 'Diario d’intervento',
    toggleDetailedAudit: 'Prova di integrità dettagliata',
    framingTitle: 'Scegli il ritaglio dello schizzo',
    framingHint: 'Sposta e ingrandisci la mappa — verrà stampato esattamente questo ritaglio.',
    framingFit: 'Zoom sull’intervento',
    framingConfirm: 'Usa questo ritaglio',
    controlHead: 'Controlli',
    proofChecking: 'Verifica della prova di integrità …',
    annotatedDefault: '{n} piani annotati vengono stampati di default.',
    missingTranscripts: '{n} voce/voci audio senza trascrizione — integra per il verbale.',
    fixTranscripts: 'Integra nel diario',
    stateNote: 'Stato: intero intervento fino alla creazione del rapporto ({at}).',
    cancel: 'Annulla',
    openPrint: 'Apri anteprima di stampa',
  },
  printRelay: {
    send: 'Stampa',
    sending: 'Invio in corso …',
    queued: 'Inviato alla stampante di caserma',
    confirmTitle: 'Stampa',
    confirmMsg: 'Inviare il rapporto d’intervento alla stampante di caserma?',
    confirmBtn: 'Stampa',
    undo: 'Annulla',
    cancelled: 'Stampa annullata',
    undoTooLate: 'Troppo tardi — il documento è già alla stampante',
    failed: 'Invio alla stampante di caserma non riuscito',
    online: 'Stampante di caserma raggiungibile',
    offline: 'Stampante di caserma offline',
    offlineConfirmTitle: 'Stampante di caserma offline',
    offlineConfirmMsg: 'Il relè di stampa al momento non risponde. Il documento verrà stampato non appena sarà di nuovo raggiungibile. Inviare comunque?',
    offlineConfirmBtn: 'Invia comunque',
  },
  anwesenheit: {
    title: 'Presenza',
    summary: '{present} presenti · {left} andati via · {total} effettivo',
    reload: 'Ricarica effettivo',
    loading: 'Caricamento …',
    refresh: 'Aggiorna',
    searchPlaceholder: 'Cerca nome',
    clearSearch: 'Cancella ricerca',
    legendFrei: 'non presente',
    legendPresent: 'presente',
    legendLeft: 'andato via',
    loadFailedTitle: 'Impossibile caricare l’effettivo.',
    loadFailedHint: 'Offline o server non raggiungibile. L’ultimo elenco caricato resta disponibile.',
    emptyTitle: 'Nessun effettivo disponibile.',
    emptyHint: 'Sincronizza l’effettivo da Divera.',
    retry: 'Riprova',
    noMatches: 'Nessun risultato.',
    lockedTitle: 'In una squadra ARA — segna prima la squadra come fuori',
    notInDivera: 'Non più in Divera',
    weg: 'via',
    editTime: 'Modifica ora',
  },
  checklists: {
    railLabel: 'Checklist',
    showList: 'Mostra elenco',
    groupTasks: 'Compiti',
    groupTactics: 'Tattica · parole chiave',
    searchPlaceholder: 'Cerca parola chiave ...',
    searchAria: 'Cerca parola chiave',
    matching: 'Corrispondente: {title}',
    noMatches: 'Nessun risultato.',
    none: 'Ancora nessuna checklist disponibile.',
    pickEntry: 'Scegli o cerca una parola chiave.',
    done: 'fatto',
    variantLabel: 'Variante',
    pickVariant: 'Scegli una variante per vedere i compiti.',
    milestoneTitle: 'Traguardo — appare nel diario',
    actionLabels: { journal: 'Diario', plan: 'Piano', draw: 'Disegna' },
    hazardLabels: { red: 'Incendio', orange: 'Pericoli', green: 'Traffico', yellow: 'Tecnico', blue: 'Acqua' },
    diagramAlt: 'Diagramma pagina {page}',
  },

  admin: {
    common: {
      configLoading: 'Caricamento configurazione…',
      copy: 'Copiare',
      copied: 'Copiato',
      confirmYes: 'Sì, eseguire',
      confirmNo: 'Annulla',
    },
    shell: {
      verwaltung: 'Amministrazione',
      toLageMap: '← Alla carta della situazione',
      logout: 'Disconnetti',
      openSections: 'Apri sezioni',
      closeSections: 'Chiudi sezioni',
      navAria: 'Sezioni di amministrazione',
    },
    denied: {
      title: 'Nessun accesso',
      body: 'L’amministrazione è riservata agli editor. Sei connesso come {name}.',
    },
    nav: {
      groupStation: 'Stazione',
      groupPersonen: 'Persone',
      groupDaten: 'Dati',
      groupSystem: 'Sistema',
      identitaet: { label: 'Stazione e mappa', title: 'Stazione e mappa', lede: 'Nome, lingua, colore del marchio, loghi e vista iniziale della mappa per questa installazione.' },
      karte: { label: 'Carta', title: 'Carta', lede: 'Vista iniziale della carta della situazione (centro + zoom), prima che sia scelto un intervento.' },
      doktrin: { label: 'Dottrina', title: 'Dottrina', lede: 'Prescrizioni FKS di questo corpo: canale radio predefinito, intervallo di contatto ARA e preavviso.' },
      fahrzeuge: {
        label: 'Simboli',
        title: 'Simboli',
        lede: 'Elenchi di scelta per l’immissione nella situazione. Suggerimenti — l’inserimento libero resta possibile.',
        tip: 'Ogni elenco collega suggerimenti di scelta a un campo di simbolo — es. tipi di veicolo a «VKF veicolo · titolo». Solo suggerimenti; nella situazione l’inserimento libero resta sempre possibile.',
      },
      ebenen: { label: 'Livelli della carta', title: 'Livelli della carta', lede: 'Livelli di riferimento/condotte di questo corpo (idranti, catasto delle condotte, WMS cantonale …). Le carte di base sono nazionali/incluse.' },
      objektplaene: {
        label: 'Piani degli oggetti',
        title: 'Piani degli oggetti (moduli)',
        lede: 'Catalogo dei moduli di questo corpo: quali moduli esistono, la loro etichetta (M1, 2/3 …), l’ordine e le regole di riconoscimento per l’importazione. Vuoto = moduli standard inclusi.',
        tip: 'Una configurazione per entrambi: le tessere dei piani nell’app e l’analisi dei file di import_einsatzplaene (l’importatore recupera questo elenco via /api/config). «Famiglia» genera sottomoduli dal nome del file (Modul 5 - Wasser → modul5-wasser); «Combinato con» riempie più slot da un foglio cumulativo (Modul 2-3 → modul2, modul3).',
      },
      mitglieder: { label: 'Membri e accesso', title: 'Membri e accesso', lede: 'Chi può accedere, con quale ruolo e quale PIN.' },
      mannschaft: { label: 'Effettivo', title: 'Effettivo', lede: 'Anagrafica locale canonica: inserimento manuale e CSV sempre disponibili; una fonte personale può sincronizzare i dati.' },
      erfassung: { label: 'Rilevamento', title: 'Rilevamento (poster)', lede: 'Il poster di rilevamento per il magazzino: un codice QR con cui registrare presenze, materiale e note di un intervento recente senza login.' },
      einsaetze: { label: 'Storico interventi', title: 'Storico interventi', lede: 'Tutti gli interventi attuali e storici con ora di inizio, stato, origine, stato del rapporto e ultima modifica.' },
      divera: {
        label: 'Allarmi',
        title: 'Ricezione allarmi',
        lede: 'Stato della fonte allarmi configurata, allarmi in arrivo non assegnati, aggiornamento e test di connessione.',
        tip: 'Il «pool» sono gli allarmi rilevati da Divera non ancora assegnati. «Aggiorna» li recupera di nuovo dal server.',
      },
      traccar: {
        label: 'Localizzazione veicoli',
        title: 'Localizzazione veicoli',
        lede: 'Stato della fonte di localizzazione configurata, veicoli trasmittenti, segnale più recente e test di connessione.',
        tip: 'GPS live dei veicoli tramite Traccar. «connesso» = collegamento attivo; «online» = veicoli che stanno trasmettendo.',
      },
      statistik: {
        label: 'Export statistiche',
        title: 'Export statistiche',
        lede: 'Feed di dati in sola lettura di tutti gli interventi per analisi esterne (ad es. statistica annuale).',
      },
      objekte: {
        label: 'Oggetti e piani',
        title: 'Oggetti e piani',
        lede: 'Oggetti registrati e i loro piani (modulo, versione, stato). Solo per visualizzazione.',
        tip: 'I piani sono fogli PDF per oggetto, ordinati per modulo FKS: Modul 1 panoramica, 2 accesso, 3 interno, 2-3 combinato, 6 piani degli edifici.',
      },
      geodaten: {
        label: 'Geodati',
        title: 'Geodati e simboli',
        lede: 'Dati di riferimento caricati: livelli GeoJSON, set di simboli e PDF. Solo per visualizzazione.',
        tip: 'Dati di riferimento propri della stazione (idranti, condotte …). «Set di dati» = un livello, «Features» = oggetti contenuti, «Fonte» = da dove proviene.',
      },
      system: { label: 'Sistema e manutenzione', title: 'Sistema e manutenzione', lede: 'Stato e manutenzione: versione, database, inventario, archiviazione e la cache offline di questo dispositivo.' },
      sicherung: { label: 'Backup', title: 'Backup', lede: 'Salva la configurazione su file o ripristina un file salvato.' },
    },
    erfassung: {
      cardTitle: 'Poster di rilevamento',
      body: 'Chi scansiona il poster in magazzino può registrare presenze, materiale e note di un intervento recente — senza login, senza formazione.',
      stateLabel: 'Rilevamento',
      stateOn: 'attivo',
      stateOff: 'disattivato',
      enableBtn: 'Attivare & generare il token',
      rotateBtn: 'Ruotare il token',
      rotateMsg: 'Generare un nuovo token? Tutti i poster stampati diventano subito non validi.',
      rotated: 'Nuovo token generato — ristampare il poster.',
      disableBtn: 'Disattivare',
      disableMsg: 'Disattivare il rilevamento? Il codice QR su tutti i poster smetterà di funzionare.',
      disabled: 'Rilevamento disattivato.',
      printBtn: 'Poster in PDF (A4)',
      posterHead: 'Registrare l’intervento',
      posterStep1: 'Scansionare il codice QR con il telefono',
      posterStep2: 'Toccare l’intervento e scegliere il proprio nome',
      posterStep3: 'Spuntare i presenti, inserire materiale e note',
      failed: 'Azione non riuscita',
      sheetBtn: 'Foglio di rilevamento in PDF (A4)',
      sheetCardTitle: 'Foglio di rilevamento (carta)',
      sheetCardBody: 'Il gemello cartaceo del rapporto digitale: stessi campi, stesso ordine — per l’intervento completamente analogico. Generato da organico, materiale e configurazione attuali; fotografare i fogli compilati (diario/allegato) e riportarli nell’app.',
      sheetHead: 'Foglio di rilevamento intervento',
      sheetIncident: 'Intervento',
      sheetAdresse: 'Indirizzo / oggetto',
      sheetEigentuemer: 'Proprietario / responsabile',
      sheetGerettete: 'Salvati (persone / animali)',
      sheetZeiten: 'Orari di allarme / partenza',
      sheetPartner: 'Organizzazioni partner',
      sheetPartnerOther: 'Altre',
      sheetRueckmeldung: 'Rapporto alla centrale',
      sheetZeit: 'Ora',
      sheetDate: 'Data',
      sheetAlarm: 'Allarme',
      sheetEnde: 'Fine intervento',
      sheetKontakt: 'Persona di contatto',
      sheetSignatures: 'Visto',
      sheetName: 'Nome',
      sheetEl: 'Capo intervento',
      sheetKdt: 'Comandante',
      sheetPersonen: 'Presenze (spuntare, da–a se necessario)',
      sheetMaterial: 'Materiale (indicare le quantità)',
      sheetNotizen: 'Breve rapporto / lavori eseguiti',
      hint: 'Il link copre gli interventi in corso e non ancora rapportati; quelli rapportati scompaiono dopo alcune ore (12 h di default, alarms.captureWindowHours).',
    },
    statistik: {
      body: 'Export in sola lettura di tutti gli interventi come record JSON piatti (metadati, orari, presenze da–a, materiale, stato del rapporto) — per analisi esterne come la statistica annuale. Nessun diritto di scrittura, nessun accesso alla mappa o all’amministrazione.',
      stateLabel: 'Export',
      stateOn: 'attivo',
      stateOff: 'disattivato',
      enableBtn: 'Attivare e generare token',
      rotateBtn: 'Ruotare il token',
      rotateMsg: 'Generare un nuovo token? Tutti gli strumenti di analisi collegati dovranno essere riconfigurati.',
      rotated: 'Nuovo token generato.',
      disableBtn: 'Disattivare',
      disableMsg: 'Disattivare l’export statistiche? Gli strumenti collegati non riceveranno più dati.',
      disabled: 'Export disattivato.',
      failed: 'Azione non riuscita',
      exampleLabel: 'Esempio di richiesta',
      tokenLabel: 'Token',
      hint: 'Mantenere segreto il token — concede accesso in lettura a tutti i dati degli interventi, nomi inclusi. Da passare allo strumento di analisi come header X-Stats-Token (oppure ?t=).',
    },
    incidentHistory: {
      loading: 'Caricamento interventi…', error: 'Impossibile caricare gli interventi.', search: 'Cerca titolo, indirizzo o origine…',
      none: 'Nessun intervento.', noMatches: 'Nessun intervento corrisponde.', started: 'Inizio', incident: 'Intervento', status: 'Stato',
      source: 'Origine', report: 'Rapporto', updated: 'Modificato', open: 'aperto', closed: 'concluso', complete: 'completo', incomplete: 'in sospeso',
    },
    autosave: {
      retry: 'Riprova',
      saving: 'Salvataggio…',
      pending: 'Salvataggio delle modifiche…',
      saved: 'Salvato',
      sessionExpired: 'Sessione scaduta — accedi di nuovo.',
      saveFailed: 'Salvataggio fallito',
      loadFailed: 'Impossibile caricare la configurazione',
    },
    usageBar: { aria: '{pct}% occupato' },
    identity: {
      appName: 'Nome dell’app',
      appNameTip: 'Mostrato nella barra del titolo, nel login e nell’aiuto. Vuoto = «KP Front».',
      accentColor: 'Colore d’accento',
      accentColorHint: 'Colore del marchio (login / splash)',
      accentColorTip: 'Colore del marchio del corpo; permea l’intero sistema di colori --accent (login, splash, accenti).',
      pickAccentColor: 'Scegli colore d’accento',
      language: 'Lingua',
      languageHint: 'Lingua dell’interfaccia per l’intero corpo',
      languageTip: 'Lingua di tutti i testi dell’interfaccia. Vale per l’intero corpo (un deployment = una lingua); viene applicata al caricamento dell’app. fr/it sono tradotti solo in parte e altrimenti ripiegano sul tedesco.',
      pickLanguage: 'Scegli lingua',
      kommandant: 'Comandante',
      kommandantTip: 'Nome del comandante — prestampato accanto alla riga di firma «Kommandant» sul rapporto d’intervento. Vuoto = solo la dicitura.',
    },
    map: {
      centerLon: 'Centro — longitudine (lon)',
      centerLonTip: 'Longitudine (WGS84) dell’avvio della carta, prima che sia scelto un intervento.',
      centerLat: 'Centro — latitudine (lat)',
      centerLatTip: 'Latitudine (WGS84) dell’avvio della carta, prima che sia scelto un intervento.',
      zoom: 'Zoom',
      zoomTip: 'Livello di zoom iniziale della carta (più alto = più vicino; ~16 mostra un’estensione di quartiere).',
    },
    doctrine: {
      defaultFunkkanal: 'Canale radio (predefinito)',
      defaultFunkkanalTip: 'Canale radio preimpostato di un nuovo intervento.',
      contactInterval: 'Intervallo di contatto (min)',
      contactIntervalTip: 'Intervallo di contatto ARA; una volta trascorso, il contatto è dovuto (ambra).',
      contactGrace: 'Tolleranza (s)',
      contactGraceTip: 'Secondi dopo il contatto dovuto prima dell’allarme di ritardo.',
    },
    backup: {
      title: 'Backup',
      caption: 'Salva la configurazione su file o ripristina un file salvato. L’importazione la sostituisce completamente (senza le integrazioni env).',
      export: 'Esporta configurazione',
      import: 'Importa configurazione',
      lastChangedBy: 'Ultima modifica di {name} il {date}',
      lastChanged: 'Ultima modifica il {date}',
      notJson: 'Il file non è un JSON valido.',
      notConfig: 'Il file non contiene una configurazione valida.',
      replaceConfirm: 'Questo file sostituisce completamente la configurazione attuale. Quella precedente viene prima scaricata come backup. Continuare?',
      imported: 'Configurazione importata.',
      invalidSchema: 'Configurazione non valida (422) — il file non corrisponde allo schema.',
      importFailed: 'Importazione fallita.',
    },
    common2: {
      cancel: 'Annulla',
      save: 'Salva',
      saving: 'Salvataggio…',
      create: 'Crea',
      edit: 'Modifica',
      remove: 'Rimuovi',
      notAvailable: 'non disponibile',
      unknownError: 'Errore sconosciuto',
    },
    infoTip: { prefix: 'Info: {label}' },
    stringList: {
      addPlaceholder: 'Aggiungi…',
      removeItem: 'Rimuovi {item}',
    },
    fleet: {
      filterPlaceholder: 'Cerca simbolo …',
      loading: 'Caricamento della libreria dei simboli …',
      noMatches: 'Nessun simbolo corrisponde alla ricerca.',
      noAttributes: 'Nessun campo.',
      fieldTitle: 'Titolo',
      fieldMeaningTitle: 'Campi speciali',
      guideTitle: 'Spiegazione di campi e proprietà',
      fieldGlossary: {
        Titel: 'Etichetta visibile del veicolo.', Status: 'Stato dipendente dal contesto, ad es. salvato o valvola aperta/chiusa.',
        Stoff: 'Nome della sostanza pericolosa.', 'UN-Nr': 'Numero ONU a quattro cifre.', Einheit: 'Organizzazione o unità impiegata.',
        Name: 'Persona dall’organico.', Funktion: 'Compito di comando.', Fahrer: 'Autista dall’organico.', Typ: 'Tipo di attrezzatura o configurazione.',
      },
      propsLabel: 'Proprietà',
      controls: {
        rotation: 'Ruotabile',
        rotation2: 'Seconda rotazione',
        count: 'Numero',
        floor: 'Piano',
        floorRange: 'Intervallo di piani',
        spread: 'Propagazione',
      },
      propertiesMeaningTitle: 'Proprietà',
      controlGlossary: {
        rotation: 'Il simbolo può essere ruotato dopo il posizionamento.', rotation2: 'È disponibile un secondo angolo di direzione indipendente.',
        count: 'Più elementi uguali sono gestiti come quantità.', floor: 'Il simbolo può essere assegnato a un piano.',
        floorRange: 'Il simbolo può coprire un intervallo di piani.', spread: 'È possibile mostrare direzione ed estensione della propagazione.',
      },
      listsMeaningTitle: 'Origine e lista di scelta.',
      noConfiguredLists: 'Nessuna lista personalizzata è configurata per questa stazione. Nome e autista provengono dall’organico; gli altri campi restano liberi.',
      configuredLists: '“Configurato” mostra i suggerimenti della stazione e “Dall’organico” usa il personale. Il testo libero resta possibile.',
      rosterField: 'Dall’organico',
      rosterBadgeHint: 'compilato dall’organico',
      configuredBadge: 'Configurato',
      configuredBadgeHint: 'impostato nella configurazione della stazione',
      freitextBadge: 'Testo libero',
      freitextBadgeHint: 'nessun elenco — l’operatore digita liberamente',
      freitextValue: 'inserimento libero',
    },
    members: {
      add: 'Aggiungi membro',
      addCaption: 'Nome utente per accedere, nome visualizzato sulle tessere di login. PIN: esattamente {n} cifre.',
      username: 'Nome utente',
      usernamePlaceholder: 'es. fu',
      displayName: 'Nome visualizzato',
      displayNamePlaceholder: 'es. Felix Muster',
      role: 'Ruolo',
      roleViewer: 'Osservatore',
      roleEditor: 'Editore',
      colorLabel: 'Colore',
      colorOptional: 'facoltativo',
      pickColor: 'Scegli colore',
      pinLabel: 'PIN',
      pinDigits: '{n} cifre',
      title: 'Membri',
      caption: 'Chi può accedere e con quale ruolo. I membri vengono disattivati, mai eliminati (la cronologia resta intatta).',
      loading: 'Caricamento membri…',
      none: 'Nessun membro.',
      colName: 'Nome',
      colUsername: 'Nome utente',
      colRole: 'Ruolo',
      colStatus: 'Stato',
      colLastLogin: 'Ultimo accesso',
      colActions: 'Azioni',
      active: 'Attivo',
      inactive: 'Inattivo',
      toViewer: '→ Osservatore',
      toEditor: '→ Editore',
      deactivate: 'Disattiva',
      reactivate: 'Riattiva',
      resetPin: 'Reimposta PIN',
      guardSelf: 'Non puoi modificare o disattivare il tuo account.',
      guardLastCmd: 'L’ultimo account editor attivo non può essere disattivato o declassato.',
      guardSelfRole: 'Non puoi modificare il tuo ruolo.',
      guardLastCmdRole: 'L’ultimo account editor attivo non può essere declassato.',
      guardSelfDeactivate: 'Non puoi disattivare il tuo account.',
      guardLastCmdDeactivate: 'L’ultimo account editor attivo non può essere disattivato.',
      guardLabel: 'Azioni protette per {name}',
      newPinPrompt: 'Nuovo PIN per {name} ({n} cifre):',
      pinInvalid: 'Il PIN deve avere esattamente {n} cifre.',
    },
    roster: {
      sourceHint: 'Colonne: name (obbligatoria), rank (facoltativa). UTF-8, separato da virgole, con intestazione. Le identità provider sono gestite dalla sincronizzazione.',
      addPerson: 'Aggiungi persona',
      addPersonCaption: 'Inserisci il nome della persona.',
      name: 'Nome',
      namePlaceholder: 'es. Meier Hans',
      csvImport: 'Importa CSV',
      csvTemplate: 'Scarica CSV di esempio',
      importing: 'Importazione…',
      imported: '{n} importati',
      skipped: '{n} saltati',
      syncDivera: 'Sincronizza l’effettivo con Divera',
      diveraNotConfigured: 'Divera non configurato',
      syncProvider: 'Sincronizza con {provider}',
      providerNotConfigured: 'Nessuna fonte personale configurata · CSV e inserimento manuale disponibili',
      title: 'Persone registrate',
      caption: 'Anagrafica del corpo. Le persone vengono disattivate, mai eliminate (la cronologia resta intatta).',
      showInactive: 'Mostra inattivi',
      loading: 'Caricamento effettivo…',
      none: 'Nessuna persona registrata.',
      colName: 'Nome',
      colSource: 'Fonte',
      colStatus: 'Stato',
      colActions: 'Azioni',
      sourceDivera: 'Divera',
      sourceManual: 'manuale',
      active: 'Attivo',
      inactive: 'Inattivo',
      deactivate: 'Disattiva',
      reactivate: 'Riattiva',
    },
    data: {
      testConnection: 'Testa connessione',
      testing: 'Test…',
      testOk: 'OK',
      testOff: 'non configurato',
      testErr: 'Errore',
      genericError: 'Errore',
      stateConnected: 'connesso',
      stateUnavailable: 'non disponibile',
      stateNotConfigured: 'non configurato',
      poolLoading: 'Caricamento pool…',
      poolCount: '{n} allarme nel pool',
      poolCountPlural: '{n} allarmi nel pool',
      poolUnavailable: 'Pool non disponibile',
      refresh: 'Aggiorna',
      refreshing: 'Aggiornamento…',
      lastAlarm: 'Ultimo allarme',
      alarmFallback: 'Allarme {id}',
      noneInPool: 'nessuno nel pool',
      address: 'Indirizzo',
      vehiclesLoading: 'Caricamento veicoli…',
      vehicleCount: '{n} veicolo',
      vehicleCountPlural: '{n} veicoli',
      onlineCount: '{n} online',
      positionsUnavailable: 'Posizioni non disponibili',
      server: 'Server',
      freshestSignal: 'Segnale più recente',
      colDevice: 'Dispositivo',
      colStatus: 'Stato',
      colLastSignal: 'Ultimo segnale',
      colSpeed: 'Velocità',
      online: 'online',
      offline: 'offline',
      unknown: 'sconosciuto',
      noPlans: 'nessun piano',
      objectsLoading: 'Caricamento oggetti…',
      objectsUnavailable: 'Oggetti non disponibili.',
      objectsError: 'Impossibile caricare gli oggetti.',
      objectsNone: 'Nessun oggetto registrato.',
      objectsHintBefore: 'Gli oggetti e i loro piani vengono caricati lato server — tramite ',
      objectsHintAfter: ' dal repository dati privato. Qui appaiono poi per la visualizzazione.',
      mapLoading: 'Caricamento carta…',
      noLocation: 'nessun luogo',
      geodataLoading: 'Caricamento dati…',
      geodataUnavailable: 'Dati non disponibili.',
      geodataError: 'Impossibile caricare i dati.',
      geodataNone: 'Nessun dato di riferimento caricato.',
      geodataHintBefore: 'Idranti, catasto delle condotte e altri livelli vengono caricati lato server — tramite ',
      geodataHintAfter: ' dal repository dati privato. Il GeoJSON deve essere in WGS84.',
      colDataset: 'Set di dati',
      colType: 'Tipo',
      colVersion: 'Versione',
      colUpdated: 'Stato',
      colFeatures: 'Features',
      colSource: 'Fonte',
      justNow: 'proprio ora',
      relMin: '{n} min fa',
      relHour: '{n} h fa',
    },
    objectsMap: {
      showAll: 'Mostra tutti',
      showAllTitle: 'Mostra tutti gli oggetti',
    },
    modules: {
      empty: 'Nessun modulo configurato — si applicano i moduli standard forniti.',
      summary: '{modules} moduli · {objects} oggetti · {plans} piani',
      coverage: '{covered}/{total} oggetti',
      code: 'Codice',
      title: 'Titolo',
      order: 'Ordine',
      orientation: 'Orientamento',
      orientationPortrait: 'Verticale',
      orientationLandscape: 'Orizzontale',
      detection: 'Regola di riconoscimento',
      detectionNone: 'nessuna regola',
      combinedWith: 'Combinato con',
      familyBadge: 'Famiglia',
      familyHint: 'genera sotto-moduli dal nome file',
      viewerBadge: 'Sola vista',
      viewerHint: 'PDF senza disegno',
      objectsTitle: 'Oggetti e piani',
    },
    layers: {
      filterPlaceholder: 'Cerca livello …',
      loading: 'Caricamento …',
      empty: 'Nessun livello di riferimento configurato.',
      noMatches: 'Nessun livello corrisponde alla ricerca.',
      summary: '{total} livelli · {loaded} caricati · {missing} mancanti · {external} esterni',
      statusLoaded: 'Caricato',
      statusMissing: 'Non caricato',
      statusExternal: 'Fonte esterna',
      features: '{n} elementi',
      updated: 'Aggiornato {date}',
      group: 'Gruppo',
      opacity: 'Opacità',
      colorDay: 'Colore giorno',
      colorNight: 'Colore notte',
      symbol: 'Simbolo',
      geometry: 'Geometria',
      geometryPoint: 'Punti',
      geometryLine: 'Linee',
      maxZoom: 'Zoom max',
      attribution: 'Fonte',
      source: 'Fonte',
      datasetsTitle: 'Set di dati caricati',
    },
    branding: {
      logo: 'Logo',
      logoHint: 'Schermata di accesso',
      favicon: 'Favicon',
      faviconHint: 'Scheda del browser',
      upload: 'Scegli immagine',
      uploading: 'Caricamento…',
      remove: 'Rimuovi',
      removeConfirm: 'Rimuovere questa immagine?',
      uploadFailed: 'Caricamento fallito',
      removeFailed: 'Rimozione fallita',
      iconsNote: 'Le icone dell’app / schermata iniziale vengono impostate al build (separatamente).',
    },
    system: {
      loading: 'Caricamento dati di sistema…',
      refresh: 'Aggiorna',
      liveSnapshot: 'Stato sistema in tempo reale',
      updatedAt: 'Aggiornato alle {time}',
      healthSummary: 'Stato del sistema',
      server: 'Server',
      reachable: 'raggiungibile',
      error: 'Impossibile caricare i dati di sistema.',
      notAvailable: 'non disponibile',
      version: 'Versione',
      versionTip: 'Stato di build di questa installazione. «Commit» = stato Git del server, «Ambiente» = esercizio produttivo o di sviluppo.',
      commit: 'Commit',
      branch: 'Branch',
      environment: 'Ambiente',
      production: 'Produzione',
      development: 'Sviluppo',
      database: 'Database',
      databaseTip: 'Segnale di vita del database: una semplice query di test. «OK» = il server raggiunge il database.',
      ok: 'OK',
      error2: 'Errore',
      inventory: 'Inventario',
      inventoryTip: 'Record nel database di questa installazione.',
      incidentsTotal: 'Interventi (totale)',
      incidentsOpen: 'Interventi (aperti)',
      personnelActive: 'Effettivo (attivo)',
      users: 'Utenti',
      referenceData: 'Dati di riferimento',
      domain: 'Ambito',
      status: 'Stato',
      active: 'attivo',
      personnelProvider: 'Fonte personale',
      alarmProvider: 'Fonte allarmi',
      vehicleProvider: 'Fonte localizzazione',
      configured: 'configurato',
      notConfigured: 'non configurato',
      connectors: 'Connessioni',
      connectorsTip: 'Tutto ciò a cui è collegata questa installazione — provider (Divera/Traccar) e tutti i consumatori/produttori — sola lettura. Configurazione tramite variabili d’ambiente o l’area admin (registrazione, statistiche).',
      connection: 'Connessione',
      directionIn: 'in entrata',
      directionOut: 'in uscita',
      connOnline: 'online',
      connOffline: 'offline',
      connLastSeen: 'Ultimo segnale: {time}',
      connPrintRelay: 'Stampante di caserma (agente di stampa)',
      connCapture: 'Poster di registrazione (QR)',
      connStats: 'Esportazione statistiche',
      connDiveraWebhook: 'Webhook Divera',
      connAlarmWebhook: 'Ingresso allarmi generico',
      connPush: 'Web push (allarme)',
      connStt: 'Riconoscimento vocale',
      storage: 'Archiviazione',
      storageTip: 'L’archivio oggetti del server (foto, piani, file di riferimento) e l’occupazione del disco sottostante.',
      mediaUsed: 'Occupato (media)',
      files: 'File',
      directory: 'Directory',
      diskUsed: 'Disco occupato',
      diskUnavailable: 'Occupazione del disco non disponibile.',
      free: 'Libero: {size}',
      offlineCache: 'Cache offline (questo dispositivo)',
      offlineCacheTip: 'La cache offline (service worker) di questo dispositivo: carte, piani e file dell’app salvati per l’uso senza copertura. I numeri valgono solo per QUESTO dispositivo, non per il server.',
      cacheReading: 'Lettura della cache…',
      cacheUnavailable: 'Non disponibile in questo browser.',
      usedQuota: 'Occupato / contingente',
      storageEstimateUnavailable: 'Stima dell’archiviazione non disponibile.',
      cacheStorage: 'Archivio cache',
      cacheSummary: '{caches} · {entries} voci',
      cache: 'Cache',
      entries: 'Voci',
      clearCaches: 'Svuota le cache',
      clearing: 'Svuotamento…',
      cleared: 'svuotato',
      clearConfirm: 'Svuotare la cache offline su QUESTO dispositivo?\n\nLe carte, i piani e i file dell’app salvati verranno eliminati. Al prossimo caricamento verranno recuperati di nuovo dal server (serve internet). Accesso e dati del server restano intatti.',
      offlineCacheCaption: 'Manutenzione locale: svuota solo la cache offline su QUESTO dispositivo. Al prossimo caricamento i file vengono recuperati di nuovo. Accesso e server restano intatti.',
    },
  },
}
