// Italian copy · Anwesenheit, Anrückend, Zeitplan and Schichten.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/anwesenheit.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'anwesenheit' | 'anrueckend' | 'zeitplan' | 'schichten'

export const anwesenheitCopy: Localizable<Pick<Copy, Keys>> = {
  anwesenheit: {
    title: 'Presenza',
    summary: '{present} presenti',
    summaryLeft: '{left} andati via',
    reload: 'Ricarica effettivo',
    loading: 'Caricamento …',
    searchPlaceholder: 'Cerca …',
    ortScene: 'Sul posto',
    ortStation: 'Rimessa',
    ortToScene: 'Manda {name} sul posto',
    ortToStation: 'Metti {name} in rimessa',
    logOrtScene: '{name} sul posto',
    logOrtStation: '{name} in rimessa',
    summaryOrt: '{scene} sul posto · {station} rimessa',
    statusFrei: 'non presente',
    filterLabel: 'Filtra',
    statusAll: 'Tutti',
    statusFilterLabel: 'Filtra per stato',
    noteOnly: 'Solo con osservazione',
    statusPresent: 'presente',
    statusLeft: 'andato via',
    loadFailedTitle: 'Impossibile caricare l’effettivo.',
    loadFailedHint: 'Offline o server non raggiungibile. L’ultimo elenco caricato resta disponibile.',
    emptyTitle: 'Nessun effettivo registrato.',
    emptyHint: 'L’effettivo si registra o si sincronizza nell’amministrazione.',
    emptyHintSync: 'Sincronizza l’effettivo da {provider}.',
    retry: 'Riprova',
    lockedTitle: 'In una squadra – annunciare prima l’uscita con «Annuncia uscita»',
    notInDivera: 'Non più nell’elenco',
    notInSource: 'Non più in {provider}',
    weg: 'via',

    noteLabel: 'Osservazione',
    notePlaceholder: 'p. es. autista autobotte',
    logNote: '{name} – osservazione: {note}',
    logPresent: '{name} presente',
    logPresentAgain: '{name} di nuovo presente',
    logLeft: '{name} andato',
    logGuestAdded: '{name} registrato come persona aggiuntiva',
    logGuestAddedAs: '{name} registrato come persona aggiuntiva – {role}',
    addGuest: 'Aggiungi «{name}» come ospite',
    guestBadge: 'Ospite',
    removeGuest: 'Elimina la persona',
    logPresentAs: '{name} presente – {role}',
    logRoleGroup: 'Sotto {role}: {list}',
    logRoleGroupTrupp: 'In squadra: {list}',
    undoTap: 'Annulla l’ultimo tocco',
    redoTap: 'Ripristina il tocco',
    undone: 'Presenza annullata: {names}',
    redone: 'Presenza ripristinata: {names}',
    roleEinsatzleiter: 'Capo intervento',
    roleEinsatzleiterShort: 'CI',
    roleEinsatzleiterStv: 'Sostituto capo intervento',
    roleEinsatzleiterStvShort: 'Sost. CI',
    roleFahrer: 'Autista {vehicle}',
    roleBedienung: 'Operatore {symbol}',
    roleOffizier: 'Ufficiale {funktion}',
    roleAtemschutz: 'ARA',
    roleTrupp: 'Squadra',
    // la funzione del caposquadra — UN solo token con trattino, così resta univoco nell’elenco di
    // funzioni separate da virgole («ARA-CS, Autista TLF»).
    roleLeader: '{role}-CS',
    roleOffizierPlain: 'Ufficiale',
    alreadyBooked: '{role}',
    conflictUnderPa: '{name} è sotto ARA – squadra {trupp}.',
    conflictInTrupp: '{name} è nella squadra {trupp}.',
    statusUnderPa: 'sotto ARA',
    statusInTrupp: 'in una squadra',
    conflictElInTrupp: '{name} è capo intervento e allo stesso tempo nella squadra {trupp}.',
    conflictLeft: '{name} è registrato come «andato».',
    presentOnlyOn: 'Solo presenti – tocca per tutto il corpo',
    presentOnlyOff: 'Tutto il corpo – tocca per i soli presenti',
    onlyPresent: 'Solo presenti',
    rankFilterLabel: 'Filtra per grado',
    rankAll: 'Tutti',
    backAgain: 'Di ritorno',
    von: 'da',
    bis: 'a',
    addBlock: 'Nuovo intervallo da adesso',
    blockSplit: '{name}: nuovo intervallo – quello in corso è stato chiuso',
    blockRemoved: 'Intervallo di {name} eliminato',
    blockRemove: 'Elimina l\'intervallo',
    blocksTitle: 'Presenza – {name}',
    blocksSection: 'Intervalli registrati',
    blocksNone: 'Non ancora stato presente.',
    blocksHint: 'Ogni riga è una presenza reale di questa persona. Correggi qui se una timbratura è sbagliata.',
    openBlocks: 'Apri la presenza di {name}',
    openBlocksNote: 'Apri la presenza di {name} · osservazione registrata',
    statusNote: 'Osservazione',
    stillHere: 'ancora qui',
    running: 'in corso',
    ended: 'terminato',
    flip: 'commuta',
    viewList: 'Presenza',
    viewPlan: 'Pianificazione',
    viewBands: 'Turni',
    viewLabel: 'Vista',
  },
  anrueckend: {
    title: 'In arrivo',
    sourceBare: 'Divera',
    coming: (n: number) => (n === 1 ? '1 arriva' : `${n} arrivano`),
    notComing: (n: number) => (n === 1 ? '1 non arriva' : `${n} non arrivano`),
    here: (n: number) => (n === 1 ? '1 presente' : `${n} presenti`),
    notComingGroup: (n: number) => `Non arriva (${n})`,
    notComingWord: 'non arriva',
    checkIn: 'presente',
    checkInLabel: '{name} è qui – registrare come presente',
    allHere: 'Tutti quelli che hanno annunciato di venire sono registrati.',
    unmapped: (n: number) => (n === 1 ? '1 risposta senza voce nell’effettivo' : `${n} risposte senza voce nell’effettivo`),
    hint: 'Una risposta Divera non è una presenza – solo «presente» registra qualcuno.',
    collapse: 'Chiudi «In arrivo»',
    expand: 'Apri «In arrivo»',
  },
  zeitplan: {
    title: 'Pianificazione',
    summary: '{planned} pianificati · {present} presenti',
    summaryEmpty: 'Niente di pianificato',
    add: 'Turno',
    from: 'da',
    to: 'a',
    remove: 'Elimina il turno',
    removed: 'Turno di {name} eliminato',
    added: 'Turno pianificato per {name}',
    moved: 'Turno di {name} spostato',
    conflict: 'Doppia assegnazione – due turni nello stesso momento',
    conflictTitleOne: 'Una persona è assegnata due volte.',
    conflictTitleMany: '{n} persone sono assegnate due volte.',
    conflictWho: '{name} · {from}–{to}',
    conflictMore: '… e altre {n}',
    conflictFix: 'Tocca una delle due assegnazioni e mettila su «disponibile» – l\'orario stesso rimane.',
    conflictShort: 'doppia assegnazione',
    brokenShift: 'Questo turno finisce prima di iniziare – tocca per correggere',
    now: 'adesso',
    coverage: 'Copertura',
    coverageHint: 'Tre linee: grigio disponibile, blu assegnato, verde realmente presente – dove la linea verde cala c\'è il buco.',
    coverageExpand: 'Mostra i numeri – quanti sono disponibili, assegnati e presenti',
    coverageCollapse: 'Nascondi i numeri',
    planned: 'disponibile',
    actual: 'presente',
    emptyTitle: 'Nessun turno pianificato.',
    emptyHint: 'Pianifica per ogni persona da quando a quando è disponibile. La pianificazione non modifica le presenze – quelle si spuntano sempre nell\'elenco presenze.',
    legendHint: 'Vuoto = disponibile · pieno = assegnato · verde = realmente presente',
    print: 'Stampa la pianificazione',
    sheetSchichtplan: 'Piano dei turni …',
    sheetVerfuegbarkeiten: 'Disponibilità …',
    sheetSchichtplanTitle: 'Piano dei turni',
    sheetVerfuegbarkeitenTitle: 'Disponibilità',
    peopleCount: (n: number) => (n === 1 ? '1 persona' : `${n} persone`),
    bandsCount: (n: number) => (n === 1 ? '1 turno' : `${n} turni`),
    sheetContent: '{people} · stato {t}',
    sheetContentBands: '{people} · {bands} · stato {t}',
    sheetSchichtplanHint: 'I turni in colonna, i nomi in riga, le spunte in mezzo – il formulario di condotta come lo conosce il corpo.',
    sheetVerfuegbarkeitenHint: 'Chi può da quando a quando, indipendentemente da ogni turno – anche tutti quelli che non ne hanno nessuno.',
    pdf: 'In PDF',
    paperMenu: 'Su carta',
    printFailed: 'Impossibile stampare la pianificazione.',
    who: 'Chi',
    editTitle: 'Turni – {name}',
    plannedSection: 'Disponibilità e assegnazione',
    actualSection: 'Realmente presente',
    actualHint: 'Proviene dalle presenze e lì si registra – la pianificazione non la modifica.',
    actualNone: 'Non ancora stato presente.',
    plannedNone: 'Nessuna disponibilità registrata.',
    addShift: 'Aggiungi un turno',
    stillHere: 'ancora qui',
    running: 'in corso',
    ended: 'terminato',
    flip: 'commuta',
    done: 'Fatto',
    fromStart: 'dall\'inizio',
    sheetHint: 'Regola gli orari qui · commuta lo stato a destra · si elimina solo qui.',
    laneHint: 'Trascinare registra la disponibilità · toccare una barra assegna la persona · trascinare sposta la barra · tenere premuto apre i turni',
    laneHintShow: 'Mostra i comandi',
    laneHintHide: 'Nascondi i comandi',
    available: 'disponibile',
    confirmed: 'assegnato',
    toggleHint: 'Toccando diventa «{state}»',
    zoomIn: 'Periodo più breve',
    zoomOut: 'Periodo più lungo',
    horizonUntil: 'fino a {t}',
    horizon: 'Periodo',
    openFor: 'Apri i turni di {name}',
    planAt: 'Pianifica un turno per {name}',
    dragFrom: 'Trascina l\'inizio',
    editEntry: 'Modifica …',
    dragTo: 'Trascina la fine',
  },
  schichten: {
    title: 'Turni',
    who: 'Chi',
    addBand: 'Definisci un turno',
    addBandFirst: 'Definisci il primo turno',
    emptyTitle: 'Nessun turno.',
    emptyHint: 'Crea le fasce che vuoi coprire – poi basta toccare per ogni persona.',
    emptyAxisHint: 'Oppure disegna liberamente per persona nella pianificazione.',
    sheetAddTitle: 'Crea un turno',
    sheetEditTitle: 'Modifica il turno',
    labelField: 'Nome',
    labelPlaceholder: 'Mattino',
    sheetHint: 'Il turno è creato per tutto il corpo. Ogni cella parte vuota.',
    create: 'Crea',
    save: 'Salva',
    removeBand: 'Elimina il turno',
    removeBandHint: 'L\'eliminazione toglie solo la colonna – gli orari assegnati restano nella pianificazione come orari liberi.',
    removedBand: 'Turno «{label}» eliminato',
    moveTitle: 'Spostare anche gli orari?',
    moveMsg: '{n} persone sono assegnate ai vecchi orari. I loro orari devono seguire?',
    moveYes: 'Fai seguire',
    moveNo: 'Solo il turno',
    countsAria: '{available} disponibili, {planned} pianificati',
    available: 'disponibile',
    confirmed: 'pianificato',
    ownTimes: 'orari propri fuori da ogni turno: {times}',
    ownTimesMore: '{first} +{n}',
    deviating: '{name}: {from}–{to} invece di {bandFrom}–{bandTo}',
    cellAria: '{name} in {band}',
    cellFrom: 'da {t}',
    cellUntil: 'fino a {t}',
    partial: 'parzialmente',
    partialHint: 'Non tutti coprono l\'intero turno.',
    resolveTitle: 'In parte disponibile, in parte pianificato',
    resolveMsg: '{name} è in parte assegnato a {band} e in parte solo disponibile. Cosa deve valere per questa fascia?',
    resolveGap: 'Il resto del turno non è coperto da questa persona – questo non cambia.',
    splitTitle: 'Verrà diviso',
    splitChanges: 'cambia',
    splitKeeps: 'resta {state}',
    splitNote: 'Cambia solo la parte all\'interno del turno; fuori resta tutto com\'è.',
    crossTitle: 'Va oltre il turno',
    crossMsg: 'Questo intervallo di {name} va oltre {band}. Cosa deve valere per questa fascia?',
    resolveAvailable: 'Tutto su disponibile',
    resolveConfirmed: 'Tutto su pianificato',
    resolveCancel: 'Annulla',
    conflict: 'Doppia assegnazione – due turni nello stesso momento',
    editEntry: 'Modifica …',
    scrollHint: 'Scorri in orizzontale per altri turni',
  },
}
