// Italian copy · the Trupps board (Atemschutz) and line decorations.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/atemschutz.ts.

import type { Copy, Localizable } from '../index'

export const atemschutzCopy: Localizable<Pick<Copy, 'atemschutz' | 'lineDecor'>> = {
  atemschutz: {
    title: 'Sorveglianza autoprotezione',
    // titolo della tavola nell'app completa — porta entrambe le sezioni (vedi de/atemschutz.ts)
    boardTitle: 'Squadre',
    // il titolo troncato apre i dati dell'intervento (09.09., vedi de/atemschutz.ts)
    headDetailOpen: 'Mostra i dati dell\'intervento',
    headDetailTitle: 'Intervento',
    sectionAtemschutz: 'ARA',
    sectionAtemschutzEmpty: 'Al momento nessuna squadra è sotto ARA.',
    sectionPlain: 'Altre squadre',
    kindLabel: 'Tipo di squadra',
    kindAtemschutz: 'Sotto ARA',
    kindPlain: 'Senza ARA',
    asMark: 'ARA',
    empty: 'Ancora nessuna squadra in sorveglianza.',
    emptyHint: 'Crea una squadra per avviare la sorveglianza.',
    newTrupp: 'Annuncia squadra',
    shareLink: 'Cedi la sorveglianza',
    shareLinkOn: 'Cedi la sorveglianza – un link è attivo',
    linkReentryHint: 'Il link riporta a questa tavola – se la pagina viene chiusa per errore, basta aprire di nuovo il codice QR.',
    /** the «+ Trupp» tab on the handed-over phone board (AtemschutzView · focusMode) */
    liteNewTab: 'Squadra',
    /** the three-section stack on ANY phone (TruppForm · stack, 04.09.) – replaces the two-step
     *  wizard; «Incarico e linea» è una sola sezione (vedi de/atemschutz.ts). */
    stackPressure: '{n} bar',
    // no longer asked in the Trupp form (04.09.) – still offered on the Lage/plan and in admin
    colorAuto: 'Automatico',
    // stato sync/orologio nell'intestazione della tavola (vedi de/atemschutz.ts)
    syncStand: '{status} · {t}',
    clockSkewChip: 'Orologio del dispositivo sfasato ({d} min)',
    formCreateTitle: 'Annuncia squadra',
    formEditTitle: 'Modifica squadra',
    formRedeployTitle: 'Rientrare',
    sectionTeam: 'Squadra',
    auftragLabel: 'Compito',
    auftragOpen: 'Incarico aperto',
    // Etichette di VISUALIZZAZIONE dei tipi di mandato, indicizzate per id (il valore resta l'id).
    auftragLabels: {
      retten: 'Salvare',
      loeschen: 'Spegnere',
      absuchen: 'Perlustrare',
      sichern: 'Mettere in sicurezza',
      erkunden: 'Esplorare',
      verkehr: 'Traffico',
      sanitaet: 'Sanitario',
      wasser: 'Approvvigionamento idrico',
      bereitstellung: 'Messa a disposizione',
      anderes: 'Altro',
    },
    equipmentLabels: {
      retthaube: 'Cappuccio di salvataggio',
      wbk: 'WBK',
      multiwarn: 'Multiwarn',
    },
    equipmentLabel: 'Equipaggiamento',
    equipmentShort: {
      retthaube: 'RH',
      wbk: 'WBK',
      multiwarn: 'MW',
    },
    zielLabel: 'Obiettivo',
    // UN solo segnaposto per entrambi i tipi di squadra e per ogni incarico (vedi de/atemschutz.ts).
    zielPlaceholder: 'Dove / cosa …',
    zielClear: 'Svuota obiettivo',
    leaderLabel: 'Capogruppo',
    teamSearchPlaceholder: 'Cerca persona …',
    // the phone chip row (05.09.) — see de/atemschutz.ts for why the roster list is gone there
    teamSearchMore: 'Cerca un\'altra persona …',
    teamHintChips: 'Tocca un nome = capogruppo',
    leaderBadge: 'CS',
    makeLeader: 'Designa {name} capogruppo',
    teamRemove: 'Togli {name} dalla squadra',
    teamTaken: 'in una squadra',
    teamManual: 'ospite',
    teamGuestAdd: 'Aggiungi «{name}» come ospite',
    lineNoLabel: 'Condotta',
    lineLegacyNote: 'Registrato prima: «{value}»',
    lineTyped: 'N. …',
    lineTakeTitle: 'La linea {n} è occupata',
    lineTakeMsg: 'La squadra {from} è sulla linea {n}. Mettere la squadra {to}?',
    lineTakeConfirm: 'Subentra',
    lineHeldToast: 'La linea è occupata dalla squadra {name}.',

    lineOptTaken: 'La squadra {name} è su questa linea',
    lineShow: 'Mostra la linea sulla mappa',
    logLineLinked: 'Squadra {name} sulla linea {n}',
    logLineUnlinked: 'Squadra {name}: linea scollegata',
    lineUnlinkedToast: 'Linea scollegata',
    markerLabel: 'Squadra AR',
    markerNone: 'Nessuna squadra',
    markerPick: 'Riprendi una squadra posata',
    markerOptTaken: 'Appartiene alla squadra {name}',
    markerTakeTitle: 'Qui è la squadra {from}',
    markerTakeMsg: 'Questa squadra posata appartiene alla squadra {from}. Passarla alla squadra {to}?',
    markerTakeConfirm: 'Riprendi',
    logMarkerUnlinked: 'La squadra {name} non è più posata',
    entryAskTitle: 'Far entrare la squadra?',
    entryAskMsg: 'La squadra {name} è annunciata ma non è ancora entrata. Farla entrare ora? Il cronometro dei contatti parte subito.',
    entryAskCancel: 'Non ancora',
    pressureLabel: 'Pressione d’ingresso',
    newPressureLabel: 'Nuova pressione d’ingresso',
    funkkanalSection: 'Canale radio',
    funkkanalDown: 'Canale radio giù',
    funkkanalUp: 'Canale radio su',
    funkkanalUnit: 'Canale',
    clearName: 'Svuota nome',
    notPresent: 'non presente',
    noRoster: 'Nessun effettivo disponibile',
    assignedConflict: '{name} è già in un’altra squadra.',
    // l’unica mossa che scioglie il nodo — toglierla dall’altra squadra e proseguire qui
    assignedTransfer: 'Sposta in questa squadra',
    // …e quando non viene offerta: l’altra squadra è in intervento, il suo orologio di contatto corre
    assignedConflictDeployed: '{name} è in una squadra che è in intervento.',
    saveBlockedTeam: 'Indicare prima un caposquadra.',
    auftragMissingHint: 'Manca il compito – la squadra viene registrata con «Incarico aperto».',
    saveBlockedAuftrag: '«Altro» richiede un obiettivo.',
    saveBlockedPressure: 'Pressione in entrata mancante.',
    cancel: 'Annulla',
    save: 'Salva',
    start: 'Annuncia',
    reenterSubmit: 'Entrare',
    reenterStandby: 'Tenere di riserva',
    reenterStandbyHint: 'Registra la squadra come riserva – il contatore parte solo con «Entrare».',
    sinceContact: 'Dall’ultimo contatto',
    elapsed: 'Tempo d’intervento',
    outFor: 'Fuori da',
    outForPlain: 'Senza compito da', // ⚠️ app only — see de/atemschutz.ts · outForPlain
    currentPressure: 'Pressione',
    lowestPressure: 'Più bassa',
    lineField: 'Linea',
    edit: 'Modifica',
    pressureConfirm: 'Conferma',
    pressureConfirmHint: 'Conferma la nuova pressione – vale come contatto',
    verlauf: 'Diario',
    cardMenu: 'Altre azioni',
    bandPreEntry: 'Non ancora entrata',
    bandRegisteredAt: 'annunciata alle',
    zoneTimes: 'Orari',
    lastContactAt: 'Ultimo contatto',
    nextContactDue: 'Prossimo contatto',
    contactIntervalLabel: 'Intervallo di contatto',
    contactIntervalValue: '{min} min',
    verlaufLatest: 'ultimo: {time} {what}',
    // ⚠️ Parole dell’EVENTO in questa colonna («Art»), mai parole di stato: la riga dice che
    // cosa è successo, «Fuori» è ciò che la scheda dice della squadra dopo (status · outFor).
    readingKind: { registered: 'Annunciata', entry: 'Entrata', contact: 'Contatto', pressure: 'Pressione',
      alarm: 'Pressione d\'allarme',
      rueckzug: 'Ripiegamento',
      // ⚠️ il ripiegamento è stato annullato — nessuno è rientrato (vedi la base tedesca)
      exit: 'Uscita', resume: 'Ripiegamento annullato',
      paOn: 'Sotto ARA', paOff: 'Sorveglianza ARA conclusa',
      // a `crew` row prints its names (AtemschutzView · readingLabel); this is the fallback word
      crew: 'Squadra',
    },
    readingNoAs: '{what} – senza ARA',
    clockOk: 'Contatto ok',
    clockFrozen: 'Stato alla chiusura',
    clockWarn: 'Contatto in scadenza',
    clockOverdue: 'In ritardo',
    clockAlarmPressure: 'Pressione d’allarme',
    clockAlarmLimit: 'Limite {bar} bar',
    overdueBadge: (n: number) => `${n} in allarme`,
    overdueBadgeGo: 'Vai alla squadra {name} – allarme più urgente',
    collapse: 'Panoramica',
    actEnter: 'Entrare',
    actContact: 'Contatto',
    actRueckzug: 'Annuncia il ritiro',
    actContinue: 'Continua',
    actExit: 'Annuncia uscita',
    tileRueckzug: 'Ritiro',
    tileExit: 'Fuori',
    quickTrupp: 'Squadra {no}',
    kanalSheetHint: 'Toccare sceglie e chiude.',
    formPickTake: 'Applica',
    lineNone: 'nessuna',
    lineChip: 'Cond. {n}',
    auftragAdd: '+ Compito',
    actExitPlain: 'Compito svolto', // ⚠️ app only — see de/atemschutz.ts · actExitPlain
    actReenter: 'Rientrare',
    actNotDeployed: 'Non impiegata',
    actNotDeployedHint: 'Chiudi la squadra senza che sia entrata con l’autorespiratore – resta pronta per un impiego successivo',
    statusNotDeployed: 'Non impiegata',
    statusRemoved: 'Rimosso dalla lavagna',
    logNotDeployed: 'Squadra {name} non impiegata',
    remove: 'Rimuovi',
    removeUnusedTitle: 'La squadra non è stata impiegata',
    removeUnusedMsg: 'Chiudere {name} come «non impiegata» invece di rimuoverla? La squadra resta pronta sulla lavagna – «Rimuovi» serve per le registrazioni errate.',
    place: 'Posiziona',
    placeWhere: 'Dove posizionare?',
    placeNoTarget: 'Nessun piano disponibile – scegli prima un edificio con «Edificio» nella barra.',
    showOnPlan: 'Mostra sul piano',
    dockedAt: 'presso «{host}»',
    dockLabel: '{who} · presso «{host}»',
    dockedTeams: 'Agganciato',
    showOnMap: 'Mostra sulla carta',
    preEntryHint: 'Non ancora entrata – premi «Entrare» appena la squadra va sotto ARA.',
    alarmArmed: 'Allarme attivo – suono e notifica · toccare per silenziare',
    alarmMuted: 'Allarme silenziato – suono e notifica, fino alla fine di questo intervento · toccare per attivare',
    alarmBlocked: 'Audio non sbloccato – il browser lo ha rifiutato · toccare, altrimenti avvisa solo la notifica',
    alarmBlockedNoFallback: 'Audio non sbloccato – toccare per attivarlo. Questo browser non può mostrare notifiche.',
    alarmDemoNote: 'Demo – suono e notifica sono disattivati su questa istanza',
    restoreMenu: 'Squadre rimosse',
    // the bell's WORD on a wide head (22.09.2026; the honest state stays in the tooltip/aria)
    alarmWord: 'Suono allarme',
    alarmMutedWord: 'Muto',
    alarmBlockedWord: 'Attiva audio',
    restoreItem: 'Ripristina {name}',
    alarmNotifyTitle: 'Autoprotezione in ritardo',
    alarmNotifyBody: 'Squadra {name} in ritardo – stabilire il contatto.',
    status: { angemeldet: 'Annunciata', aktiv: 'In intervento', rueckzug: 'Ritiro', ueberfaellig: 'In ritardo', raus: 'Fuori' },
    statusPlainOut: 'Senza compito', // ⚠️ app only — see de/atemschutz.ts · statusPlainOut
    // come si CHIAMA una squadra nel testo corrente — vedi la base tedesca
    truppTerm: 'Squadra {name}',
    logRegister: 'Squadra {name} annunciata – pressione d’ingresso {bar} bar',
    logRegisterPlain: 'Squadra {name} annunciata',
    logRenumbered: 'Squadra {name} diventa Squadra {no}',
    logRenumberedChip: '{from} diventa {to}',
    logPlaced: 'Squadra {name} posizionata sul piano',
    logPlacedMap: 'Squadra {name} posizionata sulla carta',
    placeLage: 'Mappa',
    logEntry: 'Squadra {name}: entrata',
    // ⚠️ le righe di ENTRATA dicono con che cosa la squadra è entrata — vedi la base tedesca
    logEntryNoAs: 'Squadra {name}: entrata – senza ARA',
    logSafetyEntry: 'Squadra {name}: squadra di sicurezza impiegata',
    logContact: 'Squadra {name}: contatto confermato',
    logPressure: 'Squadra {name}: pressione {bar} bar',
    // ⚠️ dice che cosa SUCCEDE invece di affermare un contatto che nessuno ha confermato
    logRueckzug: 'Squadra {name} annuncia il ripiegamento – orologio di contatto azzerato',
    // ⚠️ UNA riga che annulla il ripiegamento e dice che cosa vale invece — vedi la base tedesca
    logContinue: 'Squadra {name}: ripiegamento annullato – intervento ripreso',
    logExit: 'Squadra {name}: uscita',
    logExitBar: 'Squadra {name}: uscita – pressione residua {bar} bar',
    actPressure: 'Pressione',
    pressureSheetTitle: 'Pressione',
    pressureSheetHint: 'Un tocco salva – conta come contatto.',
    exitSheetTitle: 'Pressione residua',
    exitSheetHint: 'Un tocco annuncia l’uscita – valore più basso della squadra.',
    exitNoBar: 'Fuori senza pressione',
    phoneSectionIn: 'Dentro',
    phoneSectionReady: 'Pronti',
    phoneSectionOut: 'Fuori',
    safetyTitle: 'Squadra di sicurezza',
    safetyPick: 'Designare',
    safetyPickTitle: 'Designare la squadra di sicurezza',
    safetyPickNew: 'Annunciare una nuova squadra (sicurezza)',
    pinnedLabel: 'Squadre da contattare',
    contactEchoTitle: 'Contatto già confermato',
    contactEchoWho: 'Squadra {n}',
    contactEchoMsg: '{name} · {s} s fa su un altro apparecchio',
    contactEchoAgain: 'Confermare di nuovo',
    contactEchoOk: 'OK',
    editConflictOne: '{field} è stato modificato nel frattempo su un altro apparecchio: {now} – sovrascrivere comunque?',
    editConflictMany: '{fields} sono stati modificati nel frattempo su un altro apparecchio – sovrascrivere comunque?',
    editConflictOverwrite: 'Sovrascrivere',
    editConflictBack: 'Torna al modulo',
    editFieldLabels: { crew: 'Squadra', auftrag: 'Compito', ziel: 'Obiettivo', lineNo: 'Condotta', funkkanal: 'Canale radio', pressure: 'Pressione d’entrata', kind: 'Tipo di squadra', equipment: 'Equipaggiamento' },
    logFirstPressure: 'Squadra {name}: contatto – prima pressione {bar} bar sostituisce la pressione d’entrata {from} bar',
    logFirstPressureSame: 'Squadra {name}: contatto – prima pressione {bar} bar (come la pressione d’entrata)',
    pressureSheetFirst: 'Prima pressione – sostituisce la pressione d’entrata {bar} bar, conta come contatto',
    newTruppShort: 'Squadra',
    removedToast: 'Squadra {name} rimossa',
    notDeployedToast: 'Squadra {name}: non impiegata',
    removeInsideTitle: 'La squadra {name} è dentro – annunciarla fuori prima?',
    removeInsideMsg: 'Rimuovere toglie la squadra dalla lavagna e da ogni allarme. Di solito si intende: la squadra è uscita.',
    actEnterFirst: 'Impiegare',
    contactDone: 'Confermato',
    pressureLockedLabelPlain: 'Pressione d’entrata',
    pressureLocked: 'Squadra fuori',
    pressureLockedWhyExit: 'Squadra fuori · residuo {bar} bar',
    entryLowTitle: 'Pressione d’entrata bassa',
    entryLowMsg: '{bar} bar – di solito da {min} bar',
    entryLowConfirm: 'Tenere {bar} bar',
    entryLowChange: 'Modificare',
    bottleAsk: 'Uscita {min} min fa, ultima {bar} bar. Quale bombola?',
    bottleAskNow: 'Appena uscita, ultima {bar} bar. Quale bombola?',
    bottleSame: 'Stessa bombola',
    bottleNew: 'Nuova bombola',
    saveBlockedBottle: 'Scegliere stessa o nuova bombola',
    logReenter: 'Squadra {name} rientrata – pressione d’ingresso {bar} bar',
    logReenterPlain: 'Squadra {name} rientrata',
    logReenterNoAs: 'Squadra {name} rientrata – senza ARA',
    logStandby: 'Squadra {name} di riserva – non ancora entrata',
    // la clausola d’impiego aggiunta alle tre righe che APRONO un impiego (vedi de/atemschutz.ts):
    // forme brevi, perché si agganciano a una frase già completa
    logDetailLine: 'Linea {n}',
    logDetailFunk: 'Canale {n}',
    logDetailNoAs: 'senza ARA',
    logAlarm: 'Allarme autoprotezione: squadra {name} – {status}',
    logAlarmCleared: 'Allarme autoprotezione terminato: squadra {name} – {reason}',
    alarmClearedBy: {
      exit: 'uscita',
      contact: 'contatto radio',
      pressure: 'lettura di pressione',
      rueckzug: 'ripiegamento',
      resume: 'impiego ripreso',
    } as Record<string, string>,
    alarmClearedOther: 'contatto ristabilito',
    alarmClearedByReopen: 'orologio di contatto riavviato (riaperto)',

    orderLabel: 'Ordine',
    orderUrgency: 'Urgenza',
    orderManual: 'Come posato',
    orderAuftrag: 'Compito',
    orderName: 'Nome',
    moveBack: 'Sposta su',
    moveForward: 'Sposta giù',
    truppFallbackName: 'Squadra',
    editPressureLabel: 'Correggi la pressione d\'ingresso',
    editPressureHint: 'Corregge la pressione d\'ingresso registrata – non conta come contatto radio.',
    officersOnly: 'solo ufficiali',
    assignedFallbackName: 'Questa persona',
    estimated: 'Pressione stimata',
    // la forma breve per la riga che resta dello zoccolo (09.09., vedi de/atemschutz.ts)
    estimatedShort: 'Stima',
    estimatedHint: 'Ausilio alla pianificazione – finché non c\'è abbastanza storico di pressione, stimato con una bombola da {liters} L e un consumo di {rate} L/min. Non sostituisce l\'annuncio di pressione.',
    estimatedHintHistory: 'Ausilio alla pianificazione – estrapolato dal consumo di pressione confermato di questa squadra. Non sostituisce l\'annuncio di pressione.',
    estimatedSourceHistory: 'da {count} rilevamenti di pressione · stato {time}',
    estimatedSourceFallback: '{rate} L/min presunti · stato {time}',
    alarmNote: 'Pressione d\'allarme di {bar} bar raggiunta',
    alarmNoteEst: 'Pressione d\'allarme di {bar} bar – raggiunta secondo la stima',
    pressureRose: 'Più alto dell\'ultima volta ({from} bar) – errore di battitura?',
    chipHint: 'ARA – tocca per la sorveglianza',
    alarmRowOverdue: 'Autoprotezione in ritardo – {name}',
    alarmRowOverdueSub: 'Nessun contatto radio – stabilire subito il contatto.',
    alarmRowPressure: 'Pressione d\'allarme raggiunta – {name}',
    alarmRowOverdueMany: 'Autoprotettori in ritardo – {count} squadre: {names}',
    alarmRowPressureMany: 'Pressione d\'allarme raggiunta – {count} squadre: {names}',
    alarmRowPressureManySub: 'Ordinare il ritiro.',
    alarmRowPressureSub: '{bar} bar, limite {line} bar – ordinare il ripiegamento.',
    alarmRowGo: 'Alla squadra',
    alarmRowAck: 'Preso atto',
    alarmRowReadOnly: 'sola lettura',
    logSafety: 'Valori di sicurezza ARA modificati: {changes}',
    logSafetyInterval: 'Intervallo di contatto radio {from} → {to} min',
    logSafetyGrace: 'Tempo di tolleranza {from} → {to} s',
    logSafetyFunkkanal: 'Canale radio {from} → {to}',
    logEditFields: 'Squadra {name}: {changes}',
    changeLeader: 'Capo squadra {from} → {to}',
    changeMemberOut: '{names} tolti dalla squadra',
    changeMemberIn: '{names} si sono aggiunti',
    // …e CHI C’È ADESSO, con il « / » con cui quest’app scrive una squadra ovunque
    changeCrewNow: 'Ora: {crew}',
    crewChange: {
      leader: 'Caposquadra {from} → {to}',
      movedTo: '{name} → squadra {to}',
      movedFrom: '{name} dalla squadra {from}',
      left: '{name} tolto dalla squadra',
      joined: '{name} aggiunto',
    },
    // il passaggio, in UNA riga presso la squadra che cede la persona — {name} è quella squadra,
    // {to} quella che la accoglie (la cui riga nomina già il suo effettivo completo)
    logMovedOut: 'Squadra {name}: {person} passato alla squadra {to}',
    logMovedOutPlain: 'Squadra {name}: {person} passato a un’altra squadra',
    changeAuftragTo: 'compito {auftrag}',
    changeAuftragCleared: 'compito rimosso',
    changeLine: 'Linea {n}',
    changeLineCleared: 'Linea liberata',
    // ⚠️ da → a, come la pressione d’ingresso — «Canale radio 12» non diceva se fosse stato
    // impostato, cambiato o solo confermato
    changeFunkkanal: 'Canale radio {from} → {to}',
    changeFunkkanalSet: 'Canale radio {n} impostato',
    changeFunkkanalCleared: 'Canale radio rimosso',
    changeColor: 'Colore modificato',
    changeEquipment: 'Equipaggiamento: {list}',
    changeEquipmentNone: 'Equipaggiamento: nessuno',
    changePressure: 'Pressione d\'ingresso {from} → {to} bar',
    // una bombola aperta adesso non ha un «prima» — vedi la base tedesca
    changePressureSet: 'Pressione d\'ingresso {n} bar',
    changeKindPa: 'ora sotto ARA',
    changeKindPlain: 'non più sotto ARA',
    kindOffTitle: '{name}: terminare la sorveglianza ARA?',
    kindOffMsg: 'La squadra è in servizio. Senza ARA l’orologio di contatto e la pressione non '
      + 'proseguono e non c’è più alcun allarme per lei. Tutto quanto registrato finora resta '
      + 'nel registro e nel rapporto.',
    kindOffConfirm: 'Terminare la sorveglianza',
    logPressureAlarm: 'Squadra {name}: pressione {bar} bar – pressione d\'allarme raggiunta',
    logRemoved: 'Squadra {name} rimossa',
    logRestored: 'Squadra {name} ripristinata',
    logInsideAtClose: 'Squadra {name} ancora dentro alla chiusura',
    cycleEndAtClose: '{t} (ancora dentro alla chiusura)',
    logClockRestart: 'Squadra {name}: orologio di contatto riavviato – intervento riaperto',
  },
  lineDecor: {
    W: 'Acqua',
    S: 'Schiuma',
    H: 'Cortina d’acqua',
    P: 'Polvere',
    N: 'Linea d’arresto umida',
    T: 'Linea d’arresto secca',
    G: 'Controfuoco',
  } as Record<string, string>,
}
