// Italian copy · the Gebäude card and floors.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/building.ts.

import type { Copy, Localizable } from '../index'

export const buildingCopy: Localizable<Pick<Copy, 'building'>> = {
  building: {
    title: 'Edificio',
    hint: 'Indicazione del registro',
    hintTitle: 'Dai registri federali (REA, UFE) – può essere superato o incompleto. Verificare sul posto.',
    floors: '{n} piani',
    floorsOne: '1 piano',
    flats: '{n} abitazioni',
    flatsOne: '1 abitazione',
    year: 'Costruito nel {y}',
    period: 'Costruito {p}',
    shelter: 'Rifugio',
    heating: 'Riscaldamento {e}',
    hotWater: 'Acqua calda {e}',
    pv: 'PV {kw}',
    pvBare: 'PV',
    pvTitle: 'Fotovoltaico nel registro UFE{since} – può mancare anche se un impianto c’è',
    pvSince: ', in esercizio dal {d}',
    kw: '{n} kW',
    energy: {
      gas: 'gas',
      oil: 'olio combustibile',
      wood: 'legna',
      district: 'teleriscaldamento',
      air: 'pompa di calore (aria)',
      geothermal: 'pompa di calore (suolo)',
      water: 'pompa di calore (acqua)',
      electricity: 'elettrico',
      solar: 'solare',
      waste_heat: 'calore residuo',
      other: 'altro',
    },
    status: {
      planned: 'progettato',
      approved: 'autorizzato',
      under_construction: 'in costruzione',
      unusable: 'inutilizzabile',
      demolished: 'demolito',
      not_built: 'non realizzato',
    },
    srcGwr: 'REA {a} · stato {d}',
    srcGwrNoAddr: 'REA stato {d}',
    srcHeating: 'riscaldamento registrato {d}',
    srcPv: 'UFE consultato {d}',
    srcCached: 'salvato {d}',
    measures: 'Misure immediate',
    remarks: 'Osservazioni',
    objectSource: '{name} · {src}',
    objectNear: '{name} · nelle vicinanze ({m} m)',
    objectNearNoDist: '{name} · nelle vicinanze',
    visit: 'Ultima visita all’oggetto {d}',
    visitFindings: 'Ultima visita all’oggetto {d} · {n} difetti',
    visitFindingsOne: 'Ultima visita all’oggetto {d} · 1 difetto',
    chipTitle: 'Info edificio',
    chipLabel: 'Apri la scheda dell’edificio',
    chipLabelHazards: 'Edificio: {h} – apri la scheda',
    measuresShort: 'Misure',
  },
}
