// Italian copy · the capture (QR) app.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/capture.ts.

import type { Copy, Localizable } from '../index'

export const captureCopy: Localizable<Pick<Copy, 'capture'>> = {
  capture: {
    title: 'Registrare l’intervento',
    invalid: 'Link non valido o rilevamento disattivato.',
    noIncidents: 'Al momento nessun intervento registrabile.',
    noIncidentsHint: 'Qui appaiono gli interventi in corso e non ancora rapportati. Manca il vostro? Annotatelo sul foglio cartaceo o segnalatelo alla condotta – potrà aggiungerlo in seguito.',
    searchName: 'Cerca nome …',
    filterRecorded: 'Registrati {n}',
    back: 'Indietro',
    alarmedAt: 'Allarme {t}',
    saveFailed: 'Salvataggio non riuscito',
    saveFailedOffline: 'Nessuna connessione – l’ultima modifica non è stata salvata.',
    retry: 'Riprova',
    savedOk: 'Salvato',
    undo: 'Annulla',
    mittelSet: '{label}: ora {n} {unit}',
    mittelRemoved: '{label} rimosso',
    mittelExtra: 'Altre posizioni registrate',
    gerettete: 'Salvati',
    gerettetePersonen: 'Persone',
    geretteteTiere: 'Animali',
    rueckmeldung: 'Rapporto alla centrale',
    rueckName: 'Scegliere un nome …',
    rueckZeit: 'Ora',
    jetzt: 'Adesso',
    kurzberichtHead: 'Rapporto breve',
    kurzberichtPlaceholder: 'Cosa è successo, cosa è stato fatto?',
    gruppenHead: 'Allarme dei gruppi',
    fahrzeugeHead: 'Partenze dei veicoli',
    einsatzleiter: 'Capo intervento',
    rapportPdf: 'Rapporto PDF',
    pdfFailed: 'PDF non riuscito – riprovare',
    sectionZeiten: 'Orari',
    sectionAngaben: 'Indicazioni',
    zeitenFilled: '{n} orari registrati',
    abschlussHead: 'Chiusura',
    missingHead: 'Ancora aperto:',
    missingGo: 'Apri {step}',
    missingNote: 'Stampato come campo da compilare.',
    ausgerueckt: 'Partenza',
    kontaktperson: 'Persona di contatto',
    kontaktpersonPlaceholder: 'Proprietario / segnalante',
    kontaktpersonTelefon: 'Telefono persona di contatto',
    kontaktpersonTelefonPlaceholder: 'Numero di telefono',
    kontaktpersonCall: 'Chiama la persona di contatto',
    von: 'da',
    bis: 'a',
    ende: 'Fine intervento',
    sectionPersonen: 'Presenze',
    presentCount: '{n} presenti',
    tapHint: 'Toccare: assente → rimessa → sul posto → andato. Ora accanto: da = arrivo, dopo l\'uscita a = uscita.',
    stateLeft: 'partito',
    sectionMaterial: 'Materiale',
    cancel: 'Annulla',
    mittelCount: '{n} posizioni',
    pickMaterial: 'Scegliere il materiale …',
    add: 'Aggiungere',
    notePlaceholder: 'Nota per il diario …',
    footNote: 'Tutto viene salvato continuamente.',
    tapHelp: 'Guida all\'uso',

    logAttendancePresent: '{name} presente (QR)',
    logAttendanceLeft: '{name} andato (QR)',
    logAttendanceCleared: '{name} rimosso dalle presenze (QR)',
    logAttendanceRestored: '{name} ripristinato (QR)',
    logTimes: 'Orari di {name} corretti (QR)',
    logMittel: '{label}: {menge} {unit} (QR)',
    logAttachmentAdd: 'Foto del rapporto aggiunta (QR)',
    logAttachmentRemove: 'Foto del rapporto rimossa (QR)',
    logMeta: 'Dati del rapporto modificati (QR): {fields}',
    partnersHead: 'Organizzazioni partner',
    partnerOrg: 'Organizzazione',
    partnerNote: 'Osservazione',
    partnerAdd: 'Aggiungi un\'organizzazione',
    partnerPlaceholder: 'Organizzazione …',
    partnerRemove: 'Rimuovi l\'organizzazione',
    partnerCount: '{n} registrate',
    partnerNone: 'nessuna',
    beilagenHead: 'Foto',
    beilagenAdd: 'Aggiungi una foto',
    beilagenBusy: 'Caricamento …',
    beilagenCaption: 'Didascalia',
    beilagenRemove: 'Elimina la foto',
    beilagenFailed: 'Impossibile caricare la foto.',
    beilagenCount: '{n} foto',
    beilagenNone: 'nessuna',
    loadFailedOffline: 'Nessuna ricezione',
    clockSkew: 'L\'orologio di questo dispositivo devia di {n} minuti – controlla gli orari registrati.',
    searchMaterial: 'Cerca materiale …',
    kpActive: 'Tablet PC attivo',
    kpActiveHint: 'Il tablet del PC è in uso – il rapporto completo (con lo schizzo) arriva da lì.',
    kpNormallyHint: 'Il rapporto completo (con lo schizzo) arriva normalmente dal tablet del PC.',
    usageChip: 'QR: {n} voci · ultima {t}',
    usageChipOne: 'QR: 1 voce · ultima {t}',
    exerciseHint: 'Esercitazione – non conta nella statistica degli interventi.',
    groupCurrent: 'Attuale',
    groupBacklog: 'Ancora aperto',
  },
}
