// Italian copy · measuring, shapes, object Verlauf rows, the tool dock.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/drawing.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'measure' | 'shapes' | 'log' | 'objectDone' | 'addSheet' | 'toolDock'

export const drawingCopy: Localizable<Pick<Copy, Keys>> = {
  measure: {
    modeLine: 'Distanza',
    modeArea: 'Superficie',
    clear: 'Reimposta',
    insertPoint: 'Inserisci punto',
    extendLine: 'Prolungare la linea',
    deleteNode: 'Tenere premuto per eliminare · clic destro sul computer',
    snapConnect: 'Tenere premuto per collegare',
    snapRelease: 'Allontanare per staccare',
    distance: 'Distanza',
    perimeter: 'Perimetro',
    boxWidth: 'Larghezza',
    boxHeight: 'Altezza',
    area: 'Superficie',
    hoses: 'Tubi',
    profile: 'Profilo altimetrico',
    ascent: 'Salita',
    descent: 'Discesa',
    min: 'Più basso',
    max: 'Più alto',
    profileLoading: 'Caricamento profilo altimetrico …',
    profileNone: 'Nessun profilo altimetrico disponibile',
    hintLine: 'Almeno 2 punti per la distanza',
    hintArea: 'Almeno 3 punti per l’area',
    adoptLine: 'Riprendi come linea',
    adoptArea: 'Riprendi come superficie',
  },
  shapes: {
    sectionTitle: 'Forme',
    kindLabel: 'Forma',
    color: 'Colore',
    rotate: 'Ruotare',
    stopLabel: 'Barra di arresto',
    carrierLabel: 'Vettore',
    carrierNone: 'Nessuno',
    carrierHeli: 'Eli',
    carrierTlf: 'TLF',
    resizeHint: 'Trascina l’angolo per ridimensionare',
    heightLabel: 'Altezza',
    boxWidthHint: 'Trascinare — larghezza',
    boxHeightHint: 'Trascinare — altezza',
    endHint: 'Trascinare l’estremità — distanza e direzione',
    strokeLabel: 'Spessore linea',
    cornersLabel: 'Angoli',
    cornersRound: 'Arrotondati',
    cornersSharp: 'Vivi',
    names: { arrow: 'Freccia', cloud: 'Fumo', square: 'Rettangolo', rotation: 'Rotazione' },

    size: 'Dimensione',
    sizeSmaller: 'Più piccolo',
    sizeBigger: 'Più grande',
    lengthLabel: 'Lunghezza',
    lengthShorter: 'Più corto',
    lengthLonger: 'Più lungo',
    moveHint: 'Trascina il cestello – direzione e portata',
  },
  log: {
    audioNote: 'Nota audio',
    symbolPlaced: 'Simbolo «{name}» posizionato',
    shapePlaced: '{name} posizionato',
    notePlaced: 'Nota posizionata',
    shapeDrawn: '{name} disegnato',
    objectMoved: '{name} spostato',
    placardDocked: '{name} agganciato a «{host}»',
    placardUndocked: '{name} sganciato da «{host}»',
    teamDocked: '{name} presso «{host}»',
    teamUndocked: '{name} sganciato da «{host}»',
    referenceRebaked: 'Riferimento adattato – {n} oggetti riposizionati',
    referenceRemeasured: 'Forma del foglio misurata – {n} oggetti riposizionati',
    referenceRolledBack: 'Modifica del riferimento annullata – salvataggio non riuscito',
    referenceDropped: 'Riferimento rimosso',
    referenceDroppedKept: 'Riferimento rimosso – {n} oggetti mantengono la loro ultima posizione',
    referenceLinked: 'Piano collegato alla mappa – {plan}',
    referenceLinkedPlaced: 'Piano collegato alla mappa – {plan} – {n} oggetti posizionati',
    objectDeleted: '{name} rimosso',
    drawingDeleted: 'Disegno rimosso',
    undo: 'Azione annullata',
    redo: 'Azione ripristinata',
    undoNamed: '{action} annullato',
    redoNamed: '{action} ripristinato',
    journalNote: 'Nota',

    teamPlaced: '{name} posata sulla mappa',
    selectionDeleted: '{n} oggetti rimossi',
    duplicated: 'Oggetto duplicato',
    entityEdited: '{name}: {changes}',
    fieldSet: '{field}: {value}',
    fieldChanged: '{field} cambiato in {value}',
    fieldCleared: '{field} svuotato',
    // le stesse due affermazioni SENZA il valore — per l'unico caso in cui nominarlo ripeterebbe
    // il nome della riga stessa («Pfeil: Abschluss: Pfeil», vedi lib/drawingEdit)
    fieldSetPlain: '{field} impostato',
    fieldChangedPlain: '{field} modificato',
    labelSet: 'Etichetta «{value}»',
    labelCleared: 'Etichetta rimossa',
    floorSet: 'Piano {value}',
    floorCleared: 'Piano rimosso',
    floorRangeSet: 'Piani {from} – {to}',
    floorRangeCleared: 'Intervallo di piani rimosso',
    countSet: 'Numero {n}',
    spreadSet: 'Propagazione registrata',
    spreadCleared: 'Propagazione rimossa',
    noteWritten: 'Nota «{value}»',
    notesCleared: 'Nota svuotata',
    drawingLabelSet: '{kind} «{value}»',
    gpsReverted: '{name}: tornata allo stato sul posto ({time}), liberata da {vehicle}',
    gpsRevertedBare: '{name}: tornata allo stato sul posto ({time})',
    gpsReleasedOnSite: '{name}: liberata da {vehicle} sul posto, tragitto rimosso',
    gpsReleasedOnSiteBare: '{name}: liberata sul posto, tragitto rimosso',
    drawingLabelCleared: '{kind}: etichetta rimossa',
    drawKinds: {
      area: 'Superficie',
      line: 'Linea',
      circle: 'Cerchio di sbarramento',
    },
  },
  objectDone: {
    word: {
      fire: { title: 'Spento', inline: 'spento' },
      other: { title: 'Concluso', inline: 'concluso' },
    },
    action: 'Concluso',
    actionHint: 'resta visibile in grigio',
    state: '{word} {time}',
    reopen: 'Di nuovo attivo',
    removeHint: 'solo in caso di errore',
    logDone: '{name}: stato {word}',
    logReopened: '{name}: stato attivo',
  },
  addSheet: { tile: 'Aggiungi', tools: 'Disegno & squadra' },
  toolDock: {
    colorGroup: 'Colore',
    colorName: '{group} {n}',
    widthName: 'Spessore {n} px',
    autoCommitted: '{name} salvato',
    autoCommitUndo: 'Annulla',
    draftDiscarded: 'Disegno incompleto scartato',
  },
}
