// Italian copy · the symbol / drawing editors, top bar and small controls.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/editors.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'contextPanel' | 'drawingEditor' | 'topBar' | 'stepper' | 'confirm' | 'combo'

export const editorsCopy: Localizable<Pick<Copy, Keys>> = {
  contextPanel: {
    titlePlaceholder: 'Denominazione ...',
    floor: 'Piano',
    floorFrom: 'Dal piano',
    floorTo: 'Al piano',
    floorNone: '–',
    spread: 'Propagazione',
    spreadH: 'Orizzontale',
    spreadV: 'Verticale',
    spreadBounded: 'Limite',
    spreadBoundedTitle: 'Limite di propagazione — propagazione fermata qui',
    spreadDirTitles: { left: 'a sinistra', right: 'a destra', up: 'Piano superiore (↑)', down: 'Piano inferiore (↓)' } as Record<string, string>,
    count: 'Quantità',
    rotation: 'Rotazione',
    rotationVehicle: 'Veicolo',
    rotationFan: 'Ventilatore',
    rotationLadder: 'Scala',
    center: 'Centra',
    toOriginal: 'Vai all\'originale',
    toProjection: 'Mostra sulla superficie collegata',
    showOnMap: 'Mostra sulla mappa',
    showOnPlan: 'Mostra su {plan}',
    resetGps: 'GPS',
    resetGpsTitle: 'Reimposta su posizione e rotta GPS',
    pinGps: 'Fissa qui',
    pinGpsTitle: 'Fissa il veicolo qui – il simbolo resta anche se riparte',
    logPinned: '{name} fissato',
    driverLabel: 'Conducente',
    driverPlaceholder: 'Nome',
    rotateHint: 'Trascina la maniglia per orientare',
    notes: 'Note',
    notesPlaceholder: 'Note generali …',
    addField: 'Aggiungi campo',
    addFieldShort: 'Campo',
    removeField: 'Elimina campo',
    fieldKeyPlaceholder: 'Denominazione',
    fieldNamePlaceholder: 'Nome …',
    fieldValuePlaceholder: '{label} …',
    duplicateField: '«{key}» esiste già – viene mantenuto solo l\'ultimo valore.',
    stoffSearch: 'Cerca o inserisci una sostanza …',
    unHazardTitle: 'Merci pericolose (ADR)',
    adrMeanings: {
      '1': 'Materie esplosive',
      '1.4': 'Materie esplosive (pericolo minore)',
      '1.5': 'Materie esplosive (molto insensibili)',
      '1.6': 'Materie esplosive (estremamente insensibili)',
      '2': 'Gas',
      '2.1': 'Gas infiammabile',
      '2.2': 'Gas non infiammabile, non tossico',
      '2.3': 'Gas tossico',
      '3': 'Liquidi infiammabili',
      '4.1': 'Solidi infiammabili',
      '4.2': 'Materie soggette ad accensione spontanea',
      '4.3': 'Sviluppa gas infiammabili a contatto con l’acqua',
      '5.1': 'Materie comburenti',
      '5.2': 'Perossidi organici',
      '6.1': 'Materie tossiche',
      '6.2': 'Materie infettanti',
      '7': 'Materiali radioattivi',
      '7E': 'Materiali radioattivi (fissili)',
      '7X': 'Materiali radioattivi',
      '8': 'Materie corrosive',
      '9': 'Merci pericolose varie',
      '9A': 'Batterie al litio',
    } as Record<string, string>,
    packingGroups: { I: 'pericolo elevato', II: 'pericolo medio', III: 'pericolo basso' } as Record<string, string>,
    unClass: 'Classe',
    unKemler: 'Numero di pericolo',
    unLabels: 'Etichette di pericolo',
    unPacking: 'Gruppo di imballaggio',
    unNoMatch: 'N. ONU non trovato nella tabella ADR',
    unWater: 'Reagisce pericolosamente con l’acqua – NON usare acqua!',
    unLookupLabel: 'Scheda ERI (Cefic)',
    unLookupUrl: 'https://www.ericards.net/psp/ericards.psp_search_result?p_lang=6&lang=6&unnumber={un}',
    kemler: {
      '2': 'Gas (fuoriuscita sotto pressione o per reazione)',
      '3': 'Liquido / gas infiammabile',
      '4': 'Solido infiammabile',
      '5': 'Comburente (ossidante)',
      '6': 'Tossico / rischio di infezione',
      '7': 'Radioattivo',
      '8': 'Corrosivo',
      '9': 'Rischio di reazione spontanea violenta',
    } as Record<string, string>,
    kemlerDoubled: 'Pericolo intensificato (cifra raddoppiata)',

    labelField: 'Denominazione',
    countBySymbol: {
      'VKF Patientensammelstelle': 'Numero di pazienti',
      'VKF Sanitaetshilfsstelle': 'Numero di pazienti',
      'FW Verwundetennest': 'Numero di feriti',
      'VKF Totensammelstelle': 'Numero di deceduti',
      'VKF Sammelstelle': 'Numero di illesi',
      'VKF Rettungen': 'Numero di persone',
    },
    airflow: 'Direzione dell\'aria',
    airflowBlow: 'Immissione',
    airflowExtract: 'Aspirazione',
    stopSharing: 'Rimuovi la posizione',
    stopSharingTitle: 'Rimuove la posizione auto-segnalata di questa persona. Potrà ricondividerla in qualsiasi momento.',
    stopSharingFailed: 'Impossibile rimuovere la posizione.',
    caption: 'Etichetta',
    captionDefault: 'Standard',
    captionOff: 'Nessuna',
    captionAuto: 'Auto',
    captionAll: 'Tutte',
    swapEl: 'Trasferisci la condotta',
    fieldPlaceholders: {
      'Kapazität': 'p. es. 80 m³',
    },
    ergGuide: 'Guida ERG',
    ergPolymerization: 'Rischio di polimerizzazione (P) – il contenitore può scoppiare violentemente',
    ergIsolate: 'Isolamento (piccola quantità)',
    ergProtectDay: 'Distanza di protezione, giorno',
    ergProtectNight: 'Distanza di protezione, notte',
    ergLarge: 'Grande quantità',
    ergTable3: 'vedi ERG tabella 3 (contenitore/vento)',
    ergDayShort: 'Giorno',
    ergNightShort: 'Notte',
    ergSunrise: 'alba {t}',
    ergSunset: 'tramonto {t}',
    dockedTo: 'Agganciato a «{name}»',
    dockedRelease: 'Sgancia',
    ergAdopt: 'Applica come perimetro',
    ergRingsLabel: 'Raggio sulla mappa',
    ergRingsOff: 'No',
    ergRingsSmall: 'Piccolo',
    ergRingsLarge: 'Grande',
    ergSource: 'Fonte: {v} (PHMSA) – ausilio alla pianificazione, non validato',
    ergCameoLabel: 'CAMEO Chemicals (dettagli ERG)',
  },
  drawingEditor: {
    area: 'Superficie',
    drawing: 'Disegno',
    circle: 'Perimetro di sicurezza',
    radius: 'Raggio',
    fill: 'Riempimento',
    fillHatch: 'Tratteggiato',
    move: 'Sposta',
    moveArmed: 'Spostamento attivo – trascinare ovunque',
    rotateArmed: 'Rotazione attiva – trascinare ovunque',
    selectionBar: 'Selezione',
    points: 'Punti',
    color: 'Colore',
    width: 'Spessore',
    lineStyle: 'Linea',
    lineSolid: 'Continua',
    lineDashed: 'Tratteggiata',
    lineHalteliniUp: 'Linea d’arresto – denti sopra',
    lineHalteliniDown: 'Linea d’arresto – denti sotto',
    lineAbwurfzone: 'Zona di sgancio',
    label: 'Testo',
    labelPlaceholder: 'Etichetta …',
    areaLabelPlaceholder: 'es. Settore A',
    abschnittLeiter: 'Capo settore',
    abschnittLeiterPlaceholder: 'Scegliere il capo settore …',
    abschnittAuftrag: 'Compito',
    abschnittAuftragPlaceholder: 'es. Spegnimento edificio B',
    abschnittMaxHint: 'Direttiva FKS: al massimo 3–4 settori.',
    marker: 'Marcatore',
    markerPlaceholder: 'es. R',
    arrow: 'Punta della freccia',
    ending: 'Terminazione',
    endingNone: 'Nessuna',
    endingArrow: 'Freccia',
    endingArrowStop: 'Freccia con stop',
    endingTeilstueck: 'Tratto',
    endingNoneWhat: 'Senza chiusura',
    endingArrowWhat: 'Punta di freccia',
    endingArrowStopWhat: 'Freccia con barra d’arresto — limite di propagazione',
    endingTeilstueckWhat: 'Teilstück — forcella con tre attacchi',
    reverse: 'Inverti il senso',
    content: 'Tipo',
    contentPlain: 'Acqua',
    lineNo: 'Linea n.',
    lineNoDuplicate: 'La linea {n} esiste già qui',
    trupp: 'Appartiene alla squadra',
    truppShow: 'Mostra la squadra {name}',
    truppNone: 'Nessuna squadra',
    truppOut: 'fuori',
    floorTag: 'Piano',
    distance: 'Lunghezza',
    measurement: 'Misura',
    showOnMap: 'Sulla mappa',
    inputMode: 'Immissione',
    modeFreehand: 'Mano libera',
    modeNodes: 'Punti',
    on: 'Attivo',
    off: 'Spento',
    lock: 'Blocca',
    lockHint: 'Blocca la forma contro spostamenti accidentali; tieni premuto il lucchetto al centro per sbloccare.',
    unlockHold: 'Tieni premuto per sbloccare',

    connections: 'Collegamenti',
    connectedStart: 'Inizio',
    connectedEnd: 'Fine',
    connectedLines: 'Linee collegate ({n})',
    line: 'Linea',
    lineLabelNo: 'Linea {n}',
    route: 'Tracciato',
    routeDirect: 'Diretto',
    routeTrace: 'Traccia',
    detachConnection: 'Libera il collegamento',
    gpsFollowing: 'Il GPS segue attivamente',
    gpsMovingAway: 'Il veicolo si allontana',
    gpsContinue: 'Continua a seguire',
    gpsDetachOnSite: 'Libera sul luogo dell’intervento',
    gpsDetachHere: 'Libera qui (mantieni la traccia)',
    gpsDismiss: 'Nascondi',
    gpsPause: 'Interrompi il tracciamento',
    gpsAwayTitle: '{vehicle} si allontana · {distance} dal luogo dell’intervento',
    gpsAwayTitleBare: '{vehicle} si allontana',
    gpsAwaySub: '{lines} termina ancora sul luogo dell’intervento.',
    gpsAwaySubMany: '{lines} terminano ancora sul luogo dell’intervento.',
    gpsKeepOnSite: 'Lascia sul posto',
    gpsStoppedTitle: '{vehicle} · {distance} dal luogo dell’intervento',
    gpsStoppedTitleBare: '{vehicle} · tracciamento interrotto',
    gpsStoppedSub: 'Tracciamento interrotto · {lines} mostra il tragitto.',
    gpsStoppedSubMany: 'Tracciamento interrotto · {lines} mostrano il tragitto.',
    gpsBackTitle: '{vehicle} di nuovo sul luogo dell’intervento',
    gpsBackSub: '{lines} mostra il tragitto dalle {time}.',
    gpsBackSubMany: '{lines} mostrano il tragitto dalle {time}.',
    gpsRevert: 'Torna allo stato sul posto',
    gpsRevertAt: 'Torna allo stato sul posto ({time})',
    gpsRevertStep: '{name} tornata allo stato sul posto',
    gpsFollowingHead: '{line} · segue {vehicle} dalle {time}',
    gpsFollowingHeadBare: '{line} · segue {vehicle}',
    gpsStoppedHead: '{line} · tracciamento interrotto · {vehicle}',
    gpsDistanceNow: 'ora a {distance}',
    hiddenTarget: 'Bersaglio nascosto',
    revealTarget: 'Mostra il livello',
    removeConnectedTitle: 'Rimuovere {name}?',
    removeConnectedMessage: '{n} linee verranno liberate.',
    removeEMessage: 'Eliminare il tratto? {n} linee collegate verranno liberate.',
  },
  topBar: {
    offline: 'Offline',
    tiles: 'Tasselli',
    recording: 'REC',
    gpsFrozen: 'GPS congelato',
    gpsFrozenHint: 'Il feed GPS in tempo reale non risponde. I veicoli restano sull’ultima posizione nota.',
  },
  stepper: {
    less: 'meno',
    more: 'più',
    reset: 'reimposta',
    typeToEnter: 'Tocca per inserire',
  },
  confirm: {
    ok: 'OK',
    cancel: 'Annulla',
  },
  combo: {
    empty: 'Nessuna scelta',
    searchPlaceholder: 'Cerca persona …',
    searchOrType: 'Cerca o inserisci …',
    useTyped: 'Usa «{name}»',

    officersOnly: 'solo ufficiali',
  },
}
