// Italian copy · incident switcher, archive, history, Abschluss, data sources, replay.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/incident.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'incidentSwitcher' | 'archived' | 'history' | 'abschluss' | 'datenquellen' | 'personnelSync'
  | 'planPicker' | 'replay'

export const incidentCopy: Localizable<Pick<Copy, Keys>> = {
  incidentSwitcher: {
    noIncident: 'Nessun intervento',
    savedAt: 'Salvato alle {t}',
    saved: 'Salvato',
    badgePending: 'Non sincronizzato – salvataggio in corso',
    badgeOffline: 'Offline – salvato localmente, si sincronizza non appena riconnesso',
    badgeError: 'Sincronizzazione non riuscita – salvato localmente, si riproverà',
    badgeStorage: 'Memoria piena – le modifiche NON sono salvate localmente e andranno perse alla chiusura',
    storageShort: 'Memoria piena',
    syncNow: 'Sincronizza ora',
    incidents: 'Interventi',
    app: 'App',
    allIncidents: 'Tutti gli interventi',
    editMetaShort: 'Modifica',
    archiveShort: 'Chiudi',
    archive: 'Chiudi intervento',
    archiveOpen: '{n} in sospeso',
    share: 'Condividi l’intervento',
    shareShort: 'Condividi',
    report: 'Rapporto d’intervento',
    noOpenIncidents: 'Nessun intervento aperto',
    logout: 'Disconnetti',
    logoutTitle: 'Disconnettere?',
    logoutMsg: 'Dopo, questo dispositivo apre interventi solo dopo un accesso con PIN.',
    logoutOffline: 'Un nuovo accesso è possibile solo con la rete – fino ad allora questo dispositivo non apre alcun intervento.',
    logoutUnsyncedOne: '1 voce non è ancora stata trasmessa. Resta su questo dispositivo e sarà inviata appena accedi di nuovo.',
    logoutUnsyncedMany: '{n} voci non sono ancora state trasmesse. Restano su questo dispositivo e saranno inviate appena accedi di nuovo.',
    logoutUnsyncedChanges: 'Alcune modifiche non sono ancora state trasmesse. Restano su questo dispositivo e saranno inviate appena accedi di nuovo.',
    appVersion: 'Versione app (build)',

    startedRow: '{t} · {d}',
    startedFull: 'Inizio dell\'intervento {t} · {d}',
    offlineShort: 'Offline',
    errorShort: 'Errore di sync',
    syncErrorToast: 'Sincronizzazione non riuscita – le modifiche sono salvate localmente.',
    syncOfflineToast: 'Ancora offline – le modifiche vengono salvate localmente.',
    clockSkewToast: 'L\'orologio di questo dispositivo devia di {n} minuti – controlla gli orari registrati.',
    bootOffline: 'Offline – vengono mostrati i dati salvati.',
    bootListFailed: 'Impossibile caricare l\'elenco degli interventi',
    openFailed: 'Impossibile aprire l\'intervento',
    openFailedNoCache: 'Questo intervento non è salvato su questo dispositivo – serve una connessione',
    syncDone: 'Tutto sincronizzato',
    syncFailedToast: 'Sincronizzazione non riuscita – le modifiche restano salvate localmente.',
    editMeta: 'Modifica i dati dell\'intervento',
  },
  archived: {
    title: 'Intervento chiuso',
    hint: 'Il rapporto resta correggibile (aggiunte) – riaprire per tutto il resto.',
    hintViewOnly: 'Sola visualizzazione.',
    reactivate: 'Riapri',
    reactivateOffline: 'Richiede una connessione al server',
    reactivateNeedsServer: 'La riapertura richiede una connessione al server – l’intervento resta chiuso. Riprovare una volta online.',

    back: 'Indietro',
    closedElsewhere: 'L’intervento è stato chiuso su un altro dispositivo ({t})',
    closedElsewhereSub: 'Il rapporto resta correggibile (aggiunte) – riaprire per tutto il resto.',
    closedRefusedOne: '1 voce di questo dispositivo è arrivata dopo la chiusura e non è stata ripresa. Resta salvata su questo dispositivo.',
    closedRefused: '{n} voci di questo dispositivo sono arrivate dopo la chiusura e non sono state riprese. Restano salvate su questo dispositivo.',
    closedExport: 'Salva le voci',
    closedDismiss: 'Nascondi avviso',
    reopenedElsewhere: 'L’intervento è stato riaperto su un altro dispositivo ({t})',
    rapportClosedHint: 'Intervento chiuso – le modifiche al rapporto appaiono come aggiunte.',
    linkClosedTitle: 'Intervento chiuso – questa tabella mostra soltanto',
    linkRefusedTitle: 'Questo link non è più valido – questa tabella mostra soltanto',
    reopenedElsewhereSub: 'Di nuovo modificabile – le voci successive appaiono come aggiunte.',
    reopenedParkedOne: 'Di nuovo modificabile. 1 voce di questo dispositivo non ripresa dopo la chiusura viene inviata ora – come aggiunta.',
    reopenedParked: 'Di nuovo modificabile. {n} voci di questo dispositivo non riprese dopo la chiusura vengono inviate ora – come aggiunte.',
  },
  history: {
    title: 'Interventi',
    empty: 'Ancora nessun intervento.',
    noLocation: 'senza luogo',
    searchPlaceholder: 'Cerca intervento …',
    groupOpen: 'Aperti',
    groupToday: 'Oggi',
    groupWeek: 'Ultimi 7 giorni',
    offlineNote: 'Offline: la consultazione funziona; chiudere e riaprire richiedono una connessione al server.',
    since: 'dalle {t}',
    reactivate: 'Riapri',
    reactivateConfirmTitle: 'Riapri intervento',
    reactivateConfirmMsg: 'L\u2019intervento viene riaperto ed è modificabile. Le modifiche successive appaiono nel diario e nel rapporto come aggiunte.',
    reactivateConfirmBtn: 'Riapri',
    statusArchived: 'Chiuso',

    emptySub: 'Gli interventi aperti e chiusi appaiono qui.',
    archiveConfirmTitle: 'Chiudi l\'intervento',
    archiveConfirmMsg: 'L\'intervento viene chiuso e l\'ora di fine registrata. Le aggiunte successive appaiono nel diario e nel rapporto come supplementi.',
    archiveConfirmBtn: 'Chiudi',
    deleteExercise: 'Elimina',
    deleteConfirmTitle: 'Elimina l\'esercitazione',
    deleteConfirmMsg: 'L\'esercitazione e tutti i suoi dati (diario, foto, rapporto) vengono eliminati definitivamente. Non si può annullare.',
    deleteConfirmBtn: 'Elimina definitivamente',
    deleted: 'Esercitazione eliminata',
    deleteFailed: 'Eliminazione non riuscita',
  },
  abschluss: {
    leftEarly: ' · fino alle {t}',
    steps: {
      zeiten: 'Orari',
      anwesenheit: 'Presenze',
      mittel: 'Materiale',
      einsatzleiter: 'Capo intervento',
      kurzbericht: 'Rapporto breve',
      rueckmeldung: 'Riscontro alla CO',
      abweichungen: 'Divergenze',

      kontaktperson: 'Persona di contatto',
    },
    ausgerueckt: 'Partenza',
    ende: 'Fine intervento',
    personen: '{n} presenti',
    von: 'da',
    bis: 'a',
    mittelCount: '{n} posizioni',
    mittelNone: 'Niente usato',
    complete: 'Chiudere l’intervento',
    backToRapport: 'Torna al rapporto',
    confirmTitle: 'Chiudere l’intervento',
    confirmMsg: 'Il rapporto viene contrassegnato come chiuso e l’intervento chiuso. Le correzioni restano possibili e appaiono come aggiunte.',
    confirmBtn: 'Chiudere',
    confirmAnyway: 'Chiudere comunque',
    registeredOne: '1 squadra ancora annunciata ({list}).',
    registeredMany: '{n} squadre ancora annunciate ({list}).',
    registeredSafety: '{name}, squadra di sicurezza',
    registeredToBoard: 'Alla tavola',
    registeredTitle: 'Ancora annunciata',
    registeredStandDown: 'Chiudere come «non impiegata»',
    insideOne: '1 squadra è ancora dentro: {list}.',
    insideMany: '{n} squadre sono ancora dentro: {list}.',
    insideTrupp: 'Squadra {name}',
    insideClose: 'Chiudere comunque',
    insideTitle: 'Squadre ancora dentro',
    confirmBack: 'Indietro',
    done: 'Rapporto chiuso',
    doneMediaPending: 'Rapporto concluso · {n} foto/audio non ancora caricati – restano salvati e partono alla prossima apertura',
    failed: 'Chiusura non riuscita',
    corrected: 'Ore corrette: {name}',
    attendanceRemoved: 'Presenza di {name} rimossa',
  },
  datenquellen: {
    title: 'Fonti dati',
    uploaded: 'Caricato',
    uploadFailed: 'Caricamento non riuscito',
    invalidFilename: 'Il nome del file non produce un identificativo valido',
    layerAdded: 'Livello «{name}» aggiunto – visibile al prossimo caricamento',
    addLayerFailed: 'Impossibile aggiungere il livello',
    layerConflict: 'I livelli cartografici sono appena stati modificati altrove. Premi di nuovo «Aggiungi».',
    layerNoVersion: 'Non è stato possibile leggere la configurazione – il livello non è stato salvato. Controllare la connessione e ricaricare la pagina.',
    globalDatasets: 'Set di dati globali',
    objectsCount: 'oggetti',
    replace: 'Sostituisci',
    adminOnlyNote: 'Per sostituire un set di dati o aggiungere un livello occorre che /admin sia sbloccato in questo browser (ADMIN_SECRET).',
    newGeoLayer: 'Nuovo livello geo …',
    chooseGeojson: 'Scegli GeoJSON …',
    labelPlaceholder: 'Denominazione (es. idranti)',
    groupPlaceholder: 'Gruppo (es. acqua)',
    defaultGroup: 'Riferimento',
    kindLines: 'Linee',
    kindPoints: 'Punti',
    color: 'Colore',
    adding: 'Caricamento …',
    add: 'Aggiungi',
    geojsonNoteBefore: 'GeoJSON in WGS84 [lng, lat]. Salvato come set di dati globale ',
    geojsonNoteAfter: '.',
    incidentObjects: 'Oggetti dell’intervento',
    plansWord: 'piani',
    nearby: 'Nelle vicinanze ({n})',
    allOther: 'Tutti gli altri oggetti',
    allObjects: 'Tutti gli oggetti',
  },
  personnelSync: {
    title: 'Sincronizza effettivo con {provider}',
    unknownError: 'Errore sconosciuto',
    syncFailed: 'Sincronizzazione non riuscita',
    countNew: 'nuovi',
    countUpdated: 'aggiornati',
    countUnchanged: 'invariati',
    countStale: 'non più in {provider}',
    querying: 'Interrogazione di {provider} …',
    done: 'Sincronizzazione completata.',
    resultCreated: '{n} creati',
    resultUpdated: '{n} aggiornati',
    resultReactivated: ' (di cui {n} riattivati)',
    resultUnchanged: '{n} invariati',
    resultDeactivated: '{n} disattivati',
    staleHide: 'Nascondi {n} persone non più presenti in {provider} (mantenute per i vecchi interventi, non eliminate)',
    syncing: 'Sincronizzazione …',
    sync: 'Sincronizza',
  },
  planPicker: {
    searchPlaceholder: 'Cerca nome o indirizzo …',
    autoNextObject: 'Oggetto più vicino automaticamente',
    loading: 'Caricamento oggetti …',
    loadFailed: 'Impossibile caricare gli oggetti.',
    noObject: 'Nessun oggetto trovato.',
    planOne: 'piano',
    planMany: 'piani',
    mapNote: 'Coordinate in parte imprecise – fa fede l’elenco.',
    hideMap: 'Nascondi carta',
    showMap: 'Mostra carta',
  },
  replay: {
    region: 'Riproduzione diario',
    banner: 'DIARIO · RIPRODUZIONE',
    subtitle: 'Vista in sola lettura del passato',
    backToLive: 'Torna in diretta',
    loadFailed: 'Impossibile caricare il diario.',
    loading: 'Caricamento diario …',
    transport: 'Riproduzione',
    skipBack: 'Evento precedente',
    skipFwd: 'Evento successivo',
    skipped: '{span} saltati',
    gapTitle: '{span} senza eventi',
    sinceAlarm: '{span} dall’allarme',
    pause: 'Pausa',
    speed: 'Velocità',
    timepoint: 'Momento',
    now: 'Ora',
    laneLabel: 'Diario',
    captionOpen: 'nel diario',
    laneEntries: '{n} voci',
    captionNone: 'Nessuna voce in questo momento',
  },
}
