// Italian copy · the Einsatz wizard (intake).
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/intake.ts.

import type { Copy, Localizable } from '../index'

export const intakeCopy: Localizable<Pick<Copy, 'intake'>> = {
  intake: {
    titleNew: 'Apri intervento',
    locationHead: 'Posizione',
    addressLabel: 'Indirizzo',
    addressPlaceholder: 'Via n., NPA località',
    addressSearching: 'Ricerca …',
    addressNoHits: 'Nessun indirizzo trovato',
    objectButton: 'Dai piani',
    objectSearchPlaceholder: 'Cerca oggetto o indirizzo …',
    objectNear: 'Nelle vicinanze',
    objectNoHits: 'Nessun oggetto trovato',
    objectPlans: (n: number) => (n === 1 ? '1 piano' : `${n} piani`),
    objectNoPlans: 'nessun piano',
    mapPickButton: 'Sulla carta',
    coordSet: 'Coordinata impostata',
    coordNone: 'Nessuna posizione – verrà aperto senza coordinata',
    coordClear: 'Rimuovi posizione',
    coordFold: 'Coordinate',
    keywordHead: 'Parola chiave e categoria',
    titleLabel: 'Parola chiave / titolo',
    titlePlaceholder: 'es. Incendio edificio scuola',
    categoryLabel: 'Categoria',
    detailsPlaceholder: 'Indicazioni aggiuntive sulla segnalazione',
    open: 'Apri intervento',
    opening: 'Apertura …',
    cancel: 'Annulla',
    errorCreate: 'Creazione non riuscita',
    errorTake: 'Rilevamento non riuscito',
    errorUpdate: 'Aggiornamento non riuscito',
    editTitle: 'Modifica dati intervento',
    save: 'Salva',
    saving: 'Salvataggio …',
    created: 'Intervento creato',
    taken: 'Allarme rilevato',
    updated: 'Intervento aggiornato',
    alarmierungHead: 'Allarme',
    alarmTime: 'Ora dell’allarme',
    alarmMessage: 'Messaggio d’allarme',
    addressUnknown: 'Indirizzo sconosciuto',
    alarmOpen: 'Apri',
    alarmOpening: 'Apertura …',
    dismiss: 'Scarta',
    manualIncident: 'Intervento manuale',
    attach: 'Aggiungi a un intervento esistente',
    attachShort: 'A intervento',
    attachConfirmTitle: 'Aggiungere «{alarm}» a questo intervento?',
    attachHint: 'Il messaggio d\u2019allarme finisce nel giornale, i tempi GPS seguono automaticamente. Parola chiave e luogo dell\u2019intervento restano invariati.',
    attachConfirm: 'Aggiungi',
    attachDone: 'Allarme aggiunto all\u2019intervento',
    attachError: 'Aggiunta non riuscita',
    newDiveraAlarm: 'Nuovo allarme',
    hide: 'Nascondi',
    fromDivera: 'Rilevato dalla fonte di allarme',
    reviewTitle: 'Verificare i dati dell’intervento',
    locationSet: 'Posizione impostata',
    noLocationOnMap: 'Nessuna posizione – imposta sulla carta',
    ok: 'Va bene',
    // Etichette di VISUALIZZAZIONE per l'elenco categorie — il valore inviato resta in tedesco.
    kategorienLabels: {
      'Brandbekämpfung': 'Lotta antincendio',
      'Strassenrettung': 'Soccorso stradale',
      'Technische Hilfeleistung': 'Aiuto tecnico',
      'Elementarereignis': 'Eventi naturali',
      'Ölwehr': 'Intervento antinquinamento (idrocarburi)',
      'Chemiewehr': 'Intervento chimico',
      'Strahlenwehr': 'Intervento radiologico',
      'Einsatz Bahnanlagen': 'Intervento ferroviario',
      'BMA / unechte Alarme': 'RAI / falsi allarmi',
      'Gerettete Tiere': 'Salvataggio animali',
      'Dienstleistungen': 'Prestazioni di servizio',
      'Diverse Einsätze': 'Interventi diversi',
    },

    hereButton: 'Qui',
    hereFailed: 'Posizione non disponibile',
    exerciseNo: 'No',
    exerciseYes: 'Sì',
    exerciseLabel: 'Esercitazione',
    exerciseSub: 'Non conta nella statistica degli interventi',
    moveConfirmTitle: 'Spostare il luogo d\'intervento?',
    moveConfirmMsg: 'Il luogo d\'intervento verrà posto sulla tua posizione attuale – a {d} da quella precedente. La carta, l\'inquadratura dello schizzo e i piani d\'oggetto vicini si adeguano.',
    moveConfirmBtn: 'Sposta',
    alarmTextUnavailable: 'Impossibile caricare il messaggio d\'allarme – resta invariato',
    demoBlocked: 'Disattivato nella demo – qui non si può aprire un nuovo intervento.',
  },
}
