// Italian copy · the Verlauf / journal and error sentences.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/journal.ts.

import type { Copy, Localizable } from '../index'

export const journalCopy: Localizable<Pick<Copy, 'journal' | 'errors'>> = {
  journal: {
    delivery: {
      failedTitleOne: '1 voce non trasmessa',
      failedTitle: '{n} voci non trasmesse',
      storageTitle: 'Voci non salvate in modo sicuro',
      storageBody: 'Mantieni aperta l’app e salva una copia. Chiudendo l’app, queste voci potrebbero andare perse.',
      savedBody: 'Salvate su questo dispositivo. Queste voci mancano sugli altri dispositivi.',
      offlineBody: 'Salvate su questo dispositivo. La trasmissione riprende automaticamente quando è disponibile una connessione.',
      retry: 'Riprova', retrying: 'Nuovo tentativo …', export: 'Salva le voci', short: 'Voci non trasmesse',
      refusedTitleOne: '1 evento di protocollo non previsto per questo ruolo',
      refusedTitle: '{n} eventi di protocollo non previsti per questo ruolo',
      refusedBody: 'Il server non accetta questi eventi da questo accesso. Restano su questo dispositivo e possono essere salvati; il diario non ne è interessato.',
      closedTitleOne: '1 voce non ripresa dopo la chiusura',
      closedTitle: '{n} voci non riprese dopo la chiusura',
      closedBody: 'L’intervento era già chiuso quando queste voci hanno raggiunto il server. Non sono nel diario, ma restano su questo dispositivo e possono essere salvate. Se l’intervento viene riaperto, vengono inviate.',
      closedShort: 'Voci non riprese dopo la chiusura – salvarle',
    },
    open: 'Diario',
    add: 'Voce',
    addHint: 'Tocca per una voce · tieni premuto, poi scorri su memo vocale o foto',
    title: 'Diario',
    empty: 'Nessun evento registrato',
    surfaceMap: 'Mappa',
    surfacePlan: 'Piano',
    replay: 'Avvia riproduzione',
    replayHint: 'Riproduci situazione e piano a un momento precedente',
    composerTitle: 'Nuova voce',
    textPlaceholder: 'Cosa è successo? Segnalazione, osservazione, decisione …',
    typeLabel: 'Tipo',
    entryTypes: { info: 'Info', auftrag: 'Ordine', sofort: 'Misura immediata' } as Record<string, string>,
    entryTypesWrap: { info: 'Info', auftrag: 'Ordine', sofort: 'Misura immediata' } as Record<string, string>,
    record: 'Registra',
    recordStop: 'Ferma registrazione',
    discardAudio: 'Scarta registrazione',
    attachUpload: 'Carica file',
    attachUploadShort: 'File',
    attachLabel: 'Allegato',
    attachDiscard: 'Rimuovi allegato',
    attachOpen: 'Scarica allegato',
    attachOffline: 'Il caricamento richiede una connessione. Riselezionare il file più tardi.',
    attachTooLarge: 'File troppo grande. Massimo: {max} MB.',
    attachUnsupported: 'Questo tipo di file non è supportato.',
    attachUploadFailed: 'Caricamento del file non riuscito. Verificare la connessione e riprovare.',
    attachDropped: 'Allegato «{name}» scartato – selezionarlo di nuovo.',
    attachPrint: 'Allegato: {names}',
    attachPrintMany: 'Allegati: {names}',
    attachAudioExtra: 'Una sola registrazione per voce – «{names}» non acquisito.',
    audioClipLabel: 'Nota vocale',
    audioImportLabel: 'Registrazione audio esterna',
    audioStartLabel: 'Inizio registrazione',
    audioStartHint: 'Verificare l’ora di inizio con il memo vocale.',
    audioStartConfirm: 'Confermare l’ora di inizio',
    audioImportedNote: 'Registrazione audio esterna ({duration})',
    audioDiscardImport: 'Rimuovi file audio',
    audioUploading: 'Caricamento …',
    audioOffline: 'Il caricamento audio richiede una connessione. Riselezionare il file più tardi.',
    audioTooLarge: 'File audio troppo grande. Massimo: {max} MB.',
    audioUnsupported: 'Questo formato audio non è supportato.',
    audioUploadFailed: 'Caricamento non riuscito. Verificare la connessione e riprovare.',
    audioImportDropped: 'Registrazione audio esterna «{name}» scartata – selezionarla di nuovo.',
    playerOpen: 'Riascolta',
    editEntry: 'Modifica testo',
    removeEntry: 'Elimina voce',
    entryRemoved: 'Voce eliminata',
    playerEntryHere: 'Voce in questo punto',
    playerEntryPlaceholder: 'Cosa si è sentito? Messaggio, decisione …',
    playerEntries: 'Voci in questa registrazione',
    playerNoEntries: 'Ancora nessuna voce in questa finestra.',
    playerSkipBack: '15 secondi indietro',
    playerSkipFwd: '15 secondi avanti',
    playerSpeed: 'Velocità di riproduzione',
    playerSeek: 'Posizione di riproduzione',
    playerOffline: 'La riproduzione richiede una connessione.',
    sttTranscribe: 'Trascrivi',
    sttRunning: 'Trascrizione in corso … Può richiedere alcuni minuti.',
    sttFailed: 'Trascrizione non riuscita: {error}',
    sttRetry: 'Riprova',
    sttErrorGeneric: 'server non raggiungibile',
    sttBanner: '{n} bozze rilevate – verificare e acquisire.',
    sttTakeAll: 'Acquisisci tutte',
    sttTake: 'Acquisisci',
    sttDismiss: 'Scarta',
    sttEmpty: 'Nessun parlato rilevato.',
    photo: 'Foto',
    photoNote: 'Foto',
    discardPhoto: 'Scarta foto',
    send: 'Registra',
    saved: 'Voce registrata',
    transcriptPlaceholder: 'Aggiungi trascrizione',
    transcriptSave: 'Salva',
    transcriptEdit: 'Modifica trascrizione',
    transcriptAdd: 'Aggiungi trascrizione',
    nachtrag: 'Aggiunta',
    corrected: 'corretto {t}',
    // ⚠️ il numero TOTALE di occorrenze, lo stesso che il rapporto stampa come «N×» — vedi la base tedesca
    repeated: 'in totale {n}×',
    repeatedTitle: 'Quante volte in totale il messaggio compare nel verbale – ognuna resta.',
    correctHint: 'Il testo originale resta nel verbale.',
    viaAtemschutzLink: 'Link APR',
    viaAtemschutzLinkTitle: 'Inserito sulla tabella APR ceduta.',
    detailTime: 'Ora',
    detailArea: 'Ambito',
    detailSource: 'Fonte',
    detailSourceManual: 'Inserito a mano',
    detailSourceSystem: 'Registrato dall’app',
    detailSourceSystemHint: 'Le righe di sistema non sono modificabili',
    detailAttachments: 'Allegati',
    detailAttachmentsN: '{n} immagini',
    detailAttachmentsOne: 'Un’immagine',
    detailCorrected: 'Corretto',
    detailCorrectedFirst: 'prima: {text}',
    detailRepeated: 'Ripetuto',
    detailRepeatedN: 'in totale {n}× fino alle {t}',
    detailNachtrag: 'Aggiunta',
    detailNachtragHint: 'inserito dopo la chiusura dell’intervento',
    arrowTitle: 'Inserisci la freccia – chi a chi',
    arrowBackTitle: 'Inserisci la freccia – chi da chi',
    dueHead: 'Ricordare',
    dueNone: 'Senza promemoria',
    dueSetTitle: 'Ricorda alle {t}',
    dueExactTitle: 'Ricordare alle',
    dayToday: 'Oggi',
    dayTomorrow: 'Domani',
    duePast: 'Il momento è già passato',
    reminderExact: 'Ora …',
    reminderChipLabel: 'tra {n} min',
    reminderTomorrow: ' · domani',
    reminderSaved: 'Promemoria impostato',
    reminderCreated: 'Promemoria impostato per le {t}: {text}',
    dueTitle: 'Promemoria in scadenza',
    dueOne: 'Promemoria in scadenza',
    dueDone: 'Fatto',
    dueSnooze: '+10 min',
    dueOpen: 'Apri nel diario',
    openCount: '{n} aperti',
    doneLog: 'Promemoria completato: {text}',
    reopenLog: 'Promemoria riaperto: {text}',
    snoozeLog: 'Promemoria +{mins} min: {text}',
    dueAtLabel: 'scade {t}',
    overdueLabel: 'scaduto',
    markDoneTitle: 'Segna come fatto',
    againChip: '{mins} min',
    againTitle: 'Ricordamelo di nuovo tra {mins} minuti',
    legend: 'Legenda',
    legendPendenzOpen: 'Pendenza aperta',
    legendPendenzUrgent: 'Pendenza urgente',
    legendPendenzDone: 'Pendenza conclusa',
    search: 'Cerca nel diario',
    searchPlaceholder: 'Cerca …',
    searchClose: 'Chiudi la ricerca',
    searchCount: '{n} di {m}',
    searchEmpty: 'Nessun risultato per «{q}»',
    searchEmptyHint: 'Si cerca nel testo e nei nomi di persone e squadre. Un errore di battitura è tollerato.',
    filter: 'Filtra il diario',
    filterArt: 'Tipo di voce',
    filterArea: 'Ambito',
    filterAll: 'Mostra tutto',
    filterActive: 'Filtrato:',
    filterEmpty: 'Nessuna voce in questa selezione',
    filterEmptyHint: '«Mostra tutto» rimuove il filtro.',

    stripLabel: 'Linea del tempo – tocca per saltare al punto corrispondente',
    photoOpen: 'Vedi la foto in grande',
    mediaPending: 'Caricamento',
    mediaFailed: 'Non caricato',
    attendanceConflict: 'Presenza {name}: {what} – controlla.',
    // ⚠️ Frammenti, non frasi: uniti con « · » e inseriti in {what} qui sopra, che ha già scritto
    // «Presenza {name}: ». Ciò che quella riga dice già non si ripete qui.
    attendanceConflictTwoNotes: 'due funzioni – «{a}» e «{b}»',
    attendanceConflictOneNote: 'funzione «{a}» su un solo dispositivo',
    attendanceConflictStatus: 'stato divergente',
    attendanceConflictOrt: 'posizione divergente',
    attendanceConflictTimes: 'orari divergenti',
    truppConflict: 'Protezione respiratoria {name}: modifiche di due dispositivi unite – controlla.',
    tafelConflict: 'Lavagna «{page}» · {where}: modificato su due dispositivi contemporaneamente – vale «{kept}» (più recente), «{lost}» sovrascritto. Controlla.',
    attendanceConflictOther: 'voci divergenti unite',
    attendanceConflictResolved: 'Divergenza {name} verificata – {taken}, {by}',
    attendanceConflictByUnknown: 'senza nome',
    attendanceConflictFromKp: 'dato dal posto comando',
    attendanceConflictFromCapture: 'dato dal foglio di rilevamento',
    attendanceConflictKeepBoth: 'entrambi i dati sono corretti',
    attendanceConflictOpenEnd: 'aperto',
    attendanceConflictTake: 'Riprendi {side}',
    attendanceConflictKeep: 'Entrambi corretti',
    attendanceConflictOpenTitle: 'Divergenze',
    attendanceConflictOpenCount: '{n} aperte',
    attendanceConflictNoneOpen: 'Nessuna aperta',
    attendanceConflictCheckedAt: 'verificata {t} · {by}',
    quickPhrasesAria: 'Frasi tipo',
    openRemindersHead: 'Pendenze',
    // l'interruttore ○ accanto ai chip Art — tre stati su un unico comando
    openStates: ['Tenere aperto', 'Resta aperto – compare tra le pendenze', 'Urgente – va in cima'] as string[],
    pendenzSaved: 'Pendenza registrata',
    pendenzUrgentSaved: 'Pendenza registrata – urgente',
    pendenzDoneLog: 'Pendenza conclusa: {text}',
    pendenzReopenLog: 'Pendenza riaperta: {text}',
    noteOnTitle: 'Segnalazione',
    noteOnLabel: 'su ',
    noteOnClear: 'Scollega',
    linkPendenzTitle: 'Segnalazione su',
    pendenzNew: 'Nuova pendenza',
    pendenzNewUrgent: 'Pendenza urgente',
    pendenzNotOpen: 'Non tenere aperta',
    noteSaved: 'Segnalazione registrata',
    noteChip: 'Pendenza',
    noteOpen: 'Registrare una segnalazione',
    ageLabel: '{n}′',
    ageLabelHours: '{n} h',
    ageToggle: 'Alterna ora / età',
    openState: 'aperto',
    openReminderGo: 'Vai alla voce',
  },
  errors: {
    serverUnreachable: 'Errore di rete – server non raggiungibile',
    serverTimeout: 'Il server non risponde – timeout',

    updateFailed: 'Aggiornamento non riuscito',
    serverUnreachableHint: 'Nessuna rete, o il server non è a questo indirizzo. Gli interventi salvati restano disponibili offline.',
    serverTimeoutHint: 'La connessione c\'è, ma non torna nulla – tipico di un Wi-Fi che muore. Gli interventi salvati restano disponibili offline.',
    httpUnauthorized: 'Sessione scaduta',
    httpUnauthorizedHint: 'Effettua di nuovo l\'accesso.',
    httpForbidden: 'Non autorizzato',
    httpForbiddenHint: 'Questo account non può farlo. Accedi con un account che ha il diritto di modifica.',
    httpNotFound: 'Non trovato sul server',
    httpNotFoundHint: 'Il server non conosce questo indirizzo. Forse gira una versione diversa.',
    httpTooLarge: 'File troppo grande',
    httpTooLargeHint: 'Il server non accetta file di questa dimensione.',
    httpStale: 'Pagina non aggiornata',
    httpStaleHint: 'Questa pagina conosce uno stato più vecchio. Ricarica e ripeti la modifica.',
    httpTooMany: 'Troppi tentativi',
    httpTooManyHint: 'Attendi un momento, poi riprova.',
    httpRejected: 'Richiesta rifiutata',
    httpRejectedHint: 'Il server ha respinto la richiesta.',
    httpGateway: 'Server irraggiungibile',
    httpGatewayHint: 'Il server non risponde – probabilmente sta riavviando. Riprova tra poco; gli interventi salvati restano disponibili offline.',
    httpServerError: 'Errore sul server',
    httpServerErrorHint: 'La richiesta è arrivata, il server non è riuscito a gestirla. Riprova – se persiste, non dipende dal dispositivo.',
    httpCode: 'Codice di errore {code}',
  },
}
