// Italian copy · the Lagemeldung and the Führungsrhythmus.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/lagemeldung.ts.

import type { Copy, Localizable } from '../index'

export const lagemeldungCopy: Localizable<Pick<Copy, 'lagemeldung'>> = {
  lagemeldung: {
    title: 'Rapporto di situazione',
    chip: 'Situazione',
    chipIn: 'Situazione · tra {m}′',
    chipDue: 'Situazione dovuta',
    chipOff: 'Situazione · spento',
    chipHint: 'Comporre un rapporto di situazione',
    chipAria: 'Rapporto di situazione – {state}',
    modeSeit: 'Da {t}',
    modeVoll: 'Completo',
    modeFirst: 'Primo rapporto',
    modeLabel: 'Ambito',
    firstNote: 'Ancora nessun rapporto di situazione · tutto è nuovo',
    seitNote: 'Solo ciò che è cambiato da {t} · il vitale sempre',
    vollNote: 'Tutto ciò che vale – consegna, corpo vicino, Rück',
    slots: {
      zuerst: 'Prima', lage: 'Situazione', menschen: 'Persone', gefahren: 'Pericoli', massnahmen: 'Misure',
      mittel: 'Mezzi', bedarf: 'Bisogni', naechste: 'Prossimo', zusatz: 'Inoltre',
    } as Record<string, string>,
    tags: {
      neu: 'Nuovo', schlechter: 'Peggio', besser: 'Meglio', erledigt: 'Fatto', gleich: 'ancora',
    } as Record<string, string>,
    tagSchaetzung: 'Stima',
    tagSchaetzungTitle: 'Aiuto alla pianificazione – stimato dall\'andamento della pressione, non una misura',
    tagRegister: 'Registro',
    tagRegisterTitle: 'Indicazione del registro (REA, UFE) – può essere superata, verificare sul posto',
    tick: 'Includere nel rapporto',
    untick: 'Togliere dal rapporto',
    dropT0: 'Vitale – toglierlo comunque?',
    dropT0Yes: 'Togliere',
    editLine: 'Modificare la riga',
    editDone: 'Fatto',
    addLine: 'Riga propria',
    addLinePlaceholder: 'Cosa va ancora detto',
    hidden: 'Nascosto ({n})',
    hiddenNone: 'Niente di nascosto',
    hiddenReasons: {
      gleich: 'invariato da {t}',
      declined: 'omesso {t}',
      budget: 'oltre la durata radio',
      routine: 'routine',
      offer: 'sfondo',
      superseded: 'sostituito da «{by}»',
      dispatch: 'la centrale lo sa',
      inLine: 'compreso in «{slot}»',
    } as Record<string, string>,
    hiddenAdd: 'Aggiungere',
    hiddenAddAria: 'Aggiungere «{text}» al rapporto',
    words: '{n} parole',
    seconds: '≈ {s} s',
    overBudget: 'Più lungo di un messaggio radio ({n} parole)',
    radio: 'Vista radio',
    radioClose: 'Torna alla bozza',
    share: 'Condividere',
    shareCopied: 'Rapporto di situazione copiato',
    shareFailed: 'Condivisione non possibile',
    more: 'Altre azioni',
    send: 'Trasmesso',
    sendHint: 'Scrive il rapporto nel diario e pianifica il prossimo',
    close: 'Chiudere senza salvare',
    source: 'Bozza da gruppi, carta, diario, orari dei veicoli · nulla salvato prima di «Trasmesso»',
    empty: 'Niente di nuovo da {t}.',
    emptyFirst: 'Ancora nulla nel dossier – completare situazione, persone, mezzi a mano.',
    row: 'Rapporto di situazione {t}: {text}',
    rowVoll: 'Rapporto di situazione {t} (completo): {text}',
    sentToast: 'Rapporto di situazione {t} nel diario',
    undoneLog: 'Rapporto di situazione {t} ritirato',
    next: 'Prossimo rapporto verso le {t}.',
    nextHandover: 'Prossimo rapporto alla consegna.',
    nextNone: 'Nessun altro rapporto previsto.',
    rhythm: 'Ritmo',
    rhythmEvery: '{m}′',
    rhythmHandover: 'Consegna',
    rhythmOff: 'Spento',
    rhythmOffAction: 'Spegnere il ritmo',
    rhythmOffLog: 'Ritmo dei rapporti di situazione spento',
    rhythmOnLog: 'Ritmo dei rapporti di situazione {m}′ · prossimo {t}',
    rhythmWindDown: 'Fuoco spento – allungare il ritmo?',
    nextLog: 'Prossimo rapporto di situazione alle {t}',
    reminderText: 'Rapporto di situazione',
    dueTitle: 'Rapporto di situazione dovuto',
    dueLast: 'ultimo {t}',
    dueNone: 'ancora nessun rapporto di situazione',
    dueChanges: '{n} cambiamenti',
    dueChangesOne: '1 cambiamento',
    dueUrgent: '{n} urgenti',
    dueOpen: 'Rapporto',
    dueSnooze: '+10′',
    phraseOffer: 'Comporre il rapporto di situazione',
    truppNo: 'Gruppo {n}',
    truppBare: 'Gruppo',
    truppPressure: '{trupp} pressione d\'allarme {bar} bar, ritirata{where}.',
    truppContact: '{trupp} in ritardo, nessun contatto radio da {m}′{where}.',
    truppEnded: '{trupp}: allarme cessato.',
    where: ', {w}',
    vermisstOne: '1 persona dispersa{where}.',
    vermisstMany: '{n} persone disperse{where}.',
    eingesperrtOne: '1 persona bloccata{where}.',
    eingesperrtMany: '{n} persone bloccate{where}.',
    keineVermissten: 'Nessun altro disperso.',
    gerettetOne: '1 persona salvata{extra}.',
    gerettetMany: '{n} persone salvate{extra}.',
    anSanitaet: ', consegnata al servizio sanitario',
    geraeumt: 'Edificio evacuato.',
    keinePersonen: 'Nessuno nell\'edificio.',
    un: 'Sostanza pericolosa ONU {un}{stoff}{dist}.',
    unDist: ', perimetro {m} m',
    unDone: 'Sostanza pericolosa ONU {un}: fatto.',
    hazard: '{label}{where}.',
    hazardDone: '{label}: fatto.',
    gas: 'Riscaldamento a gas nell\'edificio.',
    oil: 'Riscaldamento a olio nell\'edificio.',
    pv: 'Impianto FV sul tetto.',
    gasAb: 'Gas chiuso.',
    stromAb: 'Corrente staccata.',
    geschosse: '{n} piani.',
    wind: 'Vento girato a {dir}.',
    unterKontrolle: 'Incendio sotto controllo {t}.',
    feuerAus: 'Fuoco spento {t}{extra}.',
    nachloesch: ', bonifica in corso',
    lageTitle: '{title}.',
    lageDamage: '{list}.',
    feuerGeloescht: 'Fuoco spento {t}.',
    trupps: '{n} gruppi impiegati: {list}.',
    truppsOne: '1 gruppo impiegato: {list}.',
    truppsShort: '{n} gruppi impiegati.',
    truppsShortOne: '1 gruppo impiegato.',
    sitr: 'Gruppo di sicurezza pronto.',
    asEnded: 'Protezione respiratoria terminata, tutti i gruppi fuori.',
    bereit: 'Pronto: {list}.',
    mittelOn: '{list} sul posto',
    mittelComing: '{list} in arrivo',
    mittelNew: 'nuovo {list}',
    mittelLeft: '{list} rientrato',
    mittelShort: '{n} veicoli nuovi',
    mittelShortOn: '{n} veicoli sul posto',
    adf: '{n} militi.',
    nachalarm: 'Allarme supplementare {title}.',
    abloesungJetzt: 'Cambio protezione respiratoria ora.',
    abloesungBald: 'Cambio protezione respiratoria tra ca. {m}′.',
    verstaerkung: 'Rinforzo richiesto, non ancora sul posto.',
    bedarfNone: 'nessuno più.',
    bedarfDone: '{text}: fatto.',
    reminderSoon: '{text} ({t}).',
    routineSymbolsOne: '1 voce di simbolo',
    routinePhotosOne: '1 foto',
    routineTeamOne: '1 voce protezione respiratoria',
    routineSymbols: '{n} voci di simboli',
    routinePhotos: '{n} foto',
    routineTeam: '{n} voci protezione respiratoria',
    routineDispatch: 'Testo d\'allarme',
    routineElTaken: '«Direzione d\'intervento assunta»',
  },
}
