// Italian copy · incident and standing links, shared positions.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/links.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'incidentLink' | 'standingLink' | 'sharePosition' | 'livePosition'

export const linksCopy: Localizable<Pick<Copy, Keys>> = {
  incidentLink: {
    opening: 'Apertura dell\'intervento …',
    pendingTitle: 'Intervento non ancora disponibile',
    pendingHint: 'L\'allarme è appena arrivato. Nuovo tentativo automatico …',
    notReadyTitle: 'Questo intervento non è disponibile.',
    notReadyHint: 'Il link vale solo finché l\'intervento è in corso. Se l\'allarme è appena arrivato, l\'intervento forse non è ancora pronto – altrimenti avvisare il comando d\'intervento.',
    invalidTitle: 'Questo link non è più valido.',
    invalidHint: 'Apri il link direttamente dal messaggio d\'allarme attuale.',
    disabledTitle: 'I link d\'intervento non sono attivati in questo corpo pompieri.',
    disabledHint: 'Il comando d\'intervento può attivarli nella configurazione.',
    offlineTitle: 'Nessun segnale',
    offlineHint: 'Senza connessione l\'intervento non può essere aperto.',
    errorTitle: 'Il server non risponde.',
    errorHint: 'Se il problema persiste, avvisare il comando d\'intervento.',
    retry: 'Riprova',
    closedTitle: 'Intervento chiuso',
    closedAt: 'Chiuso alle {time}.',
    closedHint: 'Se l’intervento viene riaperto, il tabellone ricompare qui da solo.',
    unavailable: 'Questo intervento non è raggiungibile al momento. Ricarica la pagina appena hai di nuovo segnale.',
  },
  standingLink: {
    idleTitle: 'Nessun intervento in corso',
    // una frase per superficie (09.09., vedi de/links.ts)
    idleHintTerminal: 'Appena arriva un allarme, questo schermo passa da solo all\'intervento.',
    idleHintAs: 'Appena è in corso un intervento o un\'esercitazione, questo codice apre la sorveglianza APR.',
    terminalKicker: 'Terminale di caserma',
    checkedLabel: 'Ultimo controllo',
    chooseTitle: 'Più interventi in corso',
    chooseHint: 'Scegli quale intervento deve mostrare questo schermo.',
    exerciseTag: 'Esercitazione',
    notEnrolledTitle: 'Questo dispositivo non è configurato come terminale di caserma.',
    notEnrolledHint: 'Nell\'amministrazione, sotto «Link e accessi», generare il link di configurazione e aprirlo su questo dispositivo.',
    asInvalidTitle: 'Questo codice per la protezione respiratoria non è più valido.',
    asInvalidHint: 'Il codice è stato rinnovato. Stampare il codice QR attuale nell\'amministrazione e appenderlo.',
    disabledTitle: 'Questa funzione non è attivata.',
    disabledHint: 'L\'amministrazione può attivarla sotto «Link e accessi».',
  },
  sharePosition: {
    askTitle: 'Condividere la tua posizione?',
    askBody: 'Il posto comando vede allora sulla carta della situazione dove sei – così è chiaro chi lavora dove (p. es. al trasporto d\'acqua) e chi è raggiungibile.',
    askWho: 'Visibile solo al posto comando. Gli altri che hanno il link dell\'intervento non vedono la tua posizione.',
    askHowLong: 'Solo finché questo intervento è in corso. Alla chiusura la posizione viene cancellata.',
    askBackground: 'Se blocchi il telefono non viene più trasmesso nulla – l\'ultima posizione resta, con la sua ora.',
    askAgain: 'Devi attivare la condivisione tu stesso a ogni intervento – non parte mai da sola.',
    pickTitle: 'Chi sei?',
    pickHint: 'Così il tuo punto sulla carta ha un nome.',
    pickAgain: 'Nuovo intervento – conferma di nuovo chi sei. L\'ultimo nome scelto è in cima.',
    pickLast: 'ultimo',
    search: 'Cerca un nome …',
    yes: 'Sì, condividi la posizione',
    no: 'No grazie',
    menuOff: 'Condividi la posizione',
    menuOn: 'Condivisione della posizione – attiva',
    menuClosed: 'Solo finché l\'intervento è in corso',
    menuDemo: 'Demo: simulato – la tua posizione non viene richiesta',
    menuOnHint: 'Tocca per terminare',
    on: 'Posizione condivisa',
    starting: 'Ricerca della posizione …',
    paused: 'Posizione in pausa',
    pausedHint: 'Il telefono non trasmette nulla finché l\'app è in secondo piano o lo schermo è bloccato. Riapri l\'app e riprende.',
    denied: 'Posizione bloccata',
    deniedHint: 'L\'accesso alla posizione è bloccato per questo sito. Si può riautorizzare solo nelle impostazioni del browser.',
    taken: 'Nome già in uso',
    takenHint: 'Un altro dispositivo sta condividendo con questo nome. Scegli di nuovo il tuo nome o attendi un momento.',
    failing: 'La posizione non arriva',
    failingHint: 'Il telefono trova la tua posizione, ma il server non la accetta – di solito manca la ricezione. I tentativi continuano.',
    impreciseHint: 'La ricezione è ancora troppo imprecisa per un punto sulla carta. All\'aperto di solito migliora in pochi secondi.',
    lastAt: 'Ultima {t}',
    stop: 'Non condividere più la posizione',
    change: 'Cambia nome',
    settingsLabel: 'Usa la posizione',
    settingsHint: 'Consente a questo dispositivo di usare la tua posizione. Nulla viene condiviso finché non lo attivi dalla carta.',
    settingsAs: 'Come {name}',
    settingsName: 'Nome sulla mappa',
    settingsNameSub: 'Così ti vede il posto di comando – tocca per cambiare',
  },
  livePosition: {
    chip: '{d} · {n} min fa',
    chipNow: '{d} · adesso',
    atScene: 'Sul posto',
    tapHint: 'Mostra sulla carta',
  },
}
