// Italian copy · Material (Mittel) and checklists.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/material.ts.

import type { Copy, Localizable } from '../index'

export const materialCopy: Localizable<Pick<Copy, 'mittel' | 'checklists'>> = {
  checklists: {
    railLabel: 'Checklist',
    showList: 'Mostra elenco',
    groupTasks: 'Compiti',
    searchPlaceholder: 'Cerca parola chiave …',
    searchAria: 'Cerca parola chiave',
    matching: 'Corrispondente: {title}',
    none: 'Ancora nessuna checklist disponibile.',
    pickEntry: 'Scegli o cerca una parola chiave.',
    done: 'fatto',
    variantLabel: 'Variante',
    pickVariant: 'Scegli una variante per vedere i compiti.',
    milestoneTitle: 'Traguardo – appare nel diario',
    // the word the flag wears on the row (22.09.2026): the tooltip above is what a mouse
    // reads, and a tablet reads nothing — a lone glyph said «something», not what
    milestoneTag: 'annotato nel diario',
    milestoneUndone: 'Traguardo annullato: {text}',
    actionLabels: { journal: 'Diario', plan: 'Piano', draw: 'Disegna' },
    hazardLabels: { red: 'Incendio', orange: 'Pericoli', green: 'Traffico', yellow: 'Tecnico', blue: 'Acqua' },
    diagramAlt: 'Diagramma pagina {page}',
    diagramOpen: 'Ingrandisci lo schema',
    groupManuals: 'Istruzioni',
    manualUpdated: 'Stato al {date}',
    manualWarning: 'Attenzione:',
    manualImageAlt: 'Immagine del passo {n}',
    manualImageOpen: 'Ingrandisci l’immagine',
    manualSource: 'Fonte: {source}',
  },
  mittel: {
    title: 'Materiale',
    summary: '{lines} posizioni',
    summaryEmpty: 'Niente di registrato',
    add: 'Materiale',
    viewBySource: 'In uso',
    // the category filter's WORD on a wide head (22.09.2026)
    categoryFilterWord: 'Filtra',
    noSource: 'Senza assegnazione',
    searchPlaceholder: 'Cerca …',
    addOne: 'Registra {label}',
    addPickSource: '{label} – scegli la provenienza',
    materialSearchPlaceholder: 'Cerca materiale …',
    unitSearchPlaceholder: 'Cerca unità …',
    sourceSearchPlaceholder: 'Cerca provenienza …',
    categoryFilterLabel: 'Filtra per categoria',
    categoryAll: 'Tutte',
    categoryOther: 'Vari',
    customGroup: 'Altri',
    noch: 'restano {n}',
    stockAria: '{label}: restano {remaining} su {total}',
    emptyTitle: 'Nessun materiale registrato.',
    emptyHint: 'Registra con «+ Materiale» ciò che è stato consumato – per il rapporto e per vedere se serve rifornimento.',
    emptyReadonly: 'Nessun materiale registrato.',
    composerTitle: 'Registra materiale',
    materialLabel: 'Materiale',
    materialPlaceholder: 'Scegli il materiale',
    customMaterial: 'Altro materiale',
    composerFromQuery: 'Registra «{name}»',
    unitLabel: 'Unità',
    unitPlaceholder: 'Unità',
    sourceLabel: 'Provenienza',
    sourcePlaceholder: 'Provenienza (facoltativa)',
    qtyLabel: 'Quantità',
    save: 'Salva',
    cancel: 'Annulla',
    removeRow: 'Metti a 0',
    removedToast: '«{label}» eliminato',
    logSet: '{label}: {menge} {unit}',
    logRemoved: '{label} messo a 0',
    logDeleted: '{label} eliminato',
    logRestored: '{label} ripristinato',
    logNote: '{label} – osservazione: {note}',
    logStock: '{label} – scorta: {stock}',
    logBefore: '(prima {n})',
    noteLabel: 'Osservazione',
    notePlaceholder: 'p. es. consegnato al deposito comunale',
    editLabel: 'Modifica la voce',
    stockLabel: 'Scorta',
    stockPlaceholder: 'facoltativo',
    deleteLine: 'Elimina la voce',
    lageStrip: 'Posato, ma non registrato: {list}',
    lageStripTake: 'Registra',
    lageStripHide: 'Nascondi i suggerimenti',
    lageStripCapture: 'Registra …',
    lagePickTitle: 'Posato, ma non registrato',
    lagePickSub: '{n} simboli sulla mappa/nei piani non sono ancora nel materiale. Quali erano?',
    lagePickSubOne: 'Un simbolo sulla mappa/nei piani non è ancora nel materiale. Quale era?',
    lagePickGroupHint: 'Simbolo sulla mappa/nel piano',
    lagePickGroupSourceHint: 'Fonte?',
    lagePickUnambiguous: 'Univoco',
    lagePickUnambiguousSub: 'registrato senza domande',
    lagePickOpen: 'Ancora {n} domande aperte',
    lagePickOpenOne: 'Ancora 1 domanda aperta',
    lagePickConfirm: 'Registra {n} posizioni',
    lagePickConfirmOne: 'Registra 1 posizione',
  },
}
