// Italian copy · Objektbesuche.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/objectVisits.ts.

import type { Copy, Localizable } from '../index'

export const objectVisitsCopy: Localizable<Pick<Copy, 'objectVisits'>> = {

  objectVisits: {
    launcher: 'Visite agli oggetti',
    title: 'Visite agli oggetti',
    back: 'Indietro',
    loading: 'Caricamento delle visite …',
    notPreparedTitle: 'Non ancora preparato per l’uso offline',
    notPreparedBody: 'Questo dispositivo non ha mai caricato l’elenco degli oggetti né le liste di controllo. Apri le visite una volta con la connessione: poi restano sul dispositivo.',
    notPreparedDrafts: 'Le bozze su questo dispositivo restano disponibili anche senza l’elenco degli oggetti.',
    retry: 'Riprova',
    refusedTitle: 'Visite agli oggetti non disponibili',
    refusedBody: 'L’amministrazione non ha attivato le visite agli oggetti per questo corpo, oppure questo account non può aprirle.',
    storageUnreadable: 'Non è stato possibile leggere la memoria del dispositivo – in questo elenco potrebbero mancare visite di questo dispositivo.',
    myDrafts: 'Le mie bozze',
    unsent: 'Non ancora salvato',
    lists: 'Liste',
    listObjectsOne: '1 oggetto',
    listObjectsMany: '{n} oggetti',
    listOn: "il {date}",
    listArchived: "Non più in programma",
    schedule: {"today": "Oggi", "overdue": "In ritardo", "upcoming": "Prossime date", "undated": "Senza data", "recent": "Completati di recente"},
    listUntil: 'entro il {date}',
    searchHead: 'Cerca un oggetto',
    searchPlaceholder: 'Cerca oggetto …',
    nearby: 'Nelle vicinanze',
    nearbyUse: 'Usa la mia posizione',
    nearbyLocating: 'Rilevamento della posizione …',
    nearbyFailed: 'Posizione non disponibile',
    nearbyNone: 'Nessun oggetto del catalogo ha coordinate.',
    distanceM: '{m} m',
    distanceKm: '{km} km',
    neverVisited: 'mai visitato',
    lastVisit: 'ultima volta il {date}',
    intro: 'Scegli un oggetto da una lista, con la ricerca o «Nelle vicinanze». La visita viene salvata prima su questo dispositivo e inviata appena c’è rete.',
    viewerNote: 'Con questo account puoi leggere le visite ma non registrarle.',
    listSub: '{done} di {total} visitati',
    listUnresolved: '{n} oggetti di questa lista non sono noti su questo dispositivo.',
    listUnknown: 'Questa lista non è nota su questo dispositivo.',
    listDoneElsewhere: 'fatto',
    stateDraft: 'Bozza',
    stateDone: '✓ {date}',
    statePhotos: 'Foto in sospeso',
    stateUnsent: 'non inviato',
    visitLoading: 'Caricamento della visita …',
    visitMissing: 'Questa visita non è su questo dispositivo e non è stato possibile caricarla.',
    objectUnknown: 'L’oggetto «{key}» non è noto nel catalogo di questo dispositivo.',
    chooseChecklist: 'Quale lista di controllo?',
    chooseChecklistLead: 'Per questo oggetto esistono più liste di controllo di visita.',
    noChecklist: 'Senza lista di controllo',
    plans: 'Piani',
    changeChecklist: 'Cambia lista di controllo',
    changeChecklistLead: 'Le risposte presenti anche nella nuova lista restano. Le foto restano sempre.',
    checklistCurrent: 'attuale',
    changeChecklistDropOne: '1 risposta non corrisponde alla nuova lista e verrà rimossa. Le foto restano.',
    changeChecklistDropMany: '{n} risposte non corrispondono alla nuova lista e verranno rimosse. Le foto restano.',
    changeChecklistConfirm: 'Cambia',
    planLoading: 'Caricamento del piano …',
    suggestedHead: 'In intervento',
    startFailed: 'Non è stato possibile creare la visita',
    menu: 'Altre azioni',
    saveFile: 'Salva come file',
    discard: 'Scarta la bozza',
    discardTitle: 'Scartare la bozza?',
    discardMsg: 'La visita viene segnata come scartata e non compare più in nessuna lista. Non si può annullare.',
    discardBtn: 'Scarta',
    details: 'Da e data',
    visitedAt: 'Visitato il',
    with: 'Da',
    withPlaceholder: 'Nomi, p. es. Max Muster, Nina Frei',
    notChecked: 'non controllato',
    photoMissing: 'Foto mancante',
    answer: { ok: 'OK', defect: 'Difetto', na: 'n. a.', yes: 'Sì', no: 'No', photo: 'Foto' },
    defectNote: 'Qual è il difetto?',
    defectNotePlaceholder: 'p. es. il coperchio si blocca',
    photosAdded: '{n} foto aggiunte',
    photosOne: '1 foto',
    photosMany: '{n} foto',
    takePhoto: 'Scatta una foto',
    addPhoto: 'Aggiungi foto',
    valuePlaceholder: 'Valore',
    notes: 'Osservazioni',
    notesPlaceholder: 'Altro che hai notato …',
    photos: 'Foto',
    proposals: 'Proposte di correzione',
    proposalAdd: 'Aggiungi proposta',
    proposalRow: 'finora: {current} · nuovo: {proposed}',
    proposalRowNew: 'nuovo: {proposed}',
    complete: 'Concludi',
    completeOpenOne: '1 punto non controllato',
    completeOpenMany: '{n} punti non controllati',
    completeOpenMsg: 'Concludere comunque? I punti non controllati compaiono nel rapporto come «non controllato».',
    completeRequired: 'Tra questi obbligatori: {items}',
    completeAnyway: 'Concludi comunque',
    completed: 'Visita conclusa',
    correctionNote: 'Correzione: la visita resta conclusa, la modifica diventa una nuova revisione.',
    correctionDone: 'Fatto',
    lifecycle: { draft: 'Bozza', completed: 'Conclusa', discarded: 'Scartata' },
    sync: {
      unsaved: 'Non salvato',
      conflict: 'Conflitto',
      auth: 'Accesso necessario',
      error: 'Non inviato',
      sending: 'Invio in corso',
      local: 'Solo su questo dispositivo',
      localAt: 'sul dispositivo {time}',
      changes: 'Modifiche sul dispositivo {time}',
      photos: 'Foto {done}/{total}',
      saved: 'Salvato {time}',
      remote: 'Revisione {n}',
      offline: 'offline',
    },
    delivery: { waiting: 'Archiviazione in attesa', delivered: 'archiviato', failed: 'Archiviazione: errore', paused: 'Archiviazione in pausa' },
    statusTitle: 'Stato di questa visita',
    statusOpen: 'Mostra lo stato',
    statusLifecycle: 'Visita',
    statusDevice: 'Dispositivo → server',
    statusFiling: 'Archiviazione',
    statusSavedAt: 'Salvato su questo dispositivo alle {time}.',
    statusRevision: 'Revisione {n} sul server.',
    statusNeverSent: 'Mai inviato al server.',
    statusPending: 'Le modifiche più recenti sono solo su questo dispositivo.',
    statusPhotos: '{done} foto su {total} sul server.',
    statusNoFiling: 'Nessuna destinazione di archiviazione configurata.',
    destinationSharePoint: 'SharePoint',
    statusFilingRow: '{destination}: {state}',
    conflictTitle: 'Due versioni: {what}',
    conflictBody: 'Lo stesso punto è stato modificato su un altro dispositivo.',
    conflictMine: 'La mia',
    conflictTheirs: 'L’altra',
    conflictBoth: 'Tieni entrambe',
    conflictRemoved: '(rimosso)',
    conflictWhat: {
      notes: 'Osservazioni', visitedAt: 'Data della visita', with: 'Da', checklist: 'Lista di controllo',
      workRef: 'Lista', object: 'Oggetto', photo: 'Foto', proposal: 'Proposta',
    },
    unsavedTitle: 'Non salvato sul dispositivo',
    unsavedBody: 'Il browser ha rifiutato il salvataggio (memoria piena?). Ciò che non è salvato esiste solo in questa finestra.',
    unsavedRetry: 'Salva di nuovo',
    authTitle: 'Accesso scaduto',
    authBody: 'La visita è al sicuro su questo dispositivo. Accedi di nuovo per inviarla.',
    authLogin: 'Accedi',
    errorTitle: 'Il server non ha accettato la visita',
    errorAttachment: 'Una foto non è stata accettata',
    errorForbidden: 'Questo account non può registrare visite.',
    errorDisabled: 'Le visite agli oggetti sono disattivate.',
    photoTitle: 'Foto',
    photoCaption: 'Didascalia',
    photoCaptionPlaceholder: 'p. es. accesso nord',
    photoBelongs: 'Appartiene a',
    photoGeneral: 'Generale',
    photoStored: 'Salvata su questo dispositivo · verrà inviata appena c’è rete',
    photoNotStored: 'Non salvata sul dispositivo – solo in questa finestra',
    photoAnother: 'Un’altra',
    photoDone: 'Fatto',
    photoRemove: 'Rimuovi foto',
    photoRemoved: 'Foto rimossa',
    photoPreparing: 'Preparazione della foto …',
    photoFailed: 'Non è stato possibile acquisire la foto',
    photoPending: 'non ancora inviata',
    photoOpen: 'Apri foto: {caption}',
    proposalTitle: 'Proponi una correzione',
    proposalField: 'Campo',
    proposalOther: 'Altro',
    proposalOtherLabel: 'Quale campo?',
    proposalCurrent: 'Finora',
    proposalCurrentHint: 'come nei dati di base',
    proposalNew: 'Nuovo',
    proposalReason: 'Motivo',
    proposalReasonPlaceholder: 'p. es. il custode è cambiato',
    proposalSave: 'Salva proposta',
    proposalRemove: 'Rimuovi proposta',
    proposalRemoved: 'Proposta rimossa',
    defectsOne: '1 difetto',
    defectsMany: '{n} difetti',
    countOk: '{n} OK',
    countOpen: '{n} non controllati',
    proposalsOne: '1 proposta',
    proposalsMany: '{n} proposte',
    report: 'Rapporto (PDF)',
    reportSub: 'Revisione {n}',
    reportFailed: 'Non è stato possibile caricare il rapporto',
    edit: 'Modifica',
    editSub: 'Correzione · resta conclusa, nuova revisione',
    history: 'Cronologia',
    historyFailed: 'Non è stato possibile caricare la cronologia',
    historyRow: 'r{n} · {time}',
    nextInList: 'Prossimo nella lista',
    listDone: 'Tutti gli oggetti di questa lista sono stati visitati.',
    by: 'Da {name}',
    fileSaved: 'File salvato',
    fileSavedMissing: 'File salvato – {n} foto non erano su questo dispositivo',
    fileFailed: 'Non è stato possibile creare il file',
    sent: 'Inviato',
    sendContended: 'Conflitto con un altro dispositivo – nuovo tentativo a breve',
    conflictTakeOther: 'Prendi l’altra',
    conflictKeep: 'Tieni questa',
    conflictOther: 'Altra versione',
    conflictCurrent: 'Nella visita',
    storageWait: 'Non è stato possibile leggere la memoria del dispositivo. Per non creare una seconda bozza, ora non viene avviata nessuna nuova visita.',
    sendOffline: 'Offline – verrà inviato appena il server è raggiungibile',
  },
}
