// Italian copy · photos, weather, PDF, Einstellungen, Feedback, offline and empty states.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/panels.ts.

import type { Copy, Localizable } from '../index'

type Keys =
  | 'photoViewer' | 'photoGeo' | 'einsatzuhr' | 'mapPicker' | 'weather' | 'weatherLayer' | 'pdf'
  | 'settings' | 'feedback' | 'offline' | 'emptyApp' | 'incidentAlert'

export const panelsCopy: Localizable<Pick<Copy, Keys>> = {
  mapPicker: {
    title: 'Imposta la posizione sulla carta',
    hint: 'Tocca la carta per impostare la posizione',
    confirm: 'Usa la posizione',
  },
  weather: {
    label: 'Meteo',
    details: 'Dettagli meteo',
    from: 'da',
    cardinals: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    cardinalsLong: ['Nord', 'Nordest', 'Est', 'Sudest', 'Sud', 'Sudovest', 'Ovest', 'Nordovest'],
    windTitle: 'Vento {dir} ({deg}°)',
    detailsHint: ' – tocca per i dettagli',
    meteoHint: ' – tocca per i dettagli MeteoSvizzera',
    windDir: 'Direzione del vento',
    windSpeed: 'Velocità del vento',
    gust: 'Raffiche',
    precip: 'Precipitazioni',
    station: 'Stazione',
    source: 'Fonte',
    meteoRadar: 'Radar delle precipitazioni MeteoSvizzera',
    detailsUrl: 'https://www.meteosvizzera.admin.ch/servizi-e-pubblicazioni/applicazioni/precipitazioni.html',
    conditions: {
      clear: 'Sereno', fair: 'Poco nuvoloso', partly: 'Parzialmente nuvoloso', overcast: 'Coperto',
      fog: 'Nebbia', drizzle: 'Pioviggine', rain: 'Pioggia', snow: 'Neve',
      rainShowers: 'Rovesci di pioggia', snowShowers: 'Rovesci di neve', thunder: 'Temporale', cloudy: 'Nuvoloso',
    },
    windShiftOpen: 'Apri nel diario',
    windShiftDismiss: 'Nascondi',

    unavailable: 'Dati meteo attualmente non disponibili',
  },
  weatherLayer: {
    group: 'Meteo',
    radar: 'Precipitazioni (radar)',
    radarSub: "MeteoSvizzera · ultima ora",
    attribution: 'Radar © MeteoSvizzera',
    radarTitle: 'Radar delle precipitazioni',
    play: "Riproduci l'ultima ora",
    pause: "Ferma (torna all'immagine attuale)",
    frameSlider: "Scegli l'immagine radar",
    frameAgo: '{minutes} min fa',
    latest: 'attuale',
    legendLight: 'debole',
    legendUnit: 'mm/h · stima radar',
    legendHeavy: 'forte',
    radarPending: 'Nessuna immagine radar ancora – caricamento.',
    radarUnavailable: 'Radar al momento non disponibile.',
    stale: 'Stato {time} – non aggiornato',
    chipAria: 'Allerte meteo ({count}): {summary}',
    more: '+{count}',
    from: 'dalle {time}',
    until: 'fino alle {time}',
    untilRevoked: 'fino a revoca',
    validity: 'Validità',
    source: 'Fonte',
    sourceMeteoswiss: 'MeteoSvizzera (via MeteoAlarm)',
    sourceAlertswiss: '{publisher} (via Alertswiss)',
    moreInfo: 'Maggiori informazioni alla fonte',
    warningStale: 'Stato {time} – fonte al momento non raggiungibile',
    verbatimNote: 'Testo originale della fonte, non modificato.',
    level1: 'Informazione',
    level2: 'Giallo – potenzialmente pericoloso',
    level3: 'Arancione – pericoloso',
    level4: 'Rosso – molto pericoloso',
    authorityNotice: 'Comunicazione delle autorità',
  },
  pdf: {
    loading: 'Caricamento del PDF…',
    failed: 'Impossibile caricare il PDF.',
    retry: 'Riprova',
    reason: {
      stale: 'L’app sta usando una versione vecchia – chiudila e riaprila.',
      offline: 'Nessuna connessione – questo PDF non è salvato su questo dispositivo.',
      missing: 'Il PDF non si trova più sul server.',
      denied: 'L’accesso non è più valido – accedi di nuovo.',
      timeout: 'Il server non ha risposto.',
      unsupported: 'Questo browser è troppo vecchio per visualizzare i PDF.',
      unknown: 'Motivo sconosciuto.',
    },
  },
  settings: {
    title: 'Impostazioni',
    deviceGroup: 'Dispositivo',
    colorScheme: 'Schema colori',
    symbolSizeMap: 'Dimensione simboli – mappa',
    symbolSizeMapSub: 'Simboli tattici sulla mappa della situazione e sui piani modulo collegati',
    symbolSizeBoard: 'Dimensione simboli – moduli',
    symbolSizeBoardSub: 'Simboli tattici sui piani modulo non collegati',
    offlineRadius: 'Raggio offline',
    offlineAuto: 'Preparazione offline',
    offlineAutoSub: 'Carica mappa e piani da sé poco dopo l\'apertura',
    offlineRadiusSub: 'Carta e condotte attorno all’intervento',
    deviceFoot: 'Vale solo su questo dispositivo. Raggio più piccolo = download offline più veloce e più piccolo.',
    incidentGroup: 'Intervento',
    contactInterval: 'Contatto radio autoprotezione',
    contactIntervalSub: 'Intervallo fino al contatto dovuto (ambra)',
    contactIntervalAria: 'Intervallo del contatto radio',
    grace: 'Tempo di tolleranza',
    graceSub: 'Allarme rosso dopo intervallo + tolleranza',
    funkkanal: 'Canale radio',
    funkkanalSub: 'Predefinito per le nuove squadre ARA',
    syncedFoot: 'Sincronizzato con tutti i dispositivi',
    syncedFootViewer: ' · solo il capo intervento può modificarle',

    symbolCaptions: 'Etichette',
    symbolCaptionsSub: 'Il valore chiave sotto il simbolo',
    railLabels: 'Etichette delle barre',
    railLabelsSub: 'Una parola sotto ogni simbolo in entrambe le barre',
    captionsOff: 'Nessuna',
    captionsAuto: 'Auto',
    captionsAll: 'Tutte',
    keepScreenOn: 'Mantieni acceso lo schermo',
    keepScreenOnSub: 'Non oscurare lo schermo durante l\'intervento',
    utilityGroup: 'Modelli',
    blankSheet: 'Foglio di registrazione vuoto (PDF)',
    blankSheetSub: 'Un foglio cartaceo da riempire a mano',
    blankSheetDownload: 'Scarica',
    blankSheetFailed: 'PDF non riuscito – riprova',
    feedbackRow: 'Dai un riscontro',
    feedbackRowSub: 'Cosa era scomodo o mancava',
    feedbackOpen: 'Scrivi',
  },
  offline: {
    title: 'Prontezza offline',
    syncedAgo: 'Dati dell’intervento sincronizzati {ago}',
    offline: 'Offline – salvato localmente',
    pending: 'Salvataggio …',
    error: 'Errore di sincronizzazione – salvato localmente',
    agoNever: 'non ancora',
    agoJustNow: 'proprio ora',
    agoMin: '{n} min fa',
    agoHour: '{n} h fa',
    checking: 'verifica in corso …',
    ready: 'pronto',
    notLoaded: 'non caricato',
    loading: 'caricamento …',
    rowSymbols: 'Simboli',
    rowHazmat: 'Merci pericolose (ONU/ADR)',
    rowMap: 'Carta',
    noLayer: 'nessun livello',
    rowPlans: 'Piani',
    noObject: 'nessun oggetto',
    rowLeitung: 'Livelli di riferimento',
    geoAllReady: 'tutti i {n} pronti',
    geoSome: '{cached}/{total} caricati',
    rowWeather: 'Meteo',
    weatherUnreachable: 'non raggiungibile',
    onlineOnly: 'solo online',
    rowPersonnel: 'Effettivo',
    personnelCount: '{n} persone',
    rowObjectSearch: 'Ricerca oggetti',
    rowStorage: 'Memoria del dispositivo',
    storageFree: '{size} liberi',
    storageUnknown: 'Il dispositivo non indica lo stato della memoria',
    storageFullShort: 'Piena – nulla viene salvato localmente',
    storageFull: 'Memoria piena – le modifiche non sono salvate localmente',
    dlTightTitle: 'Memoria scarsa su questo dispositivo',
    dlTightMsg: 'Il download richiede ≈ {need}, liberi {free}. In versione ridotta viene caricata tutta l’area ma con meno dettaglio (circa {pct} % delle tessere). Così resta spazio per il rapporto d’intervento.',
    dlTightConfirm: 'Carica ridotto',
    dlNoSpace: 'Memoria insufficiente per il set offline (solo {free} liberi). Libera spazio sul dispositivo.',
    loadingForOffline: 'Caricamento per l’offline …',
    cancel: 'Annulla',
    loadAll: 'Carica tutto per l’offline',
    foot: 'Carica carta, piani, simboli e condotte di questo intervento su questo dispositivo. Meteo e ricerca oggetti richiedono una connessione e non sono disponibili offline.',
    dlDone: 'Carta pronta offline – {n} tasselli',
    dlDoneCapped: 'Carta pronta offline – area limitata, {n} tasselli',
    dlPartial: 'Caricamento parziale – {n} di {total}. Ai bordi dell’area la carta manca.',
    dlPartialCapped: 'Caricamento parziale – {n} di {total}, area limitata. Ai bordi la carta manca.',
    dlNone: 'Nulla caricato – nessuna rete. Sul posto la carta non sarà disponibile.',
    dlNoCoverage: 'Nulla caricato – la sorgente della carta non copre questa zona. Controllare il livello della carta o l’URL dei tasselli.',
    dlContinue: 'Continua a caricare',
    dlRetry: 'Riprova',
    dlFailed: 'Download offline non riuscito',

    browserTitle: 'Offline affidabile come app installata',
    browserBody: 'In una scheda del browser nulla è memorizzato in modo affidabile: carte, piani e linee possono essere cancellati in qualsiasi momento, e la scheda deve essere ancora aperta al prossimo intervento. Installata, PC Fronte funziona anche offline.',
    browserNoInstall: 'Questo dispositivo non offre l\'installazione. Per essere offline in intervento, installa PC Fronte sul tablet o sul telefono.',
    wsDropped: '{n} voci danneggiate ignorate al caricamento',
    wsNewer: 'I dati d\'intervento provengono da una versione più recente dell\'app – aggiorna l\'app.',
  },
  emptyApp: {
    title: 'Nessun intervento aperto',
    bodyViewer: 'Al momento nessun intervento è attivo.',
    bodyEditor: 'Apri un intervento.',
    bodyEditorAlarm: 'Apri un intervento o rileva un allarme {provider}.',
    history: 'Cronologia',
  },
  incidentAlert: {
    kicker: 'Nuovo intervento',
    switch: 'Cambia',
    open: 'Apri',
    later: 'Più tardi',
  },
  photoViewer: {
    title: 'Foto',
    download: 'Scarica',
  },
  photoGeo: {
    place: 'Posiziona sulla mappa',
    placeN: 'Posiziona {n} foto sulla mappa',
    show: 'Mostra sulla mappa',
    placedStep: 'Foto posizionata sulla mappa',
    logPlaced: 'Foto posizionata sulla mappa',
    logPlacedN: '{n} foto posizionate sulla mappa',
    where: 'Luogo dello scatto',
    whereN: 'Luogo dello scatto foto {n}',
    distance: 'a {d} dal luogo dell\'intervento',
    facing: 'vista verso {dir}',
    takenAt: 'scattata alle {t}',
    tooFar: 'Troppo lontano per la mappa',
    marker: 'Foto dal diario',
    markerTaken: 'Foto dal diario · scattata alle {t}',
    planMark: 'Foto – spostala o rimuovila sulla mappa',
  },
  einsatzuhr: {
    title: 'Durata dell\'intervento – inizio {t}',
    modeElapsed: 'Durata dell\'intervento',
    modeNow: 'Ora',
    modeStart: 'Inizio dell\'intervento',
  },
  feedback: {
    title: 'Riscontro',
    promptTitle: 'Una domanda veloce',
    promptDismiss: 'Non adesso',
    promptOpen: 'Descrivi brevemente',
    promptFor: {
      crashLoop: 'L\'app è andata in crash più volte durante un intervento. Cosa stavi facendo?',
      crash: 'L\'app è andata in crash una volta poco fa. Cosa stavi facendo?',
      renderStorm: 'L\'app ha girato a pieno carico durante un intervento – probabilmente lenta, o la batteria si è scaricata in fretta. Cosa era aperto?',
      storageFull: 'La memoria di questo dispositivo era piena. Si è perso qualcosa?',
      syncConflict: 'Due dispositivi avevano stati diversi. Alla fine mancava qualcosa?',
    },
    kinds: {
      crashLoop: 'crash ripetuto nello stesso intervento',
      crash: 'crash dell\'interfaccia',
      renderStorm: 'interfaccia sotto carico continuo',
      storageFull: 'memoria del dispositivo piena',
      syncConflict: 'conflitto di sincronizzazione durante l\'unione',
    },
    subject: 'Riscontro',
    intro: 'Cos\'è successo e cosa ti aspettavi? Bastano una o due frasi.',
    placeholder: 'p. es. «Ho messo la squadra in rientro, poi lo schermo è diventato bianco.»',
    techTitle: 'Questo viene inviato con il messaggio',
    techNote: 'Nient\'altro – nessun dato d\'intervento, nessun indirizzo, nessun nome. L\'app non fa mai uno screenshot da sola.',
    routeGithub: 'Segnala come issue GitHub',
    routeGithubBadge: 'consigliato',
    routeGithubNote: 'Apre un modulo precompilato. Puoi seguire la segnalazione e ricevi una notifica quando è risolta. Serve un account GitHub.',
    routeMail: 'Invia per e-mail',
    routeMailBadge: 'senza account',
    routeMailNote: 'Funziona sempre, anche senza GitHub. La risposta arriva direttamente per e-mail.',
    next: 'Avanti',
    diagNote: 'In entrambi i casi: il file diagnostico ({n}) viene salvato quando prosegui – allegalo alla issue o all\'e-mail. Senza di esso manca il messaggio di errore vero e proprio.',
    diagNoteEmpty: 'In entrambi i casi: al momento non è registrato alcun log di errore. Descrivi semplicemente cosa è successo.',
    diagCount: '{n} log di errore',
    diagCountOne: '1 log di errore',
    diagLine: 'Errori: ',
    diagSaved: 'File diagnostico «{name}» salvato – allegalo, per favore.',
    diagFailed: 'Non è stato possibile creare il file diagnostico – la segnalazione funziona comunque.',
    privacy: 'Nulla viene inviato automaticamente. Decidi tu se, come e a chi.',
    close: 'Chiudi',
    tech: {
      version: 'Versione:',
      locale: 'Lingua:',
      device: 'Dispositivo:',
      viewport: 'Finestra:',
      network: 'Rete:   ',
      event: 'Evento:',
      online: 'online',
      offline: 'offline',
      noDescription: '(nessuna descrizione)',
    },
  },
}
