// Italian copy · the Rapport: Auswertung, report, preflight.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/report.ts.

import type { Copy, Localizable } from '../index'

export const reportCopy: Localizable<Pick<Copy, 'auswertung' | 'report' | 'wheel' | 'preflight'>> = {
  auswertung: {
    heading: 'Analisi',
    note: 'Per il debriefing – ricavato dai dati dell’intervento, non fa parte del rapporto firmato.',
    missing: '—',
    firstOnScene: 'Allarme fino al 1° veicolo sul posto',
    firstOnSceneDef: 'Dall’allarme all’orario «sul posto» più precoce di un veicolo (orari di allarme / di partenza).',
    firstAs: 'Allarme fino al 1° ingresso con autoprotezione',
    firstAsDef: 'Dall’allarme al primo ingresso di una squadra con autoprotezione.',
    contacts: 'Contatti radio rispettati',
    contactsSub: '{n} in ritardo su {total}',
    contactsDef: 'Quota degli intervalli di contatto radio con autoprotezione terminati prima che la squadra fosse in ritardo ({n} min + {g}). Un intervallo va dall’ingresso o da un contatto al contatto, alla pressione, alla ritirata o all’uscita successivi; uno aperto conta solo una volta in ritardo. Il tempo tra chiusura e riapertura non conta.',
    contactsDefNoGrace: 'Quota degli intervalli di contatto radio con autoprotezione terminati prima che la squadra fosse in ritardo ({n} min). Un intervallo va dall’ingresso o da un contatto al contatto, alla pressione, alla ritirata o all’uscita successivi; uno aperto conta solo una volta in ritardo. Il tempo tra chiusura e riapertura non conta.',
    longestAs: 'Intervento più lungo con autoprotezione',
    longestAsDef: 'Tempo concluso più lungo di una squadra con autoprotezione, dall’ingresso all’uscita.',
    total: 'Durata dell’intervento',
    totalDef: 'Dall’allarme alla fine dell’intervento.',
    totalRunning: 'Intervento in corso',
    truppLane: 'Squadra {no} · {name}',
    groupPhases: 'Fasi (check-list)',
    groupVehicles: 'Veicoli',
    groupTrupps: 'Squadre',
    groupMilestones: 'Tappe',
    noTimeline: 'Nessun orario di veicoli, squadre o check-list registrato.',
    legendTravel: 'in viaggio',
    legendScene: 'sul posto',
    legendReturn: 'rientro',
    legendAs: 'con autoprotezione',
    legendWork: 'impiegata senza autoprotezione',
    legendStandby: 'pronta',
    legendContact: 'contatto radio',
    legendFaellig: 'contatto dovuto',
    legendUeberfaellig: 'in ritardo',
    legendMilestone: 'tappa',
    legendPhase: 'fase: dalla prima all’ultima spunta',
    footnotesHead: 'Definizioni',
    lehrenSeePage1: 'Insegnamenti / sicurezza: vedi pagina 1',
    graceMin: '{n} min',
    graceSec: '{n} s',
  },
  report: {
    erfasser: 'Registrato da',
    gerettete: 'Salvati',
    gerettetePersonen: 'persone',
    geretteteTiere: 'animali',
    gerettetePerson: 'persona',
    geretteteTier: 'animale',
    rueckmeldungElz: 'Rapporto alla centrale',
    back: 'Indietro',
    print: 'Stampa',
    keyword: 'Parola chiave',
    einsatzleiter: 'Capo intervento',
    // la successione stampata quando la condotta è cambiata durante l’intervento (lib/reportPdfDirect)
    einsatzleitungBis: '{name} (fino alle {t})',
    einsatzleitungAb: '{name} (dalle {t})',
    kontaktperson: 'Persona di contatto',
    alarmierung: 'Allarme',
    ausgerueckt: 'Partenza',
    incidentId: 'ID intervento',
    alarmMessage: 'Messaggio d’allarme',
    partnerOrgs: 'Organizzazioni partner',
    remarks: 'Osservazioni',
    kroki: 'Schizzo',
    krokiState: '{title} · stato {at}',
    atemschutz: 'Sorveglianza autoprotezione',
    truppEntry: 'Entrata',
    mittel: 'Materiale (indicare la quantità)',
    journal: 'Diario d’intervento',
    photo: 'Foto',
    transcript: 'Trascrizione',
    planFallback: 'Piano',
    proofOffline: 'Verifica non possibile (offline)',
    proofIntact: 'Catena di hash intatta',
    proofBroken: 'Catena di hash interrotta',
    proofBrokenAt: 'Catena di hash interrotta al #{seq}',
    areaManual: 'Manuale',
    areaAtemschutz: 'Squadre',
    areaAnwesenheit: 'Presenze',
    areaMittel: 'Materiale',
    areaChecklist: 'Checklist',
    areaRapport: 'Rapporto',
    areaSystem: 'Sistema',
    areaLage: 'Situazione',
    drawCircle: 'Perimetro di sicurezza',
    drawAreaLabeled: 'Sezione «{label}»',
    drawArea: 'Superficie',
    drawRescueAxis: 'Asse di salvataggio',
    drawMeasureArrow: 'Freccia di misura',
    drawLine: 'Linea',

    pdf: 'Scarica il PDF',
    pdfBusy: 'Creazione del PDF …',
    pdfFailed: 'Impossibile creare il PDF.',
    lehren: 'Insegnamenti / sicurezza',
  },
  wheel: {
    invalidTime: 'Inserire un orario valido (00:00–23:59).',
    day: 'Giorno',
    hour: 'Ora',
    minute: 'Minuto',
    now: 'Adesso',
    ok: 'OK',
  },
  preflight: {
    pdfFull: 'Rapporto d’intervento (PDF)',
    pdfBusy: 'Creazione del PDF …',
    geretteteLabel: 'Salvati',
    geretteteLageStrip: 'Sulla carta: {list}',
    geretteteLagePersonen: '{n} persone',
    geretteteLageTiere: '{n} animali',
    geretteteLageTake: 'Applica',
    gerettetePersonen: 'Persone',
    geretteteTiere: 'Animali',
    geretteteNone: 'Nessuno',
    geretteteNoneHint: 'Nulla salvato',
    geretteteNonePrint: 'nessuno',
    gruppenLabel: 'Allarme dei gruppi',
    fahrzeugeLabel: 'Partenze dei veicoli',
    ausgeruecktDerived: 'ripreso dagli orari dei veicoli',
    vorOrtShort: 'sul posto',
    zurueckShort: 'rientro',
    gpsTableTitle: 'Veicoli GPS · in diretta',
    gpsTableNote: 'Orari dalle posizioni GPS, rilevati dal server',
    gpsColFzg: 'Veic.',
    gpsColStatus: 'Stato',
    gpsColAn: 'arr.',
    gpsColAb: 'part.',
    gpsColFahrten: 'Viaggi',
    gpsColPos: 'Pos.',
    gpsStatusScene: 'sul posto',
    gpsStatusAway: 'in viaggio',
    gpsAgeSec: '{n} s fa',
    gpsAgeMin: '{n} min fa',
    gpsAgeHour: '{n} h fa',
    gpsAgeStale: 'Posizione non aggiornata',
    fahrtenCount: '{n} viaggi',
    rueckmeldungLabel: 'Rapporto alla centrale',
    rueckmeldungName: 'Nome',
    rueckmeldungZeit: 'Ora del riscontro alla centrale',
    title: 'Rapporto d’intervento',
    headAllRecorded: 'tutti i dati registrati',
    headStillOpen: 'aperto',
    tabsLabel: 'Parte del rapporto',
    tabs: { bericht: 'Rapporto', werwas: 'Personale & Materiale', beilagen: 'Allegati' },
    stichwort: 'Parola chiave',
    einsatzart: 'Tipo',
    ort: 'Luogo',
    fromDispatch: 'Dai dati dell’intervento',
    edit: 'Modifica',
    alarmMessage: 'Messaggio d’allarme',
    alarmierung: 'Allarme',
    notRecorded: 'Non registrato',
    summaryLabel: 'Rapporto breve',
    summaryPlaceholder: 'Cosa è successo / cosa è stato trovato?',
    einsatzleiterLabel: 'Capo intervento',
    einsatzleiterPlaceholder: 'Scegli o inserisci',
    kontaktpersonLabel: 'Persona di contatto',
    kontaktpersonClear: 'Svuota persona di contatto',
    kontaktpersonPlaceholder: 'Proprietario / segnalante',
    kontaktpersonTelefon: 'Telefono persona di contatto',
    kontaktpersonTelefonClear: 'Svuota il telefono',
    kontaktpersonTelefonPlaceholder: 'Numero di telefono',
    kontaktpersonCall: 'Chiama la persona di contatto',
    entfaellt: 'Non applicabile',
    entfaelltUndo: 'Modifica',
    incidentEndLabel: 'Fine intervento',
    zeitBeforeAlarm: 'Precede l’allarme ({t})',
    zeitBeforeAusgerueckt: 'Precede l’uscita ({t})',
    zeitFuture: 'Nel futuro',
    madeToast: 'Rapporto creato',
    bandDone: 'Rapporto creato.',
    bandAsk: "L'intervento è ancora aperto – chiuderlo?",
    bandLater: 'Più tardi',
    exportIncompleteTitle: 'Mancano ancora dei dati',
    exportIncompleteLead: 'Ancora aperto:',
    exportIncompleteMsg: 'Il rapporto può comunque essere creato – i campi aperti restano vuoti e possono essere completati a mano.',
    now: 'Ora',
    remarksLabel: 'Osservazioni',
    remarksPlaceholder: 'Facoltativo',
    sectionsHead: 'Sezioni',
    printMenu: 'Altre opzioni di stampa',
    toggleKroki: 'Schizzo',
    plansAnnotated: 'Piani annotati ({n})',
    toggleGebaeude: 'Edificio – piani ({n})',
    plansAll: 'Tutti i piani',
    toggleAtemschutz: 'Sorveglianza autoprotezione ({n})',
    toggleAttendance: 'Presenza ({n})',
    toggleJournal: 'Diario d’intervento',
    togglePendenzen: 'Ordini / pendenze ({n})',
    toggleAttachments: 'Foto ({n})',
    archiveZip: 'Scaricare gli allegati (ZIP)',
    krokiAtLabel: 'Kroki al',
    krokiOrientation: 'Orientamento',
    krokiPortrait: 'Verticale',
    krokiLandscape: 'Orizzontale',
    krokiAtNow: 'Adesso',
    krokiAtFailed: 'La situazione in quel momento non è stata ricostruita – viene stampata quella attuale.',
    partnersLabel: 'Organizzazioni partner',
    partnerOrg: 'Organizzazione (p. es. polizia)',
    partnerOrgShort: 'Organizzazione',
    partnerNote: 'Osservazione (p. es. assume il traffico)',
    partnerNoteShort: 'Osservazione',
    partnersNone: 'nessuna registrata',
    partnerAdd: 'Aggiungi organizzazione',
    partnerPlaceholder: 'Organizzazione …',
    partnerLageStrip: 'Sulla carta: {list}',
    partnerLageTake: 'Applica',
    attachmentsHead: 'Foto',
    attachmentsAdd: 'Aggiungi foto',
    attachmentsOpen: 'Vedi la foto',
    attachmentsCount: '{n} foto',
    attachmentsNone: 'nessuna',
    attachmentsCaption: 'Didascalia (p. es. «Licenza di condurre»)',
    attachmentsPending: 'non ancora caricata',
    attachmentsFailed: 'La foto {name} non è stata caricata – non comparirà nella stampa.',
    attachmentAdded: 'Foto aggiunta',
    attachmentCaptioned: 'Didascalia',
    attachmentRemoved: 'Foto rimossa',
    linksHead: 'Moduli e link',
    shareHead: 'Condividere',
    shareLede: 'Senza login · resta valido dopo la chiusura.',
    shareLiveLede: 'Senza login · resta valido dopo la chiusura.',
    shareCreate: 'Crea link',
    shareBusy: 'Creazione del link …',
    shareLoading: 'Caricamento del link …',
    shareLoadFailed: 'Non è stato possibile caricare il link.',
    shareRetry: 'Riprova',
    shareCreateFailed: 'Creazione del link non riuscita',
    shareCopy: 'Copia indirizzo',
    shareCopied: 'Copiato',
    shareScan: 'Inquadra con la fotocamera',
    shareSend: 'Invia …',
    shareWarn: 'Chi ha il link vede l’intero intervento – i nomi dei presenti, le foto e il '
      + 'diario completo.',
    shareRevoke: 'Revoca link',
    shareRevokeTitle: 'Revocare il link a tutto l’intervento?',
    shareRevokeBody: 'L’indirizzo smetterà di funzionare. Chi lo ha aperto perde subito l’accesso. '
      + 'Un nuovo link può essere creato in qualsiasi momento – sarà un altro indirizzo.',
    shareRevokeConfirm: 'Sì, revoca',
    shareRevokeFailed: 'Revoca del link non riuscita',
    shareKindLabel: 'Cosa apre il link',
    shareKindFull: 'Intervento · leggere',
    shareKindAtem: 'Squadre · operare',
    shareAsLede: 'Chi apre il link vede solo la lavagna delle squadre di questo intervento – la '
      + 'sorveglianza APR – e la usa: annunciare una squadra, contatto, pressione, ripiegamento, '
      + 'fuori. Nessuna carta, nessun diario. Vale finché l’intervento non è chiuso.',
    shareAsLiveLede: 'Vale fino alla chiusura.',
    shareAsWarn: 'Quanto viene inserito lì compare nel rapporto sotto «Sorveglianza autoprotezione». Dai il link '
      + 'solo alla persona che sorveglia.',
    shareAsRevokeTitle: 'Revocare il link alla lavagna delle squadre?',
    shareAsRevokeBody: 'L’indirizzo smetterà di funzionare. Chi ha la tabella aperta non può più '
      + 'inserire nulla. Un nuovo link può essere creato in qualsiasi momento – sarà un altro '
      + 'indirizzo.',
    linksCount: '{done} di {n} fatti',
    linksOpen: 'Apri',
    linksMarkDone: 'Segna {title} come fatto',
    linksMarkOpen: 'Segna {title} di nuovo come aperto',
    linksDoneAt: 'fatto · {at}',
    linksOpened: '{title} aperto.',
    linksOpenedAction: 'Fatto',
    linksOpenFailed: '{title} non è stato aperto – il browser ha bloccato la finestra.',
    toggleDetailedAudit: 'Prova di integrità dettagliata',
    toggleAuswertung: 'Analisi (interna)',
    krokiHead: 'Ritaglio dello schizzo',
    framingHint: 'Sposta e ingrandisci la mappa – verrà stampato esattamente questo ritaglio.',
    framingFollows: 'Segue la situazione',
    framingFollowOn: 'Il ritaglio cresce con la situazione. Spostando la mappa si disattiva.',
    framingOutside: '{n} fuori – tocca per adattare',
    framingLegend: 'Legenda',
    framingLegendEmpty: 'niente di etichettato nel ritaglio',
    framingLegendPending: 'si aggiorna al rilascio …',
    framingLegendMissing: '{n} senza numero – il disco non sta interamente sul foglio.',
    framingDiscOut: 'Non finirà nella legenda – il disco non sta interamente sul foglio.',
    controlHead: 'Controlli',
    controlOpen: '{n} in sospeso',
    pdfShort: 'PDF',
    controlHint: '1 nota',
    controlHints: '{n} note',
    controlOpenHead: 'In sospeso',
    plansPrintNone: 'I piani non vengono stampati – aggiungerli dal menu ▾ se necessario.',
    plansPrintAnnotated: '{n} piani annotati verranno stampati.',
    plansPrintAll: 'Tutti i piani verranno stampati.',
    missingTranscripts: '{n} voce/voci audio senza trascrizione – integra per il verbale.',
    fixTranscripts: 'Integra nel diario',
    stateNote: 'Stato: intero intervento fino alla creazione del rapporto ({at}).',

    sectionBericht: 'Rapporto e persone coinvolte',
    sectionZeiten: 'Orari',
    sectionNachbearbeitung: 'Rielaborazione',
    vehicleOrder: 'Ordine di partenza',
    einsatzplan: 'Piano d\'intervento',
    lehrenLabel: 'Insegnamenti / sicurezza',
    lehrenPlaceholder: 'Constatazioni, indicazioni di sicurezza (facoltativo)',
    toggleMittel: 'Materiale ({n})',
    logMetaChanged: 'Dati del rapporto: {fields}',
    metaValue: '{label} «{value}»',
    metaWritten: 'scritto',
    metaRewritten: 'rielaborato',
    metaCleared: 'svuotato',
    metaRueckmeldung: 'Riscontro alla centrale da {name} alle {t}',
    metaRueckmeldungTime: 'Riscontro alla centrale alle {t}',
    metaRueckmeldungName: 'Riscontro alla centrale da {name}',
    metaGeretteteNone: 'Salvati: nessuno',
    metaGeretteteNoneOff: 'Salvati: «nessuno» revocato',
    metaGerettete: 'Salvati: {value}',
    metaPartnerAdded: 'Organizzazione partner {org} aggiunta',
    metaPartnerRemoved: 'Organizzazione partner {org} rimossa',
    metaPartnerNote: 'Organizzazione partner {org} – osservazione: {note}',
    metaPartnerNoteCleared: 'Organizzazione partner {org} – annotazione rimossa',
    metaPartnerUnnamed: 'Organizzazione partner registrata',
    metaGruppe: 'Ora d\'allarme {gruppe}: {t}',
    metaGruppeCleared: 'Ora d\'allarme {gruppe} svuotata',
    metaFahrzeugAus: '{fahrzeug} partito {t}',
    metaFahrzeugVorOrt: '{fahrzeug} sul posto {t}',
    metaFahrzeugZurueck: '{fahrzeug} rientrato {t}',
    metaFahrzeugCleared: '{fahrzeug}: ora svuotata',
    metaMittelNoneOn: 'Materiale: «nessuno utilizzato» confermato',
    metaMittelNoneOff: 'Materiale: «nessuno utilizzato» revocato',
    metaNoneOn: '{label}: non applicabile',
    metaNoneOff: '{label}: «non applicabile» revocato',
    unresolvedHours: '{names}: gli orari sono invertiti o mancano – non nelle ore d\'intervento.',
    pendingMedia: '{n} foto/audio non ancora caricati – verranno aggiunti appena c\'è una connessione; forse non ancora visibili su altri dispositivi.',
    pendingMediaConfirm: '{n} foto/audio non ancora caricati – restano su questo dispositivo',
    truppsDeployedConfirm: 'Ancora in servizio: {n} – mai annunciate uscite',
  },
}
