// Italian copy · tactical symbol names, search aliases and categories.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/symbols.ts.

import type { Copy, Localizable } from '../index'

export const symbolsCopy: Localizable<Pick<Copy, 'symbolNames' | 'symbolAliases' | 'symbolCategories'>> = {
  // Etichette di VISUALIZZAZIONE dei simboli tattici, indicizzate per nome FireGIS grezzo.
  // L'identità memorizzata resta il nome grezzo; solo l'etichetta viene tradotta.
  symbolNames: {
    'VKF Feuer': 'Incendio',
    'VKF Rettungen': 'Salvataggio',
    'VKF Unfall': 'Incidente',
    'VKF Gefaehrliche Stoffe': 'Sostanze pericolose',
    'VKF Wasser': 'Acqua',
    'FW Gefahr allgemein': 'Pericolo',
    'FW Gefahr Tafel': 'Targa di pericolo',
    'FW Gefahr Radioaktiv': 'Radioattivo',
    'FW Gefahr Ex': 'Esplosione',
    'FW Gefahr G': 'Gas',
    'FW Gefahr C': 'Chimico',
    'FW Gefahr W': 'Acqua',
    'FW Elektroanlage': 'Impianto elettrico',
    'VKF Patientensammelstelle': 'Punto di raccolta feriti',
    'VKF Sanitaetshilfsstelle': 'Posto di soccorso sanitario',
    'VKF Totensammelstelle': 'Punto di raccolta deceduti',
    'VKF Sammelstelle': 'Illesi',
    'FW Sammelplatz': 'Punto di raccolta',
    'FW Warteraum': 'Area di attesa',
    'FW Verwundetennest': 'Nido feriti',
    'VKF Bereich Sanitaet': 'Sanitario',
    'VKF KP Front': 'KP Front',
    'VKF Einsatzleiter': 'Capo intervento',
    'FW Offizier': 'Ufficiale',
    'VKF Kontrollposten': 'Posto di controllo',
    'VKF Informationszentrum': 'Centro informazioni',
    'VKF Bereich Materialdepot': 'Deposito materiale',
    'FW Absperrung': 'Sbarramento',
    'VKF Verkehrssperre ueberwacht': 'Blocco stradale',
    'VKF Drehleiter': 'Autoscala',
    'VKF Hubretter': 'Autopiattaforma',
    'VKF Fahrzeug': 'Veicolo',
    'VKF Pumpe Typ2': 'Pompa',
    'VKF Helilandeplatz': 'Area atterraggio elicottero',
    'VKF Luefter mobil': 'Ventilatore',
    'FW Entrauchung': 'Evacuazione fumi',
    'FW Kleinloeschgeraet': 'Piccolo estintore',
    'FW Sprungretter': 'Cuscino di salvataggio',
    'FW Leiter': 'Scala',
    'SI Ueberflurhydrant': 'Idrante soprasuolo',
    'SI Unterflurhydrant': 'Idrante sottosuolo',
    'VKF Innenhydrant': 'Idrante interno',
    'SI Wasserloeschposten': 'Posto di estinzione',
    'WV Loeschweier': 'Vasca antincendio',
    'SI Wasserbezugsort': 'Punto di prelievo acqua',
    'SI Wasserdruckversorgung': 'Alimentazione idrica in pressione',
    'GB Lift': 'Ascensore',
    'GB Kamin': 'Camino',
    'GB Abzug': 'Sfiato',
    'SI Schieber': 'Saracinesca',
    'GB Elektrotableau': 'Quadro elettrico',
    'GB Sprinklerzentrale': 'Centrale sprinkler',
    'GB Brandmeldezentrale': 'Centrale rilevazione incendi',
    'GB BMA Melder': 'Rivelatore d’incendio',
    'GB BMA-Z': 'Cartello centrale incendi (BMA-Z)',
    'GB RWA-BS': 'Cartello evacuatore fumo (RWA-BS)',
    'FW AED': 'DAE / Defibrillatore',
    'GB Fernsignaltableau': 'Quadro segnalazione a distanza',
    'GB Schluesseldepot': 'Deposito chiavi',
    'GB BA Wand F30': 'Parete F30',
    'GB BA Wand F60': 'Parete F60',
    'GB BA Wand F180': 'Parete F180',
    'GB Ture BS R30': 'Porta R30',
    'GB Ture Durchgang': 'Passaggio',
    'GB Treppe 8': 'Scala',
    'SI Nordpfeil': 'Freccia nord',
    'FKS Schluesselstelle': 'Punto chiave',
    'FKS Beobachtungsposten': 'Posto di osservazione',
    'FKS Helikopter': 'Elicottero',
    'FKS Drohnenlandeplatz': 'Area atterraggio droni',
    'FKS Forst': 'Servizio forestale',
    'ZS Fahrzeugplatz': 'Parco veicoli',
    'ZS Angehoerigensammelstelle': 'Punto raccolta familiari',
    'ZS Verpflegungsabgabestelle': 'Vettovagliamento',
    'ZS Betriebsstoffabgabestelle': 'Rifornimento',
    'ZS Dekontaminationsstelle': 'Punto di decontaminazione',
    'SI Windrichtung': 'Direzione del vento',
    'VKF Bereich Polizei': 'Polizia',
    'VKF Bereich Chemiewehr': 'Intervento chimico',
    'VKF Bereich Zivilschutz': 'Protezione civile',
    'VKF Bereich Feuerwehr': 'Pompieri',

    'VKF Rauch': 'Fumo',
    'FW Boot': 'Barca',
    'FW Tauchpumpe': 'Pompa sommergibile',
    'FW Wassersauger': 'Aspiraliquidi',
  },
  // Intestazioni di categoria della palette, indicizzate per chiave di categoria tedesca.
  symbolCategories: {
    'Schadenlage': 'Situazione danni',
    'Gefahren': 'Pericoli',
    'Gebäude': 'Edificio',
    'Wasser': 'Acqua',
    'Führung': 'Comando',
    'Personen / Sanität': 'Persone / Sanitario',
    'Partner': 'Partner',
  },
  symbolAliases: {
    'VKF Feuer': ['incendio', 'fuoco', 'focolaio', 'fiamme', 'Brand', 'Brandherd', 'Flammen'],
    'VKF Rettungen': ['salvataggio', 'evacuazione', 'persone', 'Personenrettung', 'Menschenrettung', 'Evakuierung'],
    'VKF Unfall': ['incidente', 'incidente stradale', 'collisione', 'Verkehrsunfall', 'Kollision'],
    'VKF Gefaehrliche Stoffe': ['sostanze pericolose', 'merci pericolose', 'chimico', 'olio', 'fuoriuscita', 'NBCR', 'Gefahrgut', 'ABC', 'Chemie', 'Öl', 'Oel', 'Austritt', 'Hazmat'],
    'VKF Wasser': ['danno d’acqua', 'inondazione', 'perdita', 'Wasserschaden', 'Hochwasser', 'Leck'],
    'FW Gefahr Ex': ['rischio d’esplosione', 'detonazione', 'Explosionsgefahr', 'Detonation'],
    'FW Beschaedigung': ['danno', 'danneggiato', 'Schaden', 'beschädigt'],
    'FW Teilzerstoerung': ['distruzione parziale', 'macerie', 'Zerstörung', 'Trümmer'],
    'FW Totalzerstoerung': ['distruzione totale', 'crollo', 'macerie', 'Zerstörung', 'Einsturz', 'Trümmer'],
    'FW Ueberschwemmung': ['inondazione', 'alluvione', 'danno d’acqua', 'Hochwasser', 'Flut', 'Wasserschaden'],
    'FW Gefahr Tafel': ['numero ONU', 'ADR', 'pannello arancione', 'Kemler', 'tabella di pericolo', 'UN', 'UN-Nummer', 'ADR', 'Gefahrgut', 'Kemler', 'orange Tafel', 'Warntafel', 'Hazmat'],
    'FW Gefahr allgemein': ['attenzione', 'avvertimento', 'zona di pericolo', 'Achtung', 'Warnung', 'Gefahrenstelle'],
    'FW Gefahr G': ['gas', 'condotta del gas', 'gas naturale', 'propano', 'Gasleitung', 'Erdgas', 'Propan', 'Explosionsgefahr'],
    'FW Gefahr C': ['prodotti chimici', 'acido', 'base', 'sostanza pericolosa', 'Chemikalien', 'Säure', 'Lauge', 'Gefahrstoff'],
    'FW Gefahr Radioaktiv': ['radiazione', 'radioattivo', 'nucleare', 'Strahlung', 'atomar', 'nuklear', 'A-Gefahr'],
    'FW Gefahr W': ['pericolo per le acque', 'corso d’acqua', 'protezione delle acque', 'Wassergefahr', 'Gewässer', 'Gewässerschutz'],
    'FW Elektroanlage': ['elettricità', 'corrente', 'tensione', 'alta tensione', 'Strom', 'Spannung', 'Hochspannung', 'Elektrizität'],
    'VKF KP Front': ['posto comando', 'PC fronte', 'condotta', 'Kommandoposten', 'Einsatzleitung', 'Führungsstandort'],
    'VKF Einsatzleiter': ['capo intervento', 'CI', 'Einsatzleitung', 'EL'],
    'FW Offizier': ['ufficiale', 'quadro', 'Kader', 'Führung'],
    'FW Sammelplatz': ['punto di raccolta', 'ritrovo', 'Treffpunkt', 'Besammlung'],
    'FW Warteraum': ['zona d’attesa', 'zona di attestamento', 'Bereitstellungsraum', 'Bereitstellung'],
    'VKF Kontrollposten': ['posto di controllo', 'controllo', 'varco', 'Checkpoint', 'Kontrolle', 'Verkehrsposten', 'Pforte'],
    'VKF Informationszentrum': ['informazione', 'media', 'stampa', 'Info', 'Medien', 'Auskunft', 'Mediensammelstelle'],
    'VKF Bereich Materialdepot': ['materiale', 'deposito', 'magazzino', 'Material', 'Depot', 'Lager'],
    'FW Absperrung': ['sbarramento', 'barriera', 'nastro', 'zona interdetta', 'Sperre', 'Barriere', 'Absperrband', 'Sperrzone'],
    'VKF Verkehrssperre ueberwacht': ['chiusura stradale', 'blocco stradale', 'presidiato', 'sorvegliato', 'Strassensperre', 'Absperrung', 'Sperre', 'bewacht', 'Bewachung', 'Überwachung'],
    'VKF Fahrzeug': ['veicolo', 'automezzo', 'autobotte', 'camion', 'Auto', 'TLF', 'Tanklöschfahrzeug', 'Einsatzfahrzeug', 'Lastwagen'],
    'VKF Drehleiter': ['autoscala', 'scala girevole', 'ADL', 'Autodrehleiter', 'Leiterfahrzeug'],
    'VKF Luefter mobil': ['ventilatore', 'ventilazione', 'Ventilator', 'Belüftung', 'Druckbelüfter'],
    'FW Kleinloeschgeraet': ['estintore', 'coperta antifiamma', 'Feuerlöscher', 'Handfeuerlöscher', 'Löschdecke'],
    'VKF Hubretter': ['piattaforma aerea', 'braccio elevatore', 'palo telescopico', 'Hebebühne', 'Teleskopmast'],
    'VKF Pumpe Typ2': ['motopompa', 'pompa', 'trasporto d’acqua', 'Motorspritze', 'Wassertransport', 'MS'],
    'FW Tauchpumpe': ['pompa sommergibile', 'pompa', 'cantina', 'acqua', 'Pumpe', 'Keller', 'Wasser', 'TP', 'Lenzpumpe'],
    'FW Wassersauger': ['aspiraliquidi', 'aspiratore', 'aspirazione', 'Sauger', 'Nasssauger', 'Wasser', 'WS'],
    'VKF Helilandeplatz': ['elicottero', 'piazzola', 'atterraggio', 'Rega', 'Helikopter', 'Heli', 'Rega', 'Landeplatz'],
    'VKF Drohne': ['drone', 'UAV', 'ricognizione aerea', 'termica', 'Drone', 'UAV', 'Multicopter', 'Quadrocopter', 'Luftaufklärung', 'Wärmebild'],
    'FW Entrauchung': ['evacuazione fumi', 'estrazione fumi', 'Rauchabzug', 'Belüftung', 'Abluft'],
    'FW Sprungretter': ['cuscino di salvataggio', 'materasso di salvataggio', 'Sprungkissen', 'Sprungpolster', 'Rettungskissen'],
    'FW Leiter': ['scala', 'scala all’italiana', 'scala a ganci', 'Anstellleiter', 'Schiebleiter', 'Steckleiter'],
    'VKF Sammelstelle': ['punto di raccolta', 'illesi', 'sfollati', 'assistenza', 'Unverletztensammelstelle', 'Betreuung', 'Evakuierte'],
    'VKF Patientensammelstelle': ['punto raccolta feriti', 'triage', 'pazienti', 'Verletzte', 'Triage', 'Patienten'],
    'VKF Sanitaetshilfsstelle': ['posto sanitario', 'posto di soccorso', 'Verbandplatz', 'Sanposten', 'Sanhist'],
    'VKF Totensammelstelle': ['deposito salme', 'deceduti', 'Tote', 'Verstorbene'],
    'FW Verwundetennest': ['nido feriti', 'feriti', 'Verletzte', 'Verwundete'],
    'VKF Bereich Sanitaet': ['ambulanza', 'soccorso sanitario', 'sanitario', '144', 'Ambulanz', 'Rettungsdienst', '144'],
    'VKF Bereich Feuerwehr': ['pompieri', 'vigili del fuoco', '118', '118'],
    'VKF Bereich Polizei': ['polizia', '117', '117', 'Kantonspolizei'],
    'VKF Bereich Chemiewehr': ['difesa chimica', 'NBCR', 'ABC-Wehr', 'Chemikalien'],
    'VKF Bereich Zivilschutz': ['protezione civile', 'PCi', 'ZS', 'Bevölkerungsschutz'],
    'SI Ueberflurhydrant': ['idrante', 'idrante soprasuolo', 'presa d’acqua', 'Wasserbezug'],
    'SI Unterflurhydrant': ['idrante sottosuolo', 'presa d’acqua', 'Wasserbezug'],
    'VKF Innenhydrant': ['idrante interno', 'colonna montante', 'Steigleitung', 'Wandhydrant'],
    'SI Wasserloeschposten': ['posto antincendio', 'attacco interno', 'Innenangriff'],
    'WV Loeschweier': ['stagno', 'bacino', 'riserva d’acqua', 'Weiher', 'Teich', 'Reservoir', 'Löschwasserreserve'],
    'SI Wasserbezugsort': ['punto d’acqua', 'aspirazione', 'fiume', 'lago', 'Saugstelle', 'Fluss', 'Bach', 'See'],
    'SI Wasserdruckversorgung': ['alimentazione in pressione', 'condotta in pressione', 'serbatoio', 'Druckleitung', 'Reservoir'],
    'GB BA Wand F30': ['compartimento tagliafuoco', 'muro tagliafuoco', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F60': ['compartimento tagliafuoco', 'muro tagliafuoco', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB BA Wand F180': ['compartimento tagliafuoco', 'muro tagliafuoco', 'Brandabschnitt', 'Brandmauer', 'Brandschutzwand'],
    'GB Ture BS R30': ['porta tagliafuoco', 'porta', 'Brandschutztüre', 'Brandschutztür', 'Tür'],
    'GB Ture Durchgang': ['porta', 'entrata', 'accesso', 'Tür', 'Eingang', 'Zugang'],
    'GB Lift': ['ascensore', 'montacarichi', 'Aufzug', 'Fahrstuhl', 'Warenlift'],
    'GB Kamin': ['camino', 'canna fumaria', 'Cheminée', 'Schornstein', 'Abgas'],
    'GB Abzug': ['estrazione', 'ventilazione', 'canale', 'Lüftung', 'Ventilation', 'Abluft'],
    'SI Schieber': ['saracinesca', 'valvola d’arresto', 'valvola del gas', 'Absperrschieber', 'Ventil', 'Gasschieber'],
    'GB Elektrotableau': ['quadro elettrico', 'scatola dei fusibili', 'interruttore principale', 'Sicherungskasten', 'Verteiler', 'Strom', 'Hauptschalter'],
    'GB Sprinklerzentrale': ['sprinkler', 'centrale sprinkler', 'impianto di spegnimento', 'Sprinkler', 'Löschanlage'],
    'GB Brandmeldezentrale': ['centrale di rivelazione incendi', 'quadro di segnalazione', 'BMA', 'BMZ', 'Brandmeldeanlage', 'Alarmzentrale'],
    'GB BMA Melder': ['rivelatore', 'rivelatore di fumo', 'pulsante manuale', 'zona', 'Melder', 'Brandmelder', 'Rauchmelder', 'Meldergruppe', 'Handfeuermelder'],
    'GB BMA-Z': ['cartello centrale incendi', 'BMA', 'BMZ', 'targa', 'Brandmeldezentrale', 'Brandmeldeanlage'],
    'GB RWA-BS': ['evacuatore fumo e calore', 'RWA', 'comando evacuatore', 'targa', 'Rauch- und Wärmeabzug', 'Bedienstelle'],
    'FW AED': ['defibrillatore', 'DAE', 'rianimazione', 'arresto cardiaco'],
    'GB Fernsignaltableau': ['pannello di ripetizione', 'ripetitore d’allarme', 'Brandmeldeanlage', 'Signaltableau'],
    'GB Schluesseldepot': ['deposito chiavi', 'cassetta chiavi pompieri', 'Schlüsselrohr', 'Feuerwehrschlüsseldepot'],
    'GB Treppe 8': ['scala', 'vano scala', 'Treppenhaus', 'Stiege', 'Aufgang'],
    'SI Windrichtung': ['vento', 'direzione del vento', 'manica a vento', 'meteo', 'Wind', 'Windsack', 'Wetter'],
    'SI Nordpfeil': ['nord', 'bussola', 'orientamento', 'Norden', 'Kompass', 'Orientierung'],
    'FKS Schluesselstelle': ['punto chiave', 'passaggio', 'Schlüsselstelle'],
    'FKS Beobachtungsposten': ['osservazione', 'vedetta', 'Beobachtungsposten'],
    'FKS Helikopter': ['elicottero', 'eli', 'Helikopter'],
    'FKS Drohnenlandeplatz': ['drone', 'atterraggio', 'Drohne', 'Landeplatz'],
    'FKS Forst': ['forestale', 'bosco', 'Forst', 'Waldbrand'],
    'ZS Fahrzeugplatz': ['veicoli', 'parco', 'Fahrzeugplatz'],
    'ZS Angehoerigensammelstelle': ['familiari', 'parenti', 'Angehörige'],
    'ZS Verpflegungsabgabestelle': ['vettovagliamento', 'cibo', 'Verpflegung'],
    'ZS Betriebsstoffabgabestelle': ['carburante', 'benzina', 'Tankstelle', 'Treibstoff'],
    'ZS Dekontaminationsstelle': ['decontaminazione', 'decon', 'Dekontamination'],
  },
}
