// Italian copy · the Plan whiteboard, notes and entities.
// One slice of the `it` overlay, assembled in ../it.ts; the German base is ../de/whiteboard.ts.

import type { Copy, Localizable } from '../index'

export const whiteboardCopy: Localizable<Pick<Copy, 'incidents' | 'entities' | 'notes' | 'whiteboard' | 'tafel'>> = {
  incidents: {
    migratedTitle: 'Stato di lavoro migrato',
    geojsonNotJson: 'File JSON non valido.',
    geojsonNotFc: 'Non è una FeatureCollection GeoJSON.',
    geojsonNotWgs84: 'Le coordinate sembrano LV95, non WGS84 [lng, lat]. Riproiettare prima in EPSG:4326.',
  },
  entities: {
    noteSubtitle: 'Nota',
    fallbackObjectName: 'Oggetto',
  },
  notes: {
    section: 'Nota',
    content: 'Testo',
    size: 'Dimensione',
    sizeS: 'Piccolo',
    sizeM: 'Normale',
    sizeL: 'Grande',
    look: 'Aspetto',
    lookPill: 'Foglietto',
    lookPlain: 'Testo semplice',
    color: 'Colore',
    done: 'Fatto',
    deleteTitle: 'Rimuovere la nota?',
    deleteMsg: 'Questa nota contiene del testo. Rimuoverla davvero?',
  },
  whiteboard: {
    fit: 'Adatta',
    pan: 'Selezione',
    team: 'Squadra',
    draw: 'Disegna',
    text: 'Nota',
    symbol: 'Simbolo',
    line: 'Linea',
    area: 'Superficie',
    dockHints: {
      draw: 'Trascina sul piano per disegnare liberamente. Colore, spessore e stile si scelgono poi nell’editor.',
      line: 'Tocca i vertici. Doppio tocco o «Fatto» chiude la linea. Colore, spessore e stile si scelgono poi nell’editor.',
      lineFreeShort: 'Trascina il dito sul piano',
      lineNodesShort: 'Tocca i punti – ✓ chiude la linea',
      areaFreeShort: 'Traccia il contorno con il dito',
      areaNodesShort: 'Tocca almeno 3 vertici – ✓ chiude',
      area: 'Tocca i vertici (almeno 3). Doppio tocco o «Fatto» chiude la superficie.',
      circle: 'Trascina dal centro verso il bordo per impostare il raggio. Raggio, colore e riempimento si regolano poi nell’editor – in metri reali una volta calibrata la scala.',
      text: 'Tocca il piano per inserire una nota.',
      resource: 'Tocca il piano per posizionare una squadra. Trascina per spostarla.',
      scale: 'Tocca i due estremi della scala stampata, poi inserisci la lunghezza reale. Dopodiché le linee con «Lunghezza» mostrano metri reali.',
      measure: 'Tocca i punti sul piano. «Distanza» mostra la distanza, «Superficie» l’area + perimetro – in metri reali una volta calibrata la scala. Trascina i punti per spostarli, tieni premuto un punto per rimuoverlo.',
    },
    scale: {
      tool: 'Scala',
      promptTitle: 'Imposta la scala',
      promptBody: 'Lunghezza reale della distanza rilevata (es. la barra di scala):',
      unit: 'm',
      confirm: 'Applica',
      cancel: 'Annulla',
      chipCalibrated: 'rif. {m} m',
      chipAuto: 'rif. auto',
      chipAutoHint: 'rif. automatico – scala ricavata dal collegamento alla mappa',
      chipAutoStackHint: 'rif. automatico – scala ricavata dalla pianta dell’edificio',
      chipUncalibrated: 'non calibrata',
      recalibrate: 'Ricalibra',
      calibrate: 'Calibra la scala',
      calibrateHint: 'Tocca due punti della barra di scala',
      stale: 'ricontrolla la scala',
      saved: 'Scala calibrata ({m} m di riferimento)',
      needsCalibration: 'Imposta la scala: tocca i due estremi della barra di scala',
      needsCalibrationViewer: 'Per misurare serve prima una scala calibrata',

      persistTitle: 'Memorizzare la scala?',
      saveAll: 'Per tutti i piani',
      saveThis: 'Solo questo piano',
      savedAll: 'Salvata come scala predefinita',
      savedThis: 'Scala salvata per questo piano',
      saveFailed: 'Salvataggio della scala non riuscito',
    },
    georef: {
      chipUnlinked: 'Collega alla mappa',
      chipLinked: 'collegato',
      chipTwoPoints: 'da 2 punti',
      chipResidual: '⌀ {m} m',
      linkTitle: 'Collega questo piano alla mappa',
      openQuality: 'Verifica e correggi il riferimento',
      freeOrderTap: 'Tocca lo stesso punto su modulo e mappa',
      freeOrderTip: 'Meglio punti inequivocabili – spigolo, idrante, incrocio. L’ordine è libero: le metà poste trovano da sole la loro controparte.',
      freeOrderPlace: 'Agisce sulla superficie visibile – mappa o modulo, ordine libero',
      moveMap: 'Sposta il punto {n} – tocca il nuovo punto sulla mappa, il vecchio sparisce.',
      movePlan: 'Sposta il punto {n} – tocca il nuovo punto sul modulo, il vecchio sparisce.',
      title: 'Collega alla mappa',
      barOpen: '{n} in attesa',
      sideProgress: 'Mappa {map} · Modulo {plan}',
      statusOpenMap: 'Il punto {n} manca ancora sulla mappa.',
      statusOpenPlan: 'Il punto {n} manca ancora sul modulo.',
      statusOpenMapMany: '{k} punti mancano ancora sulla mappa.',
      statusOpenPlanMany: '{k} punti mancano ancora sul modulo.',
      statusOpenBoth: 'Punti aperti su mappa e modulo – i punti uguali si abbinano automaticamente.',
      statusSelected: 'Punto {n} selezionato – tocca accanto per deselezionare.',
      cancel: 'Annulla',
      closeMode: 'Chiudi',
      done: 'Fatto',
      placePoint: 'Imposta punto',
      targetOutside: 'Sposta prima il mirino sulla superficie visibile',
      checkFit: 'Verifica la sovrapposizione',
      checkOpacity: 'Visibilità della sovrapposizione del modulo',
      checkMap: 'Mappa',
      checkPlan: 'Modulo',
      autoStart: 'Allinea automaticamente',
      autoStartSub: 'Verifica la proposta sulla mappa, poi conferma',
      autoManual: 'Imposta i punti manualmente',
      autoManualSub: 'Tocca lo stesso punto sul modulo e sulla mappa – ordine libero',
      autoBusy: 'Allineamento automatico in corso…',
      autoStepRender: 'Rendering del piano',
      autoStepOsm: 'Caricamento degli edifici',
      autoStepMatch: 'Confronto degli edifici',
      autoNone: 'Nessuna proposta affidabile trovata – imposta i punti manualmente',
      autoNoScale: 'Scala del piano non riconosciuta – calibra prima o imposta i punti manualmente',
      autoFailed: 'Allineamento automatico non riuscito',
      autoUnavailable: 'L’allineamento automatico non è configurato su questo server',
      proposalHead: 'Allineato automaticamente',
      proposalSub: 'Confronta i bordi degli edifici, poi conferma',
      proposalCheckHead: 'Verifica la sovrapposizione',
      proposalCheckSub: 'Gli edifici coincidono solo in parte – confronta attentamente, regola se necessario',
      proposalAdjustHead: 'Regola il piano',
      proposalAdjustSub: 'Sposta o ruota finché i bordi degli edifici combaciano.',
      adjust: 'Regola',
      accept: 'Conferma',
      discard: 'Scarta',
      restore: 'Ripristina la proposta',
      planSize: 'Dimensione del piano',
      sizeSmaller: 'Riduci il piano dell’1 per cento',
      sizeBigger: 'Ingrandisci il piano dell’1 per cento',
      undoNudge: 'Annulla l’ultima regolazione',
      rotateGrip: 'Ruota',
      hintMove: 'Trascinando si sposta il piano',
      hintRotate: 'Trascinando si ruota il piano attorno al centro',
      acceptedToast: 'Allineamento confermato',
      crossTitle: 'Punto {n} – trascina per spostare, tocca per le opzioni',
      pendingCrossTitle: 'Punto {n} aperto – trascina per spostare, tocca per le opzioni',
      pointN: 'Punto {n}',
      popMove: 'Sposta',
      popKeep: 'Mantieni',
      popResidual: 'scarto {m} m',
      popOpen: 'aperto',
      popPairHint: 'Per abbinare, tocca il punto aperto sull’altra superficie',
      detailsTitle: 'Dettagli della corrispondenza',
      saveFailed: 'Salvataggio del collegamento non riuscito',
      qualityTitle: 'Corrispondenza',
      pairs: 'Coppie',
      qualityDeviation: 'Scarto ⌀ {m} m',
      warnTwoPoints: 'Due coppie si risolvono esattamente – solo un terzo punto mostra quanto sia davvero buona la corrispondenza.',
      warnCollinear: 'Imposta il punto successivo fuori dalla linea – quelli attuali sono quasi allineati e trasversalmente la posizione è indeterminata.',
      warnBaseline: 'Imposta il punto successivo più lontano – i punti distano solo {m} m, distanze maggiori rendono la corrispondenza più stabile.',
      lampNoneHead: 'Ancora nessun collegamento',
      lampNoneBody: 'Due punti posano il piano sulla mappa.',
      lampOneHead: '1 punto impostato',
      lampOneBody: 'Il secondo posa il piano sulla mappa.',
      lampTwoHead: '2 punti – esatto, ma non verificato',
      lampGoodHead: '{n} punti · ⌀ {m} m',
      lampGoodBody: 'Abbastanza preciso per rispecchiare i simboli tra piano e mappa.',
      addThird: 'Imposta un terzo punto',
      lampAutoHead: 'Allineato automaticamente',
      lampApprovedHead: 'Approvato dalla stazione',
      lampApprovedBody: 'La stazione ha verificato la sovrapposizione e approvato questo adattamento.',
      chipAuto: 'non misurato',
      warnAuto: 'Imposta punti di riferimento per misurare l’adattamento – finora vale solo la verifica visiva.',
      autoAddPoints: 'Imposta punti di riferimento',
      autoOneHead: 'Allineato automaticamente · 1 punto',
      autoOneBody: 'Un secondo punto sostituisce l’allineamento automatico con riferimenti reali.',
      autoOnePoint: '1 punto',
      openDroppedOne: 'Punto aperto scartato – un punto di riferimento richiede entrambe le superfici',
      openDroppedMany: '{k} punti aperti scartati – un punto di riferimento richiede entrambe le superfici',
      addMore: 'Aggiungi punti',
      transfer: 'Trasferisci',
      transferTitle: 'Copia la corrispondenza',
      transferBody: 'I punti di riferimento di {source} vengono copiati. Ogni modulo può poi essere regolato separatamente.',
      transferLinked: 'già collegato',
      transferCompleted: 'copiato',
      transferReplaceTitle: 'Sostituire la corrispondenza di {target}?',
      transferReplaceBody: 'I punti di riferimento esistenti di {target} vengono sostituiti dalla corrispondenza di {source}.',
      transferDone: 'Corrispondenza copiata su {target} – verificare lì la sovrapposizione',
      reset: 'Reimposta',
      resetTitle: 'Reimpostare il riferimento?',
      resetBody: 'Il collegamento tra questo piano e la mappa viene eliminato. I punti dovranno essere impostati di nuovo.',
      resetDone: 'Riferimento reimpostato',
      clearPoints: 'Reimposta',
      clearTitle: 'Reimpostare tutti i punti?',
      clearBody: 'I punti impostati vengono eliminati e con essi il collegamento tra questo piano e la mappa. Si ricomincia da capo.',
      removePoint: 'Elimina punto',
      layerGroupPlans: 'Piani',
      layerPlanImage: 'Piano ({plan})',
      twinFromMap: '{name} – rispecchiato dalla mappa. Tocca per i dati, trascina per spostare l’originale.',
      twinUnnamed: 'Simbolo',
    },
    finishShape: 'Fatto',
    cancelShape: 'Annulla',
    insertVertex: 'Inserisci punto',
    dragVertex: 'Trascina il vertice · tenere premuto per eliminare',
    dragRadius: 'Trascina il raggio',
    groupDeleteTitle: 'Rimuovi selezione',
    groupDeleted: 'Selezione rimossa',
    placeText: 'Nota posizionata sul piano',
    placeSymbol: 'Simbolo «{name}» posizionato sul piano',
    placeLine: 'Linea disegnata sul piano',
    placeArea: 'Superficie disegnata sul piano',
    placeCircle: 'Perimetro di sicurezza disegnato sul piano',
    placeTeam: '{name} posizionato sul piano',
    selectTrupp: 'Quale squadra?',
    newTeam: 'Nuova squadra',
    showTrupp: 'Mostra in Squadre',
    markPosition: 'Segna posizione',
    positionMarked: '{name}: posizione segnata',
    removeMarker: 'Rimuovi marcatore',
    removeMarkerTrail: 'Rimuovi marcatore e traccia',
    clearTrail: 'Rimuovi traccia',
    clearTrailConfirm: 'Rimuovere tutte le {n} posizioni segnate di {name}? La traccia sparisce da carta e piano.',
    trailCleared: '{name}: traccia rimossa',
    trails: 'Tracce',
    trailsOn: 'Mostra tracce',
    trailsOff: 'Nascondi tracce',
    ghostTrail: 'Traccia {name}',
    ghostTrailHint: 'Traccia di {name} – il marcatore è stato rimosso',
    ghostTrailTitle: 'Traccia di {name}',
    ghostTrailAsk: 'Il marcatore è stato rimosso, la sua traccia è rimasta. Riposizionare la squadra alla fine della traccia – o rimuovere la traccia?',
    ghostTrailRestore: 'Riposiziona la squadra',
    ghostTrailRestored: '{name} riposizionata – traccia ripresa',
    teamNameTaken: '{name} è già assegnato – il nome resta',
    textPlaceholder: 'Nota ...',
    blankHint: 'Foglio bianco – annota con linea, superficie, nota, simbolo o squadra',
    osmLoading: 'Caricamento sagome degli edifici …',
    osmError: 'Sagome degli edifici (OSM) non raggiungibili',
    osmEmpty: 'Nessun edificio in questa zona',
    osmRetry: 'Riprova',
    osmPickHint: 'Tocca un edificio, poi applica',
    osmPickHintReplace: 'Tocca un edificio, poi applica – sostituisce l’edificio esistente',
    osmPickHintAmend: 'L’edificio esistente è evidenziato – tocca altri per aggiungerli, poi applica',
    osmPickHintHere: 'L’edificio sul luogo d’intervento è evidenziato – controlla, poi applica.',
    osmPickMissing: 'Qui mancano sagome dell’edificio esistente ({n}) – andranno perse applicando.',
    osmTransfer: 'Applica ({n})',
    osmClear: 'Svuota la selezione',
    addFloorUp: 'Aggiungi piano superiore',
    noFloorPlan: 'Nessuna planimetria del piano',
    stairTo: 'Continua verso {floor}',
    stairFrom: 'Da {floor}',
    climbUp: 'Continua un piano più in alto',
    climbDown: 'Continua un piano più in basso',
    climbBack: 'Torna a {floor}',
    addFloorDown: 'Aggiungi piano inferiore',
    floorAddedToast: '{floor} aggiunto',
    floorHide: 'Nascondi piano',
    floorHideShort: 'Nascondi',
    floorMenu: '{name}: nascondi o rimuovi',
    floorShow: 'mostra',
    floorHidden: 'nascosto',
    removeFloor: 'Rimuovi piano',
    removeFloorConfirm: '{floor}: {n} contrassegni di questo piano verranno rimossi o accorciati. Rimuovere comunque il piano?',
    removeFloorConfirmOne: '{floor}: 1 contrassegno di questo piano verrà rimosso o accorciato. Rimuovere comunque il piano?',
    floorRemoved: 'Piano rimosso',
    floorRemovedLog: 'Piano {floor} rimosso',
    floorRemovedLogMarks: 'Piano {floor} rimosso – {n} contrassegni rimossi o accorciati',
    floorRestoredLog: 'Piano {floor} ripristinato',
    floorAddedLog: 'Piano {floor} aggiunto',
    floorAdded: 'Piano aggiunto',
    buildingReplaced: 'Edificio sostituito',
    buildingReplacedMarks: 'Edificio sostituito – {n} contrassegni rimossi',
    buildingReplacedKept: 'Edificio cambiato – piani mantenuti',
    buildingReplacedCarried: 'Edificio cambiato – {n} contrassegni trasferiti',
    buildingReplacedCarriedDropped: 'Edificio cambiato – {n} trasferiti, {d} rimossi',
    buildingTaken: 'Edificio adottato',
    replaceBuilding: 'Scegli un altro edificio',
    replaceBuildingConfirm: 'La pila di piani attuale viene scartata e sostituita dalla nuova sagoma.',
    replaceBuildingConfirmMarks: 'Sui piani ci sono {n} contrassegni. Sono ancorati alla sagoma attuale e non possono essere trasferiti a un’altra – verranno rimossi. «Annulla» nell’avviso li ripristina.',
    replaceBuildingConfirmKeep: 'La nuova sagoma prende il posto di quella attuale. I piani restano.',
    replaceBuildingConfirmCarry: 'La nuova sagoma prende il posto di quella attuale. I piani restano e {n} contrassegni vengono trasferiti – mantengono la loro posizione sul terreno.',
    replaceBuildingConfirmCarryDrop: '{n} contrassegni vengono trasferiti sulla nuova sagoma e mantengono la loro posizione sul terreno. {d} non vi rientrano più e vengono rimossi. «Annulla» nell’avviso ripristina tutto.',
    backToBuilding: 'Torna all’edificio',
    railBuilding: 'Edificio',
    otherObject: 'Altro oggetto',
    objectLabel: 'Oggetto',
    objectNone: 'Nessun oggetto',
    objectIs: 'Oggetto: {name}',
    objectSwitch: 'Oggetto: {name} – scegli un altro oggetto',
    objectSwitchShort: 'Scegli un altro oggetto',
    objectNearby: '{name} · a {distance}',
    objectNearbyLabel: 'Oggetto più vicino a {distance} – non l’indirizzo dell’intervento',
    nearbyBannerTitle: 'Oggetto più vicino, non l’indirizzo dell’intervento.',
    nearbyBannerBody: 'Intervento: {incident} · piano: {object} ({distance}).',
    nearbyBannerNoAddress: 'senza indirizzo',
    objectActive: 'Piani di «{name}»',
    objectReset: 'Reimposta al prossimo oggetto',
    objectSwitchConfirmTitle: 'Carica un altro oggetto',
    objectSwitchConfirm: 'I piani di tutti i moduli passeranno a «{name}». Cambiare l’oggetto attuale?',
    objectSwitchConfirmCta: 'Carica oggetto',
    northLabel: 'N',
    northTitle: 'Direzione nord – edificio ruotato sull’asse maggiore',
    orientAsDrawn: 'Come disegnato',
    northUnknownTitle: 'Nord sconosciuto – piano non collegato alla mappa',
    orientNorthUp: 'Nord in alto',
    orientLongAxis: 'Ruota sull’asse maggiore',
    orientMenuTitle: 'Ruota l’edificio',
    orientSliderLabel: 'Rotazione',

    groupDeletedN: '{n} oggetti rimossi dal piano',
    truppPlacedHere: 'già qui',
  },
  tafel: {
    templateTitle: 'Modello',
    plakatName: 'Primo cartellone (CSSP)',
    plakat: {
      heading: 'Prima condotta',
      prefilled: 'precompilato dall’intervento',
      title: 'Intervento',
      address: 'Indirizzo',
      alarm: 'Allarme',
      el: 'Capo intervento',
      problems: 'Rilevamento dei problemi',
      front: 'Fronte',
      ordnung: 'Ordine',
      sanitaet: 'Sanitario',
      spezial: 'Problemi speciali',
      massnahmen: 'Misure',
      mittel: 'Mezzi',
      verbindungen: 'Collegamenti',
      absprachen: 'Punti da concordare',
      was: 'Cosa / dove',
      wer: 'Chi',
      wann: 'Quando',
      formation: 'Formazione',
      pers: 'Pers.',
      wo: 'Dove',
      funktion: 'Funzione / posizione',
      kanal: 'Canale',
      ruf: 'Nominativo / tel.',
      newProblem: 'Problema …',
      newRow: 'Nuova riga …',
      note: 'Parola chiave',
      trendNone: 'Tendenza aperta',
      trendUp: 'peggiora',
      trendSame: 'stabile',
      trendDown: 'migliora',
      trendTitle: 'Tendenza: {trend} – tocca per cambiare',
      done: 'Fatto',
      weatherTag: 'Meteo',
      wind: 'Vento {dir} {speed} km/h',
      absprachenDefaults: ['Posizione della direzione d’intervento', 'Accesso / asse di salvataggio', 'Zona d’attesa', 'Punto di raccolta pazienti', 'Approvvigionamento idrico', 'Sbarramento'],
      inserted: 'Primo cartellone inserito',
      edited: 'Cartellone modificato',
      remove: 'Rimuovi cartellone',
      removeTitle: 'Rimuovere il cartellone?',
      removeMsg: 'Tutto ciò che è scritto sul cartellone se ne va con esso. Annulla lo riporta.',
      removed: 'Cartellone rimosso',
      reportTitle: 'Prima condotta (cartellone)',
    },
  },
}
